---
title: "약물 치료의 혜택"
subtitle: Benefit of pharmacotherapy
bibliography: References/03-01.bib
---

## 약물 치료를 둘러싼 비판과 정신과 의사의 역할

### 생물학적 환원주의

오늘날 정신의학은 모든 정신질환을 <s>생물-심리-사회 모형</s>[^1]으로 이해한다. 조현병 역시 예외가 아니며, 생물학적 이상이 근간이 되더라도 심리적, 사회적 상황과 계기가 발병의 주요한 원인으로 간주되며, 증상의 심각도, 경과나 예후 역시 심리, 사회적 상황에 따라 크게 좌우된다.

[^1]: **생물-심리-사회 모델(Biopsychosocial model)**: 인간의 건강과 질병, 그리고 정상적 발달과정을 생물학, 심리학 및 사회 환경 요인 간의 상호 연결을 통해 이해하려는 학제 간 모델이다. 신체와 정신의 이원론을 배격하고, 신체가 정신에 영향을 끼치는 것 뿐 아니라, 심리와 사회 환경 역시 생물학적 영향을 미칠 수 있다고 주장한다. 이 이론은 1977년 George Engel과 Jon Romano에 의해, 의생물학적 질병 모델에 치우쳐진 연구풍토를 바로잡고자 고안되었다. 이후 의학적 치료에 있어 전인적 접근(holistic approach)이 강조되는 이론적 출발점이 되었다.

정신의학의 태동기에는 오히려 생물이 빠진 심리사회적 모형이 대세였다. 생물학적 지식이 미천하였기 때문에, 심리내적 갈등과 의사소통의 제약, 사회적 모순 등이 중점적으로 연구되었다. 이 때문에 정신분석과 같은 학문 영역은 주류 의학과 분리되었으며 독자적인 길을 모색해왔다. 그러던 와중 20세기 중반 정신약물학이 태동하였고, 정신의학은 주류 의학으로의 복귀를 위해 안간힘을 썼다. DSM-III의 발간은 이를 공공연히 선언하는 사건이었다.[@Pasnau1987-cp]

현대 정신의학은 생물학적 모형에 치중하고 있으며, 표면적으로 생물심리사회적 기치를 내걸고 있다 하더라도 현실적으로는 심리사회적 접근을 타 학제 전문가(심리학, 사회복지학 등)에게 위탁하고 있다. 자연스레 정신보건 서비스에 다양한 시각과 입장들이 참여하게 되었고, 기본 시각이 서로 다르다보니 치료 방향이 제각각일 뿐 아니라 타 학제가 행하는 치료에 대한 불신과 폄하가 만연하게 되었다.[@Fulford2004-ao] 정신과 의사는 상이한 입장과 시각들을 종합하고 반목을 조정하는 최상의 적임자라고 할 수 있음에도, 어째서인지 점점 더 생물학적 모형에 안주하면서 스스로의 역할을 축소시키고 있다.[@Olfson1997-kr]

현대의 정신의학이 비판받는 주된 이유는, 지나치게 <s>생물학적 환원주의</s>[^2]에 의지한다는 것이다. 인문/사회계열의 전문가들은 환원주의 프로젝트는 절대로 성공할 수 없으며, 오히려 인간을 자신의 마음으로부터 소외시킬 것이라 경고하였다.[@Ruther2014-pn] 설령 정신 현상을 생물학적 기반을 통해 설명할 수 있다 하더라도, 무엇이 정상이고 무엇이 비정상이라는 구분 자체가 사회의 합의를 통한 인위적 규범이기 때문에 그 생물학적 기반은 찾을 수 없다는 것이다.[@Stier2013-hl]

[^2]: **생물학적 환원주의 (biological reductionism)**: 개개 인간의 심리나 행동, 나아가 사회 전반적 현상을 생물학적 요인의 결과로 해석하려는 학문적 경향. 예들 들어 성격, 동기, 감정, 반복된 행동 패턴 등이 유전자, 신경전달물질, 호르몬에 의해 결정된다고 주장한다. 타 학문으로부터 거센 비판을 받는 편인데, 특히 사회생물학과 진화심리학은 가열찬 논란을 불러 일으킬만한 이론들을 거듭 내놓고 있다. 예를 들어 Richard Dawkins나 Edward Wilson같은 학자들은 인간의 공격성, 성적 행동, 이타주의, 종교 등은 오로지 유전자의 생존과 증식이라는 근본적 목적에 봉사하기 위해서 등장하였다고 말한다.

### 판단 중지 {#sec-stop-judgement}

약물 치료 역시 동일한 이유로 비판받는다. 조현병을 생물학적 시각으로 충분히 설명할 수 없다면 약물 치료의 의의는 무엇인가? 일단 조현병 환자만을 치료의 대상으로 삼는 것은 옳은가? 평범과 다른 사람들을 편견에 찬 시각으로 배척하는 사회 자체가 치료의 대상이 되는 것은 아닌가? 정신병적 증상은 그 자체로서 소멸되어야 할 악인가? 종교적 신비체험이나 광신적 믿음은 숭앙하면서, 환자들의 망상은 어떻게든 없애려 하는 것이 정당화될 수 있는가? 약물 치료의 장기적 부작용이 점점 더 우려의 대상이 되면서, 모든 희생을 감내해서라도 약물을 사용해야 하는 이유가 무엇인지에 대해 비판과 자성의 목소리가 높아져만 간다.

이러한 비판을 던지는 것은 타 분야의 전문가들 뿐 아니라 환자들 역시 마찬가지이다. 항정신병 약물을 거부할 법적 권리가 개인의 자기결정권과 밀접하게 연결되어 있는 만큼, 환자들은 약물 치료를 억압적 수단이라 여기며 낮은 병식과 어우러져 흔히 투약 거부로 이어진다.[^3] 이런 상황에서 약물 치료의 필요성에 대한 확고한 증거가 쌓이고, 든든한 철학적 근거가 마련되지 않으면 점점 더 조현병의 약물 치료는 뒤로 후퇴할 수 밖에 없다.

[^3]: 미국인 Eleanor Riese는 25세에 조현병 진단을 받았으며, 이후 20년 동안 정신병동에 수차례 입퇴원을 반복하였다. 그녀는 44살이던 1989년 입원하고 있던 St. Mary's Hospital에 대하여, 본인이 동의하지 않았는데 강제로 항정신병 약물을 투여받는 바람에 회복이 어려운 배뇨 장애를 앓게 되었다면서 고소하였다. 이 사건을 두고 치열한 법정 다툼 끝에, 샌프란시스코 법원은 설령 위험한 상태에 놓여 강제입원을 당했다 할지라도 환자는 약물 투여를 거부할 권리가 있다고 판결하였다. 이 사건은 이후 정신증 환자에 대한 강제투약 관행에 제동을 걸게 되었으며, 2017년 *"55 계단(55 steps)"*라는 제목으로 영화화되었다.

후설이 "현상학을 수립하기 위해서 일차적으로 이루어져야 할 작업은 [사태 자체로(zu den Sachen selbst)]{.underline} 돌아가는 것!"이라고 외친 것처럼, 의학이든, 심리학이든, 철학이든 모두 각자의 학문적 선입견에서 벗어나 일단 판단을 중지하는 것이 필요하다. <s>판단 중지</s>[^4]를 통해 전제나 편견을 배제하고, 타 분야의 시각이 무엇인지를 이해하고자 하며, 사태 그 자체로서의 조현병의 경험적 현상을 살핌으로써 좀 더 모순없는 구조를 구축할 수 있을 것이다. 이를 통해 다양한 치료들이 통합한, 새로운 서비스 모형을 만들 수 있을 것이며 약물 치료의 역할 역시 그 모형 안에서 굳건한 자리를 차지할 수 있을 것이다.[@Fulford2004-ao]

[^4]: **판단 중지(*epoché*)**: 고대 그리스의 철학자 피론과 그 추종자들이 사용했던 용어. 논리적 비판이 처음의 목적을 상실하고, 비판을 위한 비판으로 흐를 때 일단 멈춘다는 의미이다. 후설은 이를 현상학에 적용하여, 사물에 대해 기존의 관점, 선입견, 습관적 이해를 배제하고 직관해보자는 의미로 사용했다.

### 사회 환경의 변화와 시대적 흐름

명칭이란 어떤 현상을 바라보는 당대의 시각을 반영하기도 하고, 새로운 시각의 변화를 유도하기도 한다. 크레펠린이 처음 사용한 [조발성 치매(dementia praecox)]{.underline}라는 이름은 지극히 절망적이고 비관적인 인상을 불러일으켰기 때문에, 곧바로 블로일러가 제안한 [정신분열병(schizophrenia)]{.underline}으로 대체되었다. 이를 통해 치매의 이미지에서는 벗어났지만, 정신분열병이라는 용어는 질병이 전적으로 [개인 내부에서 일어나는 사건]{.underline}임을 시사한다. 이에 비해 [조현병(attunement disorder)]{.underline}이라는 명칭이 환기하는 것은, 이 병은 개인이 스스로의 셀프와 맺는 관계, 나아가 상호주관적 세계에서 타자와 맺는 관계가 무너져내리는 상태라는 것이다. 따라서 조현병은 개인 내부에만 국한되거나, 망가진 기능을 고치거나 대체하면 금방 회복되는 그런 단순한 질환이 아니다. 이러한 시각의 변화와 함께, 성공적인 치료란 증상으로 인한 제약에도 불구하고 [사회 속에서 의미 있는 삶을 추구할 수 있도록 돕는 것]{.underline}이라는 개념이 좀더 중요해졌다.

같은 맥락에서 조현병 치료의 최종 목표 역시, 원인의 제거나 병적 과정이 진행되는 것을 막는 것에서 <s>회복탄력성</s>[^5]을 증대시키는 쪽으로 전환되고 있다.[@Izydorczyk2019-hb] 비정형 항정신병 약물 도입 이후, 약물의 효과를 판정하는 기준이 과거의 양성 증상 경감에서, 음성/인지 증상 경감으로 확대되었고, 개인적/사회적 기능 회복이 추가되기도 했지만, 여전히 비정상적인 부분을 최소화한다는 수동적 입장에서 벗어나지 못하고 있다. 이에 대한 대안으로 방어력과 회복력을 최대화하는 적극적 입장으로 전환해야 한다는 목소리가 등장하고 있다. 이는 비정상 심리현상만을 연구하던 심리학이 긍정 심리 쪽으로 연구 방향을 틀고 있는 것과 같은 맥락에 놓여있다.[@Jeste2017-wf]

[^5]: **회복탄력성(resilience)**: 크고 작은 다양한 역경과 시련, 실패의 경험을 오히려 도약의 발판으로 삼아 더욱 성장하는 능력과 자질을 의미한다. 부정적 상황에 대한 긍정적 적응력이라 할 수 있다. 1970년대에 이 용어를 처음 사용한 Emmy Werner는 지극히 가난하고 부모의 보살핌을 받지 못하는 아이들을 추적관찰하고 있었다. 이중 상당수는 비행 청소년이 되거나 어른이 되어서도 실직, 약물 남용 등 부정적인 행동 패턴을 보였으나, 소수의 아이들은 성숙하고 배려심많은 어른으로 성장하였고, 이들은 남다른 회복탄력성을 지녔다고 간주되었다. 이 이론은 주로 아동발달과 관련해서 연구되었고, 조현병 부모를 둔 아동의 성장과정과 관련해서도 많은 연구가 행해졌다. 현재는 아동발달 뿐 아니라, 역경을 디디고 일어나는 성인의 경험에도 적용되고 있다.

치료의 주도권이 점점 환자 쪽으로 이동하고 있다는 것 역시 간과할 수 없는 시대적 흐름이다. 환자 기본권에 대한 강조, 치료에 대한 기대 변화라는 외부로부터의 압력과, 치료 결정 과정에 환자가 적극적으로 참여할수록 치료 성과가 높아진다는 증거에 의해, [공유된 의사 결정(shared decision-making)]{.underline}이 점점 강조되고 있다.[@Beitinger2014-qm] 법적인 면에서도 치료를 거부할 권리, 원하는 치료를 선택할 수 있는 자기결정권이, 누구도 침해할 수 없는 권리로 받아들여지고 있다. 환자들의 입장에서는 항정신병 약물 치료가 자신을 향해 행해지는 폭력이라고 경험하기 마련이다. 완치에 대한 기약도 없이 오로지 주변 사람에게 피해를 주지 않기 위해, 온갖 부작용을 감내하면서 오늘도 약을 먹고 있는 것이라고 느낀다. 이런 인식이 변화될 정도로, 약물 치료가 발전되지 않는다면 낮은 순응도를 탓할 수만은 없을 것이다. 거듭 개정되고 있는 정신보건법 역시 정신질환자의 자기결정권을 다른 가치들보다 우선시하고 있으며, 이에 따라 약물 치료의 입지 역시 점점 좁아지고 있다.

결국 약물 치료는, 정신사회적 치료, 신체와 심리적 건강의 관리, 대처 전략의 다양화 및 회복탄력성의 증대, 사회적 편견의 최소화 및 지역사회로의 통합 등 다양한 전략들이 어우러지는 통합적 치료의 한 부분일 뿐이다. 정신과 의사는 환자에 대한 책임을 넘겨받은 사람으로서, 심리학자, 사회복지사, 공공기관, 다른 과의 의사 등으로 구성된 다학제적 치료진의 협력과 조화를 이끌어내어야 한다. 그런 와중에서도 성공적인 치료가 행해지기 위해선, 정신병리학이 중심에 있음을 잊지 말아야 한다. 정확한 진단을 위해, 고통 받는 개인의 경험을 이해하기 위해, 치료적 동맹(therapeutic alliance)을 맺고 개별화된 치료를 적용함으로써 목표에 도달하기 위해, 공감과 이해를 무기로 하는 정신병리학적 접근이 필수적이다. 무엇보다도 고통받고 있는 환자에게는 자신의 정신내적 세계를 탐색하는 과정의 길잡이가 필요하기 때문이다.

## 약물 치료가 가져오는 혜택

### 치료 효과의 근거

항정신병 약물 치료의 가장 두드러진 효과는 급성 증상 특히 양성 증상과 폭력/흥분 증상의 감소이다. 약물을 사용하기 시작해서 짧게는 며칠, 길게는 몇 주 사이에 양성 증상이 반응을 보이며, 대부분 강제입원의 사유가 해소될 정도까지는 회복된다. 비록 위약을 투여한 대조군에서도 ⅓ 가량의 환자들이 저절로 회복되곤 하지만, 여전히 약물 복용 환자군은 통계적으로 유의하게 높은 반응률을 보인다.[@Haddad2018-ey] 단적인 예로, 클로르프로마진이 도입되기 전, 정신과 병동에 입원하게 된 조현병 환자들은 수년 이상 아니 수십년이라도 병동에 갇혀 있을 수 밖에 없었다. 약물이 도입된 후에야 비로소 탈원화 운동이 가능해질 수 있었다는 것은 항정신병 약물의 효력을 간접적으로 증명해준다.

급성 증상에 대한 효과가 논란의 여지가 없는 것에 비해, 문제가 되는 것은 장기복용의 효과이다. 수많은 연구를 통해 증명된 것은 약물을 꾸준히 복용하면 재발율이 현저히 감소된다는 것이다. 1년 까지 수집된 자료를 분석한 고전적인 연구에 따르면 약물을 중단하고 6개월 내에 재발하는 비율은 평균 52%에 이르며, 이에 비해 유지치료를 지속한 군은 16%에 지나지 않았다.[@Gilbert1995-cl] 재발방지는 주요 정신질환의 치료에 있어서 포기할 수 없는 중요한 목표이다. 조현병을 비롯한 대부분의 주요 정신질환은 재발이 반복될수록 증세가 심해지고, 삽화의 기간이 길어지며, 치료에 대한 반응이 좋지 않다.[@takeuchi2019] 게다가 재발이 반복될수록 뇌 실질이 위축되고 뇌 손상의 정도가 심해진다는 증거가 있다.[@Andreasen2013-zq] 과거에 비해 인격이 황폐화된 조현병 환자의 수가 줄어들고 있다는 것은, 그만큼 약물 치료가 널리 보급되면서 개개 환자의 재발 횟수를 다소나마 줄이고 있기 때문이라고 생각되고 있다.[@Templer1982-zx]

그러나 어떤 정신과 의사도, 항정신병 약물을 충분히 오래 먹으면 조현병이 완치(cure)된다고 이야기하지 못한다. 현실적으로 단 한번의 정신병적 삽화만으로는 조현병이라고 진단하기 어렵기 때문에, 평생 단일 삽화만 경험하는 조현병 환자의 비율은 알려져 있지 않다. 대신 조현병 스펙트럼 질환의 경우, 평생 재발하지 않았던 경우는 약 15% 정도에 불과하다.[@Rosen2005-eh] 한번이라도 재발하여 조현병 진단이 확인된 후에는 이미 완치는 불가능하다는 것이 보편적인 견해이다. 다만 증상이 잘 조절되어 기능적으로 문제가 없는 경우를 회복(recovery)이라 정하는데, 이 비율 역시 13.5% 정도에 불과하다.[@Jaaskelainen2013-ow] 평생 유지 치료를 지속한다 해도 완치의 희망이 희박하다면, 장기 치료의 의미는 어디에서 찾을 수 있을까?

유지 치료에 대한 부정적인 시각 역시 수긍할 부분이 없지 않다. 논란을 불러일으킨 것은 네덜란드에서 행해진 초발 조현병 환자 추적 연구였다. 추적 초기 18개월 까지는 중도에 약을 끊은 환자군에서 훨씬 높은 재발률을 보였고, 불과 22%의 환자만이 성공적으로 약을 끊을 수 있었다.[@wunderink2007] 반면 동일한 코호트를 7년후에 재추적 조사한 결과, 오히려 유지치료를 지속한 군에 비해 중도에 약을 끊은 환자군에서, 병전 기능을 회복한 환자의 비율이 두 배 이상 높았다.[@wunderink2013] 유지 치료를 비판하는 학자들은 설령 유지 치료를 통해 재발 횟수를 줄일 수는 있다 해도, 장기간 약물 사용에 의한 인지적 부작용 등으로 오히려 기능상의 회복을 막는다고 주장한다.[@Moncrieff2015-ac] 해묵은 득과 실에 대한 논란이 여기서도 결론이 나지 않은 채 이어지고 있다.

말할 것도 없이 반대되는 증거 역시 부족하지 않다. 유지 치료를 지속하면 재발률이 낮아진다는 것은 명백하고, 더 나아가 기능 수준이나 삶의 질도 나아진다는 증거가 있다. 중국에서 행해진 14년간의 추적 조사에서 관해상태를 유지한 환자의 비율은 치료받지 않은 군에서는 16.4%에 그친 반면, 치료군에서는 34.1%로 두 배 이상이었다.[@Ran2015-eu] 핀란드에서 행해진 1996년부터 2014년 까지의 국가 통계를 분석한 연구에서, 초발 정신증 환자가 관해 후 얼마나 오래 투약을 지속했느냐와, 이후의 재입원율, 사망률 등으로 집계한 예후는 반비례 관계에 있었다. 첫번째 삽화 이후 1-5년의 유지치료를 행한 후에는 일단 중단해본다는 임상적 관행과는 달리, 5년이 지난 후에도 일단 약을 끊으면 예후가 점점 불량해졌다.[@tiihonen2018]

### 장기 투여의 부정적 측면과 반론

항정신병 약물의 장기적 효과에 대해 의구심이 드는 것은 당연하다. 약물의 효과를 판정하는 임상 시험은 거의 대부분 18주 이내의 단기 연구이고, 재발 방지 효과를 탐색하는 장기 연구도 기껏해야 1년 정도에 불과하다. 그 이상의 연구는 관찰 연구이거나 데이터베이스를 이용하는 연구로, 증거중심의학에서 요구하는 엄격한 증거에 미달한다. 적극적으로 재발을 막으면 뇌 손상이나 인지기능의 손실을 최소화할 수 있다고는 하지만, 아직 장기적인 연구자료가 충분히 축적된 것은 아니며 어쩌면 의사들의 희망에 지나지 않을 지도 모른다. 오히려 장기간의 약물 투여는 구조적, 기능적 뇌손상을 일으키고, 궁극적인 예후나 삶의 질에 악영향을 끼치고 있을 지도 모른다. 약물 반대론자들은 수십년 전부터 이런 부정적인 측면에 주목해왔으며, 다방면의 연구와 홍보를 통해 경각심을 불러일으켜왔다.[^6]

[^6]: 대표적인 약물 반대론자는 미국의 사이언톨로지교(scientology)를 신봉하는 자들이다. 이들의 중심교리와 정신질환이 직접적 관계는 없지만, 창시자인 L. Ron Hubbard는 초창기부터 정신의학을 부정하고, 약물치료를 거세게 반대하고 있다. 저널리스트인 Robert Whitaker는 "Mad in America", "Anatomy of an Epidemic"과 같은 영향력 있는 저서를 통해 약물치료가 보편화되면서 오히려 정신질환의 유병률을 높이고, 환자들의 회복을 방해하고 있다고 주장한다.

언제부터인가 약물 치료를 지지하는 측과 반대하는 측의 다툼은 엄밀한 과학적 논쟁이라기 보다는 이데올로기 싸움으로 변질되는 듯 하다. 과격한 비판자들은 항정신병 약물 뿐 아니라 모든 종류의 향정신성 의약품은 장기적으로 보았을 때 이득보다 피해가 더 심각하며, 당장 사용이 중단되어야 한다고 소리 높여 외친다.[@Gotzsche2015-vl] 환자 입장에 선 권익단체와 인권 옹호자들, 푸코([섹션 @sec-before-kraepelin])와 <s>랭</s>[^7] 등의 철학을 사상의 토대로 삼는 반정신의학자 들 역시, 항정신병 약물의 한계를 파고 들면서 약물을 사용하는 것은 비윤리적, 반인권적 행위일 뿐이라고 강변한다. 2017년 <s>Lieberman</s>[^8]을 위시한 일군의 명망있는 정신과 의사들은 유지 치료를 둘러싼 소모적인 논쟁에 종지부를 찍기 위해 마치 성명서와도 같은 논문을 발표하였다.[@Goff2017-ey] 이 논문은 항정신병 약물의 장기 사용을 둘러싼 다양한 논점들을 비교적 객관적으로 평가하려고 애썼기 때문에, 본서에서도 저자들의 관점에 기초하여 주요 이슈들에 대해 정리해보고자 한다.

[^7]: **Ronald David Laing (1927\~1989)**: 영국의 정신과 의사. 조현병은 개념일 뿐 사실이 아니라고 주장하였으며, 정신질환이 생물학적 이유때문에 일어난다는 전제 자체를 부인하였다. 정신질환이 생물학적 근거가 없는 이상, 약물 치료를 비롯한 생물학적 치료는 환자를 이해하지 못한다는 것을 숨기기 위한 눈가림일 뿐이라 하였다. 반정신의학의 이론적 지주로 여겨지지만 스스로는 그렇게 불리우길 거부하였다.

[^8]: **Jeffrey Alan Lieberman (1948\~)**: 미국 컬럼비아 대학의 정신과 교수. 조현병 임상 시험에 있어서 많은 경험과 업적을 쌓았다. 그의 명성은 Clinical Antipsychotic Trials of Intervention Effectiveness (CATIE) 연구를 성공적으로 이끌면서 높아졌다.

#### 초기 항정신병 약물 치료가 장기적 예후에 미치는 영향

초기의 약물 치료가 효과적이라는 증거는 분명하며, 그 효과 크기(effect size)는 0.51 정도로, 보편적 신체 질환에서 약물 치료를 했을 때 얻어지는 효과 크기와 비교하여 결코 적지 않다.[@Leucht2012-lh] 아무런 치료를 하지 않아도 저절로 회복되는 비율이 15% 정도는 되기 때문에, 심리사회적 치료만으로 충분한 효과를 볼 수 있다는 주장은 강력한 증거라고 보기 어렵다. 낙관적 결과들도 선택 편향, 진단의 불분명, 높은 중도 탈락률 때문에 해석하기 어렵다.

반면 초기 약물 치료가 장기적으로 먼 훗날, 예후에 악영향을 미친다는 주장[@wunderink2013] 역시 엄격한 증거로 보기에는 미약하다. 장기간의 효과를 조사하는 연구의 공통적 문제점은 엄격한 연구에 필요한 통제 상태를 장기간 유지할 수 없다는 것이다. 자연히 자연적 연구(naturalistic study)에 의지할 수 밖에 없는데, 자연적 연구에서는 교란 변수의 효과는 물론 [선택 편향(selection bias)]{.underline}을 해결할 수 없다. 예를 들어 대부분의 연구에서 약물 치료를 하지 않은 군의 중도 탈락 비율이 약물 유지군에 비해 현저히 높기 때문에, 약물 치료를 하지 않은 군에서 연구 종료 시점까지 탈락하지 않고 남아있는 환자들은 애초에 예후가 좋은 환자들이었을 것이라는 점이다. 이러한 선택 편향 문제는 모든 장기 추적 조사의 결과를 온전히 신뢰할 수 없게 만든다.

초기 약물 치료가 장기 예후에 악영향을 미친다는 증거는 미비한 반면, 초기에 치료 기회를 놓치면 장기 예후가 불량하다는 증거는 풍부한 편이다. [치료받지 않은 정신병적 기간(duration of untreated psychosis)]{.underline}은 급성 시기가 지난 후의 잔여 정신증상 및 기능 손실과 양의 상관관계를 보이며, 이는 다른 교란변수들의 영향을 보정한 후에도 유의하게 유지되었다.[@Penttila2014-uy] 비록 치료받지 않은 정신병적 기간 동안 비가역적 뇌손상이 일어나는지 여부는 알 수 없지만, 조기정신증(early psychosis)에 좀더 관심을 가지고, 될 수 있는 한 빨리 약물 치료를 시행하면 만성화와 황폐화를 조금이라도 줄일 수 있음은 분명해보인다.[@Murru2018-qf; @Albert2019-us]

#### 만성 유지 치료가 장기적 예후에 미치는 영향

Harrow 등[@Harrow2014-sp] 139명의 초발 정신증 환자를 대상으로 이후 20년간의 경과를 추적하였다. 이중 2/3은 꾸준히 약물 치료를 시행하였고, 1/3은 약물을 복용하지 않았다. 예상과 달리 꾸준히 약물을 복용한 군의 70% 가까이는 20년이 지난 후에도 여전히 정신병적 증상을 보이고 있었으며, 약물을 복용하지 않은 군에서는 8% 만이 증상을 보였다. 동일 저자는 약물을 쓰지 않고도 재발을 겪지 않았던 환자들의 특성을 조사하였는데, 이들은 높은 병전기능, 무난한 인격과 긍정적 태도, 그리고 높은 회복탄력성을 보였다.[@Harrow2007-lp] 이러한 결과는 표면적으로는 마치 유지 치료가 예후를 나쁘게 만드는 것같은 인상을 주나, 앞절에서도 언급했듯이 유사한 연구들에 내재할 수 없는 한계를 잘 드러내준다. 실제 임상에서 증상이 뚜렷하지 않거나 기능 손상이 적은 환자가 장기간 유지 치료를 받는 일은 예외적이다. 즉 예후가 좋기 때문에 약물 치료를 안 한 것이지, 약물 치료를 안 해서 예후가 좋아졌다고 보기는 어렵다.

애초에 논란을 일으켰던 Wulderlink의 연구[@wunderink2013] 역시 이러한 비판에서 자유롭지 못하다. 2013년의 연구에서는 급성기 치료 후 무작위로 약물 지속군과 중단군으로 나눠서 비교했던 2007년 연구[@wunderink2007]와 동일한 코호트를 추후 추적관찰했다고 했으나, 1단계 연구가 끝나고 그 후 5년 동안의 약물 사용 여부는 무작위 배정이 아니라 그때그때 상황에 맞추어 이루어졌다. 연구자들은 약물 유지군과 중단군이 뚜렷이 구분되는 것처럼 묘사했지만, 추적 마지막 2년 동안 두 군에 투여된 항정신병 약물의 평균 용량은 할로페리돌 환산용량으로 4.0mg/일과 2.8mg/일로 사실상 큰 차이가 없었다.

그러나 이러한 연구 결과들을 전적으로 무시할 수는 없다. 유지 치료를 통한 재발 방지와 부작용으로 인한 삶의 질 저하 간의 밸런스를 유지하는 것은 생각보다 까다로우며, 믿고 의지할만한 증거도 별로 없는 편이다. 다만 유지 치료를 위한 약물 용량은 될 수 있으면 줄여야 하나, 표준 치료 용량의 50% 이하가 되면 재발율이 급격히 높아진다는 것이 전문가들의 중론이다.[@uchida2011]

#### 항정신병 약물과 뇌 손상

조현병 환자의 뇌 용적이 정상에 비해 작다는 것은 거듭 확인된 바이지만, 그것이 약물 때문이라는 견해 또한 만만치 않다. 18,000명 이상의 자료에 대한 메타 분석에서 뇌 용적의 감소는 투여 약물 농도 및 치료받지 않은 정신병적 기간과 양의 상관관계를 보였다.[@nakajima2013] 그러나 이 역시 증상이 심했기 때문에 고용량의 약물을 사용했을 것이라 짐작해 본다면, 인과관계의 방향을 결정하기 어렵다. 반면 항정신병 약물이 도입되기 전에도 뇌 용적 감소는 흔히 발견되는 현상이었으며, 약물 치료를 중단한 후에도 재발 횟수와 비례하여 뇌 용적 감소가 멈추지 않고 진행된다고 한다.[@Boonstra2011-an] 약물과 뇌 용적 감소에 대한 가장 영향력 있는 논문인 Ho 등[@ho2011]의 논문에서, 복용한 항정신병 약물의 갯수나 용량은 용적 감소의 정도와 유의한 상관관계를 보였다. 비록 저자는 정신증상의 심각도와 용량 사이에는 약한 상관관계 밖에 보이지 않았다고 주장하고 있으나, 이런 종류의 연구가 의례 그러하듯, 질병의 영향과 약물의 영향을 분리해낼 수는 없었다. 최근에 발표되는 연구들은, 조현병 환자의 뇌는 정상대조군에 비하여 지속적으로 용적이 감소되며, 이 과정에 약물이 미치는 영향력은 미미할 뿐이라고 보고 있다.[@Lawrie2018-my; @Barth2020-al]

한편 항정신병 약물에 비판적인 사람들은, 장기간의 약물 사용이 뇌 용적 감소와 함께 인지 기능 저하를 일으켜, 결국 삶의 질을 망가뜨린다고 주장한다. 그러나 조현병으로 인한 인지 기능 저하는 약물 사용 전에도 이미 뚜렷하며, 오히려 약물 치료로 조금은 호전되는 양상을 보인다. 더군다나 뇌 용적 감소가 반드시 인지 기능 저하를 일으키는 지도 확인되지 않았다. 약물 치료 후 임상 양상이나 인지 증상이 좋아졌음에도 불구하고, 회백질의 부분적 소실이 여전히 진행되는 경우도 있다.[@Ahmed2015-bb]

동물을 대상으로 한 연구에서도 확실한 결론이 나지 않았다. 원숭이를 대상으로 한 연구에서, 18-24개월 약물을 투여해보니, 대조군에 비해 확실히 뇌의 용적 감소가 두드려졌다. 그러나 주목할 점은 용적 감소의 원인이 신경세포의 수가 줄어들었기 때문이 아니라, 성상세포(astrycyte)가 개수가 줄고 신경돌기의 다발인 신경그물(neuropil, 4장 참조)의 용적이 줄었기 때문이었다는 점이다. 즉 동물 실험에서 항정신병 약물이 신경세포 자체에 독성을 띤다는 증거는 발견되지 않은 셈이다.[@Konopaske2007-bm; @Vernon2011-uj]

#### 도파민 수용체 민감화 현상

혹자는 도파민 수용체 차단제를 오래 사용하면 점점 [D~2~ 수용체의 민감화(sensitization)]{.underline}가 일어나 점점 더 높은 용량의 약물이 필요하게 되거나, 혹은 최대 용량을 써도 치료 효과를 거둘 수 없게 된다고 주장한다. 이는 과거에 고용량의 약물을 사용했던 환자일수록 위약으로 교체했을 때 재발률이 높았다는 관찰에서 비롯되었다.[@Prien1971-vp] 유사한 개념으로 Chouinard는 [과민감도 정신증(supersensitivity psychosis)]{.underline}이라는 가설을 제안하였다. 약물에 내성이 생기는 것처럼, 항정신병 약물에도 필요 용량이 점점 높아지며, 갑자기 끊었을 때 금단으로 인해 심한 재발을 일으킨다는 것이다.[@chouinard1980] 지연 운동 이상증과도 밀접한 관련이 있는 과민감도 정신증은 재발을 거듭할 수록 약물 반응이 좋지 않은 이유로 거론되곤 한다. Chouinard는 치료 저항성 환자의 약 70%는 도파민 수용체의 과민감화 때문인 것으로 추정하고 있다.[@Chouinard2017-za]

항정신병 약물을 갑자기 끊었을 때 급격히 재발하는 현상은 이미 오래전부터 잘 알려진 현상으로, 특히 클로자핀처럼 항콜린 효과가 강한 약물을 갑자기 끊었을 때 흔히 발생한다.[@moncrieff2006] 클로자핀을 끊었을 때 나타나는 금단 증상은 정신증의 재발 뿐 아니라, 불안, 불면, 안절부절함 등 벤조디아제핀 금단 시와 유사한 증상을 보이며, 심지어 섬망 상태를 일으키기조차 한다.[@Green2019-xp] 이러한 증상을 겪는 비율은 많게는 53%에 이르는데, 정신증의 재발과 구분하기 힘들지만 약물을 다시 사용하면 금새 안정화된다는 차이를 보인다.[@brandt2020] 따라서 항정신병 약물에 의한 [금단 정신증(withdrawal psychosis)]{.underline} 혹은 [반동성 정신증(rebound psychosis)]{.underline} 현상이 문제가 되는 것은 사실이지만, 이것이 도파민 과민화 때문인지는 분명하지 않으며 장기적 예후를 망가뜨리는 지도 확인되지 않았다.

항정신병 약물의 장기적 이득과 폐해에 대한 논쟁이 점점 이데올로기 싸움으로 변질되어 가는 것은, 위에서 살펴본 듯이 수십년의 경험이 축적되었음에도 여전히 모든 관계자가 납득할만한 증거가 발견되지 않았다는데 원인이 있다. 그도 그럴 것이 장기간의 추적 관찰은 연구 방법론 상의 한계때문에 믿을만 하지 못하며, 그렇다고 윤리적 문제때문에 장기간에 걸쳐 통제된 연구를 할 수도 없기 때문이다. 최근에는 국가가 관리하는 데이터베이스와 같은 빅데이터를 이용한 연구가 눈에 자주 띠고 있지만, 이 역시 그 동안의 치료 관행을 반영하는 것일 뿐 논쟁적 주제에 대해 확실한 답을 주진 않는다. 조현병 약물 치료의 역사는 지금까지 두 차례에 걸쳐 큰 희망과 낙관론에 고무된 적이 있다. 그 하나는 클로르프로마진이 처음 개발되었을 때요, 다른 하나는 비정형 항정신병 약물이 등장했을 때이다. 이미 그러한 긍정적 전망이 퇴색한 현재, 정신약물학자들은 엄격해진 의료 윤리와 향상되는 개인의 결정권, 전문가 집단을 불신하는 탈권위의 시대적 흐름 속에서, 점점 더 약물 치료의 당위성을 일반 대중에게 납득시키기 어려워지고 있다. 이러한 상황에서 단순히 "약물을 꾸준히 먹다보면 언젠가는 치료될 수 있을 겁니다"라는 성의없는 자세는 점점 더 설득력을 잃어가고 있다. 좀더 체계적이고 다면적으로 약물의 득과 실을 저울질 할 수 있는 역량이 필요할 때다.


## References {.unnumbered}
