---
title: "치료의 의미"
subtitle: Meaning of treatment
bibliography: References/03-01.bib
---

## 기술 정신병리학적 관점에서 바라보는 치료

### 약물이 치료할 수 있는 증상

약물 치료가 조현병 치료의 핵심이라고 해도, 약물 치료 만으로는 조현병을 이겨낼 수는 없다. 약물 치료와 더불어 심리적 지지, 가족치료, 인지행동치료, 재활치료, 사회적 지지체계 등이 모두 합목적적으로 어우러져야 환자 한 사람의 미래를 지킬 수 있다. 그렇다면 약물 치료가 효과적인, 혹은 약물 치료 밖에는 도움이 되지 않는 증상은 어떤 것일까?

일반적으로 정신 증상은 [내인성(endogenous)]{.underline}과 [외인성(exogenous)]{.underline}으로 나눌 수 있으며, 이중 내인성은 [기질성(organic)]{.underline}과 [심인성(psychogenic)]{.underline}으로 나뉜다. 문헌에 따라선 심인성 원인을 [기능성(functional)]{.underline} 원인과 동일한 것으로 서술하기도 한다.[@Bell2020-jj] 약물 치료는 생물학적 약리작용을 기분으로 하므로, 외인성 보다는 내인성, 심인성 보다는 기질성 질환에 효과적일 것이라 예상할 수 있다. 과거에는 조현병 환자 중에서도, 기질성 정신증과 심인성 정신증을 나눠서 생각하기도 하였고[^03-02-1], 뚜렷한 외적 요인이 없는 내인성 정신증을 기능성 질환으로 이해하기도 하였다. 그러나 연구가 거듭될수록 조현병이 기질성 뇌질환임을 부인할 수 없는 증거가 점점 늘어만 갔다. 이러한 변화는 조현병 외의 기타 질환에서도 마찬가지여서, 순전히 심인성이라 여겨졌던 질환들 역시 생물학적 변화를 동반한다는 것이 분명해졌다. 혹자는 기질성과 기능성의 구분은 더 이상 유효하지 않다고 주장한다.[@Kendler2012-lb]

[^03-02-1]: 블로일러는 이를 "physiogenic schizophrenia"와 "psychogenic schizophrenia"라 불렀다.[@Bleuler1930-jn]

어찌보면 하나의 질환을 단위로 하여 기질적/기능적 임을 구분하는 것은 의미가 없을 수 있다. 질환을 구성하는 다양한 증상 중 어떤 것은 좀더 기질적에 가까울 것이며, 다른 것들은 기능적(functional) 혹은 반응적(reactive)에 가까울 수 있다. 조현병의 병식에 대한 논란이 대표적인 사례이다. 병식 부재는 조현병의 대표적 증상이지만, 그것이 뇌 기능(특히 인지기능)의 저하 때문인지, 부정(denial)이라는 심리적 방어 혹은 사회적 편견에 대한 거부감 때문인지는 여전히 해결되지 않았다. 환청은 기질적 원인에 의해 생겼지만, 이에 반응하여 생긴 망상은 심리적 기전으로 설명할 수 있을 지도 모른다. 야스퍼스는 그 발생과정을 도저히 이해할 수 없는 일차적 정신증상을 <s>자생적</s>[^03-02-2]이라고 불렀다. 이를 구분하는 잣대는 역시 정상적 심리과정에 대한 이해가능 여부였다. [자생적 증상]{.underline} 다시 말하여 [이해 불가능한 증상]{.underline}은 기질적 원인에 더 가깝다고 말할 수 있다. 이에 비해, 정신병 후 우울증(postpsychotic depression)과 같이 2차적, 즉 정상 심리적 반응으로 설명할 수 있는 증상도 있을 것이다.[@mcglashan1976]

[^03-02-2]: **자생적(autochthonous)**: autochthonous라는 개념은 고대 그리이스에 유래하였으며, 외부에서 유입된 정착민에 대비하여 그 지역의 고유한 토착민을 지칭하였다. 또한 외부 문화나 혈통의 유입을 차단하고 고유한 부족성을 지키는 집단을 가리켰다. 생물지리학에서도 사람의 개입 없이 해당 지역에서 원래 나고 자라는 동식물을 의미한다. 의학에서는 전이된 병소가 아니라 원발병소를 의미한다. 야스퍼스는 매우 독특한 의미로 사용하였는데, 분명한 선행 이유없이 발생하는, 발생과정을 이해할 수 없는 망상을 자생적 망상이라 하였다.

### 기술 정신병리학적인 증상 이해

DSM은 내적 경험을 바탕으로 하는 증상 구분에는 별 중요성을 두지 않는다. 약물 치료를 할 지 여부는 해당되는 진단 기준의 개수, 혹은 사회적/직업적 기능의 손상 정도로 가늠하는 질병의 중증도에 따라 결정된다. 정신병 후 우울증을 보이는 환자의 증상이 심하여, 주요 우울증의 진단 기준을 만족시키게 되면 항우울제 치료가 필요하다고 여겨진다. 치료법의 효과를 판정하는 것도 투약과 증상 변화 간의 통계적 유의성을 기준으로 이루어진다. 이 경우 정신병리학적 내면 탐구는 불필요할 것이다.

이에 비해 전통적인 기술 정신병리학의 입장이라면, 여전히 내적 경험을 탐구하고 그런 증상에 이르게 된 정신과정을 재구성할 것이다. 이 과정에 대한 이해가능 여부에 따라 증상 각각에 대하여 기질성, 심인성 구분을 할 것이며, 전자에 대해선 약물 치료를 후자에 대해선 심리 치료를 고려할 것이다. 앞에서 든 정신병 후 우울증이라는 예에서, 만약 조현병 환자의 무기력과 우울감이, 심적 변화나 왜곡된 인지와 상관없고 오히려 음성 증상에 가깝다고 판단된다면 좀더 적극적인 약물 치료를 고려할 것이다. 그러나 병식의 회복과 더불어 찾아온 좌절/비관이라면 약물보다는 교육과 지지를 통해 해결하려고 할 것이다.

기술 정신병리학 특히 현상학적 정신병리학에서는, 일부 자생적 증상을 제외하고는, 어떤 사람이든 상황에 따라 경험할 수 있는 존재 양식으로 증상을 이해한다. 우울증이냐 조현병이냐는 의학 모델이 반드시 필요한 것도 아니다. 약물이 사용되는 것은 [환자의 고통을 줄이기 위함]{.underline}이지, 증상을 완전히 소멸시키기 위함이 아니다. 우울병적 체험이든 정신병적 체험이든, 고통스러운 체험도 경우에 따라선 꼭 겪고 넘어가야 하는 경우도 있다. 극단적으로 말하여, 정신병적 혼란 속에서 겪는 끔찍한 체험이 병식을 얻고 치료 필요성을 수용하는데 필요하다면 약물에 의한 치료를 조금 늦출 수도 있을 것이다.

이렇듯 설명만 들으면 이상적으로 보이는 기술 정신병리학적 관점이 점점 쇠퇴하게된 원인은 어디에 있을까? 가장 흔한 우려는 [낮은 신뢰성과 타당성]{.underline}이다. 정신병리학에서 환자의 주관적 경험을 파악하기 위해 사용하는 수단은 [공감을 통한 이해]{.underline}이다. 타인의 경험을 따라가기 위해 의사는 자신의 심리 내부를 들여다보아야 하며, 자신의 과거 경험과 인간성에 대한 보편적 지식을 활용해야 한다. 그러나 의사가 이해했다고 믿는 바가 단지 자신의 무의식을 환자에게 투사한 것에 지나지 않음을 어떻게 보장할 수 있는가? 또한 한번도 환각이나 망상에 시달려본 적이 없는 의사가 어떻게 혼란된 의식 상태에 있는 조현병 환자의 경험을 파악할 수 있는가?[@Stanghellini2009-rv; @Stanghellini2013-vq]

각양각색의 환자들이 경험하는 결코 일상적이지 않은 경험을 이해하기 위해선, 현상학적 분석과 <s>공감적 이해</s>[^03-02-3]에 대한 상당한 지식과 훈련이 요구된다.[@Heckers2014-tp] Schwartz와 Wiggins[@Schwartz1987-vt]는 "여러 가지 정신질환을 식별할 수 있는 근본적인 능력은 개념적 정의에 통달하는 것보다는 이러한 질환을 보이는 각각의 환자를 직접 만나서 대면함으로써, 다양한 정신질환의 전형적인 형태를 구분해낼 수 있어야 한다"고 말하며, 이러한 과정을 [유형화(typification)]{.underline}라고 하였다. 이처럼 현상학적 분석과 공감적 이해라는 기술은 책이나 강의로 배울 수 있는 것이 아니기 때문에, 표준화와 객관적 평가가 점점 더 강조되는 현대적 의학교육과는 거리가 멀다. 기술 정신병리학의 전통이 강한 유럽에서도 적절한 교육이 이루어지지 않고 있으며, 하물며 미국의 실용적 정신의학을 따라가는 우리나라의 사정 역시 여의치 않은 것 같다.[@Fiorillo2016-qn]

[^03-02-3]: **공감적 이해 (empathic understanding)**: 공감(empathy)과 동정(sympathy)은 명확한 차이를 가진다. 공감은 다른 사람의 생각이나 느낌을 나 자신의 내면에서 추체험하는 것이라면, 동정은 환자의 불행이나 슬픔에 대해 도와주고 싶은 마음을 갖는 것이다. 따라서 동정은 전적으로 나 자신의 감정이요, 환자의 내면 세계와는 무관하다. 공감은 환자의 입장을 상상해봄으로써 도달 가능하지만, 인지적 노력만이 아니라 타인과 마음을 나누는 인간 본연의 심리적 기능을 이용해야 한다. 거울 뉴런(mirror neuron), 표정 모방(facial mimicry)과 같은 기능은 인간 뿐 아니라 영장류에게서도 발결되는 생리적 기능이다.

이렇듯 교육의 기회가 부족하고, 커리큘럼에 정해진 의학 교육 보다는 개인적 자질이나 의학외적 소양에 의존하다보니, 정신병리학에서 강조하는 이해란 쉽사리 주관적이고 자의적인 해석에 빠지기 쉽다. 추구하는 이상은 높고 숭고하지만, 현실적으로는 추상적 개념의 남발과 의미가 불분명한 언술의 연속에서 더 나아가지 못한다. 증거중심의학에서 구축해놓은, 신뢰도를 높이기 위한 다양한 장치들을 적용할 수 없다보니, 자신의 이론에 부합하는 증거만을 수집하는 확증 편향이 생기기 쉽다. 덧붙여, 자신의 내적 경험을 상세히 묘사할 수 있는 환자들의 진술 만을 연구대상으로 삼을 수 밖에 없기 때문에, 음성 증상, 와해 증상 등에 대한 자료는 영영 얻을 수 없을 지도 모른다.[@Le_Lievre2013-tf]

### 현상학적 인류학적 접근

기술 정신병리학적 관점을 따라가다 보면, 환자 개인의 주관적 경험이 그 무엇보다도 강조되고 있음을 볼 수 있다. 여기에는 환각에 대한 경험, 망상에 대한 경험이 있을 것이며, 스스로의 인지기능이 점점 쇠퇴하는 것에 대한 경험도 있을 것이다. 생물정신의학이 조현병의 근본 병태생리가 무엇인지 끊임없이 질문을 던지는 것처럼, 조현병 환자의 주관적 경험에 있어서도 개개 증상을 포괄하는 근본적 경험이 무엇이냐고 물을 수 있다.

인문/사회과학에서 주로 행해지는 질적 연구 방법론 중, 현상학적 질적 연구의 전통은 <s>살아진 경험</s>[^03-02-4] 에 초점을 맞춘다. 살아진 경험이란 현실에서 상황에 맞닥뜨린 개인이 실제로 경험한 모든 것들과 그가 내린 결정들, 그리고 그로부터 얻어진 모든 것들을 지칭한다. 조현병 환자의 근본적 경험을 탐구하고자 하는 학자들 역시 살아진 경험에 주목하며, 이러한 전통을 [현상학적-인류학적 접근(Phenomenological-anthropological approach)]{.underline}이라고 한다.[@Wiggins2006-qy]

[^03-02-4]: **살아진 경험(lived experience)**: 인간이 현상을 경험하는 것은, 1) 스스로가 몸소 체험하는 현상학적 경험과 2) 사회적으로 용인된 개념의 틀에서 경험에 의미를 부여하는 것으로 나눌 수 있다. 부모의 죽음이라는 현상에 대해 실제 체험한 것은 비현실감과 당황스러움이었는데, 타인에게 그 경험을 전달할 때는 말할 수 없는 슬픔과 후회를 느꼈다고 말하는 것이 그 예이다. 인간은 언어의 힘을 빌어 경험을 전달하기 때문에, 지배 이데올로기나 그래야만 한다는 당위성에서 자유롭지 못하다. 살아진 경험이란 이중 전자의 경험을 가리키며, 당사자의 직접적인 경험과 주체적인 결정, 그리고 이를 통해 얻어진 지식을 말한다. Wilhelm Dilthey(1833\~1911)는 살아진 경험이란 경험하고 있는 그 순간에 의식에 주어지는, 개념화되기 전에 느껴지는 반사적 인식(reflexive awareness)이라고 하였다. 이 개념은 질적연구를 진행할 때 핵심적인 도구로 광범위하게 사용되고 있다.[@Lewis-Beck2004-ap]

현상학적-인류학적 접근에서 조현병의 내적 경험은 <s>자기 경험</s>[^03-02-5]의 장애와 <s>상호주관성</s>[^03-02-6]의 세계 속에서의 존재감의 이상이라는 두 가지 차원으로 분석할 수 있다고 본다. 모든 개인은 세계 속에서 행동하고 결정을 내리는 가운에, 자신이 그러한 행동과 결정의 주체라는 경험을 한다. 이는 곰곰히 생각한 후에나 느껴지는 것이 아니라 성찰 이전의 반사적(reflexive) 경험이며, 육체를 가진 인간으로서 모든 경험의 주인이라는 일인칭 시점의 경험이다. 그러나 조현병 환자들은 이러한 주체로서의 경험을 상실하고, 자신이 세계는 물론 자신의 운명에 대해서도 영향력을 잃기 시작한다는 공포감에 시달린다. 이와 함께 동반되는 경험은 상호주관성의 세계 속에서 배제되고 있다는 경험이다. 인간의 주체로 존재할 수 있는 것은 수많은 사회적 관계 속에서 서로가 서로의 주체를 인정하고 있기 때문이다. 정상적인 의사소통을 할 수 없고, 자신의 경험을 타인에게 이해시킬 수 없는 환자들은 점점 더 자신이 유령이 되어가는 경험을 한다.[@JSH2008-tq; @Irarrazaval2015-nb] 2011년 대한조현병 학회를 주관으로 하여 [정신분열병]{.underline}이라는 명칭이 [조현병]{.underline}으로 바뀌었다. 여기서 [조현(調絃)]{.underline}이란 현악기의 줄을 고른다는 뜻으로, 뇌의 신경구조의 이상으로 마치 현악기가 제대로 조율이 되지 않은 것처럼 혼란을 겪는 상태를 의미한다. 그러나 조현병의 영어 번역인 [attunement disorder]{.underline}에서의 ["attunement (독일어로 Befindlichkeit)"]{.underline}란 원래 독일 철학자 하이데거가 인간의 존재론적 위치를 묘사하기 위해 사용한 말로, 개인이 상호주관적 세계에 대하여 어떤 태도를 지니고 그 속에서 어떤 느낌과 감정을 지니며 살아가는지를 가리킨다.[@Zegers2010-vn]

[^03-02-5]: **자기 경험(self experience, *ipseity*)**: 현상학에서는 어떤 현상을 의식할 때는, 의식하는 대상과 함께 의식하는 주체가 동시에 경험된다고 한다. 능동적으로 대상을 인식하고, 주체적으로 결정을 내리는 실행주체(agent)로서의 확고한 경험은 자신이 살아있다는 경험의 기반이 된다. *Ipseity*란 이러한 자기-의식(self-consciousness)을 가리키며, 이는 자기 표상(self-representation)이나 자기 정체성(self-identity)과는 다르다. 후자의 두 개념도 *ipseity*가 경험하는 또 다른 외적 대상일 뿐이다.[@Carruthers2018-fx]

[^03-02-6]: **상호주관성(intersubjectivity)**: 세상을 경험하고 인식하는 주체는 외부의 객관적 세계와 내면의 주관적 세계 사이에서 분열된 채로 지낼 수 밖에 없다. 이 세상에 객관적 현실이란 존재하지 않고 오로지 각각의 개인이 자의적으로 해석하는 주관적 현실만 있다면 사람들은 사회를 이루어 살아가지 못할 것이다. 상호주관성이란 이런 난관을 극복하기 위해 후설, 하버마스 등이 제안한 개념이다. 한마디로 요약하면, 무수히 많은 주관성 사이에서 서로 공동(共同)으로 인정하는 것을 가리킨다. 상호주관성의 세계가 가능해지려면, 개개 주체들은 다른 주체를 인정할 수 있어야 하며, 그들과 공감, 공통된 경험, 참여, 의사소통 등을 통해 서로의 주관적 경험을 나누고 일정 부분을 수용해야 한다. 후설은 우리 자신의 주체가 타인의 눈에 정당한 주체로 인정받지 못하면, 즉 상호주관성에 참여하지 못하면, 스스로의 주체성도 붕괴된다고 보았다. 하버마스는 합리적 의사소통 행위를 바탕으로한 부단한 노력을 통해 사회구성원 간에 최소한의 객관성에 대한 합의가 가능하고 상호주관성이 지탱될 수 있다고 보았다. 조현병 환자가 사회적 철퇴를 통해 상호주관성의 세계로부터 떨어져나가면, 주체로서의 존재감 역시 옅어질 것이다.[@Gallagher2013-cc]

만약 위와 같은 분석이 환자의 내적 경험을 충실히 반영하며, 진정 환자가 고통받는 이유가 이러한 소외에 있는 것이라면, 치료 역시 이러한 근본 경험을 묵인할 수 없을 것이다. 그러나 아무리 현상학적 통찰이 조현병의 근본 문제를 밝혀준다고 해도, 이를 치료의 대상으로 삼기에는 난점이 많아 보인다. 철학적 개념을 토대로 환자를 평가할 수 있는 전문가가 얼마나 될 것이며, 또 그러한 전문가의 진단이 타당하다는 증거는 어디서 찾을 수 있는가? 약물 치료란 여전히 생물학적 기반의 존재를 전제로 한다. 그렇다면 *ipseity*의 장애의 근간이 되는 생물학적 이상을 찾을 수 있을 것인가? 평가하는 사람마다 제각기 다른 진단을 내놓는, 신뢰성이 떨어지는 개념이라면, 아무리 의학이 발전한다 하더라도 그 생물학적 기반을 찾을 수 있다는 보장이 어디에 있겠는가?[@Maj2012-yb]

현상학적-인류학적 접근법이 효과적인 치료로 이어질 수 있는 길이 애초부터 막혀있다면, 이를 연구하는 것은 무의미한 것이 될 지도 모른다. 이러한 논리를 조금만 확장하면, 애초에 주관적 경험과 심리 내적 고통에 대해 약물 치료를 논의하는 것 자체가 어떤 결론에도 이를 수 없는 막다른 길인지도 모른다. 그럼에도 불구하고, 환각과 망상 등 객관적으로 측정 가능한 증상만을 치료 대상으로 삼기에는 무언가 중요한 것을 놓치고 있다는 느낌을 떨치기 힘들다. DSM에 의한 기계적 진단이나, 점검표를 하나씩 지우는 식의 치료적 접근, 치료 성과를 숫자로 환산하며 숫자로 표시되지 않는 것은 효과가 없는 것이라 주장하는 증거중심의학의 모토 등에 대해 막연한 거부감이 드는 것은 우리가 인간심리를 탐구하는 정신과 의사이기 때문일 지도 모른다.

### 정신적 경험의 생물학적 기반

#### 난항을 거듭한 유전 연구

기술 정신병리학이 추구하는 것은, 개인이 경험하는 현상을 최대한 세밀하게 분석함으로써 병적 증상의 미묘한 뉘앙스까지 명료화 하는 것이다. 이러한 세분화를 통해서만 그 하나하나에 해당되는 생물학적 기반을 추적할 수 있고, 이를 통해 조현병의 근본 병태생리를 파악함은 물론 정교한 치료에도 이르게 될 것이라 기대한다.[@Schultze-Lutter2018-np] 한 가지 예를 들자면, 지난 30 여년간 조현병의 원인 유전자를 찾기 위한 무수히 많은 연구가 이루어져 왔으나, 뚜렷한 결론을 얻지 못하였다. 이에 대해 고심한 연구자들은 조현병이 워낙 이질적인 상태 들의 집합이라, 이를 몇 개의 유전자로 설명하는 것은 애초에 불가능한 과업이라고 항변한다.[@Hodgson2017-sv] 이후 개개 증상으로 대표되는 표현형(phenotype) 혹은 <s>내적 표현형</s>[^03-02-7]에 대한 유전적 연구가 대신 이루어지게 되었다.[@Greenwood2019-hy] 만약 이러한 정교화 과정이 더 진행되어 기술 정신병리학의 성과가 유전학 연구에 통합된다면, 환청을 내면의 목소리로 인식하는 지 아니면 외부에서 들려오는 목소리로 인식하는 지를 결정하는 유전자 탐색 연구가 진행되지 말라는 법은 없을 것이다.

[^03-02-7]: **내적 표현형(endophenotype)**: 유전학자인 Bernard John과 Kenneth Lewis가 1966년 제안한 개념이다. 유전학 연구에서는 외적 표현형(phenotype)의 발현에 영향을 미치는 유전형(genotype)을 찾고자 한다. 그런데, 표현형이 너무나 복잡한 요인들에 의해 다면적으로 결정되는 경우, 통계적 방법으로 유전형과의 연관을 분리해내기가 힘들어진다. 따라서 표현형과 유전형 사이에 놓인, 좀더 생물학적 근본에 가까운 대체 표현형을 찾게 되는데, 이를 내적 표현형이라고 한다. 예를 들어 상위 표현형인 조현병의 유전 인자를 찾는 것보다, 조현병 환자에게서 흔히 나타나는 P300 유발 전위의 이상을 결정하는 유전자를 찾는 것이 훨씬 성공 가능성이 높다.

#### 할머니 뉴런

이러한 염원이 결실을 맺을 수 있다면 더 바랄 나위 없겠지만, 과연 가능한 과업인지 잠깐 살펴볼 필요가 있다. 진지하게 들리지 않을 수도 있지만, 한때 신경생물학 연구자들 간에 <s>할머니 뉴런</s>[^03-02-8]의 존재에 대해 가열찬 논란이 행해졌고, 구체적인 증거도 제시되고 있다.[@Quiroga2013-al] 이는 세상에 존재하는 구체적인 사물, 혹은 개념 하나하나에 상응하는 뉴런이 존재할 수 있겠느냐는 근본적 질문이었다. Hubel과 Wiesel의 혁명적인 연구를 통해 확인된 사실은 뇌가 시각정보를 처리할 때, 하위 뉴런은 모서리라든가 명암의 차이 등 기초적인 자극을 식별하지만, 점점 단계가 올라갈수록 복잡한 패턴에 흥분하는 뉴런이 발견된다는 것이었다.[^03-02-9][@Wurtz2009-es] 이를 논리적으로 확장하면, 시각정보 뿐만 아니라 추상적 정보에 대해서도, 혹은 지극히 복잡한 개념 혹은 행동양상 하나하나에 대해서도 해당되는 뉴런이 있을 법 하다는 것이다. 이러한 가설은 실제 실험으로도 일부 증명된 바 있다.[@landi2021]

[^03-02-8]: **할머니 뉴런 가설(grandmother neuron hypothesis)**: 1966년 영국 캠브리지 대학의 Jerry Lettvin이 처음 주장하였다. 특정 현상에 대한 인간의 기억은 100억개가 넘는 신경세포의 연결망 속에 분산 저장되었으리라는 것이 정론이다. 그러나 Lettvin은 특정 개념 하나하나를 기억하는 세포가 있을 것이라 가정하였다. 실제로 인간의 뇌에는 얼굴에만 반응하는 신경세포가 있다. 2005년 캘리포니아 주립대학의 연구자들은 유명 연예인의 사진을 보여주거나 언급하는 것을 들었을 때만 반응하는 신경세포를 찾아내기도 하였다.[@Quiroga2005-wr] 이렇게 극단적인 주장은 아니지만, 특정 개념을 부호화하는 데는 소규모의 신경세포 그룹만이 관여한다는 이론을 sparse coding theory이라고 한다.[@olshausen2004]

[^03-02-9]: **Hubel과 Wiesel의 시각정보처리 이론**: 1958년, 당시 존스 홉킨스 의과대학의 대학원생이던 Daniel Hubel과 Torsten Wiesel은 고양이 후두엽의 시각 중추에 전극을 꽂은 후, 시각정보에 반응하여 신경세포가 활성화되는 양상을 관찰하고 있었다. 그들이 처음 발견한 것은 특정한 각도의 시각 자극에 대하여 각기 반응하는 신경세포가 따로 존재한다는 것이었다. 두 사람은 실험을 계속 확장시켜, 특정 각도 뿐 아니라 좀더 복잡한 형태에 반응하는 세포들이 위계구조를 이룬다는 것을 알아내었고, 나아가 신경세포 들의 기능적 단위가 원주형태를 이룬다는 것(columnar functional organization), 시각 중추의 시각우세기둥 구조 등을 발견하였다. 두 사람은 이 공로로 1981년 노벨 생리의학상을 수상하였다.

이러한 개념이나 연구자들의 열망은, 아무리 복잡한 정신병리적 현상이라도 이에 상응하는 생물학적 기전이 어딘가에는 존재할 것이라는 염원과 매우 닮아있다. [할머니 뉴런]{.underline}은 아닐 지라도, [환청 유전자]{.underline}라든지, [망상 생성 신호전달계]{.underline} 같은 식이다.[@Manji2003-dz] 그러나 다수의 신경생물학자들이 할머니 뉴런의 존재를 의문시하듯이 인간의 주관적 경험 각각에 해당하는 신경생물학적 기반이 반드시 존재하는지는 의문이다. 그 중요한 이유 중 하나는 정신현상이 복잡계(complex system)가 발현하는 <s>창발된 속성</s>[^03-02-10]일 가능성이 높기 때문이다. 태풍을 예로 들어본다면, 환원주의적 입장에서 보았을 때 태풍을 구성하는 것은 결국 공기의 흐름과 수증기의 밀도일 뿐이다. 그러나 이 둘이 상호 작용하는 과정에서 어떤 특정 조건에 도달하면, 엄청난 파괴력을 지닌 에너지 덩어리로 변모한다. 태풍의 발생과 소멸을 이해하려면 풍속과 습도라는 두 변수의 관계를 분석해야지, 공기와 물의 분자구조를 아무리 연구한다 해도 그 현상을 이해하는데 도움이 안 될 것이다. 여기서 얻을 수 있는 결론은 복잡계의 속성을 기술하고 이해하려면, 적절한 수준(level)의 추상화(abstraction) 과정이 필요하다는 것이다.[@Maayan2017-jj] 현상을 일으키는 구성 요소들의 상호 관계를 규명하여야 복잡계를 이해할 수 있을 텐데, 그 구성 요소를 어느 수준에서 정의하느냐에 따라 연구는 통찰에 도달하기도 하고 벽에 부딪히기도 한다.[@Damper2000-zp] 조현병을 앓는 환자의 망상 경험을 설명하고자 할 때, 이를 유전자나 신경전달물질 단계에서 기술하고자 하는 것이 [적절한]{.underline} 수준인지는 의문의 여지가 있다. 구성 요소들의 부적응적인 상호 작용으로 인해 창발된 속성이 병적 현상이요 증상이라고 했을 때, 치료는 이러한 상호관계를 끊어내고 바람직한 방향으로 되돌리는 것이다. 따라서 구성 요소를 무엇으로 정의하느냐는 치료의 관점에서도 매우 중요한 문제이다.

[^03-02-10]: **창발된 속성(emergent property)**: 창발(創發)은 계층 구조를 갖는 시스템에서, 하위 계층(구성 요소)에는 존재하지 않는 특성이나 행동 양상이 상위 계층(전체 구조)에서 자발적으로 예기치 않게 출현하는 현상이다. 가령 흰개미 한마리는 집을 지을 만한 지능이 없지만, 그 집합체는 자신이 맡은 역할만을 수행하는 다른 개미들과의 상호작용을 통해 거대한 집을 짓는다. 창발 현상은 복잡계(complex system)와 단순계(simple system)를 구분하는 중요한 잣대이다. 구성 요소를 아무리 모아놓아도 동적 상호작용을 통해 하위 계층에서 예상할 수 없었던 거시적 성질이 출현하여야 복잡계라고 칭할 수 있다. 뇌기능은 가장 대표적인 복잡계이며, 의식은 대표적인 창발 속성이다.

#### 위계적 구조를 가진 중추신경계

중추신경계의 기능 역시 위계적 단계로 구성되어 있을 것이라는 견해를 최초로 제시한 사람은 1900년대 말에 활동한 <s>Jackson</s>[^03-02-11]이었다. (Levin, 1965) 그는 신경계의 기능을 크게 세 개의 단계로 구분하였으며, 상위 단계의 기능은 하위 단계에 의존하지만, 역으로 하위 단계의 기능은 상위 단계의 조절을 받는다고 주장하였다. 하위 단계일수록 진화론적으로 고태적인 것으로 가장 안정되어 있으며 쉽사리 흔들리지 않는다. 이에 비해 상위 단계는 하위 단계의 성숙에 수반하여 창발된 현상으로 질병의 영향에 가장 취약하다. 또한 새롭게 창발된 기능이 진화를 거치면서 점차 더 정교화되고 새로 등장한 단계 내에서의 상호 작용이 활발해지기 시작하면, 하위 단계에 대한 의존성이 점차 옅어져 간다. 따라서 상위 기능을 일군의 신경세포나 특정 생화학적 기전으로 환원하는 것은 가망없는 전략이다. 이러한 기능들은 셀 수 없이 많은 기능 단위들의 상호 작용 속에서 일어나며 폭넓게 분산되어 있기 때문이다.

[^03-02-11]: **John Hughlings Jackson (1835\~1911)**: 영국의 신경학자로 간질의 진단과 이해에 많은 업적을 남겼다. 말년에는 신경기능을 진화론적 관념에서 이해하고자 하였는데, 이때 등장한 것이, 정신기능의 3단계 이론이었다. 그는 John Russell Reynolds (1828\~1896)의 아이디어를 발전시켜, 음성 증상이란 상위 기능의 해체(dissolution)때문이며, 양성증상은 하위 기능이 상위 기능으로부터 해제(release) 혹은 탈억제(disinhibition)됨으로써 발생한다고 주장하였다. 이는 병소가 직접 증상을 일으키는 것이 아니라, 전체 시스템 내의 균형을 무너뜨림으로써 증상발현을 조장한다는 혁신적인 주장이기도 하다. 이는 후에 조현병의 양성, 음성 증상 개념에 영향을 미친다.[@Pearce2004-xa]

## 무엇을 치료할 수 있으며 무엇을 치료해야 하는가?

### 과학과 비과학

과학의 발전은 목표를 제대로 세우는 것으로부터 시작한다. DSM을 제정한 선대 연구자들은 자신이 집필한 DSM이 결함 투성이임을 알고 있었지만, 그들이 세운 방향을 따라 부단한 발전이 이어질 것이라 굳게 믿었고, 조금씩 더 진실에 가까워지리라 확신하였다.[@Kendler2017-qy] 과학철학자인 <s>Popper</s>[^03-02-12]는 과학과 비과학을 구분하는 기준은 [반증가능성(falsifiability)]{.underline}라고 하였다. 즉 어떤 주장에 대해 실험이나 관찰을 통해 반증할 수 있는 여지가 있어야 과학적 탐구의 대상이 되는 것이요, 과학 발전의 정당한 방향이 될 수 있다는 뜻이다.[@Johnson2009-hd] 조현병을 둘러싼 개념들은 풀리지 않는 실타래처럼 얽혀만 있어서, 어디서 어떻게 풀어야 할 지 갈피를 잡기 어렵다. 그러나 이들 개념 중에는 반증가능성의 기준에 부합하는 것도 있고 그렇지 않은 것도 있다. 내적 경험과 심리적 현실에 대한 탐구는 진정 의미있는 주제이긴 하지만 반증가능성이라는 벽에 부딪힌다. 따라서 그 모든 결함과 모순에도 불구하고, 70년 가까운 세월 동안 정신약물학과 질병분류학 연구는 "[반증가능한 것부터 해결해보자"]{.underline}라는 방향으로 발전해왔다. 반증가능하다는 것은 가설의 설정과 오류의 발견, 그에 뒤이은 가설 보완의 과정을 무한히 반복하다보면 진실에 조금씩 수렴할 수 있다는 보장을 뜻한다. 다행히 정신병리학 연구에 있어서도 객관화 정량화의 도구를 통해 반증가능한 과학의 영역으로 편입시키려는 노력이 끊임없이 이어지고 있다.[@Stieglitz2017-yj]

[^03-02-12]: **Karl Raimund Popper (1902\~1994)**: 20세기의 가장 영향력있는 과학철학자이다. 그는 고전적인 관찰-귀납의 과학 방법론을 거부하고, 과학자가 제시한 가설을 경험적인 증거를 통해 반증하는 과정을 반복함으로써 과학이 발전내 나감을 주장하였다. 그가 해결하고자 했던 것은 과학과 비과학을 구별하는 "'구획 기준의 문제"였다. 여기서 포퍼가 말하는 과학이란 어디까지나 경험 과학을 말한다. 경험 과학과 그 밖의 과학을 구분하는 것은 반증가능성이다. 거짓으로 밝혀진 이론이라 할 지라도, 반증가능성이 있다면 과학적 가설이자 경험 과학의 구획 내에 있다. 반면 자명한 진리라도 반증가능성이 없다면 과학이라 할 수 없다. 반증가능성(falsifiability)이란 주장되는 가설이 실험이나 경험을 통해 기각될 수 있는 가를 묻는다. 이는 또한 가설을 반박하는 증거가 지지하는 증거보다 더 많은 정보를 담고 있다는 주장이기도 하다.

지난 반세기가 넘는 세월 동안 조현병의 정체를 밝히려는 노력은 반증가능성의 테두리 안에 갖혀 있었다. 물론 신경생화학은 도파민, 세로토닌, 글루타메이트 등의 다양한 신경전달물질이 조현병의 병태생리에 관여한다고 알려주었으며, 신경해부학은 전두엽, 측두엽, 피질하 조직 등 여러 뇌 영역에서 이상이 발견된다고 알려주었다. 그럼에도 불구하고 축적된 정보는 너무나도 많지만, 이를 통합하여 정신 현상을 이해하는 길은 멀고도 험난해보인다. 정신병리학과 인지심리학 분야에서도 지각, 사고, 인지, 감정, 의지 등이 따로따로 연구되어 왔으며, 이를 통합해주는 이론은 아직 소식이 없다. 조현병을 구성하는 하나하나의 증상만이라도 단순, 명료했으면 좋으련만, 흔히 전적인 지각 이상으로 간주되는 환각 역시 실제로는 지각 뿐 아니라 인지, 정동, 판단, 병식 등 다양한 정신 기능이 함께 작동한 최종 결과물이다.[@hayashi2004]

정신 영역 각각에 대해 깊이 있게 탐색하고 또 이를 생물학적 소견과 연결시키는 작업이 과연 성공할 수 있을런지, 애초에 전제부터 잘못된 것인지는 여전히 오리무중이다. 그러나 문제점을 인식하고 자신이 취한 방향을 재검토 할 수 있는 연구자들의 노력이 모인다면, 언젠가 개개 증상과 그 생물학적 기반, 나아가 조현병 자체의 정체에 대해서 이해할 수 있는 날이 찾아오리라 기대한다. 근대 심리학의 아버지라 일컬어지는 <s>Wundt</s>[^03-02-13]가 역설했듯이 심리학 연구에서, 단순한 현상마저 이해하지 못한다면 결코 그 너머의 복잡한 현상을 이해할 수 없을 것이다.[@Hergenhahn2013-bz] 하지만 나무만 열심히 들여다보아서는 결코 숲을 보지 못한다. 기술 정신병리학이 정신질환에 대한 일인칭적 진술에서 출발하여 비정상적인 경험의 근본 구조에 대한 보편법칙적 탐구하는데까지 전진하기 위해서는 새로운 방법론의 모색이 절실하다.

[^03-02-13]: **Wilhelm Maximilian Wundt (1832\~1920):** 독일의 생리학자로 근대 심리학의 아버지라 불리운다. 철저한 실험심리학자로서 여러가지 심리현상을 계측 가능하고 객관적으로 파악할 수 있는 것으로 탈바꿈시켰다. 이를 통해 심리학을 생물학과 철학으로부터 분리시켰으면서도, 심리학을 정당한 과학의 테두리 안에 포함시킬 수 있었다.

### 약물 치료를 뒷받침하는 치료자의 자세

본서의 주제가 조현병의 약물 치료인 만큼, 주된 논의의 내용은 생물학적 환원주의에 근거한 질병 및 증상 치료이다. 그러나 설령 약물 치료를 주로 시행하더라도, 치료를 행하는 의사와 이를 수용하는 환자는 생물학적 수준에서가 아니라 인본주의적 수준에서 만나고 공감을 이루어내야 한다. 그렇게 하기 위해선 광범위한 가치에 대해 친숙해져야 하며, 이를 포괄할 수 있는 넓은 시각이 필요하다.

조현병을 비록 뇌의 병이라고 하지만, 정신과 의사가 돌보는 것은 조현병이 아니라 조현병을 앓고 있는 환자이다. ["좋은 의사는 질병을 치료한다. 그러나 훌륭한 의사는 병을 앓고 있는 환자를 치료한다"]{.underline}는 Osler의 경구는 의사라면 누구나 한번쯤은 들어보았음직 하다.[@Seeman2017-mu] 이 경구는 물론 어떤 분야의 의사에게도 해당되는 말이겠지만, 정신과 의사에게는 더욱 더 가슴에 와닿는다. 뇌와 마음의 관계, 혹은 객관적 세계와 주관적 세계의 관계는 여전히 철학과 형이상학적 영역의 질문 들이다. 질병 개념은 정신 장애의 과학적 탐구를 위해 반드시 필요한 개념이다. 하지만 정신의학은 신체 의학과 달리 성격이나 문화 배경 등이 바탕이 된 환자의 주관적 경험을 중심에 두기 때문에, 동일한 약물 치료를 둘러싸고도 정신의학에서의 접근은 신체 의학에서의 접근과 달라야 한다.

### 주관적 경험의 세계

현상학에서 바라보는 주관적 경험이란 현상학적 경험과 그 경험에 개인이 부여하는 의미를 모두 아우른다. 정신병리학은 주관적 경험에 접근하는 신뢰성 있고 타당한 방법론을 강조한다는 점에서, 인간성 탐구의 유용한 도구이다. 병을 앓고 있다는 것은 어디까지나 환자의 주관적인 경험이며, 따라서 이를 경험하는 사람이 중심에 놓여야 한다. 환자는 자신의 병에 대해 해석하고 나름의 이론을 구축함으로써 진단 과정에서 능동적인 역할을 한다. 증상이란 취약성이 있는 개인이 자신에게 벌어지는 부적응적 변화를 이해하고 이에 대응해 나가는 과정에서 이루어지는 타협의 산물이다.[@Stanghellini2014-hm]

예를 들어 슈나이더의 일급 증상은 조현병 진단 기준의 중요한 일부로 채택되었지만, 의미가 축약되고 잘못 해석되어 있다.([섹션 @sec-schneider-first-rank]) 슈나이더는 피동체험(somatic passivity)을 경험의 구조 및 질의 변형, 즉 내용(content)이 아닌 형식(form)의 이상으로 보았으나, DSM에서는 내용에 집중하여 괴이한 망상, 즉 상식에 부합하지 않는 왜곡된 인지와 잘못된 판단으로 해석하고 있다. DSM을 비롯한 진단 중심주의적 접근에서는 증상의 유무만을 중요시하여 단순히 진단을 뒷받침하는 증거로 이용하는데 그치고 있다. 하지만 일급 증상이 아무리 이해불가능하다고 해도, 여전히 이상 경험에 대해 판단하고 의미를 부여하는 환자의 주관성이 표현된 것이다. 의사는 대부분의 사람이 공유하는 상식적 <s>생활세계</s>[^03-02-14]에서 살고 있으나 조현병 환자들은 여기서 유기되어 또 다른 정신병리의 세계에 머물러 있을 수 있다. 이런 환자를 이해하기 위해서는 그가 사는 생활세계의 맥락에서 소통할 수 있어야 한다.[@Stanghellini2014-hm]

[^03-02-14]: **생활세계(lifeworld, 독일어로는 Lebenswelt)**: 개인의 모든 현상학적 경험이 일어나는 장으로서의 세계. 객관적으로 파악된 세계와는 대조적인 의미를 갖는다. 앞서 언급했던 살아진 경험(lived experience)가 일어나는 장이라고 간주할 수 있다.[@Rich2013-ne]

정신병리학은 증상을, 제거해야 하는 비정상적 현상으로 보는 데 그치지 않고, 내재된 정신내적 세계를 탐구하는 단서로 삼는다. 환자의 정신내적 세계에서 공감할 수 있는 부분을 발견하지 못한다는 것은, 치료가 진전되고 있지 못하다는 뜻이다. 이때 타인의 심적 경험에 다가서기 위해서는, 환자 스스로 자신의 내면을 기술하는 진술에 기대지 않을 수 없다. 환자가 아니라 조현병만 보거나, 질병의 보유자 정도로 탈개인화한다면 제대로 된 치료가 이어질 리 없다. 치료란 증상을 없애는 것 뿐 아니라, 환자가 자신만의 독특한 장점과 자원, 한계를 가지고 능동적으로 자신의 질병에 적응해나가는 과정을 돕는 것이다. 따라서 모든 치료는 질병 중심이 아니라 환자 중심이어야 한다.

정신과 의사가 환자를 접근하는 방식은 대부분 질문으로 이루어진다. 그런데 어떻게 질문하냐에 따라 그 반응이 놀랄 만큼 차이가 날 수 있다.[@Silberman2010-zg] 정신 증상에 대한 진술은, 환자 내부에서 그리고 환자와 의사 간의 대화 속에서 일어나는 설명 과정의 산물이다. 이런 점을 이해하지 못하면 증상의 평가에서부터도 어긋나기 시작한다. 동일한 병리현상에 대해서 의사와 환자의 해석은 완전히 다를 수 있다. 의사는 일반적 정의를 통해 병리현상의 유무를 환자에게 묻지만, 환자는 의사가 무엇을 물어보는지 의미를 파악하는데 어려움을 겪는다. 획일적인 질문은 이런 어긋남을 더욱 강화시키는데, 정해진 문구로 질문해야 하는 평가도구를 사용할 때 상황이 더 악화된다. 의사는 공감을 통해 환자가 경험하고 있을 것이라 예상되는 현상을 기술함으로써 질문을 던져야 하며, 의사가 던진 질문이 환자의 마음 속에서 어떤 파장을 일으키는지 조차 평가의 대상이 된다.[@Stanghellini2013-vq]

### 공감, 인간적, 가치-친화적 접근

현상학적 입장은 정신질환을 대할 때 공감, 인간애, 가치를 중시한다. 인간애를 바탕으로 한 공감이란 "[타인의 고통에 입회함으로써 갖는, 타인을 향한 관심, 연민의 감정"]{.underline}이며 라포, 즉 치료적 동맹을 형성하여 신뢰를 이끌어내는 특수한 기술이다. 그런데 타인에 대한 공감을 가로막는 주된 요소 중 하나는 서로 다른 가치관이다. 의사는 환자와 전혀 다른 성장과정을 겪어 왔기 때문에 추구하는 것, 옳다고 생각하는 것 등에 대한 가치관이 전혀 다를 수 있다. 인간은 자신과 가치관이 동일한 타인에게는 얼마든지 관대해질 수 있지만, 가치관이 어긋나는 타인에게는 무관심하거나 잔인해질 수 있다.

[증거중심의학]{.underline}에서 치료와 관련된 결정은 정확한 진단과 객관적인 증거에 입각한다. 의사결정 과정에 환자의 주도적인 참여를 적극 권장하지만, 기껏해야 환자에게 관련된 의학적 증거들을 제시하고 그 중에서 최대한 합리적인 선택을 할 수 있도록 돕는 선에서 멈춘다. 이에 비해 근래 제시되고 있는 <s>가치기반 진료</s>[^03-02-15]는 환자가 어떤 가치를 가장 중요시하는가에 따라 의학적 결정을 내리는 것을 말한다.

[^03-02-15]: **가치기반 진료(value-based practice)**: 정신과 의사인 Kenneth Fulford에 의해 제안된 개념이다.[@Fulford2008-iq] 모든 복잡한 의학적 의사결정은 가치를 떼어놓고 생각할 수 없다. 과거에는 의료윤리적 가치만을 고려했으나, 결정에 참여하는 당사자 마다 중요시하는 가치가 다를 수 있다는 원칙 하에, 개인적 선호도, 욕구, 기대, 소망 등 다양한 가치를 반영할 필요성이 높아졌다. 가치기반 진료를 행하기 위해서는, 참여자들이 지닌 서로 다른 가치를 찾아내고, 적용되는 가치들의 우선순위를 매겨 충돌하는 가치를 조정할 수 있는 기술이 필요하다.

한편 무엇이 최상의 가치인지는 시대에 따라 변하고, 증거중심의학에서 내세우는 근거가 확실한지도 의문이다. 의료 행위가 점점 복잡해지면서, 경제적, 법적, 윤리적, 정치적 가치 들이 충돌하기 시작했고, 심지어 어떤 희생을 무릅쓰고라도 생명을 살려야 한다는 가치조차 절대성이 흔들리고 있다. 낙태금지법안을 둘러싼 종교계와 페미니스트들의 가열찬 논쟁 또한 그러한 대표적인 예이다. 상황이 너무도 꼬여있다보니, 오히려 의사의 개인적 경험이나 전통적인 신념체계에 반성없이 의존하는 경향이 나타나기도 하며, 환자가 추구하는 가치를 경청하려 하지 않는 태도가 나타난다.[@Moller2009-dm]

이를 보완하기 위해 등장한 가치기반 진료는 의학적 결정이 좀 더 환자-중심적이 되도록 보완하는 역할을 하며, 상반되는 가치가 부딪히는 상황을 진료를 방해하는 걸림돌로 보는 게 아니라 좀 더 나은 상호 이해에 도달하는 기회로 본다. 가치기반 진료가 강조된다고 해서 의학적 증거를 무시하라는 뜻은 아니다. 두 진료 체계는 상호보완적이며, 증거중심의학이 독단으로 흐를 수 있는 가능성을 막아주는 역할을 한다.[@Peile2013-sa; @Fernandez2015-fa] 가치기반 진료는 점차 복잡해지고 상충되는 가치를 조정하고 근거와 이어주는 역할을 한다. Sackett 등[@sackett2000]은 "최상의 연구 증거, 임상적 전문성과 환자의 가치라는 세 가지 요소가 통합될 때 임상의와 환자는 치료 결과와 삶의 질을 최적화할 수 있는 진단적, 치료적 동맹을 형성할 수 있다"고 한 바 있다. 더군다나 가치란 인간이 어떤 행동을 취하도록 만드는 강력한 추진력이다. 의사와 환자가 상호 이해를 바탕으로 공통의 가치에 도달한다면 치료 성과도 자연히 높아지는 것을 기대할 수 있다.

환자와 보호자의 가치를 구하고 이해하기 위해선, 인간의 경험과 행동의 숨겨진 부분을 밝히는 심리학적, 해석학적 지식이 필요하다. 그들은 자신이 추구하는 가치를 구체적으로 생각해본 적이 없을 수도 있고, 이를 남에게 전달해본 경험은 더더욱 부족할 것이다. 의사는 가능한 많은 정보를 바탕으로 환자가 추구하는 가치를 추론해내야 하며, 자의적인 해석을 삼가야 한다. 또한 아무리 환자가 추구하는 가치가 중시된다 해도, 넘어서는 안 되는 한계가 있다. 의학 윤리에서의 기본 원칙은 1) 환자의 자율성 존중, 2) 환자의 이익을 우선시함, 3) 환자 혹은 주변인에게 피해가 가서는 안 됨, 4) 공정하고 정의로운 결정이다.[@Beauchamp2007-ml]

조현병의 약물 치료에서 이러한 윤리 원칙은 명료한 해결책보다는 고민할 숙제만 더 던져주는 것 같다. 환자의 자기 결정권, 공유된 의사결정, 가치기반 진료 등 환자가 무엇을 원하는 지 적극 반영하라는 책무는 늘어났지만, 무엇이 환자에게 이익이 되는 지, 환자 가족들이나 사회의 피해는 고려의 대상이 되지 않는 것인지 등 해결되지 않는 숙제가 많다.[@Bassman2005-bs] 병식이 전혀 없거나 판단력이 손상되어 이성적인 결정을 할 수 없는 경우를 제외한다 하더라도, 환자 중에는 투약을 원하지 않거나 질병이라는 이름표가 붙는 것 자체를 거부하는 경우가 흔하다. 그러나 의사 입장에서는 치료를 하지 않았을 때 재발할 것이 분명하기 때문에 환자의 가치를 존중하는 것은 그에게 해를 입히는 셈이다. 환자의 돌발 행동이나 기능 부전이 가족에게 상처를 입힘은 물론 위협으로 다가온다는 것 역시 윤리적으로 받아들이기 어려운 점이다.[@Sabin2016-nf] 일부 인권학자들은 조현병 환자가 편견과 차별에 시달리는 것을 사회의 공동책임으로 돌리고 있지만, 증상이 여과없이 외부로 드러나기 때문에 차별을 받는 것이요, 증상을 조절하고 관리하는 것은 환자 자신이 떠맡아야 할 책임이기도 하다.

## 종합적 시각

오늘날 정신의학은 정신질환을 [생물심리사회적 모형]{.underline}으로 이해한다. 따라서 정신의학은 본질적으로 생물-심리-사회에 대해 종합적일 수밖에 없다. 정신의학이 다시 의학으로 복귀하기 위해 생물정신의학으로 탈바꿈하고자 안간힘을 쓰고 있는 와중에, 일반 의학은 정신과적 가치를 받아들이고자 애쓰는 역설적인 현상이 일어났다. 환자 중심, 가치기반 등의 모토는 애초에 정신의학에서는 당연한 진료 원칙이었다. 정신병리학의 전통이 잘 말해주듯, 환자의 주관적 세계에 대한 이해없이는 정신의학이 존재할 수 없었으며, 애초에 질병보다는 고통 받는 사람을 먼저 보았던 것도 정신의학의 전통이었다. 인문, 사회 과학의 다양한 이론 역시 사람과 그를 둘러싼 사회를 이해하는 노력 들이요, 이러한 인접 학문 영역에 대해 정신과 의사만큼 개방적이고 교양을 갖춘 의사도 많지 않을 것이다. 오히려 일반 의학을 따라잡아야 한다는 강박관념 속에서 원래 지니고 있던 장점들을 버리려 하는 지도 모른다.

야스퍼스는 이미 100여년전에 정신의학은 자연과학과 사회과학이라는 이질적인 요소가 합쳐져 있는 [혼성 과학(hybrid scientific discipline)]{.underline}이라고 하였다. <s>딜타이</s>[^03-02-16]는 자연 과학은 현상의 인과적 [설명(explanation)]{.underline}을 요구하지만, 인문학은 인간 행동의 의미를 파악하는 [이해(understanding)]{.underline}에 관심을 둔다고 하였다. 야스퍼스는 이 개념을 빌려, 정신의학은 이 두가지 방법론을 모두 아우르는 독특한 학문 영역이라고 하였다. 자연과학으로서의 정신의학은 질병의 신경생물학적 기반을 밝히고자 하지만, 인문과학으로서의 정신의학은 사회가 왜 어떤 행동을 일탈(deviant)로 낙인찍고, 동일한 질병이라도 왜 사람마다 정신적 고통의 정도가 다른 지를 탐구한다. 이러한 혼성 학문이라는 인식론적 위치는 장점이기도 하지만, 필요없는 혼란을 유발하기도 한다. 이해를 필요로 하는 탐구 과제에 인과적 설명을 밝히는 양적 연구 방법론을 쓴다던가, 자연과학적 연구를 통해 얻은 사실을 가치 중심적인 논조로 비판하는 것이 그러한 예이다. 이는 동일한 현상을 이렇게도 바라볼 수 있고, 저렇게도 바라볼 수 있다는 상대주의(relativism), 다원주의(pluralism)적 주장을 하는 것이 아니다. 정신현상이란 그 발생과 현현 자체가 자연과학과 인문과학 적 요소가 깊게 뒤섞여 나타나는 지극히 복잡한 현상임을 잊어선 안 된다는 것이다.[@Markova2012-ul]

[^03-02-16]: **Wilhelm Dilthey (1833\~1911)**: 독일의 철학자로 역사학, 해석학의 권위자. 정신과학의 인식론적 토대 구축을 위해 애썼다. 인간의 삶과 경험이 하나의 이해의 대상으로 주어지며, 이를 학문의 대상으로 하는 것이 정신과학이라 하였다. 따라서 정신과학의 학문적 원천은 바로 내적 경험이며, 이는 동시에 언어와 전통을 매개로 역사적으로 형성된 조건 하에서 생성되는 경험을 의미한다고 주장하였다. 야스퍼스는 물론 주관적 경험을 중시하는 모든 종류의 질적 연구에 큰 영향을 미쳤다.

## References {.unnumbered}
