---
title: "정신약물학 이전 시대의 치료"
subtitle: "Before the birth of psychopharmacology"
bibliography: References/04-01.bib
---

## 항정신병약 개발 이전

정신장애의 치료와 관련된 역사를 살펴볼 때 명심해야할 부분이 있다. 조현병 치료와 관련된 비판적 문헌들은 역사적으로 행해졌던 치료들의 [무지몽매함]{.underline}과 [비윤리적 요소]{.underline}를 유달리 강조하는 경향이 있다. 이는 특히 반정신의학([-@sec-ancient-period] 장)을 지지하는 사회과학자들의 문헌에서 많이 발견된다. 다만 광증을 의학적인 정신질환과 구분하지 못한 시절의 치료를 정신질환 치료의 역사에 넣어야 할 지는 의문이다.[@Kroll1995-bh] 조현병이 분명한 뇌질환이라는 개념이 정립되기 전에는, 유감스럽지만 치료법이 조악하거나 비상식적인 경우가 많았다. <s>Battie</s>[^04-01-1]가 1758년 저술한 *"광기에 대한 소론(A Treatise on Madness)"*에는 당시의 정신질환을 치료하는 방법들이 묘사되어 있는데, 여기에는 화상 입히기, 굶기기, 찬물이나 뜨거운 물에 담그기, 사혈 등의 치료 방법이 기술되어 있다. 이 정도로 비상식적인 것은 아니라 할 지라도, 임상시험이라는 증거 수집의 기본 방법론조차 정립되지 않은 상황에서, 의사들은 객관적 증거보다는 광증에 대한 자신들만의 지극히 주관적인 이해에 입각하여 그들의 치료를 정당화하였다.[@Owen2014-mh] 이러한 부끄러운 과거의 역사적 유산들은 현재까지도 조현병 치료에 대해 부정적 시각과 편견을 조장하는 요인이 되고 있다.

[^04-01-1]: **William Battie(1703\~1776)**: 영국의 의사. 1764년 정신과 의사로서는 최초로 영국 왕립의사협회의 회장을 역임하였다.

### 크레펠린과 블로일러, 그리고 생물학적 치료의 시작

적을 물리치거나 방어할 수단을 마련하기 위해선, 무엇보다 [적의 정체]{.underline}가 무엇인지를 분명히 해야 한다. 질병분류학이 궤도에 올라서기 전까지 많은 정신질환은 광증이라는 애매모호한 범주에 속해있었고, 그것이 생물학적 질환인지, 도덕/윤리적 일탈인지도 분명하지 않았다.

크레펠린은 그가 명명한 [조발성 치매]{.underline}가 뚜렷한 생물학적 기반을 가진 질병이라고 믿어 의심치 않았다. 하지만 정작 그는 생물학적 기반을 확실히 밝히지 못한 이상, 조발성 치매의 치료는 불가능할 것이라 믿었다. 조발성 치매의 치료불능성에 대한 그의 확고한 믿음 때문에 동시대 정신과 의사들 조차 그를 염세주의자로 여길 정도였다고 한다.[@Ghaemi2019-ac]

조현병 해석에 정신분석적 관점을 도입한 블로일러 역시, 조현병이 생물학적 기반을 갖고 있다고 믿었다. 그는 ["정신분열병의 대부분의 증상은 심리적 영향에 더하여, 독성 물질이나 해부학적 이상 때문에 일어난다"]{.underline}고 말하였다.[@Ghaemi2019-ac] 그러나 그는 크레펠린과는 달리 조현병이 치료될 수 있으리라고 믿는 낙관론자에 속하였다. 이상과 같이 크레펠린과 블로일러, 그리고 동시대의 선구적 정신과 의사들에 힘입어 분명하진 않다 하러다도 적의 정체를 파악할 수 있게 되었고, 바야흐로 다양한 생물학적 치료가 강구되기 시작하였다.

그러나 신경전달물질에 의한 신호전달 등 신경과학의 기본 지식조차 밝혀지지 않은 상황에서, 치료법이라고 해봤자 수없는 시행착오를 거듭하며 요행을 바랄 뿐이었다. 의사들은 단순히 흥분을 가라앉히는 것이 아니라 제대로 병을 낫게 하기를 꿈꾸었으나, 새로 고안된 치료법들 역시 전통적 치료법에서 그리 발전했다고 보기 어려웠다. 당시 조현병의 병인으로 거론된 것은 변성([-@sec-before-kraepelin] 장) 이외에, <s>자가중독</s>[^04-01-2]과 신경계 감염이었다. 따라서 조현병 뿐 아니라 다양한 질환의 치료를 위해 [관장]{.underline}이 시도되었고, [맹장이나 대장 일부분을 절제]{.underline}하는 수술이 행해지기도 하였다.[@Noll2004-nx] 일부 의사들은 충치균이 조현병의 원인이라 생각하여, 환자의 [치아를 모두 발치]{.underline}하는 웃지 못할 치료법을 시행하기도 하였다.[@Kerner2017-kg]

[^04-01-2]: **자가중독(autointoxication)**: 프랑스의 의사 Charles Jacques Bouchard(1837\~1915)는 1887년 행한 *"질병의 자가 중독 이론"*이라는 강의에서, 장 내에 서식하는 세균의 양이 너무 많거나, 그 독소가 간이나 신장에서 제대로 처리되지 못하면, 다른 장기로 들어가 질병을 유발한다고 믿었으며, 정신질환도 그러한 사례 중 하나라고 하였다. 이는 현대에 들어와서 **gut-brain axis**라는 이론으로 계승되고 있다.

### 정신약물학 이전의 정신증 치료

20세기 초 세균학과 면역학이 급속도로 발달하면서, 한때 조현병이 신체 조직 일부에 대한 자가면역 현상이라는 이론이 주목을 받기도 하였다.[@Noll2006-xm] 이 이론에 근거하여 면역억제제인 sodium nucleinates를 사용하여 백혈구 수를 일시적으로 감소시키는 치료가 행해졌다.[@Domingo2010-hk] 이 이론은 얼마 지나지 않아 배척되었지만, 최근에도 주목을 받고 있는 [면역질환으로서의 조현병 모델]{.underline}의 선구 이론이라고 할 수 있다. 조현병이 미생물 감염에 의한 것이라는 이론 또한 많은 지지를 받았다. 19세기 중반 <s>파스퇴르</s>[^04-01-3]는 고온 가열을 통해 세균을 박멸할 수 있음을 증명하였다. 만약 미생물이 조현병의 원인이라면 체온을 인위적으로 올려서 세균을 죽일 수 있을 것이다. 이 이론에 착안한 <s>바그너-야우레크</s>[^04-01-4]은 말라리아 균을 이용한 신경매독의 발열 치료를 개발하였다. 이 치료는 최초의 성공적인 치료법으로 기록되었으며, 실제로는 일시적인 효과가 있을 뿐이었지만 조현병 등 다양한 정신질환에 적용되었다.

[^04-01-3]: **Louis Pasteur (1822\~1895)**: 프랑스의 생화학자로 Robert Koch(1843\~1910)와 함께 세균학의 아버지로 불린다. 질병과 미생물의 연관관계를 밝혀냈고, 저온 살균법, 광견병, 닭 콜레라의 백신을 발명했다.

[^04-01-4]: **Julius Wagner-Jauregg (1857\~1940)**: 오스트리아의 의사. 신경 매독에 걸린 환자에게 말라리아 환자의 피를 주입하는 방법을 사용하는 치료법을 발견했다. 약화된 말라리아 균이 주입된 환자가 심한 발열 반응을 수차례 반복하면, 해열 작용이 있는 퀴닌 등으로 치료하였다.그는 이 발견으로 1927년 노벨 생리-의학상을 수상하였다.

말리리아 균을 이용한 치료 외에도 [발열 반응]{.underline}을 응용한 몇 가지 치료가 행해졌다. 피하나 복강 내에 <s>테레핀</s>[^04-01-5]을 주입하여 염증반을 일으킴으로써, 발열과 함께 백혈구 증가를 꾀하는 방식도 있었다. 정신병적 증상을 보이는 환자가 신체적 상태가 안 좋아지면 일시적으로 정신상태가 호전된다는 관찰은 현대에 들어서도 임상 의사들이 흔히 경험하는 사실이다. 2차 대전 전의 의사들은 이러한 일시적 변화를 질병의 근본적 치료와 혼동했던 것으로 보인다.[@Lehmann1997-mi]

[^04-01-5]: **테레핀(turpentine)**:침엽수종인 소나무, 전나무등의 수지(송진)를 증류하여 얻은 액체이다. 과거에는 가정 상비약으로서, 찰과상, 기생충 치료제 등으로 사용되었다. 현재는 플라스틱 제조, 방부제, 청소용품 등에 첨가물로 사용된다.

발열 치료와 함께 널리 사용되었던 치료법은 [수 치료(hydrotherapy)]{.underline}와 <s>수면 치료</s>[^04-01-6]였다. 뇌의 과다 각성이 정신 증상의 원인이라 여겼던 의사들은 환자들을 얼음물이 든 욕조에 담가 저체온증을 유도하였으며, 의식을 잃으면 몸을 데워 체온을 되돌렸다. 한편 19세기 말, 20세기 초에 걸쳐 바비튜레이트와 같은 수면/진정제가 개발되자, 과도한 수면을 통해 과다 각성을 안정시키고자 시도하기도 하였다. 특히 Epifaneo, Kläsi 등은 지속수면요법을 써서 치료하였다. 며칠이고 잠이 들었던 환자들은 간혹 폐렴을 일으켜 사경을 헤매기도 하였다.[@Lehmann1997-mi]

[^04-01-6]: **수면 치료(prolonged sleep therapy)**: 1900년 중국 상해에서 일하던 Neil Macleod는 갓 발견된 수면제인 bromide를 이용하여 조증 환자를 잠재우는 치료법을 적용하였으며, 1년 뒤 H. Wolff는 Trionalkur라는 약물을 이용하여 수면치료를 행하였다. 이후 1910\~20년대에 Epifaneo, Kläsi 등에 재발견된 후 "prolonged sleep (*l'ipnosi prolongata*)" 혹은 "continuous narcosis (*Dauernarkose*)"이라는 명칭으로 정신질환 치료에 응용되었다. 1930년대부터 60년대까지 상당히 오랜 기간 동안 정신질환자 수용소에서는 바비튜레이트를 이용한 수면치료가 광범위하게 행해졌는데, 1970년대 말 호주 Chelmsford 사립병원에서 25명의 환자가 수면치료를 받다가 사망한 것이 알려지면서, 그 위험성이 세간에 알려지게 되었다.[@ban2001]

20세기 들어와 [쇼크(shock)]{.underline}라는 개념을 정신의학에 도입한 사람은 프랑스의 여성 정신과 의사였던 Pascal[^04-01-7]이었다.[@Benson2009-wk] 그녀는 정신질환을 [정신적 과민반응(mental anaphylactic reactions)]{.underline}이라고 정의하고, 이를 되돌리기 위해선 쇼크가 필요하다고 역설하였다. 그녀는 신경매독 치료에 성과를 보였던 발열요법에서, [열]{.underline}이 아니라 [쇼크]{.underline}가 치료의 주 요인이었다고 주장하였다. 이 이론에 따라 1930년대 이후 세가지 쇼크 요법, 즉 [인슐린 혼수요법]{.underline}과 [메트라졸 경련]{.underline}, 그리고 [전기경련치료]{.underline}가 경쟁적으로 연구되었다. 이중 모진 비판과 엄격한 평가를 이겨내고 현재까지도 유효한 치료법으로 자리잡은 것은 전기경련치료 뿐이었다.

[^04-01-7]: **Constance Pascal (1877\~1937)**: 루마니아에서 출신의 프랑스 정신과 의사. 당시만 해도 여성, 그것도 외국인 여성으로서 의사의 길을 가는 것은 매우 드문 일이었다. 그녀는 조현병의 생물학적 원인 뿐 아니라 심리적 외상, 사회적 유발 요인들에 대해서도 활발히 연구하였다.

인슐린 혼수 요법은 <s>사켈</s>[^04-01-8]에 의해 개발되었다. 사켈은 단순한 혼수가 아니라 긴장간대성 경련(tonic-clonic seizure)이 일어난 환자들이 치료 성과가 우수했다는 것을 관찰하고, [쇼크]{.underline}가 아니라 [경련]{.underline}이 치료에 핵심이라는 것을 알아내었다.[^04-01-9] 당시대의 학자들은 간질 환자에게 조현병이 드물게 발생한다는 관찰결과를 근거로, 간질과 조현병은 상극 관계에 있다고 가정하였다. 애초에 <s>메두나</s>[^04-01-10]는 간질 환자에게 조현병 환자의 피를 주사하여 경련을 치료하고자 하였으나, 이에 실패한 후 방향을 바꿔 조현병 환자에게 경련을 일으켜 긍정적인 치료 효과를 얻을 수 있었다. 처음에는 장뇌(樟腦, camphor)를 이용하였으나 이후 보다 안전한 <s>메트라졸</s>[^04-01-11]을 사용하였다. 인슐린 혼수요법이 2\~10%의 높은 치사율을 보였던 것에 비해, 메트라졸로 인해 사망은 거의 없었으며, 경련을 일으키는 속도도 빨라 치료 기간이 단축될 수 있었다.

[^04-01-8]: **Manfred Sakel (1900-1957)**: 비엔나에서 활동한 오스트리아 정신과 의사

[^04-01-9]: 사켈은 **경련**이라는 단어가 불러일으킬 혐오감을 피하기 위해 여전히 **혼수 요법(coma therapy)**이라는 이름을 선호했다고 한다.

[^04-01-10]: **Ladislas J. Meduna (1896-1964)**: 헝가리에서 활동한 정신과 의사이자 신경 병리학자

[^04-01-11]: **Metrazol**: pentylenetetrazol, pentetrazole (PTZ) 등으로 불리우는 이 약물은 원래 호흡부전 환자에게 자극제로 사용되었으나, 경련 유발 효과 때문에 현재는 실험 목적으로만 사용된다. 경련유발 효과는 GABA~A~ 수용체 길항작용 때문이다.

## 근대적 생물학적 치료의 개발

의학의 발전은 우연과 시행 착오 그리고 드문 행운으로 한걸음씩 전진해왔다. 정신증의 치료 역시 비록 잘못된 전제로부터 시작되었다 하더라도, 환자에게 도움을 주고자 하는 열망과 임상의사들 고유의 세밀한 관찰 그리고 실패를 반복하는 끈기와 집념을 통해 조금씩 실마리가 열렸다.

### 전기경련치료

간질 환자에게는 조현병이 생기지 않는다는 이론은 잘못된 전제였지만, 보다 안전하고 일관되게 경련을 일으킬 수 있는 방법에 대한 모색은 지속되었다. 이탈리아의 신경생리학자였던 <s>셀레티</s>[^04-01-12]는 가축 도살장에서의 경험을 통해 전기를 이용하면 경련 발작을 일으킬 수 있음을 일찌감치 깨닫고 있었다. 그러나 수없이 실험을 반복하였음에도 불구하고, 경련을 일으킨 동물 중 다수가 생명을 잃었기에, 인간에게 응용하기란 요원해보였다. 다행히 그의 조수였던 <s>비니</s>[^04-01-13]는 의사였음에도 전기 회로를 다룰 수 있는 기술이 있었고, 전류와 전압을 자유자재로 변경시킬 수 있는 장치를 조립하는데 성공하였다. 1938년 첫번째 인간 실험이 극적인 성공을 거둔 이후, 전기경련치료는 유럽을 중심으로 전세계에 보급되었으며, 거듭된 기술 혁신과 장비의 개선으로 안전하고도 효과적인 치료법으로 자리잡았다. 우리나라에서도 비교적 이른 시기에 도입되어 세브란스병원과 경성제국대학 의학부 부속병원에서 시행했다는 기록이 있다. 전기경련치료는 1940\~50년 대를 거치면서 한 때 정신증의 가장 확고한 치료법으로 자리잡는 듯 했으나, 1900년대 말에 발명된 <s>전기의자 처형</s>[^04-01-14]을 연상시킨다는 부정적 인식때문에 점점 기피되기 시작하였다. 치료 직후 발생하는 일시적인 기억 상실 문제때문에 이 치료를 받고 나면 바보가 된다는 우려가 있었고, 설령 치료가 되더라도 자발성, 창의성 등을 영영 잃게 된다는 편견이 널리 펴졌다.

[^04-01-12]: **Ugo Cerletti (1877\~1963)**: 이탈리아의 신경학자. Lucio Bini와 함께 전기경련치료를 개발하였다. 원래 신경 조직병리학을 전공했으며, 알츠하이머 치매 환자의 아밀로이드 침착(amyloid plaque), 신경교세포의 구조, 뇌-혈관 장벽에 대한 연구 등 다양한 업적을 남겼다.

[^04-01-13]: **Lucio Bini (1908\~1964)**: 이탈리아의 정신과 의사로 Cerletti와 공동으로 전기경련치료를 개발하였다.

[^04-01-14]: **전기의자 처형(electric chair execution)**: 고압의 전류를 흘려 죄수를 사형하는 데 쓰는 의자이다. Thomas Edison의 연구소에서 제작하였고, 1890년 처음으로 미국에서 실제 사형에 사용되었다. Edison은 당시 Nikola Tesla가 지지하던 교류 전기를 폄하하기 위해, 교류의 위험성을 부각시키고자 전기의자를 제작했다고 한다. 전기경련치료도 교류를 사용하기는 하나, 전압이나 전류 량이 낮고 펄스사각파(pulse square wave)를 사용하기 때문에 훨씬 안전하다.

### 백질 절제술

전기경련요법과 함께 정신과 치료에 부정적인 인상을 심어준 대표적인 치료가 바로 [전두엽 백질 절제술(frontal lobotomy)]{.underline}이었다. 두뇌에 수술적 개입을 함으로써 정신과 행동에 영향을 미치는 수술의 시작은 19세기 후반으로 거슬러 올라간다. 기록에 따르면 1888년 스위스의 의사 Gottlieb Burckhardt(1836\~1907)가 최초의 정신 수술을 시도한 것으로 되어있다. 영미권과는 대조적으로 독일어권 지역에서는 이러한 수술에 상당히 허용적이었으며, 백질 절제술을 도입한 Egas Moniz(1874\~1955)가 포르투갈 인이라는 것도 무관하지 않다. Moniz는 1935년 신경외과 의사인 Almeida Lima의 도움을 받아 최초로 전두엽의 백질 절단 치료를 수행했다. Moniz의 기법은 전 세계적으로 큰 반향을 일으켰으며 바그너-야우레크에 이어 1949년 노벨 의학상을 받았다.

Moniz는 결코 백질 절제술이 왜 치료효과가 있는지 밝혀내지 못하였다. 그는 정신병리가 백질 내 신경회로의 병적 연결이 고정되기 때문이라 제안하였다. 그리고 이 병리적 연결을 분쇄함으로써 자연적인 회복을 앞당길 수 있다고 믿었다. 초기에는 전두엽 백질에 알코올을 주입하는 시술을 했지만, 점차 특정 섬유를 절단하는 쪽으로 개선되었다. 미국에서 이 수술을 광범위하게 전파하여 악명이 높았던 <s>Freeman</s>[^04-01-15]은 시상과 전두엽 사이 섬유를 절단하는 것이 가장 효과적이라고 주장하였다. 그는 시상(hypothalamus)은 병적인 감정적인 내용을 사고에 전달하기 때문에, 이 섬유를 파괴함으로써 감정이 사고에 미치는 영향을 최소화해야한다고 믿었다.[@Braslow1999-ts]

[^04-01-15]: **Walter Jackson Freeman (1895\~1972)**: 미국의 신경과 의사. Moniz의 백질 절제술을 접한 후, 안구를 통해 두개골에 구멍을 내지 않아도 전두엽에 접근하는 **경안 전두엽 절제술(transorbital frontal lobotomy)**을 개발하였다. 이 수술법은 마취도 수술실도 필요로 하지 않았기 때문에, 만성 정신과 병원에서 수요가 급증하였고, Freeman은 얼음 깨는 송곳을 개조한 수술도구만을 들고 미국 전역을 돌아 다니면서 집도하였다. 그는 1936년부터 1967년까지 무려 4,000번이 넘는 전두엽 절제술을 시행하였다고 전해진다. 또한 미디어의 관심 받기를 좋아하여 수술 과정을 일반에게 공개하기도 하였다. 그에게 수술 받은 환자 중에는 그의 부주의와 경솔함으로 인해 뇌출혈을 일으켜 사망하거나 신경손상으로 심각한 기능 상실을 겪게된 환자가 적지 않았다.[@Kerner2017-kg]

1950년대 이전에 도입 된 모든 치료적 중재술 중, 백질 절제술는 초기부터 혹독한 비판에 봉착했으며, 의사들이 시술을 중단 한 후에도 오랫동안 비난과 조롱의 대상이 되었다. 도입되자마자 급속히 보급되었던 전기경련치료와는 달리 백질 절제술의 확산은 매우 속도가 느렸다. Freeman이 미국에 이 수술을 도입한 것이 1936년이었지만, 그거 명성을 얻은 것은 1940년대 후반 부터였다. 이렇게 각광받지 못했던 것은 비가역적인 수술에 대한 저항감뿐 아니라 만성 조현병 환자에서 그다지 효과가 명백하지 못하였기 때문이다. Moniz 역시 초조성 우울증에 가장 효과가 높고, 정신증에서는 가장 결과가 나쁘다고 보고하였다. 1940년대에 들어서야 비로소, 조현병에 대한 백질 절제술의 긍정적 효과에 대한 보고가 이루어졌고[@Strecker1942-xd], 그제서야 비로소 주립 병원 의사들을 중심으로 조금씩 수술이 이루어졌다. Moniz가 노벨상을 수상한 이후 미국을 중심으로 상당히 활발하게 백질 절제술을 행해졌지만, 1954년 클로르프로마진이 개발된 이후 너무나도 급작스럽게 이 수술은 종적을 감추었다.

아이러니컬하게도, 겉으로는 사이비 수술처럼 보였지만 백질 절제술 자체는 분명한 이론적 근거가 있었다. 예일 대학에서 미국 최초의 영장류 실험실을 개설했던 John Fulton (1899\~1960)은 1929년부터 전두엽 기능을 이해하는데 많은 열성을 쏟았다.[@Braslow1999-ts] 그는 전전두엽을 절제한 침팬지 한마리에 대한 관찰기록을 발표했는데, 바로 이 발표에서 아이디어를 얻은 자가 Moniz 였다. Fulton의 연구와 수술 후 환자들의 경과에 대한 관찰은 전전두엽의 기능 및 인간의 고위 인지기능에 대한 이해에 도달하는 실마리가 되었다.

### 한국에서의 치료

1917년 조선의학회잡지에 실린 논문에 따르면 우리나라에서 최초로 정신의학을 수련받은 분은 심호섭인데, 그가 지속수면요법을 시행했다고 되어 있다.[@1999-mq] 시대의 흐름과 함께 정신질환의 치료가 다양해져서 1930년대에 들어서서는 자가중독설을 근거로 하여 링거 액을 반복적으로 주사하는 수액치료법이 시도되었다. 유럽의 선진 치료법도 일본을 통해 비교적 빨리 도입되었다. 1930년대 중반부터는 인슐린 혼수요법, 화학적 쇼크 요법이 시도되었고, 전기경련치료 역시 시행되었다는 기록이 있다.[@1999-mq]

### 초창기 생물학적 치료법의 유산

위에서 살펴본 바와 같이 1950년대 이전까지 프로이트의 정신분석적 접근이 점차 영향력을 넓혀가는 와중에서도, 19세기 후반에 정립된 생물정신의학의 전통 하에 다양한 치료법이 등장했다가 소멸되기를 반복해왔다. 뇌기능이나 병태 생리에 대한 이해가 부족하고, 과학적 증거 보다는 개인의 신념에 근거하여 이론을 정립했던 시대에 고안된 치료법들은, 지금와서 돌아볼 때 지극히 원시적이고 조악하였다. 일부 환자에서 극적인 효과를 거두었다고 하나, 전체적으로 혜택 보다는 피해를 주었으며, 이는 모두 사회에서 소외되고 추방된 환자들이 감수할 수 밖에 없었다.

정신분석은 일부 부유층과 지식인들의 신경증적 고통과 존재론적 공허함을 달래주는데 기여했을 지 모르지만, 심각한 정신질환을 앓고 있던 환자들에게는 별 다른 도움을 주지 못했다. 항정신병 약물이 개발되기 전까지 이들 환자들은 사회에서 방치되어 있었고, 과밀하고 비위생적인 대형 정신병원에 수용되어 결핵이나 기타 전염병에 희생되는 사례가 비일비재하였다. 당시 한 기관에 수용된 조현병 환자의 사망률이 25%에 육박했다는 기록을 보면 상황이 얼마나 절박했음을 짐작할 수 있다.[@Gross2011-lq]

이러한 상황에서 어떤 식으로든 환자들을 관리하여 건강을 유지시키고, 부적절한 행동을 조절하여 사회로 돌려보내는 책임은 정신과 의사들에게 지워져 있었다. 치료법이 정말로 효과적인지, 윤리적으로 문제가 없는지를 하나하나 고려하기에는 너무도 암울한 상황이었다. 따라서 이 시대에 대한 맹렬한 비난은 현실을 도외시한 면이 없지 않다. 전기경련치료를 제외하고 당시 도입된 치료법이 더 이상 시행되지 않는다 해도, 이것이 생물정신의학의 실패를 의미하는 것은 아니다. 현대에 들어와서도 경련의 치료 효과는 분자생물학적 관점에서 끊임없이 재해석되고 있으며, 조현병의 제반 증상이 고위 인지기능의 이상 때문에 발현된다는 이론 역시 실패했던 전두엽 절제술의 유산이라고 볼 수 있다. 동일한 오류를 반복하는 인간의 역사와는 달리, 과학 발전은 끊임없이 앞을 향해 나아가고 있으며, 거듭되는 실패를 통해 지식을 쌓고 과거의 실패를 반복하지 않을 지혜를 획득한다. 현대의 생물학적 치료 역시 과거의 실패를 밑거름으로 여기까지 올 수 있었다.

## 클로르프로마진 이전의 약물들

인간은 오래 전부터 식물 뿌리나 차 잎사귀 등 자연으로부터 얻어진 산물을 이용하여 정신 상태를 변화시키려 애써왔다.[^04-01-16] 육신을 입은 채 신과 접하려 했던 고대 무당으로부터, 커피로 밤잠을 설치며 학문적 토론에 몰두했던 아랍인 들, 그리고 현대의 시름을 잊기 위해 오남용 물질에 손대는 현대인에 이르기까지, 향정신성 약물의 역사는 인간의 고뇌와 열망에 맞닿아 있다. 1800년대 들어서 기초적인 화학 기술이 눈부시게 발전하면서, 약리 작용을 일으키는 물질을 분리하여 순도를 높이는 방법이 강구되었다. 1806년 아편으로부터 모르핀이 분리되었고, 1817년에는 페탈라이트 암석으로부터 리튬이, 1826년에는 해초로부터 안정제로 쓰이는 브로마이드가 분리되었다. 새로운 화합물의 개발 역시 탄력을 받았다. 1832년 클로랄 하이드레이트, 1863년 바비튜레이트가 합성되어 마취제 및 수면제로 사용되었다. 또한 현대 항정신병 약물의 선조 격으로 페노타이아진 고리 구조가 1883년에, 암페타민 구조가 1887년에 밝혀졌다.[^04-01-17]

[^04-01-16]: **피토케미컬(phytochemical)**: 식물이 외부 유해 환경으로부터 스스로를 보호하기 위해 만들어낸 화학물질. 커피에 든 카페인을 비롯하여 니코틴, 모르핀, 코카인, 메스칼린, 에페드린 등이 이에 속한다. 이런 물질들은, 안정제, 흥분제, 환각제, 진통제 등으로 오랜동안 사용되어 왔으며, 종교적 목적으로는 의식 상태를 변화하여 영적 차원에 도달하기 위해 사용되어 왔다.

[^04-01-17]: 19세기 후반을 **알칼로이드의 시대**라고 부르기도 한다. 1806년 독일 약리학자 Friedrich Sertürner (1783\~1841)가 아편으로부터 모르핀을 분리한 이후, 탄소, 수소와 질소를 중심으로 구성된 다양한 알칼로이드가 추출 혹은 인공적으로 합성되었다. 이들은 즉각 안정제, 수면제, 진통제로 사용되었으며, 생물정신의학의 창시자로 일컬어지는 Griesinger는 모르핀을 수면 장애와 불안의 치료제로 추천하기도 하였다. 당시만 해도 그 독성이나 중독 위험에 대해 잘 알지 못했던 셈이다.

1800년대만 해도 조현병과 간질, 히스테리 발작은 질병분류학에서 전혀 구분되지 않았다. 수용 시설의 의사들은 치료보다는 환자들의 발작을 안정시켜야만 했고, 육체적 구속을 대신할 수 있는 방법을 찾아야만 했다. 모르핀은 갑작스런 분노발작이나 공격성을 가라앉히는데 안성마춤인 약물이었으나, 중독 문제가 심각하였다. 예를 들어 당시 정신과 환자에게 다양한 [칵테일 요법]{.underline}이 시도되었는데, 그 중 하나인 [Hyoscine Co A]{.underline}라는 것은 스코폴라민, 아트로핀 그리고 모르핀을 혼합한 것이었다. 1857년 Charles Locock(1799\~1875)은 potassium bromide를 복용시키면 히스테리성 발작을 줄일 수 있다는 것을 발견하였고, 이후 이 약물은 안정제 겸 항경련제로 널리 사용되었다.[@Eadie2012] Chloral hydrate는 최초의 수면제로서, 심리적으로 동요된 환자를 수면에 들게 함으로써 안정시키는데 이용되었다. 특히 이 약물은 모르핀과는 달리 경구 복용이 가능했기 때문에 병원이 아닌 가정으로 보급되었다.

1900년대에 접어들어 바비튜레이트(barbiturate)의 합성으로부터 진정/수면제의 혁명이 시작되었다.[^04-01-18] 특허권을 지닌 바이엘 사는 [베로날]{.underline}이라는 상품명 하에 바비튜레이트를 수면유도제로서 판매하였고, 베로날은 근대 유럽인에게 없어서는 안 될 약물이 되었다. 바이엘 사는 1912년에 phenobarbital 합성에 성공하였고, 이는 현재까지고 항경련제로 사용되고 있다.[@Lopez-Munoz2005-ii]

[^04-01-18]: 바비튜레이트는 독일의 약리학자 Adolf von Baeyer(1835\~1917)에 의해 합성되었다. 그는 이를 기반으로 독일 최대의 제약회사인 바이엘 사를 세웠고, 1905년에는 노벨 화학상을 수상하기도 하였다.

하지만 이러한 약물들은 어디까지나 소란스러운 조현병 환자를 일시적으로 안정시키는데 이용되었을 뿐, 망상이나 환각을 가라앉히는 효과는 얻을 수 없었다. 게다가 안정성에 문제가 있어서 고의로 혹은 실수로 과다 복용시 치명적인 경우가 잦았고, 중독이나 남용 문제도 심각하였다. 1930년대 들어서 정신분석의 영향력이 점차 강해지기 시작하였고, 조현병은 생물학적 원인이 아니라 부모의 잘못된 양육방식이나 사회 전반의 왜곡된 억압구조 때문에 일어난다는 이론이 널리 받아들여졌다. 생물학적 병인론은 막다른 길에 다다른 듯 했고, 미국과 유럽의 대학에서도 생물정신의학을 신봉하는 학자를 찾아보기 힘들었다.

## References {.unnumbered}
