---
title: "신경염증"
author: "정성훈"
bibliography: References/06-10.bib
---

## 신경염증

### 신경염증의 개요

뇌-혈관 장벽에 둘러싸여 있는 뇌는 오랜 세월 동안 체내의 면역 활동으로부터 고립된 성역으로 여겨졌지만, 이제는 뇌와 척수 안에서도 독자적인 면역 체계가 활동하며, 말초의 면역 체계와 활발한 정보 교환을 한다는 것이 분명해졌다. 다만 혈구세포 들이 주인공 역할을 하는 말초 면역 시스템과는 달리 중추신경계에서는 신경교세포(glial cell)가 그 역할을 떠맡고 있다.[@muldoon2013]

말초 면역 시스템과 마찬가지로 신경교세포를 중심으로 한 중추 면역 체계는 유해 자극에 반응하여 활성화되는데, 이는 소위 신경염증(neuroinflammation)을 일으킨다. 신경교세포 중에서 가장 잘 알려진 것은 미세아교세포(microglia)이지만, 이외에도 거대아교세포(macroglia)라고도 불리우는 성상세포(astrocyte), 희소돌기 아교세포(oligodendrocyte), 신경상피세포(neuroepithelial cell)가 존재한다. 이들은 중추신경 내의 모든 세포 중 90% 이상을 차지하며, 염증이 시작되기 전에는 구조적 혹은 기능적으로 신경세포의 생존과 기능을 보조한다.

신경염증은 미세아교세포 막에 부착된 <s>TLR 수용체</s>[^06-10-1]로부터 시작된다. 예를 들어 박테리아 단백질이 TLR에 포착되면, AKT, MAPK, mTOR를 아우르는 세포내 신호전달계를 거쳐 <s>NF-κB</s>[^06-10-2]가 활성화된다. NF-κB는 염증 유발 사이토카인의 분비를 촉진시키며, 그 결과로 주변에 위치한 미세아교세포 뿐 아니라 다른 거대아교세포들도 활성화된다. 미세아교세포는 그 자신이 대식구일뿐 아니라 항원을 T-세포에 전달하는 역할도 하며, 반응성 산소종(6-7-5-3절)을 비롯한 다양한 세포독성물질을 분비한다.[@shabab2017]

[^06-10-1]: **Toll-like receptor (TLR)**: 대식구, 미세아교세포와 같이 면역 체계에서 파수꾼(sentinel) 역할을 하는 세포의 세포막에 부착된 수용체이다. 세균, 바이러스 등 유해 항원을 감지하면 사이토카인 분비를 유도하여 주변 면역 세포들을 활성화시킨다. 이 명칭은 초파리(*Drosophila melanogaster*)의 toll pathway와 유사하다고 해서 붙여졌다.

[^06-10-2]: **Nuclear factor kappa-light-chain-enhancer of activated B cells (NF-κB)**: NF-κB는 대부분의 진핵 세포에서 발견되며, 모든 종류의 스트레스, 즉 사이토카인, 자유 라디칼, 중금속, 자외선, 산화물, 박테리아나 바이러스 등에 반응하여 면역 반응을 개시하도록 유도한다. 이외에도 신경계에서는 시냅스 가소성이나 기억의 형성에도 관여하는 것으로 보인다. NF-κB는 초기 유전자 유래 단백질 들처럼 항상 세포내에 일정농도 이상 존재하고 있으며, 단백질을 새로 합성할 필요가 없기 때문에 스트레스에 즉각적으로 반응할 수 있다.

신경염증은 유해 물질을 제거하고, 체내 방어력을 높이는 긍정적인 기능도 있지만, 지나치거나 너무 오래 지속되면 각종 신경퇴행성 질환의 원인이 된다.[@wysscoray2002; @ransohoff2015; @kwon2020] 정신과 영역에서도 오래전부터 알츠하이머 병과 같은 신경퇴행성 질환의 원인 중 하나로 지목되어 왔으며, 최근에는 주요 우울증을 비롯하여 조현병의 발병이나 악화 과정에도 개입되어 있을 것으로 짐작되고 있다. [@buckley2019; @troubat2021]

### 신경염증과 정신질환

비정상적인 신경염증이 일어나는 경로는 몇 가지로 나누어 생각해볼 수 있다. 아무리 뇌-혈관 장벽을 통해 말초와 중추 면역체계가 분리되어 있다고 해도, 사실은 끊임없는 양방향 소통이 이루어진다. 조현병 환자에서 항정신병 약물과 관계없이 다양한 면역 기능 이상이 발견된다는 것은 오래전부터 잘 알려져 있다. 만약 이와 동시에 뇌-혈관 장벽의 투과성에도 변화가 생긴다면, 전신의 항진된 염증 상태가 신경계에도 파급될 것이다.[@kealy2020] 하지만 중추신경계에서 비롯된 염증때문에 뇌-혈관 장벽이 붕괴되고, 흘러넘친 사이토카인이 말초 면역계를 활성화시킬 수도 있기 때문에, 어느 쪽이 원인이고 어느 쪽이 결과인지는 확실하지 않다.

어느 쪽이 원인이든 간에 미세아교세포가 비정상적으로 자극받거나, 활성화된 상태가 지나치게 오래 지속되면 주변 신경세포의 <s>괴사</s>[^06-10-3]나 <s>necroptosis</s>[^06-10-4]로 이어진다. 연구자들은 특별한 방사성 표지자를 써서 활성화된 미세아교세포를 PET로 직접 촬영하거나, <s>CD68</s>[^06-10-5]와 같은 단백질 표지자를 써서 미세아교세포 활성을 측정해왔다.[@tronel2017] 비록 모든 결과가 항상 일치한 것은 아니었지만, 대체로 조현병 환자에서 염증 수치가 높고 이들의 뇌가 항진된 염증 상태에 머물러 있다는 것을 관찰할 수 있었다. [@depicker2017]

[^06-10-3]: **괴사 (necrosis)**: 세포자멸사(apoptosis)와는 달리 외적 요인에 의해 준비가 되지 않은 세포가 사멸하는 과정이다. 세포자멸사가 대체로 주위 조직에 긍정적인 영향을 끼치는 것과는 반대로, 세포가 괴사하면 세포 내부의 독성 물질이 세포 밖 공간으로 흘러넘치면서 주위의 다른 세포도 괴사로 이끈다.

[^06-10-4]: **Necroptosis**: 염증 상태에 있는 세포가 사멸하는, 세포 사멸의 또 다른 기전이다. 괴사와는 달리 주변 조직에의 피해가 훨씬 덜 하기 때문에 programmed necrosis, 혹은 숙주의 면역학적 방어 기전 중 하나이기 때문에 inflammatory cell death라고 부르기도 한다.

[^06-10-5]: **CD68**: 대식구나 단핵구에 주로 발현되는 당단백질로서, 염증 조직이나 암 조직에서 면역활성세포를 염색할 때 주된 표지자로 사용된다.

정상적으로도 노화에 따라 신경세포의 수가 줄어드는데, 이 과정에도 미세아교세포가 큰 역할을 한다.[@schuitemaker2012] 미세아교세포 활성화로 인한 신경세포 소실이 <s>뇌 노화</s>[^06-10-6]의 척도라면, 조현병 환자는 <s>가속화된 노화</s>[^06-10-7]현상을 보이고 있다. 개체가 나이를 먹거나 누적된 스트레스가 많을 수록 미세아교세포는 스트레스에 대해 과민화된 반응을 보이게 되는데, 이를 **과민화(sensitized)** 혹은 **프라이밍(prmining)** 현상이라고 한다.[@niraula2017] 조현병이나 우울증을 비롯한 일부 정신질환이, 미세아교세포가 **프라이밍**되어 지나친 염증 반응을 보이기 때문에 일어난다는 가설도 등장하였다.[@tay2017]

[^06-10-6]: **뇌 노화 (brain aging)**: 40세가 지나면 뇌 용적이 10년마다 5% 정도씩 감소하며, 70세가 넘으면 이 속도 자체가 점점 더 가속된다. 용적 감소에는 백질의 수초가 줄어드는 것도 한몫하지만, 무엇보다도 뇌세포가 사멸하는 것이 가장 큰 요인이다. 줄어드는 뇌세포를 보상하기 유해 수상돌기가 점점 더 가지를 치기도 하나, 종국에는 시냅스 자체의 수도 감소하며 뇌내 도파민, 세로토닌 양도 줄어든다. 뇌 부위 중에서도 특히 전전두엽이 노화의 영향을 가장 많이 받으며, 이에 따라 고위 인지 기능도 감퇴한다.[@peters2006]

[^06-10-7]: **가속화된 노화 가설 (accelerated aging hypothesis)**: 조현병 환자에서 보이는 인지기능 및 신체기능의 점진적 쇠퇴가, 정상 노화 과정이 미지의 원인에 의해 점점 더 빨리 찾아오는 것이라고 설명하는 가설.[@schnack2016; @nguyen2018] 정상적인 노화 과정이 DNA의 메틸화 정도나 텔로미어의 단축으로 진행된다고 했을 때, 조현병 환자에서는 이러한 지표들이 생물학적 나이에 비해 훨씬 앞당겨져 있다.

한편 신경염증은 지금 현재의 뇌 기능을 손상시킬 뿐 아니라, 발달 단계의 뇌에서도 문제를 일으킬 수 있다. 신경교세포의 대식 작용은 정상적인 신경망의 구조 형성이나 시냅스 가지치기에 결정적인 역할을 한다.[@bilbo2012; @hong2016] 임신 중인 산모가 바이러스 등에 감염되면, 미세아교세포가 프라이밍되면서 청소년기에 접어들었을 때 격렬한 면역 반응을 일으킬 수 있다.[@perry2014] 이러한 산모의 면역항진 모델은 조현병의 유력한 동물모델로 사용될 정도로 조현병 발병과정을 설명하는데 도움이 된다.(5-3-3-3절) 그래서 학자들은 이 가설을 **"미세아교세포 활성화 가설 (microglial activation hypothesis)"**이라고 부르기도 한다.[@monji2009] 미세아교세포가 프라이밍되면 시냅스 가지치기가 지나치게 이루어져 정상적인 신경망 구성이 어려워질 수 있다.[@sellgren2019] 이는 Feinberg 가설에 대한 또 다른 증거로 간주된다.(6-7-3-2절)

### 항정신병 약물의 항염증 효과

재미있는 것은 조현병이 항진된 염증 상태라면[@comer2020], 항정신병 약물은 대체적으로 항염증(anti-inflammatory) 작용을 한다는 것이다. 물론 어떤 약물이 염증 유발(pro-inflammatory) 쪽이냐 항염증(anti-inflammatory) 쪽이냐를 구분하기란 쉽지 않다. 약물이 영향을 미치는 경로는 주로 특정 사이토카인의 분비를 자극하는 것인데, 개개 사이토카인조차 둘 중 어느 쪽인지 구분하기 어렵기 때문이다.[^06-10-8] 이 방면으로 가장 연구가 활발히 된 클로자핀은 대체로 항염증 쪽으로 분류되지만[@al-amin2013], 투여한 지 6주 정도까지는 염증 유발 쪽으로 작용하기 때문에 이 시기에 발열 반응을 일으키기도 한다.[@røge2012] 투여 초기를 무사히 넘어갔더라도 심근염, 췌장염, 이하선염을 일으키는 등 염증을 유발하는 것처럼 보이지만, 동시에 무과립구증과는 상관없이 폐렴 위험을 높이며, 비특이적인 항체 생성을 억제하는 등 면역 억제 효과를 보인다.[@song2000; @ponsford2019; @jeong2021] 이처럼 말초 면역체계에서는 어느 쪽인지 방향을 구분하기 힘들지만, 적어도 미세아교세포에게만큼은 항염증 쪽으로 작용하는 것 같다. 미세아교세포를 인공 항원인 lipopolysaccharide (LPS) 혹은 Poly(I:C)로 자극하였을 때(5-3-3-3절), 클로자핀을 함께 투여하면 염증 방응과 함께 신경독성이 현저히 줄어든다. 동시에 superoxide나 반응성 산소종 등 유해 물질 생성을 줄이며, 세포자멸사를 유도하는 TNF-α 생성 또한 억제한다.[@hu2012; @ribeiro2013; @vgiridharan2020] 이는 클로자핀이 Akt 경로를 억제하여, NF-κB가 활성화되는 것을 최대한 막기 때문으로 여겨진다.[@jeon2018]

[^06-10-8]: 예를 들어 interleukin-6 (IL-6)는 급성 염증상태에서는 항염증 효과를 보이지만, 만성 염증상태에서는 오히려 염증을 지속시키는 쪽으로 작용한다.[@gabay2006]

항염증 효과를 갖는 것은 클로자핀 뿐 아니라 많은 항정신병 약물에 공통되는 특징이다. Phenothiazine 계열 약물은 세포에 면역 자극을 주었을 때, IL-lb, TNF-α, IL-2, IFN-gamma, IL-4 등 염증 유발 사이토카인이 증가되는 것을 억제하며, 대신 IL-10 등 항염증 효과가 있는 사이토카인을 증가시킨다.[@pollmächer2000] de Witte 등[@dewitte2014]은 180명의 초발 조현병 환자에게 비정형 항정신병 약물로 치료하면서, 치료 전과 후의 IL-10 수치를 비교하였다. 그 결과 IL-10의 증가 정도는 PANSS 총점의 변화와 유의한 상관관계를 보였다. 한편 클로자핀을 비롯한 항정신병 약물들은 IL-18, IFN-γ 등의 농도를 높여 식세포 작용을 강화하고 항체 생성을 줄이기 때문에, 조현병 환자에서 치우쳐져 있던 type I/type II 면역 체계 비중을 정상화시킨다.[@jeong2021][^06-10-9] 이를 고려하면 클로자핀이 항체 생성을 줄이는 현상이 반드시 몸에 나쁘다고 말하기는 어렵다.[@ponsford2019] 혹자는 type I/type II 비율을 정상화시키는 현상이 비정형 약물에서 더 두드러진다고 말하나[@chen2012], 할로페리돌을 투여했을 때에도 유사한 면역조절 효과가 관찰된다. [@dacruzjung2016; @yamamoto2016]

[^06-10-9]: 말초 면역체계는 세포 매개를 주로 하는 type I (Th1)과 항체를 매개로 하는 type II (Th2)로 나누어진다.[@berger2000] 조현병 환자에서는 type I에 비해 type II가 차지하는 비중이 커지면서, 불필요한 항체 생성이 늘고 되려 식세포 작용(phagocytosis)이 둔해진다. 이를 조현병의 Th2 shift 가설이라고 한다.[@schwarz2001]

### 염증 반응과 대사 증후군

항정신병 약물이 면역 체계에 간과할 수 없는 변화를 가져오는 것은 분명하지만, 그것이 진정 치료적 효과인지, 단순한 부수현상인지, 아니면 대사증후군과 같은 부작용만 일으키는 것인지는 가늠하기 어렵다. 특히 사이토카인을 비롯한 면역체계의 혼란은 대사증후군 발생에 깊은 연관이 있기 때문에, 더더욱 혼란을 가중시킨다.

항염증 효과가 좀더 뚜렷한 클로자핀, 올란자핀 등의 비정형 약물은 체중 증가 효과도 큰 편이다. 염증 유발 사이토카인은 식욕을 떨어뜨리고 체중 감소를 유발하므로, 이를 거꾸로 뒤집으면 염증 유발 사이토카인을 줄여주는 항정신병 약물은 식욕을 항진시키고 체중을 증가시키는 쪽으로 몰고 간다고 볼 수 있다.[@fonseka2016] 염증 유발 사이토카인들은 <s>leptin</s>[^06-10-10], insulin과 함께 체내 <s>지방저장고</s>[^06-10-11]에 대한 정보를 시상하부의 <s>섭식 중추와 포만 중추</s>[^06-10-12]에 전달한다.[@ahima2006] 사이토카인은 이처럼 직접 시상하부에 정보를 전달하는 것 말고도 cholecystokinin (CCK)과 함께 미주 신경(vagus nerve)을 자극하여 포만 신호를 보내기도 하며, IL-1이나 TNF-α는 지방 세포에서 leptin 분비를 늘려 음식 섭취를 억제한다.[@fonseka2014]

[^06-10-10]: **Leptin**: 주로 지방세포에서 분비되는 호르몬으로, 시상하부, 배쪽 피개 영역에 작용하여 배고픔을 느끼지 못하도록 하며, 지방 세포에서는 지방이 축적되지 못하도록 막는다. 결과적으로 체중을 줄이는 쪽으로 작용하는데, 비만 환자들은 leptin에 대한 감수성이 떨어져있다고 한다.

[^06-10-11]: **Adipose tissue**: 체내 지방은 지방세포(adipocyte)에 저장되며, adipocyte가 밀집된 조직을 adipose tissue라고 한다. Adipocyte는 단순히 지방을 저장하는 것 말고도, leptin을 비롯하여 스테로이드 호르몬, 염증 유발 사이토카인, adiponectin, resistin 등 다양한 물질을 생성, 분비함으로써, 체내의 지방 저장상태를 시상하부에 전달한다.

[^06-10-12]: 시상하부의 arcuate nucleus (ARC)에는 사이토카인 수용체들이 밀집되어 있으며, 여기에는 1) 식욕을 떨어뜨리는 (anorexigenic) 신경세포와 2) 식욕을 증가시키는(orexigenic) 신경세포들이 분포되어 있다. 특징적으로 전자는 proopiomelanocortin (POMC)를, 후자는 neuropeptide Y(NPY)를 생성한다. 이들 신경세포들은 각각 좀더 상부에 위치한 시상하부 중추에 연결되는데, 바깥쪽에는 **"섭식 중추(feeding centre)"**가안쪽에는 **"포만 중추(satiety centre)"**가 자리하고 있다.[@ahima2008]

항정신병 약물이 이러한 사이토카인 체계를 뒤흔들면 체내 지방 저장상태에 대한 정보가 제대로 시상하부 중추에 전달되지 못하기 때문에, 칼로리 섭취를 줄여 항상성을 회복하려는 피드백 과정이 방해를 받는다. Klunge 등[@kluge2009]은 6주간 클로자핀 혹은 올란자핀으로 치료한 후, 다양한 사이토카인과 함께 leptin 농도의 시간에 따른 변화를 측정하였다. 그 결과 몇몇 사이토카인의 변화가 BMI 변화와 밀접한 연관을 지니고 있음을 관찰할 수 있었다. 아마도 사이토카인 체계의 교란은 체중 변화뿐 아니라 좀더 넓은 맥락에서 대사증후군에 영향을 미칠 것으로 예상된다.

체중이란 단순히 식욕만으로 설명되는 현상이 아니며, 인슐린을 중심으로 한 당과 지질 대사 이상, 좀더 나아가 에너지 항상성 자체의 변동으로 설명된다.[@faulconbridge2011] 그러나 항정신병 약물의 효과를 해석하는 지점에서 연구자들의 입장은 혼란스럽게 엇갈린다. 비정형 약물을 우호적으로 보느냐 그렇지 않느냐에 따라, 동일한 결과를 해석할 때도 정반대 방향으로 갈라지곤 한다. 앞서 항정신병 약물이 **항염증** 효과가 있고, 이 때문에 사이토카인이 포만 중추로 신호전달을 제대로 하지 못하여 비만에 이를 수 있다고 설명하였다. 이와는 대조적으로, 약물을 부정적으로 보는 학자들은 인슐린 저항성이 만성 염증상태에서 출발한다는데 주목하고[@donath2011], 항정신병 약물의 **염증 유발** 효과 때문에 체중 증가뿐 아니라 광범위한 대사증후군에 이르게한다고 주장한다.[@oconnell2014; @zhao2021] 이러한 해석의 혼란은 대사증후군에 관여하는 변수가 워낙 많고, 무엇이 원인이고 무엇이 결과인지를 가려내기 어렵기 때문에 초래된다. 비만은 대사증후군의 원인일수도 결과일수도 있으며, 마찬가지로 염증 역시 대사증후군의 원인일수도 결과일수도 있다. 비만으로 인해 복부의 <s>백색지방</s>[^06-10-13]이 팽창하게 되면, 이곳에서는 adipokine을 비롯하여 IL-6, TNF-α와 같은 염증 유발 사이토카인이 생성된다. 이들은 이어서 leptin 분비를 증가시키는데, leptin은 오히려 IL-6, TNF-α의 생성을 촉진시킨다.[@agrawal2011] 결과적으로 비만으로 인해 사이토카인 생성의 악순환이 자리잡을 수 있다는 뜻이다.

[^06-10-13]: 체내 지방조직은 크게 백색 지방(white fat)과 갈색 지방(brown fat)으로 나눈다. 후자는 미토콘드리아의 함량이 높아 갈색으로 보인다. 백색 지방은 성인의 주된 지방 저장 조직인데, 비해 갈색 지방은 영아에 주로 나타나며 성인이 될수록 감소한다. 전자는 저장이 목적이라면, 후자는 지방을 연소시켜 체온을 높이는 것이 목적이다. 한때, 백색 지방은 무조건 나쁘고, 백색 지방을 갈색 지방으로 전환해야 체중이 줄어든다는 식으로 소개되기도 했으나, 아직 확실한 증거는 없다.

농도가 증가된 IL-6, TNF-α은 이번에는 지방 세포의 inositol 경로를 방해하며, 동시에 인슐린 수용체를 이루는 tyrosine kinase의 활성 및 GLUT-4 포도당 수송체를 억제하여 당분이 세포 내로 들어가는 것을 방해한다. 이렇게 유발된 인슐린 저항성에 더하여 간세포로 하여금 지방을 분해하도록 유도하기 때문에 지질대사 이상까지 부가된다.[@leonard2012] 이렇게 보면 IL-6, TNF-α가 모든 악역을 담당하는 것처럼 보이지만, 앞절에서 지적했듯이 포만중추를 자극하여 식욕을 떨어뜨리는 것 역시 동일한 사이토카인이다. 이러한 복잡한 피드백 혹은 피드포워드 메커니즘 중에 항정신병 약물이 어디에 위치하느냐에 따라, 약물의 치료에 도움이 되는지 해가 되는 지를 판가름할 수 있을 것 같다. 한편 조현병은 항정신병 약물의 영향과는 독립적으로도 당 및 지질 대사 이상을 동반하고 있으니, 이 모든 변수와 조건들이 엮어내는 관계의 사슬을 이해하기에는, 원인과 이를 뒤따르는 결과라는 선형적인 사고는 역부족인지도 모르겠다.

## 산화 스트레스

### 산화 스트레스의 개요

세포 내 대사과정, 특히 미토콘드리아에서 에너지를 생성하는 <s>산화적 인산화</s>[^06-10-14]는 필연적으로 <s>반응성 산소종</s>[^06-10-15]이라는 부산물을 생성한다.[^06-10-16] 이들은 활성이 매우 높기 때문에 가만 놔두면 DNA 구성요소를 산화시켜 비가역적인 손상을 입히거나[^06-10-17], 세포막을 구성하는 지질을 산화시켜 구조를 망가뜨린다. 따라서 세포 내에는 이를 제거하기 유해 superoxide dismutase (SOD), catalase (CAT) 혹은 glutathione peroxidase (GPx) 등과 같이 ROS를 제거하는 기전을 마련해두고 있다.[@pizzino2017] 생성과 제거가 균형을 이룰 때는 별 문제가 되지 않지만, 외적 스트레스가 심해져 제거 역량에 비해 ROS의 생성이 과하게 되면 산화 스트레스(oxidative stress)가 세포에 부담을 주게 된다. ROS의 과다한 생성을 유발하는 유해 자극으로는 자외선, 이온화 방사선(ionizing radiation), 공해물질, 중금속, 박테리아, 바이러스, 약물 등이 있다. DNA에 손상이 가해지더라도 어느 정도 까지는 세포에 내장된 <s>수선 메커니즘</s>[^06-10-18]으로 수선이 가능하지만, 이런 손상이 누적되면 결국 세포가 죽게 된다. 사멸에 이르지 않은 세포라도 ROS가 축적되면 염증 유발성 사이토카인을 과도하게 분비하기 때문에 주변 세포에게도 부담을 주며, 전체적으로 조직의 노화를 불러 일으킨다. 신경계에서 이런 과정이 진행되면 미세아교세포 자체가 노화되면서, 과민화 혹은 프라이밍 현상을 일으킨다.[@niraula2017a]

[^06-10-14]: **산화적 인산화 (oxidative phosphorylation)**: 모든 세포는 당분을 분해해서 ATP를 만들어내며, 생성된 ATP는 세포가 즉각 사용할 수 있는 형태의 에너지를 실어나른다. 포도당(glucose)에서 에너지를 끄집어내는 과정은 1) **당 분해(glycolysis)**와 2) **산화적 인산화(oxidative phosphorylation)** 두 단계를 거친다. 체내로 흡수된 당분은 당 분해 과정을 거쳐 pyruvate로 분해되는데, 이때 산화 상태에 있던 NAD^+^가 NADH로 환원된다. 당 분해 과정 자체는 산소가 필요없으며, 이 과정 중에도 ATP가 생성되기는 하지만 효율이 그다지 높지 못하다. 미토콘드리아 내에서 일어나는 산화적 인산화는 당 분해보다 훨씬 효율이 높다. NADH (Nicotinamide adenine dinucleotide)는 높은 에너지의 전자를 지니고 있으며, 이 전자를 미토콘드리아 내부 막에 위치한 complex I에 전달한다. 이후 전자는 complex I에서 IV까지 차례대로 옮겨 다니다가 마지막에 산소에 전달되며, 여분의 전자가 결합된 산소(O~2~ ^-^)는 수소(H^+^)와 결합하여 물을 생성한다. 한편 전자가 지니고 있던 높은 에너지는 양성자 펌프인 complex I\~IV를 가동시켜 미토콘드리아 세포질에 있는 양성자(H^+^)를 지질막 바깥으로 뿜어낸다. H^+^의 이동으로 생긴 전하의 경사는 마지막에 ATP synthase로 하여금 ATP를 생성하도록 한다.

[^06-10-15]: **반응성 산소종 (reactive oxygen species, ROS)**: 자유 전자를 지난 산소가 포함된 화합물을 가리키는 용어로, 과산화물(peroxide, H~2~O~2~)과 초과산화물(superoxide, O~2~ ^-^)이 그 대표적인 예이다. 유리기 혹은 자유 라디칼(free radical)이라고도 부른다.

[^06-10-16]: 산화적 인산화의 마지막 단계에서 전자가 O~2~에 전달되면 O~2~  ^-^가 형성된다. 여기에 NADH로부터 떨어져 나온 H^+^가 붙으면 물(H~2~O)이 되어 모든 과정이 종료되는데, 아직 H^+^가 붙기 전의 O~2~  ^-^는 잉여 전자때문에 자꾸 주변 분자들에 결합하려고(산화시키려) 하여 매우 위험하다.

[^06-10-17]: DNA의 염기 중 하나인 guanine을 8-oxoguanine으로 변형시켜 버린다.

[^06-10-18]: **DNA repair**: DNA의 single strand 혹은 double strand가 다 끊어지더라도, 어느 정도는 무리없이 복구될 수 있다. 무척 다양한 기전들이 마련되어 있으며, 이를 집중적으로 연구한 Tomas Lindahl, Paul Modrich, Aziz Sancar는 2015년 노벨 화학상을 수상하였다.

물론 ROS가 반드시 해로운 것만은 아니다. ROS는 세포내 신호전달물질로 작용하기도 하며[@reczek2015], 미세아교세포와 같은 염증 세포들은 많은 양의 ROS를 생성하여 침입한 외부 물질을 중화시키는데 사용한다.[@simpson2020] 그러나 중추신경계는 유달리 산화 스트레스에 취약한 편이다.[@murray2021] 무엇보다 체내 산소 소모량의 20%를 뇌가 사용하기 때문에, 다른 세포보다 산화적 인산화가 훨씬 활발하다고 보아야 하며, ROS에 의해 변성되기 쉬운 <s>다중 불포화 지방산</s>[^06-10-19]이 풍부하다. 또한 신경세포는 글루타메이트 과활성에 의한 exicitotoxicity에 노출되어 있으며, 신경전달물질의 생성과 재활용 과정에서 생기는 중간 부산물 역시 산화 스트레스를 가중시킬 수 있다.[@cobley2018] [^06-10-20] 신경세포 내에서 ROS를 신호전달물질로 사용한다는 것은 조심스레 균형을 이루고 있는 <s>redox signaling</s>[^06-10-21]에 의지한다는 뜻인데, 이 균형은 쉽게 깨질 수 있다.[@maher2000]

[^06-10-19]: **다중 불포화 지방산 (polyunsaturated fatty acid, PUFA)**: 뼈대를 이루는 탄소체인에 두개 이상의 이중 결합(double bond)을 갖고 있는 지방산. 필수 지방산을 비롯하여 오메가 계열의 지방산 등은 불포화 지방산에 속한다. 이에 비해 음식으로 섭취하는 지방산에는 포화 지방산이 대다수이다.

[^06-10-20]: 단가 아민이 단가아민 산화효소에 의해 분해되면 amine + O~2~ + H~2~O -\> aldehyde + H~2~O~2~ + NH~3~의 과정을 거쳐 과산화수소(H~2~O~2~)를 만들어낸다. 또한 도파민은 자가산화(autoxidation) 과정을 거쳐 semiquinone radical을 만들어낸다.

[^06-10-21]: Redox signaling: 신호를 감지하는 단백질(예: 수용체)이 2차 메신저에게 정보를 전달할 때, 전자의 전달(산화/환원 과정)을 수단으로 삼는 신호전달. 과산화수소와 같은 ROS가 신호전달매개체로 사용된다.

### 산화 스트레스와 정신질환

산화스트레스에 의한 신경세포와 미세아교세포의 노화는 알츠하이머 병, 파킨슨 병을 비롯한 신경퇴행성 질환의 또 하나의 중요한 기전으로 떠올랐다.[@singh2019; @simpson2020] 산화스트레스가 제대로 해소되지 않으면, 미토콘드리아가 제대로 에너지를 생성하지 못하며, 희소돌기아교세포가 손상되어 탈수초화가 발생한다. 또한 parvalbumin 발현 사이뉴런의 NMDA 수용체가 기능부전을 일으켜 신경망 전체의 원할한 기능이 저해된다. 흥미롭게도 이러한 변화들은 조현병의 발병기전을 논할때 빠지지 않고 등장하는 요소들이기도 하다.[@bitanihirwe2011] 그 때문에 일찍부터 연구자들은 조현병 환자에서 산화 스트레스를 측정하고 이를 대조군과 비교해보고자 하였다. 이런 연구들에서는, 직접 <s>변성된 지질 성분</s>[^06-10-22]을 측정하기도 했지만, 대부분은 사후 뇌조직이나 혈중에서 다양한 항산화 효소의 농도를 측정해왔다.[@bitanihirwe2011]보고된 결과들이 항상 일치한 것은 아니지만, 종합해보면 변성된 지질 성분은 높게 측정된 반면, 항산화 효소 활성은 대부분 낮은 수치를 보였다. 산화 스트레스의 정도를 종적으로 관찰한 연구도 있었는데, 환자와 대조군의 차이는 환자가 급성기냐 만성기냐에 따라 그 특성이 조금씩 달라진다는 것을 발견할 수 있었다.[@solberg2019]

[^06-10-22]: **Lipid peroxidation products**: 대표적인 예로 malondialdehyde, 4-hydroxynonenal 등이 있다.

살아있는 환자의 뇌에서 산화 스트레스를 측정하기는 정말 쉽지 않다. 연구자들은 <s>MRS</s>[^06-10-23]를 이용하여 glutamate/glutamine의 농도비를 계산해보았는데, 전대상회(anterior cingulate gyrus) 및 전전두엽에서 측정한 glutamate/glutamine 비는 증상이 남아있는 환자에서 증상이 거의 없는 환자에 비해 유의하게 높았다.[@egerton2012]

[^06-10-23]: **자기공명영상분광경검사 (magnetic resonance spectroscopy, MRS)**: 인체 내에 있는 수소는 어떤 화학 구성물(분자)에 포함되어 있느냐에 따라 공명주파수가 약간씩 다르다.이 원리를 응용하여 수소 공명의 주파수 대역별 크기를 역으로 추적하면, 뇌 내 특정 화학구성물의 비율을 알 수 있다. MRS 그래프의 가로축은 주파수 대역을 표시하며, 세로축에서 해당 물질의 농도를 나타낸다.

### 항산화제의 치료 효과

만약 산화 스트레스가 조현병 발병을 유발하거나 증상을 악화시킨다면, 항산화제를 투여함으로써 증상 완화를 꾀할 수 있을 것이다. N-acetyl cysteine은 <s>glutathione</s>[^06-10-24]의 전구물질로서 한때 미토콘드리아의 기능을 회복시켜준다면서 치료에 적용되었다. 2008년부터 시작되어 10여년 동안 이루어진 연구들을 종합한 메타분석 결과 N-acetyl cysteine은 특히 조현병의 음상 증상을 호전시키는데 도움이 되는 것으로 나타났다. [@yolland2020]

[^06-10-24]: **Glutathione**: 세포 내에 존재하는 자연적인 항산화물질로, 과산화물을 분해하는 glutathione peroxidase의 cofactor이다.

오메가-3는 가장 손쉽게 사용할 수 있는 항산화제로, 치료 저항성 조현병 환자의 증상을 완화시키는데 도움이 된다고 한다.[@chen2015] 최근에 발표된 메타분석에서도 오메가-3를 포함한 eicosapentaenoic acid를 기존 항정신병 약물에 병용 투여했을 때 특히 양성 증상 감소에 도움이 되었으며, 더불어 중성지방 수치도 개선되었다고 한다.[@goh_effects_2021] 특히 오메가-3는 발병 후 시간이 많이 지난 환자보다는 전구기 환자에게 사용했을 때 조현병으로 전환되는 비율을 줄이는 것으로 나타나, 초기 정신증을 연구하는 학자들에게 특히 기대를 받고 있다.[@chen2015]

### 항정신병 약물이 산화 스트레스에 미치는 영향

몇 가지 항산화제들은, 단독으로 조현병 치료제로 사용되기는 역부족이라 하더라도, 발병을 예방하거나, 증상을 경감하고, 진행을 늦추는데 도움이 되는 것 같다. 그보다 궁금한 것은 기존 항정신병 약물이 산화 스트레스에 과연 어떤 작용을 하는가이다. 앞서 비정형 약물들이 미세아교세포의 염증 반응 및 신경독성을 줄여준다는 것은 언급한 바 있다. 그렇다면 산화 스트레스에 있어서도 긍정적인 효과를 보여줄 것인가? 아니면 오히려 스트레스를 가중시켜 부정적인 효과를 일으키는 것일까?

먼저 분명히 해야할 부분은 일부 항정신병 약물은 오히려 산화 스트레스를 가중시킬 수 있다는 점이다. 쥐에 할로페리돌은 투여하면 대표적 항산화 효소들인 <s>Mn-SOD</s>[^06-10-25], Cu/Zn-SOD, catalase 등의 활성이 떨어지고, 대신 변성된 지질(lipid peroxidation)이 증가한다.[@parikh2003] 후속 연구들에서 할로피리돌과 클로자핀은 또 다른 산화 스트레스의 지표인 <s>TBAR</s>[^06-10-26]을 증가시킨다.[@polydoro2004] 이후 축적된 데이터들은 매우 혼란스러워서, 약물의 종류, 투여 조건, 뇌 부위, 산화 스트레스의 지표 등에 따라 결과가 제각각이다. 그러나 큰 그림은 그려질 수 있는데, 정형 약물과 클로자핀은 산화 스트레스를 가중시키는 반면, 비정형 약물은 그런 효과를 찾아내기 어렵다는 것이다.[@pillai2007] 할로페리돌을 장기간 투여하면 예외없이 산화 지표가 나빠지는데, 이후 클로자핀, 올란자핀 등 비정형 약물을 투여하면 이들 지표가 정상화된다.[@pillai2007] 일부 연구자들은 산화 스트레스가 지연 운동장애의 원인이라고 여기기도 하는데, 비정형 약물이 지연 운동장애의 위험이 적은 것은 산화 스트레스를 덜 주기 때문인지도 모른다.[@lohr2003; @adams2019]그러나 비정형 약물 역시 산화 스트레스가 만만하지 않다는 주장도 있어, 섣불리 단언하기는 어렵다.[@panariello2020]

[^06-10-25]: 항산화 효소로 작용하는 superoxide dismutase (SOD)는 그 구조 내부에 금속을 포함하는 metalloprotein이다. 그 중에는 망간을 포함하는 Mn-SOD (SOD-2)와 구리/아연을 포함하는 Cu/Zn-SOD (SOD-1)가 있다.

[^06-10-26]: **Thiobarbituric acid reactive substances (TBARS)**: 지질의 과산화 과정에서 만들어지는 부산물인데, thiobarbituric acid에 반응하기 때문에 정량화 목적으로 많이 사용된다.

한편 항정신병 약물은 산화 효과 뿐 아니라 항산화 효과를 동시에 지니고 있으며, 두 효과가 서로 상쇄된다 하더라도 결과적으로는 항산화 효과가 우위에 있다는 주장도 적지 않다. 특히 비정형 약물은 산화-환원 균형(redox balance)을 바로잡고, 이 정도는 증상 호전 정도와도 상관관계를 보인다.[@dakhale2004] 만성 환자와는 달리 초발 환자는 산화 스트레스 지표가 그리 나쁘지 않을 뿐 아니라, 비정형 약물 치료를 한 후에 지표가 더 좋아졌다고 한다.[@kriisa2016] 정형 약물 역시 항산화 효과가 전혀 없지는 않다. 정형 약물로 6주 치료한 후 치료 전과 후를 비교해보았을 때 catalase 활성은 증가했으나, glutathione 활성을 반영하는 glucose-6-phosphate dehydrogenase (G6PDH)는 더 감소하였다.[@ivanova2014] 이처럼 항정신병 약물은 산화/항산화 효과가 어지러이 뒤섞여 있어, 뭐라고 잘라 말하기가 어렵다.

그래서인지 항정신병 약물이 가진 항산화 효과가 과연 치료에 보탬이 되는 지는 불확실하다. 도파민을 비롯한 단가아민의 분비와 대사과정에서 다량의 ROS가 생성되기 때문에, 시냅스 근방에 밀집되어 있는 항정신병 약물 분자들이 인근의 산화, 혹은 <s>질소화</s>[^06-10-27]된 분자들을 제거해줄 지도 모른다.[@sadowskabartosz2016] 신경세포 뿐 아니라 미세아교세포에서 비롯된 산화 스트레스를 줄이는 것도, 건강한 신경망을 유지하는데 절대적으로 필요하다. 미세아교세포가 염증 반응을 일으키면 ROS 생성이 과도해지며, 미세아교세포 자신 뿐 아니라 주변의 신경세포에 악영향을 미친다. 리스페리돈과 팔리페리돈은 미세아교세포에서 비롯된 염증 반응 및 산화 스트레스를 정상화시킨다는 연구 결과가 있다. [@macdowell2013; @caruso2020] 클로자핀 역시 항산화 효과를 통해 조현병 증상을 경감시킨다는 증거가 있다. 예를 들어 격리 양육(5-3-3-2절)되어 키워진 쥐는 변성된 지질의 증가와 함께 파동 전 억제의 결함을 보이는데, 클로자핀을 투여하면 두 현상이 동시에 교정된다.[@möller2013]

[^06-10-27]: **질소화 (nitration)**: 산화 스트레스 기전 중 하나로, NO로 부터 비롯된 활성 물질들이 단백질의 tyrosine 가지에 질소를 붙이는 과정을 가리킨다.

질병의 발병기전과 치료전략이 반드시 같은 방향을 가리키지는 않는다. 발병기전을 연구하는 학자들은 신경발달과정에 있는 세포들이 받는 지나친 산화 스트레스가 정상적인 신경망 발달은 가로막아 조현병이 생길 것이라 여긴다.[@do2009] 따라서 이미 발병한 후에는 산화 스트레스를 줄인다 해도 이미 늦었을 지도 모른다. 이를 지지하듯 항산화제를 치료에 이용하려 했던 연구들은 공통적으로, 발병 전에 예방 목적으로 사용했을 때 가장 뚜렷한 효과를 볼 수 있다고 말한다.[@sawa2014] 발병 이후에 산화 스트레스를 줄이려는 노력이 조금이라도 의미를 지니려면, 조현병의 황폐화 과정을 조금이나마 늦출 수 있어야 할 것이다. 조현병이 신경발달학적 질환이냐 신경퇴행성 질환이냐는 질문은 해묵은 논쟁거리이지만[@rund2009; @zipursky2013], 산화 스트레스가 신경퇴행 과정에 중요한 역할을 차지한다는 증거는 넘치고 또 넘친다. 항정신병 약물의 항산화 효과를 이용하여 신경퇴행을 최소화할 수 있다면, 그것만으로도 경과를 호전시키는데 한몫 할 수 있을 것이다.[@nishioka2004]

## References {.unnumbered}
