---
title: "약물 처방의 철학"
author: "정성훈"
bibliography: References/08-04.bib
---

## 근거와 경험

### 모두가 따르는 길과 자신만의 길

항정신병 약물은 **조현병을 치료하기 위함**이 아니라, 조현병에 걸린 **환자를 돕기 위해** 사용된다. 정신과에 처음 발걸음을 내딛는 초심자들은, 약물들이 효과 면에서 대동소이하기 때문에 부작용 특성을 보고 선택하면 된다고 여긴다. 이 말은 시험 답안으로서는 맞을지 모르지만, 경험많은 임상가 입장에서는 영 마땅치 않다. 물론 기존의 어떤 임상연구도, 클로자핀을 제외하고는, 특정한 약이 다른 약보다 더 우수하다는 것을 입증하지 못하였다. 비정형 약물이 도래한 후에도, 정형 약물보다 더 나은 효과를 기대하기는 어려웠고, 그저 안전성에서 일보 전진한 것에 지나지 않았다. 그러다보니 "왜 항정신병 약물이 여러 종류가 필요하느냐"는 병원 경영진의 추궁을 받기도 한다.

그러나 비열등성은 어디까지나 **환자 집단**에 해당하는 것이지, **개별 환자**에 해당하는 것은 아니다. 개별 환자에게는 분명, 그의 독특한 증상과 체질에 가장 들어맞는 약물이 따로 있기 마련이다. 이를 찾아내는 일은, 몇 가지 약물 중에서 어느 하나를 선택하는데 그치는 것이 아니라, 이들이 어울려 만들어내는 무궁무궁한 조합 중에서 가장 최적의 조합을 선택해야 하는 과제이다. 이를 해내는데 필요한 지식은 그 어떤 서적이나 논문도 알려주지 않는다. 초심자들은 교과서에 실려있는, **모든 이가 따라야 한다고 적힌**, 도그마(dogma)를 손에 들고 여행을 시작하지만, 몇 걸음 디디지 않아 손에 든 도그마가 별 도움이 안 된다는 것을 체득한다. 여행을 멈추지 않는 용기있는 의사들은, 책에서 접해보지 못했고 이해하기조차 힘에 겨운 환자들의 사례를 헤치고 나아가면서, 점차 자신만의 고유한 시각을 키워나간다.

흔히 약물 처방은 **확고한 근거**에 기반해야 한다고 강조된다. 그러나 메타 연구와 체계적 문헌고찰의 홍수 속에서도, "아직도 명확한 근거는 제시되지 않고 있다"는 어정쩡한 결론에 실망하게 된다. 모두가 따르는 길을 고수할 수도 있지만, 스스로의 경험을 비판적으로 되돌아보면서, 자신만의 지식을 축적해나가는 것도 못지 않는 미덕이다. 환자의 상황과 약물의 작용 기전을 대조해가며 전략을 세우고, 시행 결과를 통해 가설을 수정하여 다음 전략을 마련하는 일련의 반복된 과정은, 자신만의 시각을 키워나가는 재료가 된다. 성공 사례는 가설을 굳건히 하는 밑거름이 되며, 실패 사례는 스스로의 생각을 되짚어보는 계기가 될 것이다. 매일 매일 맞닥뜨리는 상황에서 근거는 항상 부족하다. 이러한 불확실성을 견뎌 나가기 위해서는 부단히 축적한 지식과, 세월을 통해 연마한 날카로운 감에 의지할 수 밖에 없다.

그렇다고 모두가 가는 길에서 너무 동떨어져도 된다는 뜻은 아니다. 약물 선택에 조금씩 자신감이 붙기 시작할 때, 자칫하면 독단 혹은 자신만의 왜곡된 논리에 빠지기 쉽다. 따라서 항상 약물을 선택할 때에는 다음 함정에 빠지지 않았는지 스스로를 돌아봐야 한다.[@crumlish2009]

1.  

    가용성 바이어스(availability bias)

    :   쉽게 생각해낼 수 있거나 접근하기 쉬운 정보에 근거해서 결정하는 편향성 (최근에 학회에서 소개받았던 처방을 그대로 사용한다 혹은 최근에 좋은 효과를 거두었던 약을 반복해서 사용한다)

2.  

    확인 바이어스 (confirmation bias)

    :   원래 기대했던 바에 부합하게, 실패 사례를 각색하는 편향성 (클로자핀을 6개월 사용해도 호전을 보이지 않는 환자에 대해, 클로자핀은 효과를 나타내는데 원래 오래 걸리는 법이라며 수긍한다)

3.  

    고정 바이어스 (anchoring bias)

    :   여러 가능성을 생각하지 않고, 처음에 내렸던 선택을 끝까지 밀고 나가는 편향성 (주의력이 떨어진다는 말만 듣고 ADHD 약물을 처방한 후, 주의력 발휘를 막아온 다른 정신질환에 대한 탐색을 중단한다.)

4.  

    커미션 바이어스 (commission bias)

    :   아무것도 안 하는 것보다는 무엇이라도 하는 것이 옳다고 믿는 편향성. (조증 삽화를 겪은 지 얼마 되지 않은 환자가 무력감을 호소하면, 선뜻 항우울제를 처방한다.)

약물을 처방한다는 것은 부실한 지도와 흔들리는 나침판만 갖고 대양을 건너는 것과 같다. 본서 역시 부실하기 짝이없는 지도를 소개할 수 밖에 없다. 그러나 명심할 것은 이렇게 부실한 **근거**와 **원칙**이라는 것도, 사실은 선배 정신과 의사들이 각자 혼자만의 길을 외롭게 걸어가면서 조금씩 얻어낸 경험의 집적이라는 것이다.

### 근거중심의학과 예술로서의 의료

허가된 적응증에 허가된 용량을 썼다 할 지라도, 효과나 부작용은 개개인마다 커다란 차이를 보인다. 이러한 차이를 이해하고자 약물유전학이 발전했고, 몇몇 야심찬 연구자들은 개인의 유전형을 통해 맞춤형으로 약물을 찾아낼 수 있다고 자신한다. 개인별 맞춤의료나 정밀의료라는 슬로건은 이러한 염원의 결정체로, 개인의 유전정보를 비롯하여 신체와 관련된 모든 정보를 알고리즘에 입력하여, 최적의 치료 프로토콜을 만들어낼 수 있는 날을 꿈꾼다.

물론 기술의 발전과 정보의 집적을 통해 이런 꿈은 조금씩 현실에 가까워지고 있다. 그러나 그 꿈이 어느 정도 이루어진다 하더라도 여전히 그 효용성은 제한적이다. 아무리 인공지능 알고리즘이 발달한다 해도, 그 타당도를 결정하는 것은 알고리즘 자체가 아니라 학습에 사용된 데이터이다. 그런데 임상 시험에서 얻어지는 데이터와 실제 임상에서 경험하는 데이터는 일치하지 않는다. 과학이라는 이상에 다가가기 위해 표준화, 규격화에 매달릴수록 실재하는 세상과 거리가 멀어진다. 마찬가지로 엄격한 진단기준을 적용한 양질의 임상 시험일수록 진료실에서 매일 마주치는 환자들과는 동떨어져 있다.

이러한 갈등은 예로부터, 잘 설계된 임상시험과 자연적 연구(naturalistic study) 간의 결과 차이라는 문제로 꾸준히 논의되어 왔다.[@katona2021] 예를 들어 임상 시험은 반드시 피험자의 자발적인 동의를 요하는데, 동의를 했다는 것은 어느 정도 협조가 되고 병식이 갖추어져 있음을 의미한다. 따라서 정말 비협조적이고 치료를 거부하는 환자들은 근본적으로 임상연구에 포함될 수 없다. 또 다른 예로 과거에는 임상 연구가 서유럽 백인을 중심으로 행해졌기 때문에, 얻어진 결과를 소수 인종에 적용하는데 애를 먹었다. 하지만 현재는 상황이 바뀌어, 많은 임상 연구가 비용이 싸고 윤리 기준이 느슨한, 동유럽, 중국, 인도, 아프리카 등에서 이루어진다. 이렇게 얻어진 결과를 서로 다른 인종과 민족에게 가감없이 적용할 수 있을지는 의문이다.

아무리 기술이 발전한다고 해도, 획일화, 규격화된 알고리즘은 실제 세계에 존재하는 다양성(heterogeneity)을 반영하기 힘들며, 따라서 대표성(representativeness)에 문제가 있다. 고유한 생물학적, 사회적, 문화적 상황에 처해있는 의사는 환자와 협력관계를 맺은 상태에서, 증상은 어떻게 변화하고 환자는 어떻게 반응하는지, 그가 가장 가치를 두는 것이 무엇이며 지금 당장 필요한 것은 무엇인지를 고려하여 처방을 다듬어 나간다. 이 모든 과정에는 **근거** 뿐만 아니라, 의사의 **인격**이 필요하다. 근거중심의학은 근거에서부터 출발하라는 뜻이지, 근거에 얽매여 제자리에 머물라는 뜻은 아니다. 의사는 자신의 논리와 감정, 감각과 직관을 모두 활용하여야 하며, 이는 과학과 예술 그 중간 어딘가일 것이다.

## 약물 사용의 일반 지침

"마음의 고통을 약물로 치료할 수 있는가"는 모든 정신과 의사들의 풀리지 않는 의문점이다.[^08-04-1] 정신약물학이 아무리 발전하고 수많은 약물이 쏟아져 나와도, 여전히 내가 사용하는 약물이 과연 환자의 고통을 줄여줄 수 있을 지는 아무도 자신하지 못한다. 약물이라는 무딘 칼을 들고, 적과의 싸움에서 승리하기 위해선 몇 가지 지켜야할 일반 지침이 있다. 이는 약물을 최대한 효율적이고 안전하게 사용할 수 있는 요령이라 할 수 있다.

[^08-04-1]: Joseph Davis는 저서 "마음이 병이 될 때: 힘겨운 마음은 약물로 치유 가능한가"에서 마음의 고통에서 삶을 배울 수 있는 기회를 배제하고, 점점 더 그 원인을 생물학적 오류로 돌리려는 현대인의 심리를 지적한다.[@davis2020]

1.  

    허가된 적응증을 정확히 파악한다.

    :   약물의 허가된 적응증이나 용량은 유용한 길잡이라기 보다는 자율권을 얽매는 고루한 제약처럼 느껴질 때가 많다. 게다가 허가 사항이 과학적 증거말고도, 제약사의 영업 전략에 영향을 받는다는 사실도 부인할 수 없다. 그러나 적어도 허가된 내용은 대부분의 환자에게 이득을 가져다주며, 최소한의 안전을 보장해주는 안전망이다. 오프라벨 사용이 반드시 부적절한 것은 아니지만, 그럴때는 결정을 뒷받침할만한 합리적인 근거가 있어야 한다. 이 떄는 환자와 충분히 논의되어야 하며, 문서화된 동의가 필요할 수도 있다.[^08-04-2]

2.  

    위험에 비해 이익이 상회해야 한다.

    :   증상 개선의 가능성이 부작용의 위험을 상회해야 하며, 대체 가능한 다른 안전한 치료법보다 우수해야 한다. 위험과 이익의 균형은 임상적 판단에 기반하되 환자의 견해와 가치관을 반드시 고려한다.

3.  

    불필요한 복합처방을 피한다.

    :   동일한 치료 타겟에 대해 병합 요법, 증강 요법 등의 이름으로 행해지는 다약제 병용(polypharmacy)은 원칙적으로 추천되지 않는다. 이는 대개의 경우 효과보다는 부작용 위험만 증가시킨다. 하지만 다약제 병용에 대한 학계의 태도는 시대에 따라 달라지며, 약을 조합함으로써 생각지도 못한 효과를 얻어내기도 한다. 꼭 필요하다면 망설이지 말되, 목표와 근거를 명확히 해야 한다. 특히 이전 약물을 새 약물로 교체하는 교차 적정(cross-titration) 과정에서 어정쩡하게 복합처방이 되는 기간을 최소화한다.[^08-04-3]

4.  

    약물 치료는 광범위한 치료 계획의 일부분이다.

    :   약물 치료는 반드시 심리사회적 중재와 함께 이루어져야 한다. 스트레스를 줄이고, 행동을 교정하며, 필요하다면 환자를 둘러싼 환경도 개선해야 한다. 약물 치료를 전공했다고 해서, 상담치료나 인지행동치료를 등한시해서는 안 된다.

5.  

    치료 결정에 환자를 참여시킨다.

    :   공유된 의사결정은 이제 예외가 아니라 표준이 되었다. 조현병 환자가 이 과정에 제대로 참여할 수 있을지는 상황에 따라 다르겠지만, 가능하다면 환자가 치료적 결정에 참여할 수 있어야 한다. 환자가 주도적으로 치료 결정에 관여할 때 순응도가 높아지고 장기적 예후가 향상된다.

6.  

    부작용에 대해 환자와 미리 논의한다.

    :   정신과 약물은 광범위한 부작용을 일으킬 수 있다. 그중 일부는 객관적으로 인지할 수 있지만, 나머지는 환자의 주관적 경험세계에서만 알 수 있다. 심각한 부작용뿐 아니라 사소해 보이는 부작용 역시 치료 전과 치료 중에 환자와 상의한다. 환자가 부작용임을 모르는 경우가 많으므로, 가능한 부작용에 대한 정보를 제공하고 체계적으로 질문하여 평가한다.

7.  

    순응도를 정기적으로 점검한다.

    :   약물 치료가 실패하는 가장 큰 이유는 환자가 약을 먹지 않는 것이다. 고전적으로는 낮은 순응도를 병식 부재의 탓으로만 돌렸으나, 이제는 의사가 추구하는 목표와 환자가 추구하는 가치가 서로 일치하지 않았기 때문이라는 반성의 목소리가 높아지고 있다. 병식이 없더라도 치료에 응을 할 것 수는 있다는 것을 명심하고, 환자를 치료 결정에 적극적으로 참여시킨다. 병식의 문제는 물론, 환자들이 약물에 대해 가지고 있는 비합리적 걱정에 대해서도 다룰 필요가 있다.

[^08-04-2]: 미국에서 오프라벨 사용은 법적 소송의 단골소재이다. 물론 이런 소송에서는 처방을 낸 의사를 벌하기 보다는, 제약사가 의도적으로 오프라벨 사용을 부추겼는지를 심판한다.

[^08-04-3]: 이전 약(A)을 다음 약(B)으로 바꾸기 위해, A를 조금 감량하고 B를 새로 추가한 상황에서 환자가 호전되면, 환자는 물론 의사도 현재 처방을 그대로 유지하고 싶은 유혹을 받는다. 그러나 이런 어정쩡한 상황을 그대로 유지하면, A와 B 중 호전이 어느 약물때문인지 알기 어렵고, 나중에 유사한 상황에 부딪혔을때 또 다시 A와 B를 섞여 쓸 수 밖에 없게 된다. 따라서 가급적이면 B로의 교체를 완결짓는 것이 좋다.

## 환자에게 약물이 갖는 의미

"병에 걸렸으면 당연히 약먹고 치료해야지"라는 전통적인 사고방식에서부터, "약물에 의해 변화된 나는 진정한 내가 아니다"라는 실존적 관념까지, 환자가 약에 대해 가지는 생각과 환상은 가지각색이다. 같은 환자라도 약에 대해 긍정적 인식과 부정적 인식이 뒤섞여 있는 수가 많으며, 스스로도 자신의 관념을 인식하지 못하고 있을 때도 많다. 그러나 특히 정신과 약물에 대해서는 부정적 인식이 더 많은 편이며, 이는 순응도를 저하시킨다.

### 자율성과 통제감 상실

자신이 병에 걸렸다는 사실을 인정하는 환자들조차 의사의 처방을 순수히 따르지 않는다. 심지어 외래 치료에 꼬박꼬박 맞추어 오고, 약이 떨어지면 큰일날 것처럼 굴어도, 실제로는 약을 매일 안 먹거나, 이것저것 골라 먹곤 한다.

현대 사회는 무수히 많은 정보가 제공되고 선택의 폭이 넓기 때문에, 소비 형태도 많이 달라졌다. 소비자들은 사소한 물건 하나라도, 구입하기 전에 샅샅이 정보를 검색하여 유사한 제품 들의 가격과 품질을 서로 비교하며, 경험자의 사용기를 참조하여 자신에게 맞는 물건이 맞는 지 고민한다. 요컨데 필요하니까 물건을 산다는 개념에서 나아가, 구매 행위 하나하나가 큰 프로젝트가 되었다. 이에 비해 의사의 약물 처방은 일방적인 구매강요에 가깝다. 새로운 소비 형태에 익숙해진 환자들은 자신이 받은 처방에 대해 최대한 정보를 모으며, 충분히 수긍되기 전까지 받아들이기를 미룬다.

환자들의 이러한 **고집**은 원활한 치료를 방해할 수 있다. 치료의 주도권을 놓지 않으려는 의사와 자율권을 방어하려는 환자는 종종 대치 상태에 놓인다. 싸움을 싫어하는 환자들 역시 자율성과 통제감을 유지하기 위해, 의사에게 말하지 않고 자기 멋대로 약을 복용한다. 어떤 환자들은 자기 식대로 약을 복용하였더니 증상이 좋아졌다며 자랑스레 의사에게 보고하지만, 이는 의사의 오류를 지적함으로써 자신의 통제력을 되찾아오려는 노력이기도 하다. 여기서 한걸음만 더 나아가면 약을 먹지 않고도 질병을 다스릴 수 있다는 자신감으로 확장된다.

이런 상황은 비순응으로 이어져 결국 환자의 미래를 망가뜨리지만, 개인이 자신에게 가장 이로운 것이 무엇인지를 스스로 찾아나서 결정한다는 의미에서는 긍정적이다. 의사는 이런 환자를 치료적 결정에 적극 참여시킴으로써, 환자가 자율성을 발휘할 여지가 있음을 확인시켜준다. 일부 논쟁적인 환자들은 약물 치료에 내재된 **생물학적 환원주의**와 거대 제약 산업의 영향력을 비난한다. 의사는 이러한 문제는 모든 정신과 의사가 함께 고민하는 부분이라며, 오히려 환자를 자기편으로 끌어들일 수 있다. 쟁점이 많아진다는 것은 환자가 의사의 지시에 무조건 저항한다기 보다는, 자신의 생각을 존중해주기를 원하는 것이다.

### "나"를 변화시키지 않는 선에서의 타협

조현병을 포함한 만성 질병의 문제점은 "나는 원래 이랬던 사람이야"라는 포기 반, 순응 반의 감정이 자리잡는다는 것이다. 환자들은 더 이상 입원하지 않기 위해, 가족들을 기쁘게 하기 위해, 직장에서 해고당하지 않기 위해 약을 복용하지만, 근본적으로는 약을 먹어도 아무것도 달라질 것이 없다고 믿는다.

외래에 규칙적으로 등원하는 조현병 환자들에게 왜 약을 먹느냐고 물어보면, "약을 안 먹으면 잠을 못 자니까"라는 답이 가장 많다. 즉 이들은 약물의 효과를 실감해본 적도 없고, 그것이 자기 인생에 얼마나 도움이 되는지 느껴보지도 못했다. 이들은 현 상황이 유지되는 동안에는 약물 치료에 순응하지만, 환경이 달라지면 바로 저항할 가능성이 높다. 예를 들어 만성 조현병 환자가 결혼을 하게 되면서, "더 이상 약 먹는 가장이 되기는 싫어요"라고 말하는 경우이다.

심지어 어떤 환자들은 환청을 **또 다른 자기(the other self)**로 받아들인 나머지, 환청이 없는 삶을 상상하지 못한다. 예를 들어 환청을 외로움을 달래주는 벗이요, 결정을 대신 내려주는 부모같은 존재, 더 높은 의식 수준으로 이끌어주는 지혜로운 목소리라고 묘사하는 환자들이 있다. 매우 정교하고 체계화된 망상을 품은 환자는, 자신이 얼마나 끈질기게 노력하여 이러한 깨달음에 도달하게 되었는지 자랑스러워한다.

만약 이런 환자들이, 약물 치료를 하는 이유가 바로 이런 현상들을 뿌리뽑기 위한 것이라는 점을 알게되면, 자신의 정체성 중 일부를 제거하려는 공격으로 받아들인다. 그리 거부적이지 않은 환자들조차, "내가 잠을 못 자고 가끔 불안해지니까 약을 먹기는 하지만...나머지 약은 먹고 싶지 않아요"라면서, 자기 자신을 근본적으로 바꾸는 것은 거절한다.

이런 저항에 맞닥뜨린 의사들은 환자의 생각에 일부분 맞장구 쳐주며, 일부 증상이라도 조절하여 고통을 줄이기 위해서는 약이 필요하다는 식으로 은근슬쩍 넘어가곤 한다. 그러나 가끔은, 비정상적인 것은 어떻게 뒤집어도 비정상적이요, 환자가 고집하고 있는 인격의 일부를 포기하면 훨씬 더 다채롭고 가능성이 풍부한 현실이 기다리고 있다고 알려주어야 한다.

### 치료자를 대신하는 약물

항정신병 약물을 오랜 기간 먹어야 한다는 사실을 받아들인 환자들은, 동시에 자기 인생의 일부분을 의사에게 맡겼다고 생각한다. 그들은 정신과 의사에게 온갖 신체 증상을 상의하며, 다른 약을 먹어도 되는지, 수술은 받아도 되는지 등을 묻는다. 더불어 결혼하여 아이를 가져도 되는지, 어떤 자격증을 따야 하고, 직업은 어떤 것을 가져야하는지 인생행로 전반에 대한 질문에도 답해주기를 바란다.

한번 의사에게 의지하기 시작하면, 약물은 의사를 만나지 못하는 동안 자신을 지탱해주는 이행 대상(transitional object)이 되어버린다. 약은 다음 번에도 의사를 만날 것이라는 약속이자 통행증이다. 가끔 상담만 하고 싶다는 환자들이 있는데, 이들이 몇번 오다가 마는 것은 처방이 없는 관계의 끈은 끊어지기 쉽기 때문이다. 어떤 환자들은 처방이 바뀌는 것을 잘 받아들이지 못하는 것처럼, 의사가 바뀌는 것도 힘들어한다. 동일한 약을 처방한다고 해도 새로운 의사를 못 미더워하며, 자기 주치의에게서 약을 타가기 위해 먼 거리를 왕복하는 것을 무릅쓰기도 한다.

역으로 의사에 대한 불신과 반감을 약에 투사하기도 한다. 의사와 우호적인 관계를 갖지 못한 환자는 약물에 부정적인 태도를 보인다. 약물에 대한 태도는 의사 뿐 아니라, 단골로 거래하는 약국, 주사를 놓는 간호사와의 관계에 따라 달라지기도 한다. 따라서 약물 순응도를 높이기 위해서는 **환자가 평생 믿고 의지할 수 있는 의사**라는, 어쩌면 조금은 신경증적인 관계를 유지할 수 있어야 한다.

### 공권력의 도구

인류의 역사는 고압적인 계급 사회, 전제군주 사회에서, 모든 국민이 기본권을 누리고, 평등한 관계를 유지하는 민주주의 사회로 발전해왔다. 그럼에도 불구하고, 사람들은 자신들이 보이지 않는 공권력에 의해 제약을 받는다고 믿는다.[^08-04-4] 환자들은 자신이 문제가 있음을 시인하면서도, 약물 투여는 그러한 자신을 "올바르게" 바로잡으려는 숨겨진 권력의 의도라고 믿는다. 그러한 환자들은 급성 증상에 대한 약물 치료에는 어렵사리 동의할 수 있지만, 유지 치료를 받아들이지 않는다. 또한 흥미롭게도 수면제, 안정제에 대해선 쉽사리 순응하면서도, 항정신병 약물에 대해선 거부한다.

[^08-04-4]: 이러한 막연한 불안은 Michel Foucault에 의해 생생하게 표현되었다. 그는 지식 체계 자체가 공권력이 민중을 억누르기 위해 마련된 제도적 장치라고 주장하였다. 그는 ***광기와 문명: 계몽주의 시대의 광기의 역사 (Folie et Déraison: Histoire de la Folie à l'âge Classique)***라는 저서를 통해 정신의학이 어떻게 개인의 삶을 비정상이라 규정해왔는지 비판하였다. 또한 ***감시와 처벌; 감옥의 역사(Surveiller et punir : Naissance de la prison)***이라는 책에서는 공권력이 민중을 파놉티콘(panopticon)에서 드러나지 않게 감시한다고 주장하였다. George Orwell의 ***1984*** 역시 정체를 알 수 없는 권력이 인민을 통제하는 상황을 섬뜩하게 묘사하였다.

이들이 거부하는 것은 가족의 압력, 사회의 압력 뿐 아니라, **정상과 비정상**을 구분하는 보이지 않는 권력에 대해서이기도 하다. 약을 먹는 것은 이런 권력에 굴복하여 자신이 비정상임을 시인하는 것이다. Usher[@usher2001]는 조현병 환자에 대한 질적 연구를 통해, 그들이 주위로부터 얼마나 약을 먹으라는 압력을 받고 있으며, 이에 저항할 수 없다는 무력감에서 어쩔 수 없이 약을 먹고 있음을 발견하고, 이러한 상황을 **강요된 순응(imposed compliance)**라고 불렀다. 일부 환자는 재발때문에 입원하는 것이 아니라, 약물을 복용하지 않는데 대한 사회적 제재로서 입원하게 된다고 믿기도 한다. 이러한 믿음은 엄연히 사실과 다르지만, 그럼에도 불구하고 쉽사리 부인하기 어려운 부분이 있다.

### 낙인과 편견의 각인

환자들은 **조현병**이라는 진단명 자체에는 그렇게 충격을 받지 않아도, **"약을 먹어야 한다"**는데 대해선 큰 충격을 받는다. 처음 진단을 접한 환자들은 "약을 먹지 않아도 이겨낼 수 있지요"라고 물어본다. 마치 약을 먹는다는 것이 감추고 있던 치부를 드러내어 버리는 것처럼 느낀다. 환자들은 자신이 복용하는 약물에 의해 분류되고 낙인 찍히는 것처럼 느낀다. 수면제나 항불안제를 먹는 환자는 스스로를 **"예민한 사람"**으로 분류하고, 항우울제를 먹는 사람은 **"슬픔에서 헤어나지 못하는 사람"**으로 분류한다. 이에 비해 항정신병 약물을 먹는다는 것은 **"스스로가 어딘가 정상이 아닌 사람"**임을 의미한다.

마치 남용 약물을 한번이라도 사용하면 영원히 **약쟁이**로 치부되듯이, 항정신병 약물을 먹는다는 것은, 정상적인 대인관계를 맺을 수도, 사회에서 책임있는 자리를 맡을 수도 없다는 낙인이 되어버린다. 이러한 믿음은 환자의 내적 심리에서 과장된 면이 있지만, 우리나라 현실에서 전혀 동떨어져 있는 것도 아니다. 주요 정신질환에 대한 사회적 편견과 낙인은 뿌리깊은 것으로, 정신질환자가 취득할 수 없는 자격이나 직업은 28가지에 이른다.[^08-04-5]

[^08-04-5]: 병무청 훈령 1816호. \[별표 1\] [안과ㆍ정신건강의학과 질환자 취득 제한 자격ㆍ면허](https://www.law.go.kr/LSW/admRulLsInfoP.do?admRulSeq=2100000204860#AJAX)에 그 목록이 나와있다.

환자들에게 약을 먹지 않는다는 것은 **"병에서 회복되었다"**거나, **"자기 힘으로 병을 이겨내고 있다"**는 것을 의미한다. 의사 입장에서는 약을 제대로 복용하며 자기 관리를 충분히 할 수 있는 상태를 회복이라 판단하지만, 환자나 사회의 입장은 **약을 먹지 않아도 되는 상태**를 요구한다. 이러한 사회 전체의 왜곡된 의식을 바로잡아나가지 않으면 환자가 약에 대해 갖는 부정적 인식은 해결되지 않을 것이다.

### 성역할에 의한 차이

동일한 약물에 대해서 남녀가 느끼는 바는 차이가 있다. 남성은 약물에 의해 자신의 육체적 힘과 성적 역량, 전문인으로서의 기술이 손상을 입었다고 인식한다. **"약을 먹으니 남자 구실하겠어요"**라는 조소에 가까운 표현은 이런 수치심을 잘 보여준다. 또한 평생 누군가에게 의지하며 살아야 한다는데 대해 자존심에 큰 상처를 입는다.

그에 비해 여성은 가족이나 사회에 의지하여 사는데 큰 거부감을 보이지 않지만, 대신 성적 매력과 생식력을 상실한다는데 충격을 받는다. 조현병 진단을 받은 젊은 여성 환자가 간혹 **"이제 어떤 남자가 저를 데려가려 하겠어요"**라고 말할 때가 있다. 물론 항정신병 약물을 먹으면 결혼을 못하고, 아이도 낳지 못한다고 생각하는 것 자체가 잘못된 믿음이지만, 한겹한겹 쌓여나간 집단의 무의식은 쉽게 바뀌지 않는다.[@breslau2011] 이는 현대 사회처럼 결혼과 출산이 당연시 되지 않는 사회에서도, 여전히 마찬가지이다.[@thara2003]

### 상징과 메타포

약물의 모양과 색깔뿐만 아니라 약물의 이름도 개인의 자부심이나 수치심에 영향을 미칠 수 있다. 어떤 문화는 환약을 선호하고, 어떤 사람들은 액체 또는 좌약을 선호한다. 주사는 보통 **"가장 강력한"** 것으로 간주되며, 경구약 중에서는 강렬한 색을 띤 약이 더 강하고 독하다고 여겨진다. 약물은 **"서양에서 넘어왔고"**, **"공장에서 만들지만"**, 한약은 **"생약성분이라 해가 없고"**, **"자연치료에 더 가깝다"**. 반대로 국내에서 만든 복제약보다는 굳이 수입된 오리지널 약을 선호하는 환자들이 많다.

교육의 영향 때문에, 환자들은 약을 먹으면 뇌의 **"화학적 불균형을 교정한다"**라고 믿는다. 그 외에도 **"막힌 혈관을 뚫어준다"**, **"부족한 호르몬이 다시 나오게 해준다"**, **"끊어진 회로를 다시 연결한다"**, **"나쁜 영을 몰아내어 준다"**, **"잡생각을 없애준다"**는 등 다양한 개념을 갖는다. 이렇게 환자가 약물 작용을 묘사하는데 사용하는 수사학(메타포)은 왜 무언가가 작동하고 다른 것은 효과가 없는지에 대한 개인의 고유한 설명을 담고 있다.[@rhodes1984] 환자들이 약물에 부여하고 있는 메타포를 알아야, 반쯤의 성공과 뼈아핀 실패를 반복하게 되는 약물 치료의 긴 여정을, 환자와 발맞추어 동행할 수 있다.[@rosenman2016]

## 약물 비순응

### 비순응의 실태

약물 비순응의 실태를 정확히 집계하기는 어렵다. 환자들이 처한 환경에 따라 크게 달라지기 때문이다. 2002년 집계된 체계적 문헌고찰에서 항정신병 약물에 대한 비순응도는 약 40% 정도였다.[@lacro2002] 미국 재향군인회 병원처럼 치료비가 지원되는 곳에서조차, 비순응하는 환자의 비율은 비슷한 정도였다.[@valenstein2006] 그나마 순응도는 항상 일정한 것이 아니라 시간에 따라 계속 변화하기 때문에, 4년동안 일관되게 순응도를 유지하는 환자의 비율은 40%가 채 되지 않았다. 즉 60% 이상의 환자는 처방을 일관되게 지키지 못한다는 뜻이 된다.

비순응은 약물 치료가 실패하는 가장 중요한 요인으로서, 그 영향은 해당 환자의 병이 잘 낫지 않는다는 것에 그치지 않는다. 약물 치료에 순응했음에도 불구하고 효과를 보지 못했던 환자와 비순응하는 환자는 차이가 있다. 비순응을 보이는 환자들은 정신 병원 입원율, 응급 정신과 서비스 사용, 체포, 폭력사용, 알코올 및 약물 관련 문제가 현저히 높았으며, 삶의 질 또한 형편없이 낮았다.[@aschersvanum2006] 유럽에서 진행된 3 년간의 전향적 연구에 따르면, 알코올 문제, 주거의 불안정성, 공격성은 비순응을 예측하는 인자였지만, 역으로 비순응은 재발, 입원 및 자살 시도와 유의하게 연관되어 있다.[@novick2010]

상대적으로 짧은 기간의 비순응도 문제가 된다. 미국의 한 연구에 따르면 심지어 10일 간의 비순응도 입원 위험을 유의하게 높이며, 비순응 기간이 길어지면 길수록 위험이 높아진다.[@law2008] 첫번째 정신병적 삽화를 겪은 환자는 집중적인 유지 치료의 대상이 된다. 재발을 막느냐 못 막느냐는 평생의 삶의 경로를 뒤바꿀 수 있는 결정적인 갈림길이다. 그렇지만 여전히 많은 초발 환자들이 중도에 탈락한다.[@offord2013; @hickling2018] 예상한 바대로, 5 년간의 추적 연구에서 첫 정신병 삽화가 끝난 후 약물을 중단한 환자군은 그렇지 않은 군에 비해 재발율이 5나 높았다.[@robinson1999]

### 비순응의 예측 요인

부적절한 통찰과 부족한 병식은 조현병 증상의 일부로 간주되며, 비순응의 가장 중요한 원인이다.[@mcevoy2004] 병식은 고정된 특성이 아니라 시시각각 변화하며, 치료가 되면서 호전되기도 한다. 그러나 이미 약을 먹지 않고 있는 중이라면, 중간에 병식을 얻게 되었다 해도 약을 먹지 않는다. 인지 장애 역시 비순응과 관련이 있다. <s>질병인식불능증</s>[^08-04-6]을 모델로 한 병식 이론에서는, 뇌의 기질적 문제가, 스스로에게 문제가 있음을 인정하기 어렵게 만든다고 주장한다.[@lehrer2014] 증상의 특성도 순응도에 영향을 준다. 약물을 통해 자신을 독살시키려 한다고 믿거나, 치료를 받지 말라고 하는 환청을 듣는 환자는 약을 먹지 않을 것이다. 음성/우울 증상은 치료를 받으려는 동기를 감소시킨다.

[^08-04-6]: 질병인식불능증 (anosognosia): 자신의 몸에 생긴 질병이나 이상 상태를 알아치리는 능력이 소실되어, 이를 부인하는 증상. 비우성 대뇌 반구에 병변이 생겨 좌측 반신불수가 된 환자가 이를 인식하지 못하는 사례에 대해 1914년 Joseph Babinski가 처음 사용한 용어이다. 조현병 환자의 병식부재가, 전전두엽 기반의 인지장애로 인한 일종의 질병인식불능증이라는 가설을 "insight-anosognosia model"이라고 한다.[@shad2006]

꼭 병식이 온전한 환자만 순응하는 것은 아니다. 무엇때문에 약을 먹는지 잘 모르는 환자도, 의사에 대한 신뢰와 주변의 압박때문에 약물 치료에 응한다. 거꾸로 병식이 있는데도 비순응에 빠질 수 있다. 자신만의 건강-질병 모델에 따라 약물 치료를 거부할 수도 있고, 일부러 그러는 것은 아니지만, 제때 복용하는 것을 잊어버린다든지, 병원에 오기 어려운 사정이 있다든지, 약값을 감당하기 어려워 치료를 이어가지 못할 수 있다. 의도적이든 의도적이 아니든, 한번 약을 안 먹기 시작하면 다시 먹기가 여간 어려운 일이 아니다. 많은 환자들이 치료를 거부하여 병원에 오지 않지만, 또 다른 환자들은 어쩌다 약을 안 먹게 된 후, 의사를 볼 낯이 없어서 병원에 오지 않는다. 이런 부담감을 초기부터 덜어주고, 설령 약을 먹지 않았더라도 의사를 만나러 와야 한다고 강조하는 것이 중요하다.

부작용 역시 비순응의 중요한 이유이다. 부작용의 객관적인 면에만 치중하다보면 주관적인 불편감을 놓칠 수 있다. 환자들은 부작용의 객관적 정도보다는 주관적 불편감때문에 투약을 거부한다. 오랜 투약으로 항상 입을 오물거리던 환자가, 새삼스레 탈모가 생긴다며 약을 거부할 수 있다. 또한 환자가 약물의 효과는 물론 의사를 신뢰하지 않는다면, 사소한 부작용만으로도 투약을 거부한다. 이런 환자는 지금은 어쩔 수 없이 의사의 지시에 따르지만, 의사가 틀렸음을 밝히기 위해 호시탐탐 기회를 노리고 있다. 그러던 중 몸에서 이상 반응이 나타나면, 자신이 옳고 의사가 틀렸다는 것을 입증하는 증거로 이용한다.

그 밖에도 많은 요인들이 병식이 온전함에도 불구하고 비순응에 빠지게 만든다. 치료비가 부담스러우면 일찍 약물을 중단한다. 병원까지의 거리가 멀 때, 직장 때문에 매달 일정한 시간에 외래를 방문하기 어려울 때, 투약 빈도가 잦고 복잡할 때, 병원에서 아는 사람을 마주칠 기회가 많을 때 병원에 오지 않는다. 이렇게보면 지극히 사사로워 보이는 요인들 때문에도 유지 치료가 실패한다.

역으로 치료에 순응하게 되는 요인은, 가족간의 관계가 단단할 때, 지지해주는 사회적 관계의 폭이 넓을 때, 질병을 잘 극복해낸 롤 모델이 있을 때, 질병에 대한 정보에 자주 접해보았거나, 정보를 찾는데 익숙할 때 등이다. 이런 환경에 있는 환자들은 의학적 설명을 신뢰하고, 소위 말하는 "모범 환자"가 되어 주체적으로 병을 극복하고자 하며, 그 경험을 타인에게 전달하기 원한다.

### 비순응의 평가

예약된 시간에 나타나지 않는 환자는 자연히 비순응 환자이다. 그러나 외래에 꼬박꼬박 오는 환자라고 순응하고 있다고 확신하기 어렵다. 재발한 환자의 방을 뒤져보면 쌓아놓은 약 뭉치가 발견되는 일이 허다하다. 물론 순응도를 평가하는 가장 손쉬운 방법은 환자에게 직접 물어보는 것이다. 환자를 책망하지 않는 태도만 잘 유지한다면, 환자들은 얼마나 약을 빼먹었는지 솔직히 말해준다. 그러나 이 역시 의사-환자 관계가 확고한 환자들에게나 해당되는 방법이다.

임상 연구에서는 순응도를 평가하는 객관적 방법이 필요하다. 과거에는 남은 약을 일일이 세는 방법을 썼으나, 환자가 남은 약을 가져오지 않으면 소용이 없다. 좀더 발전된 전자 모니터링 시스템에서는, <s>MEMS</s>[^08-04-7]라는 장치를 이용하여 약병 뚜껑이 열릴 때마다 서버에 기록을 전송한다.

[^08-04-7]: Medication Event Monitoring System (MEMS)

약물의 혈중 농도를 측정하여 순응도를 평가할 수도 있다. 그러나 이는 손쉬운 일이 아닐 뿐더러, 정확한 지표라고 말하기도 어렵다. 개인마다 약동학적 특성이 다르기 때문에, 약을 제대로 복용해도 혈중 농도가 크게 차이날 수 있다. 또한 혈중 농도는 채혈 직전 며칠 동안의 약물 복용 정보만을 제공한다. 비순응을 숨기고자 하는 환자라면, 외래에 오기 며칠 전부터만 제대로 복용하면 된다. 따라서 혈중 농도를 재는 것은 그저, 약물 복용을 강조하기 위한 보여주기식 으름장인 경우가 많다.

가장 최근에 개발된 방법은 <s>복용 가능한 이벤트 마커</s>[^08-04-8]이다. 이 시스템은 약 1mm^2^크기의 디지털 센서가 내장된 디지털 알약(digital pill)을 사용한다. 섭취된 센서는 위액에 의해서 활성화되고, 패치 형태로 피부에 부착된 외부 기기에 무선으로 정보를 전달하며, 이 때 복용 날짜와 시간이 기록된다. 알약이 분해되면 센서는 대변으로 배설된다.[^08-04-9] [@demiguelberiain2020]

[^08-04-8]: Ingestible event marker (IEM)

[^08-04-9]: Abilify McCite® 시스템은 오츠카 제약과 Proteus Digital Health 라는 IT 기업이 합작해서 개발하였고, 2017년에 미국 FDA의 승인을 받았다. 이는 센서가 부착된 알약인 Abilify McCite ®과 피부 부착형 센서인 MyCite® Patch, 그리고 스마트폰 앱인 MyCite® app으로 구성되어 있다.

디지털 알약과 같은 기술지향적 방법은 순응도 문제 뿐 아니라 약물의 효과를 개인에 맞추어 최적화하는 획기적인 기술을 제공한다. 그러나 어두운 부분이 없는 것은 아니다. 순응도 문제는 어디까지나 환자의 회복을 위한 것이라며 논의되고 있으나, 여전히 외부에서 정한 올바럼의 기준에 강압적으로 맞추게 하려는 억압적인 면이 도사리고 있다. 디지털 필은, 개인의 은밀한 사생활이나 생리 정보마저 누군가에게 열람되고 평가받는 시대가 도래하고 있음을 알려준다. 아무리 부인해보아도 해도 결국 순응도 문제가 감시의 패러다임에서 벗어날 수 없다는데 대해 막막한 느낌이 든다.

### 비순응의 대책

원론적인 이야기이지만, 치료방침 결정 과정에 환자를 적극 참여시키는 것은 순응도를 높이는데 효과적이다. 의사는 환자의 가치관과 우선 순위가 존중받고 있다는 느낌을 주어야 한다. 가능하면 몇 가지 대안을 주고 그중 선택할 수 있는 기회를 제공한다.

부작용 관리에 힘쓰며, 언제든지 부작용에 대해 보고할 수 있고, 그 내용은 치료 방침을 바꾸는데 큰 영향을 미친다는 것을 믿을 수 있도록 해야 한다. 약물을 사용하면서 겪는 경험은 긍정적인 것이든 부정적인 것이든, 가족, 간호사, 사회사업가 등 다양한 채널을 통해 표현하도록 권한다. 치료팀이 잘 구성된 곳에서는 이렇게 표현된 내용이 결국 의사에게 전달된다. 부작용 체크리스트를 사용하는 것도 도움이 된다. 이런 도구들은 환자가 치료의 수동적 소비자가 아니라, 적극적 의사결정자임을 실감하게 해준다.

전통적으로 질병교육을 통해 질병에 대한 지식과 이해를 향상시키면, 자연적으로 순응도가 높아지리라 기대되었다. 그러나 지식과 이해가 갖춰지더라도 그것만으로는 행동이 변화되는 계기가 되지 못했다.[@lincoln2007] 질병교육 모델은 직접 행동을 강화하거나 인지를 수정하는 프로그램과 통합되어야 한다. 행동 개입은 행동 모방, 강화 전략 등을 사용하여, 매일 약을 복용하는 것과 관련된 규칙적이고 건강한 행동 습관을 길러주고자 한다.[@heinssen2002] 예를 들어 비록 오래된 방법이긴 하지만, MUSE[^08-04-10] 프로그램은 약병을 개봉할 때마다 다음 복용 시간을 상기할 수 있도록 안내를 해준다. 이 방법은 심한 정신 장애가 있는 환자에서도 순응도를 유의하게 향상시킬 수 있었다.[@cramer1999]

[^08-04-10]: Medication Usage Skills for Effectiveness (MUSE)

이외에도 다양한 인지행동치료가 시도되었다. 이는 약물중독 치료에서 기본 설계를 가져오고, 건강에 도움이 되는 행동을 증가시키고, 그렇지 못한 행동을 줄이는 행동의학적 기법을 참고하여 만들어졌다. 질병교육[^08-04-11], 동기강화면담[^08-04-12], 순응치료[^08-04-13]들은 환자에게 보다 폭넓은 시야를 갖게 하여 선택의 폭을 넓히면 환자는 결국은 자신에게 이로운 선택을 하리라 기대하였다.

[^08-04-11]: 질병교육(psychoeducation): 질병의 성질과 효과적인 치료법에 대한 지식을 환자에게 전달하여, 환자 스스로 질병에 잘 대처해나갈 수 있도록 돕는 교육을 의미한다.

[^08-04-12]: 동기강화면담 (motivational interviewing): 미국의 심리학자인 William Miller와 Stephen Rollnick에 의해 개발된 모델로, 내담자의 양가감정을 탐색하고 해결함으로써, 내담자 내면에 잠재해 있는 변화 동기를 끄집어 내어 강화시킴으로써, 바람직한 행동을 하도록 유도하는, 내담자-중심, 목표지향적인 상담기법.

[^08-04-13]: 순응치료(compliance or adherence therapy): 동기강화면담 기법을 주요 정신질환 환자의 약물 순응에 초점을 두어 수정, 보완한 치료 기법. 의사-환자 관계의 근본적 갈등을 피해가면서, 목표로 하는 약물순응 행동만을 늘려나가는 간략하고 실용적인 면담으로 이루어진다.

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

그러나 되돌이켜보면 질병교육이든 인지행동치료든 기대만큼 성과를 거두지는 못하였다.[@hegedüs2014; @gray2016] 이는 제품에 대한 모든 정보가 주어지면, 소비자가 합리적인 소비를 할 것이라 믿는 순진한 기대와 같은 차원이다. 환자가 합리적인 결정을 할 것이라는 믿음보다는, 외적 압박이나 은근한 강요가 더 효과적일 지도 모른다. 환자가 제대로 약을 먹는지 의심스러을 때, 보호자에게 약봉지마다 일일이 해당 날짜를 적어두라고 권할 때가 있다. 이런다고 순응도가 높아지진 않겠지만, 비순응의 정도를 비교적 정확하게 파악할 수 있다. 약 먹는 시간을 알려주는 알람 장치나, 정해진 시간에 문자 메시지를 보내는 방법도 조금씩 도입되고 있다. <s>스마트 디스펜서</s>[^08-04-14]는 환자에게 약 먹는 시간을 알려줄 뿐 아니라, 복약 상황을 중앙의 서버에 보내주기도 한다. 첨단이라고 하기엔 이미 낡은 기술이지만 Med-eMonitor™ System, MEMS V TrackCap® devices와 같은 스마트 디스펜서는 지정된 시간에 열리지 않은 경우 환자 및 의료진에게 문자메시지가 보내진다. 시간이 지나도 반응이 없으면, 의료진은 환자에게 전화를 걸어 복약에 대한 상담을 진행한다. 앞서 언급했던 디지털 필보다는 환자들의 거부감이 적고, 민감한 개인정보가 유출될 위험이 적다. 그러나 기술이 보급된 지가 벌써 20년 가까이 지났음에도 불구하고 널리 사용되지는 않는다.

[^08-04-14]: **스마트 디스펜서 (smart dispenser)**: 우리나라는 약을 약봉지(packet)에 일회분씩 담아주지만, 외국은 보통 한품목당 하나의 통(bottle)에 담아 준다. 따라서 여러가지 약을 먹는 환자들은 이를 디스펜서에 나눠담아 일회분씩 먹는다. 디스펜서에 다양한 디지털 기술을 장착하여 정확한 복용을 도와주는 장치를 스마트 디스펜서라고 한다. 언뜻보면 우리나라의 약봉지가 합리적이고 편리할 것 같지만, 약봉지에 담을 수 있는 약도 있고 아닌 것(햇빛이나 상온에 노출되면 안 되는 약 등)도 있기 때문에 혼란이 가중된다. 또한 스마트 디스펜서와 같은 기술을 약봉지에 적용하기는 곤란하다.

만성 정신질환자에게 복지 서비스를 제공하는 것에 대한 급부로, 규칙적인 외래 치료와 약물 복용을 조건으로 거는 지역도 있다. 미국, 캐나다, 뉴질랜드, 호주, 이스라엘, 스웨덴, 영국을 포함한 많은 나라들은 지역사회에 거주하는 만성정신질환자를 위해 <s>외래치료명령제</s>[^08-04-15]를 도입하고 있다. 법적 및 임상 요건은 다양하지만, 환자는 규칙적인 약물 복용을 포함해 지역사회 내에서 치료를 받아야 한다는 의무를 지고, 정신보건 전문요원은 이러한 조건이 깨졌을 때 환자를 병원에 재입원시킬 수 있는 권한을 가진다. 하지만 외래치료명령제의 인권 침해 여부 및 그 효용성에 대해서는 논란이 많고, 우리나라에서도 갑론을박 중이다.[@jang2017; @oreilly2019]

[^08-04-15]: 외래치료명령제 (community treatment order, CTO): 정신질환을 앓고 있는 사람이 특정한 외래치료 프로그램에 참여하도록 법에 의해 명령을내리는 사회적 강제 제도. 우리나라에서도 임세원법이라고 하여 도입하고자 하였으나, 인권침해 논란때문에 무산되고 대신 외래치료지원제를 채택하였다.

심지어 약물을 규칙적으로 복용하면 환자에게 돈을 주는 방법도 제안되었다. 금전적 보상은 행동 변화의 가장 강력한 동기이기 때문이다. 경제적으로도 지역사회에서 환자가 재발했을 때 소요되는 비용과 비교하면 오히려 더 유리한 면이 있다. 지급하는 방식은 현금을 비롯하여, 상품권, 바우처 등이 있다. 무작위 임상연구에 의하면 인센티브를 제공한 환자군의 장기지속형 주사제 순응도가 85%였는데 비해, 대조군은 71%에 지나지 않았다.[@priebe2016] 하지만 확실한 효과에도 불구하고, 윤리적 논란과 형평성 문제때문에 실제로 사용되기에는 어려움이 있어 보인다.

조현병 환자의 순응도와 재발 방지 문제는 환자 개인이나 해당 가족만의 문제가 아니라, 지역사회가 함께 고민해야 할 문제이다. 심각한 정신질환을 제대로 관리하지 못했을 때, 지역사회가 겪는 고통이 심각할 수 있고, 낭비되는 사회적 비용도 매우 크기 때문이다. 위에 기술한 약물 순응도 개선 전략은 이러한 비용을 줄일 수 있는 잠재력을 가지고 있다. 의사의 역할은 처방까지라는 소극적 개념보다는, 순응도 문제를 적극 다루려는 자세가 필요하다.

## References {.unnumbered}
