---
title: "신세대 비정형 약물"
author: 정성훈
bibliography: References/08-03.bib
---

## 아리피프라졸과 브렉스피프라졸

### 개발 역사와 약물의 특성

1990년대 말에 연이어 리스페리돈, 올란자핀, 퀘티아핀이 혜성처럼 임상 현장에 등장하면서, 의사들은 비정형 항정신병 약물이라는 낯선 개념을 소화하기 바빴다. 이전까지 클로르프로마진과 할로페리돌이라는 양대 선택지에 머물러있던 의사들은 어쨌든 새로운 치료제 도입을 반겼으나, 급격히 높아진 가격에 어리둥절하면서 과연 약물이 그 가치를 하는 지에 대해 반신반의하였다.

새로운 개념을 앞다투어 받아들였던 의사들도 힐로페리돌 → 리스페리돈, 퍼페나진 → 올란자핀, 클로르프로마진 → 퀘티아핀으로 대체된 것 뿐 아니냐는 의구심을 갖기 시작하였다. 고강도/저강도의 구분도 유사했고, 그에 따른 약물의 특성도 정형 약물 시절과 크게 달라진 점이 없었다. 게다가 비정형성이라는 선전문구는 요란했지만, 여전히 음성/인지 증상에는 효과가 불확실하였고, 고용량을 쓰면 추체외로 증상이 심해지는 것도 마찬가지였다. 설상가상으로 리스페리돈은 프로락틴 혈증을 일으켰으며, 올란자핀은 대상증후군을 퀘티아핀은 QTc 구간 연장을 불러오는 등 새로운 골치덩이가 생기기조차 하였다.

비정형 약물이라고 해도 음성/인지 증상에 효과가 없고 추체외로 증상에서 자유롭지 못했던 것은, 이들이 여전히 D~2~에 대한 <s>완전 길항제</s>[^08-03-1]이기 때문이다. 아무리 5-HT~2A~ 에 대한 효과를 통해 D~2~ 차단 작용을 완화시킨다고 해도 약물 용량이 올라가면 D~2~를 거의 완전히 차단하는 것은 피할 수 없다. 부분적으로 A9와 A10(8-1-5-2절)에 대한 지역 선택성을 통해 혹은 D~1~/D~2~에 대한 상대적 효과를 통해 미세조정을 가한다고 하지만, D~2~의 완전 길항제로서는 전전두엽의 도파민 활성을 회복시킬 수 없다. 하지만 만약 동일한 약물이 D~2~ 수용체에 결합하되, 도파민 활성이 떨어진 부위에서는 내인적 활성을 높여주고, 활성이 지나친 곳에서는 억제해줄 수 있다면 이상적인 약물이 될 것이다. 이런 바람을 통해 등장한 개념이 **도파민 시스템 안정제(dopamine system stabilizer, DSS)**이다.

[^08-03-1]: 완전 길항제(full agonist): 약물이 수용체에 결합했을 때, 수용체가 원래 갖고 있던 내인적 활성(intrinsic activity)을 전혀 나타내지 않는 것을 완전 길항제라고 하며, 부분적으로 나타내는 것을 부분 효현제(partial agonist), 오히려 수용체의 원래 작용과 반대되는 효과를 나타내는 것을 역 효현제(inverse agonist)라고 한다.

애초부터 아리피프라졸(aripiprazole)이 도파민 시스템 안정제로서 개발된 것은 아니었다. 일본의 오츠카 제약 연구실에서는 도파민 자가수용체[^08-03-2]를 차단하면 도파민 분비가 늘어나면서 음성/인지 증상에 효과적일 것이라는 가설에 입각하여 약물을 개발하고 있었다.[@kikuchi2021] 연구진이 발견한 것은 자가수용체 차단만으로는 양성 증상에 효과가 없고, 시냅스 전 수용체와 동시에 시냅스 후 D~2~ 수용체도 차단할 수 있어야 한다는 것이었다. 이런 조건을 만족하는 화합물로서 1995년에 아리피프라졸이 합성되었다. 연구진은 새로 찾아진 약물의 성질을 연구하던 중 뜻하지 않게 아리피프라졸이 D~2~의 **부분 효현제**라는 것을 알게 되었고, 도파민 시스템을 안정화할 수 있는 가능성을 확신할 수 있었다. 게다가 아리피프라졸은 5-HT~2A~를 강력히 차단하기 때문에, 세로토닌-도파민 가설에도 충실히 부합하는 약물이었다. 한마디로 고전 이론과 혁신적 이론을 동시에 구현하는 이상적인 약물인 셈이다.

[^08-03-2]: **도파민 자가수용체(dopamine autoreceptor)**: 동일한 D~2~ 수용체이지만 도파민을 분비하는 시냅스 전 뉴런의 세포체나 수상돌기에 위치하면서 음성 피드백을 통해 도파민 분비를 조절하는 수용체. 이를 차단하면 일종의 브레이크가 풀리면서 도파민 분비가 늘어나게 된다.

아리피프라졸은 dihydroquinolinone 유도체로서 D~2~와 5-HT~1A~에 부분 효현 작용을 하며, 5-HT~2A~를 강력히 차단한다. 이외에도 D~3,4~, 5-HT~2C,7~ 그리고 α~1~과 H~1~ 수용체에 결합한다. 세로토닌 운반체도 차단하기 때문에 SSRI와 유사한 성질을 갖는다. 아리피프라졸이 5-HT 수용체에 미치는 영향 역시 도파민 못지 않게 약리 효과에 큰 비중을 차지한다. 5-HT~2A~는 글루타메이트 분비 뉴런과 GABA 분비 뉴런을 포함하는 장거리 피드백 루프에 위치하여 도파민 분비를 조절한다.[@alex2007] 세로토닌-도파민 길항제들은 5-HT~2A~를 차단함으로써 이 피드백 루프를 잠시 멈추게 한다.[^08-03-3] 피드백 루프의 봉쇄는 도파민 뿐 아니라, 세로토닌, 노르에피네프린 등 단가아민 분비를 자극하여 항우울 효과를 가져온다. 5-HT~1A~에 대한 효과도 흥미로운데, 일단 약물 투여 초기에는 5-HT~1A~ 차단 작용때문에 불안을 유발하기도 하지만, 곧이어 수용체의 탈감작을 일으켜 오히려 5-HT~1A~를 통한 신호를 활성화한다.[@han2009] 이러한 복잡한 약리 작용은 항불안 효과와 함께, 항우울제의 효과를 보조하는 역할을 한다.[@pae2011]

[^08-03-3]: 과거에는 비정형 항정신병 약물이 5-HT~2A~ 길항제인 것으로 여겨졌으나, 최근에는 역 효현제로 작용한다는 것이 중론이다.

아리피프라졸은 2002년 미국 FDA의 승인을 받아 Abilify®라는 상품명으로 출시되었다. 기존 비정형 약물과의 차별성 때문에 아리피프라졸과 이후 도입된 약물들을 통털어 제 3세대 약물이라고 따로 분류하기도 한다.[@mailman2010]

### 사용 요령과 부작용

아리피프라졸의 약품 설명서에 따르면 초회 용량은 10mg/day, 목표 용량은 15mg/day이다. 일반적으로 조현병 환자에서는 10\~30mg 범위에서 사용하게 되며, 보편적인 사례에서는 15mg/day 이상으로 증량하여도 크게 효과 차이가 나지 않는다고 한다. 허가된 최대 용량은 30mg/day이며, 이상의 용량에서의 안전성을 확보되지 않았다.

아리피프라졸은 기존 약물과는 전혀 다른 작용기전을 갖고 있기 때문에, 약물이 도입된 초기에 의사들은 이미 안정화된 환자에게 항정신병 약물을 교체하는 목적으로 많이 사용하였다.[@fagiolini2015] 하지만 적지 않은 임상 시험에서 급성 조현병 혹은 양극성 환자에서도 만족스러운 효과를 보인다는 것이 확인되었다.[@janicak2009] 위약군보다 우수할 뿐 아니라, 급성 환자에 대한 표준 치료인 할로페리돌이나 리스페리돈에 비해 결코 부족하지 않은 효과를 보였다.[@kane2002; @potkin2003] 다만 양성 증상이 심한 환자나 현재 흥분 상태에 있는 조증 환자에게는 30mg/day 정도의 고용량이 필요할 수 있다.[@disciascio2015; @qian2021]

하지만 약물이 쓰이기 시작한 지 20년 가까이 되었음에도 불구하고, 의사들이 아리피프라졸에 대해 갖는 이미지는 아래 나열한 바와 같다.[@disciascio2015] 이 때문에 조현병 환자의 급성기에는, 리스페리돈, 올란자핀으로 급성 증상을 가라앉힌 후, 슬슬 부작용이 표면화될 시점에서 아리피프라졸로 바꾸는 경우가 많으며, 기존 약물에 병용 투여하는 경우도 생각보다 흔하다.

-   아리피프라졸은 양성 증상 보다는 음성 증상에 더 효과적이다.
-   흥분 상태에 있는 급성 조현병 혹은 조증 환자에게 1차 약물로 선뜻 선택하기 어렵다.
-   환자 증상의 심한 정도에 따라 어느 정도의 용량을 써야할 지 애매하다.
-   치료저항성 조현병 환자에게는 별 효과가 없다.
-   기존 약물에 불충분한 반응을 보일 때 보조 치료제로서 유용하다.
-   기존 약물에 대한 부작용, 특히 체중 문제나 대사 증후군, 고프로락틴혈증을 호소하는 안정화된 조현병, 양극성 장애 환자에게 최선의 선택이다.
-   부작용에 특히 민감한 초기 정신병, 초발 환자에게 유용하다.

이러한 의사들의 임상 경험을 통한 인상에 대해, 전문가들은 단순히 편견에 지나지 않는다며 급성기 환자에서의 우수한 효과, 그리고 단독 치료로도 충분한 효과를 강조하고 있다.[@keck2007; @brown2013] 그러나 이러한 강조가 오히려 아리피프라졸의 약점을 가리고 있는 것 아닌지 의심이 든다. 실제로 리스페리돈과의 비교 임상 시험에서, 전체적 호전 정도는 시험약과 차이가 없었지만, 양성 증상 호전에서는 리스페리돈보다 유의하게 효과가 미진한 것으로 나타났다.[@kim2021]

아리피프라졸의 초회량에 대해서도 논란이 계속되고 있다. 약품 설명서에는 10mg/day로 되어있고, 대규모 임상 시험도 이에 맞추어 진행되었지만, 의사들은 높은 초회 용량을 사용했을 때 생기는 안절부절함에 대해 신경을 많이 쓴다.[@lea2007] 이 현상에 대해 어떤 연구자는 좌불안석이라고 했고, 또 다른 연구자는 도파민 활성에 의해 깨어나는 현상이라고 하는 등 서로 상반되는 해석이 제시되었다.[@vergouwen2005; @basu2006] 아리피프라졸의 허가 임상에서는 좌불안석 현상이 크게 부각되지 않았지만, 이후의 실제 경험상 환자들이 투여 초기에 안절부절해지는 비율은 무려 15\~25%에 이르러, 아리피프라졸의 가장 중요한 부작용으로 자리매김하였다.[@poyurovsky2010] 이러한 높은 좌불안석 위험은 아리피프라졸 뿐만 아니라 3세대 항정신병 약물의 공통적인 특성이기도 하다.[@thomas2015]

이런 문제때문에, 조심스러운 의사들은 초회량을 낮추거나 증량 속도를 좀더 늦추기도 한다.[@sullivan2007; @mago2008] 또한 기존 약물에서 아리프프라졸로 교체할 때는, 후자의 약물이 충분한 용량으로 올라갈 때까지 기존 약물을 함께 병용하는 것을 권장한다.[@casey2003] 최근 문헌들은 15mg/day를 기준으로 고용량 전략과 저용량 전략을 나누고 있다. 급성기나 상당한 양성 증상이 있는 환자, 그리고 조증 삽화에 있는 양극성 장애 환자에게는 처음부터 고용량을 쓰거나 신속하게 증량하며, 만성 조현병 환자나 기존 약물에서 교체하는 환자는 5mg/day 정도에서 시작하여 서서히 증량한다.[@mago2008] 낮은 용량에서도 D~2~ 차단정도는 꽤 높다. 1\~2mg/day만 써도 선조체 D~2~ 수용체의 75%가량이 차단되며, 10mg/day에서 85%, 30mg/day 에서는 90% 이상이 차단된다.[@yokoi2002] 비정형 항정신병 약물의 치료적 창이 D~2~를 65\~80% 차단하는 것이라고 여겨지고 있지만, 아리피프라졸은 이 기준이 좀 다르다. 아리피프라졸 자체가 도파민 활성을 일부 지니고 있기 때문인지, 적어도 D~2~를 90% 이상 차단해야 조현병 치료 효과를 나타낸다. 또한 이 정도로 높게 D~2~가 차단되어도 추체외로 증상은 드문 편이다.[@natesan2006]

### 대사와 부작용

아리프피라졸과 그 대사물질인 dehydroaripiprazole은 반감기가 거의 3\~4일이기 때문에 하루 한번 복용으로 충분하다. 아리피프라졸은 간에서 CYP3A4 및 CYP2D6을 통해 주로 탈수소화, 하이드록실화 및 N-탈알킬화가 진행된다. 정상 상태에서 혈장 아리피프라졸의 약 40%는 주요 대사 산물인 dehydro aripiprazole이다. 신장과 간을 통해 배설되며 간 또는 신장 장애, 연령, 성별, 인종 또는 흡연 상태를 이유로 용량을 조절할 필요는 없다. 하지만 CYP3A4 및 CYP2D6 억제제나 CYP3A4 유도제를 함께 사용할 때는 용량 조정이 필요하다. 다행하게도 양극성 장애 환자에서 리튬과 발프로에이트와 함께 사용해도 약동학에 유의한 영향을 미치지 않기 때문에 안심하고 쓸 수 있다.

안절부절함은 특히 기존 항정신병 약물을 오래 사용하던 환자에서 두드러진다. 기존 약물을 끊고 아리피프라졸로 교체하였을 때, 안절부절함을 보이기 시작하면 이 현상이 좌불안석인지 정신병 증상의 악화인지 구분하기 어렵다. 심지어 일부 환자들은 자해나 자살 시도까지 행하기 때문에, 특히 의사들의 경각심을 불러 일으켰다.[@barnas2005; @raja2007; @takeuchi2013] 이러한 현상은 D~2~ 길항제를 오래 사용하여 D~2~ 수용체가 보상적으로 늘어나있던 환자에게, 부분효현제가 들어가면서 갑자기 도파민 활성이 과다해지기 때문에 발생하는 것으로 설명되었다.[@takase2015][^08-03-4] 오랫동안 연구자들은 이러한 현상이 실제로 근거가 있는 것인지, 의사들의 단순한 편견때문인지를 밝히기 위해 애써왔다. [@montastruc2019; @takeuchi2018] 대부분의 연구는 기존 약물을 아리피프라졸로 바꿀 때나, 다른 약물로 바꿀 때나 증상이 악화되는 비율에는 차이가 없다고 결론짓고 있지만, 의사들의 인상은 잘 바뀌지 않고 있다.

[^08-03-4]: 일종의 도파민 초과민성 정신병(dopamine supersensitivity psychosis)이라고 볼 수 있다.

안절부절함외에 흔한 부작용은 두통과 불면이다. 물론 추체외로 부작용이 아예 없다고는 할 수 없지만, 좌불안석을 제외하고는 정형 약물보다는 확실히 적다. 하지만 클로자핀, 올란자핀, 퀘티아핀보다는 추체외로 증상이 많다고 보여진다.[@kim2021] 이에 비해 기타 비정형 약물의 공통된 약점인 체중 증가, 인슐린 저항성 증가, 지질 대사 이상, 프로락틴 혈증에서 자유로우며, QTc 간격 연장을 비롯한 심장에 대한 영향도 거의 없다. 게다가 앞서 언급한 두통, 불면 등의 증상도 투여 초기에 집중되며, 장기간 투여 시에는 그리 현저하지 않기 때문에 부작용면에서는 확실히 우수한 약이라고 하겠다.

문헌에서 강조되지는 않고 있지만, 아리피프라졸은 D~3~에도 부분효현 작용이 있다. 이는 양성 증상 치료에는 크게 도움이되지 않지만, 음성 증상을 개선하고 기분을 고양시키는데 기여할 수 있다.하지만 병적 도박 등 예기치 않은 부작용을 가져올 수도 있다.[@boileau2013; @grallbronnec2016][^08-03-5]

[^08-03-5]: 2016년 미국 FDA는 아리피프라졸(장기주사제 포함) 투여 중 도박, 폭식, 쇼핑, 성행위에 대한 과도하고도 참을 수 없는 강박적 욕구가 생길 수 있다는 경고문을 넣을 것을 지시하였다. 이러한 부작용은 pramipexole, ropinirole과 같은 다른 D3 효현제에서도 발생할 수 있다.

### 기타 제형

아리피프라졸은 그 동안 구강 붕해정, 용액, 급성 주사제 등 다양한 제형이 개발되었으나, 2015년 갑자기 생산이 중단되었다. 이는 제약사의 전략적인 선택으로 보이며, 효과나 안정성 문제는 아니었다. 대신 2013년에 장기지속형 주사제인 Abilify Maintena®가 FDA의 승인을 얻고 출시되었다. 한달에 한번 맞는 장기지속형 주사제 300\~400mg는, 경구약 10\~20mg/day에 상응하는 효과를 보인다. Abilify Maintena®는 시장에서 금새 인기를 끌었고, Invega Sustenna®와 함께 조현병의 유지 치료를 대표하는 약물이 되었다.

아리피프라졸의 성분특허는 이미 풀려있기 때문에, 미국에서는 또 다른 장기지속형 주사제인 Aristada®가 출시되었다. 이는 aripiprazole lauroxil 성분으로 두달에 한번만 맞으면 되는 등, Abilify Maintena®보다 좀더 유리한 약동학적 특성을 보인다.

### 브렉스피프라졸

브렉스피프라졸(brexpiprazole)은 아리피프라졸의 쌍동이 형제라고 볼 수 있다. 아리피프라졸의 개발 과정 중 1999년에 합성되었다. 당시 개발을 주도한 연구진의 목적은 아리피프라졸의 좌불안석, 안절부절못함, 불면 증상을 어떻게든 해결하는 것이었다. 이를 위해 D~2~에 대한 내인적 효과가 적고, 세로토닌-도파민 길항제로서의 성질이 더 뚜렷한 약물을 찾고자 하였다. 브렉스피프라졸은 2015년에 와서야 우울증의 보조 치료 및 조현병 치료에 FDA 승인을 받았으며, Rexulti®라는 상품명으로 출시되었다.[@kikuchi2021]

브렉스피프라졸은 동일한 D~2~ 부분 효현제라고 해도 아리프피라졸에 비하여 <s>내인적 효과</s>[^08-03-6]가 좀더 작고, 대신 5-HT~2A~와 5-HT~1A~ 대한 차단 효과가 더 크다.[@maeda2014] 따라서 D~2~ 효현 효과때문에 나타나는 좌불안석, 불면이 적고, D~2~ 차단때문에 발생하는 추체외로 증상 발생도 적다. 제약사 역시 세로토닌을 좀더 강조하여 아리피프라졸과 차별화하기 위해 <s>세로토닌-도파민 활성 조절제</s>[^08-03-7]라고 선전하고 있다.[@das2016] 이런 성질 때문인지, 브렉스피프라졸은 우울증 치료제로서 좀더 시장에서의 위치가 굳어지고 있는 느낌이다.[@kishi2019] D~3~에 대한 효과는 아리피프라졸과 거의 동일하고, α~1~, H~1~ 대한 결합력은 아리피프라졸보다 약간 크지만 거의 유사하다고 보면 된다.[@maeda2014]

[^08-03-6]: 부분효현제가 수용체를 100% 차단했을 때 나타내는 도파민 활성

[^08-03-7]: Serotonin-dopamine activity modulator (SDAM)

브렉스피프라졸은 두 개의 허가 임상 연구[^08-03-8]를 통해, 급성 조현병 환자에게 6주간 치료 했을 때 위약과 분명한 차이를 보였다.[@kane2015; @correll2015] 52주 동안의 유지 치료에서도 위약군과 비교하여 탁월한 재발방지 효과를 보였다.[@fleischhacker2017; @forbes2018] 또한 네 개의 임상 시험[^08-03-9]을 통해 주요우울증 환자에서 항우울제와 함께 투여되었을 때 뚜렷한 효과를 보였다.[@thase2015; @thase_adjunctive_2015; @hobart2018; @hobart_efficacy_2018]

[^08-03-8]: BEACON, VECTOR trial

[^08-03-9]: Pyxis, Polaris, Sirius, Delphinus trial

이중 맹검 임상 시험은 모두 위약을 비교 대상으로 삼았기 때문에, 다른 항정신병 약물 특히 아리피프라졸에 비해 어떤 장점이 있는지는 알기 어렵다. 안정성 자료를 검토한 바에 따르면, 좌불안석이나 안절부절함이 없지는 않다 하더라도 위약군과 크게 차이나지 않았으며, 약간의 체중 증가 및 프로락틴 상승 효과가 있는 정도였다.[@watanabe2020] 브렉스피파리졸을 아리피프라졸과 직접 비교한 연구는 Citrome 등[@citrome2016]에 의한 연구가 유일하다. 6주 치료 후 PANSS 호전 정도가 -22.9와 -19.4로 미미하게 브렉스피프로졸이 우세한 경향을 보였다. 하지만 역시 차이가 난 것은 좌불안석 발생빈도였는데, 각각 9.4%와 21.2%로 브렉스피프로졸이 절대적으로 빈도가 적었다. 그러나 이 연구는 표본수도 적고 개방 연구라 근거로서의 가치는 낮다. Kishi 등[@kishi2020]은 위약 대조군 연구의 자료들을 네트워크 메타 분석 기법을 통해 종합함으로써, 두 약간의 효과와 안정성을 비교하였다. 그들이 분석한 바에 따르면 효과 뿐 아니라 좌불안석, 수면, 어지러움, 추체외로 증상 등 모든 안정성 자료에 있어서도 두 약물간에 유의한 차이는 없었다.

## 일로페리돈

2009년부터 2010년 사이에 미국 FDA는 일로페리돈, 아세나핀, 루라시돈의 순서로 허가를 내주었다. 항정신병 약물의 개발에 많은 노력과 시간이 드는 것을 고려하면, 짧은 기간 동안에 세 개의 신약이 시장에 도입되었다는 것은 주목할만한 사건이다. 그래서인지 이 세 약물은 함께 논의되는 일이 많으며, 일종의 경쟁 관계에 놓여있다.[@tarazi2012] 이들은 고전적인 세로토닌-도파민 길항제 계열이지만, 리스페리돈/올란자핀/퀘티아핀에 비해 체중 증가 및 대사 부작용이 훨씬 적다. 하지만 효과 면에서 기존 약에 비해 크게 차이가 나지 않는데다가, 한국에서 출시될 예정이 없기 때문에 발매된지 10년이 지났어도 별 주목을 받지 못하고 있다.

일로페리돈(Iloperidone)은 리스페리돈과 마찬가지로 benzisoxazole 계열 약물이며, 2009년에 조현병 치료용으로 FDA로부터 승인을 받았다.[^08-03-10] 일로페리돈의 수용체 프로파일은 매우 복잡한데, 기본적으로 세로토닌-도파민 길항제인 것은 맞지만, D~2~와 5-HT~2A~ 이외에도 D~3,4~ 및 5-HT~6,7~에 친화도가 높다. 5-HT~2A~/D~2~ 결합비는 1.1 정도로 클로자핀, 리스페리돈에 비해 매우 떨어진다.[@kongsamut1996] 일로페리돈을 기타 비정형 약물과 차별화하는 가장 큰 특징은 클로자핀에 버금가는 α~1~ 수용체 결합력이다. 그에 비해 5-HT~1A~와 H~1~에 대한 결합력은 매우 낮은 편이다.

[^08-03-10]: 일로페리돈의 판권은 여러 제약사의 손을 거쳤다. 원래 Hoechst Marion Roussel에 의해 개발된 약으로, Titan Pharmaceutical을 거쳐 Novartis가 권리를 인수하였다. Novartis는 다시 2004년에 Vanda Pharmaceutical에 판권을 넘겼으나, 2009년에 장기지속형 주사제 개발에 대한 권리를 다시 사들였다. 지금은 두 회사가 공동으로 제조, 판매를 하고 있다.

일로페리돈의 효과는 몇 가지 장단기 연구를 통해 확인되었다.[@cutler2008; @potkin2008; @weiden2016] 위약에 대해서는 확실한 차이가 드러나지만, 다른 비정형 약물보다 우수하다는 근거는 발견되지 않았다. 일로페리돈의 효과가 타 약물과 차별화되는 것 같지는 않으며, 효과보다는 부작용 특성을 살피는게 중요할 것이다.

일로페리돈의 가장 흔한 부작용은 α~1~ 차단때문에 생기는 빈맥, 어지러움과 기립성 저혈압이다. 임상 시험에 참여한 환자 중 6\~17%가 어지러움을 호소하였다. 그 밖의 부작용 특성은 리스페리돈과 지프라시돈의 중간 정도라고 보면 될 것이다. 추체외로 증상이나 체중 증가 등의 부작용이 정형 약물보다 적은 것은 사실이지만, 지프라시돈보다는 흔한 편이다. 무척 졸리다는 것도 고려해야할 사항인데, 환자의 4\~13%가 졸리움을 부작용으로 호소한다. 그 밖에 구강 건조, 코막힘 등의 부작용이 있다. 프로락틴을 약간 올릴 수 있지만, 아미설프라이드, 리스페리돈보다 훨씬 덜 하다.[@peuskens2014] 프로락틴에 영향이 적어 성적 부작용이 없을 것이라 기대되지만, 다른 비정형 약물과 마찬가지로 역행성 사정 및 지속발기증이 보고되었다.[@freeman2013; @latorre2013] 한편 용량 의존적으로 QTc 간격을 증가시킬 수 있으며, 증가 폭은 지프라시돈과 유사하다.[@potkin2013] [^08-03-11]

[^08-03-11]: 제약사가 시행한 **A thorough QTc (TQT) study**에서 일로페리돈을 하루에 8mg bid, 12mg bid로 2주간 투여했을 때, QTc 간격이 각각 8.5mg, 9.0mg 증가하였다. 동일한 기간 동안 지프라시돈을 80mg bid로 투여한 군은 9.6ms 증가하였다.

특이하게도 일로페리돈의 치료 효과는 몇 가지 유전자 변이의 영향을 받는다. <s>CNTF</s>[^08-03-12] 는 사이토카인의 하나로 노르아드레날린과 세로토닌 기능을 억압하는데, CNTF에 변이가 있어 단백질 활성이 떨어지는 환자는 임상 효과도 크게 떨어졌다.[@lavedan2008] 그 밖에도 일로페리돈 효과에 영향을 끼치는 변이가 여러개 발견되었다.[^08-03-13] <br><br><br><br><br><br><br><br>

[^08-03-12]: Ciliary neurotrophic factor (CNTF)

[^08-03-13]: 예를 들어 Neuronal PAS domain protein 3 (NPAS3), XK Kell blood group complex subunit--related family member 4 (XKR4), tenascin-R (TNR), glutamate receptor ionotropic AMPA 4 (GRIA4), glial cell line--derived neurotrophic factor receptor alpha 2 (GFRA2), NUDT9P1 pseudogene located in the serotonin receptor 7 gene (HTR7) 등

일로페리돈의 유효 용량 범위는 12\~24mg/day로 하루 두번 투여한다. 기립성 저혈압이 심하기 때문에 천천히 조심스레 증량해야 한다. 첫날 1mg 하루 두번으로 시작해서, 하루에 최대 4mg 씩 증량한다. 목표 용량에 도달하는데 최소 1주일은 여유를 두어야 한다.

종합하면 일로페리돈은 효과 면에서는 다른 비정형 약물과 큰 차이가 없지만, 추체외로 증상의 위험이 적고, 프로락틴을 올리지 않으며, 체중 증가 및 대사 증후군의 위험이 적다는 장점이 있다. 클로자핀을 제외한 다른 비정형 약물의 경우, 용량이 일정 수준을 넘어서면 추체외로 증상 빈도가 상당히 높아지는 것에 비해, 일로페리돈은 용량이 높아져도 추체외로 증상 위험이 따라 증가하지 않는다.[@weiden2012] 하지만 하루 두번 투여해야 하고, 어지러움과 기립성 저혈압의 위험이 커서 용량 적정 과정이 복잡하다. 유사한 시기에 도입된 경쟁 약물들에 비해 양극성 장애에 적응증이 없다는 것도 한계이다.

## 아세나핀

아세나핀(asenapine)은 2009년에 조현병 치료 및 양극성 장애의 조증 또는 혼합 기분 에피소드의 급성 치료를 위한 단일 요법, 또는 기분조절제와의 병합 요법으로 미국 FDA의 승인을 받았다. Mianserin이라는 친숙하지 않은 항우울제를 토대로 화학구조를 변형시켜 Organon 사에서 개발에 성공하였으며, Saphris® 혹은 Sycrest®라는 상품명으로 판매되었다.[^08-03-14] <br><br><br><br><br><br><br><br>

[^08-03-14]: Saphris®는 상업적으로는 우여곡절을 겪었다. Organon 사는 Pfizer와 함께 약물을 공동 개발하였는데, Pfizer는 상업성이 없다고 포기하였다. Organon 사는 이후 Merck사(MSD)에 합병되었고, 2009년에 Saphris®를 출시한 것은 Merck 사였다. 그러나 Merck 역시 2013년에 판권을 Forest Laboratories에 넘겼고, Forest Laboratories 사는 2019년에 AbbVie 사에 인수합병 되었다. 현재는 AbbVie 사에서 제조, 판매하고 있다.

아세파핀은 전형적인 세로토닌-도파민 길항제로 D~2~, 5-HT~2A~ 그리고 α~2~ 수용체에 강한 길항작용을 보인다. 그 밖에도 D~3~, 5-HT~2B~, 5-HT~6,7~, H~1~ 수용체에 강한 친화도를 보인다.[@citrome2014] 이 약물의 독특한 점은 위장 흡수가 매우 불량하기 때문에, 설하 정제로 투여되며 구강 점막을 통해 흡수된다는 것이다. 따라서 약물 복용 후 10분 동안은 먹거나 마시지 말아야 한다는 불편함이 있다. 하지만 그 때문에 투약한지 30\~90분 내에 최대 농도에 도달한다는 장점도 있다. 빠른 효과 발현 때문인지 급성 조증 삽화에 승인을 획득한 최초의 항정신병 약물이 되었다.[@tarazi2012] 한편 영국을 비롯한 유럽에서는 급성 조증 삽화에서만 사용이 허가되었다.

시작 용량은 조현병 환자는 5mg 씩 하루 두번이며, 급성 조증 환자는 10mg 씩 하루 두번이다. 용량 적정과정은 필요없으며, 부작용이 발생하면 조금 낮춰보거나 효과가 부족하면 20mg 하루 두번까지 올린다. 설하 투여하는 정제이기 때문에, 다른 약물처럼 반으로 잘라 투여할 수는 없다. 가장 두드러진 부작용은 α~1,2~, H~1~ 수용체 결합에 의한 진정 작용과 어지러움이며, 그 밖의 부작용은 다른 세로토닌-도파민 길항제와 유사하다.[@citrome_asenapine_2009] 체중 증가 및 대사 증후군의 위험은 매우 적으며, 프로락틴 상승 효과는 아리피프라졸에 비해 좀더 심하다.[@citrome_asenapine_2014] 혀 밑에서 녹기 때문인지, 약을 먹다보면 입에서 이상한 맛이 나고(dysgeusia), 혀가 먹먹해지는(oral hypoesthesia) 부작용이 5% 정도에서 일어난다. 기전은 알 수 없지만 좌불안석의 위험이 매우 높으며, 이와 연관되어 하지불안 증후군이 발생한 사례도 자주 보고되고 있다.[@mccall2014; @thomas2015]

투약의 불편함때문인지 좌불안석 때문인지 중도탈락률이 상당히 높다.[@schoemaker2012] 이를 개선하기 위해 아세타핀 경피 패치(transdermal patch)가 개발되었고, 2021년에 FDA 승인을 받아 Secuado®이라는 상품명으로 출시되었다.[^08-03-15] 하지만 매일 교환하여야 하며, 갈아붙일 때마다 피부의 다른 부위를 선택해야 하는 등 여전히 불편한 것은 마찬가지이다.[@citrome2020]

[^08-03-15]: 아세나핀의 물질특허는 2020년에 풀렸고, 이를 기다렸다는 듯이 Noven이라는 제약사가 2021년에 경피 패치를 출시하였다.

## 루라시돈

루라시돈(lurasidone)은 2010년에 미국 FDA로부터 조현병 치료제로 허가를 받았으며, 2013년에는 양극성 장애 환자의 우울 삽화에 승인을 받았다. 특히 항정신병 약물로서 후자에 적응증을 받은 것은 퀘티아핀과 함께 유일하며, 다른 약물과 차이가 나는 점이다.

루라시돈은 benzisothiazole 유도체로서 D~2~와 5-HT~2A~ 그리고 5-HT~7~ 수용체에 강력하게 결합한다. 5-HT~1A~에 부분 효현 효과를 보이고, α~2~에 길항 작용이 있지만, H~1~, M~1~ 수용체에는 별로 결합하지 않는다. 따라서 용량을 높여도 체중 증가, 진정 작용, 항콜린 부작용에서 자유로운 편이다.[@javed2019]

루라시돈의 반감기는 18시간으로, 지프라시돈과 마찬가지로 음식과 함께 복용했을 때 흡수율이 두 배 가까이 증가한다. 따라서 적어도 350 칼로리 이상의 식사와 함께 섭취하는 것이 권장된다. 시작 용량은 40mg/day이며, 조현병에서는 160mg/day, 양극성 우울증에서는 120mg/day 까지 사용한다. 일로페리돈이나 아세나핀과 달리 하루에 한 번만 복용해도 된다. 간기능 또는 신기능이 저하된 환자에게는 40mg/day 이상 쓰면 안 된다.

루라시돈은 부작용이 참 적은 약이다. 효과는 기존 비정형 약물에 비해 크게 내세울 것이 없지만, 신체적 건강을 지킨다는 측면에서 매우 이상적인 약이다. 기존 약물에서 루라시돈을 바꾸는 경우 오히려 체중이 조금 빠질 정도이며, 당 수치, 인슐린 저항성, 지질 수치에도 거의 영향이 없다.[@inamdar2015; @zhang2017] 프로락틴 상승 효과는 아리피프라졸, 카리프라진에 비하면 조금 높지만, 리스페리돈/팔리페리돈에 비하면 훨씬 낮다. 따라서 성적 부작용도 거의 없는 편이다.[@clayton2018] QTc 간격 연장 역시 전혀 신경쓰지 않아도 될 정도이다.[@loebel2013]

항정신병 약물을 복용하는 환자들이 가장 힘들어하는 부작용 중 하나가 졸리움이다. 클로자핀을 비롯하여, 올란자핀, 퀘티아핀은 무척이나 졸리운 약에 속한다. 새로 출시된 약물 중에서도 지프라시돈, 일로페리돈, 아세나핀 모두 졸리운 편에 속한다. 그나마 덜 졸린다고 하는 리스페리돈과 아리피프라졸은 환자에 따라 졸리기도 하고, 불면을 초래하기도 하며, 가장 중립적인 약물은 브렉스피프라졸이다. 이에 반해, 루라시돈과 아래 소개할 카리프라지는 오히려 깨우는(activating) 약물에 속하며, 기존 약물에서 후자의 약물들로 교체할 때는 불면이 실제로 문제가 되기도 한다.[@citrome2017]

루라시돈은 일로페리돈, 아세나핀, 그리고 아리피프라졸, 클로자핀과 함께 5-HT~7~에 결합하며, 그 중에서도 가장 결합력이 강하다. 5-HT~7~과 인지 기능의 관계는 vortioxetine을 통해 관심을 모으기 시작하였다.[@westrich2015] 5-HT~7~가 차단되면 전전두엽, 해마 그리고 측좌핵에서 도파민 분비가 늘어난다.[@huang2012] MK-801에 의한 인지 기능 저하 모델에서도 5-HT~7~ 길항제를 미리 투여하면, 예방 효과가 있다.[@horisawa2013] 하지만 5-HT~7~ 효현제는 글루타메이트에 의한 세포독성으로부터 신경세포를 보호하며, 기억력을 포함한 인지 기능을 증진시키는 효과가 있다.[@meneses2015; @yuksel2019] 따라서 인지 기능에 미치는 5-HT~7~의 역할을 모순 덩어리이며, 아직까지 완전히 이해되지 못하고 있다.[@meneses2014] 어쨌든 루라시돈은 낮은 용량에서도 조현병 환자의 인지 기능을 개선하는 효과가 있으며, 이는 양성 증상의 호전과는 상관이 없었다.[@meltzer2020] 5-HT~7~ 길항제는 이외에도 일중 리듬을 정상화시키며, 기분을 증진시키는 효과가 있기 때문에, 항우울제를 비롯한 신약 개발의 중요한 타겟이 되고 있다.[@nikiforuk2015]

종합하면 루라시돈은 같은 시기에 도입된 세 개의 비정형 약물 중에서도 대사성 부작용, 기립성 저혈압, QTc에 대한 효과, 졸리움 등에서 압도적으로 유리한 약물이다. 비록 추체외로 증상의 위험이 조금 높지만, 지난 세대의 비정형 약물에 비해서는 여전히 낮은 편이다. 게다가 5-HT~7~에 대한 작용을 통해 인지 기능을 향상시키고, 항우울 효과를 나타낸다. 아직은 임상 경험이 많지 않지만, 가장 기대되는 약물 중 하나이다.

## 카리프라진

카리프라진(cariprazine)은 헝가리의 Gedeon Richter Ltd.에서 2004년에 합성에 성공하였으며, 미국에서는 Actavis Generics 사에서 제조, 판매하고 있다.[^08-03-16] 카리프라진은 2015년에 조현병, 그리고 양극성 장애 조증 혹은 혼합형 삽화 치료에 허가를 받아, Vraylar®라는 상품명으로 판매되고 있다. <br><br><br><br>

[^08-03-16]: Actavis Generic 사는 아일랜드에서 출발한 다국적 기업이며, 전 세계에서 3번째로 규모가 큰 제네릭 의약품(복제약) 생산 업체이다. 복제약 생산 업체가 오리지널 약품인 카리프라진을 생산하는 것은 의외이다.

카리프라진은 D~2~와 D~3~의 부분 효현제로, 아리피프라졸, 브렉스피프라졸의 뒤를 잇는 항정신병 약물이다.[^08-03-17] 특히 D~3~에 더욱 강력한 효현 효과를 보이는데, 이는 항정신병 약물 작용 기전 연구의 새로운 방향을 제시했다고 보아야 한다. 카리프라진은 그 밖에도 5-HT~1A~에 부분 효현, 5-HT~2A~에는 길항 효과를 보인다.

[^08-03-17]: 아리피프라졸, 브렉스피프라졸, 카리프라진 그리고 루마테퍼론을 가리켜 3세대 항정신병 약물이라 부른다.

아무래도 앞서간 두 약물과 자꾸 비교를 당하게 되는데, 아리피프라졸과 브렉스피프라졸이 D~3~에는 거의 결합하지 않는 반면, 카리프라진은 D~2~와 비교해 6-8배 이상 D~3~에 대한 결합력이 크다. 아리피프라졸과 비교하면 D~3~에 대한 결합력이 3\~10배 이상 크다.[@citrome2016] D~2~에 대한 내인적 효과는 아리피프라졸에 비해 다소 적은 편인데, 이는 브렉스피프라졸과 마찬가지로 좌불안석, 안절부절못함의 부작용이 적은 원인이다. D~3~에 대해서 비록 내인적 효과를 갖긴 하지만, 도파민 자체보다는 한참 낮은데다가 D~3~에 대한 결합력이 도파민보다도 높기 때문에, 결과적으로 D~3~를 차단하는 효과를 보인다.[@stahl2016] 이는 D~3~를 어중간하게 자극하여 병적 도박을 유발하는 아리피프라졸과 차별되는 점이며, 오히려 아미설프라이에 접근한다고 볼 수 있다.(8-1-5-4절, 8-1-5-6절) 5-HT~1A~에 친화도가 높은 것은 새로운 세대의 항정신병 약물의 공통점이다. 다만 5-HT~2A~에 대한 결합력이 기타 세로토닌-도파민 길항제에 비해 턱없이 낮은데, 어떻게 비정형성을 나타내는지는 의문이다.

카리프라진은 빠르게 흡수되어 경구 투여 후 3\~4시간 사이에 최고 농도에 도달한다. 음식 섭취는 흡수율에 크게 영향을 미치지 않는다. 유효 용량은 1.5\~6 mg/day이며 하루 한번 복용한다. 카리프라진을 사용할 때 꼭 기억해야 하는 것은 긴 반감기이다. 카리프라진 자체의 반감기가 2\~4일인데다가, 주요 대사물 중 하나인 <s>DDCAR</s>[^08-03-18] 은 체내에 2\~3주간 머무른다.[@kiss2019] DDCAR 역시 약물 활성을 보이기 때문에, 카리프라진 자체의 반감기가 그만큼 길다고 생각해야 한다. 반감기가 길기 때문에, 항정상태에 도달할 때까지 10\~12주 이상 걸릴 수 있으며, 용량을 바꿔도 바로 혈중 농도에 반영되지 않는다. 용량을 변경한 날로부터 2주는 지나야 그 효과가 반영될 정도이다. 또한 약물을 갑자기 끊어도, 몇 개월 이상 약효가 지속된다. 이러한 성질은 투여 초기 농도 적정을 힘들게 하고, 부작용 관리에도 부담을 주지만, 또 다른 한편으로는 환자의 복용 순응도가 떨어져도 쉽게 재발하지 않는다는 장점이 있다.[@stahl2016]

[^08-03-18]: Didesmethyl-cariprazine (DDCAR)

카리프라진은 위약군과 비교한 몇몇 임상 시험을 통해 조현병의 급성 증상 치료 및 재발방지 효과가 있다는 것이 확인되었다.[@kane_efficacy_2015; @durgam2015; @durgam2016] 뿐만 아니라 급성 조증 삽화 및 혼합형 삽화에서도 유의한 치료 효과를 보였다.[@durgam_efficacy_2015; @sachs2015; @calabrese2015] 하지만 양극성 우울증 환자에서는 1.5mg/day만이 위약군보다 유의하게 우수한 효과를 보였을 뿐, 0.75mg/day 그리고 3mg/day는 위약군과 뚜렷한 차이를 보이지 못했다.[@durgam_depression_2016] 주요 우울증에서의 병용 투에에서도 인상적인 결과는 보이지 못했다.[@durgam_adjunctive_2016] 현재로서는 양극성 우울증 또는 주요 우울증에 대한 적응증은 획득하지 못하였다.

부작용으로는 제법 좌불안석, 불면 등 활성화 부작용이 나타나는 편이며, 추체외로 증상도 드물지 않다. 위약군에 비해 좌불안석을 경험할 오즈비는 3.92로 가장 신경이 쓰이는 부작용이다. 그에 비해 체중 및 대사 지표에 대한 변화는 일으키지 않았고, 프로락틴 수치 및 QTc 간격에도 영향이 없다.[@lao2016]

## 루마테퍼론

루마테퍼론은 긴 항정신병 약물 개발 역사에 있어서 가장 마지막에 위치하고 있다.[^08-03-19] Intra-Cellular Therapies라는 제약사에서 개발된 이 약물은 2019년에 조현병 치료에 대해 미국 FDA의 승인을 받았으며, Caplyta®라는 상품명으로 2020년부터 판매되고 있다. 2021년말에는 양극성 장애 I, II 형에 동반된 우울삽화에 단독 치료 혹은 기분조절제와의 병용 치료도 승인받았다.

[^08-03-19]: 카리프라진 이후 개발된 비정형 항정신병 약물로 pimavanserin이 있다. 그러나 이 약물은 조현병이 아니라, 파킨슨병에 동반된 환각과 망상에 대하여 각각 2016년과 2018년에 미국 FDA 승인을 받았다.

루마테퍼론은 butyrophenone 계열 약물이다. 그렇지만 같은 계열인 할로페리돌과는 달리 5-HT~2A~/D~2~ 비가 60정도로 클로자핀보다도 큰 편이다.[@snyder2015] 한편 α~1~, H~1~, M~1~ 등 다른 수용체에는 거의 결합하지 않기 때문에 사소한 부작용들이 매우 적은 편이다. 루마테퍼론의 독특한 점은 유효 용량에서 D~2~ 차단율이 40% 미만으로 퀘티아핀 정도에 지나지 않는다는 것이다.[@vanover2019] 그런데 이렇게 낮은 차단율로도 항정신병 효과를 나타내는 것은 루마테퍼론이 시냅스 전 도파민 수용체의 효현제이기 때문이다.

일반적인 비정형 약물은 시냅스 전,후 D~2~ 수용체 모두에 길항 효과를 보이기 때문에, 일단 시냅스 전 수용체를 차단하여 도파민 분비를 늘리고, 대신 그만큼 시냅스 후 D~2~를 막아 정신병 증상이 악화되는 것을 막는다. 하지만 루마테퍼론은 시냅스 전 D~2~ 수용체에는 효현작용을 하여 도파민 분비를 줄이기 때문에, 시냅스 후 D~2~를 철저히 차단하지 않아도 충분하다.[@zhang2018] 그 밖에도 루마테퍼론은 <s>mTOR</s>[^08-03-20] 경로의 몇가지 주요 단백질을 인산화시켜, NMDA, AMPA 수용체를 통한 글루타메이트 활성을 촉진하는 성질을 갖는다.[@kumar2018; @snyder2018] 문헌에는 <s>GSK-3</s>[^08-03-21]의 인산화를 촉진시켜 항정신병 효과에 기여한다는 것도 언급되곤 하는데, 사실 GSK-3에 대한 영향은 모든 D~2~ 차단제가 공통적으로 갖는 성질이다. 이렇게 조금씩 발견되는 새로운 기전 때문에 루마테퍼론은 \<s\>선택적/동시적 세로토닌, 도파민, 글루타메이트 조절제\</s\>[^08-03-22] 혹은 \<s\>도파민 수용체 인산화 조절제\</s\>[^08-03-23]라는 수식어가 따라붙어있다. (6-4-1절)

[^08-03-20]: Mammalian target of rapamycin (mTOR)

[^08-03-21]: Glycogen synthase kinase (GSK-3)

[^08-03-22]: Selective and simultaneous modulator of serotonin, dopamine and glutamate

[^08-03-23]: Dopamine receptor phosphoprotein modulator

루마테퍼론은 또한 세로토닌 운반체를 차단하기 때문에, SSRI와 같은 항우울 작용을 보인다. 세로토닌 운반체 차단율은 30% 정도로 SSRI 보다는 적지만, 5-HT~2A~ 길항효과와 합쳐지면 강한 항우울 효과를 나타낸다고 한다. 이는 루마테퍼론이 양극성 우울증 환자에게 적응증을 얻게 된 주된 원인이다.[@davis2015]

항정신병 효과는 D~2~ 수용체 차단에 의해서만 일어나며, 5-HT 수용체에 대한 효과는 부작 용을 줄이기 위한 수단일 뿐이라고 믿는 의사라면 분명 의심스러워 할 것이다. 그러나 <s>pimavanserin의 예</s>[^08-03-24]를 보았을 때, 이상적인 조합이 갖춰진다면 D~2~ 차단이 항정신병 효과에 필수적이지 않은 것인지도 모른다.[@meltzer2012] 루마테퍼론의 낮은 D~2~ 차단율은 좌불안석을 비롯한 추체외로 증상이 거의 나타나지 않는 특징을 설명해준다.

[^08-03-24]: 파킨슨병 환자의 망상/환각을 치료하는 pimavanserin은 D~2~를 차단하지 않으면서도 5-HT~2A~에 대한 역효현 작용 하나만으로 항정신병 효과를 나타낸다.

루마테퍼론의 반감기는 13\~21시간으로 하루 한번 복용하며, 용량 적정 필요없이 첫날부터 유효 용량인 42mg를 투여한다. 일반적으로는 42mg/day를 유지하나, 효과가 부족하면 84mg/day로 증량할 수 있다. CYP3A4에 의해 주로 대사되며, 그 밖에도 UGT[^08-03-25] 효소에 의해 glucuronidation되거나, ketone reductase에 의해 알코올로 분해된다.[^08-03-26] 따라서 흔한 CYP3A4 억제제인 플루복사민에 의해 혈중 농도가 증가하며, 카바마제핀에 의해 감소한다. 또한 UGT 억제제인 발프로레이트와 병용해도 농도가 증가한다.[@greenwood2021]

[^08-03-25]: Uridine diphosphate glycosyltransferase (UGT)

[^08-03-26]: 이는 음주용의 에틸알코올과는 다르다.

루마테퍼론은 낮은 용량에서도 5-HT~2A~를 거의 완전히 차단하기 때문에 졸리움과 피로감을 유발할 수 있다. 이는 흥분하거나 공격적인 환자에게는 유리하지만, 양극성 우울증 환자에게는 부정적인 효과이다. 오히려 용량을 높여야 세로토닌 운반체 차단 효과가 궤도에 오르면서 항우울 효과가 시작된다. 졸리움 외에는, 추체외로 증상을 비롯하여 대사 부작용, 프로락틴, QTc 에 대한 효과가 거의 없기 때문에, 부작용때문에 기존 항정신병 약물을 복용하기 어려웠던 환자에게 좋은 선택이 될 수 있다. 그러나 한달 약값이 무려 \$1,500이 넘기 때문에, 그만한 가치가 있는 지는 의문이다.[^08-03-27]

[^08-03-27]: 예를 들어 경구 Invega®에 비해 약 5배 가량 비싸다.

## References {.unnumbered}
