---
title: "항정신병 약물의 선택"
author: "정성훈"
bibliography: References/08-05.bib
---

## 과연 최적의 약물 선택이 가능한가? {#sec-best-medication}

정형 항정신병 약물 시대에는 비교적 약물 선택의 기준이 명료하였다. 원형격이 클로르프로마진과 할로페리돌을 양쪽 끝에 놓고, 약물들은 저/중간/고역가 약물로 구분되었다. 고역가 약물은 효과는 좀더 우수한 대신 추체외로 증후군과 지연성 운동장애의 위험이 높고, 저역가 약물은 운동부작용은 상대적으로 적지만 기타 부작용이 심하다는 식으로 명료하게 정리되었다. 그에 비해 중간 역가 약물은 이도 저도 아니기에, 일차 약물이 실패한 경우에 두번째 혹은 세번째로 사용되었다. 어떤 약물들은 특별한 목적을 위해 선택되었다. 설피라이드와 록사핀은 음성/인지 증상을 돕기 위해, 피모자이드는 신경성 식욕부진증이나 뚜렛 증후군, 강박증의 치료를 위해, molindone은 체중 감소를 위해 선택되었다. 어떻게 보면 나름대로 약물 선택에 그럴듯한 지침이 있었던 셈이다.

비정형 약물이 도입되면서 상황은 크게 변화되었다. 제약사들은 자사 약품의 독특한 특색보다는, 광범위하게 우수하다는 점을 전면에 내세웠다. 리스페리돈과 올란자핀이 처음 도입되었을 때, 두 회사는 서로 자사 약물이 효과가 우수하다고 선전하는데 열을 올렸다. 소위 <s>맞대결 비교임상시험</s>[^08-05-1]이라는 것이 등장하였는데, 대표적인 예로 20세기가 끝날 무렵 리스페리돈과 올란자핀의 효과와 안정성, 경제적 효과를 비교하는 다국적 연구가 진행되기도 하였다.[^08-05-2] [@kasper2001] 미국 FDA가 허가를 내줄 때에는 일단 위약 대조 연구 자료만을 요구하지만, 허가 이후라도 기존 약물에 대한 우수성 혹은 <s>비열등성 시험</s>[^08-05-3] 자료를 요구할 때가 있다. 따라서 제약 회사들은 다수의 맞대결 비교임상을 진행하여 자사 약의 우수성을 강조해왔다. 10여년 전에 발표된 항정신병 약물 메타 연구에서도 이미 78개의 맞대결 시험 자료가 포함되어 있었으며[@leucht_meta_2009], 이로부터 10년 사이에 그 수는 훨씬 증가되어 있었다.[@huhn2019] 게다가 맞대결 임상 자료가 없다 하더라도, 간접적으로 약물 사이의 서열을 매기는 <s>네트워크 메타 분석</s>[^08-05-4] 기법이 동원되면서, 어떤 약이 얼마나 더 효과적인지에 대해 치열한 암투가 벌어졌다.[@huhn2019]

[^08-05-1]: **맞대결 비교임상시험 (head-to-head clinical trial)**: 기대하는 치료 효과를 가진 두 개의 약물(혹은 치료법)에 대해, 어느 약물이 더 우수한 지 직접 비교하는 무작위 임상시험. 자사 약물의 우수성을 입증하기 위해서 하는 경우(superiority design)와, 비열등성을 입증하기 위해 하는 경우(non-inferiority design)가 있다. 점점 치료효과가 없는 위약을 임상시험에 사용하는 것이 윤리적으로 문제시되면서, 맞대결 임상시험의 일종인 활성 대조군 연구(active comparator design)가 늘어나고 있다.[@streiner2008]

[^08-05-2]: **Risperidone olanzapine drug outcomes studies in schizophrenia (RODOS)**: 얀센 사의 주도로 진행된 다국적 임상 연구로 전 세계 9개국의 61개 센터가 참여하였으며, 총 1,901명의 환자가 등록된 대규모 연구이다.

[^08-05-3]: **비열등성 시험 (non-inferiority test)**: 새로운 약물이 기존에 표준으로 확립된 치료법에 비해, 더 낫거나 혹은 적어도 효과가 더 떨이지지 않는다는 것을 입증하기 위해 행해지는 임상 시험. 적어도 효과가 열등하지만 않다면, 안정성이나 경제성에서 이점이 있다는 이유로 새롭게 임상에 도입될 수 있다.

[^08-05-4]: **네트워크 메타분석 (network meta-analysis)**: 만약 A와 C약물을 비교하고 싶지만 둘을 직접 비교한 임상시험 자료가 없을 경우, A와 B, B와 C를 비교한 연구를 토대로 A와 C의 차이를 도출해내는 것을 간접비교라 한다. (여기서 B는 보통 위약에 해당한다.) 다수의 약물 사이에서, 앞의 방법으로 얻어낸 간접 비교 결과와 직접 비교 결과를 모두 통합하여, 약물 간의 순위를 매기는 것을 네트워크 메타 분석이라고 한다.

그럼에도 불구하고, 이 모든 노력들의 결론은 클로자핀 말고는 어떤 약도 다른 약보다 확실히 우수하다는 증거를 찾지 못헀다는 것이다. 약물 효과의 신뢰구간은 서로 넓게 겹쳐져 있었다. 게다가 적지 않은 연구자들은 임상 시험 자체의 신뢰성과 효용성에 대해 의문을 제기한다. 양질의 임상 시험은 대부분 제약회사의 후원 하에 이루어지고, 연구 설계 단계부터 암암리에 후원사의 입김이 가해진다. 최근에는 모든 임상 시험을 시행 전에 미리 <s>사전등록</s>[^08-05-5]하도록 규정되어 있지만, 그럼에도 불구하고 후원사에 불리한 결과(소위 음성 결과)는 연구 목표를 달성하지 못했다는 구실로 논문화되지 않는 경향이 있다. 이러한 <s>출판편향</s>[^08-05-6]은 메타 분석 결과의 신뢰성을 떨어뜨리는 중요한 원인 중 하나이다. 이런 상황이다보니, 57개의 제약회사 후원 맞대결 비교임상시험 중에서 55개(96.5%)가 후원사 약이 우수하거나, 열등하지 않다는 결과를 낼 정도로 <s>비뚤림</s>[^08-05-7]이 심각하다.[@flacco2015] 제약사의 후원을 받지 않는 자연적 연구(naturalistic study)나 대규모 데이터베이스 연구는 이런 비뚤림에서 자유로운 편이나, 대신 연구 자체의 엄정성이나 신뢰도에 상당한 문제가 있다. 만약 임상 시험 결과와 자연적 연구 결과가 일치한다면 훨씬 믿을 만한 결과이겠지만, 실제 임상 자료 역시 마케팅 캠페인의 영향에서 완전히 자유롭다고 하기는 어렵다.[@katona2021]

[^08-05-5]: 국제보건기구(WHO)는 2005년에 International Clinical Trials Registry Platform (ICTRP)를 발족하여 임상시험을 사전등록하고 그 정보를 공개하는 국제 표준을 제도화하였다. 미국은 2008년 이후 [ClinicalTrials.gov](https://clinicaltrials.gov/)를 운영하여 인간을 대상으로 하는 모든 임상 시험을 사전에 등록하도록 법적으로 제약하고 있다. 우리나라도 2010년에 ICTRP로부터 승인을 받아, 임상시험 자료를 전 세계와 공유하고 있다. 국내에서는 [임상연구정보서비스](https://cris.nih.go.kr/)(Clinical Research Information Service, CRIS)가 연구자들의 사전 등록을 받고 있다. 하지만 아직 법적으로 강제되고 있지는 않다.

[^08-05-6]: **출판 편향 (publication bias)**: 원래는 통계적으로 유의한 차이를 발견한 연구가, 그렇지 못한 연구보다 학술논문으로 출판될 가능성이 높은 편향을 말한다. 이제는 의미가 확장되어, 애초에 목적한 양성 결과만이 발표되고 음성 결과는 발표되지 않는 편향을 뜻하기도 한다. 가설 입증에 실패한 연구가 발표되지 못하면, 메타 분석에서는 성공한 연구만 포함되어 결과가 긍정적인 쪽으로 왜곡된다. 임상연구 사전등록제도는 실패한 연구라도 결과가 공개되어 메타 분석에 포함될 수 있게 하는 제도적 보완장치이다.

[^08-05-7]: 2006년에 다음과 같은 도전적 제목의 논문이 발표되었다. ***Why Olanzapine Beats Risperidone, Risperidone Beats Quetiapine, and Quetiapine Beats Olanzapine: An Exploratory Analysis of Head-to-Head Comparison Studies of Second-Generation Antipsychotics?***[@heres2006]

약물 간의 효과 차이에 대한 결론이 나지 않다보니, 효과의 개념을 좀더 광범위하게 정의하는 경향이 등장하였다. 일반적으로 항정신병 약물 임상시험에서 일차 평가 변수(primary endpoint)는 BPRS나 PANSS 점수를 이용하지만,, 이차 평가 변수(secondary endpoint)에는 심리사회적 적응 정도나 사회적/직업적 기능, 삶의 질에 대한 평가가 포함되기 시작하였다.[^08-05-8] 이를 통해 단순히 정신병적 증상 만 아니라, 궁극적 효과인 환자 삶의 긍정적 변화에 효과가 있다는 것을 부각시키고 있다.

[^08-05-8]: 예를 들어 현대의 임상시험에는 Personal and Social Performance Scale (PSP), Subjective Well-Being Under Neuroleptics Treatment Scale (SWN-20), WHO Quality of Life (WHO-QOL), health-related quality of life (HRQoL) 등이 단골로 포함된다.[@canuso2008; @kim2009; @potkin2016; @awad2014]

서로 상충하는 수많은 연구 자료와 공격적인 마케팅 캠페인 속에서, 의사들은 약물 간의 차이에 대해 냉소적인 입장을 취하게 되었다. 비정형 약물 들간의 우열에 대한 논란을 넘어, 과연 비정형 약물이 정형 약물에 비해 나은 점이 있느냐는 원론적인 비판들도 가시지 않고 있다.[@lieberman2005; @lieberman2011] 그러나 언제인가부터 최적의 약물 선택에 대한 논의가 샛길로 벗어나버렸다는 느낌을 받는다. 의사로서 궁금한 것은 **"눈앞의 한 환자에게 어떤 약물을 써야하는가"**라는 질문이지, **"어떤 약이 전반적으로 더 우수한가"**라는 질문이 아니다. 아무리 비교임상시험에서 다른 약에 뒤지는 것으로 보여진 약이라도, 특정한 환자에게는 매우 효과적일 수 있다. 의사들은 각각의 독특한 임상 상황에서 어떤 원칙을 따라야하는지를 알고 싶을 뿐, 고가의 약들이 값어치를 하는지, 기존 약보다 더 우수하지 못하다면 왜 새 약을 도입해야 하는지 등 비생산적 논의에는 관심이 없다.

**"모든 면에서 우수한 약물이 없다면 약물 선택은 어떤 원칙으로 이루어져야 하는가?"** 이 난제에 대해 현재까지 이루어진 합의는 두 가지로 요약할 수 있다. 첫째, 약물 선택은 부작용 프로파일에 따라 행해져야 하며, 어떤 부작용을 우선시할 지는 환자 자신의 선호가 가장 중요하다. 둘째, 환자의 증상 특성, 생리적 지표, 유전형 등에 대한 광범위한 자료를 분석함으로써, 개개 환자에 대한 약물 반응을 예측할 수 있고, 이를 통해 최적의 약물을 선택할 수 있다. 후자는 맞춤의학, 정밀의학이라는 이름으로 연구의 탄력을 받고 있다.

## 약물 선택의 기준

### 심각한 약물유해반응을 피해가는 선택

정형 약물 시대부터 약물의 선택은 **"가장 효과적일 것 같은"** 약물을 선택하는 것보다는 **"사용해선 안 되는 약물을 배제"**하는 것으로부터 시작할 때가 많았다. 예를 들어 녹내장 환자에게 항콜린 효과가 큰 약물을 쓰면 안 된다든지, 심장 질환 환자에게 QTc를 연장시키는 약을 쓰면 안된다든지 하는 것들이다. 그러나 **부작용**이란 원래 목적한 바가 아닌 작용을 뭉뚱그려 가리키는 것이지, 꼭 **약물유해반응**을 의미하는 것은 아니다.(9-1장 참조) 예를 들어 진정 작용은 애초에 원했던 작용은 아니지만(즉 부작용이지만), 원활한 치료를 위해 유용하게 사용될 때가 있다.

그렇다 하더라도 분명히 심각한 약물유해반응들이 존재하며, 이들은 어떤 상황, 어떤 맥락에서도 달갑지 않다. 따라서 약물을 선택할 때 최우선적으로 고려할 것은 심각한 약물유해반응을 최소화하는 것이다. 여기에 해당하는 약물유해반응으로 다음 네가지를 들 수 있다.[@lugg2022]

1.  지연성 운동장애
2.  대사증후군
3.  고프로락틴혈증
4.  신경이완제 악성증후군

이중 앞선 세가지 유해반응은 당장 눈앞에 벌어진 현상이 문제가 될 뿐 아니라, 장래에까지 영향을 미칠 후유증을 낳는다는 공통점이 있다. 지연성 운동장애는 한번 발생하면 절반 이상의 환자에서 회복될 수 없기 때문에 치명적인 유해반응이다. 대사증후군 역시 체중 증가 뿐 아니라, 심혈관계 질환, 뇌혈관 질환 등 환자의 기대수명을 단축시키는 심각한 후유증으로 이어진다. 고프로락틴혈증 역시 단지 월경이 중단되는 것 뿐 아니라, 골밀도 감소, 암 발생 위험 증가 등의 위험을 동반한다. 이 밖에 신경이완제 악성증후군은 비록 그 빈도가 매우 낮지만, 치명률이 높고 뾰족한 치료법이 마련되어 있지 않기 때문에 반드시 피해야하는 대상에 포함된다.

이렇게 따지면 사용할 수 있는 약물이 거의 없을 것이다. 지연성 운동장애를 고려하면 특히 고역가 정형 약물을 피해야하며, 대사증후군을 고려하면 클로자핀, 올란자핀이 배제된다. 신경이완제 악성증후군과 특별히 연관되는 약물은 없지만, 고프로락틴 혈증을 막으려면 리스페리돈, 아미설프라이드 계열의 약이 배제된다. 그러나 이렇게 따지기 시작하면, 남는 약물이라곤 아리피프라졸을 비롯한 2000년대 이후에 도입된 약물들뿐이다.

특히 초기 정신병 혹은 소아/청소년 환자에 대한 관심이 높아지면서, 이들의 신체적 건강에 해를 끼치면 안된다는 인식이 높아지고 있다. 적극적인 약물 치료로 조현병의 진전을 조기에 막아야한다는 목적과, 약물 치료에 불가피한 장기적 후유증을 막아야 한다는 목적이 정면으로 충돌하고 있다. 정신과 의사들은 항정신병 약물이 **필요악(necessary evil)**이라는 인식에 대체로 동의하고 있다. 따라서 **가장 덜 나쁜 대안(the least worst option)**을 선택하는 것이 최선일지도 모른다.[@morant2018]

### 부작용 및 기타 제약 사항을 고려한 선택

심각한 유해반응이 아닐 지라도 다양한 부작용들은 약물을 선택할 때 반드시 고려해야할 사항이다. 아무리 이상적인 약물을 선택한다고 해도 모든 부작용을 피할 수는 없기 때문에, 부작용들에 대해 우선 순위를 매길 수 밖에 없다. 순위가 높은 부작용을 피하기 위해선 그보다 낮은 순위의 부작용을 감수해야만 한다. 예를들어 운동부작용이 예상되는 환자에게는 항콜린 효과를 무릅쓰고 저역가 정형 약물을 쓰며, 대사부작용을 감수하고 비정형 약물을 쓰게 된다. 반대로 전립선비대증이나 장폐색의 과거력이 있어서 항콜린제를 쓰면 안 되는 환자라면, 운동부작용의 위험을 무릎쓰고 고역가 약물이나 리스페리돈 계통의 약물을 쓸 것이다.

경우에 따라선 부작용을 치료에 이용할 수 있다. 급속 진정을 위해 진정 작용이 강한 약물을 일부러 선택할 수 있다. 음성 증상 위주의 환자라면 약간 불안이나 좌불안석을 야기할 수 있는 아미설프라이드, 아리피프라졸 계통의 약물을 선택할 것이다.

과거에는 부작용의 우선 순위를 매기는 것이 전적으로 의사 손에서 행해졌지만, 이제는 시대가 바뀌어 의사의 독단적인 결정보다는, 환자의 선택을 존중하는 것이 보다 바람직한 의료형태로 자리잡고 있다.[@ngmak2018; @achtyes2018; @fiorillo2020] 동일한 현상이라도 의사와 환자가 서로 다른 가치를 부여할 수 있다. 의사들은 당연히 치료 효과에 가장 높은 가치를 두지만, 환자들에게 치료 효과는 부작용, 복용 편리성에 뒤이은 부차적인 요소였다.[@kaar2019] 부작용 중에서도 환자들은, 체중 증가와 좌불안석을 의사들이 생각하는 것보다 훨씬 더 중요시하며, 살이 찔 바에는 약을 안 먹겠다고 생각하기도 한다.[@wykes2017; @achtyes2018]

희생해야 할 부분은 부작용 뿐만이 아니다. 무엇보다 비싼 비용을 감수해야 하며, 병원과의 관계에 얽매게 된다는 것, 낙인과 편견에 시달려야 한다는 것, 제대로 복용하고 있는지 간섭을 받아야 된다는 것 등 한 두 가지가 아니다. 그런데 이러한 다수의 조건이 서로 상충할 때가 많다. 예를 들어 의사는 부작용을 줄이기 위해 하루 두번으로 나누어 처방하고자 하지만, 환자는 도저히 아침에 약을 챙기기 힘들다고 한다. 환자는 가급적이면 비싸고 좋은 약을 쓰고 싶어하지만, 의료보호라는 제도의 굴레때문에 처방의 제약을 받아야 할 때도 있다. 환자는 졸리는 약을 절대로 먹고 싶어하지 않지만, 가족들은 환자가 밤중에 잠 안자고 돌아다니는 것이 가장 걱정스러운 부분이라며 마찰을 빚기도 한다.

합리적인 의사결정을 위해서는 의사가 평가하는 환자의 증상적, 생리적 특성(personalization by physiology과 환자가 보고하는 선호도(personalization by preference), 그리고 그 외 제약조건들 사이에 균형을 잡아야 한다. 전문가들은 이러한 갈등 상황을 해결하는 하나의 방법론으로 <s>다기준결정분석(MDCA)</s>[^08-05-9]을 제시한다.[@adunlin2015] MCDA는 다양한 이해당사자의 상충되는 가치가 개입되고, 명백하게 옳은 결정이 없는 경우에 최선의 선택을 하기 위해 개발되었다. 한때 항암치료에 인공지능 기반 <s>의사결정지원시스템</s>[^08-05-10]이 사용되었던 것처럼, 정신과 영역에서도 복잡한 알고리즘을 갖춘 의사결정 지원 시스템이 도입될 지도 모른다.[@ozsahin2020]

[^08-05-9]: Multi-Criteria Decision Analysis (MCDA)

[^08-05-10]: 의학적 의사결정지원시스템(Clinical Decision Support System, CDSS): 예를 들어 IBM's Watson for Oncology는 수집된 빅데이터 분석 결과와 환자 개인의 자료를 비교 검토하여 가장 효과가 높을 것으로 예상되는 항암치료전략을 제시해준다. 우리나라에서는 2016년 길병원을 시작으로, 많은 대학병원이 앞다투어 도입하였다. 그러나 실제 임상 실제와 잘 맞지 않고, 정확도가 떨어져 점차 관심이 멀어졌다. 급기야 2022년 IBM 사는 Watson Health 전체를 매각하였다.

### 질병 아형에 따른 선택

아무리 약물들 사이에 효과 차이가 없다고 해도, 특정 약물을 써야만 증상이 호전되는 환자가 있다는 경험을 무시할 수 없다. 마찬가지로 몇 가지 약물에 실패하여 이것저것 약물을 교체하던 도중, 별로 기대하지 않았던 약에 갑자기 좋아지는 사례를 드물지 않게 만나게 된다. 의사는 자연스레 "애초에 이 약부터 시작했었으면..."하는 미련이 남고 후회를 하게 된다. 이는 또한 과거에 잘 들었던 약이 재발 후에도 효과적이라는 임상 격언에도 들어맞는다. 이는 부작용이나 선호도와는 아무 상관없이 환자에게 안성맞춤인 약물이 있다는 뜻일텐데, 안타깝게도 현재로서는 이를 미리 예측할 방법이 없다.

개개인의 약물 반응을 예측할 수 없다면, 환자가 어떤 아형(subgroup)에 속하는 지를 판단하여 부족하나마 약물 선택에 도움을 받을 수 있을 지 모른다. 이론의 여지는 있지만 조현병은 단일한 질환이라기보다는, 서로 밀접한 유사성이 있지만 꽤 차이가 나는 다수의 이질적인 질환들일 가능성이 높다.[@tsuang1990; @kirkpatrick2001; @clementz2016] 이 질환들은 현상학적(증상 특성)으로, 병태생리학적으로, 병인론적으로 다양하게 구분될 수 있다. 만약 합리적으로 이들 아형을 분별해내는 방법이 있다면, 각 아형에 걸맞는 치료법을 찾아내고 이를 환자에게 적용할 수 있을 것이다.[@gillespie2017; @lee2015] 예를 들어 Mars등[@mas2020]은 초발 정신병 환자들을 종적으로 관찰하여 반응과 유해반응 여부에 따라 아형으로 구분한 후, 약물 사용 이전부터 드러난 임상 특성을 비교하였더니 유의한 차이를 발견할 수 있었다. 이를 역으로 적용하면, 약물을 사용하기 전에 환자에게 약물이 도움이 될 지 피해만 줄 지를 예측할 수 있다는 뜻이다.

예로부터 편집형, 파과형, 강직형 등의 고전적인 아형에 따라, 치료 반응 및 예후를 구분해보려는 시도가 있어왔다.[@fenton1991] 그러나 이 접근법은 100여년간의 노력에도 불구하고 큰 성과를 내지 못했고, 전통적 아형 자체가 DSM-5에 이르러서는 폐기될 운명에 처했다.[@mattila2015] 최근에는 생물학적 표지자를 이용하여, 좀더 생물학적 기반에 근거하여 아형을 나누고자 한다.[^08-05-11] 앞으로 더욱 다양한 유전학적 지표, 신경생리 및 신경인지 지표를 사용하여 정밀하게 아형을 구분할 수 있다면, 개인의 아형을 진단하여 맞춤형 치료를 제공하는 것도 불가능하지 않을 것이다.[^08-05-12] 아마도 이러한 염원을 달성하기 위해서는 다음 절에 소개할 맞춤의학/정밀의학의 선구자들에게 맡겨야 할 것 같다.

[^08-05-11]: 한 연구에서는 44개의 생물학적 표지자를 이용하여 조현병을 3가지 biotype을 나누었는데, 유형 1은 낮은 뉴런 반응, 유형 2는 과도한 뉴런 반응 및 감각신경 억제곤란으로 특징지워졌으며, 유형 3은 이 두 지표가 모두 정상인 경우였다.[@clementz2016]

[^08-05-12]: Duke 의과대학을 중심으로 구성된 Mood Disorder Precision Medicine Consortium은 정밀의학 방법론을 이용하여 각종 항우울제에 대한 반응을 예측하고자 한다. 독일에서는 Munich/Augsburg consortium이 구성되어, 조현병, 양극성 장애, 주요 우울증을 대상으로 역시 정밀의학을 통해 질병의 만성화를 방지하고 기대수명을 늘리겠다는 목표를 추구하고 있다.[@basile2002]

### 타겟 증상에 따른 선택

정신과 치료가 어쩔 수 없이 대증적 치료의 비중이 크다는 것을 감안했을때, 지금 현재 환자에게 나타나는 증상에 가장 큰 비중을 두어 약물을 선택할 수 밖에 없을 것이다. Stahl은 우울증의 개개 증상을 도파민, 세로토닌, 노르에피네프린의 상대적 영향에 따라 분류하고, 이를 근거로 두드러진 증상에 맞춰 항우울제를 선택하는 <s>증상기반 약물선택</s>[^08-05-13]을 제안하였다.[@stahl1997] 이는 아마도 반복해서 나타나는 증상 특성이 특정한 아형을 지시하고, 아형의 차이에 따라 약물 반응이 달라질 수 있다는 앞절의 논점을 반복하는 주장일 것이다.[@chekroud2017; @murawiec2021] [^08-05-14] 그러나 설령 아형 구분과는 상관없는 증상일 지라도, 환자에게는 지금 당장 가장 고통스럽고 절실하게 해결을 바라는 문제일 수 있다.

[^08-05-13]: Symptom-based antidepressant selection

[^08-05-14]: 우울증의 예를 들자면, 두드러진 증상에 따라 8개의 생물학적 유형이, 1) rumination, 2) anxious avoidance, 3) negative bias, 4) threat dysregulation, 5) anhedonia, 6) context insensitivity, 7) inattention, 8) cognitive dyscontrol, 설정되었으며, 각각에 대한 치료약 개발이 진행되고 있다.[@williams2016]

비정형 항정신병 약물은 다양한 수용체와 결합하여 폭넓은 효과를 나타내며, 이는 기분 장애, 불안 장애, 강박 장애 등까지 아우른다. 몇몇 수용체 결합 특성이 특정 증상에 대한 효과와 연결되기도 하는데, 예를 들면 5HT~2A~ 길항 **&#8594** 음성 증상, 5HT~1A~ 효현 **&#8594** 불안, 5HT~1D,2C~ 길항 **&#8594** 우울 증상에 효과적이라는 식이다. 최근 개발되는 신약들은 아예 약물 개발 단계에서부터 기분 장애를 중요한 적응증으로 포함시키는데, 예를 들어 아리피프라졸, 브렉스피프라졸은 주요 우울증에, cariprazine, lurasidone은 양극성 우울증에 FDA 허가를 받아내었다. 이러한 적응증을 잘 이용하면, 기분 증상을 동반한 환자, 양극성 장애 조증과 구분이 잘 되지 않는 환자, 조현정동장애 환자에게 효과적인 약물을 어렵지 않게 선택할 수 있다. 비록 적응증을 받지 않았지만, 일부 항정신병 약물은 조현병 환자의 불안, 불면 뿐 아니라, 순수한 불안 장애, 수면 장애 환자에서도 효과를 보이며, 이 역시 약물을 고르는데 단서가 될 수 있다. [@hershenberg2014; @gao2006; @morin2014]

### 맞춤의학/정밀의학의 비젼

맞춤의학/정밀의학은 거의 동등한 개념으로 받아들여진다. 처음에 등장한 용어는 맞춤의학이었지만, 이는 마치 환자 개개인을 위해 안성맞춤으로 재단한 치료법을 찾아내는 실용 기술처럼 들린다. 물론 이러한 목적을 추구하는 것도 맞지만, 학문으로 자리매김하기 위해선 보편적으로 어떤 **접근법**을 취할 것인지를 다뤄야지, 최적의 처방을 찾아내는 요령만 다뤄서는 곤란할 것이다. 그래서인지 최근에는 **맞춤의학(personalized medicine)** 대신 **정밀의학(precision medicine)**이라는 용어를 더 많이 사용한다.[@cesková2021]

모든 치료가 환자의 증상과 체질, 그리고 요구에 맞추어 행해져야 한다는 것은 고대로부터 지금까지 한번도 의학의 원칙에서 누락된 적이 없다. 문제는 환자의 증상과 체질을 어떻게 파악하겠느냐이다. 모든 환자는 **별난 체질(idiosyncrasy)**을 지닌다. 고대 그리이스 의학에서는 이를 ***"iδιoσυγκρασiα (idiosynkrasia)"***라고 표현하였으며, 신체의 독특한 기질이나 성향 즉 <s>체액</s>[^08-05-15]의 혼합 비율을 의미하였다.[@visvikissiest2020] 따라서 동일한 질병이라도 체질에 맞게 치료법이 달라진다는 것은 지극히 당연하였다. 지금도 전통의학에서는 질병의 종류보다도 개인의 체질을 더 우선시하는 경향을 찾아볼 수 있다. 그런데 근대 의학이 자리를 잡으면서 체질보다는 질병의 정체성이 더 강조되기 시작하였고, 1950년대 등장한 근거중심의학을 정점으로 **"동일한 질병에는 동일한 치료법"**이라는 원칙이 새로운 미덕으로 간주되었다. 근현대 의학에서 질병분류학이 그 무엇보다도 중요시된 이유는, 개인의 체질에서 질병의 속성으로 강조점이 옮겨간 탓으로 무리가 아니다.

[^08-05-15]: **체액(humor)**: 육체의 건강은 4가지 체액(피, 점액, 노란 담즙, 검은 담즙)의 조화에 달려있다는 이론으로 히포크라테스로부터 비롯된다고 여겨지고 있다. 원래 고대 그리스 철학자들은 우주의 삼라만상이 몇 가지 기본 요소로 구성되어 있다고 믿었는데, 히포크라테스가 이를 의학에 처음 적용하였다. 이 이론은 19세기 중반 미생물 병인론이 탄생하면서 자연스레 사라졌다.)

그러던 중 체질이 다시 부상하기 시작한 것은 다름 아닌 유전학의 발전때문이었다. 개인의 생물학적 정체성이 게놈을 이루는 30억개의 염기 서열에 모두 담겨있다면, 체질에 대한 정보도 이 안에 온전히 포함되어 있을 것이다. 게다가 개인과 개인 사이의 변이는 전체 염기 서열의 1%도 되지 않으니, 더욱 분석대상이 좁아진다. **약물유전학(pharmacogenetics)**은 이러한 시대적 변화에서 탄생하였으며, 개별 유전자 변이가 약물 반응에 어떤 영향을 미치는지를 조사하기 시작하였다. 이후 인간 게놈 지도가 완성된 후에는, 체질을 파악하는 범위가 개개 변이에서 전체 게놈으로 확장되었다. 학문의 이름도 바뀌어서 새로이 등장한 **약물유전체학(pharmacogenomics)**은 전체 게놈에 분포하는 모든 변이의 조합이 약물 반응과 맺는 관계를 연구한다. 고대 의학의 치료 방침을 갈랐던 개인의 별난 체질이, 이제는 유전적 변이라는 이름하에 슬그머니 되돌아온 셈이다.

19세기 중반 자리잡은 **미생물 병인론(germ theory)**의 유산은, 신체와 질병을 두 개의 서로 대립하는 존재로 인식하게 만든다는 것이다. 이 때문에 흔히 **"질병에 걸린다"**, **"병을 뿌리뽑다"**는 식의 표현이 자주 쓰인다. 그러나 조현병은 이러한 표현이 잘 들어맞지 않는다. 조현병에 이르게 되는 길은 환자 수만큼이나 다양하며, 병의 시작도 태생기로 거슬러 올라간다. 이쯤되면 **"조현병에 걸린 것"**인지, **"조현병 체질을 타고나는 것"**인지 알 수 없을 정도이다. 즉 환자의 신체/정신, 그리고 조현병이라는 두 개체를 서로 대립하는 존재라고 보기 어렵다는 것이다. 조현병을 바라본다는 것은, 애초부터 환자의 체질을 마주하는 것과 마찬가지이다.

약물유전체학으로부터 발전한 정밀의학은 첨단 과학의 도구를 이용하지만, 환자의 체질을 객관적으로 파악하려는 노력에 다름아니다. **차세대 염기서열 분석(Next Generation Sequencing, NGS)**이 가능해지면서, 축적된 생물학적 데이터의 양은 폭발적으로 늘어났다. 유전체(genome) 뿐 아니라, 전사체(transcriptome), 단백체(proteome), 대사체(metabolome)에 대한 정보가 축적되었다.[@manzoni2018] 이러한 소위 **omics** 학문들은 그야말로 생물체 내의 **완전한(complete)** 정보를 추적하며, 이를 통해 신체 생리를 미시적으로부터 거시적 수준까지 이해하고자 한다.(5-5장 참조) 전세계 연구소로부터 제공되어 데이터베이스에 축적된 거시적 데이터 말고도, <s>개인의 유전정보를 비교적 싼 값에 해독해주는 서비스</s>[^08-05-16]도 등장하였다. 암 치료 분야에서 이는 매우 성공적인 결과를 내고 있다. 환자의 유전체 정보를 해독하고, 이를 분석하여 <s>항암제 반응성을 예측하는 서비스</s>[^08-05-17]는 이미 미국 FDA의 승인을 받아 상용화되었다.

[^08-05-16]: 소비자가 직접 자신의 유전정보를 조사할 수 있는 대표적인 서비스로, [23andMe](https://www.23andme.com/)가 있다.

[^08-05-17]: [Personal Genome Diagnostics](https://www.personalgenome.com/)는 의료진이 보내준 환자의 혈액 및 조직으로부터 유전체 정보를 해독한 후, 기계 학습 알고리즘을 거쳐 생성한 유용한 정보를 되돌려준다.

정신의학에서도 발빠른 연구자들은 이러한 시대적 흐름에 뒤쳐지지 않으려 최선을 다하였다. 기분장애 분야에서는 이미 상당한 진전이 있어서, 유전 변이와 신경영상학 자료를 바탕으로 항우울제나 리튬의 반응을 예측하는 연구들이 다수 진행되었다.[@maciukiewicz2018; @athreya2018; @lee_applications_2018; @huhn2019] [^08-05-18] 지금까지 정밀의학의 방법론은 진단, 아형 분류, 예후 예측 등에 더 많이 사용되어 왔지만, 미국 FDA가 정밀의학의 궁극적인 목표로 삼은 것은 **"적합한 환자에게 적합한 시기에 올바른 치료를 제공하는 것"**[^08-05-19]이다.

[^08-05-18]: 한국에서도 2019년 고려대 연구팀은 ARPNet라는 기계 학습 알고리즘을 설계하여, 항우울제에 대한 반응 여부를 85%에 달하는 정확도로 예측하는데 성공하였다.[@chang2019]

[^08-05-19]: *"to fit the right treatment to the right patient at the right time"* quoted from <https://www.fda.gov/medical-devices/vitro-diagnostics/precision-medicine>

항정신병 약물의 반응성을 예측하고자 하는 연구는 비록 기분 장애에 비해서는 훨씬 수가 적지만, 착실하게 한발한발 나아가고 있다. 초기에 사용된 방법은 취약 유전자 변이 정도를 가중합으로 표시한 **다유전자 위험 점수(polygenic risk scoring, PRS)**(2-1-6절 참조)이다. 이는 단순한 가중합이기 때문에 이해가 쉽고, 복잡한 알고리즘을 적용할 필요가 없다. Zhang 등[@zhang2019]은 PRS가 낮은 환자들은 높은 환자에 비해 2배 가량 항정신병 약물에 반응하는 비율이 높았다고 하였다. 하지만 단순한 선형 조합만으로는 다수의 유전자가 상호작용하면서 자아내는 약물 반응성을 설명하기 어려울 것이다. Vivian-Griffiths 등[@viviangriffiths2019] 역시 유전 정보를 이용했지만, 가중합인 PRS 대신 비선형 조합인 서포트 벡터머신[^08-05-20] 기법을 사용하여 치료저항성을 예측해보고자 하였다. 비록 비선형 방식이 선형 방식보다 더 우수하다는 것을 입증하지는 못했지만, 좀더 정교한 알고리즘이 필요하다는 것을 시사하는 연구라 하겠다. 특정 생물학적 경로를 이루는 유전 변이들은 부작용을 예측하는데 사용되기도 한다. 도파민 신호의 세포내 신호전달을 담당하는 mTOR 신호전달계의 주요 유전자 변이를 사용하여, 추체외로 증상의 발현을 예측하려 했던 연구에서는, 비록 민감도는 40%에도 미치지 못했지만, 특이도는 80% 정도에 육박하였다.[@boloc2018]

[^08-05-20]: **서포트 벡터머신 (support vector machine, SVM)**: 분류 과제에 사용할 수 있는 강력한 기계학습(machine learning) 지도학습 모델. 각 데이터를 다차원 공간에 임베딩한 후, 가장 분류 정확도가 높은 결정경계(decision boundary)를 찾는 과정이다.

약물 반응을 예측하는 것은 유전 정보에만 국한되지 않는다. 어떤 종류의 생물학적 표지자라도 예측에 사용할 수 있을 것이며, 더욱 중요한 것은 이질적인 데이터들을 서로 통합하는 문제일 것이다. 뇌파는 이런 생물학적 지표의 하나이다. 클로자핀은 뇌파에 상당한 영향을 미치기 때문에, 역으로 뇌파 특성을 통해 클로자핀 반응성을 예측하려는 시도가 있었다.[@masychev2020; @ciprian2020] 유사한 맥락에서 P300 유발전위의 진폭, 안정기 뇌파의 부위간 연결성(coherence) 등은 전기경련 치료의 반응성을 예측하는데 이용되어 왔다.[@simon2021]

이론가들은 다양한 omics 데이터들이 서로 다른 층위에서 통합될 수 있다고 믿는다. 이들은 증상을 비롯한 전통적인 표현형보다, 다층의 omics 데이터들이 환자 상태를 이해하는데 더 많은 정보를 제공한다고 주장한다. 이들을 통합하는 <s>multi-omics profiling</s>[^08-05-21]은 생리현상과 질병을 이해하는 한차원 앞선 정보를 제공할 것이다. 이처럼 맞춤의학/정밀의학의 비젼은 야심차지만, 정신의학에서 아직까지의 연구 성과들은 이 비젼을 현실화하기에는 여전히 요원하다. 암 치료에서 얻어낸 눈부신 성과를 조현병 치료에도 적용한다는 아이디어는 일견 불가능할 것도 없다는 확신을 주지만, 세부사항을 파고들기 시작하면 장애물이 한 두개가 아니다. 민감도와 특이도, 그리고 정확도가 몇 %였다는 등 주의를 끄는 많은 연구가 꽤 있었으나, 독립된 검증 데이터셋을 통해 외부검증 단계를 거친 연구는 거의 없다. 기계 학습을 적용하기 위한 데이터셋의 규모가 수만\~수백만 명 단위라고 볼 때, 정신의학에서 아직까지 그만큼 큰 데이터셋을 사용한 연구는 보기 힘들다. 그러다보니 성공적인 연구 결과도 제대로 재현되지 않아 신뢰성에 금이 가는 일이 반복되고 있다.[@pardiñas2021]

[^08-05-21]: **Multi-omics profiling**: multinomics, panomics 등으로도 불린다. 이는 다층의 omics 데이터들이 시스템 의학의 원리 하에 서로 통합하여, 일관된 유전-형질-환경의 관계를 도출해낼 수 있다는 전략이다.

빅데이터, 기계 학습, 딥 러닝, 인공 지능 등 우리 시대의 키워드 들은 조현병 치료도 한시바삐 다음 차원으로 넘어가야할 것만 같은 조급함을 안겨준다. 그러나 조급함에 마음을 뺏겨, 조현병을 둘러싼 근본 질문들을 소홀히 하다가는, 겉멋만 쫓다가 금새 시들해지던 과거의 행태를 답습하지 않을 수 없을 것이다. 정밀의학이 정신의학의 미래를 가리키고 있는 것은 분명하지만, 현재는 비전과 슬로건만이 나부끼고 있는 실정이다.

## 약물 선택의 일반 원칙

### 일반적인 참조 기준

합리적인 약물 선택을 둘러싼 이론과 논의들은 많지만, 결국 실제 임상에서 약물을 선택할 때 참조하는 기준은 다음 몇 가지[^08-05-22]에 불과하다.

[^08-05-22]: [Guidelines on Choice and Selection of Antipsychotics for the Management of Psychosis and Schizophrenia in Adults, Hertfordshire Partnership University NHS Foundation Trust (HPFT), 2016](https://www.hpft.nhs.uk/media/5096/final-guidance-on-choice-and-selection-of-antipsychotics-in-management-of-psychosis-and-schizophrenia-dec-2016-amended-sep-18-and-nov-20-docx.pdf)서 발췌

1.  현재의 증상 특성
2.  현재의 신체적 건강 상태
3.  항정신병 약물 이외의 다른 병용 약물
4.  이전 항정신병 약물에 대한 반응 경력
5.  이전 항정신병 약물에 대한 이상 반응 경력
6.  환자가 감수할 수 있는 부작용의 범위
7.  기타 심각한 금기 사항
8.  환자 개인의 선호도
9.  비용 효과 측면
10. 제도적 한계

현재의 증상 특성에 대한 고려는 윗절 8-3-2-4. 문제가 되는 증상에 따른 선택을 참조하기 바란다. 특히 퀘티아핀과 아미설프라이드는 용량에 따라 기분 증상에 미치는 효과가 다르기 때문에 증상에 따라 용량을 선택할 수 있다. 신체적 건강 상태는 역시 부작용 프로파일과 관련이 있다. 심장질환이 있다면 QTc 연장 위험이 높은 약은 피하며, 녹내장/전립선비대증이 있으면 항콜린 효과가 큰 약물을 피한다. 전반적 건강상태가 좋지 않다면 클로자핀처럼 부작용이 다양한 약물을 쓰기 힘들며, 다른 약물을 쓴다 하더라도 고용량은 부담스럽다. 젊고 심혈관계 기능이 양호한 환자라면 기립성 저혈압 위험에도 불구하고 α~1~ 길항작용이 있는 약을 마음껏 사용할 수 있다.

### 과거에 효과가 있었던 약물

이전에 효과가 있었던 약물이 이번 삽화에도 효과가 있을 것이라는 예상은 맞기도 하고 틀리기도 한다. 환자의 체질이나 질병의 아형은 특성 변수일 터이기 때문에, 만약 약물에 대한 효과가 이들에 좌우된다면, 삽화를 거듭하더라도 환자에게 가장 효과적인 약물은 변하지 않을 것이다. 그러나 첫번째 삽화에서 A라는 약물에 적당한 효과를 보였더라도, A가 이 환자에게 최적의 약물인지는 확실하지 않다. 왜냐하면 다른 약물을 시도한 적이 없었기 때문이다. 동일 약물에 대한 효과는 재발이 반복될수록 떨어지기 때문에[@takeuchi2019], 이번 삽화에서는 A에 대한 효과가 만족스럽지 못하여 다른 약을 써야만 할 수 있다. 이렇게 따져보면 이전에 반응이 좋았던 약물보다는, 이전에 실패했던 약물에 대한 과거력을 확인하는 것이 더 중요할 것이다. 하지만 이전에 실패했던 약물이, 그야말로 효과불충분에서였는지, 아니면 부작용, 순응도, 짧은 사용 기간 등 그 밖의 원인 때문이었는지 확인하기는 쉽지 않다. 만약 효과 이외의 다른 원인때문에 실패했던 것이라면, 이번 삽화에서는 성공적일 가능성이 충분히 남아있다.

효과에 대한 과거력보다는 부작용에 대한 과거력이 좀더 안정적이다. 효과 발현은 삽화마다 들쑥날쑥하지만, 이전에 나타났던 부작용은 이번에도 다시 나타날 가능성이 높다. 따라서 과거에 중요한 부작용을 일으켰던 약물이라면 이번에도 피하는 것이 좋다. 그런데 이번에는 환자가 감수할 수 있는 부작용의 범위가 과거와 달라질 수 있다. 삽화가 반복되어 고통이 심해지면, 월경을 안 하는 것 쯤은 개의치 않게 될 수도 있다. 이렇듯, 부작용의 과거력과 함께, 현재 환자가 부작용에 부여하는 중요성도 약물 선택의 기준이 된다. 이에 비해 환자가 감수하고 안 하고를 떠나서 약물을 다시 사용해서는 안 되는 경우도 있다. 과거 무과립구증, 심근염 등을 일으킨 적이 있다면, 클로자핀을 재시도해서는 안 된다.

### 그 밖의 제약 요인

환자 개인의 선호도는 약 자체보다는 부작용에 대한 수용범위와 관련이 깊다. 전반적인 부작용에 대해서 설명하면 대다수의 환자들은 아리피프라졸을 선호한다. 그러나 아리피프라졸에 의한 좌불안석을 경험해본 적이 있는 환자는 선호도가 확 바뀌기도 한다. 주사약 사용 여부는 선호도가 가장 큰 영향을 미치는 문제이다. 환자가 앞서서 주사약을 요구하는 경우도 많지만, 괜한 저항감때문에 끝까지 거부하는 환자도 다수이다.

한국의 의료환경에서 약값때문에 약물 선택에 제약을 받는 경우는 많지 않지만, 다약제 처방이 복잡해지면 약값이 상당히 올라간다. 약값은 용량이 높아진다고 크게 달라지지 않기 때문에, 다약제를 병용하기 보다는 단일 약제를 충분한 용량으로 쓰는 것이 훨씬 경제적이다. 만약 환자가 의료보호 서비스를 받게 된다면, 갑자기 많은 제약을 받을 수 있다. 현재의 정액수가제에서 비교적 고가인 비정형 약물을 선택하기 힘들어진다. 한국에서 집계된 자료에서도 보험 서비스 종류는 정형 약물 사용 여부에 큰 영향을 미치는 것으로 나타났다.[@lee_changes_2018]

### 치료 실패 후의 약물 선택

만약 위의 원칙을 거쳐 약물을 선택하여 충분한 용량, 충분한 기간 동안 사용했음에도 불구하고, 효과를 보지 못했다면 다음 약물을 선택하여야 한다. 하지만 이 때 적용할만한 기준이나 지침은 더더욱 존재하지 않는다. 2019년에 발간된 한국형 조현병 약물 치료 지침서(KMAP-SCZ 2019)[@yun2019]는 1단계에서 비정형 약물과 장기지속형 주사제를 시도해본 후 실패한다면, 2단계에서는 **"다른 종류의 비정형 항정신병약물이나 정형 항정신병약물을 시도할 수 있다"**라고만 적혀있다. 여기서 **"다른 종류의"**라는 용어는 보통 **"다른 클래스에 속하는"**으로 해석된다. 정형 약물 시대에는 phenothiazine, butyrophenone 등 몇 가지 클래스에 국한되어 있었기 때문에, 한 가지 약에 실패했을 때 같은 클래스에 속하는 약을 사용하는 것은 의미가 없었다. 그러나 비정형 약물 시대에 들어와서는 일부 예외(리스페리돈과 팔리페리돈)를 제외하고는 모든 약이 다른 클래스이기 때문에, 클래스 구분은 큰 의미가 없다.

지침서의 권고 사항은 다시 말하여 각 단계의 약물 선택은 이전 단계의 결과와는 **독립적**이라는 뜻이다.[^08-05-23] 그러나 이는 경험상 수긍하기 어렵다. 이전의 실패 경험은 이후 약물 선택에 무언가 중요한 정보를 제공해 줄 지도 모른다. 과거 정형 약물 시대에는 고역가 약물에 실패했다면 이번에는 저역가 약물을 시도해보는 것이 유리하다는 등, 근거는 비록 확실하지 않았지만 나름의 요령이 있었다. 그러나 비정형 약물에서는 이런 요령을 찾아내기 힘들다. 경험이 쌓이다보면, 세로토닌-도파민 길항제에 실패했다면 다음 번에는 D~2,3~ 길항제를 써본다던가, 도파민 부분효현제에 실패했다면 그 다음에는 다수용체 길항제를 써본다는 등의 나름의 요령이 생길지도 모른다. 그러나 이에 대한 임상 근거는 전혀 없다.

[^08-05-23]: 즉 이전에 어떤 약물에 실패했다 하더라도, 그 사실은 다음 약물에의 성공 확률에 영향을 미치지 못한다.

이런 지식의 공백을 인지한 탓인지 중국과 미국의 연구진은 <s>SMART-CAT</s>[^08-05-24]라는 연구를 계획하고 있다.[@li2021] 이 연구는 항우울제를 대상으로 했던 \<s\>STAR\*D 연구\</s\>[^08-05-25]를 선행모델로 하여, 첫번째 약물에 실패했을 때 어떤 식으로 약물을 선택해야 가장 효과적인지를 탐색하고자 한다. 이런 식의 연구가 결실을 얻게 되면, 항정신병 약물의 순차적 선택도 합리적 지침을 얻을 수 있을 것이다.

[^08-05-24]: Sequential Multiple-Assignment Randomized Trials to Compare Antipsychotic Treatments

[^08-05-25]: Sequenced Treatment Alternatives to Relieve Depression (STAR\*D)[@sinyor2010]

## References {.unnumbered}
