---
title: "부작용"
author: "정성훈"
bibliography: References/09-01.bib
---

## 약물유해반응

### 약물유해반응의 개념

세계 보건 기구에 따르면 **약물유해반응(Adverse Drug reaction, ADR)**이란 **"약물에 의한 유해하고 의도하지 않았던 반응"**으로 정의된다. 확실한 인과관계의 증명을 요구하는 것은 아니며, 다만 약물에 의해 일어났을 수도 있다는 합리적인 의심이 가능할 때를 가리킨다. 이에 비해, **(의도하지 않았던) 부작용(unexpected side effect)**은 **"정상적 용량에서 나타나는, 약리학적 효과에 일어났지만 의도하지는 않았던 효과"**로 정의된다. 이는 해로울 수도 있지만, 오히려 이로울 수도 있다. 예를 들어 삼환계 항우울제는 과민성대장증후군 증상을 경감시킬 수 있는데, 이는 의도했던 효과는 아니다.[@rahimi2009] 따라서 이 효과는 부작용이지만 약물유해반응은 아니다.

신약 개발 과정에서 당연히 부작용에 대한 스크리닝이 진행되지만, 드문 부작용은 일반 환자군에 널리 사용된 이후에야 드러나기 시작한다. 따라서 약물이 시판되고 난 후 예기치 못했던 ADR을 발견하고 평가하는 과정을 **시판 후 조사(postmarketing surveillance, PMS)**라고 하는데, 만약 시판 후 조사에서 ADR이 빈도가 높거나, 심각하다고 판단된다면, 약품의 허가를 철회하고 시장에서 퇴출시킬 수도 있다. 좀더 큰 개념으로 **약물감시(pharmacovigilance)**란 의약품의 유해사례 또는 안전성 관련 문제의 탐지/평가/해석/예방에 관한 모든 과학적 활동을 말한다.

모든 ADR이 심각한 것은 아니며, 환자들이 보고하는 부작용 중 5% 정도만이 심각한 문제[^09-01-1]가 된다.[@iversen2018] 보통 정신과에서 심각하다고 하는 것은, 부작용으로 인해 수술 혹은 입원치료가 필요하거나, 입원치료가 연장되거나, 장애가 남거나, 선천성 기형이 발생하거나, 자살 시도를 하거나 혹은 생명을 위협할 정도의 끔찍한 경험을 하게 된 것을 의미한다.

[^09-01-1]: 이러한 부작용을 Serious adverse event (SAE) 혹은 serious adverse drug reaction (sADR)이라고 한다. 여기서 심각하다는 것은 다음 결과 중 하나에 해당할 때를 말한다. 1) 사망, 2) 생명의 위협, 3) 입원 치료나 퇴원의 연기 4) 지속적인 장애 상태, 5) 선천적 기형

어떤 약이나 마찬가지이겠지만 정신과 약물 역시 다양한 부작용과 약물유해반응을 갖고 있다. 심각한 ADR 때문에 시장에서 퇴출된 약물[^09-01-2]도 있지만, 클로자핀처럼 심각한 ADR이 있다는 것을 알면서도 그대로 사용 중인 약물도 있다. 그리 심각하지 않은 ADR인 경우에는, 위험/이익 비를 고려하여 그대로 사용하고 있는 경우가 대부분이다. 환자에 따라서는 부작용을 치료적 목적으로 역이용하는 경우도 있다. 진정 작용이 강한 항정신병 약물은 흥분상태에 있는 급성 환자를 조절하기 위해, 혹은 불면증에 시달리는 환자를 돕기 위해 사용된다. 21세기 들어 개발된 항정신병 약물들이 대부분 우울증에도 효과를 보이는 것은 의도된 효과라고 해야할 지, 예기치 않았던 부작용이라고 해야할 지 애매하다.

[^09-01-2]: 예를 들어 remoxipride, sertindole, thioridazine, lorcaserin 등

### 약물유해반응과 치료 전략

하지만 특히 조현병 환자에서는 심각하지 않은 ADR이나 부작용이라도, 순응도를 떨어뜨리거나 삶의 질을 저하시켜, 궁극적으로 치료 실패를 가져오는 경우가 허다하다. 그렇다고 무조건 ADR을 최소화하는 치료 전략을 고수할 수는 없다. ADR을 조현병의 증상과 감별하는 것이 쉽지 않을 때가 많으며, ADR을 치료에 불가피한 약리 작용과 분리하기 어려울 때도 허다하다. 더불어 ADR의 심한 정도와 환자가 겪는 고통은 비례하지 않으며, 환자에 따라 감내하기 어려운 ADR은 모두 다르다. 안타깝지만 목적한 치료 효과를 내려면, 일정 수준 이상의 ADR을 감수해야 할 경우가 많다. 따라서 의사의 과업은 무조건 ADR을 최소화하는 것이 아니라, 환자의 주관적 고통을 최소화하면서 효과와 ADR 사이의 미묘한 균형을 유지하는 것이다. 이 과업은 정신과 의사의 지식과 임상경험 뿐만 아니라, 환자의 협조가 절대적으로 필요하다.[@morant2018; @kaar2019]

현대의 정신약물학과 항정신병 약물 개발은 막대한 발전을 이루었지만, 다양한 부작용을 만족할만큼 해결하지 못하였고, 정신병은 치료될 지언정 다른 건강문제가 야기되는 상황이 초래되고 있다. 조현병 환자의 치료는 정신병적 증상의 소실 만으로 그치지 않으며, 이들이 궁극적으로 신체와 정신 양쪽 모두가 건강한 상태에서 의미있는 삶을 누릴 수 있도록 돕는데까지 확장되어야 한다. 부작용의 해결은 단순히 순응도를 높여 치료 성공률을 높이는 것뿐만 아니라, 이러한 궁극적 치료 목표를 달성하는데 필수적이다.

### ADR의 분류

ADR은 다양한 방법으로 분류할 수 있지만, 대표적으로는 기전에 따라 A형과 B형으로 분류한다. A형 반응은 예상되는 약리적 효과가 환자의 특성때문에 통상 용량에서 과장되게 나타나는 것이다. 이는 충분히 예측가능하며, 용량을 조정하거나 일시적으로 끊음으로써 쉽게 되돌릴 수 있다. 대체로 심하지 않고, 용량에 비례하기 때문에, 용량이 상승되면 거의 모든 환자에서 나타날 것이라 예상할 수 있다. 예를 들어, 항콜린성 부작용은 M1 수용체 차단작용이 큰 항정신병 약물을 복용하는 거의 모든 환자에서 나타날 것이라 예상할 수 있다. 그러나 어떤 환자는 상당한 용량에서도 잘 나타나지 않는 반면, 민감한 환자들은 소량에서도 심하게 나타난다.

이에 비해 B형 ADR은 소위 특이체질 반응(idiosyncratic reaction)을 의미한다. 약물의 효과로 설명할 수 없고, 용량과 무관하며, 미리 예측할 수도 없다. B형 반응의 대부분은 약물이 항원으로 작용하여 면역 기전을 매개로 일어나는 것으로 과민성 쇼크(anaphylactic shock), 무과립구증, 신경이완제 악성증후군 등이 이 범주에 속한다. B형 ADR은 매우 드물기 때문에 시판전에 걸러지지 않으며, 약물이 얼마 동안 시장에 출시되어 다양한 환자 집단에서 사용된 후에야 드러난다.

B형 ADR은 예측 불가능하다고 하지만, 용량 관련성, 시간에 따른 경과, 환자의 인구학적 정보, 유전적 정보 등을 통해 조금은 예측도를 올릴 수 있다. 예를 들어 마취 후 드물게 나타나는 악성 고열증은 Ryanodine 수용체 유전자(RYR1)의 변이가 강력한 위험 인자이다. 클로자핀 복용 후 나타나는 무과립구증이 투여 초기 18주 내에 집중된다는 것도, 예측 인자 중 하나이다.

## 약물 사용의 주관적 경험

### 주관적 경험과 임상적 의미

조현병 치료뿐만 아니라 현대 의학의 새로운 패러다임에서 환자는 더 이상 치료의 수동적 수혜자가 아니라, 자신의 치료 과정에 능동적으로 참여하는 의사결정자로 여겨진다. 물론 초발 환자라면 증상을 완전히 없애 원래 삶으로 되돌이키는 것을 목표로 할 수 있지만, 조현병과 같은 만성 질환의 경우 증상의 완전한 소실보다는 고통스럽지 않고 의미있는 삶이 목표가 될것이다. 따라서 치료에 대한 환자의 주관적 경험과 만족도는 중요한 치료결과로 간주될 것이다.[@hellewell2002]

과거 의사들은 조현병 환자의 주관적 경험을 신뢰하지 않았다. 환자들은 흔히 비합리적 사고와 원할하지 않은 의사 소통으로, 자신의 감정, 가치 및 만족도에 대해 제대로 보고할 수 없는 것으로 간주되어 왔다. 게다가 근거중심의학은 신뢰도를 무엇보다 중요시하기 때문에, 어떤 임상 시험에서도 환자의 주관적 경험과 만족도를 결과 지표로 삼지 않았다.

그러나 비정형 약물의 도입으로 약물의 부작용이 줄어들면서, 약물 치료를 받고 있는 환자라도 충분히 자신의 경험을 제대로 묘사하고 평가할 수 있다는 것이 분명해졌다. 더불어 자기보고식 평가도구가 점점 더 정교화되면서, 이러한 평가도구가 충분한 신뢰도를 지닌다는 것이 입증되었다. 자기보고의 신뢰도는 증상이 경한 환자 뿐만 아니라, 왠만큼 심한 환자의 경우에도 충분히 높은 편이었다.[@goldberg2002; @bell2007]

항정신병 약물 치료를 받는 환자의 자기보고를 통해 확인할 수 있었던 것은, 이들이 자발적 사고 및 행동을 하는데 어려움을 겪으며, 정서반응이 부자연스럽다고 느끼며, 궁극적으로 자기 삶을 사는 것 같지 않아 힘들어한다는 것이다.[@moncrieff2009; @read2020] 이러한 현상은 조현병 자체의 병리 현상보다는 약물 부작용으로 보여지며, 전통적으로 <s>신경이완제 유발 결핍증후군</s>[^09-01-3]이라는 개념으로 설명되었다.[@lewander1994]

[^09-01-3]: Neuroleptic induced deficit syndrome (NIDS)

신경이완제 유발 결핍증후군, 혹은 좀더 폭넓은 개념인 <s>항정신병 약물에 대한 불쾌감</s>[^09-01-4]은 약물 사용과 연관된 불안, 우울, 무기력, 의욕 저하, 무정동, 신체적 불편감 등의 증상을 총칭한다. 이는 추체외로 증상을 경험하지 않는 환자에서도 나타나며, 조현병이 아닌 다른 이유로 사용할 때도 비슷한 증상이 보고된다.[@margolese2002] 이 증상은 외부 관찰자의 눈에는 운동부작용 및 음성증상, 우울증상과 잘 구분되지 않지만, 환자에게 강한 정서적 반응을 일으킨다는 차이가 있다. 불쾌감은 순응도에 직접적인 영향을 끼치며, 순응도와는 독립적으로도 치료 반응에 부정적 영향을 준다. 심지어 치료 첫날에 경험한 불쾌감이 4\~8주 이후의 치료 결과를 예측하는데 기여했다는 보고가 있을 정도이다.[@vanputten1981; @voruganti2002] 초기 반응이 그만큼 중요한 이유는, 약물에 대한 첫인상이 이후에 환자가 약물 치료에 적극적으로 동참할 것인지, 거부감을 유지할 것인지를 결정하기 때문이다.[@awad1996]

[^09-01-4]: **항정신병 약물에 대한 불쾌감 (antipsychotic drug induced dysphoria, neuroleptic dysphoria)**: 약물 복용 후 환자들이 경험하는 전체적으로 부정적인 정서 반응. 저역가 약물보다는 고역가 약물에서 흔하기 때문에 D~2~ 차단과 연관이 있을 것이라 여겨진다. 예를 들어 측좌핵의 도파민 신호가 차단되면 쾌락 중추의 정상적 작용이 억제되어 삶의 기쁨을 느낄 수 없게 된다.[@voruganti2004; @wu2015]

초기의 불쾌감은 아직 추체외로 증상을 경험하기도 전에 겪는 주관적 반응이기 때문에, 단순히 운동부작용의 일종이라 치부하기는 어렵다.[@voruganti2004] 비정형 약물이 시장에 도입되었을 때, 제약사는 물론 많은 의사들은 추체외로 증상이 줄어들면 자연히 순응도가 높아지리라 기대하였다. 그러나 상황이 그렇게 단순하지는 않았고, 순응도를 결정하는 것이 단순히 추체외로 증상만은 아님이 분명해졌다.[@hale1995; @dolder2002; @aschersvanum2006]

### 약물에 대한 거부감

조현병 치료를 성공적으로 이끌려면, 왜 환자들이 약물에 대해 거부적인지 이해할 필요가 있다. 조현병 환자들은 다른 질환 환자들에 비해 유달리 순응도가 떨어지며, 약물에 대한 불쾌감도 유독 높은 편이다.[@lacro2002] 상황이 이렇게 된 데는 다양한 요인이 작용할 것이다. Larsen과 Gerlach[@larsen1996]은 이를 1) 질병 자체의 특성, 부작용 및 2) 의사-환자 관계로 구분하여 설명한다.

질병의 속성 상 환자들은 자신의 질병에 대한 통찰력이 부족하며, 일부 환자들은 음성/인지 증상때문에 질병의 병태생리 및 약물의 효과를 이해하지 못한다. 약물로 인한 불괘감이나 부작용은 약을 먹자마자 금방 드러나며, 환자는 물론 외부인에게도 분명해보이지만, 치료 효과는 한참 후에나 나타나며, 그다지 뚜렷하게 경험되지 않는 것이 문제를 더욱 심화시킨다. 환자들은 자신이 병들어있다는 것을 부정하는 것 만큼이나, 약물을 사용한 후 정상으로 돌아왔다는 것도 인정하지 않는다. 급성 정신병적 삽화 자체에 대한 기억을 잃어버리기도 하며, 현재 자신의 사회적/직업적 기능이 저하된 것에 대해 질병 때문이 아닌 다른 이유를 갖다 붙이는 경향이 있다.

부작용 역시 약물에 대한 거부적 태도에 결정적이다. 추체외로 증상은 운동 증상 뿐만 아니라 사고, 인지, 혹은 정서적 장애를 일으킨다. 환자들은 생각이 예전처럼 자유롭게 진행되지 않고, 둔탁해졌음을 보고한다. 좌불안석은 특히 고통스러운 부작용으로, 심한 경우 자살 위험을 높이기까지 한다. 의사들은 겉으로 드러나는 운동부작용에 관심을 집중하는 경향이 있지만, 환자들은 운동감소증(akinesia)이나 이상운동증(dyskinesia)에 대해 눈치채지 못하거나 별반 신경을 쓰지 않는 경우도 많다. 그에 비해 막연한 불쾌감에 대해선 상당히 예민하게 반응한다. 또한 특히 남성의 경우 성적 부작용은 드러나지 않게 거부감을 조장하는 중요한 요인이다. 남성들은 자신의 성적 역량을 자신의 가치나 자존심의 근간으로 생각하기 때문에, 설령 배우자나 성적 파트너가 없더라도 중요시한다.

마지막으로 중요한 것은 의사-환자 관계이다. 조현병 증상으로 충동/공격적 행동을 보이거나, 가족이나 지역 사회에 물의를 빚었던 환자에 대해, 가족은 물론 의사들조차 "타인에게 피해를 주었으니 약을 먹고 자중해야 한다"는 메시지를 전달하기 쉽다. 이 경우 약물은 징벌이나 속죄의 의미를 띠게 되는데, 환자들은 자연히 자신을 바라보는 이런 시각에 대해 거부감을 표시한다. 그 밖에도 의사와 환자가 상호 작용하는 방식은 질병에 대한 이해나 태도, 약물 치료의 장점에 대한 이해 및 태도에 큰 영향을 미친다.

### 정형 및 비정형 항정신병약물

정형 약물에 대한 환자의 태도는 운동부작용이 있든 없은 거의 예외없이 부정적이다. 이 약물들은 모두 D~2~ 수용체를 강하게 차단하기 때문에, Karamatskos 등[@karamatskos2012]은 도파민 차단이 보상 회로의 정상적인 작용을 방해하여 불쾌감을 초래한다고 주장하였다. 사실 건강한 지원자들에서 소량의 정형 약물을 한두차례만 투여해도 40% 가량이 불쾌감을 경험한다.[@king1995] Voruganti 등[@voruganti2001]은 SPECT 촬영을 이용하여 D~2~ 수용체 차단과 기능과 주관적 불쾌경험 간의 높은 상관관계를 보고하기도 하였다.

D~2~ 차단 강도가 낮거나 부분 효현제인 비정형 약물은 추체외로 증상뿐 아니라 무의욕, 불쾌감, 결핍 증후군과 같은 주관적 부작용도 유의하게 적은 것으로 보인다.[@karow2002] 대신 비정형 약물은 대사 증후군을 유발하지만, 다행히도 이는 약물에 대한 거부감 자체에는 크게 영향을 주지 않는다.[@garcíacabeza2001] Awad와 Voruganti[@awad2005]는 리스페리돈, 올란자핀, 퀘티아핀 혹은 정형 약물을 6개월 이상 투여받고 있는 환자군을 대상으로 부작용과 주관적 반응을 조사하였다. 비정형 약물을 투여받은 환자들은 정형 약물군에 비해 유의하게 부작용이 적었고, 치료에 대해 보다 긍정적이고 우호적인 태도를 보였다. 그렇다고 해서 의사가 평가한 삶의 질이나 GAF로 측정한 기능 정도가 더 높아진 것은 아니었다. 이는 자신의 삶과 현재 치료에 대해 만족하는 정도가, 객관적인 기능을 중심으로 측정한 삶의 질과 반드시 일치하지 않는다는 것을 보여준다. 초기 정신증 환자를 대상으로 약물에 의한 불쾌감 빈도를 직접 비교한 연구에서는, 정형 약물을 썼을 때 불괘감의 빈도가 16.5%였던 반면, 비정형 약물을 투여한 환자에서는 4.6%만이 불쾌감을 호소하였다.[@opjordsmoen2009] 이러한 차이는 실제 순응도에도 영향을 미치는 것 같다. 비정형 약물은 저/중/고 역가를 불문하고 모든 정형 약물에 비해, 약물 치료를 지속하는 기간이 길었다.[@aschersvanum2006]

같은 비정형 약물이라도 주관적 경험은 차이가 날 수 있다. Sechter 등[@sechter2002]은 이중 맹검 조건 하에서 리스페리돈과 아미설프라이드 투여 군의 주관적 반응을 평가하였다. PANSS 호전 정도에서는 두 군간에 차이가 없었으나, 환자들은 아미설프라이드에 대해 좀더 선호도를 보였으며, 이는 사회적 기능과 치료에 대한 긍정적 평가에도 반영되었다. 또 다른 연구에서는 리스페리돈과 클로자핀에 비해 올란자핀이 주관적 평가나 삶의 질에서 더 긍정적이었다.[@naber2001] 물론 비정형 약물에 대한 모든 연구가 긍정적인 결과를 보이지는 않았다. 정형 약물과 비정형 약물 투여 환자의 주관적 삶의 질을 비교한 연구에서, 약물의 차이는 삶의 질에 별반 영향을 주지 않았다.[@tempier2001] 비정형 약물이라고 해도 제각기 다양한 성격을 갖고 있으며, 현저하게 상이한 부작용을 보일 것이다. 또한 비정형 약물은 새로운 부작용들을 가져왔으며, 고용량이 되면 어김없이 D~2~ 를 강력하게 차단하기 때문에 또 다른 거부감을 일으킬 수 있다. 문헌에서는 주관적 불쾌감이 예외없이 도파민 활성에 좌우된다고 언급하고 있지만, 5-HT 시스템이나 아드레날린, 아세틸콜린, 히스타민 등 그 밖의 수용체 들이 주관적 불괘감에 관여할 가능성도 무시할 수 없다.

## 부작용의 평가

항정신병 약물의 부작용은 추체외로 증상 뿐만이 아니다. 따라서 운동부작용의 객관적 평가에만 치중하다보면 다른 부작용을 놓칠 수 밖에 없다. 치료에 조금이라도 협조적인 환자는 부작용을 적극적으로 보고하고 대책 마련을 요구하지만, 그렇지 않은 대부분의 환자들은 그저 말없이 치료에 순응하지 않을 뿐이다. 따라서 관찰자의 객관적 관찰에 의존하는 부작용 측정 도구만으로는 평가가 완전하지 못하며, 환자로 하여금 주관적 경험을 상세히 보고하도록 권해야 한다. 이를 위해선 환자의 불편감에 대해 경청하고, 치료 전략에 환자의 의향을 적극적으로 반영할 준비가 되어있음을 보여주어야 한다. 단순히 부작용이 있고 없음이 문제가 아니라 그것이 환자에게 미치는 영향을 조사하고, 어느 정도까지 환자가 수용할 수 있는지 평가해야 한다. 대안이 있다면, 그것이 갖는 또 다른 부작용 위험성, 예상되는 효과 및 환자에게 미칠 영향에 대해 평가하여야 한다. 이러한 평가는 모두 환자를 치료 전략 결정에 적극 참여시키지 않고는 진행하기 어렵다.

### 평가 척도

예로부터 항정신병 약물 사용 시 부작용을 평가하는데 썼던 척도들은 주로 운동부작용에 집중되어 있으며, 여기에는 심슨-앵거스 평가 척도(SAS), BARNES 좌불안석 평가 척도(BAS) 그리고 비정상적 불수의 운동 척도(AIMS)가 포함된다.(7-4-1-4절) 그러나 운동부작용 이외의 부작용과 주관적 경험이 강조되면서, 광범위한 신체 및 정신 부작용을 평가하는 자가설문지가 늘어났는데, 대표적인 예로 <s>글래스고우 항정신병 약물 부작용 척도</s>[@waddell2008][^09-01-5]와, <s>리버풀 항정신병약물 부작용 평가 척도</s>[@day1995][^09-01-6]가 있다.

[^09-01-5]: Glasgow Antipsychotics Side-Effect Scale (GASS)

[^09-01-6]: Liverpool University Neuroleptic Side Effect Rating Scale (LUNSERS)

자가설문지는 아니지만, 평가자가 체계적으로 평가하는데 도움을 주는 인터뷰 도구로는 Systematic Assessment for Treatment of Emergent Events (SAFTEE)[@levine1986]와 SAFTEE를 소아 환자를 위해 번안한 Safety Monitoring Uniform Report Form(SMURF)이 있다.[@greenhill2004] 좀더 최근에는 Systematic Monitoring of Adverse events Related to Treatments (SMARTS)가 개발되어 비교적 간편하게 사용할 수 있다.[@haddad2014]

| **SMARTS checklist questions (Are you troubled by...)**                       | **Potential side effect addressed**                                                                           |
|------------------------------------|------------------------------------|
| 1\. Difficulties in your movement such as shaking, stiffness or muscle aches? | Parkinsonism, tremor                                                                                          |
| 2\. Changes in your weight or appetite?                                       | Weight and appetite change                                                                                    |
| 3\. Problems with your sex life?                                              | Sexual dysfunction (may reflect raised prolactin and/or other pharmacological mechanisms)                     |
| 4\. Changes in your periods or changes in your breasts?                       | Hyperprolactinaemia                                                                                           |
| 5\. Dizziness or light-headedness?                                            | Postural hypotension                                                                                          |
| 6\. Tiredness or sleepiness?                                                  | Sedation                                                                                                      |
| 7\. Restlessness or feeling fidgety?                                          | Akathisia                                                                                                     |
| 8\. Constipation, diarrhoea, nausea, stomach problems or dry mouth?           | Gastrointestinal side effects (e.g. antimuscarinic side effects)                                              |
| 9\. Difficulty passing water or passing water very frequently?                | Urinary symptoms (e.g. antimuscarinic action may cause urinary retention; type 2 diabetes may cause polyuria) |
| 10\. Problems with your concentration or memory?                              | Sedation                                                                                                      |

Systematic Monitoring of Adverse events Related to Treatments (SMARTS)[@haddad2014]

나열된 척도 가운데 GASS와 SMARTS가 가장 현실적일 것 같다. 모두 환자 스스로 작성하며, 대기실에서 기다리는 동안 답할 수 있을 정도로 짧고, 간편하다. 그러면서도 적용 범위가 광범위하며, 각 항목의 빈도와 심각도를 모두 평가한다. SAFTEE는 반구조화된 면담도구로 시간이 많이 걸리고, LUNSER는 자가설문지이긴 하지만 무척 길다. SAS, BAS 및 AIMS는 좁은 범위의 부작용만을 목표로 하여 평가하는 연구용 도구이다.

### 정신과 이외 의학적 지식의 필요성

정형 항정신병 약물을 사용하던 시대의 정신과 의사는 신경과 의사의 기술이 필요했다. 당시에 부작용 모니터링의 초점은 신경학적 부작용 특히 운동부작용을 감지하는데 있었다. 그러나 비정형 약물이 일반화된 시대로 접어들면서, 심혈관계 질환, 대사 질환, 내분비 질환의 위험성에 대한 모니터링이 더욱 중요해졌다. 이런 전신적인 문제를 정기적으로 추적관찰하고 건강상태를 모니터링하려면, 정신과 의사가 내과적인 지식을 겸비하는 것이 이상적이다. 물론 이상이 발견되어 치료를 요할 정도라면, 타과 전문의의 도움을 청하는 것이 바람직하겠지만, 이상 소견을 찾아내는 1차 의료 서비스까지 타 기관에 의뢰해야 한다면 문제가 복잡해진다. 지역의 1차 의료기관과 정신과 의사가 활발히 의사소통하기 힘들 뿐더러, 환자들은 새로운 의사(1차 진료의)에게 자신의 문제를 털어놓기 어려워한다. 따라서 환자를 일차적으로 책임지고 있는 정신과 의사가 기본적인 내과 지식을 갖추고 있어야 한다.

의사가 필요한 지식을 갖추는 것 말고도 부작용 모니터링이 효과적으로 이루어지려면, 환자 자신 및 환자를 돌보는 보호자나 간병인의 역할이 중요하다. 치료 효과나 부작용을 스스로 인지할 수 있도록 교육이 필요하며, 효율적인 의사 소통 채널이 마련되어야 한다. 또한 문제가 발생했을 때 의뢰할 수 있는 타과 전문의들과의 협업 프로세스가 마련되어 있어야 한다. 현재 환자에게 발생한 건강 상의 이상에서 정신과 치료가 차지하는 비중이 어느 정도인지, 사용해선 안되는 약물이나 겹치는 약물은 없는지, 약물 상호작용에서 주의할 점은 무엇인지, 어디까지가 예상가능한 부작용이고 어디서부터 그렇지 못한 것인지 등등에 대한 정보를 협업하고 있는 타과 전문의들과 공유해야 한다.

## References {.unnumbered}
