---
title: "소화기계 부작용"
author: "정성훈"
bibliography: References/09-08.bib
---

## 구강 계통의 부작용

### 치과 질환

항정신병 약제가 원인이라기보다는 조현병 환자의 불규칙한 식사습관, 당분이 풍부한 자극성 음식, 흡연, 부적절한 구강 위생, 그리고 당뇨와 같은 대사 증후군은 치아 우식증과 치주 질환을 일으키는 강력한 위험인자들이다. 실제로 조현병 환자에서 충치가 생긴 치아의 개수는 일반 인구에서 발견되는 수준의 두 배이다.[@wey2016; @denis2019] 이러한 격차는 40대 미만에서는 아직 잘 드러나지 않으나, 연령이 증가할수록 격차가 벌어진다.

반면 불량한 구강 건강에 항정신병 약물이 얼마나 기여하는지는 확실하지 않다. 한 연구에서는 비정형 약물 사용군에 비해 정형 약물 사용군이 더 구강 건강이 안 좋았다고 하나, 이는 사회경제적 상태가 개입되었을 가능성이 크다.[@grinshpoon2015] 약물이 구강 위생을 해치는 기전은 항콜린 효과에 의한 구강건조증(xerostomia)와 클로자핀의 독특한 부작용인 침흘림(sialorrhea)이다. 전자는 충치, 치주염(gingivitis), 설염(glossitis), 구내염(stomatitis), 이하선염(parotitis), 혀 갈라짐(fissured tongue) 등을 일으킨다.[@friedlander2002] 반면 타액이 과다해지는 것 역시 충치와 치주염에는 직접적인 영향이 없다고 하지만 구강 위생에 좋지 않은 영향을 미친다.[@hegde2008] Eltas 등[@eltas2013]은 침흘림을 억제하는 항정신병 약물을 복용하는 군과 클로자핀을 복용하는 군 사이의 구강 위생을 비교하였다. 그 결과 확실히 치석의 양이나 잇몸 상태가 전자에서 더 불량하였다. 결국 정상적인 침분비가 구강 건강 유지에 그만큼 중요하다는 것을 엿볼 수 있다.

### 입마름과 구강건조증

항정신병 약물을 복용하는 환자 중 다수가 입이 바짝 마르고 혀가 갈라진다는 <s>구강건조증</s>[^09-08-1]을 호소한다. 일반적으로 약물의 항콜린 효과 때문으로 여겨지지만, 항콜린 효과가 강하지 않은 아미설프라이드, 퀘티아핀, 올란자핀 등 약물을 복용한 후에도 구내염 및 궤양, 인두염, 설염 등이 흔히 관찰된다.[@lai2016] 하지만 이러한 연구결과를 해석할 때는 많은 환자들이 동시에 항파킨슨제를 사용한다는 것도 고려에 넣어야 한다.[@fratto2014] 구강건조증은 그 자체만으로도 환자에게 주관적 고통을 주지만, 구역/구토와 함께 치과 질환의 중요한 위험 요소이다.[@cockburn2017]

[^09-08-1]: **구강건조증 (xerostomia)**: 환자가 주관적으로 입마름을 호소하는 상태. 객관적인 기준은 없지만, 타액이 분비되는 속도가 자연 흡수 + 자연 증발되는 속도를 따라가지 못하면 구강건조증이라 할 수 있다. 일반적인 진단기준은 자극받지 않았을 때 타액분비 속도가 0.1mL/min 이하, 자극을 주었을 때 0.5\~0.7mL/min 이하일 때이다.[@villa2015] 그러나 주관적 불편감이 꼭 침분비량과 역비례하는 것은 아니다.

약물을 쓰지 않는 치료법으로는 산도가 높은 과일 섭취, 무설탕 껌이나 사탕, 구강청결제 가글 등 침샘을 자극하는 방법을 시도해본다.[@rajkumar2019] 담배와 카페인 음료는 피하도록 하며, 알코올 및 알코올 성분이 든 구강청결제도 입을 건조하게 만든다는 것을 교육시킨다.

미국 FDA는 쇼그렌(Sjögren) 증후군에 의한 구강건조증의 약물 치료제로 cevimeline (Evoxac®)과 pilocarpine (Salagen®)을 승인하였다. 둘 다 경구로 복용하며, M~3~ 무스카린 수용체를 자극하여 침과 눈물의 분비를 늘린다. Pilocarpine은 녹내장 치료에 사용되는 안약 형태로도 시판되는데, 이를 입을 헹굴 때 사용하면 입마른데 도움이 된다.[@theunissen2021] 이외에 비특이적 무스카린 수용체 효현제인 bethanehol도 사용해볼 수 있다. 한국에서 cevimeline은 거의 사용되고 있지 않지만, pilocarpine의 경구제 및 안약, 그리고 bethanechol은 쉽게 처방할 수 있다.

### 침흘림

한국어에서는 뭉퉁그려 침흘림이라고 표현하지만, 엄밀하게 말하면 침과다증(sialorrhea, ptyalism, hypersalivation)는 침이 과다하게 생성되는 것이고, 침흘림(drooling)은 잘 삼키지 못하여 겉으로 흘리는 것이다. 어린아이들은 정상적으로도 침을 많이 흘리지만 4세가 넘어서도 침을 흘리면 비정상으로 본다. 뇌성마비, 지능저하 환자들이 흔히 침을 흘리며, 파킨슨병에서도 70% 이상의 환자가 침과다증과 침흘림을 보인다.[@isaacson2020] 이러한 사례에서는 침이 과다 생성되는 것보다는, 침을 제대로 삼키지 못하는 것이 더 문제가 된다.

정신과 문헌에서 주로 거론되는 것은 클로자핀 복용 환자들의 침흘림이다. 앞서의 경우와는 달리 낮 동안에는 그다지 눈에 띄지 않다가 수면 중에 심해지는 것으로 보아, 침흘림보다는 침의 과다 생성이 더 문제가 되는 것으로 보인다. 무스카린성 M~3~ 수용체는 침 생성을 늘리고, M~4~ 수용체는 억제한다. 클로자핀은 두 수용체 모두에 결합할 수 있지만, 길항 효과를 보이는지, 효현 효과를 보이는지 조차 아직 불확실하다.[@sockalingam2007] 이에 더해 α~2~ 수용체 길항 효과도 침 생성을 자극한다.

아마도 침이 과다하게 생성되기 때문으로 여겨지고 있지만, 실제 침 분비량을 측정한 연구에서는 대조군에 비해 큰 차이가 없는 것으로 나타났다.[@ben_aryeh1996] 파킨슨병처럼 침을 제대로 삼키지 못해서 겉으로 흐르는 것이라는 견해를 비롯하여, 일중주기(circadian rhythm)의 변동으로 인해 유난히 잠잘 때만 침이 많이 생성된다는 견해가 제기되었다. 기전이 어쨌든 간에 클로자핀 복용 환자들은 잠에서 깨어났을 때 머리카락과 베개가 침에 흠뻑 젖을 정도이며, 수면 장애, 턱과 피부 주변 부위의 염증, 피부 감염 및 흡인성 폐렴 등이 발생하기도 한다. 침흘림은 야뇨증과 함께 클로자핀 복용 환자들에게 수치심을 안겨주는 주된 원인으로, 주관적 고통이 매우 심하다. 침흘림을 그대로 방치하면 일부 환자에서 이하선이 비대해지는 후유증을 야기할 수 있다.[@vasile1995; @immadisetty2012]

침흘림에는 뾰족한 치료법이 마련되지 않았다. 전통적으로 hyoscine, scopolamine, glycopyrrolate, ipratropium 등의 항콜린제를 이용하여 침의 생성을 어떻게든 줄이고자 하였으나, 실상 별 효과가 없으며 전신성 항콜린 효과때문에 부작용만 늘어난다. 해외 문헌에는 뇌-혈액 장벽을 넘지 않는 M~1~/M~4~선택적 차단제로서, 궤양약으로 사용되는 pirenzepine (Bisvanil®)과 마취 전 침 분비 억제를 위해 사용되는 glycopyrrolate (Robinul®)이 가장 많이 권해진다. 하지만 경구 glycopyrrolate은 역시 약효가 전신에 퍼지기 때문에 매일 사용하기는 무리가 있다. 미국에서는 시럽 형태 (Cuvposa®)가 출시되었고, 이는 소아 및 뇌성 마비 환자의 만성 침흘림에 일차적으로 추천된다. 지난 10여년간 클로자핀에 의한 침흘림에도 Cuvposa®가 추천되어 왔는데, 안타깝게도 한국에서는 시판되지 않는다.[@isaacson2020]

### 연하 곤란

역사적으로 만성 정신병원에서 발생하는 돌연사의 상당 부분은 음식을 잘 삼키지 못하다가 기도가 막혀 사망한 사례들이다.[@fioritti1997; @crouse2017] 이런 극적인 사례가 아니더라도 만성적인 연하 곤란은 탈수, 영양 부족, 투약 거부 및 흡인성 폐렴을 일으켜 환자의 건강 상태를 악화시킬 수 있다. 사레들림이나 흡인성 폐렴은 특히 요양원에 거주하며, 섬망이나 행동 문제때문에 항정신병 약물이 투여되는 치매환자들에게 자주 발생한다. 만성 정신질환자가 사레들릴 위험은 일반인의 8\~20배에 이른다.[@allen2012] 치명적일 수 있음에도 불구하고 과거에는 의사들이 별 관심을 기울이지 않았으나, 2005년 미국 FDA는 모든 항정신병 약물 설명서에, 치매 노인 환자에서 사용할 경우 흡인성 폐렴에 의한 사망 위험을 높인다는 경고 문구를 삽입하도록 지시하였다.[@cicala2019]

연하 곤란의 기전은 분명하지 않다. 음식을 삼키려 혀를 움직이는 것은 수의운동이지만, 그 후에 인두와 후두가 움직여 기도를 막지 않고 음식을 식도로 넘기는 것은 다수의 반사 작용이 조화를 이루어야 하는 불수의 운동이다. 파킨슨병 환자도 흔히 연하 곤란을 겪고, 도파민 차단이 후두 경련(laryngospasm)을 일으키는 것으로 보아, 도파민 수용체 차단 효과가 일조하는 것은 분명하다. 그러나 연하과정은 대부분 부교감 신경의 감독 하에 이루어지기 때문에 항콜린 효과가 더 문제가 되는 것 같다.[@visser2014] 항콜린 효과에 의한 <s>위장관 운동저하 (GIHM)</s>[^09-08-2]은, 식도와 인/후두에 걸친 평활근의 조화로운 이완을 방해하기 때문에 음식 흡수의 첫번째 관문에서부터 문제를 일으킨다. 더군다나 약물 복용 환자들은 치아의 문제 및 구강건조증을 함께 갖고 있는 경우가 많기 때문에, 음식을 제대로 씹지도 못하고 부드럽게 녹이지도 못한다. 역으로 클로자핀 복용 환자처럼 침이 너무 많이 흘러 음식을 제대로 삼키지 못하는 경우도 있다.

[^09-08-2]: **위장관 운동저하 (gastrointestinal hypomotility, GIHM)**: 위장관 벽을 이루고 있는 근육층의 수축력 약화 혹은 음식이 위장관을 통과하는 시간이 지연되는 상태로, 음식이 제대로 흡수되지 않거나 대변이 제대로 배설되지 않는 현상. 단순한 소화불량이나 가스팽만으로부터, 위마비(gastroparesis), 가성 장폐색(intestinal pseudo-obstruction)을 일으킬 수 있다.

연하 곤란은 전통적으로 추체외로 증상의 하나로 간주되어 왔다. 이는 연하 곤란이 다른 추체외로 증상 및 지연성 운동장애와 동반되어 나타나는 일이 많고, 도파민 차단의 영향이 중요해보이기 때문이다. 그러나 연하 곤란은 식도의 이완불능증(achalasia)과 함께 나타나기도 하며, 도파민 보다는 아세틸콜린의 비중이 더 큰 것으로 보아 위장관계 증상 즉 위장관 운동저하의 하나로 보는 것이 더 유용하다.[@crouse2017] 특히나 연하 곤란의 치료를 위해 항콜린 효과가 강한 항파킨슨제를 쓰면 상황을 더욱 악화시킨다는 점에서 더욱 그렇다.[@wolf2021]

연하 곤란은 쉽게 발견되는 증상이 아니다. 이유없이 식사량이 줄거나 투약을 거부하는 환자라면 혹시 만성 연하곤란을 겪고 있는 것 아닌지 확인해보아야 한다. 알약을 잘 삼키지 못한다고 하여 간호사가 약을 분쇄해서 주는 경우가 있는데, 이는 약동학의 변동때문에 또 다른 위험을 초래할 수 있다. 연하 곤란이 있는 환자는 식사를 자주 조금씩 섭취하게 하고, 부드러운 음식을 주며, 천천히 복용하도록 교육하는 것이 필요하다. 문제가 잘 해결이 안 되면, 항정신병 약물을 감량 및 분복 혹은 중단해야 하며, 항콜린 효과가 약한 약으로 교체를 고려한다.

## 위-식도 질환

한국인 환자의 대부분은 약물이 속을 버린다며, 식후 30분에 약 먹는 것을 고집한다. 환자들은 약물이 위점막을 자극하여 위염 및 궤양을 일으키기 때문에 음식과 같이 먹어야 하며, 혹시라도 위산이 약 흡수를 방해할까봐 30분 정도 간격을 두어야 한다고 생각한다. 그러나 항정신병 약물이 위점막을 자극한다거나 궤양을 일으키는 일은 극히 드물다. 그보다는 위장관계 전체에 걸쳐 평활근의 운동성을 낮추기 때문에, 흡수로부터 배설에 이르는 모든 단계에 걸쳐 다양한 위장 증상을 나타낼 수 있다. 이러한 위장관 운동저하( GIHM)는 빈도가 매우 높은데도 불구하고 인식이 부족하여 놓치게 되는 경우가 많다. 하지만 GIHM은 경한 변비 증상뿐 아니라 장폐색 및 허혈성 장질환과 같은 심각한 상태까지 일으키므로, 평소에 관심을 가져 문제가 심각해지기 전에 해결해야 한다.[@chen2018]

위-식도 역류(gastroesophageal reflux disease, GERD)는 환자들이 약 먹고 속이 쓰리다고 호소하는 중요한 이유 중 하나이다. 식도의 운동성이 떨어지고, 하부 식도 괄약근(low esophageal sphincter)이 이완되면서 위산이 식도 내로 역류하는 현상이 생긴다. 그러나 항정신병 약물과 GERD의 관계는 잘 연구되지 않았으며, 약물이 꼭 위험을 높이는 지도 확인되지 않았다.[@kasap2015] 다만 흡연을 하는 조현병 환자가 일반인에 비해 좀더 GERD로 고생하는 경우가 많다는 정도가 알려져 있다.

이에 비해 유독 클로자핀 복용 환자에서 GERD의 빈도가 높으며, 위산억제제 치료를 받는 환자 비율이 높다는 것이 주목받았다.[@vanveggel2013] 클로자핀이 주목받는 이유가 클로자핀의 독특한 약리 효과 때문인지, 단순히 연구가 많이 된 것 때문인지는 확실하지 않다. 그러나 다른 비정형 약물과 비교했을 때에도 역시, 클로자핀 투여 환자가 더 위산억제제 치료를 많이 받는다고 한다.[@taylor2010]

조현병 환자들이 속이 쓰리다고 하면 의사들은 별다른 고민없이 위산억제제를 처방하곤 한다. 그런데 위산억제제는 위 자체에서 항정신병 약물의 흡수를 방해할 수도 있고, 특히 양성자 펌프 억제제(proton pump inhibitor)는 CYP1A2를 유도하여 클로자핀의 농도를 낮출 수 있다는 것을 기억해야 한다.[@moustafa1987; @frick2003]

## 변비

### 임상 양상

+------------------------------------------------------------------------------+
| #### **Two or more of the following...**                                     |
+------------------------------------------------------------------------------+
| -   Straining more than 1/4 of defecations.                                  |
+------------------------------------------------------------------------------+
| -   Lumpy or hard stools more than 1/4 of defecations.                       |
+------------------------------------------------------------------------------+
| -   Sensation of incomplete evacuation more than 1/4 of defecation.          |
+------------------------------------------------------------------------------+
| -   Sensation of anorectal obstruction/blockage more than 1/4 of defecation. |
+------------------------------------------------------------------------------+
| -   Manual maneuvers to facilitate more than 1/4 of defections.              |
+------------------------------------------------------------------------------+
| -   Fewer than three spontaneous bowel movements per week.                   |
+------------------------------------------------------------------------------+

: Diagnostic criteria for functional constipation according to Rome IV criteria From [@aziz2020]

뭐니뭐니 해도 항정신병 약물의 가장 흔한 부작용은 변비일 것이다. 항정신병 약물 복용 환자 중 변비의 유병률은 대략 30\~60%에 이른다,[@dehert_constipation_2011; @de_hert_prevalence_2011] 불만을 토로하는 환자들도 많지만, 상당수의 환자들은 별 문제가 아니라고 생각하여 의사에게 알리지 않는다.[@koizumi2013] 정의상으로는 일주일에 변을 3회 미만으로 보면 변비라고 하지만, 횟수와 상관없이 변볼때 통증이 심하고, 딱딱하고 단절된 변이 나오며, 힘을 많이 주어야 겨우 변이 나오고, 시간이 오래 걸려도 변비라고 볼 수 있다.[^09-08-3] 변비는 단순히 불편한 것 뿐만 아니라, 치열/치질의 원인이 되며, 변이 장에 오래 머물기 때문에 비정상적 세균총이 자리잡을 수 있다. 심지어 클로자핀 복용 환자에서는 폐쇄성/마비성 장폐색, 허혈성 장질환, 장 천공으로 목숨을 잃을 수도 있다.

[^09-08-3]: 국제적으로 통용되는 변비의 진단 기준인 **로마 기준 IV**는 변비를 1) 기능성 변비, 2) 과민성 대장증후군, 3) 아편양 물질에 의한 변비, 4) 기능성 배변장애로 나눈다. 항정신병 약물에 의한 변비는 **기능성 변비**에 해당한다.

변비의 기전은 확실하게 알려져 있지 않다. 전체적인 GIHM때문에 변이 장 내에 오랜 시간 머물게 되고, 점점 더 수분을 뺏겨 딱딱한 대변이 만들어진다. 클로자핀 복용 환자의 장운동성을 살펴본 연구에서, 82%의 환자가 위와 장의 어느 한 곳 이상에서 운동성이 심하게 떨어지는 모습을 보였다.[@everypalmer2019] 또 다른 연구에서는 대변이 대장에 머무르는 시간을 조사하였는데, 비정형 항정신병 약제 사용 군이 23시간으로 정상인과 별 차이 없었던 것에 비해, 클로자핀 사용 군은 104.5시간으로 4\~5배 늘어나 있었다.[@everypalmer2016] 장 운동은 아세틸콜린 이외에도 세로토닌, 히스타민 신호전달이 관여하고 있다. 콜린성 신호는 평활근 및 <s>카할 간질세포(interstitial cells of Cajal)</s>[^09-08-4]를 자극하여 장운동(peristalsis)을 촉진하며, 무스카린 M~1~과 M~3~를 차단하면 장운동의 리듬이 혼란에 빠진다. 세로토닌 역시 5-HT~3~를 통해 장운동에 직접 관여하며, 히스타민 H~1~ 수용체 역시 마찬가지이다. 클로자핀은 이 모든 수용체를 차단하며, 그 대사물인 norclozapine은 δ-아편양 수용체 효현작용을 통해 대장 운동을 차단한다.[@xu2021] 이렇듯 클로자핀의 영향력이 크기 때문에 학자들은 **clozapine-induced gastrointestinal hypomotility (CIGH)**라는 용어를 쓰기도 한다.[@palmer2008]

[^09-08-4]: **카할 간질세포(interstitial cells of Cajal)**: 장벽을 이루는 평활근은 세가지 세포가 gap junction을 통해 융합되어 있는 형태로 존재하며 이를 **SIP syncytium**이라고 한다. 세가지 세포는 3) 평활근육 세포(smooth muscle cell), 2) 카할 간질세포, 3) PDGF (platelet-derived growth factor) 수용체 α (PDGFRα)이다. 카할 간질세포는 장벽 운동의 pacemaker 역할을 하며, 외부 신경전달물질이나 전기신호에 반응하여 리듬을 조절한다.

장 운동성에 항콜린 효과가 가장 큰 영향을 미치고, 항콜린 효과가 큰 클로자핀, 클로르프로마진 등이 유달리 변비가 심하지만, 나머지 약물이라고 해서 변비가 안 생기는 것은 아니다. 비정형 약물 중에서는 클로자핀 다음으로 퀘티아핀과 올란자핀이 변비를 자주 유발하며, 그에 비해 리스페리돈/팔리페리돈은 빈도가 상대적으로 낮다.[@dehert_constipation_2011] 어찌된 셈인지 항콜린 효과가 적은 할로페리돌 역시 변비를 일으킬 위험이 높다.

변비는 모든 항정신병 약물의 공통적인 부작용이지만, 변비가 치명적이었던 사례는 클로자핀 복용 환자에서 주로 보고되었다. 클로자핀에 의한 변비의 유병률은 31.2%로 다른 어떤 항정신병 약물과 비교해도 높으며, 변비 합병증으로 사망할 확률은 무과립구증보다도 높다.[@dehert_constipation_2011]

### 치료

변비 치료는 무조건 변비약을 쓰기 전에 환자에게 정상적 배변에 대한 정보, 아침 배변의 중요성, 적절한 섬유질과 수분 섭취의 필요성 등에 대해 교육해야 한다. 식이성 섬유로 통곡물, 프룬(말린 자두), 헴프씨드(hempseed) 등을 규칙적으로 복용하는 것이 도움이 된다. 소위 변비약(완하제, laxative)은 크게 부피형성 완하제, 삼투성 완하제, 자극성 완하제로 나누어진다. 변비 치료에서 가장 먼저 사용하는 것은 Mutacil®, Agio®, Sylcon® 등의 부피형성 완하제이다. 이들은 임산부에서도 사용가능할 정도로 안전하나, 위장관에 물리적 협착이 의심되면 사용해선 안 된다.

정신과에서 가장 많이 사용하는 수산화마그네슘(MgO, Magmil®)과 lactulose 시럽(Duphalac®)은 삼투성 완하제이다. 삼투성 완화제는 다시 염류성과 고삼투성으로 나뉘는데, MgO는 염류성이며, lactulose는 고삼투성 완하제에 속한다. MgO는 하루 1\~2g를 투여하며, 보통 하루 두번에 나누어 충분한 물과 함께 복용한다. MgO의 문제는 신기능 장애 환자에서 고마그네슘 혈증이 생길 수 있다는 것과, 조금씩 내성이 생긴다는 것이다. Lactulose는 매우 단 시럽이기 때문에 복용감이 좋지 않다. 그래서 변비가 심할 때만 아침 식전 공복 상태에서 15\~30 mL을 투여한다. 만약 매일 사용할 때는 10\~15 mL로 양을 줄여 투여한다. 유당이 많이 들어있기 때문에 당뇨 환자라면 사용하기 어렵다. 또다른 고삼투성 완하제인 macrogol (Forlax®)은 먹기가 훨씬 수월하고 혈당을 올리지 않아 lactulose를 대체할 수 있다.

환자들이 흔히 일반 약국을 통해 구입하여 사용하는 Dulcolax®, Alaxyl® 등은 각각 bisacodyl과 senna 성분이 주 원료인 자극성 완하제로, 대장의 근육신경총을 자극하여 장운동을 촉진하고 배변 신호를 일으킨다. 오래 사용한다고 해서 장 신경을 손상시킨다는 증거는 없지만, 남용 및 의존 위험이 높기 때문에 장기 사용은 권장되지 않는다. 정신과 의사 입장에서는 1) 교육, 2) 부피형성 완하제, 3) 삼투성 완하제, 4) 자극성 완하제 순으로 사용하고, 자극성 완하제는 꼭 필요할 때만 단기간 쓰는 것이 바람직하다. 이러한 원인으로도 해결이 되지 않는 만성 기능성 변비는 소화기 내과에 의뢰하게 되는데, 최근에는 linaclotide (Linzess®), prucalopride (Resolor ®), plecanatide (Trulance®) 등 신개념 약들이 등장하고 있다.

변비는 투약 초기뿐 아니라 오래 지속되는 만성적 문제이기 때문에 완하제만 사용한다고 해서 해결이 되지 않는다. 만일 부피형성/삼투성 완하제로 해결되지 않는 경우라면, 항정신병 약물의 감량이나 교체를 진지하게 고려해야 하며, 항파킨슨제를 사용하고 있다면 지속 여부를 재평가해야 한다.

### 합병증

만약 변비를 오래 앓던 환자가 갑작스레 복통, 발열을 호소하면, 장패색이나 허혈성 장질환을 배제하기 위해 영상학적 검사를 행해야 한다. 장폐색의 치명률은 30\~40%에 이르며, 허혈성 장질환은 이보다도 높아 40\~90%에 이르기 때문에 빠른 진단이 무엇보다 중요하다. 장폐색은 기계적 장폐색(mechanical ileus)과 마비성 장폐색(paralytic ileus)으로 나누는데, 조현병 환자에서는 탈장, 게실염, 암, 과거 장 수술 등의 병력이 없다면 거의 대부분 마비성 장폐색이다. 항정신병 약물 복용 환자 중 장폐색의 누적 발생률은 0.46% 이며, 고역가 정형 항정신병 약물, 삼환계 항우울제, 항콜린성 약물 및 아편양 제제 치료를 받은 환자들에서 흔하다.[@nielsen2012] 단순 복부 촬영으로 쉽게 진단할 수 있으며, 진단되면 일단 약물을 끊고 금식하며, 수액으로 영양 공급 및 전해질을 보충한다. 필요하다면 비위관(nasogastric tube)을 삽입해 위장의 압력을 낮춘다. 이러한 대증적 요법으로 대부분 회복된다. 문제는 진단을 놓쳐 장이 막힌 채로 오랜 시간이 지나면, 체액 및 전해질 손실, 허혈에 의한 장 점막의 손상으로 심한 후유증에 빠질 수 있다는 것이다.

항정신병 약물에 의한 허혈성 장질환은 원인이 분명하지 않다. 아마도 오랜 변비로 인해 장이 팽창되면서, 장벽 압력의 증가로 인한 혈관 수축이 원인인 것 같다.[@shah2013] 장의 혈액공급이 차단되면 빠르게 괴사가 시작되며, 환자는 구토와 발작성 통증, 혈변 및 변에서의 악취를 보이기 시작한다. 치료하지 않으며, 복막염이 패혈증으로 이어져 사망에 이르게 된다.[@shah2013]

## 간, 췌장의 기능 장애

### 간 기능 저하

약물에 의한 간 손상은 1) 특이 반응(idiosyncratic liver injury)에 의한 전격적인 간부전과, 2) 심하지 않지만 점진적인 간 기능 저하(intrinsic liver injury)로 나누어 생각할 수 있다.[@chalasani2010] 클로르프로마진은 특이 반응에 의한 전격적 간 손상을 일으킬 수 있는 대표적인 약물로, 2004년 영국에서 조사된 바에 의하면 상용 약물 중에서 가장 위험비가 큰 것으로 나타났으며, 그 발생률은 1,000명 당 1.3건 정도였다.[@deabajo2004] 이러한 현상은 투여 초기 4주 이내에 나타나며, 발열, 발진, 그리고 호산구 상승이 동반된다.[@selim1999]

하지만 특이 반응은 그 빈도가 극히 드물고, 보다 흔하게 접할 수 있는 것은 경미한 간수치의 상승이다. 그 기전은 알려져 있지 않으나, 1) 간세포 자체에 대한 독성, 2) 담즙 정체 그리고 3) 지방간 유발의 세 가지 기전을 생각해볼 수 있다.[@tellescorreia2017] 이러한 분류에 따라 약물에 의한 간 손상도 1) 간세포 독성 유형과 2) 담즙 정체 유형, 그리고 3) 혼합형으로 나눌 수 있다. 항정신병 약물은 이 세가지 유형 모두 일으킬 수 있다. 특히 phenothiazine 계 약물은 과민 반응때문인지 <s>소관막</s>[^09-08-5]을 손상시켜 담즙 정체를 일으킬 수 있으며, 이는 황달과 소양감을 일으킬 뿐만 아니라 간세포 자체를 망가뜨릴 수 있다.[@regal1987] 이렇게 간에서 만들어진 일차 대사물이 담즙이나 소변으로 제대로 배출되지 못하면 그 자체가 독성을 띨 수 있다. 대사물이 축적될 때까지는 시간이 좀 걸리기 때문에 약물 투여 후 상당한 시일이 지나서야 그 영향이 나타날 수 있다.[@marwick2012]

[^09-08-5]: **소관막 (canalicular membrane)**: 간세포에서 내보내지는 물질은, ATP를 쓰는 적극적 수송에 의해 소관막을 가로질러 모세담관으로 배설된다. 이 기능이 부진하면 담즙 배출이 원할하지 못하게 된다.

항정신병 약물 특히 클로자핀을 사용한 조현병 환자의 최대 78%에서 어느 한 가지 이상의 간수치 상승을 보인다.[@gaertner2001] 이는 투여 초기에 일시적으로 나타나는 경우와 만성으로 지속되는 경우가 있다. 투여 초기 6주 내에는 간에만 부담이 가해지기 때문에 <s>ALT (GPT)</s>[^09-08-6]만 상승하지만, 이 상태가 이어지면 손상의 부담이 주변 조직으로 전파되어 <s>AST (GPT)</s>[^09-08-7]가 상승하기 시작한다. 더 오래되면 담즙 정체가 뒤따라 <s>ALP</s>[^09-08-8]와 빌리루빈 수치가 덩달아 상승할 수 있다.

[^09-08-6]: **Alanine aminotransferase (ALT)**: L-alanine의 amino-group을 α-ketoglutarate로 옮겨주는 역할을 하며, 이 결과로 glutamate가 생성된다. 간에서만 존재하기 때문에, 혈액에서 검출되는 ALT 수치는 간세포가 파괴되었음을 의미한다. 40 IU/L를 정상 상한선으로 본다. 과거에는 serum glutamic-pyruvic transaminase (sGPT)로 불렸다.

[^09-08-7]: **Aspartate aminotransferase (AST)**: L-aspartate의 amino-group을 α-ketoglutarate로 옮겨주는 역할을 하며, 이 결과로 glutamate가 생성된다. ALT와는 달리 간뿐만 아니라, 심장, 근육, 신장, 뇌에도 존재하기 때문에 ALT보다는 비특이적인 간기능 지표이다. 간세포의 손상이 시작되면 AST보다 ALT가 먼저 상승하기 때문에 AST/ALT비는 낮은 편이다. 그러나 손상이 주변 장기로 확대되어 염증이 퍼져나가면 AST도 상승하기 때문에 AST/ALT 비가 역전된다. 과거에는 serum glutamic oxaloacetic transaminase (sGOT)로 불렸다.

[^09-08-8]: **Alkaline phosphatase (ALP)**: 주로 간, 담관, 신장, 뼈, 태반에 분포한다. 생리적 기능은 확실하지 않으나, 혈중 ALP 수치는 간염, 담관폐쇄, 담낭염, 간경화 등에서 상승하며, 빌리루빈 수치와 함께 움직일 때가 많다.

경미한 간 수치 상승은 흔히 무증상이며, 환자의 건강에 크게 영향을 미치지는 않는다. 그러나 대사증후군과 체중 증가에 의해 비알코올성 지방간이 발생하는 경우에는, 처음에는 증상이 없다 하더라도 간 병변으로 진행할 수 있기 때문에, 주기적인 간 기능 검사가 필요하다. 보통 항정신병 약물을 투여하기 전 기준치를 점검한 후 1년 마다 정기적으로 평가하며, 클로자핀을 사용하는 경우에는 6개월마다 한번씩 평가하기를 권한다. 만약 알코올을 자주 복용하는 환자라면 더욱 자주 해야함은 물론이다. 혈액검사할 때가 이르지 않았더라도 황달, 가려움증, 메스꺼움 등 간 손상의 징후가 있다면 즉시 혈액검사를 해보아야 한다.

하지만 AST, ALT가 어느 정도를 넘어가면 약물을 중단해야 하는 지에 대한 기준은 세워져 있지 않다. 경미한 간수치 상승은 약물을 중단할 이유가 되지 않는다. 연구자들은 AST 혹은 ALT가 정상 상한선(upper limit of normal, ULN)의 3배 이상으로 높아졌을 때를 심각한 간 손상으로 정의하기 때문에, 이 정도가 되면 항정신병 약물을 중단하는 것이 권고된다.[@tellescorreia2017] 약을 끊으면 간수치의 정상화를 기대할 수 있지만, 지방간으로 인해 점진적으로 상승한 경우에는 약물을 중단한다고 금방 정상화되라라는 보장이 없다. 약물 중단의 결정은 AST, ALT의 절대치 뿐 아니라 AST/ALT의 비율도 고려한다. 이 비율이 2:1 이상이면 지방간이나 간경화로 확대되었을 가능성을 고려해야 한다. 또한 ALP나 빌리루빈 수치가 동반되어 올라갔는지 여부도 고려해서 최종 판단을 내려야 한다. 또한 항정신병 약물 뿐 아니라, 조현병 환자 치료에 흔히 병용되는 항우울제, 기분조절제 등의 약물이 모두 간세포 손상과 담즙 정체를 일으킬 수 있음을 명심해야 한다.

### 췌장염

급성 췌장염은 췌장 효소 상승과 함께 복통이 나타나며, 급성 췌장염이 반복되면 만성 췌장염으로 진행한다. 항정신병 약물에 의한 췌장염은 극히 드물지만, 그래도 클로자핀, 올란자핀, 리스페리돈의 순서로 경미하게나마 위험률을 올리는 것으로 나타났다.[@koller2003; @kawabe2014; @silva2016] 위험 인자로는 젊은 연령, 알코올 사용, 당뇨, 과거 담석 유무, 다약제 사용 등이었다.[@silva2016]

췌장염이 발생하면 구역/구토, 복통이 시작되며, 진행하면 발열과 함께 혈압이 떨어진다. 췌장에서 분비되는 효소인 amylase와 lipase가 정상 상한선의 3배 이상 증가되면 췌장염을 의심할 수 있다. 하지만 amylase, lipase는 매우 비특이적인 효소라 췌장염이 아닌 다른 원인에 의해서도 상승할 수 있으며, 만약 췌장염이라 하더라도 상승 정도가 심각도를 반영하지 않는다.[@ismail2017] 예를 들어 발프로에이트를 복용하는 경련성 질환 환자는 췌장염의 증거가 없이도 혈중 amylase가 일시적으로 상승한다.[@voudris2006] Amylase와 lipase를 비교한다면, lipase가 좀더 췌장에 특이하며 더 오래 상승된 상태를 유지하기 때문에 췌장염 진단에 더 유리하다.[@ismail2017]

대부분 항정신병 약물 투여 개시 후 2개월 내에 발생하며, 약물을 중단하면 자연히 호전되었다. 발프로에이트와 마찬가지로, 클로자핀 복용 환자들이 아무런 증상없이 amylase, lipase가 상승하는 경우가 있다.[@bergemann1999] 이 때문에 조심성많은 연구자들은 클로자핀 사용 중 이들 효소를 정기적으로 모니터링해야한다고 주장하지만, 수치가 상승한다고 해도 증상이 없으면 약물을 중단할 이유는 되지 않는다. 그보다는 비교적 젊은 환자가 약물 증량 중에 갑작스러운 복통, 구역/구토 등의 증상을 보일 때, 췌장염 가능성을 염두에 두고 간기능 검사와 함께 amylase, lipase를 확인하는 것이 더 현실적이다. 복부 초음파나 CT로 직접 췌장염을 증거를 찾을 수도 있다. 췌장염이 의심된다면 사용하던 약물은 중단하는 것이 좋으며, 다시 사용하는 것은 권해지지 않는다.

## References {.unnumbered}
