---
title: "약물 치료 실제 과정"
author: "정성훈"
bibliography: References/10-02.bib
---

## 치료 약물의 선택

약물을 선택하는 일반적인 원칙에 대해서는 8장(8-3-7)에서 논한 바와 같다. 그러나 좀더 여유가 있는 환자에게 약물을 선택할 때와, 지금 당장 심한 양성 증상을 보이는 환자에게 약물을 선택할 때는 사정이 다를 것이다. 일반적인 약물 선택에서는 예상되는 부작용과 환자의 선호도가 우선적으로 고려되겠지만, 지금 현재 공격적이거나 행동 조절이 이루어지지 않는다면, 부작용은 무시하고라도 진정 작용이 강하거나 양성 증상에 효과적인 약물을 선택하여 환자와 주변의 안전을 도모할 것이다.

### 행동 조절이 안 되는 환자

흥분 상태에 있고 공격적인 환자를 치료하기 위해서는, 효과가 신속하면서도 믿을만해야 한다. 만약 강제로 주사를 놓았는데 약효가 빨리 나타나지 않거나, 효과가 불충분하면 오히려 환자를 더 자극하는 꼴이 될 것이다. 따라서 약효가 빠르고, 진정 효과가 강하며, 과량 투여 시에도 안전한 약물이 필요하다. 이러한 여건을 만족하는 약물로 전통적으로는 할로페리돌 주사제가 가장 널리 사용되어 왔다.

이상적인 치료효과는 환자를 수면에 빠지지 않게 하면서 흥분을 가라앉히는 것이다. 응급실에서 행동 조절이 안 되는 환자를 맞닥뜨렸을 때 무조건 재우면, 더 이상 환자 상태를 평가하기 힘들 것이다. 만약 이 환자가 중추신경계의 기질적 문제를 안고 있는 환자였다면 큰 문제가 아닐 수 없다. 따라서 일차적 목표는 일단 흥분을 가라앉혀서 의학적 평가가 가능하게 만드는 것이다.[@schleifer2011] 또한 이런 상황에서 진정은, 환자가 스스로 상황을 통제할 수 있도록 돕는 것이 되어야지, 강압적으로 상황을 제압하는 것이 되어서는 안된다.

그러나 현재 사용되는 약물로는 이런 이상을 실현하기에 역부족이다. 전통적으로 사용되오던 할로페리돌, droperidol, midazolam 등의 주사제는 환자를 일단 재워버리기 때문이다. 그러던 중 2002년에 지프라시돈의 주사제가 미국 FDA의 허가를 받으면서 상황이 조금씩 달라졌다. 2년 후에는 올란자핀 주사제가 허가를 받았다. 두가지 비정형 약물 주사제도 진정 효과가 없는 것은 아니지만 기존 약물보다는 약하였고, 그러면서도 충분한 진정 효과를 발휘하였다. 또한 갑작스레 나타나는 추체외로 증상도 거의 없다.[@cañas2007]

#### 경구 약물에 의한 진정

신속한 효과를 꾀하려면 주사제를 써야하지만, 주사제는 강압적인 느낌이 강하기 때문에, 먼저 경구 복용을 권해볼 수 있다. 경구제는 환자 스스로 상황을 통제할 수 있을 것이라는 의료진의 신뢰를 전달하기 때문에, 의사-환자 관계에 긍정적 영향을 미친다. 경증인 경우 리스페리돈 1\~2mg, 올란자핀 5\~10mg 정도를 30분에서 한시간 간격을 두고 반복하여 투여한다. 문헌에는 24시간 동안 올란자핀을 40mg까지 투여했어도 별 탈이 없었다는 사례가 있다.[@baker2003] 흔히 벤조디아제핀을 함께 투여하는데, 이는 효과를 보충할 뿐더러 만에 하나 있을 지 모르는 급성 근긴장이나 좌불안석을 예방하기 위함이다. 주로 사용되는 것은 로라제팜 1\~2mg, 혹은 디아제팜 5\~10mg이다.

똑같이 경구 복용이라고 해도 정제보다는 액상 형태가 협조를 구하기 어려운 환자에게 사용하기 쉽다. 다행히 리스페리돈, 올란자핀, 아리피프라졸 모두 구강붕해제형이 시판되고 있으며, 리스페리돈(oral suspension)과 아리피프라졸(oral solution)은 액상 제형도 있다. 이들은 복용이 간편하고 흡수가 좀더 빠르기 때문에 급박한 상황에서 요긴하게 사용된다. 이외에도 asenapine의 설하 제제나 loxapine의 흡입 제제가 응급 상황에서 사용될 수 있다.[@lesem2011; @pratts2014] 그러나 이러한 방법들은 환자의 적극적인 협조가 필요하기 때문에, 공격적 환자보다는 스스로 고통스러워하는 환자에게 쓰인다.

#### 주사제에 의한 진정

좀더 폭력적이고 심한 행동 문제를 보이는 환자에게는 주사제를 이용한 <s>급속 진정</s>[^-1]을 시도한다.[@desouza2022] 주로 근육주사제가 사용되며, 드물게 정맥주사도 시도된다. 주사제는 협조가 이루어지지 않는 환자에게도 사용할 수 있으며, 신속하게 유효 혈중 농도에 도달할 수 있다. 안전요원 및 치료진이 환자를 둘러싼 상황에서 주사제를 권유하면, 상당히 강압적, 징벌적으로 받아들여지므로, 주사제는 환자를 편안하게 해주기 위해 투여된다는 것을 강조할 필요가 있다.

[^-1]: 급속 진정(rapid tranquilization)은 급속 신경이완화(rapid neuroleptization)과 다른 개념이다. 전자는 흥분한 환자를 일단 진정시키는 과정이지만, 후자는 조현병 치료를 위해 고용량의 항정신병 약물을 근주 혹은 정주로 짧은 시간 안에 투여하는 것이다.[@donlon1979]

급속 진정은 임상에서 흔히 사용되지만, 정작 임상적 근거는 쌓여있지 않다. 이런 상태의 환자들이 임상 연구에 동의할리가 없어 임상 연구 자체가 드물기 때문이다. 부족하나마 있는 자료들을 끌어모은 메타 연구가 있어 이를 소개한다.[@bak2019] 가장 활발한 연구가 이루어진 것은 올란자핀 근육주사였으나, 가장 효과가 확실하다고 집계된 것은 <s>할로페리돌+promethazine 주사제</s>[^-2]였다. 이외에도 올란자핀 및 아리피프라졸 주사제, 할로페리돌+로라제팜 주사제, 그리고 리스페리돈 구강 현탁액이 효과적이었으며, 이에 비해 지프라시돈, 할로페리돌, 로라제팜 각각의 단독 주사는 효과가 상대적으로 떨어졌다. 그러나 워낙 연구의 수가 작고, 대상자 수도 작아 치료 전략간의 우열을 가리기는 힘들다. 한국에는 아예 promethazine, 아리피프라졸, 지프라시돈의 주사제가 도입되지 않았으며, 그나마 올란자핀 주사제가 몇 년간 사용되다가 2016년에는 그마저 허가가 취소되었다. 더불어 위 논문의 저자들이 액상 리스페리돈의 효과가 과대평가되었을 가능성을 지적하고 있기 때문에, 남는 선택은 할로페리돌+로라제팜 주사제 밖에 없다. 실제로 우리나라 현실에서 공격적 환자에게 가장 많이 쓰이지만, 가장 부작용 발생이 흔한 선택이기도 하다.

[^-2]: **Promethazine:** phenothiazine 계열 항정신병 약물로, 강한 항히스타민, 항콜린 효과를 보이는 반면, 항도파민 효과는 약해서 할로페리돌 주사제에 의한 추체외로 증상 발생을 막아준다고 믿어진다.

할로페리돌과 로라제팜을 각각 주사했을 때보다 함께 투여했을 때 분명한 상승효과가 있으며, 평균 44분이면 진정 상태에 도달한다.[@foster1997; @currier2001] 문헌에는 이 밖에도 할로페리돌과 midazolam을 섞어 주사하면 10분내에 진정 상태를 유도할 수 있다고 보고되었다.[@calver2013] Midazolam은 단독으로, 혹은 할로페리돌과 함께 사용하며, 보통 7.5\~15mg을 근주 또는 정주로 투여한다. 최근에 급속 진정에 대한 연구로는 가장 규모가 큰 무작위 배정 이중맹검 연구결과가 발표되었다.[@chan2021] 흥분 상태에 있는 167명의 환자에게 무작위로 midazolam, 올란자핀, 할로페리돌 주사제를 투여하였다. 효과와 부작용 발생 빈도는 세 군 간에 거의 비슷하였으나, 진정 상태에 도달한 시간은 각각 8.5, 11.5, 23.0분으로 유의한 차이가 있었다. 아쉽게도 이 연구에는 할로페리돌+로라제팜 병용 주사는 포함되지 않았다.

할로페리돌+로라제팜을 주사할 때 가장 많이 사용되는 용량은 <s>5+2mg</s>[^-3]이다. 가장 널리 쓰이긴 하지만, 주사 12\~24시간 내에 후두 경련, 안구운동발작(oculogyric crisis), 사경(torticollis)을 포함한 근긴장 이상이 생길 수 있으며, 급성 좌불안석도 흔한 편이다. 이런 부작용은 환자에게 매우 공포스럽게 느껴지며, 향후 약물 순응도나 유지 치료에 심각한 영향을 줄 수 있다. 로라제팜을 함께 투여하는 이유는 진정 효과를 높이는 것 뿐 아니라, 이러한 근긴장 이상을 미리 예방하기 위해서이기도 하다.[@salzman1986] 그러나 과연 목적한만큼 부작용을 예방할 수 있는 지에 대해선 논란이 많다. [@battaglia1997] 비정형 약물의 주사제(올란자핀, 아리프피라졸, 지프라시돈)가 개발된 이후에는 할로페리돌 주사제를 단독으로 쓰는 게 과연 윤리적인지 의문이 제기되었다.[@citrome2013]

[^-3]: 외국에서는 이 조합을 **B-52**라고 부르며, 항파킨슨제인 diphenhydramine 50mg을 추가하여 **5250**이라 부르기도 한다

할로페리돌+로라제팜 조합보다는 올란자핀을 비롯한 비정형 약물 주사제를 사용하는 것이 훨씬 추체외로 증상이 적다. [@satterthwaite2008] 올란자핀, 지프라시돈 모두 일회 10mg 씩 근육 주사하며, 2시간 간격으로 반복할 수 있다. 그러나 일일 최대 용량이 40mg를 넘지 않게 한다.[@meyermassetti2010] 지프라시돈은 QTc 연장 사례가 있으므로, 심혈관 질환의 위험이 높은 환자에게는 추천되지 않는다. 올란자핀을 벤조디아제핀과 함께 주사하면 진정 작용이 지나치게 강해질 위험이 있어서, 이 두 약제를 두시간 이내에 함께 투여하는 것은 피해야 한다.[@marder2010]

만약 정맥주사 경로가 이미 확보되어 있다면, 환자를 자극하지 않고 손쉽게 투여할 수 있다. 그러나 정맥주사는 QTc 연장이나 Torsades de Pointes (9-11-3절)의 위험을 높이기 때문에 그다지 권장되지 않는다.[@meyermassetti2010] 올란자핀 주사제도 정맥으로 투여하는 경우가 있지만, 이는 허가되지 않았다.[@khorassani2019]

근육 주사이든 정맥 주사이든 주사를 투여하고 첫 한시간 동안은 10분 간격으로 생체 징후를 측정하며, 이후에는 깨어서 돌아다닐 때까지 30분에서 1시간 간격으로 생체 징후를 측정한다. 주사제 투여 후 호흡 부전, 서맥, 저혈압, 급성 근긴장 등이 드물게 발생할 수 있다. 특히 midazolam을 비롯한 벤조디아제핀을 주사제로 투여했다면 호흡 부전을 신경써야 한다. 호흡 부전이 오면 산소를 공급하며 수동식 인공호흡(ambu-bagging)을 하며, 저혈압인 경우 수액 투여, 급성 근긴장이 오면 로라제팜이나 벤즈트로핀을 경구 혹은 근육 주사한다.

### 초발 환자에서의 약물 선택

일단 급박한 위험이 조절되고 난 이후에는 부차적인 요인들을 검토하여 주된 치료 약물을 선택한다. 공격적 행동을 조절하기 위해 사용했던 주사제 성분을 경구로 바꿔 그대로 가져가는 경우도 있지만, 상황에 맞추어 치료 약물을 바꾸는 경우가 많다. 초발 환자의 경구 약물 치료는 1) 가급적 단일 약제를 2) 최대한 낮은 용량으로 사용한다는 원칙 하에서 이루어진다.[@keating2017] 환자들은 낮은 용량에서도 잘 반응하지만, 동시에 부작용도 쉽게 나타난다.

특히 초발 환자는 단일 약물로 충분한 효과를 나타낼 가능성이 높기 때문에, 약물 선택이 매우 큰 의미를 지닌다. 생애 첫번째 약물에 대한 경험이, 이후 평생동안 항정신병 약물에 대한 인식을 바꿔놓을 수 있기 때문에, 의사는 큰 부담을 느끼지 않을 수 없다. 대부분의 치료지침서는 초발 환자에게 약물을 선택할 때 부작용을 중시하는 경향이 있으며, 추체외로 증상의 위험을 줄이기 위해 비정형 약물을 권유한다.

유럽에서 진행된 <s>EUFEST</s>[^-4] 연구에서는 비정형 약물로서 아미설프라이드 200\~800mg/day, 올란자핀 5\~20mg/day, 퀘티아핀 200\~750mg/day, 지프라시돈 40\~160mg/day를 사용했으면 정형 약물로서는 할로페리돌 1\~4mg/day을 1년간 사용하면서 추적 조사하였다. 1년이 지난 후 관해 상태에 도달한 환자의 비율은 할로페리돌 사용 군이 17%에 지나지 않았던데 비하여, 아미설프라이드 군은 40%, 올란자핀 군은 41%, 퀘티아핀 군은 24%, 지프라시돈 군은 28%로 모두 할로페리돌 군보다 관해율이 높았다. 비록 리스페리돈, 아리피프라졸이 빠져있다는 문제점이 있지만, 전체적으로 비정형 약물이 초발 환자에게 의미있는 성과를 얻어낼 수 있다는 것을 입증해주었다.[@boter2009]

[^-4]: The European First Episode Schizophrenia Trial (EUFEST)

한편 미국 국립보건원이 후원한 <s>RAISE</s>[^-5] 연구에서는 아리피프라졸, 퀘티아핀, 리스페리돈, 지프라시돈이 일차 선택제로 추천되었으며, 올란자핀은 이차 선택제로 밀려났다.[@rosenheck2016] 환자들이 청소년기 후반, 초기 청년기에 걸쳐 있기 때문에, 체중이 증가하거나 대사증후군이 발생하여 신체상(body image)이 변화하면 큰 심리적 문제를 일으킬 수 있다. 더불어 성적으로 가장 활발한 나이에 무월경을 비롯한 성적 부작용이 발생하면 역시 심리성적(psycho-sexual) 발달을 저해한다. 올란자핀이 이차 선택제로 밀려난 것은 이러난 이유 때문인 듯 싶다.

[^-5]: Recovery After an Initial Schizophrenia Episode (RAISE)

그러나 실제 연구 결과를 보면 조금 다른 그림이 그려진다. 초발 정신증 환자 376명을 전향적으로 <s>3년간 추적 조사한 연구</s>[^-6]에서 가장 중도탈락률이 낮았던 약물은 오히려 올란자핀(69.09%)이었으며, 가장 높았던 약물은 퀘티아핀(95.53%)이었다.(31974576) 퀘티아핀 치료가 꾸준히 이어지지 못한 이유는 주로 효과 부족때문이었으며, 반면 리스페리돈/지프라시돈은 부작용때문인 경우가 많았다. 이 결과를 보면 환자들이, 추후에 발생하는 대사 부작용보다는 단기간에 발현되는 추체외로 증상, 성적 부작용에 더 신경을 쓴다는 것을 엿볼 수 있다. 그래서인지 환자들은 당장 편안함을 주고 단기 부작용이 적은 올란자핀에 만족했던 것으로 보인다. 아리피프라졸은 부작용으로 인한 탈락률은 매우 낮았지만, 단순 비순응때문에 전체적 중도탈락률(73.08%)이 여전히 높은 편이었다.

[^-6]: Programa de Atención a las Fases Iniciales de Psicosis (PAFIP)

### 재발 환자에서의 약물 선택

재발 환자에게는 무엇보다 과거에 반응이 좋았던 약물을 선택하는 것이 원칙이다. 환자 개개인에게 어떤 약물이 이상적인지를 정확히 예측하게 해주는 표지자가 없기 때문에, 현재로서는 과거 경험에 의지할 수 밖에 없다. 덧붙여 이전에 좋은 경험을 했던 약물을 선택하는 것은 환자의 신뢰도와 만족감을 얻는데 도움이 된다. 또한 과거에 내약성이 확인된 약이라면 적정 과정을 좀더 앞당길 수 있다.

그러나 초발 상황과 재발 상황이 같을 수는 없다. 초발 삽화때는 대부분의 약물에 비교적 반응이 좋기 때문에, 다양한 약을 써볼 기회가 없다. 따라서 어떤 약이 환자에게 최선의 선택인지를 알 수 없다. 더군다나 재발이 반복될 수록 이전 삽화보다 반응성이 떨어지고 더 오래 기다려야 한다. 또한 환자는 더욱 현저한 기능 상실을 겪게 되고, 환자를 둘러싼 사회적/직업적 상황도 달라진다. 이런 식으로 상황이 변하면 필요한 약물이 달라질 수 있다. 또한 약물 반응이 만족스럽지 못하여 용량이 올라가면, 이전에는 문제가 되지 않았던 부작용이 새삼스레 문제가 될 수 있다. 재발 상황에서는 증상의 특성도 달라질 수 있다. 초발 삽화에서는 순수한 양성 증상만 나타났었는데, 질병의 병기가 진행되면서 기분 증상, 불안증, 강박증, 인지장애 등이 고통을 가중시킬 수 있다.

만약 재발 후 좀 더 긴 유지 치료가 필요해지고, 동시에 환자의 경제적 상황이 어려워졌다면 약물의 경제적 부담도 문제가 될 수 있다. 값비싼 비정형 약물을 몇 가지씩 함께 쓴다던지, 장기지속형 주사제를 쓰게 되면 금방 경제적 부담을 감당하기 어렵게 된다. 환자의 재정 형편을 살피고, 보험 혜택을 받을 수 있는 범위를 확인하거나, 사회보장 제도를 최대한 이용하도록 돕는 것도 치료의 일환이다.[@ganguly2018]

### 유지 치료에서의 약물 선택

의사에게 유지 치료는 훨씬 부담이 적다. 일단 급성기를 무사히 넘겼을 뿐더러, 환자가 유지 치료에 응한다는 것은 어느 정도 의사-환자 관계가 확고해졌고, 부분적인 병식도 생겼다는 것을 뜻하기 때문이다. 그러나 급성기 치료 이후 몇 달 정도는 멋모르고 치료에 잘 따라오다가도, 기간이 길어지면서 서서히 투약 순응도가 떨어지고 결국 중도 탈락하는 경우가 태반이다. 이 시기에는 어떻게든 환자를 잘 이끌어 유지 치료를 오래 이어가고, 재발의 위기를 잘 넘기는 것이 의사의 사명이 된다.[@ceraso2020]

원칙적으로 유지 치료에서는, 급성기 치료에서 효과적이었다고 판단된 약물을 그대로 사용한다.[@correll2022] 많은 저자들은 심지어 용량도 줄이면 안된다고 경고한다. 하지만 현실적으로 이를 지키기는 쉽지 않다. 급성기에는 제한된 시간 안에 증상을 어떻게든 가라앉혀야 한다는 일념 하에 용량을 높게 쓰거나, 다양한 병용 약물을 사용하는 것이 보통이다. 또한 입원 상황이기 때문에 복잡한 처방이나, 하루에 여러번 분복시키는 것도 다반사이다.

환자가 퇴원하게 되면 이런 상황을 지속하기 힘들며, 용량을 새로 조절하고, 약물의 가짓수를 줄이며, 처방을 단순화시켜야 한다.[@americanpsychiatricassociation2020] 용량을 조절하는 이유는 증상이 심하지 않기 때문일 수도 있지만, 부작용에 대한 민감도가 달라지기 때문이기도 하다. 급성기에 흥분 상태에 있던 환자는 약물로 인한 진정 부작용을 별로 호소하지 않지만, 유지 치료기에 접어들면 졸림 때문에 일상 생활이 힘들다고 호소한다. 물론 이러한 호소에 대해 졸릴 수 있는 병용 약물을 먼저 끊어나가지만 결국 주된 치료약물의 용량을 낮춰야 할 수 있다. 이 밖에도 급성기에는 중요하게 생각하지 않던 무월경이나 체중 증가에 대해 많은 비난이 의사를 향해 쏟아지기도 한다.

이러한 문제가 용량을 조절하거나 병용 약물을 끊어서 해결되지 않는다면 약물을 바꿔야 할 수도 있다. 또한 임상 양상의 변화에 따라 약물 교체의 필요성이 부상할 수 있다. 유지 치료 시기에 점점 더 문제가 되는 무월경, 대사 증후군, 성적 부작용을 해결하기 위해서는 아리피프라졸을 비롯한 3세대 약물이 유리하다. 또한 음성/인지 증상 해결을 위해 다른 약물을 고려해볼 수도 있다. 또한 점점 더 떨어지는 순응도 문제를 해결하기 위해, 장기지속형 주사제가 강력한 대안으로 고려되는 것도 이 시기이다.

유지 치료의 기간에 대해선 논란이 많으며, 많은 가이드라인은 아예 언급을 회피한다. 이미 앞에서 언급했듯이, 원칙적으로는 평생 약물을 유지해야 재발을 막을 수 있다. 그러나 재발 가능성과 약물 투여의 폐해를 저울질 했을 때, 초발 환자라면 1\~2년, 재발 환자라면 적어도 5년 이상 유지치료를 하는 것이 필요하다.[@remington2017]

### 특수 환자에서의 약물 선택

고령 환자 혹은 소아-청소년 환자에게는 특별히 주의를 기울여야 할 필요가 있다. 나이가 듦에 따라 약동학적/약력학적 변화가 찾아오기 때문에, 고령 환자는 부작용에 더 민감하며, 또한 녹내장, 전립선 질환, 심장 질환 등 특정 약물을 써서는 안 되는 금기들이 더 자주 발견된다. 더군다나 이미 많은 종류의 내, 외과적 약물을 사용하고 있을 가능성이 높기 때문에 약물 상호작용의 위험도 배가된다. 고령 환자는 젊은 환자처럼 직업적, 사회적 기능 회복을 크게 기대하지 않기 때문에, 좀더 안정적이고 보수적으로 약물을 사용하여 효과보다는 안정성에 치중한다.

마찬가지로 소아-청소년 환자 역시 보다 전문적인 지식이 요구된다. 한참 대인관계를 연습하고, 정체성을 구축하며, 성적 능력을 시험하는 나이이다. 또한 각각의 약물은 사용할 수 있는 환자 연령에 제한이 있다. 조현병의 경우는 대체로 13세 이상의 환자에게만 사용할 수 있는데, 그나마 비정형 약물 중 18세 미만에서 사용이 허용된 약물은 아리피프라졸, 올란자핀, 퀘티아핀, 리스페리돈뿐이다.

## 치료 중 병행하는 의학적 평가

치료 중 발생할 수 있는 부작용은 추체외로 증상에 국한되지 않는다. 약물은 광범위한 장기에 영향을 미치며, 극히 드물지만 치명적인 부작용을 일으킬 수도 있다. 게다가 조현병 환자는 자신의 건강 상태에 충분히 주의를 기울이지 않으며, 생활 습관이 불건전하고, 신체 증상이 있어도 의학적 도움을 구하려 하지 않기 때문에, 이미 신체 상태가 별로 좋지 않을 가능성이 높다. 급성기 환자들은 신체 상태의 변화를 제대로 감지하기 어려우며, 의료진에게 도움을 청하기 힘들어 할 수 있다.

### 심혈관 활력 징후

항정신병 약물은 직, 간접적으로 자율신경계에 영향을 미친다. 직접적 영향으로는 무스카린 수용체 차단 효과, α~1~ 아드레날린 수용체 차단 효과, 그리고 나트륨, 칼륨, 칼슘 체널에의 효과를 들 수 있다. 무스카린 차단은 빈맥을 일으키는데, 특히 저역가 약물과 클로자핀이 문제가 된다. 무스카린 수용체 뿐 아니라 α~1~ 수용체에 대한 영향도 빈맥을 악화시킨다.[@iwamoto2012] α~1~ 수용체가 차단되면 말초 혈관이 확장되어 반응성으로 빈맥이 심해지기 때문이다. 마찬가지 기전으로 α~1~ 차단은 기립성 저혈압을 일으킨다. 물론 빈맥과 저혈압이 심각한 문제를 일으키는 경우는 드물며, 기껏해야 현기증 등 불쾌한 감각을 일으키는 정도이다. 그러나 오랫동안 빈맥이 지속되면 심장의 산소요구량을 늘리며 부담을 준다.

의사들이 그보다 더 신경을 쓰는 것은 QTc 연장이다. QTc가 남성에서 450msec 이상, 여성에서는 480msec 이상이면 돌연사의 위험이 높아진다.[@aronow2018] 정형 약물 중에서 치오리다진, 드로페리돌, 피모자이드, 비정형 약물 중에서는 서틴돌, 지프라시돈, 퀘티아핀이 요주의 대상이다. 특히 항정신병 약물을 사용 중인 노인 환자는 대조군에 비해 심혈관계 문제로 사망할 위험이 1.6배 높다.[@schneider2005] 물론 이는 주로 섬망/치매 환자에게서 얻어진 수치이지만, 노인 조현병 환자도 여전히 주의를 기울여야 할 것이다.

### 체온 변화

체온 조절은 시상 하부에 위치한 온도 감지 뉴런과 조절 중추에 의해 이루어는데, 다수의 신경전달물질이 관여하기 때문에 항정신병 약물 복용 후 체온 조절의 혼란이 예상된다.[@shiloh2009] 주위 온도에 따라 저체온증 및 고체온증이 나타날 수 있으며, <s>열사병</s>[^-7] 이 쉽게 생길 수 있다. 고용량의 항정신병 약물을 복용하고 있는 조현병 환자가 한여름에 경련발작을 일으키는 경우, 진짜 경련과 <s>열경련(heat cramp)</s>[^-8]을 구분할 필요가 있다.

[^-7]: **일사병(sunstroke)**은 정상적 체온조절 과정에서 땀을 과도하게 흘려 생기는 탈수와 열분 소실을 의미한다. 반면 **열사병(heat stroke)**은 체온조절 기능이 제대로 이루어지지 않아 체온이 과도하게 오르는 것으로, 의식저하, 경련, 운동실조증 등 신경학적 증상이 동반된다.

[^-8]: 열경련(heat cramps): 고온에서 심한 운동을 했을 때 나타나는 불수의적인 근육 수축으로, 근육이 경직되고 긴장되어 통증이 생긴다. 이는 소아의 열성경련(febrile seizure)과는 전혀 상관없다.

<br><br><br><br><br>

### 호흡

급성 환자의 행동 조절을 위해 벤조디아제핀 주사제를 반복하는 경우, 드물게 <s>호흡 부전</s>[^-9]이 올 수 있다. 가스 교환이 제대로 이루어지지 않기 때문에, 의식이 흐려지고 청색증이 올 수 있다. 흔히 사용되는 로라제팜은 디아제팜보다 위험이 적고, 근육 주사는 정맥주사보다 위험이 적다. 그러나 언제든 찾아올 수 있는 응급 상황이기 때문에 산소를 투여할 수 있는 시설이 마련되어 있어야 한다. 올란자핀 주사제 역시 유사한 호흡 부전을 일으킬 수 있다.

[^-9]: **호흡 부전(respiratory depression, hypo-ventilation)**: 벤조디아제핀과 아편양 물질 투여 후 중추성 호흡 드라이브가 줄어들고, CO~2~ 농도에 대한 반응성이 약해지면서 호흡수가 줄고, 무호흡 기간이 길어지며, 청색증이 발생할 수 있다. 또한 GABA 활성화에 의한 호흡 근육의 약화도 원인으로 작용한다.[@vozoris2014]

<br><br>

### 감염성 질환

조현병 환자들 중 일부는 개인 위생이 불결하고, 생활 습관이 불규칙하며, 약물 남용의 위험이 높기 때문에 여러가지 감염성 질환에 걸릴 가능성이 높다. 이러한 환자들이 입원 시설에서 공동 생활하면서, 서로서로 간염, 요로 감염, 드물게는 성병까지도 옮길 수 있다.[@ayano2018] 한 연구에서는 조현병을 비롯한 급성 정신증 환자의 20% 이상이 요로 감염에 걸려있는 것으로 조사되었다.[@graham2014] 한편 항정신병 약물의 용량이 높아지면, 면역 기능이 떨어지면서 폐렴을 비롯한 감염성 질환의 위험이 증가한다.[@dzahini2018] 클로자핀은 침흘림 때문에 흡인성 폐렴의 위험을 높인다.[@kaplan2018]

입원 중인 환자가 열이 나기 시작하면 의사는 감별 진단에 애를 먹는다. 보통은 폐렴 및 요로 감염을 의심하여 체계적인 검사를 하고, 전방위적으로 항생제를 쓰게 되는데, 감염원이 발견되지 않는 경우가 태반이다. 그런데 클로자핀은 사이토카인 분비를 촉진하면서 발열 반응을 일으키며[@jeong2002], 그 밖의 약물도 체온조절 중추의 기준점(set-point)을 변화시켜 체온을 올리기 때문에 감별에 애를 먹을 수 있다.[@ferreira2019] 무엇보다도 환자가 강직증을 보이기 시작하거나 의식 변화가 동반된다면, 항정신병약물 악성증후군, 저나트륨 혈증에 의한 횡문근융해증까지도 의심해보게된다.

### 임신

급성기 약물 치료를 받는 모든 가임기 여성 환자는 임신 여부를 확인해야 한다. 피임 등 자기 관리를 잘 하지 못하는 환자는, 자신도 모르는 채로 임신이 되었을 가능성이 있다. 대부분의 항정신병 약물은 임신과 관련된 위험에서 <s>C 등급</s>[^-10]에 속한다. 적어도 항정신병 약물 복용에 의하여 선천적 기형의 위험이 높아지는 것으로 보이지는 않는다.[@huybrechts2016] 그러나 임신 말기에 항정신병 약물이 투여되면, 갓 태어난 신생아에게서 추체외로 증후군이나 금단 증후군이 종종 발생한다.[@gentile2008]

[^-10]: 미국 FDA가 정한 임부 안정성 등급에서 C 등급은 **동물 실험에서 드물게 이상 반응이 발견되었으나 인간에게는 체계적인 연구가 이루어지지 않은 약물**을 의미한다.

## References {.unnumbered}
