---
title: "치료저항성 환자의 평가"
author: "정성훈"
bibliography: References/11-02.bib
mainfont: NanumGothic
output:
  pdf: 
    latex_engine: xelatex
---

## **치료 실패 요인의 탐색**

과거 치료가 실패의 연속이었다고 해서, 반드시 치료저항성 환자라고 단정할 수는 없다. 질병의 생물학적 요인에서 비롯된 치료저항성이 아닐 지라도, 다양한 원인으로 인해 치료가 실패한다. 치료 실패의 다른 요인, 즉 가성 치료저항성(pseudo-resistance)의 원인을 찾는 것은 생물학적 요인을 고려하는 것 못지 않게 중요하다. 예를 들어 치료에 실패하는 환자의 ⅓ 가량은 약물동역학적 변수나 낮은 순응도로 인해 유효햔 혈중 농도를 유지하지 못한다.[@mccutcheon2017] 치료 거부나 낮은 순응도로 인한 치료 실패에 비하면, 정작 생물학적 치료저항성은 그 비중이 상대적으로 낮은 편이다.

### 환자 관련 요인들

치료 실패를 부르는 요인은 수정 불가능한 요인과 수정 가능한 요인으로 나눌 수 있다. 인종, 성별 등 인구학적 특성, 유전적 배경, 발달력 등은 수정 불가능하다. 이에 비해 약물 순응도나 물질 남용, 가족 내 지지체계와 같은 요인은 원칙적으로 수정이 가능하다. 결혼 상태, 직장 유지나 종교 생활, 가족의 지지체계 등도 중요한 요인으로 손꼽히지만, 이들은 치료 실패의 원인인지 결과인지를 따져보아야 한다. 독거 남성이 치료 반응이 나쁘다고 하지만, 치료가 안 되어 결혼 시기를 놓쳤을 가능성이 높다.

마찬가지로 개인의 성격이나 심리적 회복탄력성(resilience) 역시 치료 성패를 가르는 중요한 요인이지만(4장 3-2절 참조), 부적응적인 병전 성격이 조현병 전구 증상의 일부임을 감안한다면, 질병 자체의 한 부분일 가능성이 높다. (1장 6-1절) 그렇다 해도 병전 성격은 정신병적 체험에 대처하는 자세를 결정한다는 점에서 중요한 요건이다. 질병을 어떻게 해석하고, 받아들이며, 치료에 어떤 태도를 취하는 지와 같은 질병 행동은 상당 부분 질병 자체가 아니라 병전 성격에 의해 결정된다.[@tait2003] 마찬가지로 질병과는 상관없는 스트레스에 얼마나 취약하고, 지금까지 어떻게 극복해왔는 지도 치료 성패에 큰 영향을 준다.[@myin-germeys2005]

### 가족 관련 요인들

가족 내에 환자가 있음으로해서 가족 관계가 비뚤어지고 긴장도가 높아질 가능성이 있긴 하지만, 가족들의 빈번한 언어적/비언어적 <s>감정 표현</s>[^11-02-1]은 치료 실패를 부른다.[@vaughn1984] 입원 상황에서 안정을 찾은 환자가 퇴원만 하면 증상이 나빠지는 것은 이런 원인에 의할 때가 많다.[@theimpo1996] 조현병이 빈번히 발병하는 청년기 초기는, 자신의 사회적 정체성을 확립하고 정서적, 경제적 독립을 이루는 매우 중요한 발달단계이다. 그래서인지 학업이나 취업에 대한 가족들의 압박이 매우 심하며, 환자들의 음성 증상이 보호자의 눈에는 게으름이나 소심함으로 비쳐지는 경우가 허다하다. 물론 환자가 가장이거나, 가정 살림을 책임지고 있는 경우는 말할 것도 없다. 일단 질병이 만성화되면, 환자가 증상을 이유로 가족구성원으로서의 책임을 다하지 않는 것이 더 이상 용납되지 않는다. 노골적으로 표현되든 아니든 이러한 압력들은 환자를 궁지에 몰아넣는다. 비교적 상태가 좋은 환자들은 가족들의 기대에 부응하기 위해 항정신병 약물을 복용하지 않으멸 하며, 상태가 나쁜 환자들은 망상의 세계로 도피하거나 적대감을 키운다.[@goldstein1982]

[^11-02-1]: 1956년 영국에서 퇴원 환자의 재발률을 연구하고 있던 사회학자 George Brown은, 환자가 퇴원 후 부모나 배우자와 살게 되는 경우가, 퇴원 후 형제나 지인들과 사는 경우보다 재입원률이 높다는 것을 발견하였다. Brown은 그 원인이 가족이 환자에게 가하는 비판적인 감정표현에 있다고 생각하였고, 이를 표현된 감정(expressed emotion, EE)이라 명명하였다. 대표적인 EE에는 1) 비판적 언급, 2) 적대적인 말, 3) 감정적으로 과도한 간섭이 있으며, 가족구성원은 자신들이 하는 이러한 말들이 환자에게 도움이 되리라고 믿지만, 실제로는 심한 스트레스를 주어 재발률은 높이기만 한다.

이와는 대조적으로 환자의 현 상태를 인정 및 수용할 수 있으며, 회복에 대한 희망보다 사람 그 자체의 가치에 대한 믿음이 있으며, 환자를 일상 생활에 적극 참여시키고, 무엇이 증상을 악화시키는지 인식하고 있는 가족이라면, 치료 실패나 재발률을 유의하게 낮출 수 있다. [@tlhowe2017]

### 질병 관련 요인

치료 초기의 반응을 보면 이후 경과를 대략 예측할 수 있다. 양호한 경과를 보일 환자들은 대개 치료 개시 후 첫 2주 내에 긍정적 변화를 보인다.[@agid2003; @leucht2005] 치료저항성의 정의에는 용량 적정 기간을 제외한 최소 6주 이상의 치료를 명시하고 있지만, 의사들은 대체로 현재의 치료 전략을 4주 이상 유지해도 반응이 없으면 전략을 바꿔야 할 때가 되었다고 여긴다.[@suzuki2011; @samara2015]

병식의 부재는 비순응으로 직접 이어지기 때문에, 병식은 치료 성패의 중요한 요건이다. 병식이 있고 없고는 병전 성격에 좌우되므로 환자 관련 요인아라 할 수도 있겠으나, 질병 자체의 특성으로 보아야 될 때가 많다. 예를 들어 약물 반응이 좋은데도 불구하고, 이상하게 병식을 회복하지 못하는 환자들이 적지 않다.[^11-02-2] 이는 인지 증상이나 판단력 저하와 관계가 있을 수 있는데, 이유가 어쨌든 궁극적으로 치료저항성으로 이어질 위험이 높다.[@emsley2008] 병식은 일단은 수정가능한 요소이지만, 병식이 좋아야 치료가 잘 되며, 치료가 잘 되어어야 병식을 얻는다는 순환론적 모순에 빠진다.[@kemp1995]

[^11-02-2]: 조현병 환자의 병식 부재에 대해 1) 질병 자체의 핵심 증상이라고 여기는 이론, 2) 심리적 부인(denial)의 기제와 관련있다고 보는 이론, 3) 신경인지기능의 손상에 의한 일종의 질병인식불능증(anosognosia)으로 보는 이론이 있다.[@lehrer2014]

발병 초기 부터 보이는 음성/인지 증상은 치료 실패와 깊은 연관이 있다. 긴 전구 기간 동안 적응 수준이 낮고, 인지 증상이 뚜렷하며, 양성 증상이 뚜렷하지 않으면서 서서히 발병하는 경우는 치료 반응이 불량하다. 발병이 잘 드러나지 않아 정신병의 비치료 기간(DUP, 1장 6-1절 참조)이 길었기 때문일 수도 있지만[@kane1988], 그러한 양상 자체가 치료저항성의 예측 인자이기도 하다.[@bobes2009; @crumlish2009; @white2009] 조기 정신병 예방을 강조하는 학자들은 조현병 치료의 결정적 시기(critical period)가 있어서, 이 시기에 치료하지 못하면 평생 예후가 좋지 않다고 주장한다.[@birchwood2000] 따라서 이 시기를 놓치느냐 놓치지 않느냐가 치료성패를 좌우한다는 것인데, 아직 그 근거는 분명하지 않다.

### 치료 전략 관련 요인

개개 환자에 맞는 항정신병 약물의 유효 용량은 그 범위가 매우 넓다. 또한 제조사가 제시한 권장 용량은 현실에 맞지 않을 때가 많다. 권장 용량은 임상 연구라는 특수 상황에 맞춰진 것으로 실제 임상과는 거리가 멀다. 제약사의 경제적 논리나 식약청과의 줄다리기 때문에 용량이 현실에 맞지 않게 결정되는 일도 허다하다. 예를 들어 지프라시돈, 퀘티아핀, 올란자핀은 일상적으로 필요한 용량보다 훨씬 낮게 권장 용량이 책정되었으며, 리스페리돈과 아리피프라졸은 너무 높게 책정되었다.[@citrome2009] 경험많은 의사들은 권장용량에 크게 구애받지 않고 약물을 사용하지만, 보험규정때문에 제약을 받을 때가 많다. 궁극적으로 개개 환자의 적절 용량은 치료적 약물농도검사(Therapeutic Drug Monitoring ,TDM)나 직접 D~2~ 수용체 점유율을 확인하여 결정할 수 밖에 없다. 병원에 따라선 클로자핀의 혈장 농도 검사가 가능한 곳도 있으나 보편적이진 않으며[@mauri2007], 후자의 방법은 PET 촬영을 해야한다는 점에서 더욱 비현실적이다.

따라서 용량 조절은 무엇보다 임상적 관찰에 따라 이루어져야 한다. 고전적 항정신병 약물은 부작용 최소화를 위해 용량적정(dose titration)의 중요성이 강조되었지만, 비정형 약물은 부작용이 적어 용량적정이 필요없다는 식으로 선전되는데, 이는 사실이 아니다. 불필요하게 높은 혈중 농도는 부작용을 유발하며, 간혹 부작용이 증상으로 오인되어 더욱 치료 효과를 떨어뜨리기도 한다. 역으로 약물 대사가 지나치게 활발한 환자는 권장 용량보다 훨씬 고용량을 사용해야 치료 효과를 얻을 수 있다.

치료저항성을 판정하는 충분한 용량이란 보통 클로르프로마진 등가 용량으로 600\~1,000mg 정도를 말하지만, 좀더 엄밀하게는 D~2~ 수용체를 60\~80% 차단할 수 있는 정도의 용량을 말한다. 물론 도파민 부분효현제 등 새로운 기전의 약물이 도입되고 있기 때문에, 획일화된 기준에 매달려서는 곤란하다. 게다가 개개인의 약물동역학적 차이때문에 용량의 절대값은 별 의미가 없다. 혈중 농도 검사가 가장 정확하겠지만, 클로자핀 이외에는 치료적 약물농도검사(TDM) 자체가 불가능하며, 클로자핀의 TDM 역시 진료 목적으로 사용하기는 현실적이지 못하다. 경험적으로 용량을 꽤 높였다고 생각했는데도 효과는 물론 부작용마저 없다면 일반 인구에 비해 유독 대사가 빠르다고 의심할 필요가 있다. 최근에는 약물유전학(pharmacogenetics)의 발전으로 말미암아, 미리 유전형 검사를 통해 약물 대사 정도를 예측하기도 한다.[@yoshida2018]

다약제 투여(polypharmacy)가 관행이 되고 있으므로 약물 상호 작용도 고려해야 한다. 약물 상호 작용은 싸이토크롬 p450 효소 체계 이외에도 장에서의 약물 흡수, 혈장단백질 결합정도 등에서 일어나기도 한다. 약물 상호작용은 정신과 약물 뿐 아니라 모든 처방 약물에 대해 고려되어야 하며, 간혹 비처방 약물도 영향을 줄 때가 있다. 병용 투여되는 약물이 많아지면 경우의 수가 기하급수적으로 늘어나며, 약물동역학적 차원 뿐 아니라 작용 기전 상의 상호작용까지 고려한다고 했을 때, 단순한 계산법으로는 도저히 파악할 수가 없다.[@sunny2022]

## **치료저항성의 판정**

어떤 환자를 섣불리 치료저항성으로 판정하게 되면, 향후 치료에 소극적이 되거나 역으로 너무 공격적인 치료로 인해 불필요한 피해를 입게 된다. 또한 제대로 사용했으면 효과적이었을 지도 모르는 약물을 반응이 없었다면서 평생 다시 쓰지 않게 될 지도 모른다. 치료가 되지 않는 상태가 오래되면, 환자는 더더욱 약물에 신뢰를 잃게 되며 치료가 필요없다는 생각을 굳히게 된다. 따라서 치료저항성이라고 선언하기 전에 철저한 평가 과정이 선행되어야 한다.

### 진단의 재평가

환자의 진단이 맞는가를 재평가할 필요가 있다. 인격 장애나 양극성 장애 또는 정신병적 우울장애 등이 조현병과 구별하기 어려울 수 있다. 기질적 원인에 의한 정신병적 상태인 경우 항정신병 약물에 저항적일 수 있다. 강박증이나 정신병적 증상이 동반된 우울증 등은 항정신병 약물 만으로는 최적의 치료 효과를 기대하기 힘들다. 긴장증 증상을 동반한 경우에는 벤조디아제핀, 클로자핀, 전기경련치료 등으로 치료 전략을 바꿔야 한다.[@england2011]

미국의 경우 치료저항성의 흔한 원인 중 하나는 물질남용이다. 환자들은 남용물질을 사용하여 증상에 대처하려 하지만, 그러다보면 정작 항정신병 약물에 대한 순응도가 떨어지며, 또한 남용약물 자체의 영향 때문에 항정신병 약물의 효과를 가로막을 수 있다.[@schoeler2017] 한편 우리나라에 특징적인 현상으로, 식욕억제제 때문에 정신 증상이 지속되는 것을 들 수 있다. 애초에 진단이 틀려서 조현병이 아니라, 단순히 약물에 의한 정신증이었을 가능성도 있다. 하지만 조현병 환자가 식욕억제제에 의존하는 경우도 적지 않다는 것을 기억해야 한다. 이를 놓치면, 치료저항성의 중요한 원인 중 하나를 간과하는 셈이다.

### 순응도 평가

어떤 약물이 도움이 되느냐 아니냐를 판정하기 위해서는 환자가 적어도 처방된 약물의 80% 이상을 복용하여야 한다. 환자는 자신의 약물복용 여부에 대해 정확히 보고하지 않으므로, 가족의 보고, 약품 구매 기록, 남은 약물 개수의 확인 등을 통해서 다방면으로 살펴보아야 한다. 가능하면 불시에 혈중 농도를 검사하는 것도 방법이다.[@mccutcheon2017] 외래에는 꼬박 방문하면서 약은 제대로 먹지 않는 환자들이 예상보다 많다. 의심이 된다면 장기지속 주사제를 고려해야 한다.[@dold2014] 앞서 언급했듯이 TRRIP는 치료저항성을 판정하기 전에, 장기지속 주사제를 적어도 4개월 이상 써보아야 한다고 명시하고 있다. 실제로 같은 약물이라도 장기지속 주사제의 치료 성적이 경구제보다 좋다는 것이 보고된 바 있다.[@kishimoto2013]

### 과거력 평가

치료저항성을 판정하기 위해선, 과거에 두차례 혹은 세차례 이상 항정신병 약물 치료에 실패했다는 과거력이 필요하다. 오래전부터 동일한 의료진에 의해 치료받은 것이 아니라면, 과거력을 조사할 때 신뢰할만한 기록을 얻기가 힘들 때가 많다. 환자가 설령 약물의 이름을 어렴풋이 기억한다고 해도, 사용 용량이나 기간에 대해선 잘 알지 못하며, 사용하던 약물을 효과 부족때문에 중단헀는지 부작용 때문에 중단했는지도 잘 알지 못한다. 과거 약물 치료에 실패했던 것이 의학적인 이유가 아니라 전혀 엉뚱한 이유 때문이었을 수도 있다. 과거 의무기록을 열람할 수 있다 하더라도 기록이 미비하다면, 치료 실패 판정을 내릴만큼 적절한 치료가 행해졌는지 확인하기 어렵다. 현실적으로 많은 의사들은 자신이 직접 해당 약물을 사용해본 연후에야 치료저항성이라 판정을 내리곤 한다.

### 약물 치료의 한계

조현병의 모든 증상이 약물치료에 반응하는 것은 아니다. 흔히 음성/인지 증상은 약물에 잘 반응하지 않는다고 하지만 이외에도 다양한 문제들이 있다. 특히 환자들은 우울, 강박, 물질 남용 등의 문제가 동반되는 경우가 허다한데, 이들 증상이 해결되지 않았다고 해서 항정신병 약물 치료가 실패했다고 판정하긴 어렵다. 가족 구성원과의 적대적 관계, 적응 실패의 결과로 느끼는 좌절감과 분노가 과격한 행동을 유발하여 마치 양성 증상처럼 보일 수 있지만 이는 일차적으로 약물로 해결될 수 있는 문제가 아니다. 사회적 고립과 이로인한 소외괌과 외로움 또한 약물로 호전을 기대하기 어렵다. 이러한 문제들이 환자의 회복을 가로막는다면, 전체적인 치료의 실패라고는 말할 수 있을 지언정, **"약물에 대한 치료저항성"**이라고 말하긴 어렵다.

### 부작용 평가

추체외로 증상이 음성증상으로 오인되거나 정좌 불능이 정신병적 초조로 잘못 평가되면 엉뚱하게 치료저항성 판정이 내려질 수 있다. 특히 후자의 경우 약물을 더 증량하게 되면서 환자 상태는 더 악화될 수 있다.[@dold2014] 클로자핀 투여로 인한 강박증상 역시 치료에 반응이 없는 것인지, 치료로 악화되는 것인지 구분하기 어렵다. 이런저런 이유로 해서 일시적으로 용량을 줄여보는 것도 치료저항성 판정에 도움이 된다.

## References {.unnumbered}
