---
title: "치료저항성 환자의 치료전략"
editor: visual
bibliography: References/11-03.bib
---

## 고용량 처방

적극적인 의사들은 초발 환자인 경우라도 치료저항성을 보이면 일찌감치 클로자핀을 사용할 것을 권하고 있다.[@agid2007] 그러나 아무리 치료성적이 좋다고 해도 실제로 사용하기에는 진입장벽이 높다. 무과립구증의 위험은 비율이 매우 낮아서 무시할 수 있다 하더라도, 진정작용이나 체중 증가, 침흘림, 야뇨증, 심장 및 위장관계 부작용 등, 위험은 낮아도 빈번한 부작용이 현실에서의 사용을 제한한다.[@iqbal2020]

따라서 치료저항성 환자에게 클로자핀을 이용하기 전에 다른 방도를 먼저 시도해보는 것이 보통이며, 이는 크게 1) 기존의 약물을 더 오래, 더 높은 용량으로 사용해 보거나, 2) 다른 항정신병 약물로 교체하거나, 3) 항정신병 약물 이외의 다른 약물을 병용 투여하거나, 4) 두 가지 이상의 항정신병 약물을 조합하는 것으로 나눌 수 있다.

제조사의 권장량, 임상연구에서의 용량, 가이드라인 권장 용량 등은 서로 다를 수 있으며, 실제 환자에게 적용할 때는 큰 도움이 되지 않는다. 부작용을 자주 평가하고, 필요할 때마다 실험실 검사를 진행한다면 권장 용량보다 높여도 대개 문제가 없다. 간혹 항정신병 약물을 과다 투여하여 응급실을 방문하는 환자가 있지만 부정맥의 위험 말고는 치명적인 경우는 드물다.[@trenton2003] 이런 이유에서인지 권장 용량보다 높게 투여하는 것은 다약제 투여와 함께 치료저항성 환자에서 가장 널리 시도되는 방법이다.[@howes2012]

권장 용량 혹은 표준 용량이란 보통 대상 환자의 50%에서 기대한 효과를 나타내는 용량 즉 중앙 유효량(median effective dose, ED~50~)을 말한다. 이는 예를 들어 올란자핀 10mg, 리스페리돈 2mg, 퀘티아핀 200mg 등의 용량으로 예상외로 낮다. 이에 비해 최대용량에 근접하는 용량 (near-maximal effective dose, ED~95~)이란 대상 환자의 95%에서 기대한 효과를 나타내는 용량, 혹은 약물이 발휘할 수 있는 거의 최대 효과를 나타내는 용량으로 정의된다. 이는 아리피프라졸 11.5mg, 올란자핀 15.2mg, 팔리페리돈 13.4mg, 퀘티아핀 482mg, 리스페리돈 6.3mg 정도이다.[@woods2004; @leucht2020]

표준 용량에서 반응이 없는 경우, 최대 근접 용량을 시도하는 것은 자연스러우며 대부분의 정신과 의사는 이 정도 용량을 시도하지 않고는 치료 실패라고 단정짓지 않을 것이다. 애초 Kane의 정의에 따르면 치료저항성을 판정하기 전에 적어도 클로르프로마진 등가 용량으로 1,000mg 이상을 사용해보았어야 하며, 완화된 기준도 적어도 600mg 이상 사용해보았을 것을 권하고 있다. 그러나 클로르프로마진의 최대 근접 용량은 450mg 정도이다.

논란의 대상이 되는 것은 최대 근접 용량 보다 더 용량을 높였을 때 얼마나 도움이 되느냐이다. 개인에 따른 약동학적 차이나, 병용 투여되는 약물에 의한 대사률 변화 등 다양한 원인에 의해 혈중 농도가 변화하며, 뇌혈관 장벽을 통과하는 비율도 달라지므로, 이러한 변수가 의심된다면 용량을 최대한 높여볼만 하다. 그러나 임상 연구에서 이러한 전략을 지지하는 자료는 매우 드문 편이다. Agid 등[@Agid2011]은 표준 용량에 반응하지 않는 환자를 대상으로 1) 올란자핀 22.5\~30mg, 리스페리돈 6.5\~10mg 까지 용량을 높여보았다. 그 결과 표준 용량에서 반응한 환자 비율이 71% 였는데 비해 고용량에서의 반응율은 75%로 불과 4% 증가하는데 그쳤다. 동일한 연구에서 약물을 교체해보았더니 역시 추가 4% 정도의 환자만 반응하였으며, 클로자핀으로 교체한 이후에야 비로소 앞서 두 단계에서 반응을 보이지 않았던 환자의 75%가 반응하였다.

다른 몇몇 임상 연구 및 메타 분석에서도 최대 근접 용량을 넘어서면 효과는 별반 그대로이면서 부작용만 증가하게 된다고 결론짓고 있다.[@honer2011; @dold2015; @samara2016] 이러한 결론은 앞으로도 크게 바뀔 것 같지 않으며, 치료가이드라인을 중요시하는 연구자들은 더더욱 고용량 치료가 필요없다고 강조한다. 아무래도 치료저항적 환자에서의 고용량 투여는 가장 손쉽지만 동시에 가장 효과가 떨어지는 방법으로 보인다.

## 다른 항정신병 약물로 교체

### 교체 약물의 선택

모든 항정신병 약물은 D~2~ 수용체 차단을 기본적인 작용기전으로 삼고 있지만, 개개 약물마다 독특한 차이가 있다. 따라서 한가지 약물에 반응하지 않는 환자가 다른 종류의 약물에 반응할 지 모른다고 기대하는 것은 자연스럽다. 여기서 주목할 것은 치료저항성을 정의하는 몇몇 기준들은, "서로 다른 클래스"에 속하는 약물을 두가지 혹은 세가지 이상 사용해보아야 한다고 명시했다는 점이다. 즉 작용 메카니즘이 거의 동일한 약물이라면 약물을 바꾸는 의미가 반감된다. 한 가지 약물에 실패했다면, 교체할 약물은 전혀 다른 작용기전을 가진 약물 중에서 선택해야 한다.

그런데 약물들의 클래스를 나눈다는 것이 생각보다 쉽지 않다. 모든 약물은 수용체 결합 프로파일이 조금씩 다른데, 어떤 기준으로 클래스를 나눠야 하는지에 대해선 정해진 바가 없다. 정형 항정신병 약물 시대에는 역가(potency)와 함께, 결합하는 수용체의 다양성에 의해 약물을 구분하였다. 즉 할로페리돌, 피모자이드과 같이 비교적 순수한 D~2~ 수용체 차단제이면서 역가가 높은 약물, 그리고 클로르프로마진처럼 다양한 수용체에 결합하면서 역가가 낮은 약물로 구분되었다. 경우에 따라서는 퍼페나진과 같이 그 중간에 속하는 약물을 다른 클래스로 구분하기도 하였다.[@verster2010]

한편 비정형 항정신병이 도입된 이후에는 정형과 비정형이라는 두 가지 클래스로 구분하는 것이 일반화 되었다. 리스페리돈, 올란자핀, 퀘티아핀, 아미설피라이드 등 대표적인 비정형 약물들은 한데 묶여 동일한 클래스로 취급받거나, 역으로 각자가 서로 다른 클래스에 속하는 것으로 여겨졌다. 클로자핀만은 예외취급을 받아 어떤 클래스에도 속하지 않는 것으로 간주되었다. 이러한 상황은 아리피프라졸의 등장으로 변화되기 시작하였다. 도파민 부분효현제인 아리피프라졸은, 세로토닌-도파민 수용체 차단제라는 비정형 공식에서 벗어나있었으며, 이후 등장한 소위 참신한(novel) 항정신병 약물의 원형이 되었다. 예를 들어 cariprazine, brexpiprazole, lumateperone 등은 모두 도파민 부분효현제로서 작용한다. (3장 4-1 참조) 따라서 현재 서로 다른 클래스라고 하면, 1) 정형 약물, 2) 클로자핀을 제외한 비정형 약물, 3) 클로자핀, 4) 도파민 부분효현제로 나눠질 수 있다. 앞으로 순수한 세로토닌 수용체 차단 약물이나 글루타메이트 수용체 약물이 등장한다면 클래스가보다 다양해질 지도 모른다. 치료저항성 환자에게 약물을 교체한다는 것은 이렇듯 실패했던 약물과는 클래스가 다른 약물로 교체해야 한다는 뜻으로, 선택에 신중을 기해야 한다. 무조건 새롭게 개발된 약물이 더 효과적이라는 뜻은 아니기 때문에, 비정형 약물에 효과를 보지 못했다면 정형 약물을 시도해보는 것도 방법이다.

### 약물 교체시 주의점

약물을 바꾼다는 것은 항상 위험성을 수반한다. 치료 효과가 부족하다곤 하지만, 그나마 이전 약물에 의해 현재 정도의 안정상태를 유지하고 있는지도 모른다. 특히 고정된 처방을 오래 써온 환자는 사소한 약물 교체나 용량 변경으로 인해서도 안정 상태가 무너질 수 있다. 이런 잠재적 위험성을 최소화하기 위해서는 점진적인 교체 방법(cross-tapering)이 권장된다.[@weiden2007] 기존의 약물을 서서히 줄이면서 새 약물을 도입하는 것이다. 증상이 심해서 약물 변경 시 악화 위험이 높다고 판단되면, 두번째 약물을 어느 정도 용량 이상으로 투여한 뒤에 비로서 앞서 사용했던 약물을 감량하는 전략을 취할 수도 있다. 이런 조심스러운 접근의 단점은 새 약물을 추가하는 과정 중에 환자가 호전되었을 때 이전 약물을 끊지 못하고 의도치 않게 다약제 처방이 될 수도 있다는 것이다.[@takeuchi2017] 그러나 원칙은 이전 약물을 완전히 끊는 것이며, 명확한 근거없는 다약제 처방은 바람직하지 않다.

그러나 비정형 약물 사이의 작용기전 차이는 미미한 편이기 때문에, 첫번째 약물에 반응이 없었다면 약물을 교체한다고 해도 극적인 효과를 기대하기 힘들다.[@stauffer2011; @lally2016] CATIE (Clinical Antipsychotic Trials of Intervention Effectiveness, 3장 6-1절 참조) 연구에서는 한 종류의 약물에 실패한 환자들을 적극적으로 다른 약물로 교체해가면서 관찰을 지속하였는데, 어떻게 해도 클로자핀으로 교체한 군의 반응율을 따라갈 수 없었다.[@rosenheck2009] 게다가 약물을 중간에 교체한 환자는 처음 약물을 그대로 지속한 군에 비해 중도 탈락률이 더 높았다.[@Essock2006] 이는 매우 의기소침해지는 연구 결과로 치료저항적인 환자는 약물을 어떻게 바꿔봐도 별 소용이 없을 뿐더러, 자주 약물을 바꾸면 약물에 대한 신뢰도만 떨어뜨린다 결론이었다.

### 장기지속형 주사제

장기지속형 주사제는 대체로 경구 약물로 만족할만한 효과를 보았을 때, 이 상태를 최대한 오래 유지하고 재발을 막기 위한 수단으로 선택된다. 그러나 적지 않은 연구에서 경구 약물에 비해 장기지속형 주사제가 효과나 재발 억제 측면에서 우수하고, 심지어 동일 성분의 경구 약제와 비교해도 우수하다는 결과가 얻어졌다.[@marinis2007; @markowitz2013; @kishimoto2017; @lynnstarr2018]

만약 과거의 치료 실패가 부분 순응문제 때문이었다면 고민하지 말고 장기지속형 주사제를 사용해보는 것이 필요할 것이다. 반복된 지적이지만 최근의 치료저항성 판정기준에는 장기지속형 주사제 사용을 꼭 시도해보기를 권하고 있다. 한발 더 나아가 반드시 순응도 때문이 아니었더라도, 경구 약물로 치료에 실패했을 때 주사제를 사용하는 것이 긍정적인 결과를 가져올 가능성이 있다. 주사제의 안정된 혈중 농도 유지 특성이 치료 반응을 높이는데 도움이 될 수 있다. 대표적인 예로 도파민 초과민성때문에 유발된 치료저항성 환자의 경우 장기지속형 주사제가 매우 효과적이라는 보고가 있다.[@kimura2014]

## 병용요법 혹은 증강요법

정신과 영역에서 다약제 투여(polypharmacy)는 눈살을 찌푸리게 하는 용어이긴 하지만 실상 모든 정신과 의사가 행하고 있는 치료전략이다.[@lin2019] 정의로만 따지면 동일한 질병을 치료하기 위해 두 가지 이상의 약제를 쓰는 것을 다약제 투여라 하지만, 숨겨진 의미는 반드시 필요한 약제 이외에 더 많이 투여하는 것을 가리킨다. 다약제 투여라는 용어는 다양한 개념을 포함하고 있으며, 이들은 문헌에서도 혼란스레 사용되고 있다.

좁은 의미의 다약제 투여는, 동일한 효과의 약제 혹은 동일한 클래스의 약제를 여러 개 동시에 투여하는 것이다. 이를 **병행약물(concurrent/concomitant medication)**이라고도 한다. 리스페리돈과 할로페리돌을 동시에 투여하는 것, 플루옥세틴과 파록세틴을 동시에 투여하는 것은 동일한 클래스의 약물을 사용하는 경우이다. 클로자핀과 아리피프라졸처럼 서로 다른 클래스의 약물을 투여하는 경우도 있지만 둘다 기대하는 효과는 동일하다. 이와는 달리 **병용요법(adjunctive therapy)**이란 치료 대상이 되는 질병은 같지만 기대하는 효과가 전혀 다른 약물을 사용하는 것이다. 항정신병 약물과 항우울제, 혹은 기분안정제를 함께 투여하는 것이 여기에 속한다. 그 밖에도, 항정신병 약물의 부작용을 해소하기 위해 항파킨슨 제제를 함께 투여하는 것, 수면 조절을 위해 벤조디아제핀을 투여하는 경우도 병용요법에 속한다.

매우 유사한 개념으로 **증강요법(augmentation therapy)**이 있다. 주로 사용되는 약제만으로 효과가 부족할 때, 다른 용도의 약물을 소량 첨가함으로써 부족한 반응을 보충한다는 의미이다. 추가 되는 약물은 단독으로 사용될 때에 비해 낮은 용량이 사용된다는 특징이 있다. 예를 들어 난치성 우울증에 항우울제와 더불어 갑상선 호르몬을 소량 섞는 경우이다.[@Kukreja2013]

개념들이 서로 얽혀 있어 복잡하지만 치료저항성 조현병 치료에서 주로 언급되는 것은, 1) 항정신병 약물과 비항정신병 약물을 섞어 쓰는 병용요법과 2) 두 가지 이상의 항정신병 약물을 쓰는 다약제/병행 투여 두가지이다. 후자에 대해선 달갑게 여기지 않는 의사들도 전자에 대해선 적극 수용하고 있다. 병용 투여를 하는 이유는 치료저항성을 넘어서기 위해서이기도 하지만, 항정신병 약물로는 호전되지 않는 증상을 치료하기 위해서이기도 하다. 후자의 예로는 동반된 우울이나 강박증상을 치료하기 위해 선택적 세로토닌 재흡수 억제제(SSRI)를 사용하는 것이 있다.

안타깝게도 기존의 항정신병 약물에 어떤 약물을 병용했을 때 분명히 효과적이라는 임상 증거는 희박한 편이다. 지금까지 무척이나 다양한 향정신성 의약품들이 항정신병 약물과 함께 병용요법으로 시도되어 왔으며, 이 밖에도 항염증제, 항산화제, 호르몬조절제, 글루타메이트 및 니코틴 수용체 조절제, 내인성 카나비노이드 제제(2장 2-1절 참조) 등이 연구되었다.[@Bumb2015; @Brown2016] 벤조디아제핀 사용을 병용요법의 하나로 보기도 하나[@szarmach2017]**, 실제 임상에서는** 거의 모든 조현병 환자에게 투여되기 때문에 굳이 병용요법이라 할 수 있을 지 의문이다. 이를 제외하고 가장 많이 사용되는 병용요법 제제는 항우울제와 기분안정제이다.

### 항우울제

조현병에서 항우울제가 사용되는 것은 치료저항성을 해결한다기 보다는 동반된 우울/음성/강박 증상을 해결하기 위해서이다. 항우울제는 조현병 환자에게 가장 많이 병용 투여되는 약물 중 하나이며, 미국, 유럽에서는 대략 40%에 달하는 조현병 환자에게 투여된다.[@Mao2015]

비정형 항정신병 약물의 비정형성이 5-HT~2A~ 수용체 차단에 있다고 흔히들 이해되고 있기 때문에, 세로토닌 계에 영향을 미치는 항우울제는 우울 증상 개선을 넘어서 음성 증상에 효과가 있을 것으로 기대된다. 대표적인 예로 5-HT~2A~ 길항제인 ritanserin은 음성 증상 개선제로 기대를 모았으나 아쉽게도 임상에 도입되지는 못했다.[@Akhondzadeh2008] 최근의 한 임상 연구에서는 또 다른 5-HT 길항제인 vortioxetine이 리스페리돈과 병용 투여되었을 때 음성 증상을 유의하게 호전시켰다고 보고되었다.[@Moazen-Zadeh2020] 정확한 기전은 알 수 없지만, 항우울제를 병용 투여하면 전전두엽의 도파민과 노르에피네프린 활성이 늘어나기 때문에, 이 또한 음성 증상에 도움이 될 것으로 기대되었다.[@zhang2000] 한 메타 분석에서 다양한 항우울제는 조현병 환자의 음성 증상 호전에 중등도 정도의 효과 크기를 보이는 것으로 평가되었다.[@Singh2010]

항우울제를 병용할 때는 약동학적(pharmacokinetic)뿐 아니라 약력학적(pharmacodynamic) 상호 작용을 고려하여야 한다. 오래전부터 삼환계 항우울제와 SSRI는 비교적 안전하게 병용 투여되어 왔다. 노르에피네프린 활성을 높이는 Noradrenergic and specific serotonergic antidepressants (NaSSAs)나 SNRI, 그리고 도파민 활성을 높이는 부르포피온 등은 정신병적 증상을 악화시킬 수 있다는 우려를 자아냈으나, 실제 임상에서는 큰 무리없이 사용된다. 특히 부프로피온은 조현병 환자의 금연을 위해 사용되기도 하며, 미르타자핀은 좌불안석을 호전시키는 효과가 있다.[@Englisch2013; @Kishi2014] 멜라토닌 수용체 및 5-HT~2C~에 작용하는 항우울제 Agomelatine은 일주기 리듬을 조절하고 수면 패턴을 향상시지만 조현병 환자에서의 경험은 부족한 상태이다.[@zink2012]

### 기분 조절제 및 항경련제

선조체의 도파민 활성은 시냅스 전 뉴런의 GABA와 글루타메이트 활성에 의해 조절된다. 특히 parvalbumin을 포함하는 GABA 분비 사이뉴런은 선조체 도파민 분비를 억제하며, 그 자신은 NMDA 수용체를 통한 글루타메이트 신호에 의해 조절을 받는다.(2장 10-4절 참조 article-02-02.html#NMDA) 조현병과 글루타메이트의 관계는 이중적이어서, NMDA 수용체를 통한 신호는 오히려 저활성이어서 문제가 되지만, 전반적인 글루타메이트의 과다분비와 이로 인한 농도 증가는 흥분성 독성(excitotoxicity)을 유발하여 가뜩이나 결함이 있는 신경망을 계속 망가뜨린다.(2장 10-5절 참조 article-02-02.html#excitotoxicity)

조현병의 치료를 D2 수용체 차단제에서 벗어나 다각화 시키려던 연구자들은 GABA와 글루타메이트에 영향을 미치는 항경련제제에 관심을 두기 시작하였다. 1990년대 이후 항경련제들은 양극성 장애를 비롯하여 다양한 정신질환에 사용되기 시작하였다. 발프로에이트는 GABA를 분해하는 GABA transaminase 억제제이기 때문에 GABA 농도를 높인다. 동시에 글루타메이트가 결합하는 전압-의존성 나트륨 통로를 차단하기 때문에 흥분성 독성을 막을 수 있다. 이에 덧붙여 후성 유전학에서 자주 언급되는 히스톤 디아세틸레이즈(histone deacetylase)를 억제함으로써, 신경성장인자들의 유전자가 좀더 많이 발현되도록 유도한다.[@Chiu2013]

이처럼 발프로에이트를 비롯한 각종 항경련제들은 이론적으로는 조현병에 치료 효과를 도울 수 있는 잠재력을 지니고 있다. 그러나 실제 임상에서는 정신병적 증상 자체라기 보다는 특히 급성기에 동반되는 공격성, 자극과민성, 감정의 이변성 등을 조절하는데 더 많이 이용되고 있다. 그나마 그 효과가 반박의 여지없이 입증된 것도 아니다. 치료 초반 아직 항정신병 약물의 효과가 본격적으로 드러나지 않고 있을 때 발프로에이트는 진정효과를 내면서 흥분을 가라앉히고 공격성을 줄인다.[@Citrome2004] 그러나 조현병 증상 자체를 호전시키는 지는 확실하지 않다.[@wang2016] 그나마 호전을 돕는다는 긍정적인 연구 결과는 개방 연구에 국한될 뿐, 이중맹검 연구에서는 증명되지 못했다. 개방 연구 중에서도 4주 이내의 단기 연구에서만 차이가 났을 뿐 그 이상 진행된 연구에서는 대조군과 차이가 없었다.[@tseng2016] 따라서 발프로에이트는 치료저항성 환자에게 사용한다기 보다는, 치료 초기에 호전의 속도가 느려 행동 문제가 발생할 때 유용하게 사용될 수 있다.

발프로에이트는 진정 작용 말고는 안전성에 큰 문제가 없지만 여성 환자에게 처방할 때는 임신 가능성에 신경써야 한다.[@tomson2016] 또한 발프로에이트는 클로자핀을 비롯하여 함께 투여되는 항정신병 약물의 농도를 올리기 때문에 문제가 될 수 있다.[@Centorrino1994] 클로자핀에 발프로에이트를 추가할 경우에는 호중구감소증의 위험성을 올릴 수 있다는 점에도 주의하여야 한다.

병용 투여에 있어서 리튬의 위치 또한 발프로에이트와 비슷하다. 리튬은 GSK3 억제제로서 기분을 안정시키고 흥분성을 가라앉히는 효과가 있다. 메타 분석에서는 리튬을 병용 투여했을 때 치료 반응이 좀더 나아졌지만, 조현정동장애 환자 등 기분 증상이 두드러진 환자군을 제외하면 의미있는 차이가 보이지 않았다.[@leucht2004; @leucht2015] 2000년대 초반까지는 몇 건의 임상 시험이 이루어졌고 긍정적인 결과가 얻어지기도 하였으나[@lerner1988; @small2003; @Kontaxakis2005], 실제 임상가 입장에서는 뚜렷한 정신 증상의 호전보다는 그저 감정기복이나 자극과민성이 있는 환자를 조금 더 빨리 안정시키는데 도움이 되는 정도를 기대할 수 있겠다.

라모트리진 역시 나트륨 채널 차단제로 글루타메이트 신호전달을 억제한다. 우연히도 우울 증상을 보이는 양극성 환자에게, 조증 삽화를 유발하지 않으면서도 효과적이라는 것이 알려지면서 정신과 의사에게 친숙해졌다.[@Geddes2009] 약물 자체로서 항정신병 효과는 없지만, 유달리 클로자핀과 병용 투여했을 때 반응 정도를 높인다는 것이 알려졌다.[@Tiihonen2009] 그렇다고 속단하기는 이른데, 한 메타 분석에 따르면 라모트리진 병용 투여가 PANSS/BPRS 점수를 낮추는데 도움이 되는 것처럼 보였으나, 유달리 성적이 좋은 한 개 연구[@zoccali2007]를 제외하고 분석하면 더 이상 유의성이 관찰되지 않았다.[@sommer2011]

또 다른 항경련제인 토피라메이트 역시 양성증상 및 음성증상 호전에 도움이 된다는 메타 분석이 몇 개 있었으나[@sommer2011; @okuyama2016; @zheng2016], 분석에 포함된 연구의 질이 낮아 가이드라인에 포함되거나 임상 현장에 적용하기에는 무리가 있어 보인다.

### 글루타메이트 신호조절제

앞서 언급했듯이 조현병의 정신병리에서 글루타메이트 신호전달계가 차지하는 비중이 높아지면서, 다양한 조절 물질들이 병용요법제로 시도되었다. NMDA 수용체 내부에는 glycine 결합 부위가 있으며, glycine과 글루타메이트가 동시에 결합하여야 NMDA 신호전달이 원할히 이루어진다. 이를 응용하여 glycine을 직접 투여하거나, CX516, D-serine, D-cycloserine와 같은 glycine 효현제를 투여하기도 하고, sarcosine와 bitopertin 같은 glycine 재흡수 억제제를 사용해보기도 한다.[@javitt2001; @Buchanan2007; @beck2016]

위의 약제들은 NMDA를 통한 글루타메이트 활성을 높여 음성 증상을 회복시켜보려는 시도였다면, 메만틴 사용은 정반대의 기전이다. 메만틴은 원래 항치매제로 개발되었는데, 비경쟁적 NMDA 수용체 길항제로서 글루타메이트 신호전달을 차단한다. NMDA 차단제인 ketamine이 정신병적 증상을 유도하는 것을 고려하면, 메만틴을 조현병 치료에 사용한다는 것이 얼핏 이해가 되지 않지만, 흥분성 독성을 막고 남아있는 인지 기능을 지킨다는 명목하에 병용요법으로 시도되었다. 메만틴의 효과는 주로 음성 및 인지 증상 개선에서 엿보이며[@Zheng2018], 클로자핀에 효과가 미진한 환자에서도 기억력과 음성 증상을 호전시키는데 기여하였다.[@Veerman2017] 메만틴이 왜 정신병적 부작용을 일으키지 않는지는 의문이지만, ketamine에 비해 친화도가 낮고 비경쟁적이며, 시냅스외 수용체에 주로 작용한다는 차별점이 긍정적으로 작용할 것으로 짐작된다.[@Kikuchi2020]

그 이외에도 <s>cannabidiol</s>[^11-03-1], estrogen, <s>dehydroepiandrosterone</s>, <s>allopurinol</s>[^11-03-2], oxytocin, varenicline, NSAIDS, 아세틸콜린 수용체 효현제, 불포화 지방산 등 다양한 물질을 이용한 연구가 진행되었으나 그다지 긍정적인 결과를 얻지 못하고 있다.[@Faden2019] 점점 더 신약개발이 어려워지고 있는 상황에서, 제약사들은 기존 약물의 새로운 용도를 찾는 약물 재지정(drug repurposing)에 주력하고 있다.[@Berk2015] 과거에는 조금이라도 병태생리에 연결점이 있다면 논리적 근거가 부족하더라도 병용요법으로 시도해보곤 했으며, 자연히 대부분 실패하였다. 이제는 생물정보학적 데이터를 인공지능에 접목시켜서 좀더 합리적 방법으로 기존 약물의 새로운 용도를 찾는 작업이 태동하기 시작하였다.[@Lüscher2020; @tanoli2021] 조현병에 있어서도 이런 변화가 찾아오리라 기대해본다.

[^11-03-1]: **Cannabidiol (CBD)**: 마리화나(대마초, Cannabis sativa)에는 100개가 넘는 화학 물질(cannabinoids)이 포함되어 있으며, 이중 가장 양이 많은 것이 tetrahydrocannabinol (THC)과 cannabidiol (CBD)이다. CBD는 불안, 치매, 통증 치료에 효과가 있다고 알려지면서 일반의약품으로 판매되기도 하나, 그 효과 여부는 불분명하다.

[^11-03-2]: **Allopurinol**: Xanthine의 산화억제제(xanthine oxidase inhibitor)로서 혈중 요산의 농도를 낮추기 때문에 통풍 치료에 사용된다. 반면 혈중 adenosine 농도를 높이는데, 이는 도파민 수용체 효현 효과를 보인다.

### 약물 교체와 병용요법

일정 기간 이상의 약물 치료 후에도 반응이 미미하다면 다음 단계로 나가아하는데, 이때 고민할 부분이 새로운 항정신병 약물로 교체할 것이냐 아니면 병용요법제를 추가할 것이냐이다. 치료지침서들은 대체로 단일제제 치료를 우선시 하며, 보통 2,3개 항정신병 약물을 바꿔가며 사용해 후 그래도 안 되면 병용투여나 다약제 투여를 권하고 있다.[@Ascher-Svanum2012] 또한 클로자핀 지지자들은 효과가 불분명한 다약제 투여보다는 일찌감치 클로자핀으로 교체할 것을 적극 지지한다.[@remington2013; @Okhuijsen-Pfeifer2018]

그러나 임상 실제에서는 약물 교체보다 병용투여를 시도하는 빈도가 높다. 이전에 사용한 항정신병 약물에 전적으로 반응이 없다면 모를까 부분적으로라도 효과를 보이면 포기하기가 쉽지 않기 때문이다. 게다가 일정 증상은 반응하고, 나머지 증상은 반응하지 않는 경우에는 질병에 대한 치료가 아니라 개별 증상에 대한 치료를 행하게 된다. 조현병의 모든 증상이 단일한 병태생리에서 비롯된 것이라고도 자신있게 이야기하기 어렵기 때문이다. 따라서 환자의 증상이 조현병의 핵심 증상 중 하나인지, 아니면 다른 종류의 악제가 필요한 부가 증상인지 판단해야 하는데, 이는 오롯이 임상가의 경험과 직관에 맡길 수 밖에 없다.

## 두 가지 이상의 항정신병 약물 투여

약물 교체에 대한 논의에서 언급한 것처럼 모든 항정신병 약물들이 기본적으로는 D~2~ 수용체 억제제라고 해도, 세부적인 작용 기전은 조금씩 다르다. 따라서 한가지 약물에 부분적인 반응을 보였을 때 다른 약물로 보충하는 것도 충분히 고려할만 하다. 그러나 이는 정신약물학에서 완고하게 고수하는 단일약제 사용 원칙에서 벗어나기 때문에 어떤 교과서나 어떤 치료 지침도 다약제 투여를 드러내놓고 권장하지는 않는다. 예를 들어 영국 NICE (National Health and Clinical Excellence) 지침에 따르면, 다수의 항정신병 약물을 중복 투여하는 것은 한 약물에서 다른 약물로 교체하는 과정에서만 임시적으로 정당화 될 수 있다.[@sin2009]

정의상 항정신병 약물의 다약제 투여란 두 가지 이상의 약물을 90일 이상 투여하는 것이다. 따라서 약물 교차 적정 중 거치게 되는 이중 처방은 다약제 투여에 해당되지 않는다. 무엇보다도 다약제 투여를 께림찍하게 여기는 이유는 투여되는 약제가 많아지면 환자가 호전될 가능성 보다는 부작용만 늘어날 위험이 더 크다는 점이다. 항정신병 약물들이 치료 효과를 나타내는 기전은 대동소이하지만 부작용 프로파일은 매우 다양하기 때문에, 이를 섞어 쓰면 다양한 부작용이 동시다발적으로 발생할 수 있다. 약물 상호작용의 위험 역시 배가될 수 있다. 약동학적이든 약력학적이든 함께 투여되는 약물이 상호작용 할 수 있는 경우의 수는 약물의 개수에 비례하여 폭발적으로 증가한다. 또한 어떤 약물이 효과적 이었는지 결코 알 수 없다는 현실적 단점도 있다. 약물 A에 반응이 좋지 않아 B를 섞어 사용했더니 부족하나마 효과를 볼 수 있었다면, 그것이 A 때문인지 B 때문인지 판단할 수 없다. 차후에 환자가 재발했을 때 약물 A와 B 중 어느 것을 써야할 지도 지침을 얻기가 어려워진다. 이와 관련하여 가장 빈번한 다약제 투여 사례는, 의도하지 않은 채 투여하는 것이다. 원래는 약물 A를 B로 바꾸기 위해 교차 적정(cross-titration)을 하던 중 증상이 다소 호전되면, A의 효과가 뒤늦게 나타나는 것인지, B의 효과가 일찍 나타난 것인지 판단하기 어려워진다. 힘겹게 얻어낸 호전인 만큼, A와 B 중 어떤 약도 중단하기 어려워진다. 이렇게 얼떨결에 투여되기 시작한 다약제 처방이 유지치료까지 이어지는 경우가 허다하다.

임상에서 흔한 경우로 항정신병 효과를 증강시키기 보다는, 기타 증상을 조절하기 위해 다약제를 처방하는 경우가 있다. 가장 많은 예는 불면을 해결하기 위해 퀘티아핀을 처방하는 것과, 음성 증상의 개선 및 프로락틴이나 체중 증가를 조절하기 위한 목적으로 아리피프라졸을 처방하는 것이다. 또 다른 경우로는 한 가지 약제를 고용량으로 처방하면 부작용 위험이 높아질까봐, 혹은 허가 용량의 상한선에 묶여 보험제공자로부터 불이익을 당할까봐 몇 가지 약제로 나눠서 처방하는 경우이다.[@de2013] 이런 다양한 상황들 때문인지 지난 20여년간 항정신병 약물의 다약제 처방은 지침서의 보급에도 불구하고 꾸준히 증가해 왔다.[@gilmer2007; @gallego2012]

실상 두 가지 이상의 약물을 쓴다는 것은, 한 가지 약물을 고용량으로 쓰는 것과 별 차이 없다. 고용량 투여가 별반 도움이 안 되는 것처럼 다약제 투여가 우수하다는 확고한 증거도 찾아보기 힘들다.[@barnes2011; @ballon2013] 오히려 병용투여로 인한 사망위험[@waddington1998] 및 전반적인 부작용 증가[@centorrino2004], 인지기능 저하[@élie2009] 등 문제점이 꾸준히 제기된 바 있다. 메타 분석 결과를 보면, 일부 통제되지 않은 연구에서는 다약제 투여가 단일요법에 비해 전체 증상에 대한 효과가 우수한 것처럼 보였으나, 잘 통제된 연구에서는 이러한 차이를 밝히는데 실패하였다.[@galling2017] 예외가 있다면 아리피프라졸을 타 비정형 약물과 함께 투여하는 것이다. 연구 상에서도 아리피프라졸을 병용하면 음성 증상의 호전폭이 컸으며, 프로락틴 상승이나 체중 증가를 억제하는데 도움이 되었다.[@galling2017]

반면 다약제 투여를 긍정적으로 보는 학자들은 일반적인 환자에게 처음부터 다약제 투여를 할 필요는 없지만, 치료저항성을 보이는 환자라면 시도하지 않을 이유가 없다고 주장한다. 단일약제로 충분한 이상적인 세계에서는, 조현병이란 병도 단일한 존재이고 모든 항정신병 약물의 작용 기전도 동일하다. 그러나 실제 세계에서는 똑같은 조현병을 앓고 있더라도 각각의 환자는 뇌 구조 및 기능적 변화양상이 다르고, 약제가 작용할 분자적 표적도 다르다. 따라서 여러가지 약제를 사용함으로써 복수의 표적을 동시에 공략하면 표적을 맞출 가능성이 높아질 수 있다. "하나의 유전자, 하나의 질병, 하나의 약물"이라는 고전적 패러다임은 이상적 염원일 뿐이며, 질병의 정체도 약물의 작용 기전도 무엇하나 확실한 것이 없는 현실 세계에서는 가지고 있는 수단을 모두 동원하여 치료의 가능성을 높여나갈 뿐이다.[@buckley2012]

![실제 임상에서 항정신병 약제를 다약제 처방하게 되는 경우 [@buckley2012]](images/11-03/img_0.png)

### 장기지속형 주사제의 병용 투여

장기지속형 주사제를 처음 사용할 때는, 안정적인 혈중 농도에 다다를 때까지 일정 기간 이상 경구 항정신병 약물을 함께 투여하는 것이 권장된다. 그런데, 일부 환자들은 이 기간이 한참 지난 후에도 경구 약물과 주사제를 함께 사용하는 경우가 있다.[@Aggarwal2012] 한 조사에 따르면 조사 대상자의 46%가 경구 약제를 함께 복용하고 있었으며, 이중 반수 이상은 주사제와 동일 성분의 약물을 쓰고 있었다. 정형 약물의 주사제를 맞는 환자들은 경구로 비정형 약물을 투여받고 있는 경우가 많았으며, 최근에 도입된 비정형 주사제일지라도 여전히 경구제를 병용 투여하는 비율이 절반을 넘어섰다.[@doshi2015]

기존 약제에 반응이 만족스럽지 않은 상황에서 약물 순응도가 의심된다면, 치료저항성 판정을 내리기 전에 동일성분의 장기지속형 주사제를 사용해보는 것이 권장된다. 제형을 바꾸는 것만으로도 치료 반응이 나아질 수 있다. 그런데 환자가 주사를 맞으러 오지 못하는 경우가 생길 수도 있고, 또 주사제 용량만으로 부족하다고 느껴져 경구 약물을 추가할 수 있다. 상태가 불안하면 더 먹으라고 필요시 복용 약제로 처방하기도 한다. 이 경우 경구 약물과 주사제의 병행 투여이긴 하지만, 엄밀한 의미에서 다약제 처방이라고 할 수는 없다.

장기지속형 주사제를 이용한 다약제 처방 사례들은, 장기지속형 주사제를 쓸 수 밖에 없고, 또 이미 쓰고 있는 환자에서 효과가 미진할 때 다른 클래스의 경구 약물을 함께 투여하는 경우일 것이다. 주사제 효과가 미진하다는 것은 알고 있지만, 순응도 문제때문에 주사제를 포기할 수도 없는 상황이다. 이는 원리적으로는 경구 약물을 두 개이상 병행투여하는 것과 다르지 않다. 차이가 있다면 적어도 하나는 주사제를 사용하여 불안정한 순응도로 인한 문제를 최소화하는 것이다. 일단 주사제를 써서 급격한 증상 변화를 차단한 후, 여유있게 경구 약제를 이것저것 시도하여 미비한 부분을 보충한다는 전략이다. 임상에서 흔히 사용되는 전략이긴 하지만, 체계적인 임상 시험 자료가 미비하여 추가적인 연구를 요하는 바이다.

### 두 가지 이상의 장기지속형 주사제

더욱 과격한 방법은 둘 이상의 주사제를 병용하는 것이다. 치료저항성을 보이는데다가 경구 제제를 사용할 수 없는 경우가 해당될 것이다. 서로 다른 클래스의 주사제를 번갈아 투여하는 것이 보통인데, 비정형 주사제는 종류가 제한적이어서 정형 주사제와 비정형 주사제를 혼용하기도 한다. 아직은 증례 보고 정도라 임상에 추천하기는 어렵지만, 어떤 경구 약물도 거부하는 치료저항성 환자라면 고려해볼만 하다.[@Scangos2016; @Mathew2018]

## 결론

치료저항성 환자는 그 비율도 높고, 환자 및 환자를 둘러썬 가족과 지역 사회에 미치는 폐해가 이만저만이 아니기 때문에 단 얼마간의 치료 효과 차이도 가치가 크다. 단순히 완전한 관해에 도달하느냐 아니냐가 문제가 아니라, 환청이 조금이라도 줄어들고 만족스런 수면만 취하게 되도 환자도, 가족들도 안도할 수 있다.

그래서인지 치료저항성 환자의 차도를 어떻게든 낳게 하기 위해 생각할 수 있는 모든 방도가 시도되었고, 동시에 재평가되었다. 단일 약제를 사용하여 "조현병"이라는 질병을 치료하면, 제반 문제가 자연히 사라질 것이라는 기대는 교과서에서나 가능한 이상적인 그림일 뿐이다. 의사들은 가중되는 부작용과 비용의 압박, 과연 효과가 있을 것인지에 대한 불확실성을 견뎌내면서, 이런저런 조합을 시도하며, 해당 조합이 조금이나마 변화를 가져오면 쉽사리 포기하지 못한다.

그럼에도 불구하고, "이것저것 사용하다보면 언젠가는 맞는 조합이 찾아지겠지"라는 식의 주먹구구식 접근으로는 환자의 고통을 덜어주기 힘들다. 치료 반응을 얻는데 시간이 걸릴 수록, 실패한 조합이 많을 수록 환자도 가족들도, 그리고 의사 역시 치료에 대한 희망을 점점 잃어가게 된다. 따라서 비록 치료저항성 환자에 대해 증거가 충분한 치료법이 현단계에서는 존재하지 않는다 해도, 나름의 원칙을 세워 알고리듬 적으로 접근해가는 것이 바람직할 것이다. 다양한 치료 가이드라인 들은 유사한 알고리듬을 제시하고 있으며, 아래 @fig-resistant-algorithm 역시 그러한 한 가지 예이다. [@dold2014]

![치료저항성 조현병 환자의 치료 접근 알고리듬 [@dold2014]](images/11-03/img_1.png){#fig-resistant-algorithm}

## References {.unnumbered}
