---
title: "초발 정신병"
author: "정성훈"
editor: visual
bibliography: References/12-02.bib
---

## 초발 정신병의 의미

불과 얼마전까지 건강한 정신상태를 보이며, 학교나 직장에서 맡은 바 소임을 충실하게 이행하며, 가족들로부터 사랑받던 사람이, 어느 순간부터인가 망상과 환각에 휩싸이며, 현실과 환상을 구분하지 못하고, 가족들을 적으로 돌리며, 학업과 직업을 포기하게 되는 것은, 어느 누구에게도 크나큰 충격이 아닐 수 없다. 게다가 이유를 알지 못해 방황하다가, 낯선 정신과 진료실에서 누구에게도 듣고 싶지 않았던 조현병이라는 진단명을 듣게 된다는 것은 영영 끔찍한 악몽으로 기억될 것이다. 환자는 물론 가족 역시 이러한 현실을 받아들이기 어려워하며, 설마 자신에게 이런 일이 닥치리라고 전혀 예상하지 못했기 때문에, 다른 원인 다른 설명을 찾아 헤맨다. 이때문에 귀중한 치료 시기를 놓치고, 증상은 더욱 악화되며, 자기 자신과 주위 사람에게 가해진 피해는 점점 더 걷잡을 수 없어진다.

그럼에도 불구하고 역설적으로 제대로 치료받기만 하면 치료 가능성이 가장 높은 시기이기도 하며, 향후의 퇴행을 막기 위해선 결정적이자 유일한 기회이기도 하다. 암을 조기 발견하여 치료 가능성이 매우 높다는 설명을 들은 환자들은 누구나 다행이라고 가슴을 쓸어내리는 반면, 초발 정신병 진단을 받은 환자들은 치료 전망에 대한 긍정적인 설명을 들어도 그다지 달가워하지 않는다. 정신질환 그것도 조현병이란 그만큼 무거운 편견과 기피의 대상이기 때문이다.

초발 정신병 환자를 접한 의사들은 새로운 의욕에 부풀어오르면서도 동시에 앞으로 맞이할 많은 난관에 부담스러워 한다. 환자를 설득하고 질병을 교육하며, 치료 과정에 끌어들이는데는 많은 정성이 필요하다. 부작용에 익숙해진 만성 환자와는 달리, 초발 환자들은 사소한 부작용도 받아들이지 못해 중도 탈락하기 쉬우며, 고통이 완전히 사라져야 한다는 기대가 큰 나머지 약물의 미약하나마 의미있는 효과를 인정하지 않는다. 그렇다 하더라도, 어쩌면 인생의 가장 중요한 갈림길에 놓여있는 초발 환자들을 제대로 이끌어나가야 하는 책임은 온전히 의사들의 것이다.

### 진단을 둘러싼 문제

처음 조현병이 발생한 환자들은 임상 양상이 다양하고 종종 청소년기, 초기 성인기의 심리적 과제와 뒤얽혀 복잡하게 꼬여있기 때문에 진단이 어려울 수 있다. 새롭게 진학을 한다거나 군 입대, 직업 세계로의 첫 진입 등 환자를 둘러싼 사회적 상황에 변화가 많기 때문에, 전구증상들이 발견되지 않은채 단순히 상황 변화로 인한 스트레스라고 치부되기 쉽다. 정신병적 증상이 뚜렷이 드러났다 하더라도, 종적 경과에 대한 데이터가 뒷받침되지 않기 때문에 정확한 진단을 내리기 어렵다.

환자나 가족들은 정신병적 증상을 일시적인 문제로 보거나, 적응 문제로 축소화시키려 하며, 환자는 증상을 감추려 하고 가족들도 변화를 인지하지 못하는 경우가 많다. 인생의 전환기에 있다보니, 병전 기능 수준을 알기도 어렵다. 또한 이 나이는 학업에 치중하는 연령대에 속하기 때문에, 사회적 상황에서의 기능 저하를 감지하기 어려울 수 있다.

초발 환자를 보게 된 의사는 모든 가능성을 염두에 두고 진단에 임해야 한다. 초반에 조현병 양상으로 시작되었더라도 추후에 진단이 바뀌는 경우는 매우 흔하다. 또한 기질적 원인에 대한 평가가 가장 중요한 시기도 이때이다.[@thereco1999] 이후에 같은 환자가 재발했을 때 다른 의사가 보게 될 지라도 첫번째 진단을 답습하는 경우가 많기 때문에, 첫번째 진단은 그만큼 중요한 의미를 띤다.

### 초발 정신병에 대한 몇 가지 오해

크레펠린은 조현병을 만성적이고 황폐화되는 병으로 정의하였다. 그러나 초발 정신병 환자의 85%는 일단 증상에서 회복되어 병전 기능 수준을 되찾는다. 67명의 초발 조현병 환자를 13년간 추적한 연구에서 55%는 양호한 기능 수준을 보였고 마지막 2년 동안 52%는 양성 혹은 음성증상을 보이지 않았다.[@mason1995]

정신병의 급성기에는 보통 병식이 없고, 초발 환자 역시 질병을 처음 겪어보는 만큼 병식을 얻기 힘드리라 예상할 수 있지만, 자신이 정상이었을 때의 느낌을 제대로 기억하고 있다는 긍정적인 점도 있다. 이들은 자신이 변화된 것을 인지할 수 있으며, 이에 대해 그럴듯한 설명을 찾으려 한다. 아직 음성/인지 증상이 현저하지 않으므로, 증상에 적응하기 위해 다양한 전략을 시도할 수 있으며, 어떤 것이 실패였고 어떤 것이 성공적이었는지 기억할 수 있다. 따라서 질병에 대해 상세한 정보를 제공하고, 치료 계획을 세우는데 적극 참여시키는 것이 무엇보다 중요하다.

## 초발 정신병의 치료

### 기본 원칙

초발 정신병은 대부분 어린 나이에 발병하기 때문에 만성환자나 재발환자에게 접근할 때보다 조심스럽다. 약물의 효과가 만성 환자보다 우수하다고 하지만, 그만큼 다약제 사용을 줄이고, 약물 용량도 최소화하게 되는데, 과연 어느 정도까지 줄여도 될 지 지침이 없다. 정신병을 처음 겪느니만큼 교육이나 심리적 지지, 정신치료 등이 중요하게 되는데, 인지/가족 치료 등의 심리사회적 접근이 만성 환자와 어떻게 달라져야 하는 지 좀더 많은 연구가 필요하다.[@hayes2018]

Jackson과 McGorry[@thereco1999]는 초발 정신병의 일반적 치료 원칙으로 다음을 제시하였다.

1.  포괄적인 생물-정신-사회적 평가와 함께, 의사-환자 가족 간에 좋은 치료적 동맹을 맺는 것으로부터 치료가 시작된다.
2.  평가해야할 증상에는 자살과 난폭 행위의 위험도, 환경과 사회적 지지망, 병전 성격, 정신병에 대한 인식, 적응능력, 최근의 갈등 상황, 사회문화적 환경, 직업, 재정, 가족 내 문제 등이 포함된다. 평가가 끝나면 치료 결정 과정을 도와주고 치료 시작에 대한 기본적인 정보 (진단, 질환의 임상 양상, 원인, 및 예후)를 제공한다.
3.  질병의 단계를 확인한다. 초발 정신병을 급성기와 회복기로 나누고, 단계에 따라 달라지는 환자와 가족의 요구를 충족시킨다. 회복에 대한 전망을 강조하고, 정신병적 증상을 급성기에 국한시켜야 한다는 의지를 전달한다.
4.  입원은 통상적으로 안전 문제가 있을 때, 평가와 치료를 거부할 때, 가족의 지지가 부족할 때 고려된다. 특별한 문제가 없을 때는 지역사회 내에서 안전하게 치료를 시작할 수 있다.
5.  급성 발병에 선행하는 심리사회적 스트레스와 그에 대한 환자의 대처방법을 확인한다. 환청이나 망상에 반응하여 잠을 제대로 이루지 못하는 경우, 수면 부족이 또 하나의 스트레스가 될 수 있다. 이를 막기 위해 수면유지에 힘쓴다.
6.  약물 치료 뿐 아니라, 지지적 정신치료, 인지치료, 문제해결 기술, 교육 등을 통합한다. 질병 단계에 우선 순위를 융통성 있게 조절한다.
7.  치료로 인한 잠재적 위험성을 최소화한다. 치료의 목적은 가능한 한 빨리 정상적인 삶을 회복시켜 원래의 발달궤도에 되돌려놓는 것이다. 과도기에 놓여있는 환자의 인지적, 정서적, 사회적 성장을 가로막을 수 있는 치료법은 피한다. 치료는 치료자의 기준이나 가치가 아닌 환자 개인의 요구와 목표에 맞추어서 제공되어야 한다.

### 심리사회적 치료

정신 증상의 관리 뿐 아니라, 사회적 기능 손상, 물질남용과 자살 등을 모두 포괄하는 복합적인 서비스가 제공되어야 한다.[@galletly2016] 호주의 EPPIC[^12-02-1], 노르웨이 · 덴마크의 TIPS[^12-02-2] 등의 종합관리모델이 잘 알려져 있다. 미국에서는 NIMH 주도로 초발 정신병 대한 개입 연구 (Recovery After an Initial Schizophrenia Episode, RAISE)를 통해 포괄적인 치료 프로그램 ([NAVIGATE](https://navigateconsultants.org/))이 개발되었다.[@mueser2015] 일반적으로 다직종 구성원이 포함된 팀이 치료에 개입하며, 환자 본인 및 가족에게 질병 및 약물 교육, 회복력을 높이는 인지습관 강화, 취업 및 취학 지원 등이 제공된다. 동시에 치료를 둘러싼 의사결정에 적극 참여하도록 격려한다.

[^12-02-1]: **Early Psychosis Prevention and Intervention Centre (EPPIC)**: 호주 멜버른에서 시작된 청소년과 초기 청년기의 정신병 환자에게 특화된 정신건강 서비스. 1993년 멜버른 의과대학에 다니던 Patrick McGorry가 주축이 되어 빅토리아 주정부의 지원을 받아 설립되었다. 기존에 존재하던 Aubrey Lewis Unit와 Nightingale Recovery Program을 통합하여, 초발 정신병 환자들의 조기 진단, 질병악화 예방, 사회적/직업적 기능의 유지를 목적으로 하였다.[@mcgorry1993; @edwards1994] 이후 전세계에서 유사한 초발 정신병 환자 지원 프로그램이 등장하는 기폭제가 되었으며, 심대한 영향을 끼쳤다. 현재는 [Orygen Specialist Program](https://oyh.org.au/)에 통합되어 멜버른 지역의 15\~25세 환자들에게 서비스를 제공하고 있다.

[^12-02-2]: **Treatment and Intervention in Psychosis Study (TIPS)**: 원래 스캔디나비아 각국의 다기관이 참여했던 연구로, 정신병의 조기 발견 프로그램의 홍보와 교육이 치료받지 않은 기간(duration of untreated psychosis)을 줄일 수 있는지 확인하고자 하였다.[@johannessen2000] 이 연구는 그대로 [정신보건 서비스](https://www.tips-info.com/)로 연계되어 현재까지도 운영되고 있다.

    Scandinavian early Treatment and Intervention in Psychosis Study (TIPS)

초발 정신병 환자는 대부분 진단을 받아들이기 힘들어하여, 이 때문에 치료가 지연되거나 조기 중단되는 경우가 많다. 따라서 초발 환자를 대상으로 한 치료 프로그램에는 질병 교육 및 치료 동맹의 수립, 진단 및 치료의 수용 그리고 적극적 참여에 대한 내용이 강조된다. 인지 치료에는 증상으로 말미암아 왜곡되어버린 세상을 바라보는 시각을 교정하고 이성적으로 해석하는 내용과 함께, 쉽게 없어지지 않는 정신병적 증상에 대처하는 내용이 포함된다. 가족치료는 구성원 자신이 받은 충격을 해소하고, 발병에 기인했거나 회복을 막는 유해한 가족환경을 개선하며, 낯설어지고 불편해져버린 환자를 중립적으로 대하는 기술을 습득하는 데 중점을 둔다.[@schennach2012]

혹자는 초발 환자의 높은 반응성과 약물 치료에 동반되는 부작용을 고려하여, 초발 환자를 일찍 찾아내기만 한다면 약물 치료없이 심리사회적 치료만으로도 회복에 이르게 할 수 있다고 주장한다. Davies 등[@davies2018]은 네트워크 메타 분석을 통해 각종 약물 치료와 심리사회적 개입 사이에 우열을 가릴 수없었다고 하였으며, 다른 연구에서도 적어도 심리사회적치료가 약물 치료에 비해 열등하다는 증거는 없다고 한다.[@francey2020] 심리사회적 개입은 주로 인지행동 치료 + 가족 치료로 이루어지며, 질병 교육, 사회기술 훈련, 물질사용 등 특정 증상에 대한 개입등 다양하게 구성된다.[@ochoa2015] 그러나 약물치료 없이 심리사회적 치료만으로 충분하다는 결론은 내리기 어렵다. 대부분의 연구는 소규모로 이루어졌으며, 치료센터를 중심으로 한 특정 인구집단에 집중되어 일반화하기 어렵다. 게다가 센터마다 제공하는 심리적 개입의 내용이나 구성, 환경이 달라 "심리사회적 치료"라는 하나의 범주로 통일시키기도 어렵다.[@morrison2020; @gergov2022]

### 약물 치료

#### 일반적 사항

초발 조현병과 반복 재발한 조현병은 약물치료에 대한 반응이 다르다. 게다가 약물치료에 대한 첫경험이 이후 평생동안 이어지는, 질병과 치료에 대한 태도, 정신보건 전문가와의 상호작용에 영향을 줄 수 있다.[@robinson2015]

초발 환자에 항정신병 약물을 처방할 때 다음 사항을 고려할 수 있다.[@dixon2015]

1.  초발 정신병 환자는 부작용에 매우 민감하기 때문에, 용량을 최소화하며 병용 투여 역시 가급적 피한다. 예를 들어 Schizophrenia Patient Outcomes Research Team (PORT) 지침서는 초발 환자에서는 반복해서 재발하는 환자에게 권장되는 용량의 절반 이하를 사용하라고 권고한다.
2.  다중약물요법은 효과에 대한 근거가 부족하고 부작용, 불량한 순응도, 약물상호작용의 위험을 증가시킬 수 있다. 치료저항성을 보이는 경우에는 항정신병 약물 병용보다는 클로자핀을 사용한다.
3.  그러나 클로자핀과 올란자핀을 일차 치료제로 선택하지는 않는다. 첫 발병한 젊은 환자에게 대사성 부작용의 부담이 클 수 있다. 다만 올란자핀이 매우 효과적인 약이기 때문에, 급성기에 올란자핀으로 안정화시킨 후 다른 약물로 교체하는 전략을 사용할 수 있다. 아쉽게도 이를 뒷받침하는 체계적인 연구 자료는 없다.
4.  치료 약물을 선택할 때 환자 및 가족을 주도적으로 참여시킨다. 약물 선택이나 용량 결정에 충분한 정보를 갖고 주도적으로 참여한 환자가 더 효과도 좋고, 부작용이 생겼을 떄도 잘 대처해나갈 수 있다. 그럼으로써 필요없는 약물 교체를 피할 수 있다.
5.  항우울제는 대개 음성증상이나 우울, 자극과민 등이 있을 때 항정신병 약물에 부가적으로 사용한다. 특히 처음 정신병을 겪는 충격때문에 우울/자살사고를 보이는 환자에게는 예방 차원에서 사용하기도 한다.[@tiihonen2012] 그러나 효과에 대한 근거는 희박하다. 조현병 환자에게 나타나는 우울 증상은 정상 심리반응이고, 심하지 않은 증상은 정신병적 증상이 가라앉으면 호전되기 때문에 항우울제를 사용할 필요가 없다는 주장도 있다. 항우울제가 음성증상에 효과가 있는지는 불분명하다.

Robinson 등[@robinson2015]은 미국 전역의 지역정신보건센터에서 조현병 초기 단계에서 어떤 약물치료가 시행되고 있는지를 분석했는데, 진료 지침을 엄격히 준수하지 않는 것으로 나타났다. 8.8%의 환자는 권고 용량보다 더 높은 용량을 처방받았고, 32.1%는 일차 약물로 올란자핀을 처방받았으며, 23.3%는 한 가지 이상의 항정신병 약물이 처방되었다. 36.5%는 명확한 적응증 없이 항우울제가 병용되었다. 이러한 현상에는 연령, 성별, 인종, 보험 상태가 영향을 미치고 있었다.

지침서를 따르지 않는 처방은, 환자의 불량한 치료 순응도와 물질남용 등에도 영향을 받았다.[@young1998] 물론 지침을 따르지 않은 처방이 특정 환자에게 최선의 처방일 수도 있다. 그러나 의학 외적인 편견에 휩싸여서는 안된다.

#### 약물 순응도

Whale 등[@whale2016]의 대규모 초발 정신병 코호트 연구에서 처음 처방된 항정신병 약물의 73.3%가 어떤 이유에서든 1년 내에 중단되었으며, 치료 개시 후 첫 3개월 내에 중단되는 경우가 가장 흔하였다. Tiihonen 등[@tiihonen2011]의 연구에서도 치료 시작 한달 내에 절반이 넘는 환자가 약물을 중단하였으며, 평균 2년을 추적했을 때 92.5%가 결국 약물을 중단하였다. 따라서 초발 정신병 환자의 비순응은 너무나 일반적인 현상으로 볼 수 있다.

앞에서도 여러번 강조했지만, 순응도를 높이는 방안의 하나로 공유 의사결정(Shared Decision Making, SDM)이 강조되고 있다.[@simmons2012] 치료가 왜 필요한지, 증상이 가라앉은 후에도 왜 치료를 계속해야 하는지 등에 대한 질병교육을 통해 환자와 치료자가 치료 목표와 필요한 정보를 공유할 때 순응도가 향상될 수 있다.[@kane2013]

장기지속형 주사제 (LAIs)를 사용하면 확실히 순응도를 높일 수 있다. 그러나 주사제 사용을 결정하는 과정 역시 환자 및 가족과의 활발한 정보교환을 통해 환자로 하여금 스스로 주사제를 선택할 수 있도록 유도해야 한다. 별다른 설명없이 반강제로 주사제를 사용하는 것은 오히려 치료 동맹을 위험에 빠뜨릴 수 있다.

#### 약물의 적정 용량과 사용 기간

약물치료 경험이 없는 초발 정신병 환자는 약물 효과나 부작용에 대해 얼마나 민감한 반응이 나타날 지 짐작할 수 없다. 따라서 재발 환자에 비해 훨씬 천천히 적정하게 되는데, 이 때 환자와 치료자의 인내가 필요하다. 이는 임상의사에게 이중의 어려움을 부과한다. 비교적 빠른 시간 내에 가시적인 효과가 나타나야 환자에게 치료의 필요성을 납득시킬 수 있는데, 너무 성급하다보면 부작용 때문에 오히려 환자를 놓치게 된다. Lieberman [@lieberman1993]은 초발 정신병 환자를 치료할 때는 치료 개시 후 수개월이 지나도 약물의 최대 효과에 다다르지 못할 수 있다고 하였다. 성급한 증량이나 병용 투여 습관은 오히려 단점이 더 많다. 보조 약물의 투여는 치료 초기에 보이는 수면장애, 초조/불안, 자극과민을 조절하기 위해 사용한다. 증상이 완화되면 보조 약물이 꼭 필요한 지 여부를 평가해야 하며, 가급적 항정신병 약물 단독요법을 권장한다.

대부분의 조현병 치료지침은 초발 정신병 증상이 관해된 시점을 기준으로 그로부터 1년 이상 유지치료를 할 것을 권하고 있다. 장기 임상시험이라고 해도 대부분 2년 이하에 국한되었기 때문에 그 이후의 장기 치료 효과는 아직 불분명하다. Wunderink 등[@wunderink2013]은 유지치료를 한 군과 하지 않은 군을 7년간 추적조사하였다. 1.5년 후의 재발률은 치료중단군이 2배 이상 높았으나, 7년 후에는 오히려 치료중단군의 회복률이 더 높았다. 이 연구는 연구 디자인이나 해석에 있어 많은 논란을 불러일으켰으나, 무작정 유지치료를 지속하는 것만이 능사는 아니라는 것을 보여주고 있다. 기능 회복이나 삶의 질을 무시하고, 재발률만을 고려하면 예외없이 유지치료군의 성적이 양호하였다.[@thompson2018] 그러나 어느 쪽의 비중을 더 높게 고려할 지는 의사와 환자의 가치관에 맡길 수 밖에 없다.

#### 초발 환자에서의 클로자핀 사용

초발 환자가 아무리 치료 성과가 좋다고 해도, 일정 비율의 환자는 치료저항성을 보인다. 치료저항성은 실패한 치료의 결과라기 보다는, 애초에 환자가 갖는 특성일 때가 많기 때문에, 초발일 때 치료저항성을 보이는 환자는 이후에도 계속 저항성을 보일 여지가 크다. 따라서 일부 진보적인 의사들은 초발 환자에게도 치료저항성의 징조가 나타나면 가능한 빨리 클로자핀을 사용할 것을 권장한다.[@remington2013; @demjaha2017] 보다 온건한 의사들 역시 적어도 두 가지 이상의 항정신병 약물 치료에 반응하지 않았을 때, 그리고 초기부터 자살위험성이 높게 평가되는 환자에게는 좀더 빨리 클로자핀을 사용하는 것을 권하고 있다. 최근의 의사들은 초발 환자라도 과거보다는 좀더 적극적으로 클로자핀을 권하는 추세이다.[@rowntree2020]

#### 초발 정신병 환자의 재발

초발 정신병 환자가 한번이라도 재발하면 이미 초발 환자가 아니게 된다. 조현병 연구에서 초발 환자가 차지하는 지위가 워낙 유별난지라, 초발 환자가 더 이상 재발하는 것을 막으려는 데 많은 관심이 집중되고 있다. 따라서 초발 환자의 지위를 잃게 되는 재발을 정의하는 것부터 신경을 많이 쓸 수 밖에 없다. Csernansky 등[@csernansky2002]은 정신과 입원, PANSS 총점의 25% 이상 증가 또는 기존 점수가 40점 이하인 경우 10점 이상 증가, 자해/타살의 충동, 난폭한 행동으로 인한 타해 또는 기물 손상, CGI 변화가 6 또는 7에 해당하는 경우를 재발로 정의하였다. Schooler 등[@schooler2005]은 일단 PANSS 총점이 기저치의 20% 이상 감소한 유의미한 반응을 보였던 환자가 Csernansky 등이 제시한 상태가 되었을 때를 재발로 정의하였다. 대한조현병 학회는 좀더 자세한 기준을 내놓고 있다.[^12-02-3] 재발을 논하기 전에 적어도 2개월 이상 관해상태를 유지한 적이 있어야 하며, 이러한 환자가 증상 악화로 인해 입원, CGI-S가 2점 이상 증가하여 4점 이상이 되었을 때, CGI-I가 6점 이상, PANSS의 4가지 정신병 증상 항목 (P1, P2, P3, P6) 중 어느 하나라도 2점 이상 악화되어 4점 이상이 된 경우, PANSS 총점이 25% 이상 상승하거나 40점 이하였던 경우 10점 이상 상승한 경우, 의도적인 자해행동이 있거나, 임상적으로 심각한 자살/타살 사고가 생긴 경우, 난폭한 행동에 의해 타인이나 소유물에 손상을 입힌 경우 중 어느 하나라도 해당되었을 때를 재발로 정의한다.

[^12-02-3]: [초발 정신증 임상 평가에 관한 진료지침서](https://www.guideline.or.kr/guide/view.php?number=1074&cate=A) (대한조현병학회 임상진료지침 개발위원회 한국조기정신증연구, Korea Early Psychosis Study)

재발의 대다수는 유지 치료를 더 이상 하지 않을 때 일어나지만, 환자 다섯 명 중 한 명은 꾸준한 유지치료에도 불구하고 첫 치료 후 2년 이내에 재발한다. 이를 breakthrough psychotic symptoms[^12-02-4]이라고 한다. 핀란드에서 이루어진 한 연구에서는 LAI로 유지치료 중인 환자 100명당 1년에 12회 정도 재발이 발생했는데 재발 위험은 연령과 반비례하였다.[@rubio2020] Emsley 등[@emsley2020] 역시 LAI 로 치료 중인 초발 조현병 스펙트럼장애 환자를 2년 관찰했을 때 21%가 재발하여, LAI로 치료 중인 만성 환자의 재발률 18.3%보다 오히려 높았다.[@alphs2016 ]

[^12-02-4]: Rubio와 Kane[@rubio2017]은 이를 psychosis Breakthrough on Antipsychotic Maintenance Medication (BAMM)이라고 표현하였다.

#### 초발 정신병 환자의 회복

환자가 가족이 듣고 싶어하는 회복의 기준은, 앞으로 약을 먹지 않아도 더 이상 재발하지 않는다는 보장일 것이다. 암의 경우 5년 간 재발없이 관해상태를 유지했다는 것은 이러한 의미를 내포한다. 그러나 조현병의 질병 특성을 알고 있는 어떤 의사도 그런 선언을 할 수는 없다. 이렇게 보면 아무리 초발 환자라도 회복은 불가능하다는 뜻이 되는데, 연구자들은 대신 재발에 대한 언급 대신 삶이 질을 얼마나 되찾았느냐를 기준으로 회복의 기준을 완화시켰다.

McGlashan[@mcglashan1984]은 직업을 가지고 있고 증상이 없거나 가족과 사회적으로 의미 있는 관계를 유지하는 경우를 회복으로 정의하였다. Torgalsboen[@torgalsbøen1999]은 5년 이상 병원 밖에서 생활했고 정신사회적 기능이 정상 범위에 해당하며 (GAF 65점 이상) 약을 복용하지 않거나 정의된 일일 용량의 절반 이하만 복용 중인 경우로 정의하였다. 근래에 접어들면서 회복의 정의가 조금씩 완화되면서, 구체적이 요건이 추가되고 있다. Liberman 등[@liberman2002]은 1) 증상 관해: 지난 2년 동안 BPRS의 양성 및 음성증상 항목에서 4점(moderate) 이하로 유지되고, 2) 직업 기능: 지난 2년 동안 적어도 절반의 시간 동안 학업/직업 면에서 성공적으로 활동했고, 3) 독립적 생활: 가족이나 다른 보호자의 감독 없이 독립적인 생활이 가능하며, 4) 교우 및 사회 관계를 유지할 때를 회복으로 정의하였다.

대한조현병 학회는 완전 회복과 부분회복을 나눠서 정의하였다. 완전 회복은 최소 1년 내지 2년 이상 PANSS의 정신병 항목 (P1, P2, P3, G5, G9)과 음성증상 항목 (N1, N4, N6) 모두가 2점 이하, GAF 71점 이상, 적절한 사회적 기능이 유지될 때 (아는 사람과 한 달에 2회 이상 능동적으로 만날 때), 적절한 직업기능이 유지될 때 (기준이 되는 기간의 절반 이상 동안 취업을 하거나 또는 구직 활동을 할 때, 학생과 주부는 각각 학업과 가사 일을 적절히 감당할 수 있을 때)를 말한다. 부분 회복은 동일한 기간 앞서 열거한 PANSS 관련 항목이 3점 이상, GAF 61점 이상, 기준 기간의 ⅓ 이상 적절한 직업기능이 유지될 때를 의미한다.[^12-02-5]

[^12-02-5]: [초발 정신증 임상 평가에 관한 진료지침서](https://www.guideline.or.kr/guide/view.php?number=1074&cate=A) (대한조현병학회 임상진료지침 개발위원회 한국조기정신증연구, Korea Early Psychosis Study)

## 초발 정신병의 예후

### 약물 치료 결과

초발 환자가 재발 환자에 비해 치료 성과가 좋다는 것은, 좀더 반응률이 높고, 낮은 용량 단일 항정신병 약물에 반응할 가능성이 높으며, 관해/회복에 도달하는 비율이 높다는 뜻이다.[@lieberman1993; @jäger2006] 이러한 양호한 반응이 1) 낮은 연령, 2) 짧은 정신병의 비치료기간(DUP, article-01-06.html# 6-1-1 절), 3) 항정신병 약물에 최소 노출 중 어느 것 때문인지는 확실하지 않다. 그러나 반응이 좋은 것이 재발을 적게 한다는 의미는 아니다. 아무리 빨리 환자를 선별해내고, 그럼으로써 정신병의 비치료기간을 줄이고, 조기에 적극적인 약물치료를 통해 조속히 관해상태를 이끌어냈다고 해도, 그것이 만성 경과를 의미있게 변화시키는지는 더욱 더 많은 연구가 필요하다.

결국 만성 경과를 좌우하는 데는 질병 초기부터의 적극적인 개입과 유지치료의 지속이 가장 큰 영향력을 행사했으며, 이외에도 물질사용의 동반, 가족 및 주위 지지체계의 붕괴가 영향을 끼쳤다.[@alvarez-jimenez2012; @lally2017] 앞서 소개한 Wunderink 등[@wunderink2013]의 결과와는 대조적으로 무작위 배정 임상시험에서 1년 내에 유지 치료를 중단하면, 10년 후 임상 결과가 불량했다는 보고도 있다.[@hui2018] 심지어 조심스레 선택된 환자에게 의사가 먼저 권유해서 약을 끊었던 경우에도 잘반 이상이 재발하였다.[@üçok2020] 물론 회복 여부 및 장기 예후는 약을 끊고 안 끊고와 같은 외적 요인보다는 환자 자신의 생물학적 특성에 크게 좌우되는지도 모른다. 영국에서 행해진 AESOP 연구에서는, 초발 정신병 환자 표본 중 12.5%에 해당되는 특정 환자군은 평균 53일 정도의 치료만 받고도 관해에 이르렀는데, 그럼에도 불구하고 회복 상태를 10년 이상 잘 유지했다고 하였다.[@lappin2018] 이와는 대조적으로 초발 정신병 환자의 1/4 정도는 처음부터 치료저항성을 나타내어 관해 자체를 달성하기 힘들었다는 보고가 있다;.[@lally2016; @demjaha2017]

### 인지/음성 증상의 치료 및 경과

치료가 제대로 되지 않고 정신병적 증상이 오래 지속되면서 인지/음성 증상이 서서히 악화되는 것인지, 아니면 병의 초반, 심지어 발병 전부터 인지/음성 증상이 자리잡기 시작하는 것인지에 대해선 논란이 끊이지 않고 있다. DUP를 줄이기 위해 애쓰는 초발 정신병 연구자들은 진행형인 질병 과정이 점점 더 인지/음성 증상을 악화시킨다고 믿고 있지만 , 초발 환자 중 다수가 이미 상당한 인지기능 저하를 보이고 있는 것도 사실이다.[@dequardo1994; @mohn-haugen2022] 그뿐만 아니라 발병직전까지 점점 더 정상대조군과 인지기능의 격차가 벌어지게 된다.[@fuller2002]

따라서 초발 환자를 치료하는 경우에도 이미 인지/음성 증상에 대한 대책이 필요하다. 초발 환자에게 비정형 약물이 일차약제로 추천되는 것은 적어도 인지 증상을 악화시킬 가능성이 가장 적기 때문이다. 비정형 약물이 다양한 인지개선 효과가 있다는 보고는 이어지고 있으나, 인지 영역마다 효과가 다르고 그다지 일관되지도 못하다.[@meltzer1999] 한편 비정형 약물이라 하더라도 고용량 투여 시 인지기능을 저하시킬 수 있다.[@ballesteros2018] 과감한 약물 투여로 재발을 막아야할런지, 온건한 치료를 통해 인지 기능의 보전을 우선시해야할런지는 영원히 풀리지 않는 과제이다.[@karson2016]

질병 경과에 따라 인지기능의 저하가 어느 정도로 진행되는지 역시, 치료의 결과인지 타고난 생물학적 특성인지는 분명하지 않다.[@wells2015] 인지기능의 저하를 최소화한다고 해서 재발의 가능성을 줄이는지는 분명하지 않지만, 적어도 사회적/직업적 기능을 지키는데는 지대한 영향을 미칠 것이다. [@kharawala2022] 특히 초발 환자들의 인지기능 저하를 막는 것은 향후 평생에 걸쳐 기능과 삶의 질을 유지하는데 필수적이므로, 소극적인 약물치료보다 적극적인 인지재활 치료를 필요로 할 수도 있다.[@sampedro2021; @gergov2022]

## References {.unnumbered}
