---
title: "인지 증상의 치료"
editor: visual
bibliography: References/13-05.bib
---

## 인지 기능에 악영향을 미치는 요인의 최소화

조현병의 인지 증상을 치료하기 전에, 인지 기능 발휘에 악영향을 미치는 약물을 최소화하는 것이 먼저이다. 전통적으로 조현병 치료는 항정신병 약물을 중심으로 하나, 항우울제, 기분조절제, 벤조디아제핀 등 다양한 약물을 병용 투여하며, 이들은 모두 인지 증상에 부정적인 영향을 미칠 수 있다. 비정형 항정신병 약물이 등장했을 때만 해도 인지 증상을 치료할 수 있다는 구호가 요란했으나, 실제 성과는 적어도 인지 증상에 악영향을 미치지 않는다는 정도에 그칠 뿐이었다. 그러나 그 차이가 미미해보일 지라도, 실제 환자들의 기능 발휘와 삶의 질에는 지대한 영향을 끼쳤다.

### 항정신병 약물

정형, 비정형 구분을 넘어서 항정신병 약물이 직접 인지 기능을 개선시킨다는 증거는 없지만, 정형 약물이 인지 기능을 악화시킬 가능성은 매우 높다. 항정신병 약물의 D~2~ 및 5-HT~2A~ 수용체 차단 효과는 결국 글루타메이트 신호전달과 함께, 중뇌피질의 도파민 신호를 저하시킨다.[@honey1999] 전통적으로 항정신병 약물을 고용량으로 쓰거나, 다수의 약을 섞어 쓰는 것을 꺼리는 것은 인지 기능에 미치는 악영향이 가중되기 때문이다.[@élie2009; @takeuchi2013; @joshi2021] 물론 양성 증상을 적극 조절함으로써 단기간의 인지 개선 효과를 꾀할 수 있다는 반론도 있지만[@mishara2004; @woodward2005], 그 효과가 수년 이상 지속될 수 있을 지는 의문이다. 설령 항정신병 약물이 직접적으로 인지 기능을 악화시키지 않는다 하더라도, 약물에 의한 주관적 불쾌감이나 신체적 컨디션 악화 등은 동기와 의욕을 떨어뜨려 인지 기능의 발휘를 가로막을 수 있다.[@moritz2013] 따라서 항정신병 약물은 그 순기능 보다는 얼마나 악영향을 덜 미치는가가 먼저 논의되어야 한다. [@husa2017]

도파민 활성 저하에 의한 인지 기능 저하는, 정형 약물의 피할 수 없는 부작용이다. 동물 실험은 물론 건강한 자원자를 대상으로한 실험에서도 정형 항정신병 약물은 작업기억, 처리속도, 반응 속도 및 고위 인지 기능에 악영향을 끼친다.[@arnsten1995; @ramaekers1999] 도파민에 대한 효과 뿐 아니라, 저역가 약물이 공통적으로 갖는 항히스타민, 항콜린 효과 등도 인지 기능을 저하시킨다. 물론 이러한 악영향은 용량과 비례하기 때문에, 용량을 세심하게 조절함으로써 최소화할 수 있다.

비정형 약물은 5-HT~2A~에 대한 효과로 말미암아 도파민 차단 효과의 충격을 최소화한다. 추체외로 증후군의 발생을 극적으로 억제했듯이, 전두엽에서의 도파민 차단 효과도 상대적으로 적다. 비정형 약물의 대부격인 클로자핀은 아예 D~2~ 수용체 점유율이 타 약물보다 현저히 낮다. 또한 비정형성에 대한 조기 해리 가설(fast-dissociation hypothesis)에 따르면 약물 복용 직후 순간적으로 D~2~ 차단율이 상승한다 할 지라도 금새 다시 낮아진다.[@Kapur2001]

비정형 약물이 인지 기능 개선 효과에 있어 정형 약물보다 장점이 많은 게 분명해보였다.[@meltzer1999; @bilder2002; @woodward2005; @harvey2005; @keefe2006] 자연스럽게 비정형 약물이 인지기능 개선을 통해 일상 생활을 되돌려주고, 삶의 질을 높일 것이라는 기대감이 높아졌다. 이러한 전제 하에, 5-HT~1A~ 부분 효현 작용이나 D~1~ 수용체에 대한 작용이 인지 개선의 메카니즘으로 제시되기도 하였다.[@meltzer2008] 적지 않은 연구들은 비정형 약물에 의해 호전되는 특징 인지 영역을 찾고자 애썼으며, 똑같은 비정형 약물 중에서도 좀더 효과적인 약물을 골라내고자 하였다.[@désaméricq2013; @nielsen2015]

그러나 모든 연구결과가 비정형 약물에 지지적인 것은 아니었다. 제약회사의 재정적 지원을 받지 않은 대규모 연구인 CATIE 연구[@keefe2007]와 CUtLASS 연구[@barnett2007]에서는 정형 약물과 비정형 약물의 인지 개선 효과에 차이가 없었다. 오히려 CATIE 연구에서는 perphenazine이 리스페리돈, 올란자핀에 비해 인지 개선 효과가 컸다고 보고되었다.[@keefe2007] 그러나 앞에서 언급했듯이 낮은 용량의 정형 약물은 인지 악화 효과가 거의 없기때문에 비정형 약물과 큰 차이가 나지 않는 것이 당연할 것이다.[@tandon2007; @leucht2008] 정형과 비정형 약물을 비교한 가장 최근의 메타 분석에서도 클로자핀만이 인지 개선에 효과적이었다.[@takeuchi2017] 정형 약물에 의한 인지 저하 효과 역시 단기간에 그치는 것이라 장기적 관점에서는 별반 문제가 되지 않는다. Zanelli 등[@zanelli2019]은 초발 환자를 10년 이상 추적하여 항정신병 약물이 지능 저하에 미치는 영향을 조사하였는데, 정형 약물과 비정형 약물 간의 차이는 없었고, 약물 사용 기간도 지능 저하와 아무런 상관관계를 보이지 않았다.

이상의 결과를 종합하면, 항정신병 약물에 의한 인지 기능 저하는 약물 투여 후 단기간에 집중되며 장기적 경과에는 큰 악영향을 미치지 않는다. 따라서 단기간에는 비정형 약물이 훨씬 유리하나 장기적 시점에서는 정형/비정형의 차이가 그다지 두드러지지 않는다. 약물의 악영향 뿐만 아니라 순기능 역시 질병 경과의 영향을 받을 수 있다. 초발 환자를 대상으로 한 연구결과를 종합해보면, 항정신병 약물에 의한 인지 개선 효과는 첫 수개월에 집중되며 약 1\~2년까지 지속되고, 그 이후에는 더 이상 개선이 없어보인다.[@keefe2014; @trampush2015] 초발 삽화 치료 후 인지 증상 개선 정도는 이후 예후를 추정하는데 중요한 요인이다. 보다 적극적으로 항정신병 약물을 써서 양호한 치료 결과를 얻었을 때 인지 기능도 덩달아 호전되었다는 보고가 있기도 하다.[@gold1999] 하지만 호전 정도가 미미하고 치료 초반에만 국한되어, 양성/음성 증상 호전에 기인한 2차적 호전일 뿐이라고 폄하되기도 한다. 심지어 얻어진 호전이, 단순히 인지 검사를 반복해서 생기는 학습효과에 지나지 않느냐는 반론도 있다.[@goldberg2007]

이처럼 약을 소극적으로 써서 악영향을 줄여야할지, 적극적으로 써서 인지 기능 회복을 이끌어내야 할 지 결론이 나지 않기 때문에, 유지 치료 용량을 결정하는 것은 여전히 까다로운 문제이다.[@omachi2018] 대부분 학자들은 용량 혹은 혈중 농도와 인지 기능 사이에는 역상관의 관계가 있다고 여기며, 인지 기능을 지키기 위해서는 최소 용량을 쓰는게 맞다고 여긴다.[@husa2017] Takeuchi 등[@takeuchi2013]은 무작위 개방형 연구를 통해 리스페리돈과 올란자핀을 감량했을 때, PANSS 총점은 별 변화가 없었던 반면 인지 기능은 유의하게 호전되었다고 보고하였다. 아무래도 초발일 때는 과감하게 약물을 사용하여 양성 증상을 최대한 빨리 조절한 후, 이후에는 최소한의 용량만으로 유지하는 것이 인지 기능을 지키는데 이상적일 것이다. 그러나 유지 치료가 재발을 막지 못하다면, 이런 모든 노력이 허사가 될 가능성이 높다.

### 항콜린성 약물

항콜린 효과는 예외없이 인지 기능에 악영향을 끼친다. 건강한 사람이 한두번 복용해도 주의력, 집행 기능, 기억력이 떨어지며, 용량이 과하면 환각과 망상을 포함한 섬망 증상을 일으킬 수 있다.[@effects1987; @egberts2021] 또한 항콜린성 약물의 장기간 사용이 알츠하이머 치매의 위험을 높인다는 보고도 있다.[@coupland2019; @joung2019]

정형 약물 사용 시에는 항콜린성 약물을 예방적 차원에서 장기간 사용하는 것이 권장되기도 하였으나, 인지 증상에 대한 악영향 때문에 최근의 치료 지침에서는 더 이상 장기 사용이 권고되지 않는다. 추체외로 증상을 조절해야할 때만 국한해서 사용하되 증상 변화를 추적하면서 점진적으로 줄여 나가야 한다. 다만 조기 정신병 환자는 급성 추체외로 증상의 발생 위험이 더 높고, 한번 추체외로 증상을 경험하면 이후 약물 순응도가 반감될 위험이 있으므로, 예방 차원에서 항콜린성 약물을 지속적으로 사용해야할 경우도 있다.[@ogino2013]

### 벤조디아제핀

벤조디아제핀 역시 인지 기능 특히 기억력에 부정적인 영향을 미친다. 장기간의 벤조디아제핀 사용이 치매를 유발할 지도 모른다는 우려는 2012년 Gallacher 등[@Gallacher2012]에 의해 최초로 제시되었다. 이는 열띤 사회적 논란을 불러왔고, 수면제나 안정제에 대한 부정적 시각이 우세해졌다. 연구자들의 주장 역시 첨예하게 대립하였다. 물론 이 주장이 제기되기 이전에도 장기간(평균 10년 이상)의 벤조디아제핀 사용이 인지 장애와 관련이 있다는 메타분석 결과[@barker2004]가 있었고, 이러한 환자들의 벤조디아제핀 사용량을 줄였더니 인지가 개선되었다는 보고가 있었다.[@baandrup2016] 벤조디아제핀을 복용하고 있는 동안 기억력이 감퇴하는 것은 이론의 여지가 없어보인다. 그보다 문제는 이러한 영향이 가역적이냐 아니면 비가역적이냐이다.

가장 최근의 잘 설계된 대규모 연구에 따르면, 기분 장애로 진단받고 오랜 기간 벤조디아제핀을 투여받은 환자들을 평균 6년에 걸쳐 추적 조사하였을 때 약물 사용과 치매 진단 간에는 아무런 연관성이 관찰되지 않았다.[@Osler2020] 조현병 환자에 있어서도 벤조디아제핀 및 항우울제의 누적 사용량과 인지 기능 사이에는 유의한 상관관계가 발견되지 않았다.[@Hulkko2017] 불안과 수면 부족은 조현병 환자 뿐 아니라 정상인에서도 인지 기능을 저하시키는 요인이며, 수면 부족은 그 자체가 독립적인 치매의 위험 요소이다.[@sabia2021] 따라서 벤조디아제핀은 단기기억 감퇴효과에도 불구하고, 불안과 수면 장애를 호전시킴으로써 인지 기능에 긍정적 효과를 가져올 수 있다.

### 기분조절제

치료저항성 조현병의 병용 투여 전략으로 흔히 사용되는 리튬 역시 긍정적 효과와 부정적 효과를 모두 가지고 있다. 리튬 치료를 받은 양극성 장애 환자를 6년간 추적했을 때 정신 운동과 언어 기억에 문제가 생겼다는 보고가 있다.[@mora2012] 그러나 이런 효과가 양극성 자체 때문인지, 갑상선 기능 저하에 따른 것인지 여전히 불확실하다.[@paterson2017]

긍정적 효과가 있다는 주장도 있지만 선뜻 받아들이기는 어렵다. 리튬 단독요법으로 안정된 양극성 장애 환자는 전반적인 인지, 지연회상, 선로잇기 검사 등이 유의하게 향상되었다는 보고가 있다.[@burdick2020] 양극성 장애 역시 조현병 만큼이나 인지 기능 저하를 동반하는 경우가 많기 때문에, 이러한 긍정적 효과는 큰 의미가 있다. 일부 학자들은 리튬이 신경퇴행성 질환에서 신경보호작용을 하기 때문에, 정신질환 환자에 있어서도 신경가소성의 향상 등을 일으킬 수 있다고 주장한다.[@Forlenza2014] 그러나 단순히 기분이 안정되면서 인지기능 검사의 수행 성적이 좋아졌을 가능성이 있다. 조현병 환자의 인지 기능에 미치는 리튬의 영향은 아직 불확실하다.

### 항우울제

항우울제는 전통적으로 조현병 환자의 음성 증상을 개선하기 위해 사용되어 왔으며, 제한적이나마 일부 효과를 거두고 있다.[@singh2010] 주요 우울장애 환자를 대상으로 연구를 해보면, 항우울제 치료에 의해 우울 증상이 개선되면 확실히 정신운동 속도를 비롯한 인지기능이 호전된다.[@blumberg2020] 따라서 조현병 환자의 우울/음성 증상이 항우울제를 통해 개선된다면, 간접적으로나마 인지 기능이 개선될 여지가 있어보인다.

그러나 약간의 우울 증상이 있는 조현병 및 조현정동장애 환자에게 12주 동안 citalopram을 투여한 후 인지 기능을 평가했을 때 위약군과 차이가 없었다.[@dawes2012] 유사한 연구들을 종합한 메타 분석에서도 항우울제의 인지 기능 개선 효과는 임상적으로 무시할 수 있는 수준이고, 장기간의 항우울제 사용은 인지 기능에 긍정적 영향도 부정적 영향도 없는 것으로 나타났다.[@vernon2014; @terevnikov2015; @Hulkko2017] 조현병 환자의 우울 증상은 환자 스스로가 자신의 인지 기능이나 사회적 기능을 과소 평가하게 만드는 경향이 있다. 그렇다고 해서 실제 인지 기능이 기분 상태에 따라 달라지는 것 같지는 않다.[@Harvey2017]

## 인지 기능 개선제를 이용한 치료

조현병의 인지 증상은 음성 증상과 더불어 독립적인 치료 타깃으로 인정받고 있다. 인지 증상은 양성 증상보다도 더 일찍부터 시작되어 더 오래까지 지속되며, 병태생리와 더욱 밀접한 연관을 맺고 있고, 추후의 사회적 기능과 삶의 질을 결정하는 중요한 결정 요인이라는 인식이 널리 퍼졌기 때문이다. 따라서 양성 증상과는 독립적으로 인지 증상을 치료하려는 다양한 전략이 시도되었다. 2006년 MATRICS는 장래성있는 생화학적 표적으로 1) 전전두엽의 D~1~ 수용체, 2) 전전두엽과 대상피질의 세로토닌 수용체, 3) 글루타메이트 흥분성 시냅스(glutamatergic excitatory synapse), 4) 니코틴 및 무스카린 아세틸콜린 수용체, 그리고 5) GABA 신경전달체계를 꼽았다.[@tamminga2006] 이 청사진은 이후로 조금씩 확장되었을 뿐 크게 변화하지 않았다.

현재까지 이 분야에서 많은 연구가 이루어져왔지만, 그 결과를 긍정적으로만 바라볼 수는 없다. 한 비판적 문헌 고찰[@sinkeviciute2018]에 다르면, 대부분의 연구가 효과를 검증하기에는 통계적 검증력이 부족하고, 재현 연구가 수적으로 불충분할 뿐더러, 치료 기간이 짧았다. 그나마 글루타메이트와 콜린 계열 약물들은 미약하나마 유의한 효과를 보였으나, 다른 전략은 그렇지 못하였다.

### D~1~ 수용체 효현제

도파민 수용체 중에서 D~1,5~는 세포내 cAMP를 증가시키는 반면, D~2,3,4~는 cAMP를 감소시킨다. 문헌에서 D~1~ 수용체라하면 cAMP를 증가시키는 D~1,5~를 지칭한다. 전전두엽의 D~1~ 수용체는 작업 기억과 관련하여 인지 기능에 중요한 역할을 한다고 알려져 있다.[@sawaguchi1994] 전전두엽의 세번째 피질층(cortical layer III)에 있는 피라미드 뉴런은 D~1~ 수용체를 통해 도파민 신호를 수용하면서, 주위의 GABA 분비 뉴런과 함께 미세회로(microcircuit)을 이루고 있다. 이는 사물이나 개념의 정신적 표상(mental representation)을 유지하는데 핵심적이라 여겨지며, 이를 통해 잠시나마 작업 기억을 유지할 수 있다.[\@Arnsten2017](2장%20도파민%20가설%20참조) 조현병 환자가 인지 기능이 저하되는 주된 원인이 전전두엽의 도파민 활성 저하이기 때문에, 자연스레 D~1~ 수용체는 오래전부터 치료 타깃으로 각광받았다.

과거에는 D~1~에 선택적인 효현제가 없었기 때문에, D~2~ 차단제를 사용하고 있는 상태에서 D~1,2~를 모두 자극하는 amphetamine이나 methylphenidate를 투여하곤 하였다. Barch와 Carter[@barch2005]는 위약 대조 임상 시험에서 haloperidol이나 fluphenazine으로 치료받고 있는 환자에게 D-amphetamine을 투여하였는데, 작업 기억, 자발적 언어 표현, 스트룹 과제 수행이 유의하게 향상되었다. 그러나 조현병 환자에게 중추신경자극제를 오래 사용하는 것은 선뜻 받아들이기 어렵다.[@barch2010]

돌파구는 1980년대 말 선택적 D~1~ 효현제인 <s>d**ihydrexidine**[^13-05-1]</s>이 개발되면서 열리게 되었다. Rosell 등[@rosell2014]은 조현형 인격장애 환자들에게 dihydrexidine을 투여했을 때 위약에 비해 작업 기억을 평가하는 <s>PASAT</s>[^13-05-2] 수행을 개선시켰다고 보고하였다. 그러나 dihydrexidine은 생체이용률(bioavailability)이 극히 낮고, 흡수된 약물도 신속히 대사되어 버린다는 한계가 있다. 동일한 선택적 D~1~ 효현제로 후속 약물들이 개발되었으나, 경련을 비롯한 다양한 부작용을 해결하지 못하여 현재는 추진력을 잃은 상태이다.[@Arnsten2017] 결론적으로 D~1~ 수용체를 자극하려는 노력은 이론적으로는 가장 설득력있는 전략이었으나, 마땅한 약물이 개발되지 못하면서 잠시 주춤한 느낌이다.

[^13-05-1]: **Dihydrexidine (DAR-0100): 선택적** D~1,5~ 효현제로 D~2~에 비해 10배 이상 강하게 결합한다. 원래 파킨슨 치료제로 개발되었으며, 탁월한 효과를 나타냈지만 저혈압 부작용때문에 개발이 중단되었다. 현재는 소량을 피하로 주사하는 방식으로 사용되며, 부작용 문제는 많이 해결된 상태이다.

[^13-05-2]: **Paced Auditory Serial Addition Test (PASAT)**

### 5-HT~1A~ 세로토닌 수용체 효현제

시냅스전 5-HT~1A~ 수용체는 도파민의 방출을 조절한다. 따라서 5-HT~1A~를 자극하면 도파민 방출을 늘려 전전두엽의 D~1~ 수용체를 자극하는 효과를 거둘 수 있다.[@opler2013] 5-HT~1A~ 효현제로는 buspirone, gepirone, tandospirone 등이 있으며, 항정신병 약물인 아리피프라졸과 lurasidone 역시 5-HT~1A~의 부분 효현제로, 이들 약물의 독특한 약리 효과를 설명할 때 5-HT~1A~에 대한 언급이 빠지지 않는다.[@meltzer2008]

일찌기 Sumiyoshi 등[@sumiyoshi2001]은 안정 상태의 조현병 환자에게 tandospirone을 4주간 투여한 결과, 위약에 비해 <s>WMS--R</s>[^13-05-3]로 평가한 언어 기억의 유의한 호전이 있었다고 하였다. 동일한 연구진은 비정형 항정신병 약물을 복용 중인 73명의 환자에게 buspirone을 투여하였는데, 역시 주의력과 바꿔쓰기 검사에서 유의한 향상이 있었다고 보고하였다.[@sumiyoshi2007] 그러나 이러한 주장은 Sumiyoshi와 Meltzer 등 극히 제한된 연구자들에 의해 주도되고 있으며, 큰 반향을 일으키지는 못하고 있다.

[^13-05-3]: **Wechsler memory scale-revised (WMS-R)**

### 세로토닌 수용체 길항제

5-HT~1A~에 대한 효과와는 정반대로 나머지 세로토닌 수용체에 대해서는 길항 효과가 오히려 인지 기능을 호전시킨다고 한다. 예를 들어 5-HT~3~ 수용체를 차단하면 노르에피네프린과 아세틸콜린의 방출이 촉진되어 인지 기능을 호전시킬 수 있다. Akhondzadeh 등[@akhondzadeh2009]은 30명의 안정된 조현병 환자에게 12주간 리스페리돈과 대표적인 5-HT~3~ 길항제인 ondansetron을 투여했을 때, 위약과 비교하여 WMS-R의 소검사인 시각 재생, 시각 연합, 도형 기억에서 유의한 호전이 있었다고 보고하였다.

Mirtazapine은 α~2~-adrenergic, 5-HT~2~, 그리고 5-HT~3~ 수용체에 길항 효과를 가질 뿐 아니라 5-HT~1A~ 수용체에는 부분 효현 효과를 갖는다. 따라서 인지 기능에 세로토닌 시스템이 큰 영향을 미친다는 이론에 입각하면 이상적인 약물이라 할 수 있다. 일찌기 시행된 개방연구에서 mirtazapine이 즉각 기억 및 지연 기억을 향상시킨다고 보고되었으나[@dellechiaie2007], 뒤따르는 이중 맹검 연구에서는 긍정적인 결과가 재현되지 못했다.[@berk2009] 한동안 연구자들은 값비싼 비정형 약물을 쓰는 것보다, 정형 약물에 mirtazapine을 추가함으로써 낮은 비용으로 동등한 혜택을 얻을 수 있으니라 기대하기도 하였다.[@stenberg2009] 지금도 mirtazapine은 우울증 환자의 인지 기능을 회복시키는데 긍정적인 역할을 할 것으로 기대되고 있지만, 조현병 환자에 대한 연구는 뜸한 편이다. Perry 등[@Perry2018]은 메타 분석을 통해, 조현병 환자에 대한 mirtazapine 병용 투여의 효과는 유의하지 않으며, 관련 연구의 숫자 뿐 아니라 질도 충분하지 않아 어떤 결론도 내리기 힘들다고 하였다.

5-HT~6~ 수용체는 cAMP 생성의 조절, <s>Fyn kinase</s>[^13-05-4]의 제어 등을 통해 다양한 신경전달물질 시스템에 영향을 미칠 수 있다.[@tsegay2020] 5-HT~6~ 수용체를 차단하면 GABA 신호전달이 줄어들고, GABA에 의해 억제되고 있던 글루타메이트, 아세틸콜린의 분비가 늘어나 신경가소성이 자극받게 된다.[@de2015] 최근에는 알츠하이머 치매에서 나타나는 인지 기능 저하 메커니즘의 최종 단계에 Fyn kinase가 관여하고 있음이 발견되면서, Fyn에 대한 영향 역시 인지 기능 향상에 도움이 될 것이라 기대되고 있다.[@Nygaard2018] 러시아 연구자인 Morozova 등(2012)은 리스페리돈을 투여 중인 조현병 환자에게 5-HT~6~ 길항제로, 러시아에서는 항히스타민제로 사용되는 latrepirdine을 8주간 투여했는데, WMS의 하위 항목과 WCST 수행 성적이 유의하게 호전되었다. 동일한 연구진은 이후 또 다른 5-HT~6~ 길항제로 항정신병 약물로서 개발 중인 AVN-211 (avisetron)을 투여했는데, 역시 유사한 인지 기능 향상 효과를 관찰할 수 있었다.[@morozova2013] 제약회사인 Lundbeck은 역시 5-HT~6~ 길항제인 Lu AE58054 (Idalopirdine)의 가능성을 타진하여 조현병 뿐 아니라 치매 환자의 보조 치료제로 임상시험을 진행하였으나, 뚜렷한 성과를 얻는데는 실패하였다.[@capuzzi2021 ]

[^13-05-4]: **Fyn-tyrosine kinase**: Fyn은 개체 발달 과정이나 정상 생리에서 T 세포와 신경세포의 성장과 발달에 중요한 역할을 하는 tyrosine kinase이다. 이 단백질에 문제가 생기면 다양한 종류의 암이 발생하기 때문에 암유발 유전자(oncogene)로 분류된다. 다양한 정신질환과의 연관성이 연구되었으나, 최근 연구는 알츠하이머 치매에 집중되고 있다.

5-HT~6~ 길항제는 2010년대 중반까지 상당한 주목을 받았으며, 조현병 뿐 아니라 알츠하이머 치매의 보조치료제로서 활발하 임상시험이 이루어졌다. 그러나 대부분 2상 임상시험에서조차 가시적인 성과를 내지 못하며 현재는 개발이 뒷전으로 밀려나있다.

### 니코틴 수용체 효현제

니코틴 수용체를 자극하면 도파민 방출이 촉진된다. 조현병 환자는 감각 관문이 제대로 작동하지 않아 불필요한 자극을 걸러내지 못하고 주의가 분산되는데 (2장 참조), 이러한 현상은 니코틴 수용체의 돌연변이 및 기능 이상때문이라고 여겨진다.[@Adler1998] 선조체의 니코틴 수용체 이상은 인지 기능 뿐 아니라 망상의 발생에도 직접 영향을 끼칠 것이라는 가설도 제기되었다.[@Caton2020] 조현병 환자들은 특히 흡연자의 비율이 높고 더 많은 양의 니코틴을 흡입하는데, 이는 타고난 니코틴 수용체 이상 때문이라고 해석되기도 하고, 환자들의 <s>자가 치료</s>[^13-05-5]의 일환이라고 해석되기도 한다.[@kumari2005; @Quigley2019] 과거에는 정형 항정신병 약물을 복용하는 환자들이 흡연을 함으로써 간대사를 촉진시켜 약물을 배출시키고, 도파민 활성을 높여 추체외로 증후군을 극복하려는 것이라고 이해되기도 하였다.[@Winterer2010] 그러나 현재는 좀더 근본적인 차원에서 흡연을 하면 음성/인지 증상에 미약하나마 도움이 되기 때문에, 환자들이 흡연에 집착하는 것이라는 쪽으로 받아들여지고 있다.

[^13-05-5]: **자가 치료 가설 (self-medication hypothesis)**: 약물 의존 및 남용을 설명하는 하나의 가설로, 환자들이 자신이 기존에 갖고 있는 정신 질환을 가라앉히거나 감당하기 위해 약물에 의지하게 된다는 가설. 그러나 이렇게 사용되는 약물은 장기적으로는 원래의 정신 질환을 악화시키거나 치료를 방해한다.[@khantzian1997]

조현병 환자에게 니코틴 패치, 스프레이, 껌 등 다양한 경로를 통해 니코틴을 투여하고 인지기능을 평가하면, 다양한 과제에 대해 반응 시간, 삽화기억, 작업기억, 주의 집중이 향상되며, 이와 같은 결과는 과거 흡연 여부나, 정형/비정형 약물 복용과는 상관없었다.[@barr2007] 이처럼 많은 연구에서 일관되게 니코틴의 긍정적인 효과가 보고되지만, 실제 임상에서 성과를 거두기에는 효과의 정도가 무척 작다.[@barch2010] 더욱이 금방 내성이 생기기 때문에 치료제로서는 한계가 있다. 항상 담배를 피워오던 사람은 더 이상 인지 향상 효과가 나타나지 않으며, 오히려 끊었을 때 인지 기능이 감소한다. 더군다나 장기간에 걸친 흡연은 오히려 인지 장애를 악화시키기 때문에 흡연이나 니코틴을 인지 기능 개선제로 사용하는 것은 앞뒤가 맞지 않는다.[@Campos2016]

니코틴 아세틸콜린 수용체는 많은 수의 소단위(subunit)로 구성되며 학자들은 이를 크게 4가지 유형으로 구분한다. 약물로 개발중인 물질들은 대부분 이중 α~7~ 소단위의 효현제 들이다. <s>DMXB-A</s>[^13-05-6]은 낮은 농도에서는 α~7~ 선택적 부분효현제로 기능하고 높은 농도에서는 α~4~β~2~ 소단위에 약한 길항제 역할을 한다.[@kem2006] DMXB-A를 4주간 투여한 이중맹 교차 임상시험에서 고용량 투여 시 음성증상의 적지만 유의한 호전을 보였으나 인지 기능을 개선한다는 증거는 찾지 못하였다.[@freedman2008] 최근 시행된 DMXB-A의 서방형 제제를 사용한 임상 시험에서도 뚜렷한 호전이 발견되지 않았다. 저자들은 DMXB-A가 순간적으로 강한 효현 작용을 보이나 금방 약효를 상실하는 한계를 지적하고 있다.[@kem2017]

[^13-05-6]: **3-\[(2,4-dimethoxy) benzylidene\] anabaseine (DMXB-A, GTS-21):** 끈벌레(ribbon worm, *Nemertines*) 혹은 개미에서 생성되는 알칼로이드인 anabaseine에서 파생된 물질로 α~7~ 소단위의 부분 효현제 역할을 한다.

Tropisetron은 원래 항암치료 환자의 항구토제로 사용되는 약물로 α~7~ 부분 효현제이자 5-HT~3~ 길항제인데, 동물모델에서 기억력을 증진시키는 효과를 보였다.[@poddar2018] Zhang 등[@zhang2012]은 P50 유발전위를 통해 감각 관문의 이상이 확인된 조현병 환자를 대상으로 tropisetron을 투여하였는데, 전반적 인지 향상이 있었고 이는 P50의 호전 정도와 상관관계를 보였다. 최근에는 리스페리돈을 복용 중인 조현병 환자에게 단 하루 tropisetron을 복용시켰는데도, P50과 전반적 인지 기능에 유의한 변화가 있었다는 보고가 있다.[@xia2020]

DMXB-A, tropisetron 이외에도 EVP-6164 (encenicline), AQW051와 같은 α~7~ 소단위 부분 효현제, TC-5619와 같은 효현제가 임상 시험을 거쳤으나, 각종 부작용과 효과 미진으로 3상 임상 시험을 통과하지 못하였다. 주된 부작용은 복통 및 변비 등의 위장관계 증상이었다.[@tregellas2018]

새롭게 각광받는 약물은 다른 자리 입체성 조절제 (Positive Allosteric Modulators, PAM)라 불리는 약물들이다. 이는 리간드 결합부위가 아닌 다른 부위에 결합하여 3차원적 구조를 바꿈으로서 효현 효과를 나타내는데, 내성 발생을 극적으로 줄일 수 있다는 장점이 있다. 대표적인 PAM으로는 항치매제로 쓰이는 galamtamine이 있다. 비록 galantamine 병용 투여가 효과적이라는 주장은 큰 반향을 얻지 못하고 있지만[@koola2020], AVL-3288, JNJ-39393406와 같은 유사 약물이 현재 1,2상 시험을 거치고 있다.[@Gee2017; @tregellas2018]

α~7~ 니코틴 수용체에 작용하는 약물들은 탄탄한 이론적 근거와 함께 현재 활발히 연구되고 있는 분야이며, 세로토닌 계열 약물들처럼 조현병 및 알츠하이머 치매의 보조치료제로서 개발 과정에 놓여있다. 단기적 효과는 분명하지만, 빠른 내성때문에 효과가 장기간 지속될 지가 의문이며, 위장관계 부작용을 아직 해결하지 못하고 있다.

### 항치매제

조현병 환자의 인지 기능 저하가 아세틸콜린 활성과 관련이 있다면, 항치매제로 개발된 약물을 조현병 환자에게 쓰지 말란 법도 없을 것이다. 물론 마이네르트 기저핵(nucleus basalis of Meynert)의 콜린성 뉴런이 선택적으로 파괴되는 알츠하이머 치매와 조현병의 인지 장애는 근본적으로 기전이 다르지만, 어떤 경로를 통하던 간에 인지 기능 향상 및 보존 효과를 기대해볼 수 있을 것이다.

기대와는 달리 아세틸콜린 에스테라아제 억제제인 도네페질을 이용한 초창기의 연구들은 그다지 긍정적인 결과를 얻지 못하였다. 최초의 임상 시험은 2002년에 이루어졌는데[@friedman2002] , 리스페리돈 복용 환자군에 도네페질을 병용 투여했으나 유의한 효과는 얻지 못하였다. 최초의 긍정적인 효과는 김영훈 교수팀이 한국에서 진행한 연구에서 얻어졌는데, 할로페리돌로 안정된 조현병 환자에게 도네페질을 12주간 하루 5mg 투여했을 때 언어 기억 및 MMSE 점수가 유의하게 개선되었다.[@lee2006] 그러나 이후 연구에서 일관성있게 재현되지는 못하였고, 유사한 항치매제인 rivastigmine 역시 위약보다 나은 결과를 보이지 못했다.[@barch2010; @thakurathi2012]

Galantamine은 제약회사 얀센에서 개발한 항치매제로 콜린에스테라아제 억제제일 뿐더러 α~7~ 니코틴 수용체에 PAM으로 작용한다. 따라서 도네페질 보다는 우수한 효과를 보일 것으로 기대되었다. 역시 리스페리돈을 투여받고 있는 환자에게 galantamine을 추가로 투여했을 때 주의력과 지연회상의 수행이 개선되었다는 보고가 있으나[@schubert2006], 효과가 워낙 미미하여 본격적인 개발이나 연구가 진행되고 있지는 않다.

### NMDA 수용체 효현제

조현병의 음성/인지 기능 회복에 있어서 뭐니뭐니 해도 가장 관심을 모으고 있는 것은 다양한 글루타메이트 관련 약물들이다. NMDA 수용체 차단제인 phencyclidine (PCP)과 케타민이 조현병에 특징적인 음성/인지 증상을 유발한다는 것으로 부터, 학습/기억 및 이를 뒷받침하는 신경가소성에 글루타메이트가 핵심적 역할을 한다는 것이 알려지면서 더더욱 글루타메이트의 지위가 상승되었다. 현재 조현병의 글루타메이트 가설은 고전적인 도파민 가설을 대체할 만한 강력한 가설로 부상 중이다.

글루타메이트 수용체에 접근하는 전략은 크게 이온 채널인 NMDA 수용체와 AMPA 수용체를 자극하는 방법, 그리고 대사성 글루타메이트 수용체 (metabotropic glutamate receptor)를 자극하는 방법이 있다. 이중 NMDA 수용체에 대한 연구가 훨씬 다양하게 이루어졌는데, 아무래도 NMDA 수용체가 신경가소성에 더욱 직접적인 역할을 하기 때문인 것으로 여겨진다. 시냅스 전 뉴런에서 분비된 글루타메이트는 글루타민으로 전환되며, 이는 다시 재흡수되어 글루타메이트를 만드는데 재사용된다. NMDA 수용체를 자극하기 위해 L-glutamine을 직접 투여하는 방법도 생각해볼 수 있으나, glutamine은 체내에 가장 풍부하게 분포하는 아미노산이요 정상인이 결핍 상태에 이를 일은 거의 없다. 그보다는 NMDA 수용체 활성을 조절하는 다양한 조절 부위, 그 중에서도 특히 glycine 결합부위에 작용하는 약물을 주로 사용한다.

#### Glycine

Glycine을 약으로 사용하는 아이디어는 1994년 Javitt 등[@Javitt1994]에 의해 처음 시도되었다. 동일한 연구진이 몇 차례에 걸쳐 흥미로운 연구 결과를 발표했으나[@herescolevy1996], 대규모 연구에서는 제현되지 않았고 이후 더 이상 연구가 진행되지 않았다.

#### D-cycloserine

D-cycloserine은 원래 항결핵제로 개발되었으나, glycine 결합부에 달라붙어 부분효현 작용을 일으킨다는 것이 발견되었다. 하버드 대학의 Donald Goff는 1990년대 중반부터 D-cycloserine 연구에 매진해왔다. 90년대 이루어진 정형 약물과 D-cycloserine을 병용 투여하는 연구에서는 긍정적인 효과가 나타났고, 최적의 유효 용량이 하루 50mg라는 결론까지 얻어졌다.[@Goff1995] 그러나 이후 클로자핀을 비롯한 비정형 약물과의 병용 투여 시험에서는 오히려 음성 증상을 악화시키는 결과가 나타나 D-cycloserine의 유용성은 의심받기 시작하였다. Goff 등[@Goff2008]은 D-cycloserine을 일주일에 한번 투여하는 기법을 사용하여 우수한 효과를 거둘 수 있었다고 보고하였으나, 2010년 발표된 메타 분석[@Tsai2010]에서는 다른 글루타메이트 관련 약물에 비해 효과가 열등한 것으로 나타났다. 20년 이상 연구를 이끌어온 Goff는 2017 년에 발표한 종설[@Goff2017]을 통해 D-cycloserine은 NMDA 수용체 소단위 구성 비율에 따라 강력한 효현작용을 나타내기도 하고, 어떤 경우에는 길항제 역할을 하기도 하는 등 효과를 종잡을 수 없었다고 인정하였으며, 보다 특이적인 NMDA 효현제 개발의 필요성을 강조하였다.

#### D-serine

D-serine은 뇌에서 합성되는 아미노산으로 glycine보다도 더 강력한 NMDA 효현제이다.[@wolosker2020] D-serine이 PCP를 투여한 쥐의 과도한 상동행동을 억제한다는 것은 1990년 초에 발견되었고[@Contreras1990], 대만 연구자인 Tsai는 1998년에 조현병 환자에게 D-serine을 투여하여 WCST 점수가 향상되는 결과를 얻었다고 보고하였다.[@tsai1998] 이후 MATRICS와 같은 체계적인 인지 검사 도구를 이용한 연구에서도 유사한 결과가 얻어졌고, 호전 정도는 D-serine의 혈중 농도와 상관관계가 있었다.[@kantrowitz2010**; @kantrowitz2018**] D-serine은 항우울 효과를 지닐 뿐 아니라, 케타민의 항우울 효과를 예측하는 생체표지자로서 새삼 주목을 받고 있다. 향후 조현병의 음성/인지 치료에 많은 가능성을 내포하고 있다.[@MacKay2019]

#### NMDA 수용체의 효과를 둘러싼 논란

2000년대 중반 당시까지 활발하게 연구되던 몇 가지 NMDA 효현제에 대한 논란을 종식시키고자, 관련 연구를 진행해오던 일련의 연구자들은 The Cognitive and Negative Symptoms in Schizophrenia Trial (CONSIST)라는 다기관 연구를 진행하였다. 이 연구는 미국과 이스라엘의 다섯개 센터에서 모집된 157명의 조현병 환자를 대상으로 16주에 걸쳐 glycine, D-cycloserine 그리고 위약을 투여하였다. 안타깝게도 위약과의 차이를 입증하는데 실패하였으며, 이 연구를 분수령으로 하여 기존의 구태의연한 방식에 의한 NMDA 자극은 별다른 임상적 이득을 가져오지 못한다는 것이 분명해졌다.[@Buchanan2007]

그러나 글루타메이트 시스템에 대한 연구가 중단된 것은 아니었다. 다음 세대로 개발된 약물은 선택적 glycine 재흡수 억제제인 biopterin 이었다. 이 약물은 glycine type 1 transporter (GlyT1)를 차단하여 세포 외 glycine 농도를 높인다. 이를 통해 NMDA 수용체 자극에 의한 흥분 독성(excitotoxicity)을 막으면서 음성/인지 결함을 개선시킬 것이라 기대를 모았다. 그러나 3상 임상시험에서는 아직 긍정적인 결과를 얻지 못하고 있다.[@singer2015]

### AMPA 수용체 효현제

시냅스후 AMPA 수용체도 또 다른 표적이다. AMPA 수용체가 활성화되면 NMDA 채널에서 마그네슘(Mg^2+^)의 제거를 촉진하여 NMDA 수용체를 활성화시킨다. 동시에 조현병 환자의 사후 뇌 연구에서 해마의 AMPA 수용체 밀도 감소가 보고되기도 하였다.[@meador-woodruff2000] 개방 연구에서 클로자핀에 CX516 (ampakine)을 추가했을 때 기억력과 주의력의 호전을 보였으나[@goff2001], 이후의 위약 대조 시험에서는 더 이상 인지 기능의 향상을 관찰할 수 없었다.[@goff2007] AMPA 수용체 효현제들은 조현병에서는 고무적인 성과를 얻지 못하였지만, 치매환자의 공격성 조절, 우울증, 주의력 결핍 장애, 아편양 약물에 의한 호흡저하 등에 긍정적인 효과를 보여주고 있다.[@ward2015]

### GABA 효현제

GABA 사이뉴런은 피라미드 뉴런의 흥분에 음성 되먹임을 함으로써 감마 진동을 만들어낸다는 점에서 고위 인지기능을 유지하는데 중요한 역할을 할 가능성이 제시되고 있다.(2장 6-5절 참조#article-02-06.html#gamma-band)

Menzies 등[@menzies2007]은 11명의 만성 조현병 환자에게 GABA 수용체 길항제인 flumazenil과 효현제인 lorazepam을 투여한 후 작업기억 수행을 비교하였다. 예상했던 대로 전자는 수행성적을 향상시켰고, 후자는 저해하였다. GABA α~2/3~ 수용체 부분 효현제인 MK-0777이 의미있는 성과를 보이기도 하였으나[@lewis2008], 다른 연구진이 이를 재현하는데 실패히였다.[@buchanan2011]

임상시험의 실패에도 불구하고, 학자들은 기대를 버리지 못하고 있다. 도파민, 글루타메이트, GABA는 서로 긴밀하게 맞물려있으며, 복잡한 상호 피드백을 통해 섬세한 균형을 이루고 있다. 과거의 학자들은 이들 시스템을 따로따로 이해하려 노력하였으나, 점점 더 세가지 시스템의 균형과 조화가 중요하다는 것이 강조되고 있다. 예를 들어 NMDA 길항제인 MK-801을 투여하면 GABA 유발 전위가 활성화되며, quercetin이라는 약물은 이를 정상화시킨다. MK-801은 대표적인 조현병의 동물 모델 중 하나이기 때문에, quercetin의 효과는 항정신병 약제로서의 가능성을 시사해준다.[@Fan2018] 그러나 인지 기능 뿐 아니라 전체적인 정신병적 증상 면에서 GABA 시스템의 활성을 올리는 것이 도움이 되는지 억제하는 것이 도움이 되는지 조차 확실하지 않다.[@Fan2018]

### 기타 약물들

Dehydroepiandrosterone(DHEA), DHEA의 sulfate ester(DHEA-S), pregnenolone(PREG)은 뇌에서 생성되는 신경스테로이드로서 인지 기능 유지와 연관될 것으로 추정된다.[@maninger2009][^13-05-7] DHEA 혹은 DHEA-S의 혈중 농도는 삶의 질 및 작업기억과 정적인 상관관계를 보인다. 또한 PREG의 혈중 농도 역시 작업기억, 언어유창성을 비롯한 전체적 인지 기능과 연관이 있다.[@chen2018]

[^13-05-7]: DHEA, DHEA-s, PREG 등은 콜레스테롤로부터 성호르몬이 만들어지는 단계에서 생성되는 중간 산물로 주로 부신에서 생성된다. 이들 물질은 나이가 들면서 농도가 떨어지기 때문에, DHEA(-s) 보충 요법이 부상하였으며, 일부 연구에서 인지와 기억력, 성기능, 면역기능, 근력과 체 성분, 골 대사 등에서 좋은 효과를 보이는 것이 발견되었다. 그러나 이런 결과들은 대부분 부풀려져 있으며, 건강보조식품으로써 큰 효과는 없다.

DHEA는 조현병의 음성, 우울, 불안 증상과 추체외로 증후군 개선에 도움이 된다는 보고가 있으며, 인지 기능에 대해서도 연구가 진행된 바 있다.[@strous2003; @ritsner2006] 물론 개중에는 긍정적인 결과와 부정적인 결과가 뒤섞여 있으며, 투여 전 DHEA/DHEA-S의 농도가 투여 효과를 예측한다는 보고도 있다.[@ritsner2010] <s>Pregnenolone</s>[^13-05-8]에 대해서도 몇몇 임상 시험이 진행되었고 그 중 일부에서 긍정적인 효과가 보고되었다.[@ritsner2010a; @marx2014]

[^13-05-8]: **Pregnenolone**: Androgen의 전구물질인 DHEA(-s)와 달리 pregnenolone은 progesterone의 전구물질이다. 중추신경계에서 pregnenolone은 주로 GABA 시스템을 조절하여 불안 우울과 같은 정신 증상 및 경련발작, 기억력 유지에 영향을 미친다.

한편 항생제인 <s>minocycline</s>[^13-05-9]은 항염증 작용, 미세아교세포(microglia) 활성화 억제, 산화 및 질소화 스트레스의 감소, 세포자멸사 억제, 흥분성 독성의 완화 등을 통해 신경세포를 지켜주는 약물로 주목받고 있다.[@Garrido-Mesa2013] 자연히 조현병 치료에 도움이 될 것이라는 가능성이 제기되었다.[@Solmi2017] 조현병이 만성 염증을 비롯한 면역체계의 비정상적 항진때문에 일어난다는 면역가설이 설득력을 얻어가면서 minocycline은 다양한 신경과/정신과 질환 치료에 적극적으로 사용될 가능성이 높아지고 있다.[@Chaves2021]

[^13-05-9]: **Minocycline**: 폐렴 치료에 사용되는 tetracycline 계열의 항생제이다. 그러나 세균 억제 효과는 약한 편이며, 대신 여드름, 천식, 류마치스 관절염, 탈모 등 기타 용도로 널리 사용된다.

## References {.unnumbered}
