---
title: "음성 증상의 치료"
editor: visual
bibliography: References/13-02.bib
---

## 개요

조현병의 치료에서 기능의 회복은 정신병적 증상의 소실만큼 아니 그 보다 더 중요하다. 그런데 조현병 환자가 기능을 회복하지 못하는 최대의 걸림돌 중 하나는 음성 증상이다. 속발성 음성 증상을 구분하여 치료하려는 노력은 부족하나마 어느 정도 성과를 거둘 수 있으나, 원발성 음성 증상의 치료법은 여전히 요원한 상태이다. 문헌에는 약물학적 치료, 뇌자극술, 인지행동치료와 같은 다수의 치료법이 등장했지만 현재로서는 그 근거가 너무나 미약하여 자신있게 특정한 치료법을 추천할 수 없는 형편이다.

단적으로 음성 증상 및 인지 증상의 치료를 타깃으로 하여 미국 식약청(FDA)으로부터 승인을 받은 약물은 없다. 항정신병 약물은 그저 급성기의 정신병적 증상을 가라앉히는데, 그리고 유지 치료 시 재발을 막는데 허가를 받았을 뿐이다. 그 외의 치료 효과에 대해선 허가 외 용도로 사용하는 것이나 마찬가지이다.

그러나 궁극적 예후를 결정짓는데 음성 증상이 너무나도 중요한 나머지, FDA는 양성 증상과는 별도로 지속적인 음성 증상(persistent negative symptoms)이 약물 개발의 주요 목표가 될 수 있다고 선언하였다.[@Laughren2006] 마치 항정신병 주사제가 조현병 급성기의 격앙 상태 조절에 대해 허가를 받거나, 클로자핀이 자살 방지 목적으로 허가를 받은 것처럼, 공식적인 치료 목표로 인정되면 그 분야의 약물 개발 노력이 탄력을 받을 수 있다.

비록 비정형 약물이 음성 증상에 조금이나마 효과를 보인다고 하지만, 이는 정신병적 증상, 추체외로 증상, 그리고 불안 또는 우울 증상 등 다른 증상이 호전되면서 덩달아 좋아지는 것으로 보인다. 따라서 이러한 속발성 증상이 아닌 원발성 증상에도 도움이 되는 지는 확인되지 않고 있다. 문제는 지금까지 임상에 도입된 대부분의 항정신병 약물이 도파민 신호전달을 차단하는 약물이요, 이 약물효과는 근본적으로 음성 증상에 악영향을 미친다는 것이다. 학자들은 도파민 수용체 차단을 비껴가지 않으면 결코 음성 증상을 해결할 수 없으리라 예상한다. 최근 10년 사이에 실험적으로 도입되고 있는 비 도파민성 항정신병 약물에 관심이 모아지고 있는 것도 이 때문이다.

음성 증상을 해결할 수 있는 근본적 치료제가 없는 상황에서, 다른 용도의 약물을 병용 투여하는 전략도 활발히 연구되어 왔다. 가장 보편적인 전략은 항우울제를 병용하는 것인데, 이는 우울증상의 호전과 별도로 정서의 둔마, 무언어증, 무의욕 등에 도움이 된다고 한다. 그러나 효과는 미미한 편이며 모든 연구에서 일관된 결과가 얻어진 것도 아니다.[@azorin2014]

음성 증상과 인지 증상의 밀접한 연관성을 고려하여, 인지 기능의 회복을 돕기 위해 시도되는 약물이 동시에 음성 증상을 위해서도 사용된다. 몇몇 임상시험에서 glycine이나 d-serine 등 글루타메이트 수용체에 작용하는 약물의 부가 요법에 대해 평가를 하였다. 여전히 반색할만한 결과는 얻어지지 않았지만, 많은 가능성을 품고 있는 영역이다.[@möller2015]

## 항정신병 약물을 이용한 치료

비정형 항정신병 약물이 등장하고, 세로토닌 수용체나 D~2~를 제외한 기타 도파민 수용체가 약리 효과에 차지하는 역할이 부각되면서, 소위 조현병 환자의 충족되지 못한 요구(unmet needs)에 대한 광범위한 연구와 도전이 이루어졌다. 이러한 충족되지 못한 요구에는 양성 증상을 제외한 거의 모든 증상을 비롯하여 기능 회복, 삶의 질, 재활, 지역사회 편입, 신체적 건강 등의 문제가 포함되었는데, 이 중심에는 여전히 음성/인지 증상이 자리잡고 있었다. 비정형 약물이 이러한 요구를 충족시켜 줄 수 있으리라는 기대에 부푼 나머지 지난 20년 이상 셀 수 없이 많은 연구들이 진행되었으며, 연구자들은 음성 증상의 해결에 있어서 정형 약물에 비해 비정형 약물이 갖는 우수성을 입증하고자 애썼다.[@krause2018] 그러나 이를 평가할 때 다음과 같은 연구방법론에서의 문제를 고려해야만 한다.[@möller1998]

-   장기 경과를 관찰한 연구는 별로 없으며, 대부분의 연구는 양성과 음성 증상이 혼재하는 급성 환자를 대상으로 시행되었다. 음성 증상에 대한 효과만을 관찰하려면, 일정 기간 이상 안정적인 상태에 있으면서도, 적어도 6개월 이상 음성 증상이 지속되어 기능 회복을 방해하고 있는 환자를 대상으로 연구해야 할 것이다. 그러면서도 우울증의 증거는 없어야 할 것이다.
-   대부분의 연구는 PANSS의 음성 척도를 평가의 기준으로 삼았다. 그러나 음성 증상을 다면적으로 평가하기 위해선, 따로 개발된 1세대 혹은 2세대 음성 증상 평가척도를 사용해야 할 것이다.
-   비교의 대상이 된 정형 항정신병 약물이 지나치게 용량이 높은 경우가 많았다. 추체외로 증상에 의한 속발성 음성 증상을 배제하기 위해서는, 정형 약물을 다양한 용량으로 사용한 집단과 비교하는 과정이 필요하다.
-   Butyrophenone 계열 약물이 추체외로 증상 위험이 높다고 알려져 있는데도, 비교의 대상이 된 정형 약물이 할로페리돌이었던 경우가 가장 많았다. 저역가 약물이나 설피라이드, flupenthixol 등 비정형성을 띠고 있다고 생각되는 정형 약물들은 거의 연구되지 않았다.

수많은 연구에도 불구하고 이를 통해 확인한 것은 비정형 약물이 적어도 속발성 음성 증상을 덜 일으킨다는 정도에 지나지 않았다. 그 중에서는 클로자핀과 퀘티아핀이 속발성 음성 증상을 가장 덜 일으키는 약물로 꼽혔으며[@veerman2017], 음성 증상 자체에 유의한 효과를 보인 약물은 아미설프라이드와 카리프라진 정도가 유일하였다.[@krause2018] Huhn 등[@huhn2019]이 행한 네트워크 메타분석에 따르면, 다른 약물에 비해 유의한 수준으로 음성 증상을 덜 일으키는 약물은 클로자핀, 아미설프라이드, 올란자핀이었고, 그 뒤를 리스페리돈, 조테핀이 따르고 있었다. 나머지 약물들 간의 차이는 확실하지 않았다. 무의욕에 대해서 따로 조사한 연구에서도, 적어도 6개월 이상, 다양한 비정형 항정신병 약물로 치료한 후에도 의욕이 더 살아나지도, 더 감소하지도 않았다는 것이 관찰되었다.[@fervaha2015]

이처럼 비정형 약물이 음성 증상에 구체적인 치료 효과를 나타내는 것 같아보이지는 않지만, 그럼에도 불구하고 정형 보다는 비정형 약물이 선호된다. 추체외로 증후군 발생 위험이 낮을 뿐 아니라, 세로토닌 수용체 등에 대한 효과는 항우울, 항불안 효과를 가져오기 때문에, 적어도 속발성 음성 증상의 발생을 막아줄 수 있다.[@leucht2009; @krause2018]

### 클로자핀

1988년에 발표된 치료저항성 조현병 환자에 대한 클로자핀 임상 시험 결과에서도 이미, 음성 증상을 평가하는 BPRS의 소항목 점수가 어느 정도 호전된 것이 관찰되었다.[@Kane1988] 당시만 해도 세로토닌 수용체의 역할과 비정형성의 정의에 대해 학계가 떠들썩 했던 때였고, 도파민-세로토닌 가설을 내놓았던 Meltzer는 클로자핀이 원발성 음성 증상에도 우수한 효과를 나타낼 것이라 역설하였다.[@meltzer1999] 그러나 이미 당시부터도 일부 클로자핀 신봉자를 제외한 나머지 연구자들은 이러한 주장을 받아들이는데 불편감을 드러내었다.[@carpenter2000] 문제는 클로자핀을 이용한 대부분의 임상 연구가 치료저항성 환자를 대상으로 이루어졌고, 음성 증상의 호전은 양성 증상의 호전에 뒤따른 결과였다는 점이다.[@miller1994; @Buchanan1998]

이러한 교란 변인을 최소화하기 위해 Brar 등[@brar1997]은 BPRS에서 양성 증상의 점수가 상대적으로 낮은 17명의 환자를 대상으로 클로자핀을 6개월 투여하였댜. 그 결과 BPRS의 음성 증상 항목(감정적 위축, 정서의 둔마, 운동 지체)에서 유의한 감소가 관찰되었다. 그러나 이들은 대부분 오래 입원하고 있던 만성환자였고, 포괄적인 음성 증상 평가가 이루어지지 못했다느 점에서 근거로 삼기에는 부족하다.

결국 원발성 음성 증상에 대한 클로자핀 효과를 끈질기게 주장한 학자는 Meltzer 뿐이었고, 나머지 학자들은 그다지 깊은 인상을 받지 못한 셈이다. 2006년 Murphy 등[@murphy2006]이 발표한 체계적 문헌고찰에서도 역시 이러한 클로자핀의 효과는 속발성 음성 증상에 국한되는 것같다고 논하고 있다.

### 리스페리돈과 올란자핀

리스페리돈과 올란자핀은 치료저항성 환자가 아닌 보다 일반적인 환자에게 사용된다는 면에서 음성 증상에 대한 효과를 평가할 수 있는 보다 많은 기회가 주어졌다. 물론 이들 약물도 단순히 속발성 음성 증상에만 효과가 있을 것이라는 비판에서 자유롭지 못했다. 이러한 비판에 대해 Möller 등[@möller1995]은 경로 분석을 통해 속발성 음성 증상에 대한 간접적 효과를 제거하고 난 후에도 리스페리돈은 할로페리돌에 비해 음성 증상 호전 효과가 유의하게 컸다고 보고하였다. 그러나 Peuskens[@peuskens1995]의 이중맹검 연구에 의하면 다섯 가지 용량의 리스페리돈을 할로페리돌 일일 10mg 투여와 비교했을 때 음성증상 호전에 별차이가 없었다.

음성 증상에 대한 올란자핀의 직접 효과를 분석한 Tollefson 등[@negative1997]은 올란자핀은 위약이나 할로페리돌에 비해 분명히 더 효과적이라고 하였다. 리스페리돈과 비교했을 때 SANS로 평가한 음성 증상에서는 유의하게 효과가 더 컸다는 보고도 있다.[@tran1997] Alvarez 등[@Alvarez2006]은 안정 상태에 있으며 주로 음성 증상을 보이는 외래 환자를 대상으로 리스페리돈과 올란자핀의 효과를 직접 비교하였다. 1년후 올란자핀이 유의하게 호전 정도가 컸으며, 음성 증상에 대한 효과 중 43%는 직접 효과이고, 나머지 52%는 속발성 음성 증상에 대한 간접 효과였다고 발표하였다. 이 연구에서 감안할 점은 리스페리돈 군이 훨씬 추체외로 증상 발현이 잦았기 때문에, 음성 증상에 악영향을 미쳤을 여지가 있다는 점이다.

### 퀘티아핀

퀘티아핀은 독특하게 150\~300mg 정도의 용량에서 항우울 및 항불안 효과를 나타낸다. 따라서 이 효과를 응용하면 음성 증상에도 유리할 것이라는 기대감을 일으켰다. 급성기 환자를 대상으로 연구에서 퀘티아핀 일일 307mg은 SANS 로 평가한 무관심, 무쾌감증 및 무언어증에서 위약에 비해 유의한 호전을 보였다.[@borison1996] 퀘티아핀의 저용량(209mg/day)과 고용량(360mg/day)을 비교한 연구에서는 고용량이 더 우수하였다.[@small1997] 최적 용량을 조사한 연구에서 음성 증상에 대한 최대 효과는 일일 300mg 에서 나타났다.[@arvanitis1997]

속발성 음성 증상에 대한 효과를 배제한 직접 효과를 구하기 위해 역시 경로 분석이 이용되었다. Tandon[@tandon2004]이 분석한 바에 따르면 SANS를 이용하여 치료 전과 치료 후를 비교하였을 때, 위약군 대비 효과 크기는 1.96으로 나타났으며, 이중 44.2%가 직접 효과인 것으로 나타났다. 그러나 이 모든 연구들은 통상적인 임상 시험에서 얻어진 결과이며, 유달리 음성 증상을 주로 나타내는 환자를 대상으로 이루어진 것은 아니었다.

### 아미설프라이드

아미설프라이드는 잠재력에 비해 상당히 저평가된 약물이다. 각종 메타 분석에서 클로자핀을 제외하고는 가장 우수한 효과를 보이는 것으로 나타나지만, 유럽을 제외하고는 임상에서 타 약물만큼 널리 사용되지 않는다.[@huhn2019] 아미설프라이드와 그 선조 격인 설피라이드는 오래전부터 비정형성을 띠는 것으로 알려져 왔으며, 그러면서도 세로토닌 수용체에는 결합하지 않기 때문에 눈길을 끌었다.[@Möller2003]

아미설피라이드는 용량에 따라 차별화된 작용 기전을 나타내는 약물이다. 저용량(50\~300mg)에서는 시냅스전 자가수용체를 먼저 차단하기 때문에 오히려 도파민 활성을 늘이며, 이는 항우울 효과의 기전으로 이해되었다. 300mg/day가 넘어가면서 시냅스 후 D~2,3~ 수용체 차단이 시작되는데, 이중 D~[3]{.smallcaps}~에 대한 효과가 비정형성 및 음성 증상에 대한 효과에 관련될 것으로 믿어지고 있다.[@storosum2002][^13-02-1]

[^13-02-1]: 음성 증상과 D~3~ 수용체에 대한 관계는, 최근 cariprazine이 임상에 도입되면서 매우 활발한 연구 주제가 되었다.

아미설프라이드가 음성 증상에 효과적임을 최초로 입증한 연구는 1999년 Danion 둥[@danion1999]에 의해 행해졌다. 음성 증상이 우세한 환자를 대상으로 12주 간 이중맹검으로 투여한 결과, 아미설프라이드 군은 다른 어떤 정형 항정신병 약물에 비해서도 SANS의 각 항목과 총점에서 모두 유의하게 더 나은 호전을 보였다. 20 여년 후 Krause 등[@krause2018]이 음성 증상을 주로 보이는 환자군에 대한 임상 시험을 메타 분석한 결과에서, 위약군에 비해 유일하게 뚜렷한 효과 차이를 보여준 약물은 아미설피라이드 뿐이었다. 이러한 근거들을 바탕으로 아미설프라이드는 프랑스를 포함한 몇몇 유럽 국가에서 음성 증상 치료에 허가를 받았다. 그러나 과연 양성 증상과 독립적인 원발성 음성 증상에 대해서도 치료효과를 띨 것인지에 대한 의문은 여전히 풀리지 않았다.

### 아리피프라졸

아리피프라졸은 모든 면에서 기존의 약물과는 조금 다를 것으로 기대를 모았다. 항정신병 약물 중에서는 거의 유일하게 전두엽의 도파민 저활성을 정상화시켜 줄 수 있기 때문이다. 또한 인지 기능에 대한 긍정적 효과는 음성 증상에도 유리하게 작용할 것으로 예상되었다. 1년 간에 걸쳐 아리피프라졸과 할로페리돌을 비교한 이중 맹검 연구에서 음성 증상 자료만을 따로 분석하였을 때, PANSS의 음성 증상 척도가 할로페리돌 군에 비해 유의하게 감소하였다.[@archibald2003] 그러나 이후 음성 증상만을 타겟으로 한 대규모 임상 시험은 이루어지지 않았다.

아리피프라졸의 효과는 용량에 따라 크게 영향을 받을 수 있다. 초기 임상 시험의 하나였던 Kane 등[@Kane2002]의 연구에서 아리피프라졸 15mg/day는 위약 군에 비해 유의한 음성 증상 호전을 보였으나, 30mg/day는 그렇지 못했다. 용량이 올라가면서 부분효현제의 장점이 상쇄되는 지는 더 연구가 필요하다. 또한 도파민 수용체의 수 자체가 감소된 경우에는 부분효현제가 도파민 활성을 올리지 못한다. 최근에는 클로자핀과 아리피프라졸을 병용 투여하는 것이 인기를 끌기도 했는데, 치료저항성 환자에게 이렇게 병용 투여했을 때 음성 증상에서도 상당한 호전이 있었다는 보고가 있다.[@clarke2006]

### 새로운 세대의 항정신병 약물

최근 4,5년 동안 음성 증상 치료에 있어서 가장 주목받은 것은 cariprazine의 도입이다. Cariprazine은 헝가리에 기반을 준 Gedeon Richter라는 제약회사에서 개발한, D~3~ 수용체의 부분 효현제이다. D~2~에 대한 부분 효현 작용도 있긴 하지만, D~3~에 대한 결합력이 훨씬 크기 때문에 조현병 치료에 있어 새로운 패러다임을 가져온 약물로 평가받는다. D~3~가 조현병에서 어떤 역할을 하는 지는 확실히 알려지지 않았다. 다만 D~3~ 수용체의 과민감성은 비정상적인 현저성(aberrant salience)을 일으키기 때문에, 과민화된 영역에서 D~3~ 길항제로 작용하는 cariprazine은 비정상적 현저성을 줄이는데 효과가 있을 것으로 기대된다. 더불어 전전두엽에서 글루타메이트/GABA의 항상성을 회복시키는데도 도움을 줄 것으로 믿어진다.[@correll2020]

음성 증상에 대한 치료효과는 Nemeth 등[@Németh2017]이 2017년에 발표한 임상시험 결과에서 처음 공표되었다. 리스페리돈 단독치료와 cariprazine 단독치료를 비교한 이 연구에는 지난 6개월 이상 현저한 음성 증상을 보여온, 지속적인 음성 증상(10장 1-1-2 참조) 환자를 대상으로 하였다. 그 결과 PANSS의 음성 증상 총점에서 cariprazine 군이 리스페리돈 군에 비해 평균 1.46점 더 호전되었던 것으로 나타났다. 비록 효과 크기는 0.31밖에 되지 않았지만, 타 약물과의 일대일 비교에서 우월한 성적을 보였다는 것은 주목할만 하다.

지속성 음성 증상을 보이는 환자만을 대상으로 한 것은 아니지만, 다양한 임상 시험 결과를 사후 분석한 결과를 보았을 때도, 리스페리돈 군에 비해 음성 증상이 의미있게 감소하는 것이 확인되었다.[@Fleischhacker2019] 급성 환자를 대상으로 진행된 연구 결과를 분석했을 때, 여전히 cariprazine은 위약군 및 리스페리돈 군에 비해 우수한 음성 증상 호전 효과를 보였다. 낮은 용량(1.5\~3mg/일)에서는 아리피프라졸과 차이가 없었으나, 고용량(4\~6mg/일)에서는 좀더 우수한 효과를 보였으며, 이러한 결과들은 양성 증상에 대한 효과를 보정한 후에도 유의성이 유지되었다.[@Earley2019]

이러한 임상 성적을 바탕으로 제약사는 cariprazine의 음성 증상에 대한 효과를 부각시키기 위해 노력하고 있는 중이지만, 2017년 미국 식품의약국(FDA)은 음성 증상에 대한 적응증을 인정하기에는 증거가 불충분하다고 불허하였고, 제약사는 추가적 임상시험에 대한 계획을 세우지 않고 있다. 그러나 미국에서는 허가외로 지속적인 음상 증상을 보이는 환자에게 점차 처방을 늘이고 있는 추세이다.

비슷한 시기에 미국 제약회사인 Minerva는 MIN-101 (roluperidone)이라는 신약에 대해, 지속적인 음성 증상을 보이는 환자를 대상으로 3상 연구를 시작하였다. Roluperidone은 5-HT~2A~ 및 <s>sigma-2 수용체</s>[^13-02-2] 길항제로 특이하게도 도파민에 대한 효과가 없다. 이 약물은 도파민 길항제라는 기존 패러다임과의 결별을 알리는 첫번째 항정신병 약물이기도 하다.[@Jones2020] 도파민에 작용하지 않기 때문에 원천적으로 추체외로 증상을 일으키지 않으면 속발성 음성 증상과도 거리가 멀다. 2017년에 결과가 발표된 3상 연구는 PANSS 음성 증상 총점이 20점이 넘는 환자만을 대상으로 하였는데, 위약군에 비해 효과 크기 0.45 (32mg/일 사용시), 0.57 (64mg/일 사용시)로 유의한 효과를 보였다. 아쉬운 것은 양성 증상에 대해서는 위약군과 차이를 나타내지 못했는데, 이는 도파민에 작용하지 않는 약물의 특성 때문일 수도 있지만, 임상 연구에 참여한 대상자가 이미 양성 증상이 안정된 상태에 있었기 때문일 수 있다.[@Davidson2017] 이러한 잠재력에 대한 열띤 기대에도 불구하고 좀더 규모를 늘린 3상 연구에서는 음성 증상에서 위약군과의 차이를 입증하는데 실패함으로써 향후 개발의 전망이 불투명해졌다.

[^13-02-2]: **Sigma receptor**: 원래는 아편 유사 성분에 결합하는 수용체로 처음 발견되었으나, 정작 아편양 수용체(opioid receptor)와는 구조적 유사성이 없다. 체내에서의 역할에 대해서는 거듭된 연구에도 불구하고 베일에 싸여있다. 할로페리돌이 대표적인 Sigma 수용체 길항제이며, 효현제를 투여하면 환각이 생기기 때문에 정신증, 기분변화와 연관이 있을 것으로만 짐작되어왔다. 1형과 2형이 있는데, 2형은 더더욱 그 기능이 알려져 있지 않다.

파킨슨 병에 동반되는 정신증상의 치료제로 허가받은 pimavanserin 역시 도파민에 작용하지 않는 새로운 개념의 항정신병 약물이다.[@Kianirad2017] 이는 5-HT~2A~에 대한 길항제 및 <s>역 효현제</s>[^13-02-3]로 도파민을 비롯하여, 노르에피네프린, 콜린, 히스타민 수용체에 결합하지 않는다. 따라서 운동증상을 악화시키지 않으면서 항정신병 효과를 나타내기 때문에 파킨슨 병 및 노인성 치매환자의 정신증상에 유용하게 사용된다.[@yunusa2020] 미국과 유럽에서 진행중인 2상 연구(ADVANCE study)에서는 주로 음성 증상을 보이는 안정기 환자에게 26주간 pimavanserin과 위약을 투여했는데, 음성 증상 호전에 있어서 유의한 차이가 발견되었다.[@bugarski-kirola2022] 그러나 효과 크기가 겨우 0.2에 지나지 않아, 새로운 적응증으로 허가를 받기에는 부족해보인다.

[^13-02-3]: **역 효현제 (inverse agonist)**: 길항제는 수용체의 자연적 기능을 차단하는 수동적인 역할만을 하지만, 역 효현제는 자연적 기능과 반대되는 작용을 일으킨다.

최근 수년 사이에 새롭게 임상에 도입되는 항정신병 약물은 D~2~ 수용체 차단이라는 고전적 작용기전에서 벗어나기 시작하였다. 이러한 약물이 원발성 음성 증상에 득이 될 것인지는 알 수 없지만, 적어도 비정형 약물보다도 진일보하여 속발성 음성 증상을 원천적으로 차단한다는 점에서 기대가 모아지지 않을 수 없다. 현재 신약 개발 파이프라인에 올라와있는 다양한 신물질 역시 음성 증상 개선을 타깃으로 활발한 연구가 진행될 전망이다.

## 항정신병 약물 이외의 약물 치료

### 항우울제

이상에서 본 바와 같이 각종 비정형 약물이 음성 증상에 미약하나마 효과를 보인다고는 하나, 음성 증상을 주된 타깃으로 하여 항정신병 약물을 쉽게 바꾸지는 못한다. 뭐니뭐니 해도 항정신병 약물을 선택하는 기준은 양성 증상 조절과 함께 내약성의 확보이다. 그러다보니, 음성 증상을 보이는 환자에게 의사들이 주로 시도하는 것은 병용 투여 전략이며, 그 중에서도 가장 많이 선택되는 것은 항우울제이다. 정신병후 우울증이나, 적응문제로 인해 우울 증세를 보인다면 당연히 항우울제를 사용하겠지만, 그렇지 않은 경우에도 항우울제가 도움이 된다는 견해가 있다. 플루옥세틴은 정형 약물 시절부터 소위 잔류 증상을 없애기 위해 병용 투여가 시도되었다.[@Spina1994; @Goff1995] 그러나 기대를 모았던 클로자핀과의 병용 투여가 아무런 이점을 보이지 못하면서 더 이상 임상 시험이 진행되지 않았다.[@Buchanan1996]

우리나라에서는 널리 사용되지 않지만, 역시 SSRI의 하나인 fluvoxamine 역시 일찍부터 기대를 받았다.[@Silver1992] 그러나 fluvoxamine은 클로자핀을 비롯하여 항정신병 약물의 대사를 늦추어 혈중 농도를 높이기 때문에, 이 효과가 클로자핀의 약효를 강화한 것 뿐인지 순수한 fluvoxamine의 효과인지는 분명하지 않다.[^13-02-4]

[^13-02-4]: 이러한 성질때문에 클로자핀의 복제약이 판매되기 전에는, fluvoxamine을 "poor man's clozapine"이라고 부르기도 하였다.[@Lu2000]

이후에는 단순한 SSRI 보다는 조금씩 다른 기전을 갖는 항우울제들이 주목받았다. Ritanserin은 항우울제라고 분류하기는 어렵지만 5-HT~2A~, 5-HT~1C~의 길항제로서 전두엽의 도파민 재흡수를 억제하는 효과가 있기 때문에 역시 1990년대 초반부터 임상시험이 진행되었다.[@Duinkerke1993; @ruiu2000; @Akhondzadeh2008] 몇몇 고무적인 결과가 있었지만, 임상에서는 사용되지 않았다. 한편 세로토닌 뿐 아니라 노르에피네프린 신호전달에 영향을 미치는 mirtazapine 역시 많은 기대를 모았다.\@Zoccali2004; @Berk2009], Mirtazapine를 사용한 이중 맹검 임상 시험 자료만을 모아 메타 분석한 결과에서도 효과크기는 1.0 정도로 꽤 크게 나타났다.[@Vidal2015] 특히 이런 효과는 우울 증상의 호전과는 독립적이었다. Mirtazapine은 클로자핀의 부작용 중 하나인 침흘림의 치료로서도 응용되곤 했으나, 체중 증가나 졸리움 등의 부작용때문에 더 이상 활발하게 사용되지는 못하고 있다. 최근에는 vortioxetine 역시 항정신병 약물의 부가요법으로 시도되어 가능성을 보여주고 있으나, 좀더 지켜봐야 할 것 같다.[@moazen-zadeh2020; @redaelli2022]

그 밖에 nortriptyline, 선택적 모노아민 산화효소 억제제(MAOI)인 selegiline 등이 부가 요법으로 시도되어 유의한 변화를 가져왔다고 보고되었으나, 일회성 보고에 그치고 있다.[@Bodkin2005] Duloxetine은 주로 노르에피네프린 재흡수 펌프를 억제하지만, 동일한 효소를 통해 전두엽의 도파민 재흡수를 억제하는 효과도 보인다. Nikbakhat 등[@Nikbakhat2016]은 이에 착안하여 리스페리돈에 duloxetine을 부가하는 전략을 시도하였는데, 양성 증상의 호전은 위약군과 차이가 없었음에도 불구하고, PANSS의 음성 증상 및 일반 증상 점수는 뚜렷이 감소하였다.

2015년 Fusar-Poli 등[@Fusar-Poli2015]은 음성 증상 치료전략에 대한 야심찬 메타 분석 결과를 발표했는데, 비정형 항정신병 약물치료의 효과 크기는 -0.579, 심리적 치료는 -0.396 이었음에 비해, 항우울제 병용 투여는 -0.349에 그치고 있었다. 분명 시도해보지 않은 것보다는 나았으나, 임상적으로 눈에 보이는 차이를 만들어내기에는 역부족이었다.

### 중추신경자극제

전통적으로 중추신경자극제는 조현병 환자에겐 금기사항이었다. 이들 약물은 도파민 운반체나 재흡수 펌프에 작용하여 도파민 활성을 높이기 때문이다.[@Dela2015] 게다가 암페타민 정신증은 초기 조현병 동물모델의 하나였고[@BELL1965], 메스암페타민(소위 필로폰) 역시 급성 정신증을 일으킨다. 그러나 주의력결핍과잉행동장애(ADHD) 환자에게 암페타민을 사용해도 중독되거나 정신증으로 발전하는 사례도 거의 없다는 것이 확실해지면서, 조심스레 음성 증상에도 시도되었다. 연구자들은 양성 증상이 경미하고 현재 항정신병 약물 치료를 받고 있다면, 별다른 위험없이 사용할 수 있다고 보기도 한다.[@lindenmayer2013] 초기에는 주로 ADHD에 사용하는 methylphenidate와 d-amphetamine을 사용했지만 최근에는 기면병에 사용하는 modafinil과 armodafinil이 자주 사용된다. 두 약물 역시 도파민 신호전달을 늘리며, 인지 기능 회복에 도움이 될 것으로 기대되었다. 최근 발표된 메타분석에서 이 두 약물이 음성 증상 치료에 통계적으로 유의한 변화를 가져온다는 것은 분명하지만, 효과 크기는 작을 뿐더러 만성 환자에게는 더 이상 효과가 없다고 하였다.[@Andrade2015] 이러한 결과들은 설령 기대에는 못 미치더라도, 조현병 환자에게 양성 증상의 악화없이 중추신경자극제를 사용할 수 있다는 새로운 사실을 알려주었다.

### 인지기능 개선제 및 글루타메이트 작용 약물

항치매 약물은 글루타메이트와 마찬가지로 처음에는 조현병 환자의 인지개선을 위해 연구되었다. 그러나 인지기능과 음성 증상을 따로 떼어내어 생각할 수 없는 것처럼, 어느 한쪽의 호전을 가져오는 약물은 다른 쪽에도 효과가 있기 마련이다.

인지 증상에 galantamine을 사용해보자는 착상은 조현병 환자들이 흡연에 집착하면서 저하되는 인지기능을 만회하려 애쓰는 현상에서 얻어졌다. 2009년 Conley 등[@Conley2009]은 86명의 조현병 환자에게 12주간 이중 맹검 위약 대조로 니코틴성 아세틸콜린 수용체 효현제인 galantamine을 투여하였다. 양성 증상 및 기타 음성 증상에는 효과가 없었지만, 특이하게도 무언증에서만큼은 유의한 효과를 나타내었다. 후속 연구에서는, 역시 α7 니코틴 수용체 효현제인 anabaseine(DMXB-A)이 무언어증과 무쾌감증 모두 호전시켰다.[@freedman2008] 그러나 최근 10년 사이에 이루어진 이중 맹검 임상시험에서는 모두 유의한 효과를 입증하는데 실패하였다.[@deutsch2013; @walling2015]

지난 20여년간 음성 증상 뿐 아니라 인지 증상의 호전이라는 영역에서 가장 관심을 모으고 있는 것은 NMDA 수용체를 통한 글루타메이트 신호전달 조절 약물들이다. NMDA 수용체의 과다활성은 흥분성 독성(excitotoxicity)을 일으켜 신경퇴행의 원인이 되기도 하지만, 적어도 음성 증상은 전두엽의 NMDA 활성 저하 때문에 일어나는 것으로 이해된다. 이는 phencyclidine, ketamine과 같은 NMDA 길항제가 음성 증상과 거의 유사한 정신증을 나타내는 데서 짐작할 수 있다. 일찍부터 d-serine, sarcosine, N-acetyl-cysteine, D-cycloserine 등 NMDA 수용체에 영향을 줄 수있는 다양한 약물들이 시도되었으나 일관성있는 효과를 얻어내진 못하였다.[@singh2011] 결정적으로 "The Cognitive and Negative Symptoms in Schizophrenia Trial (CONSIST)" 연구(2장 10-6절, article-02-10.html#치료적-함의)에서 음성/인지 증상에 대한 효과를 확인하는데 실패하였다.[@buchanan2007]

그러나 현대의 벤처 정신과 하이테크로 무장한 소규모 제약사들은 글루타메이트를 통하여 음성 증상을 해결하는 치료제를 개발하는데 투자를 아끼지 않고 있다.(2장 10-6절, article-02-10.html#치료적-함의) Glycine 운반체 억제제인 bitopertin과 AMG 747 은 제약회사 주도로 개발되어 1,2상 임상 시험에서 가능성을 보여주었으나, 대규모 3상 연구에서 효과 부족 및 안정성 문제때문에 개발이 중단되었다.[@Dunayevich2017; @Bugarski-Kirola2017]

이와는 대조적으로 NMDA 수용체를 차단하는 것이 오히려 음성 증상을 호전시키는데 도움이 된다는 증거가 있다. Memantine이 그 대표적인 예인데, 항치매제라는 특성에 입각하여 조현병 환자에게 병용 투여 해보기 시작하였는데, 예상 외로 긍정적인 효과를 나타내었다. 2017년 까지 진행된 8개의 임상 연구를 대상으로 메타 분석한 바에 의하면, PANSS 양성 척도에는 효과가 없었지만 음성 척도는 유의하게 감소시켰으며, 더불어 MMSE로 측정한 인지 기능 역시 위약 군에 비해 3점 정도 더 호전시켰다.[@Zheng2018] Ketamine과 같은 NMDA 길항제가 음성 증상을 나타낸다는 기존 이론과 어떻게 조화를 시켜야 할지 난감한 상황이 아닐 수 없다. 아마도 memantine이 ketamine에 비해 결합도가 낮고, 쉽게 해리되며, 전압 의존적이고, 시냅스 내 수용체보다는 시냅스 외 수용체에 주로 결합하기 때문에, ketamine과는 다른 특성을 보여주는 것 같다.[@Kikuchi2020]

### 성 호르몬

성별에 따라 음성 증상의 정도에 차이가 있는 것은 아니지만, 감정표현이나 공감 능력 등에서 여성이 더 우위에 있는 것은 사실이다. 남녀에 따른 발병연령이나 장기적 예후의 차이가 성 호르몬의 차이에 기인할 것이라는 가설로부터, 에스트로겐이 음성/인지 증상에 영향을 끼칠 것이라는 관찰은 이미 오래 전부터 있어왔다.[@ko2006; @van2013] 성 호르몬은 신경세포의 발달과정에 영향을 미치며, 피질의 두께, 시냅스 밀도 등에도 영향을 미친다.[@McEwen2017] 에스트로겐 농도가 낮아지는 생리 때나 산후 조리기, 갱년기 등에 정신증상이 악화되는 경우가 많으며, 역으로 임신 중에는 호전된다.[@Markham2012] 유사하게 남성에서는 조현병 환자의 테스토스테론 농도가 정상인에 비해 유의하게 감소해있기도 한다.[@Petrikis2020]

Oxytocin은 사회적 인지와 깊은 연관이 있고, 인간으로 하여금 대인관계를 추구하도록 부추기는 효과가 있다. 따라서 사회적 상황을 잘 이해하지 못하고, 대인관계에 대한 욕구가 없어지는 음성 증상과 밀접한 관련이 있을 것으로 예상된다.[@Shilling2016; @Goh2021]

이러한 이론적 배경 하에, DHEA, pregnenolone, raloxifene 등 성호르몬을 조절하는 약물을 사용하여 음성 증상을 호전시켰다는 보고가 있다.[@strous2003; @marx2009; @ritsner2014; @usall2015] Pregnenolone은 다양한 성호르몬의 전구물질로서 정상적인 체내에서도 합성된다. 이를 약물로 만든 것은 1950년대로 당시에는 류마티스 관절염 환자의 항염증 제제로 사용되었으나, 현재는 더 이상 사용되지 않는다. 신경계에서 중요한 역할을 하는 신경스테로이드(neurosteroid)일 뿐 아니라 카나비노이드 수용체(CB1)의 조절제이기 때문에 정신과 영역에서 다양한 방향으로 시도되었다. 조현병의 음성 증상 뿐 아니라, 인지기능 향상, 양극성 장애의 우울증, 생리후 우울증 등에서 가능성을 보이고 있다.[@cai2018] Raloxifene은 에스트로겐 수용체 조절제로서 주로 갱년기 여성의 골다공증 치료제로서 사용되어 왔다. 현재까지 주로 갱년기에 접어든 여성 조현병 환자의 인지 기능을 개선하기 위해 임상 시험이 시도되었다.[@kulkarni2016; @Gurvich2019] Oxytocin 역시 메타 분석에서 음성 증상에 중요한 역할을 할 가능성이 시사되었다.[@oya2015]

### 뇌자극술

전기경련 치료(ECT)는 주로 치료저항성 환자에서 사용되어 왔기 때문에, 음성 증상에 대한 효과만을 따로 논하기는 어렵다. 그러나 만성화되어 음성 증상이 우세한 치료저항성 환자에게 효과적이었다는 논문이 몇 개 발표되었다.[@pawelczyk2014; @tan2022]

치료저항성이 아니라 음성증상에 초점을 맞춘 연구에서는 전기경련 치료보다는 반복적 경두개 자기자극(rTMS)이나 경두개 직류자극(tDCS)이 더 관심을 모으고 있다. 적지 않은 연구결과가 있으나 아직까지는 효과 크기가 크지 않을 뿐더러 연구마다 격차가 심하다. 이는 아직까지 조현병에 대한 표준 치료 프로토콜이 마련되어있지 않고, 연구마다 자극 강도, 빈도 및 총 반복 횟수 등이 제각각이기 때문인 것으로 이해된다.[@freitas2009; @dlabac-delange2010; @prikryl2013] 최근 Wobrock 등[@wobrock2015] 은 175명을 대상으로 한 대규모 무작위 통제 시험에서 가짜 rTMS와 비교 시 이점을 찾는데 실패하였다.

rTMS는 ECT에 결부되어 있었던 부정적 이미지와 사회적 낙인을 벗어던지는데 성공하였고, tDCS는 rTMS에 동반된 비용 문제를 해결하였다. 근본 원리는 비침습적 방법으로 대뇌에 약한 전류를 흘려보냄으로써 신경세포의 탈분극을 자극하거나 억제하는 것이다. 처음에는 주로 환청을 조절하는데 시도되어 가능성을 보여주었는데, 동시에 음성 증상에 대해서도 적지만 의미있는 효과가 있다는 것이 관찰되었다.[@Brunelin2012] 이후 비록 소규모이긴 하지만 tDCS의 음성/인지 증상에 대한 임상 시험이 이어졌다. Pontillo 등[@pontillo2017]이 2018년까지 발표된 5개 연구결과를 분석한 자료에 의하면 그 중 세 개는 유의미한 효과를 발견하였지만 나머지 두 개는 입증에 실패하였다. 저자들은 역시 tDCS의 표준적인 치료법이 없다는데에 그 원인을 돌리고 있다. 마지막으로 100명의 조현병 환자가 참여한 비교적 큰 규모의 임상 시험에서는 음성 증상이 기저치의 20%이상 호전된 반응군의 비율이 tDCS군에서는 40%, 가짜 치료군에서는 4%로 현저한 차이를 보였다.[@Valiengo2020] 분명 앞으로 후속 연구를 진행할 가치가 있는 분야라 하겠다.

## References {.unnumbered}
