---
title: "조현병에서의 인지 증상"
editor: visual
bibliography: References/13-03.bib
---

## 개요

조현병의 인지 장애는 진단 기준에는 포함되어 있지는 않으나, 다른 증상과 대등하거나 오히려 좀더 근본적 증상인 것으로 여겨진다. 인지 증상때문에 환각/망상이 출현한다고 보긴 어렵다 할 지라도, 장기 경과, 치료 반응, 사회적/직업적 기능 회복의 정도, 삶의 질을 결정 짓는 가장 중요한 요인으로 손꼽히고 있다.[@elvevåg2000]

실상 거의 대부분의 조현병 환자가 임상적으로 유의한 수준의 인지 장애를 겪는다.[@keefe2007; @Bora2010] MATRICS Consensus Cognitive Battery (MCCB) (아래 참조)를 이용한 연구에서는 건강한 성인에 비해 1\~1.7 표준편차 낮다고 보고되었다.[@mccleery2019] 이에 비해 정동 정신병(affective psychosis) 환자는 60% 정도가 인지 장애를 보이고 그 정도는 건강한 성인에 비해 0.5 표준편차 정도 낮다고 보고되었다.[@reichenberg2008; @mccleery2019] 즉 인지 장애가 조현병에 특이한 것은 아니지만, 다른 질환에 비해 더욱 광범위하며 정도가 심하다. 또한 기분 장애와는 달리 관해기에도 인지 기능의 저하가 지속된다.

인지 기능의 저하는 아동기부터 관찰되기 시작하며, 청소년기에 접어들어 학업적 부담이 커지면서 더욱 격차가 벌어진다. 따라서 전구기 무렵에는 이미 정상인과의 차이가 분명해진다. 발병하지 않은 경우라도, 가족력이 있는 고위험군 역시 인지 기능이 떨어져 있을 가능성이 있다.[@fusar-poli2012] 이처럼 인지 증상은 질병단계의 초기부터 이미 나타나고, 더군다나 만성화되면서 점점 심화되는 것이 특징이다. 적극적인 치료를 하면 약간 향상되는 것처럼 보이기도 하나, 대부분 평생 지속되고 질환의 진행 단계에 따라 더 나빠지면 나빠졌지 좋아지지 않는다.[@schaefer2013] 양성 증상의 정도와는 깊은 상관관계가 없는 것으로 보아, 양성 증상과는 별개이 병태생리를 갖는 것으로 보인다.[; @keefe2012; @tripathi2018]

현대에 접어들면서 조현병 치료의 중점이 양성 증상의 소실에서 인지 기능의 보존 및 회복으로 차차 옮겨지고 있다. 약간의 양성 증상이 남아있는 것은 생활에 큰 지장을 주지 않지만, 인지 증상은 사회구성원으로서 의미있는 삶을 영위하는 것을 방해하기 때문이다. 이런 면에서 오히려 인지 기능을 감소시킬 수도 있는 항정신병 약물은 비판의 대상이 되어왔다.[@veselinovic2019] 분명 항정신병 약물 치료는 인지 증상을 호전시킬 수도 악화시킬 수도 있다. 이를 최대한 긍정적인 방향으로 끌고 가려는 것이 연구자들의 사명이요 과제이다.

## 조현병 인지 장애의 임상적 양상

조현병 환자의 인지 장애는 주의/집중력, 다양한 형태의 학습 및 기억, 언어사용, 작업기억 및 집행기능 등 대부분의 영역에서 발생하기 때문에 어떤 것이 조현병에 특징적이라고 말하기는 어렵다.[@elvevåg2000] 인지심리학자들은 지금까지 인간의 인지 능력이 최대한 세분화하고, 그 각각을 담당하는 뇌영역을 구분하는데 공을 들여왔다. 그럼으로써 갖가지 질병에서 특징적으로 드러나는 인지 증상의 독특한 패턴을 발견할 수 있으리라 기대하였다. 물론 치매나 뇌졸중에서 나타나는 인지 장애와 조현병에서 보이는 장애는 성상이 다르다. 그러나 조현병 환자 역시 너무나 광범위한 영역에서 저하가 관찰되기 때문에, 조현병을 다른 질병과 구분해주는 인지 저하 패턴은 발견되지 않았다.

굳이 조현병을 특징지워주는 인지 저하를 손꼽으라면, 인간과 하위 동물을 구분해주는 고위 인지 기능에서 그 차이를 찾는 것이 빠를 것이다. 조현병 환자에서 흔히 발견되는 양상은 인지적 자원을 적절히 배분하지 못한다는 것이다. 인간의 인지능력도 제한된 자원이기 때문에, 생존에 도움이 되는 쪽으로 최대한 경제적/효율적으로 활용해야 한다. 그러기 위해서는 부적절한 자극은 무시하고 나와 관련된 자극에 좀더 주의를 기울일 수 있어야 한다. 조현병 환자는 이러한 과제에서 실패한다. 예를 들어 바로 따라 외우기와 같은 단순 주의력 과제에서는 정상대조군과 별 차이가 없지만, 관련있는 자극을 선택하여 주의를 배분해야 하는 과제에서는 큰 결함을 보인다.[@fuller2006] 중요한 것과 그렇지 못한 것을 잘 구분하지 못하는 것은 P50 감각관문이나, 불일치 음전위(**mismatch negativity**, MMN)의 이상에서 엿볼 수 있듯이 정보 처리의 초기단계에서의 이상때문이기도 하나, 근본적으로 집행기능의 문제때문에 일어난다고 보여진다.[@mathalon2004; @Orellana2013]

일단 주의를 기울여야할 대상을 결정하곤 난 후에도 유지를 하지 못하는 것이 조현병 환자의 특징이다. 흔히 사용되는 스트룹 검사에서 환자들은 불필요한 자극에 쉽게 간섭을 받으며, 이는 내적 산만함 (internal distractability)을 반영하는 것으로 여겨진다.[@nuechterlein1984; @grillon1990; @Hahn2012] 숫자-기호 바꿔 쓰기(Digit Symbol Substitution Test, DSST)는 보통 정보 처리의 속도를 평가하는 검사로 인식되지만, 정해진 숫자-기호 표를 기억하고, 주의를 유지하는 능력을 평가하기도 한다. 정상인은 바꿔 쓰기 과제를 반복하면서 숫자-기호 표를 학습하기 때문에 점점 속도와 정확성이 높아지지만, 조현병 환자는 이런 현상이 보이지 않는다.[@dickinson2007]

주의력의 문제는 한 가지 대상에 고정한 상태를 유지하는 것 뿐 아니라, 상황이 바뀌면 다른 쪽으로 전환하는 것도 포함된다. 인지 전환 능력은 흔히 위스콘신 카드분류검사로 측정하는데, 환자들은 유달리 성적이 좋지 않다.[@franke1992] 문제해결의 한가지 방법에만 집착하여, 더 이상 해결에 도움이 되지 않는데도 놓지 못하는 것을 보속오류(perseveration error)라고 하는데, 이는 위스콘신 카드분류검사 뿐 아니라 선로잇기 검사 B에서도 일관되게 나타난다.[@Wölwer2002] 이러한 기능 저하는 계획과 조직화 능력의 결함이라고 이해할 수도 있다. 계획을 세운다는 것은 아직 일어나지 않은 상황에 대해, 행동 전략을 떠올리고, 이를 수행했을 때 뒤따를 수있는 결과를 예상하는 것이다. 다양한 전략을 상정하고, 이들을 머리 속에서 가상으로 수행해보면서, 최적의 결과가 예상되는 전략을 실제 행동으로 옮긴다는 것이다. 조현병 환자들은 이를 제대로 행할 수 없기 때문에, 한가지 전략에서 벗어나지 못하며, 문제를 해결하고자 하는 의욕이 있어도 실제 행동을 취하지 못한다.

이와 연관되는 인지적 능력은 소위 유창성 및 발산적 사고이다. 언어 유창성(verbal fluency)이란 정해진 시간 내에, 주어진 범주와 연관이 있는 사물의 이름을 최대한 많이 대는 것으로 측정한다. 이를 제대로 수행하기 위해선 범주의 경계를 지키면서도, 원할하고 광범위한 연상과정을 통하여 근접 범주에 속하는 사물의 이름들까지도 떠올릴 수 있어야 한다. <s>발산적 사고</s>[^13-03-1]란 고정 관념에서 벗어나, 자유로운 발상을 통해 새로운 문제해결 전략을 세울 수 있는 사고를 말한다. 유창성과 발산적 사고는 조현병에서 가장 떨어지는 인지 기능의 하나로, 환자들이 고정된 사고 패턴에 갇혀 빠져나오지 못한다는 것을 보여준다.[@vanbeilen2004; @nemoto2005; @nemoto2007; @waltz2017]

[^13-03-1]: 발산적 사고 (divergent thinking): 정해진 답이 없는 문제에 대해 다양한 관점에서 문제를 바라봄으로써 창의적인 해결 방안을 찾는 사고 전략. 수평적 사고(lateral thinking)라고도 불리운다. 고차원적 사고 패턴의 하나로 조현병 환자에서 떨어진다고 여겨지나, 일부 학자들은 환자들이 오히려 "정상"이라는 고정관념에서 벗어나 발산적으로 생각함으로써, 창조적인 영감을 얻을 수 있다고 주장하기도 한다.[@kaufman2014]

이러한 발견들을 종합하면, 조현병에서의 인지 장애를 단순한 언어구사의 문제, 계산능력의 저하 또는 기억력의 손상 등과 같은 개별 인지기능의 장애로 설명하기 어렵다는 것이 분명해진다. 하나하나의 인지수행 성적은 그리 떨어지지 않는데도, 실제 생활의 문제를 해결하는데 이런 기능들을 제대로 활용하지 못한다. 인간과 동물을 구분하는 고위 인지기능, 바로 이 측면이 제대로 기능발휘를 못하는 것이 조현병 환자의 어려움이라고 하겠다.

## 주관적 인지 기능 저하

질병인식불능증(anosognosia)에서처럼 병식이 없는 환자가 자신의 인지능력 결함에 대해서도 인식하지 못하는 경우가 드물지 않지만, 더 많은 수의 환자는 주관적으로도 인지 저하를 호소하며 고통받는다. 치료를 통해 주관적으로 경험하는 인지기능이 좋아지면 긍정적 강화를 제공하여, 약물 순응도를 높일 뿐더러 치료의 희망도 고양시킨다.[@naber1995]

그러나 조현병 환자가 호소하는 주관적 인지 문제(Subjective Cognitive Complaints, SCC)와 객관적인 인지 검사 수행 성적과의 상관관계는 없거나 매우 약하다.[@moritz2001; @chan2008; @johnson2011] 더욱이 특정 주관적 호소와 관련된 특정 신경심리학적 기능 장애도 확인된 바 없다. 환자가 "주의집중이 안 된다", "기억력이 떨어졌다"라고 할 때, 그들이 사용하는 "주의력", "기억력" 등의 용어는 전문가들이 사용하는 개념과는 거리가 있기 때문이다. 환자들이 인지 기능이 떨어졌다고 호소할 때, 그들이 원인으로 지목하는 것은 대부분 치료 약물이다. 약물에 대한 거부감이나 장기간의 약 복용으로 인한 불안, 우울이 주관적 인지 문제를 가져오기도 한다.[@baliga2020] 객관적인 인지기능 검사의 이상없이 SCC만 있는 경우 인지 장애로 보아서는 안된다.

그러나 환자의 호소를 불평으로만 치부할 수 없는 것은 실제로 항정신병 약물이 인지 기능을 저하시키는 경우도 있기 때문이다. 정형 약물을 고용량 사용하면 객관적 검사로도 인지 기능의 유의한 저하가 관찰된다.[@spohn1985; @spohn1989] 또한 그 정도는 용량과 유의한 연관이 있다. 고용량 사용 시 D~2~ 및 5-HT~2A~ 수용체 길항 효과로 글루타민 신호전달을 억제하여 인지 장해와 연관된 중뇌피질의 도파민 활성을 더욱 떨어뜨린다.[@liemburg2012; @sakurai2012] 고용량뿐 아니라 항정신병 약물의 다중요법이 인지 기능 저하를 심화시키며, 용량을 낮추거나 병용 투여되는 약물의 수를 줄이면 인지가 호전된다고 한다.[@hori2006; @élie2009; @torniainen2012]

클로자핀을 비롯한 비정형 약물은 이러한 기능 저하가 훨씬 경미하지만, 그래도 아주 없는 것은 아니다. 클로자핀과 리스페리돈으로 치료받는 환자들 역시 미미한 수준의 기억, 각성 수준, 주의력 결함을 경험한다는 보고가 있다.[@differen1996] Subjective Well-Being under Neuroleptics (SWN)을 사용하면 항정신병 약물 사용 후의 주관적 경험을 긍정적 혹은 부정적으로 평가할 수 있는데, 여기에는 주관적으로 느끼는 인지 증상도 포함된다. 정형 약물은 용량과 SWN 사이에 역상관관계(용량이 오를수록 안녕감이 줄어듬)를 보였는데, 비정형 약물은 오히려 정적 상관관계를 보였다.[@moritz2002] 이는 증상이 좋아지면, 약물에 의한 인지기능 저하에 대해서도 그다지 신경쓰지 않는다는 의미로 읽혀진다.

## 인지기능 평가도구

### 일반적인 인지기능 평가도구

#### 웩슬러 성인용 지능검사 (WAIS)

인지 평가에 전통적으로 가장 많이 사용된 것은 웩슬러 성인용 지능검사 (Wechsler Adult Intelligence Scale, WAIS)이다. WAIS는 1930년대에 개발된 Wechsler-Bellevue test로부터 유래한 만큼 역사가 길고, 방대한 임상자료가 축적되어 있는 검사이다. 당시만해도 <s>일반지능</s>[^13-03-2]이라는 개념이 보편적으로 받아들여질 때라, 소위 한 개인의 잠재적 지적 능력을 지능지수(IQ)라는 숫자 하나로 나타낼 수 있다고 믿었을 때이다. WAIS에서는 이 이론에 따라 전체 지능지수를 산출한다. IQ라는 단일 지표에 대한 논란이 거세지는 와중에, WAIS-IV 부터는 언어이해지표(Verbal Comprehension index), 지각추론지표(perceptual reasoning index), 작업기억지표(working memory index), 처리속도지표(processing speed index)의 네 가지 소척도가 계산된다. WAIS는 매우 포괄적인 검사이지만 시행에 두 시간이 넘게 걸리며, 애초에 조현병 환자에게 맞게 설계되지 않았다.

[^13-03-2]: **일반지능 (general intelligence)**: 여러가지 검사도구를 통해 지능평가를 하면, 얻어진 점수들 간에 강한 양의 상관관계가 드러난다. 심리측정학(psychometrics) 입장에서는 이러한 상관관계는 단일한 잠재요인(latent factor) 때문으로 설명할 수 있는데, 이러한 잠재요인을 g factor 혹은 일반지능이라 부른다. G factor에 대한 이론은 20세기 초 Charles Spearman이 처음 제기하였으며, 이후 인간은 단일한 정신적 역량이 있으며 이것이 현실에서 다양한 양상의 인지 기능으로 드러나는 것이라 생각되었다. 이러한 사고방식에 따라 소위 IQ (intelligence quotient)가 한 사람의 지적 역량을 대변하게 되었다. 그러나 실상 g factor는 통계학적인 개념일 뿐으로 정말 일반지능이 존재하는지, 아니며 서로 독립적인 여러가지 지적 역량이 존재하는지는 현재까지도 논란의 대상이다.

조현병 환자는 WAIS--IV의 거의 모든 하위 검사에서 유의한 저하를 보이는데, 그중 가장 차이가 큰 것은 처리속도 지표(processing speed)이다.[@Michel2013] 심지어 전체 IQ가 동일한 환자군과 대조군을 매칭시켜 비교했을 때에도 처리 속도가 유의하게 떨어진다. [@joyce2013] WAIS-IV가 발표되기 이전의 연구에서도 언어성 지능보다 수행성 지능에서 현저한 저하가 발견되었다.[@allen1998] Pollack 등[@pollack1970]의 고전적 연구에 따르면, 조현병 환자의 평균 IQ는 106.6이었는데, 아직 발병하지 않은 그들의 형제들의 평균 IQ는 114.7로 환자들보다 10점 정도 높았다.

#### 웩슬러 기억 검사-4판 (WMS)

WAIS와 같이 개발된 웩슬러 기억 검사(Wechsler Memory Scale, WMS)는 1945년에 발표되었으며, 지난 반세기 이상 일반인을 대상으로 가장 오래 사용되어 온 기억 평가 검사이다. 작업기억을 비롯하여, 즉각 및 지연 회상, 언어와 시각적으로 얻은 정보의 기억을 평가한다. 시각 작업기억(Visual Working Memory), 청각 작업기억(Auditory Memory), 시각기억(Visual Memory), 그리고 지연회상기억(Delayed Memory)의 4가지 지표를 얻을 수 있다.[@holdnack2010] 조현병 환자들은 모든 검사지표에서 대조군보다 낮은 수행을 보이며, IQ 수준을 통해 기대되는 기억력보다도 더 저조한 성적을 보인다.[@gold1992]

#### MATRICS Consensus Cognitive Battery (MCCB)

WAIS나 WMS는 환자군이 아닌 일반인을 대상으로 제작된 검사 도구이고, 장애의 정도라기 보다는 잠재된 학습 역량을 측정하는데 이용되었다. 따라서 조현병 환자의 인지 기능 저하를 민감하게 평가하는데는 적합하지 않다. 비정형 약물이 도입된 이후, 약물 효과를 판정할 때 인지기능에 대한 효과가 반드시 포함되게 되었으며, 기술의 발전으로 전산화 인지평가가 일반화되면서 최종 성적 뿐 아니라 반응의 세세한 측면까지 데이터가 기록될 수 있었다.

이러한 변화를 반영하기 위해 미국 국립정신건강연구원(NIMH)의 지원 하에 개발된 도구가 MATRICS Consensus Cognitive Battery(MCCB)이다.[@nuechterlein2008; @kern2008] MCCB는 주요인지 기능 영역을 포괄적으로 평가하는데, 이후 Brief Assessment of Cognition in Schizophrenia(BACS), CogState Schizophrenia Battery (CSB), Cambridge Neuropsychological Test Automated Battery(CANTAB) 등 유사한 평가 도구들이 탄생하는데 결정적인 영향을 미쳤다.

MCCB는 1) 검사-재검사 신뢰도, 2) 반복 사용 평가 척도로서의 유용성 3) 기능 회복과의 관련성, 4) 약물 치료에 대한 반응, 5) 편의성과 실용성을 기준으로 하여 처리속도, 주의/각성, 작업기억, 언어학습, 시각학습, 추론과 문제 해결, 사회인지의 7가지 인지기능 영역을 평가하는 10개 검사가 선택되었다. 이후 MCCB는 미국 FDA로부터 조현병 환자의 인지기능 관련 임상시험 사용을 승인 받았다.[@buchanan2010]

#### Brief Assessment of Cognition in schizophrenia (BACS)

Keefe 등[@keefe2004]이 개발한 BACS는 조현병에서 특히 저하를 보이는 6개의 인지 기능 영역 (언어성 학습기억, 작업기억, 운동기능, 주의와 처리속도, 언어유창성, 수행기능)을 평가하는데, MCCB가 90분 걸리는 데 비해 35분 이내에 간편하게 시행할 수 있다. MCCB 등 기존 인지기능 평가 배터리와 상관관계가 높으나, 아무래도 측정하는 인지기능 영역이 MCCB에 비하여 제한적이다.

#### CogState Schizophrenia Battery (CSB)

Maruff 등[@maruff2009]이 개발한 CSB는 컴퓨터를 이용한 전산화 평가 도구로 MCCB의 7개 인지 영역을 모두 포함하여 MCCB와 상관성이 높다.[@pietrzak2009] 시행 시간도 40분 정도로 짧고, 훈련받는 평가인력이 필요없다는 장점이 있다.[^13-03-3]

[^13-03-3]: 개발자인 Paul Maruff는 [CogState Ltd.](https://www.cogstate.com/)라는 회사를 창립하였고, 조현병 뿐 아니라 다양한 정신질환의 인지 평가를 위한 전산화 평가도구를 개발, 판매하고 있다.

#### Cambridge Neuropsychological Test Automated Battery (CANTAB)

CANTAB는 1980년대 캠브리지 대학교의 Barbara Sahakian과 Trevor Robbins의 주도하에 개발되기 시작하였다. 원래 영장류 등 동물실험에서 얻어진 인지 기능에 대한 최신 지견을 치매 등 신경퇴행성 질환을 앓고 있는 환자에게 적용하기 위해 고안되었으나, 이후 조현병을 비롯한 다른 정신 질환에 적용할 수 있도록 확대되었다.[@robbins1994; @barnett2015] 개발당시에도 이미 터치 스크린을 위한 전산화 평가도구란 점에서 혁신적이었으며, IPAD 등 저렴한 타블렛이 보급된 이후에는 보다 더 널리 보급되었다.[^13-03-4] 기억과 학습, 작업기억, 수행능력, 시각기억, 주의 및 반응시간, 의미/언어기억, 의사결정 영역을 측정하는 25개 과제로 구성되어 있다. 정확성이나 엄밀성이 뛰어나고 대부분의 과제가 비언어성 자극을 이용하기 때문에 문화 및 언어 차이를 배제할 수 있다. 현재는 상용화되었으나, 워낙 많이 보급된 탓에 거의 업계 표준으로 자리잡고 있다.[^13-03-5]

[^13-03-4]: CANTAB 검사는 비언어적이며 시각적 자극으로 구성되어 있어 언어장애를 지닌 환자들에게도 적용가능하다. 마찬가지로 언어나 문화에 구애받지 않기 때문에 전세계적으로 공통적인 규준을 얻을 수 있다. 또한 제시되는 시각 자극들이 매우 흥미롭기 때문에, 의욕이 떨어져 있는 환자들의 동기를 유발시키는데 유리하다.

[^13-03-5]: 현재는 [Cambridge Cognition](https://www.cambridgecognition.com/) 사에서 판매하고 있다.

### 조현병에 특화된 평가 도구

아무리 객관적인 검사로 인지기능을 검사한다고 할지라도, 실험실에서 측정된 결과가 실제 생활에서의 인지기능 발휘를 제대로 반영한다고 보기는 어렵다. 이 때문에 MATRICS 위원회에서는 임상시험에 인지기능 평가를 포함시키기 위해선, 면담을 통해 실제 수행 역량을 평가하는 부분을 추가하도록 하였다.[@mantovani2015] 아래 소개할 평가도구들은 실생활에서 조현병 환자의 인지적 기능 수준을 평가하는데 큰 도움이 된다.[^13-03-6]

[^13-03-6]: 미국 FDA는 2006년 제약사들에게 배포한 지침 자료에서, 신약의 효과를 판정할 때 환자들의 주관적인 효과 평가 (Patient-Reported Outcome, PRO)를 포함시킬 것을 강조하였다. 이는 객관적인 증상 호전뿐 아니라 환자 입장에서 약물의 효과를 어떻게 느꼈는지가 중요하다는 시각을 반영한 것이다.[@U.S.2006]

#### The Schizophrenia Cognition Rating Scale (SCoRS)

SCoRS[@keefe2006]는 일상 생활과 직접 관련된 인지 장애의 정도를 평가하기 위해 개발되었다. 사회인지를 제외한 MCCB의 모든 인지 영역에 대해 환자는 물론 주된 보호자로부터 얻은 정보를 바탕으로 평가한다. 이 평가도구는 주로 보고 내용에 근거하여 평가하므로 안면 타당도가 높은 대신 그만큼 주관성이 개입될 위험이 있다.

#### Clinical Global Impression of Cognition in Schizophrenia (CGI-CogS)

CGI-CogS는 치매 연구에서 사용되는 Clinical Interview-Based Impression of Severity(CIBIS)와 Clinical Interview-Based Impression of Change with input from caregivers (CIBIS/CIBIC+)를 표본으로 만들어졌으며, MCCB의 7가지 인지 영역 각각을 총 21항목으로 평가하도록 되어 있다.[@ventura2008]

#### Cognitive Assessment Interview (CAI)

CAI는 SCoRS와 CGI-Cogs에서 추출한 10개 항목으로 구성되어 있다.[@ventura2010] MCCB의 시각학습 항목을 제외한 6개 인지 영역을 포함한다. 역시 반구조화된 면담 도구로 환자와 보호자로부터 정보를 수집하여 평가하는데, SCoRS와 CGI-Cogs보다 짧은 시간에 실시 가능하다. 간단하기 때문에 임상 시험 중 반복 평가에 특히 유용하다.

## References {.unnumbered}
