---
title: "긴장증의 치료"
editor: visual
bibliography: References/14-02.bib
---

## 긴장증의 평가

### 평가척도

환자가 자신의 병력과 현증을 제대로 표현하지 못한다면, 환자와 함께 충분히 오랜 시간 동안 함께 지내면서 다양한 상황에서 환자가 어떻게 행동하고 반응하는 지를 관찰하여 진단을 내릴 수 밖에 없다. 전통적으로 만성 조현병 환자의 퇴행 정도를 판단할 때 그렇게 해왔으며, 긴장증을 평가할 때도 그렇게 할 수 밖에 없다. 그러나 이러한 방식은 효율적이지 못할 뿐더러, 연구 상황에서 객관성을 확보하기도 어렵고, 또 시간 경과에 따른 변화를 정량화하기도 어렵다. 일부 의사들은 긴장증의 한두 가지 특징적 증상만 확인하면, 진단이 어렵지 않다고 주장하기도 하지만, 그렇게 하다보면 놓치는 증상도 많아져서 전체적 임상 양상을 파악하기 힘들다. 따라서 짧은 시간 내에 보다 효율적으로 광범위한 증상군을 평가하기 위해 다양한 평가척도가 만들어졌다.[@fink2003; @Taylor2003; @fink2009; @Grover2015]

물론 긴장증의 개념 자체가 여러 차례 변하여왔고, 지금도 정확한 진단 기준에 대한 합의가 이루어지지는 않아 필요한 증상의 개수 라던가 최소 지속시간 등은 통일되지 않았다. 그러나 진단기준을 구성하는 증상 만큼은 대다수 평가척도가 일치되고 있으며, 특이도와 민감도가 높아 긴장증 평가에 매우 유용하다. 각각의 평가척도는 특정한 임상상황에 맞춰 개발되었기 때문에, 의사나 연구자가 당면한 목적에 따라 적절한 평가척도를 골라쓰면 된다.

#### Modified Rogers Scale Catatonic Subscale (MRS-C)

정신질환에 동반된 운동장애를 연구해왔던 Daniel Rogers는 긴장 증상이 추체외로 증상과 다르지 않다고 믿었다. 이 견해를 근거로 Modified Rogers Scale (MRS)은 심각한 정신질환 환자의 운동 증상과 추체외로 증상 평가를 포괄적으로 평가하기 위해 1985년에 개발되었다.[@Lund1991; @McKenna1991] 따라서 MRS에서는 긴장 증상과 추체외로 증상이 뒤섞여 있었는데, 이후 긴장증 척도의 임상적 필요성이 부각되면서 MRS의 항목 중 추체외로 증상을 배제하여 MRS-C가 만들어졌다. MRS-C는 따로 척도가 있는 것이 아니라, MRS로 평가한 후 일부 항목을 빼고 새로 총점을 구하여 MRS-C 점수를 얻어낸다.[@sienaert2011]

Starkstein 등[@Starkstein1996]은 MRS-C를 좀더 개선하여 Rogers Catatonia Scale (RCS)을 만들었으며, 이는 특히 우울증에 동반된 긴장 증상을 평가하기 위해 사용된다.

#### Bush-Francis Catatonia Rating Scale (BFCRS)

현재 가장 널리 쓰이는 긴장증 척도로 문헌 고찰을 통해 선정한 23가지 긴장증 증상으로 구성되어 있다.[@Bush1996; @Bush1996a] 첫 14개의 증상만 뽑아내어, Catatonia Screening Instrument (BFCSI)를 따로 만들었는데 이는 선별검사 목적으로 사용된다.[@Bush1996] 14개 증상 중 2개 이상이 24시간 이상 지속되면 긴장증일 가능성이 있는 것으로 판단한다. 선별검사의 목적 상 과도한 진단을 방지하기 위해 충동성과 호전성은 제외되었고, BFCRS와 달리 점수가 아닌 유무로 평정한다. BFCRI는 평가하는데 5분 밖에 걸리지 않아 임상에서 간편히 사용되며, 긴장증이 의심되면 좀더 오랜 시간을 들여 BFCRS를 평가하게 된다.

#### Northoff Catatonia Rating Scale (NCRS)

Northoff 등[@Northoff1999]은 단순히 기존 질환에 동반된 긴장 증상을 평가하기 보다는 긴장증이라는 독립적 질병 단위에 대한 평가를 하고 싶어했다. 따라서 긴장증에 기분 증상이 거의 예외없이 동반된다는 전제하에, 운동/행동 증상에 기분 증상을 추가하여 평가척도를 만들었다. 앞서의 척도들과는 달리 명확한 기준점이 있으며, 총점이 7점을 초과하면 긴장증이라 진단한다.

#### Brauning Catatonia Rating Scale (BCRS)

BCRS의 개발자들은 Rogers의 입장과는 반대로, 긴장증은 추체외로 증상이나, 파킨슨 병을 비롯한 기타 신경학적 질환의 운동 증상과는 구분되어야 한다고 믿었다. 이를 위해 긴장증에 특이한 증상만을 골라내어 평가척도를 만들었으며, 45분에 이르는 반구조화된 면담을 통해 진단특이도를 높이고자 하였다.[@Bräunig2000] 그러나 워낙 긴 시간이 걸리는데다가 평가자가 고도로 숙달되어야 하기 때문에 현실성은 떨어진다.

#### Katatonia, Autism, Neuropsychiatric and Neuromovement Examination Rating Scale

이 척도는 긴장증과 자폐증이 공통된 병태 생리와 치료 반응을 보인다는 Leo Kanner의 관점에 따라 자폐증에서 발현되는 긴장증을 평가하기 위해 개발되었으며, 다른 발달장애의 평가에도 이용되고 있다.[@carroll2008] 줄여서 Kanner Scale이라고도 부른다. 이 척도는 3부분으로 나뉘어 있는데, 첫 부분은 11가지 항목으로 구성된 선별 도구이다. 둘째 부분에서는 18항목을 0,2,4,6,8점으로 평정하고 셋째 부분에서는 상세하게 정의된 12가지 신경운동 검사를 하고 0\~1점으로 평정한다. 가장 최근에 개발되어 충분한 표준화가 이루어져 있지 않다.

### 감별진단 및 검사

긴장증을 확진할 수 있게 해주는 검사실 검사는 없다. 검사실 검사는 긴장증을 일으킬 수 있는 신경학적 혹은 기타 신체적 질환을 감별하기 위해 행해진다. 신경학적/신체적 질환이 있다고 해서 긴장증 진단을 내리지 않는 것은 아니지만, 근본적으로 치료 방침이 달라지기 때문에 반드시 관심을 두어야 하는 부분이다. 최근 들어 미국에서는 항 NMDA 수용체 뇌염에 대한 관심이 부쩍 늘고 있다. 항 NMDA 수용체 뇌염은 급격한 정신증 및 긴장증 증세를 보이는 데다가, 난소암 등 암성 질환과 연관이 있기 때문에, 긴장증 검사로 시작해서 암이 발견되는 경우도 드물지 않다.[@Bost2018]

응급실 등에서 긴장증이 강력히 의심되는 경우 치료를 겸하여 로라제팜 1\~2 mg을 정맥 주사한 후의 반응을 관찰한다. 만약 한두차례 시도 후에 증상이 50% 이상 감소한다면 긴장증이라 진단할 수 있다.[@fink2003] 로라제팜 주사를 반복할 때는 적어도 첫 주사 후 15분 이상 경과 후에 한다. 경우에 따라선 로라제팜 대신 수면제인 졸피뎀을 경구 투여하기도 한다.[@Thomas1997; @cottencin2009]

#### 감별해보아야 할 질환

과활동성 환자가 기이한 운동 증상을 보이는 경우, 긴장증 외에도 지연성 운동장애, 정좌불능증, 금단으로 인한 운동장애, 틱/뚜렛장애, 전환장애, 강박행동, 뇌전증, 섬망을 고려할 수 있다. 반대로 저활동성 환자인 경우 파킨슨병, 항정신병 약물 악성 증후군, 세로토닌 증후군, 간질지속증, 섬망, 혼수상태 등을 염두에 두어야 한다.[@dhossche2010]

긴장증이 흔히 발생하는 신경학적 질환으로는 항 NMDA 수용체 뇌염을 비롯하여, 역시 암성 질환에 동반되는 변연계 뇌염 (limbic encephalitis), 뇌전증, 다발성 경화증, 중추신경계 감염 및 두개내 종양을 꼽을 수 있으며, 신체질환으로는 전신성 홍반성 낭창, 저나트륨증, Wilson병 등 대사성 질환, Takotsubo 심근병 및 남용 약물 사용을 들 수 있다. 긴장증 증례 중 신경학적/신체적 질환이 차지하는 비율은 ¼ 정도에 달한다.

과거 정신질환의 병력이 있거나, 정신과 치료를 받고 있는 환자라면 원발성 긴장증일 가능성이 높지만, 고령에 과거 병력이 없다면 일단 신체질환을 우선시 해야 한다. 특히 의식혼탁 및 자율신경계 과다 항진 등 섬망에 가까운 증상을 보인다면 더욱 신체질환일 가능성이 높다. 긴장증 환자라면 설령 검사자에게는 반응을 보이지 않더라도, 환자가 혼자 있을 때 몰래 관찰해보면 주변 상황을 인지하고 있는 것처럼 보일 때가 많은데, 섬망 환자라면 그렇지 못하다. 뇌파검사에서 원발성 긴장증 환자는 대부분 정상 뇌파 소견을 보이지만, 신체질환에 의한 긴장증 환자의 80% 이상은 전반적인 서파를 보이는 것은 두 상태가 근본적인 차이가 있음을 시사한다.[@grover2014]

Bhati 등은 흔히 감별진단 해야 할 질환을 표와 같이 제시한 바 있는데, 물론 이들 질환이 긴장증과 공존할 가능성도 강조하고 있다.[@bhati2007]

| Differential diagnosis of catatonia          |                                                                                   |                                                                                                                               |
|----------------------------------------------|-----------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------|
| Diagnosis                                    | Characteristics similar to catatonia                                              | Distinctive characteristics                                                                                                   |
| Non-catatonic stupor                         | Immobility, mutism, absence of response to stimuli                                | Clear precipitating cause (e.g., head trauma, anoxia, drug intoxication)                                                      |
| Encephalopathy                               | Acute onset, bizarre behaviour, altered mentalstate                               | Typically occurs in the context of medical illness, reversible with treatment of underlying medical condition                 |
| Stroke                                       | Acute onset, can present with immobility,mutism and/or altered mental state       | History of cerebrovacular disease, focal neurological signs, CT/MRI findings                                                  |
| Stiff-Person syndrome                        | Immobility, posturing                                                             | Stiffness and spasms precipitated by surprise                                                                                 |
| Parkinson's disease                          | Immobility, altered mental state, comorbid mood disorder                          | Symptoms improved with dopamine agonists and anticholinergics, cogwheel rigidity                                              |
| Locked-in syndrome                           | Immobility, mutism                                                                | Complete paralysis with preserved vertical eye movements and blinking, associated with lesions in pons and cerebral peduncles |
| Malignant hyperthermia                       | Immobility, mutism, altered mental state, instability of autonomic nervous system | Hyperthermia secondary to inhalation anesthetics, autosomal dominant, diagnosed with muscle biopsy                            |
| Epileptic state                              | Immobility, mutism, altered mental state, bizarre behaviours                      | Epileptiform activity by EEG                                                                                                  |
| Autism                                       | Mutism, immobility, echolalia, echopraxia                                         | Chronic with onset at infancy or childhood                                                                                    |
| Obsessive-compulsive disorder (Severe forms) | Repetitive echophenomea, comorbid mood disorder                                   | Anxiety, awareness of compulsive behavior                                                                                     |
| Elective mutism                              | Mutism                                                                            | Possible underlying personality disorder or paranoia                                                                          |

#### 필요한 검사

긴장증이 의심되는 환자가 응급실에 방문할 경우 기본적으로 활력 징후의 확인을 비롯하여, 적혈구침강속도를 포함한 일반혈액검사, 일반화학검사, 신기능 및 전해질 검사, 젖산탈수소효소 및 크레아틴인산활성효소 검사 등이 행해진다. 동시에 흔히 사용되는 약물 또는 남용 물질에 대한 선별검사가 시행된다. 신경학적 검사가 행해진 후 미심쩍은 소견이 발견된다면, 뇌 자기공명영상검사, 뇌파검사, 뇌척수액 검사 를 행한다. 항 NMDA 수용체 뇌염을 감별하기 위해서는 뇌척수액이나 혈청에서 NMDA 수용체에 대한 IgG 항체 검사를 해야 하는데, 모든 진료기관에서 이러한 검사역량이 갖춰져 있는 것은 아니다. 경우에 따라선 자가 면역 질환을 감별하기 위해 항핵항체(anti-nuclear antibody) 등을 검사하게 된다.

## 긴장증의 치료

긴장증 환자는 원인과는 별개로 부동자세나 탈수, 영양 부족 등으로 인한 욕창, 심부정맥혈전증, 폐색전증, 발열, 감염, 요저류 및 요로 감염, 흡인성 폐렴, 전해질 불균형 등 이차적인 합병증의 위험이 높고 때로는 생명을 위협하기도 한다. 이를 교정하기 위해 정신과, 내과, 영양학자 등 다양한 직종의 통합된 노력이 요구되며, 코위삽관이나 정맥주사 등을 통한 적절한 수액 및 영양 공급, 도뇨관 삽입, 항응고제 처치 및 집중적인 간호 등이 제공되어야 한다.

### 약물치료

1930년대에 sodium amobarbital을 주사하면 강직증이 소실되면서 정상적인 면담이 가능해졌다는 <s>Bleckwenn의 보고</s>[^14-02-1] 이후 현재까지도 벤조디아제핀 특히 로라제팜이 긴장증 치료의 1차 약물로 선택된다.[@tollefson1982] 그러나 이는 의사들의 경험일뿐 긴장증에 대한 이중 맹검 임상 시험이 시도된적은 없다.[@Zaman2019]

[^14-02-1]: 1930년 미국의 신경과 의사인 William Jeferson Bleckwenn (1895\~1965)는 장기간 강직증세를 보이던 환자에게 다량의 sodium amobarbital을 주사하면 잠깐이나마 증상이 소실되어 정상적인 생활을 할 수 있게 된다는 것을 발견하였다.

진단을 겸하기 위해 시행하는 로라제팜 부하 검사에 반응을 보이면, 매 4-12시간마다 용량을 조절해가며 최대 1일 24mg 범위 내에서 반복 투여한다. 부하 검사할 때를 제외하고는 대부분 경구로 투여하며, 환자가 협조되지 않을 때는 근주, 정주 모두 가능하다. 주사제를 쓸 때는 과도한 진정 및 호흡 억제를 주의 깊게 관찰해야 한다. 하루만에 반응을 보이는 경우도 있지만 대개 늦어도 3\~7일 내에는 반응을 보인다. 정신질환 환자에서도 이보다 더 시간이 걸리는 수도 있긴 하지만, 치료 반응이 없다면 신경학적/신체적 가능성을 재조사 해보아야 한다.

로라제팜 투여 후의 관해율은 80% 정도로 추산된다.[@appiani2018] 물론 다른 벤조디아제핀을 사용해도 되는데, 로라제팜이 선호되는 것은 전통과 교육 탓이다. 실제로 로라제팜이 다른 약물에 비해 더 효과적인지는 연구조차 행해진 바가 없다. 벤조디아제핀을 언제까지 사용할지에 대해서는 아직 확실한 지침이 없다. 로라제팜 투여를 중단할 때마다 긴장증이 재발했다는 증례 보고도 있다.[@Manjunatha2007; @Grover2011]

Lin 등[@Lin2016]은 초기에 로라제팜 근주를 1\~2 회 시도한 후 그래도 해소되지 않으면, 이후에는 디아제팜 10mg을 생리식염수 500ml에 희석하여 시간당 1.25mg의 속도로 투여하는 방법을 제시하였다. 실제 임상에서도 흔히 사용되는 전략이다.

벤조디아제핀은 일시적인 긴장증에 대해서는 효과가 뛰어나지만, 만성화된 긴장형 조현병에 대해서는 효과를 기대하기 힘들다. 긴장증이 발생한지 얼마 안 되는 조현병 환자에서도 보고된 반응율은 2%에서 47% 정도로 격차가 크며[@Hatta2007; @Lin2016], 강직증상을 오래 보여온 만성 결핍성 환자에서는 거의 반응이 없다.[@Ungvari1999]

졸피뎀은 90년대 부터 이미 긴장증 감별을 위한 검사로서 이용되어 왔지만, 장기적으로 사용되는 경우는 거의 없다.[@thomas1997a] 하지만 벤조디아제핀과 달리 호흡 억제의 부작용이 없고, 드물지만 탈억제로 인한 증상 악화의 가능성이 떨어진다는 점에서 고용량의 로파제팜 대신 사용되기도 한다. [@peglow2013; @appiani2018]

긴장형 조현병 특히 만성 긴장 증상을 보이는 환자에게 벤조디아제핀이 전혀 효과가 없다면, 어쩔 수 없이 항정신병 약물에 기댈 수 밖에 없다. 원래는 긴장증 환자에게 항정신병 약물 특히 주사제를 고용량 투여하면 악성 긴장증 위험이 높아진다고 하여 금기시되어왔지만, 클로르프로마진과 할로페리돌을 투여하였을 때 각각 68%과 16%가 반응했다는 보고가 있다.[@Hatta2007]

이러한 위험을 비껴가기 위해 클로자핀과 아리피프라졸이 꽤 연구된 편이다.[@Bastiampillai2008; @Sasaki2012] 아리피프라졸은 조현병 뿐 아니라 우울증에 동반된 긴장 증상에도 효과가 있다고 한다.[@Sichert2021] 클로자핀은 주로 만성 긴장형 조현병에 사용하여 성공적이었다는 증례가 보고되고 있다.[@Chattopadhyay2012; @Tabbane2016] 그러나 오히려 더 문제가 되는 것은 오랜동안 클로자핀을 사용하던 환자가 갑자기 약을 중단했을 때 나타나는 금단성 긴장증(withdrawal catatonia)이다.[@Lander2018] 다른 항정신병 약물도 드물게 금단 후 긴장증이 나타나긴 하나, 클로자핀 처럼 중단한 지 2주 내에 급격하게 나타나는 경우는 드물다. 이 경우 클로자핀을 다시 투여하면 긴장증은 즉시 해소된다.

긴장증에 사용될 수 있는 항정신병 약물로는 D~2~ 부분 효현제인 아리피프라졸과 비교적 저역가 약물인 클로자핀, 퀘티아핀이 추천되고 있다. 고역가 항정신병 약물 특히 주사제는 악화에 대한 우려 때문에 벤조디아제핀이나 전기경련 치료가 실패했을 때 사용되며[@Beach2017], 긴장증이 풀리고 난 후 잔존하는 정신병적 증상을 치료하기 위해 사용된다.[@Sienaert2014]

이외에 실험적인 약물로는 NMDA 수용체 길항제인 amantadine과 memantine이 있다. 특히 amantadine은 도파민 활성을 증가시키고 정맥주사가 가능하다는 점에서 간혹 사용된다. 2016년까지 amantadine을 사용한 증례는 18례 보고되었으며 대부분 긍정적인 결과를 보였다.[@Sienaert2014; @Beach2017]

### 전기경련 치료

전기경련요법은 벤조디아제핀에 반응을 보이지 않거나, 악성 긴장증 등으로 진전하여 시간적 여유가 없을 때 사용될 수 있다. 더불어 신체질환이 있거나 노인, 임신부여서 약물 치료가 불가능할 때도 고려해볼 수 있다. 정신과 병력이 뚜렷하고, 신경학적/신체적 질환이 완전히 배제된 경우에는 적극 고려해볼 필요가 있지만, 정신과 질환 이외의 다른 가능성이 배제되지 못한 경우 전기경련 치료를 하는 것은 쉬운 결정이 아니다. 뇌압이 높아져있다던가, 뇌내 신생물의 존재, 뇌동맥류, 뇌졸중의 과거력, 심근경색 병력, 고혈압 등은 전기경련 치료를 피해야 하는 사항이다. 따라서 섬망과 긴장증의 감별이 중요하며, 전자에 가깝다면 전기경련 치료는 우선 순위에서 멀어진다. 물론 항정신병 약물 악성 증후군이나, 장기간 지속되는 섬망에도 전기경련 치료가 효과적이었다는 보고가 있기 때문에 절대적인 금기 사항은 아니다.[@Nielsen2014; @Morcos2019]

전기경련 치료는 급성 긴장증 환자의 80\~100%에서 반응을 이끌어내며[@Luchini2015], 기저 정신질환의 종류와 관계없이 가장 효과적인 치료법이다.[@ungvari2018] 흔히 1회 또는 수 회 실시로 증상이 좋아지지만, 더욱 장기간의 치료 혹은 유지 치료가 필요할 수도 있다. 대체로 2\~3일에 한번 정도로 시행하지만, 심한 긴장증 또는 악성 긴장증은 3-4일에 걸쳐 매일 실시해야 할 수도 있다.[@Sienaert2014]

급성 긴장증뿐 아니라 긴장형 조현병 환자의 치료에도 역시 우수한 효과를 보이며[@Pompili2013], 오히려 다른 아형의 조현병 환자보다 더 반응이 좋다고 주장하는 학자도 있다.[@Phutane2011; @Raveendranathan2012; @Santos2013] 만성 경과를 밟아온 긴장형 조현병 환자에게도 효과적일 수 있으나, 이 경우 치료를 중단하면 상당수가 재발한다.[@Malur2001; @de2013]

긴장증을 해소하는데는 단측성 전기자극으로 충분하다는 견해가 있다. 벤조디아제핀에 반응하지 않는 5명의 긴장증 환자에게 우측 단측성 전기경련 치료를 격일로 8\~12회 실시했을 때 4명은 완전관해를 보였으며, 나머지 1명은 양측성으로 변경해도 호전되지 않았다.[@Cristancho2014] 마찬가지로 또 다른 13명의 증례보고에서도 11명은 단측성 자극 후 빠르게 호전되었고, 나머지 2명은 양측성으로 변경해도 나아지지 않았다.[@Kugler2015] 어차피 치료가 안 될 환자는 양측성으로 해도 소용이 없고, 반응할 환자는 단측성 만으로도 충분하다는 의미가 되는데, 그렇다 하더라도 전기경련 치료에서 기본적으로 추천되는 방법은 여전히 양측성 자극이다.[@Kellner2010]

벤조디아제핀은 경련의 역치를 높이고 지속 시간을 단축시키기 때문에, 전기경련 치료를 할 때는 감량 혹은 중단하는 것이 원칙이다.[@Luchini2015] 그러나 함께 병용투여 하는 것이 더 효과적이라는 주장도 있다. 기분장애 환자 40명과 정신병 환자 17명의 의무 기록을 검토한 후향적 연구에서 전기경련 치료와 벤조디아제핀 병용은 모든 환자에게 효과가 있었다.[@Unal2013] 그렇다 하더라도 적어도 전기경련 치료 12시간 전후에는 벤조디아제핀을 사용하지 않으며, 불가피한 경우에는 작용시간이 짧은 로라제팜을 사용한다.

## References {.unnumbered}
