---
title: "물질/약물남용을 동반한 환자의 치료"
editor: visual
bibliography: References/16-01.bib
---

## 남용 및 중독

**"중독(addiction)"**이라는 용어는 의학 이외 영역에서 흔히 사용되지만 공식적인 진단명은 아니다. 의사들은 물질/약물 남용이 단순히 개인의 의지의 문제가 아님을 강조하기 위해 의도적으로 "중독"이라는 용어를 피해왔다. "중독", "중독자"라는 용어는 환자가 도덕적으로 타락했으며, 의지가 박약한 무능력자라는 경멸적 의미를 내포하고 있다. 따라서 의사들은 남용(abuse), 의존(dependence) 등의 용어를 대신 사용해왔으며, 바야흐로 DSM-5는 **물질 사용장애(use disorder)**라는 다소 무해한 것처럼 들리는 진단명을 채택하였다. 그러나 진단명이 바뀌었다고 낙인이 사라지는 것은 아니어서 알코올 사용장애 환자들은 현재도 주위의 경멸적 시각에서 자유롭지 못하다. 정신분열병 역시 오랜 편견과 낙인에 시달린 진단명이었고, 조현병으로 개명한 것도 "중독"이 "사용장애"로 바뀐 이유와 같다. 이런 상황에서 물질/약물 남용에 시달리는 조현병 환자라면, 이중의 낙인이 찍히는 셈이다. 이러한 심리사회적 문제를 다룰 수 있어야 환자를 제대로 치료할 수 있다.

### 남용의 의미와 신경생리학

남용 혹은 사용 장애란 삶을 유지하는데 필요하지 않은 특정 물질/약물/행위에 집착하고 반복함으로써 그 사람의 안위가 저하된 상태라고 정의할 수 있다. 전통적으로 남용은 알코올을 비롯한 기호품과 처방 약물 혹은 불법 약물과 관련된 것이었으나, 시대가 지나면서 약물이라 할 수 없는 물질(유기 용매 등)에 대한 남용이 부각되기도 했으며, 도박/인터넷/게임 특정 행위에 집착하는 것도 중독이라는 관점에서 보게 되었다.

인간은 생존 및 번식에 필요한 자극을 "좋은 것"으로 인식하며, 이를 방해하는 것은 "나쁜 것"으로 인식한다. 뇌의 현저성 회로(salience network)는 개체에게 이런 중요한 가치를 지닌 대상에 주의를 기울이도록 유도한다.[@uddin2017] 더불어 보상 회로(reward circuit)는 좋은 것을 더 추구하도록 하고, 나쁜 것은 회피하도록 한다. 보상 회로를 통해 생존에 필요한 대상이 등록되면, 그 대상의 결핍은 욕구를 일으키고, 욕구는 현저성 회로를 활성화하며, 활성화된 현저성 회로는 주변에서 그 대상을 집요하게 추구하도록 한다.[@cooper2017] 일단 대상을 획득하여 포만 상태가 되면, 현저성 회로는 비활성화 되어 당분간은 그 대상을 추구하지 않는다. 이 과정이 욕구의 항상성(homeostasis) 조절이다.

반면 문화적으로 즐기는 대상 혹은 기호품들은 사용자에게 만족감을 주지만, 생존에 필요하지도, 결핍을 보충하기 위해 사용하는 것도 아니기 때문에 욕구의 항상성 회로에서는 벗어나있다. 만끽하면 좋지만, 없어도 크게 개의치 않는 것이 이런 대상의 특성이다. 그런데 의도적으로 보상 회로를 건드리는 물질(불법 약물)을 사용하거나, 우연히 어떤 대상이 보상 회로와 현저성 회로에 등록되면, 만족을 위해서가 아니라 결핍을 채우기 위해 대상에 집착하게 된다.[@bagseoyeon2014] 더군다나 불법 물질 들은 욕구를 채워주는 기간이 갈수록 짧아지며 갈망을 점점 더 심화시키기 때문에 벗어나기 어려워진다. 이런 상태가 되면 소위 "중독"되었다고 한다. 이제 이들이 남용 대상에 집착하는 것은 결핍을 채우기 위함이지, 만족감을 구하기 위함이 아니다.

보통 사람에게는 중립적인 대상이 보상 회로와 얽히게 되는 과정은 암묵적 학습으로, 뇌의 비가역적 변화를 동반한다.[@koob2009; @volkow2011; @herman2015] 따라서 오랜 기간 남용 대상에서 떨어져 있었다 하더라도 뇌가 중독 상태 이전으로 돌아가는 것은 어렵다. 한번 중독자가 되면 평생 중독자라는 경고는 이런 이유때문이다. 남용 및 중독은 꾸준히 관리해야 하는 만성적 조건이지 완치되는 것이 아니다.

### 병존 진단의 문제

물질 남용/사용 장애는 조현병 환자에게 가장 많이 내려지는 병존 진단 중 하나이다. 주지하다시피 DSM 체계에서는 질병 원인이 아니라 증상에 근거하여 진단을 내린다. 이를 곧이곧대로 적용하면, 한 환자에게 다수의 정신과 진단이 동시에 내려지는 인위적 병존 진단 문제를 피해갈 수 없다.[@Maj2005] DSM은 원칙적으로는 진단적 서열 체계를 지향하고 있지 않지만, 일부 질환에 대해서는 서열을 적용하여 불필요한 병존 진단의 양산을 막고 있다. 예를 들어 정신병적 증상이 약물이나 신체질환에 의해 발생했다고 여겨진다던지, 자폐증 진단으로 환자의 문제를 보다 잘 설명할 수 있다면 조현병 진단을 내리지 않는 것이 그 예이다.

그런데 현행 진단 체계에서 물질 사용장애는 다른 진단과의 진단적 서열이나 배제기준의 적용을 받지 않는다. 조현병을 비롯하여 어떤 진단이라도, 물질 사용장애 진단을 함께 내릴 수 있다. 이는 정신질환에서 물질 사용장애가 차지하는 독특한 위치를 반영한다. 일반적으로 특정 진단에 부합되는 증상이 있긴 하지만, 그것이 주 진단의 결과로 나타났거나 주 진단의 한 부분으로 판단된다면 따로 병존 진단을 늘리지 않는다. 예를 들어 ICD-10에서는 조현병 환자가 강박 증상을 보인다 하더라도 강박증 진단을 내리지 못하도록 되어있다. 조현병과 물질 남용에도 이런 시각을 적용해 볼 수 있다. 예를 들어 많은 조현병 환자가 흡연에 의지하는 것에 대해, 조현병이 원인이고 담배 남용이 결과라고 생각할 수 있다. 그럼에도 불구하고 현행 진단체계는 주저없이 담배 사용장애를 따로 진단한다.

이는 물질 사용장애와 조현병이 별개의 병리과정에 의한다고 보기 때문이기도 하지만, 그보다는 물질 남용이 조현병 치료에 있어 특별히 고려해야하는 중요한 이슈이기 때문이다. 물질 남용은 조현병의 경과, 치료 반응, 순응도, 그 밖의 질병행동에 악 영향을 미치며, 조현병 증상은 물질남용을 조장하거나 남용에서 벗어나려는 노력을 방해할 수 있다. 따라서 병존 진단에 관련된 개념적 혼란과 상관없이 조현병과 별개로 물질 사용장애 진단을 내리는 것인 관행이다..

## 조현병과 물질 사용장애

### 유병률

조현병 환자에서 물질 사용장애가 진단되는 비율은 일반인에 비하여 3\~6배 높으며, 평생 유병률은 약 50%에 달한다고 한다.[@regier1990] 알코올 사용장애만 해도 유병률이 20\~60%로 집계된다.[@regier1990; @chambers2001; @Volkow2009] 그러나 물질 사용은 사회문화적 환경의 영향을 많이 받으며, 조현병 환자에서의 물질 사용 빈도도 예외가 아니다.[@mueser1990] 혼자 살거나 정해진 거처가 없는 조현병 환자는 물질 사용장애의 유병률이 매우 높은데 비해, 중산층 가정에서 가족들의 보호 아래 사는 환자들은 물질 남용이 크게 문제되지 않는다.

따라서 지역사회가 얼마만큼 물질 사용에 대해 허용적인가도 유병률에 영향을 끼친다. 서구 각국을 비롯하여 우리나라도 흡연율은 꾸준히 줄고 있지만, 알콜 사용빈도는 거의 변함이 없다. 흡연이 감소한 것은 폐암과의 직접적인 연관, 간접 흡연에 대한 계몽 등이 영향을 끼친 것으로 보인다. 이에 비해, 음주는 사회적 연대를 강화하기 위한 수단이자, 동시에 혼자만의 안락함을 제공하는 수단으로 여겨진다. 북미 지역에서는 마리화나에 대해 오히려 담배보다도 허용적인 분위기이며, 최근에는 이를 법적으로 용인하는 분위기이다.[^16-01-1] 그래서인지 흡연자의 비율보다 마리화나 사용자의 비율이 더 높을 정도이며, 이는 조현병 등 정신질환과 관련하여 심각한 보건 문제를 일으키고 있다.[@george2018; @crocker2021]

[^16-01-1]: 1960년대 미국에서 히피 문화가 발달했을때, 가장 많이 소비되고 배포된 약물이 cannabis(마리화나, 대마초)였다. 이로 인한 사회문제가 심각해지자, 미국 의회는 1970년에 Controlled Substances Act에 의거하여 마리화나의 사용과 소지를 엄격하게 단속하였다. 그러나 마리화나는 인류가 가장 오래 사용한 민간치료약이었고, 의학적 효과에 대한 연구가 꾸준히 이루어졌으며, 일각에서는 담배보다 폐해가 적다고 주장되었다. 오래전부터 암스테드담에서는 합법화되었으며, 2013년 우루과이, 2018년 캐나다와 태국, 2021년 멕시코에서 합법화되었다. 미국에서도 17개 주에서 기호용 마리화나가 허용되고 있다. 우리나라에서는 2018년부터 의료용 사용이 허용되기 시작했으나, 아직 기호용 사용은 불법이다. 2020년 UN 산하 마약위원회는 60년 만에 마리화나를 마약류에서 제외하였다.

### 물질 사용장애가 병발한 조현병의 문제

알코올, 대마초와 같은 일부 남용물질은 조현병 발병과 용량-의존적인 인과관계가 있다.[@tien1990; @miller2001; @vanos2002; @zammit2002; @donoghue2014] 인과관계가 확실하지 않더라도 물질 남용 여부는 조현병 발병위험을 1.38\~1.95배 높이며[@stefanis2014], 발병 연령도 낮춘다.[@mauri2006; @schimmelmann2012; @picci2013]

물질 사용장애가 동반된 조현병 환자는 양성 증상, 공격 행동 등 정신 증상이 더 심하고 자살률도 높다. 치료에 대한 순응도가 낮을 뿐 아니라 치료저항성을 보일 위험도 높다. 자기 관리가 안 되기 때문에 입원기간이 길고 재입원율도 높으며, 심리사회적 재활치료에 적응하지 못하기 때문에 노숙자가 될 가능성이 높다.[@duke2001; @murthy2012; @picci2013]

물질 사용장애와 조현병이 동시에 진단된 환자를 15년간 추적한 결과, 응급실 방문, 입원, 외래 등 의료시설 이용비율이 조현병 진단만을 갖고 있는 환자에 비해 유의하게 높았으며, 이 격차는 시간이 지날수록 심화되었다.[@schmidt2011] 이러한 결과는 물질 사용장애가 조현병의 장기 경과에 악 영향을 미치는 것으로 해석되었다.[@gouzoulis-mayfrank2014]

### 조현병과 물질 사용장애의 동반을 설명하는 모델들

조현병 환자에게 특히 물질 남용이 빈발하는데 대해 몇 가지 설명모델이 있다. 이는 두 질환이 공통된 위험인자를 가진다는 모델과, 물질 남용이 조현병이 결과라는 모델, 그리고 조현병이 물질 남용의 결과라는 모델이 있다.

물질 사용장애의 위험 요인으로는 남성, 낮은 연령 및 교육 수준, 높은 충동성, 감각 추구 등이 있는데[@drake2000; @gouzoulis-mayfrank2014], 이는 조현병의 위험 요인과도 겹치는 부분이 있다. 유전적 연구에서도 한 가계내에 조현병과 물질 사용문제가 공존하는 경우가 흔하며, BDNF, COMT, AKT 등 유전자는 두 질환에 공통되는 취약성 유전자로 거론된다.[@Khokhar2018] 이 이론을 주장하는 연구자들은 보상 회로의 이상은 물질 남용을 일으키는 위험 요인임과 동시에, 조현병 환자가 음성 증상을 일으키는 근본 원인이라고 여긴다.[@Green1999; @chambers2001]

조현병이 선행 원인이요, 물질 남용은 그 결과라는 대표적인 이론으로는 사회적 표류(social drift) 가설과 자가 투약(self medication) 가설이 있다. 전자에 의하면 조현병 환자는 질병 때문에 사회경제적 하위 계층으로 표류하게 되고, 이렇게 추락했다는 좌절감과 함께 낮은 사회계층 자체가 물질 사용장애의 위험요소라는 이론이다. 자가 투약 가설은, 환자들이 질병으로 인한 불안, 우울, 불면, 무력감 및 약물 부작용을 해소하기 위해 알코올, 담배, 중추신경 자극제 등을 사용한다는 것이다.[@chambers2001; @huang2019] 니코틴이 인지증상을 경감시키거나, 추체외로 증후군을 감소시킨다는 것은 잘 알려진 사실이다. 그러나 그 외의 목적으로 환자들이 물질 남용에 빠져든다는 증거는 희박한 편이다.

### 물질 남용과 조현병 발병 위험

처음으로 남용 물질에 접하는 시기가 청소년기이기 쉽상인데, 이 시기는 또한 조현병의 전구기나 초발 시기이기도 하다. 조현병의 전구기에 접어들었든 아니든 이 시기부터 쭉 사용하게 되는 물질이 이후 정신증 또는 조현병의 위험 요인이 될 수 있다.[@swendsen2010] 예를 들어 청소년기 대마 사용이 조현병 발병 위험을 높인다는 것은 잘 알려져 있다.[@kuepper2011; @vaucher2017]

마리화나처럼 분명한 인과관계가 밝혀진 것은 아니지만, 우려되는 약물은 여러 가지가 있다. 소아정신과 의사들의 홍보노력으로 말미암아 주의력결핍과잉행동장애(ADHD)는 이제 더 이상 생소한 질환이 아니게 되었다. 그런데 문제는 ADHD가 아닌데도 불구하고, 집중력과 학습효율을 높인다는 명목으로 중추신경 자극제 남용이 보편화되었다는 것이다. 중추신경 자극제의 만성적 사용의 결과는 물론, 성인이 되어서 약물을 끊었을 때 발생할 수 있는 금단 문제는 아직 제대로 미결과제로 남아있다.[@moran2019; @hollis2019] 더불어 날씬한 몸매를 추구하는 청소년들이 암암리에 사용하는 다이어트 약물 역시 문제가 된다. 중추신경 자극제나 다이어트 약물 복용 후 일시적으로 정신증상을 일으키는 사례를 드물지 않게 볼 수 있다. 우려되는 것은 이들 환자 중 일부는 약물을 중단한 뒤에도 정신병적 증상이 지속된다는 것이다.[@ujike2004]

위험 요인이 없는 청소년이 물질 남용에 의해 조현병으로 진전되는 경우보다는, 이미 조현병의 전구기에 접어들었거나, 위험 요소를 지니고 있어 병전 적응에 어려움을 겪는 청소년이 물질에 의지하는 경우가 더 흔할 것이다. 청소년기의 물질 의존은 조기 조현병을 발굴하고자 애쓰는 전문가들이 중요하게 여기는 지표 중 하나이다. 반드시 조현병이 아니라도, 다양한 정신질환 초기에 물질 사용이 증가하며, 이를 간과하여 놓치면 치료의 시기를 놓칠 뿐만 아니라 더욱 병을 심화시키는 결과를 초래한다.

최근에는 과다한 인터넷 사용이나 게임 몰입이 행위중독으로 여겨지기도 한다. 이런 행동이 정신질환을 일으킨다는 증거는 부족하지만, 앞서 물질 남용의 경우와 마찬가지로 심리적 어려움이나 정신 증상을 갖고 있는 청소년이 행위중독에 빠지기도 한다. 따라서 이러한 현상을 보이는 청소년에 대해 정신질환의 가능성을 열어놓고 대하는 것이 중요하다.

### 물질 남용과 조현병의 병태생리적 공통점

조현병과 물질 남용은 도파민과 보상 회로라는 공통 분모를 지닌다. 보상 회로에 도파민이 주요 매개체로 작용함이 알려지면서, 도파민이 "행복"을 가져다주는 물질처럼 선전되기도 하였지만 이는 사실이 아니다. 단적인 예로 도파민 과활성 상태인 조현병 환자는 전혀 행복하지 않다. 도파민이 보상 회로에서 맡는 역할을 중립적 대상에 현저성(salience)을 부여하는 것이다.[@robinson1993] 현저성이란 개체가 그 자극에 주의를 기울이고 그것을 추구하도록 만드는 자극의 속성이다. 이 자극은 즐거움을 가져올 수도 두려움의 대상일 수도 있다.

조현병에서 현저성 이론은 다양한 신경생리학적 관찰결과나 인지 증상을 설명하는데 사용되고 있다. 정상인은 정말로 중요한 것에만 주의를 기울이고, 나머지 것들에는 쉽게 자극을 무시할 수있는 반면, 조현병 환자는 불필요한 자극에도 현저성이 부여되어 자극을 걸러내기 힘들어한다. 조현병의 대표적 증상인 관계관념과 피해망상은 의미 없는 중립적 자극에 부적절한 현저성이 부여되어 나타나는 결과이기도 하다.[@Howes2016]

물질 남용 환자에서도 유사한 현저성 변화를 관찰할 수 있다. 중독의 대상이 된 물질은 강력한 현저성을 띠면서 환자에게 다가오기 때문에, 환자의 삶의 경험은 중독 물질을 중심으로 재구성된다. 알코올 사용장애 환자는 사소한 사회적 스트레스, 과거의 기억, 신체 불편감 등이 바로 술을 마시고 싶다는 욕구로 이어진다. 정상인은 술이 그다지 현저하게 다가오지 않기 때문에 이런 현상을 이해하기 힘들다. 항정신병 약물이 알코올 사용을 줄인다는 몇몇 연구 결과는 이런 이론을 뒷받침해준다.[@Zhornitsky2010; @Martinotti2016]

## 대표적인 남용 물질

### 알코올

알코올은 가장 흔하고 쉽게 구할 수 있으며, 흡연과 더불어 사회적 통제도 느슨하다. 따라서 조현병 환자에서 알코올 사용과 관련된 문제는 지극히 만연해있다. 알코올 중독까지는 아니고, 질병에 동반된 불안/불면을 해결하기 위해 알코올을 사용하는 경우라면, 해당 증상을 치료함으로써 음주 문제를 해결할 수 있다. 그러나 만성 음주자는 이미 안정제/수면제 성분에 교차 내성을 보이기 때문에, 이를 해결하려면 고용량의 약물이 필요하게 되며, 결국 안정제/수면제에 대한 남용이 새로운 문제로 등장한다.

이러한 환자를 치료하기 위해선 치료적 관계가 잘 형성된 의료진의 감독 하에 약물을 사용해야 한다. 처방 용량보다 약을 더 먹어버린다던지, 처방 약과 함께 술을 마시는 등의 문제를 솔직히 의료진에게 털어놓고 상의할 수 있는 관계가 된다면 치료될 가능성이 없지 않다. 환자들 중에서는 술과 함께 정신과 약물을 먹으면 위험하다는 생각때문에 오히려 항정신병 약물을 포함하여 정신과 약물을 아예 먹지 않는 경우도 있다. 이런 환자에게는 고용량의 안정제나 진정 작용이 강한 항정신병 약물을 사용하여, 음주 문제부터 해결해주어야 한다.

불안/불면을 해결하기 위한 음주가 아니라 음주 자체에 대한 갈망이 심한 경우, 다른 전략이 필요하다. 미국 FDA에서 알코올 중독 치료를 위해 허가한 약물은 disulfiram, acamprosate 그리고 naltrexone 뿐이다. 이중 disulfiram은 위험성 때문에 거의 사용되지 않고 있으며, acamprosate와 naltrexone을 보다 많이 사용된다. 두 약물은 정신병적 증상의 악화없이 조현병 환자의 알코올 갈망을 줄이는데 도움이 되는 것으로 알려져있다.[@Ralevski2011; @Sawicka2017] 또한 항정신병 약물 자체도 음주를 유도하는 충동성 및 현저성을 줄여주기도 한다.[@anton2017]

### 흡연

뭐니뭐니 해도 조현병 환자가 의존하는 물질 중 가장 흔한 것은 담배이다. 많게는 조현병 환자의 90% 가까이가 담배를 습관적으로 피운다고 한다. 알코올과 달리 니코틴이 직접 정신증상을 악화시킨다는 증거는 없다. 그러나 담배에 포함된 다양한 독성물질은 호흡기 질환이나 암을 일으며, 조현병 환자의 신체건강을 저해한다. 따라서 흡연을 통하지 않고 니코틴을 공급하는 것이 대안으로 시도될 수 있다.[@fairchild2018; @beaglehole2019][^16-01-2]

[^16-01-2]: 흡연을 통하지 않고 니코틴을 공급하는 방법으로 니코틴 패치가 있지만, 이는 흡연 습관을 대체하지 못한다. 최근 논란이 되는 것은 전자담배인데, 일부 학자들은 흡연을 중단시키지 못한다면 피해라도 줄여야 한다(harm-reduction model), 혹은 전자담배가 금연의 중간단계가 될 수 있다는 입장에서 지지한다.

전통적으로 과거의 정신병동은 흡연을 허용하여 왔다. 워낙 환자들의 욕구가 강할 뿐더러, 제약된 생활로 인한 스트레스를 푸는 유일한 수단이었기 때문이다. 환자들은 함께 담배를 피우며 연대의식을 강화하였고, 폭력사태의 발생을 줄이는 효과도 있었다.[@Olivier2007] 그러나 수년 전부터 모든 의료 시설은 공중보건 차원에서 흡연이 금지되었으며, 정신병동 역시 예외가 아니었다. 이 때문에 그야말로 담배를 피지 못하기 때문에 입원을 거부하는 사례도 드물지 않으며, 입원 직후 발생하는 니코틴 금단 증상을 정신증상의 악화로 보고 엉뚱하게 치료하는 경우도 생겼다.[@Soyster2016] 병원에서는 이런 환자에게 니코틴 패치를 공급하곤 하지만, 환자들의 흡연 욕구를 해소하기엔 역부족이다. 패취, 사탕, 껌 등 피부나 점막을 통한 니코틴 공급은 금단증상을 해소하는 데는 도움이 되지만 흡연 시의 고양감 및 흡연 행위 자체가 주는 만족감을 제공할 수 없다. 그래서인지 니코틴 패치를 이용하여 조현병 환자의 흡연양을 줄이려는 시도는 별반 성공적이지 못하였다.[@george2000]

최근들어 금연 치료를 위해 사용되는 부프로피온과 바레니클린은 정신적 부작용의 가능성을 완전히 배제할 수 없다.[@tsoi2013][^16-01-3] 그러나 정신증상이 악화되는 경우는 증례보고에 그치고 있으며, 대부분 안전하게 금연 유도에 사용될 수 있었다.[@Cerimele2012; @ahmed2018] 오히려 바레니클린이 P50과 같은 조현병 환자의 신경생리학적 이상을 경감시켜주거나 집행기능을 호전시킬 것이라는 기대도 있었다.[@Hong2011] 안타깝게도 이러한 기대는 후속 연구에서는 재현되지 못하였다.[@smith2016]

[^16-01-3]: 바레니클린 (Varenicline): α~4~β~2~ 니코틴 수용체의 부분효현제로 금연보조제로 사용된다. 부분효현제로서는 도파민 분비를 약하게나마 촉진하기 때문에 니코틴 금단 증상을 줄여주며, 길항제로서는 니코틴의 쾌감 효과를 차단한다. 한국에서 연구된 바에 따르면 호흡기 내과에 내원한 환자에게 금연보조제로 사용했을 때, 1,2,3년 후의 금연 유지율은 각각 43.6%, 30.6%, 32.8%이었다.[@kim2015] 하지만 2021년 제형에 포함된 nitrosamines가 암을 유발할 수 있다는 것이 발표되어 잠시 판매가 중단되었다가, 2022년 5월 새로운 제조공정이 확립되어 판매가 재개되었다. ([출처](https://www.fda.gov/drugs/drug-safety-and-availability/fda-updates-and-press-announcements-nitrosamine-varenicline-chantix))

조현병 환자의 장기적 신체건강을 꾀하기 위해 금연을 유도하는 것은 매우 바람직한 일이다. 그러나 생물학적으로 니코틴 의존에 취약하며, 음성증상 때문에 다른 즐거움을 찾지 못하는 조현병 환자에게, 일반인에게도 어려운 금연을 기대하는 것은 현실적이지 못하다. 이런 면에서 전자담배가 대안으로 제시되었다. 전자담배를 잘만 사용하면 흡연을 줄이는 효과가 있으며[@lindson-hawley2016], 담배를 끊지 못하는 만성 폐쇄성 폐질환(COPD)환자의 건강상태를 개선시켰다.[@polosa2016] 조현병 환자에서도 전자담배를 이용하여 과도한 흡연 습관을 경감시킬 수 있었다는 연구 결과가 있다.[@Caponnetto2013] 최근 연구에서는 40명의 조현병 환자를 대상으로 흡연 대신 전자담배를 사용하게 하였을 때, 12주 후 대상군의 40%가 금연에 성공하였고, 나머지 환자들도 절반 이상 흡연량을 줄일 수 있었다고 하였다.[@caponnetto2021] 그러나 실제 담배의 맛과 향을 재현하기 위해 전자담배에 <s>첨가되는 화학물질</s>[^16-01-4]이 여전히 건강에 악영향을 끼친다는 우려가 현실화되고 있다.[@matsumoto2020; @kosmider2020]

[^16-01-4]: 전자담배의 맛과 향을 내기 위해 acetaldehyde, acrolein, formaldehyde 등의 aldehyde, 그리고 살충제로 사용되는 acrolein이 포함되는데, 이들은 폐질환 및 심장질환의 위험을 높일 수 있다. 그러나 더 심각한 문제는 Vitamine E acetate이다. 미국에서는 2019년 무렵 전자담배를 핀 후 급사하는 젊은 환자가 급증하였으며, 미국 보건당국은 이를 "e-cigarette or vaping product use-associated lung injury (EVALI)" 혹은 "vaping associated pulmonary injury (VAPI)"라 칭하였다. 그 원인으로 일부 상품에 포함된 vitamine E acetate가 지목되었다.[@Boudi2019]

### 커피

커피 즉 카페인 섭취를 어디서부터 질병으로 보아야 할 지는 애매하다. DSM-5에서 카페인 사용 장애는 정식 진단명이 아니라 향후 연구가 필요한 잠정 진단으로 등재되어 있다. 진단 기준은 다른 물질 사용 장애와 유사하나, 일일 카페인 섭취량이 얼마 이상이어야 지나친 사용인지에 대해선 기준이 없다. 적절한 카페인 섭취는 오히려 건강에 이득이 되는 면도 있지만, 당연히 지나친 섭취는 문제가 된다.

조현병 환자는 대조군에 비해 카페인 섭취량이 평균 두 배 가량 높다.[@Schneier1987; @Strassnig2006] 항정신병 약물의 진정 작용때문에 힘들어하는 환자들은 카페인을 통해 이를 상쇄하려 애쓴다.[@Thompson2014] 카페인은 아데노신 수용체 길항제로 도파민 및 노르에피네프린 방출을 증가시키며, 집중력 증가, 각성 상태 유지, 기분의 고양을 일으킨다. 카페인의 효과가 여기서 멈추면 상관없지만, 고용량의 카페인은 불안을 증가시키고 불면을 일으킨다. 하루 500mg 이상의 카페인을 섭취하는 것은 건강에 해를 끼친다고 여겨진다.[@Thompson2014] 게다가 지나친 카페인 섭취는 도파민 활성을 올리기 때문에 정신병적 증상이 악화될 수 있다.[@hedges2009; @tibrewal2011] 하루 커피 6\~7잔 정도에도 정신병적 증상이 악화되거나 조증 삽화가 유발될 수 있다.[@cerimele2010; @peng2014; @frigerio2020] 최근들어 카페 문화가 일반화되면서 커피 한잔의 사이즈 자체가 커지고 있으며, 커피 이외에도 다양한 음료에 카페인이 들어있기 때문에, 본인이 의식하지 못하는 사이에 과량의 카페인을 섭취할 수 있다. 예를 들어 스타벅스에서 판매하는 톨 사이즈 커피 한 잔에는 150mg의 카페인이 들어있기 때문에, 4잔만 마셔도 위험 수치를 훨씬 초과한다. 최근 유행하는 에너지 음료를 비롯하여 캔커피, 심지어 커피우유에도 예상보다 훨씬 많은 카페인을 포함하고 있어서 주의를 요한다. 에너지 드링크가 급격한 정신병적 증상의 악화를 유발한 사례도 보고되었다.[@cerimele2010; @hernandez-huerta2017]

카페인 사용이 문제가 되어 치료를 받는 경우도 드물고, 정해진 치료법도 없는 형편이지만, 특히 조현병이나 양극성 환자의 경우에는 교육을 통해 지나친 카페인 섭취를 제한하는 것이 필요하다. 교육 내용에는 카페인의 섭취 경로나 포함된 카페인의 양을 비롯하여, 지나친 카페인과 정신병리와의 관계에 대한 내용이 포함되어야 한다.

## 물질유발성 정신증과 조현병의 위험

남용 물질의 사용으로 인해 정신증이 새로 발생할 수 있다. 알코올(F10.5) 및 마리화나(F12.5), 진정제(F13.5), 코카인(F14.5), 자극제(F15.5), 환각제(F16.5) 등이 모두 정신병적 장애와 연관이 있는데, 증상만을 놓고 보면 조현병과 구분이 어려울 때가 있다. 게다가 위험 물질의 반복적 사용으로 중추신경계의 구조적 변화가 생긴 경우에는, 유발 약물을 중단해도 정신증이 지속될 수 있는데 이때는 조현병과 구분하기 어렵다.[@núñez2002; @ujike2004]

### **중추신경계 자극제**

대표적인 중추신경계 자극제는 코카인과 메스암페타민(필로폰)이 있다. 이들은 도파민 운반체의 작용을 차단하여 재흡수를 억제함으로써, 시냅스 내 도파민 농도를 높이고 보상회로를 자극한다. 이들의 작용은 완전히 이해되지는 않고 있는데, 도파민 운반체 외에도 시그마 수용체(σ~1~)와의 결합을 통해 D~1~, D~2~ 수용체 활성을 변화시킨다.[@Navarro2013]

이중 특히 문제가 되는 것은 메스암페타민이다. 급성 코카인 중독은 조현병과 구분되지 않는 정신병적 증상을 일으키지만, 만성 코카인 사용으로 조현병이 발병한다는 증거는 없다. 이에 반해 메스암페타민을 장기 복용하면 뇌의 구조적 변화가 동반되며, 조현병의 고위험군에 있어 발병 위험을 직접 높인다.[@Aoki2013; @Li2014] 특히 한국을 포함하여 메스암페타민 남용 빈도가 높은 아시아 각국에서는 이런 현상을 체감할 수 있다. 태국에서 메스암페타민 복용으로 정신증을 일으켜 입원했던 449명의 환자를 추적 조사한 바에 의하면 이중 ⅕ 정도는 지속되는 정신병적 증상으로 인해 결국 조현병 진단이 내려졌다.[@Kittirattanapaiboon2010] 호주에서 조사한 바에 따르면, 초발 조현병 환자들이 메스암페타민을 반복적으로 사용했던 빈도는 일반인구에 비하여 10배이상 높았다.[@sara2014] 이미 조현병을 앓고 있는 환자가 메스암페타민을 사용하면 양성 증상이 심하게 악화되는 양상을 보인다.

메스암페타민에 대한 중독은 쉽게 치료되지 않으며, 정신병적 경험에도 불구하고 약물에 의한 고양감을 쉽게 포기하지 못한다. 대부분의 사용자는 불법적인 경로를 통해 약물을 추구하며 결국 치료감호소에 수용된다. 이를 계기로 약물에서 손을 떼는 경우도 있지만, 그보다는 오히려 동일한 약물을 사용하는 동료들을 만나거나 배급처를 알게 되면서 더더욱 악화되는 경우가 많다. 항정신병 약물은 메스암페타민이 주는 고양감을 차단하므로 메스암페타민 중독에 빠진 조현병 환자는 약물 순응도가 매우 떨어지며, 이 역시 자극제 사용과 별도로 정신증 재발의 위험을 높인다.

메스암페타민만큼 위험한 약물은 아니지만, 식욕억제제로 사용되는 펜터민, 펜디메트라진, 디에틸프로피온, 암페프라몬, 마진돌은 모두 중추신경자극제로 도파민과 노르에피네프린 활성을 높인다. 이들은 생각보다 중독성이 높기 때문에 우리나라에서는 의료용 마약류로 관리되고 있으며, 신규 허가를 받을 수 없게 되어있다. 그러나 우리나라의 체중 조절 관련 의료 시장의 규모가 워낙 크기 때문에, 이들 약물을 처방받고 있는 환자의 수는 생각보다 많은 것이라 예상된다.[^16-01-5] 이들 약품은 중독 문제뿐 아니라 일시적인 정신증을 유발하기 때문에, 조현병과 양극성 장애 환자에게는 절대로 사용해선 안 된다. 기존에 정신질환이 없던 일반인이 일과성 정신증을 일으킨 사례는 1960년대 이후 꾸준히 보고되었으며, 동일 환자가 펜터민을 사용할 때마다 반복적으로 정신증을 일으킨 사례도 보고되었다.[@Jo2019]

[^16-01-5]: 한국에서 집계된 바에 따르면 2020년 한 해에만 무려 3백만 명이 넘는 환자가 phentermine, phendimetrazine, diethylpropion, mazindol을 처방받았다. 아직은 30대 여성의 비율이 가장 많지만, 10대 청소년의 사용량이 2018년에서 2020년까지 25%나 증가하였다. ([출처](http://www.koreabiomed.com/news/articleView.html?idxno=10484))

식욕억제제로 유발된 정신증은 주로 환각이 주된 증상이며 사고 장애나 음성 증상은 드문 편이다.[@sookyoungkwak2017] 대부분 원인 약물을 중단하고 소량의 항정신병 약물을 사용하면 호전되기 때문에 조현병을 유발한다고 보기는 어렵다. 그러나 항정신병 약물의 부작용으로 체중이 증가하였을 때, 이에 대처하기 위해 담당 의사에게 알리지 않고 식욕억제제를 사용하는 조현병 환자들이 있다. 특별한 유발요인이 없거나 순응도가 떨어지지 않았는데도 갑자기 증상이 악화되는 비만 환자라면 의심해볼만 하다.

### 대마 제제

대마 제제(마리화나)는 주로 <s>대마초(weed) 및 수액(hashish)</s>[^16-01-6]의 흡연으로 사용되며, 대마 성분을 넣은 과자 등으로 경구 투여되기도 한다. 유효성분은 δ-9-tetrahydrocannabinol이다.[^16-01-7] 최근 유행하는 합성 대마류는 허브차, 알약, 오일 등으로 위장되어 유통된다. 대마초를 흡연하면 수분 내에 효과가 나타나기 시작하여 수시간 지속되는데, 통상 용량에서는 기분이 좋아지고, 불안이 감소하며, 음악에 대한 감정반응이 항진된다. 시공간이 왜곡되는 지각은 있을 수 있지만 환각은 드물다. 그러나 용량이 높아지면 이인증, 탈현실감을 거쳐 뚜렷한 환각과 망상이 나타날 수 있다.[@moore2007]

[^16-01-6]: 위드(weed)는 대마초의 꽃을 말려 굳어진 형태이다. 이를 훈제, 기화 또는 농축액으로 변화하여 사용한다. 반면 해시시(hashish)는 새싹이나 잎에서 수지를 분리하여 만든 대마초 추출물이다. 해시시는 매우 농축되어있으면 THC의 함량이 높아서 더욱 강력하다.

[^16-01-7]: 대마초에 들어있는 주 성분은 cannabidiol (CBD)과 δ-9-tetrahydrocannabinol (THC)이다. CBD는염증을 줄이고 통증을 완화하는 등 의학적인 목적으로 사용되나, THC 성분은 강력한 향정신성 물질로 기분의 고양, 환각 등을 일으킨다.

많은 나라에서 대마를 합법화하려는 움직임이 있다. 미국에서는 17개 주에서 대마 사용이 합법화되었고, 의료용 목적을 위한 사용은 35개 주에서 허영되었다. 대마는 중독성이 낮기 때문에 비교적 안전한 물질로 간주되며, 그 폐해도 다른 물질보다 적은 편이다. 그러나 한번 대마에 손댄 사용자는 이후 좀더 위험한 물질에 손댈 비율이 높아진다. 게다가 낮은 위험성에 비해 유달리 청소년기의 대마 사용과 후일 조현병 발병 사이의 관계가 꾸준히 지적되고 있다.[@kuepper2011; @vaucher2017] 조현병 위험인자가 없는 일반인의 경우 대마초 사용은 조현병 발병 위험은 1.4배 높이며, 이 비율은 대마 사용량이 늘어날 수록 증가한다.[@moore2007; @Marconi2016]

물론 대마 사용이 직접 조현병을 일으키는 것인지, 아니면 조현병 병전 단계에 놓인 환자들이 대마를 더 사용하는 것인지는 확실하지 않다. 조현병 환자가 대마 사용 장애 진단에 부합할 비율은 26.2% 정도인데, 흥미롭게도 만성 조현병 환자보다는 초발 환자나 전구기 환자에서의 비율이 1.5배 가량 높았다.[@hunt2018] 이 환자들이 전구기의 비특이적인 증상을 다스리기 위해 대마에 의지하고 있음을 시사한다. 이에 비해 종적관찰을 통해 조현병으로의 전환 비율을 다른 남용 물질과 비교한 연구에 따르면, 대마 사용으로 일시적 정신증을 겪은 환자가 결국 조현병으로 전환될 비율은 34%로 환각제(26%)나 중추신경 자극제(22%)보다 유의하게 높았다.[@murrie2019] 알코올 남용 환자가 조현병으로 발전될 비율이 10%임을 감안하면 얼마나 큰 위험인지 엿볼 수 있다. 대마와 조현병의 병태생리적 연관은 아직 밝혀지지 않았지만, 정신보건 측면에서 관심을 기울이지 않을 수 없는 주제이다.

### 환각제와 케타민

환각제는 약리학적으로 다양한 물질들이다. 카테콜아민, 세로토닌 등 단가아민계 효현제로 작용하는 약물이 한 부류이며, 케타민 등 NMDA 수용체 차단제가 두번째 부류이다. 카테콜아민에 작용하는 환각제에는 엑스터시, 메스칼린, psilocybin이 있으며, 세로토닌계에 작용하는 약물에는 엑스터시와 LSD가 있다. 이들은 주로 환시를 일으키며 기하학적 도형, 번쩍임 등 의미가 불분명한 것들이다. 조현병의 환각이 두려움을 끌어내는 것과는 대조된다. 환각을 기대하고 사용하기 때문에, 자신이 겪는 것이 환각이라는 병식은 보존된다. 그러나 약리작용이 사라진 뒤에도 환각을 재체험하기도 하며, 환각에 대한 기억이 생생하게 떠오르는 플래시백이 있을 수 있다. 플래시백은 자신의 의지로 조절되지 않으며, 불쾌감, 불안을 일으키기도 한다.

NMDA 수용체 길항제인 케타민과 PCP 역시 환각제로 분류된다. PCP는 불법 물질이지만 케타민은 마취보조제로 사용된다. 소량의 케타민을 복용하면 마취효과는 없으면서 다행감과 함께 환시, 환청을 체험한다. 기하학적 도형이 주로 나타나는 LSD 환각과는 달리, 케타민에 의한 지각 변화는 순수한 환각이라기보다는 지각이 왜곡되거나 동일한 지각에 대한 감정 반응이 달라진다. 맑은 의식하에서 환각이 생긴다기보다는 일종의 해리 상태에 빠지며, 마치 이상한 나라의 앨리스 세계에 들어선 것처럼 낯선 지각 경험을 하게 된다. 사용자들은 이 단계를 보통 긍정적으로 받아들이나, 용량이 높아지면 소위 "K-hole" 상태에 빠지게 된다. 이는 해리의 수준이 깊어지면서 의식 상태 자체가 변화한 것이다. 주변 세계를 인식하는 방식이 바뀌며, 가위에 눌린 것처럼 자신의 몸을 움직일 수 없다. 유체 이탈처럼 경험하기도 하며, 자신의 몸을 떠나 세계와 일체가 된 듯한 느낌을 받는다. 많은 환자들은 이를 공포스러운 경험으로 받아들이나, 반복 사용자들은 오히려 이 경험을 추구하기 위해 케타민을 찾기도 한다.[@Muetzelfeldt2008]

최근의 의료계는 케타민에 대해 긍정적 시각을 갖고 있다. 급성 통증에 대한 진통제로 케타민 정맥 투여가 미국 FDA 승인을 얻었으며[@kronenberg2002], 치료 저항성 우울증에 대한 <s>에스케타민</s>[^16-01-8] 비강 분무형 제제도 FDA 승인을 얻었다.[@singh2020] 케타민 사용은 통증이나 불쾌감을 즉시 사라지게 함으로써 강력한 학습을 일으키는데, 이는 물질 의존을 일으킬 위험이 매우 높다. 제약 회사나 당국에서는 에스케타민의 가격을 턱없이 높게 책정하여 이러한 위험을 줄이고자 하지만, 오히려 불법적 거래가 성행할 우려도 있다. 케타민 정신증은 조현병의 가장 유력한 동물 모델이라는 점에서, 케타민 상습 사용자가 조현병 유사 증상으로 발전할 위험이 우려되는 바이다.

[^16-01-8]: **에스케타민 (esketamine)**: 케타민의 광학이성질체 중 S(+)-ketamine 형태만을 가리킨다. 항우울 효과 자체만으로는 라세믹 복합체인 케타민이 에스케타민보다 우수하다고 하지만[@bahji2021], 케타민은 정맥주사로 투여되는데 비해 에스케타민은 비강 분무형 제제로 투여된다. 후자는 SPRAVATO®라는 상품명으로 판매되고 있다.

현재 불법 약물 시장에는 다양한 합성 마약 (소위 디자이너 드럭)이 유통되고 있다. 이들은 기존의 남용 약물들은 혼합하거나 화학구조를 변형시켜 제조하는데, 불법 물질로 지정되기 전까지는 합법적이라는 사법망의 맹점을 이용하는 것이다.[@luethi2020] 또한 의료용으로 허가된 약물이지만 암시장을 통해 불법 거래되는 경우도 흔하다. 케타민과 프로포폴이 그 대표적인 예이며 새로 등장한 methoxetamine 역시 이러한 암시장에서 거래된다. Methoxetamine 역시 조현병 유사 증상을 일으키는 대표적인 약물로 알려져 있다.[@corazza2013]

## References {.unnumbered}
