---
title: "조현병 환자의 임신과 출산"
editor: visual
bibliography: References/16-02.bib
---

## 여성 조현병 환자와 성적인 문제들

조현병을 앓고 있더라도 여성이라는 정체성은 어머니로서의 역할과 분리할 수 없다. 또한 심각한 정신질환을 가지고 있더라도 자녀를 양육하고 어머니 역할을 잘 해 내는 여성들이 많다. 하지만 질병으로 인한 증상과 판단력 저하를 비롯하여, 경제적인 어려움, 가정 해체나 가정 폭력과 같은 간접적인 요인들 역시 조현병 환자가 임신, 출산, 양육 과정을 제대로 헤쳐나가기 어렵게 하는 요인이 된다.[@kulkarni2015]

조현병 환자는 대인관계를 회피하여 이성을 만날 기회가 적고, 약물로 인한 고프로락틴 혈증때문에 임신 가능성이 떨어진다.[@howard2005; @vigod2012] 그러나 역으로 성폭력에 시달리거나, 문란한 성관계를 맺어 계획하지 않았거나 원치 않았던 임신을 하는 경우가 더 많다.[@sexualit1996] 여성 조현병 환자는 지속적이고 안정된 성적 파트너를 구하는 경우가 적고, 대신 일과성 성행위나 성범죄의 피해자가 되는 경향이 높으며, 성병에 걸릴 위험이 높고 피임률은 낮은 것으로 보고되었다.[@matevosyan2009] 이러한 원인으로는 계획성의 부족과 충동성의 증가, 위험을 제대로 평가하지 못하는 것, 의사소통 기술의 부족, 정보나 피임기술의 부족 등이 관련된 것으로 보인다.[@sexualit1996]

심각한 정신질환을 가졌다고 해서 성적 관심이나 욕구가 없는 것은 아니다. 오히려 치료진이 "정신질환자는 성적 파트너를 만나지 못할 것이다, 성에 무관심할 것이다, 성적으로 무능력할 것이다"는 식의 선입견을 갖고 있을 수 있다.[@kelly2004] 환자들 역시 성적인 문제를 먼저 꺼내기 불편해할 수 있다. 이런 식으로 환자와 치료자가 모두 성적인 문제에 대한 논의를 회피하다보면, 곤란한 문제가 발생하고 난 후에 서로를 탓하는 지경에 이를 수 있다.

진료실에서 뜬금없이 성적인 문제를 꺼내기는 양측 다 불편할 수 밖에 없다. 대신 지침서를 사용하거나, 활자화된 성 관련 정보를 제공하면서 의료진과 환자가 성에 관해 의논할 수 있다는 분위기를 조성하는 것이 먼저이다. 이러한 추세에 따라 조현병 진료의 포괄적 지침에서는 친밀한 성적 관계에 대한 상담을 포함할 것을 권하고 있다.[@quinn2011]

### 피임에 대한 상담

피임에 대한 상담은 여성 조현병 환자의 치료에 있어 매우 중요하다. 가임기 여성이라면 피임을 제대로 하고 있는지 확인해야 하며, 적절한 피임법을 교육/추천해야 할 수도 있다. 물론 현실적으로는 정신과 의사가 전문 지식을 가지고 있지 못할 경우가 많으므로, 산부인과 의사와의 협진이 필요하다.

경구용 피임약은 간단하면서도 효과가 우수하여 가장 흔히 사용되긴 하지만 조현병 환자에게 사용할 때는 조심해야 한다. 피임약은 CYP34A에 의해 대사되므로 클로자핀과 같은 항정신병 약물의 농도를 변화시킬 수 있다. 또한 심혈관 질환의 위험성을 높이기 때문에, 불건전한 생활 습관으로 이미 심혈관 질환의 위험성이 높아져 있거나 과다하게 흡연하는 환자에게는 추천되지 않는다.[@seeman2011] 게다가 모든 조현병 환자가 피임약을 일정에 맞추어 꼬박 복용할 것이라 기대하기도 어렵다.

경구용이 아닌 피임 방법(skin patch, subdermal implant, vaginal ring, transdermal gel, spray)은 약물 농도에 영향을 주지 않고, 매일 약을 복용할 필요가 없어서 조현병 환자에서는 더 유리하지만, 환자가 선호하지 않는다. 또한 방법마다 피임 성공률도 들쑥날쑥하다. 환자가 이렇게 많은 종류의 피임기법을 모두 알고 있으리라 기대해서는 안 된다. 가능한 방법들을 소개하고 환자의 선호도를 따져보아야 한다.

## 조현병 환자의 임신과 출산

### 임신이 조현병 증상에 미치는 영향

조현병의 호발 연령이 임신, 출산이 빈번한 연령대이기도 하기 때문에 여성 조현병 환자에서 임신은 중요한 주제이다. 그러나 임신이 조현병 증상에 어떤 영향을 주는 지에 대해 알려진 바는 거의 없다. 임산부가 정신과 진료를 받는 경우도 별로 없고, 모든 임상시험은 윤리적 이유로 임산부 및 피임하지 않고 있는 가임기 여성을 제외하기 때문이다. 대다수의 여성 조현병 환자는 약물이 기형을 유발할 지 모른다는 두려움 때문에 치료를 중단하며, 정신과 의사를 찾지 않는다.[@mcneil1984] 따라서 의사들이 경험을 쌓을 기회도 제한되어 있다.

연구의 어려움에도 불구하고, 연구되어야 할 분야는 너무나 다양하다. 임신때문에 약을 끊는 것도 문제이겠지만, 임신 중의 생리적 변화가 정신증상에 어떤 영향을 주는지도 의문이다. 임신이라는 스트레스가 증상을 악화시킬 수도 있지만, 오히려 심리적 충만감이나 증가된 에스트로겐이 증상을 경감시킬 가능성도 있다.[@pharmaco1996] 정상인도 산후우울증에 시달리는 경우가 많은 것을 고려했을 때, 출산 후 조현병 환자의 증상 변화도 연구 대상이 되어야 한다. 임신 중의 약물동역학 혹은 약력학적 변화 역시 의문에 둘러싸여 있기는 마찬가지이다.

임신 중에 증상이 악화되어 정신과에 입원하는 경우도 종종 있지만, 그 보다는 출산 직후에 증상이 급격히 악화되는 경우가 많다. 학자들은 그 원인으로 무엇보다도 에스트로겐 수치의 극적인 변화를 지목한다. 에스트로겐 농도가 상승되어 있는 임신 중에는 재발률이 줄며, 급격히 떨어지는 분만 직후에는 재발률이 다시 상승한다.[@kendell1987] 덴마크에서 이루어진 한 연구에서는 여성 조현병 환자가 출산 1개월 이내에 입원하는 비율이 5배로 높아진다고 보고되었다.[@munk-olsen2006] 높은 재발 위험은 산후 1년까지도 지속되는데, 이 때는 에스트로겐 변화보다는 수면 부족 및 육아 스트레스, 부부 관계 변화 등에 기인하는 것으로 보인다.[@howard2004] 임신 중에 약을 끊었더라도 출산 후 바로 약을 다시 복용하면 다행이겠지만, 수유를 위해서 꺼리기도 하고, 약물의 진정 작용때문에 아이를 제대로 돌보지 못할까봐 약을 먹지 않는 경우가 많다.

일반적으로 같은 조현병이라도 정동 증상을 동반했던 경우에, 출산 후 재발 위험이 커진다.[@taylor2019] 조현병의 재발인지 산후 우울증인지 구분하기 힘든 경우도 많다.[@howard2004] 조현병 환자의 임신 중 자살률은 매우 낮지만 출산 후 1년 이내 자살 및 영아살해의 위험은 상대적으로 높아진다.[@cantwell2016; @flynn2007] 그러나 출산 후의 우울/자살의 위험은 정동 장애의 병력이 있는 환자보다는 낮은 편이다. 많은 학자들은 임신과 출산이 정신병적 증상에 미치는 영향 보다는 기분 증상에 미치는 영향이 훨씬 큰 것으로 인식하고 있다.[@kumar1995]

### 조현병과 주산기 합병증

여성 조현병 환자는 수태로부터 출산, 산욕기에 이르기까지 다양한 산과적 합병증의 위험이 높다. 여기에는 유산/사산, 자간증/자간전증 (eclampsia/preeclampsia), 조산 및 저체중, 낮은 Apgar 점수, 선천성 기형, 돌발 영아 사망 증후군 등이 포함된다.[@dalman1999; @jablensky2005; @webb2006; @matevosyan2010; @vigod2019] 산과적 합병증이 증가하는 원인은 확실치 않다. 조현병 자체 보다는 흡연[@goodwin2012]*,* 물질 남용[@menezes1996]*,* 영양결핍이나 비만, 당뇨[@howard2012]*, 미흡한* 산전관리[@howard2005], 경제적인 어려움이나 가정 폭력[@trevillion2012] 등이 거론된다. 여성 조현병 환자는 임신을 알게된 후에도 흡연을 지속하기 쉬우며, 정신 증상이 심할수록 흡연의 양도 증가한다.[@aubin2012; @vigod2019] 유산 가능성 등 산과적 합병증이 임신 초기부터 흔한 것으로 보아, 조현병과 관련된 산모의 생물학적 위험인자가 산과적 합병증을 일으킬 것이라는 견해가 있다. 최근들어 조현병의 면역학적 가설이 설득력을 얻어가고 있는데, 산모의 항진된 체액성 면역(humoral immunity)과 태아라는 동종 이식(allograft)에 대한 과도한 거부반응이 유산의 위험을 높이는 원인으로 거론되고 있다.[@Jenkins2013]

문헌에는 압도적으로 주산기 합병증을 겪은 태아가 나중에 조현병을 일으킬 위험이 높다는 연구가 많다. 이에 비해 조현병 산모가 주산기 합병증을 일으킬 위험이 높다는 연구는 상대적으로 적으며, 있다 하다라도 산모의 생활습관 등 비생물학적 원인에 초점이 맞춰져 있다. 그러나 만약 생물학적, 유전적 원인으로 주산기 합병증이 증가하는 것이 맞다면, 조현병 산모는 조현병 자체때문에 주산기 합병증을 많이 일으키고, 그렇게 태어난 태아는 다시 조현병이 위험이 높아지는 악순환에 빠지게 된다. 이는 산모와 태아 간의 직접적 유전 인자 전달과는 또 다른 경로로 조현병이 물려내려지는 경우가 되겠다.

## 임신과 항정신병 약물

### 항정신병 약물과 기형

조현병 환자의 임신을 둘러싸고 의사와 환자 모두 골치를 썩게 되는 문제는 약물 사용과 태아의 건강 사이의 관련성이다. 그 중에서도 선천성 기형의 문제는 돌이킬 수 없는 과오가 되기 때문에 두려움의 대상이 된다. 일반적인 임신에서도 선천성 기형의 위험은 1\~3% 정도이다.[@updateo2008] 물론 대부분의 기형은 사소한 것으로 건강에 큰 위해를 가하지 않으며, 정말로 심각한 기형은 유산/사산되어 버린다. 심각한 정신질환을 가진 여성이 임신했을때 기형 발생률이 소폭 증가하는 것은 맞지만, 이는 항정신병 약물 사용과는 무관한 것으로 보인다.[@Abel2013; @galbally2014] 경도의 선천성 기형이 나타나는 빈도는 조현병 환자 뿐 아니라 그 친척에서도 여전히 높다.[@murphy1996; @bennedsen2001] 또한 조현병 환자가 처음 항정신병 약물을 투여받기 전에 출산한 아이들에서도 여전히 기형 발생률이 높았다.[@bennedsen2001] 이러한 증거는 약물 사용이 아니라, 환자를 둘러싼 유전적 또는 환경적 소인이 선천성 기형의 위험을 높인다는 것을 입증한다. 실제로 미국에서 백만 명이 넘는 산모의 자료를 대상으로 상대적 위험도를 조사한 바에 따르면, 교란 변수의 효과를 조절했을 때 항정신병 약물을 투여한 산모의 기형아 출산 상대적 위험도는 비정형 약물 1.05, 정형 약물 0.90으로 통계적으로 유의하지 않았다.[@Huybrechts2016]

그러나 동물을 이용한 전임상 실험에서는 기형 발생 가능성이 있는 것으로 나타난다. 항정신병 약물이 문제가 되는 것은 태반 장벽을 자유롭게 넘나든다는 것이다. 한 연구에 따르면 태아/산모 혈중 농도의 비는 올란자핀이 가장 높아 72.1%에 달했으며, 퀘티아핀은 23.8%에 머물렀다.[@Newport2007] 문제는 기형 발생 위험이 태아에서의 혈중 농도와 연관된다는 것이다. 전임상 실험에서는 연구에 따라 인간에서의 최대 허용 용량의 0.5배에서 10배까지 다양한 용량을 투여해보았는데, 과도한 용량이 투여될 수록 기형 발생률이 높았다. 60년대에 이루어진 정형 약물에 대한 실험과 비교적 최근에 이루어진 비정형 약물에 대한 실험을 비교하기는 곤란하지만, 다양한 선천적 기형이 발견된 정형 약물에 비해 클로자핀을 비롯한 비정형 약물은 그런 사례가 거의 없었다.[@iqbal2005]

### 항정신병 약물과 주산기 합병증

앞절에서도 언급했듯이 조현병 산모는 출산 시 다양한 주산기 합병증을 겪을 위험이 크다. 그러나 이런 현상의 원인에 항정신병 약물이 차지하는 비중을 어림잡기는 매우 어렵다. 호주에서 고용량의 항정신병 약물을 복용 중인 산모에서 태어난 100명의 신생아를 1년간 추적 조사한 바에 따르면, 18%가 조산이었고, 15%는 금단 증상을 보였다. 8%에서는 미세 신체기형이 발견되었다. 여러가지 이유로 말미암아 출생 직후 집중간호를 받은 태아는 43%였다. 조산 가능성과 항정신병 약물의 용량 사이에는 약한 상관관계가 발견되었다. [@kulkarni2014]

많은 연구자들이나 의사들이 공통적으로 경험하는 것은 산모가 고용량의 항정신병 약물을 복용하였을 때, 태아가 출산시 호흡부전을 보일 가능성이 높아지며, 안정된 이후에는 추체외로 증상이나 금단 증상을 보이기 쉽다는 것이다. 추체외로 증상은 근강직이나 늘어짐, 진전, 호흡 및 수유 곤란 등의 형태로 나타나며, 금단 증상은 지나친 보챔, 자극과민, 수면 장애로 나타난다. 대부분은 수일 사이에 소실되나, 이때문에 집중 간호를 받게 되는 경우가 많다. 하지만 금단 증상의 경우 항정신병 약물과 함께 처방되는 벤조디아제핀 때문일 수도 있어 구분이 어렵다. 미국 FDA는 모든 항정신병 약물의 약품 설명서에 이러한 위험이 기재되도록 규제하고 있다.

### 항정신병 약물과 향후 발달과정의 연관성

신체 기형 여부보다 훨씬 따지기 어려운 문제가 태생기에 항정신병 약물에 노출된 영아가 발달 과정에서 겪을 지 모르는 발달 지연이나 이상이다. 동물을 이용한 몇몇 전임상 연구에서는 항정신병 약물에 노출된 개체가 이후에 다양한 인지 과제에서 대조군보다 성적이 떨어짐을 보여주고 있다. [@zuo2008; @Singh2015]

인간을 대상으로 한 연구 결과는 좀더 복잡하다. 1989년 부터 2016년까지 태생기에 약물에 노출된 영아를 출생 후 1\~2년 동안 추적하는 9개의 연구가 있었는데, 이중 6개는 신경발달학적 지연을 보고하였고, 3개는 정상 발달은 보고하였다.[@poels2018] 특히 프랑스에서 행해진 EFEMERIS 데이터베이스를 이용한 연구에서는 다양한 향정신성 약물에 노출된 493명의 영아와 30,000명 가량의 대조군에 대하여, 생후 9개월과 24개월 두차례 운동 신경 발달을 비교하였는데, 9개월 째에는 거의 차이가 없었으나 24개월 째에는 현격한 차이가 드러났다. 24개월에 비정상적 운동 발달을 보일 오즈비는 무려 4.8배에 이르렀다. 물론 이 연구에는 항정신병 약물 외에도 항우울제와 항경련제가 포함되어 있었지만 우려를 자아내기에는 충분하였다.[@hurault-delarue2016]

이와는 대조적으로 역시 중앙화된 데이터베이스를 이용하여 영국에서 행해진 연구에 따르면 임신 후 항정신병 약물을 끊은 670명의 산모와, 임신 초기부터 약물을 복용해온 416명의 산모, 그리고 초기에는 끊었다가 임신 후반부에 약물을 다시 복용한 322명의 산모에게서 태어난 영아를 비교하였다. 그 결과 평균 2년 정도의 추적 기간 중 신경발달학적 문제가 발생한 비율은 세 군간에 차이가 없었다.[@Petersen2016] 동일한 연구에서 발프로에이트는 분명한 신경발달학적 문제를 일으키는 것으로 나타났던 것에 비하면 항정신병 약물은 상대적으로 안전했다고 보아야 한다. 프랑스에서의 연구와 영국의 연구가 차이나는 것은, 전자는 정상대조군과 비교했던 것이고, 후자는 약을 끊은 조현병 산모와 비교했다는 점이다. 조현병 고위험군인 자녀가 약물 노출과 관련없이 일찍부터 신경발달학적 문제를 보일 수 있음을 반드시 고려해야 한다. 이런 고찰에서 엿볼 수 있듯이, 대부분의 관련 연구들이 조현병 자체가 가지는 유전적 취약성이나 정신질환을 가진 산모의 양육 방식을 배제할 수 없는 연구 디자인을 하고 있어 결과의 해석이 난해하다.[@poels2018]

### 임신과 출산이 수반하는 약동학적, 약역학적 변화

약물이 산모와 태아에 영향을 미치는 것뿐 아니라, 임신/출산이 약물 대사에 영향을 미칠 수 있다. 임신을 하게 되면 체액이 증가하여 약물 농도가 떨어지며, 간기능/신기능의 변화로 대사율로 달라진다. 일반적으로 임신 기간 중에는 같은 혈중 농도를 유지하기 위해 더 많은 용량의 항정신병 약물이 필요하다.[@seeman2004] CYP2D6, CYP3A4, CYP1A2 등 주요 대사 효소의 활성이 증가하며[@Anderson2005], 신장으로의 혈류 증가로 인하여 소변을 통한 배설도 증가한다.[@seeman2004] 출산 후 성호르몬의 증가는 신경전달물질의 수용체 농도와 분포를 변화시킨다. 일부 학자는 이러한 약역학적 변화가 약동학적 변화를 상쇄시키기 때문에, 굳이 용량을 높일 필요가 없다고 한다. 임신으로 인한 변화는 보통 출산 후 3개월 정도면 정상화되지만, 더 오래 지속되는 특성도 있다.[@frederiksen2001] 이 모든 것을 이론적으로 따지기는 어렵고, 환자의 증상변화를 섬세하게 관찰하는 수 밖에 없겠다.

### 임신 중 약물치료를 하지 않았을 때의 위험성

항정신병 약물이 주산기 합병증을 늘리고, 영아의 신경발달학적 발달에 악영향을 끼친다면 약을 먹지 않는 것이 최선의 방책일 것이다. 그러나 운이 나빠 임신 중 재발했을 때 산모와 태아에 미치는 위험은 약물의 위험성을 훨씬 상회한다. 임신 중에 급성 정신병적 상태에 빠지면, 임산부와 태아의 생명마저 위협하는 응급 상황이 되어버린다. 정신 증상뿐만 아니라, 정신병적 상태는 시상하부-뇌하수체-부신 축(HPA axis)을 유의하게 활성화시키고 이는 태아의 중추신경계 발달에 악 영향을 끼친다.[@cohen1998] 앞서 살펴본 주산기 합병증 위험은 대부분 용량의존적인데, 재발을 하게되면 유지요법에 비해 훨씬 고용량의 약물치료가 필요하게 되므로 태아는 더 큰 위험에 노출된다.[@abel2014]

만약 출산 후에도 관해에 이르지 못하면 산모가 영아를 제대로 돌볼 수 없게 된다.[@abel2014] 육아와 관련된 이성적 판단을 할 수 없을 뿐더러, 영아와의 애착이 형성되지 못하며, 산모의 정신적 스트레스가 그대로 영아에게 전달된다. 부부 사이의 갈등이나 육아에 대한 부담으로, 자해나 영아를 학대할 위험이 커진다. 외국의 경우에는 육아 과정에 대해 외부 전문인력의 감독을 받아야 하거나, 양육권을 박탈당하기도 한다.[@howard2004]

따라서 임신과 출산을 둘러싼 의사 결정은 정해진 답이 있는 것이 아니라, 모든 잠재적 위험 요인을 고려한 후에 균형 감각을 갖고 결정되어야 한다. 증상이 경한 경우에는 약물 치료의 대안으로 심리사회적 치료를 강화할 수도 있으며, 임신 첫 삼분기에만 약을 끊을 수도 있다. 그러나 재발이 반복된 과거력이 있거나 증상이 중등도 이상이라면, 최소한의 약물을 유지함으로써 재발을 막는 것이 더 현명할 것이다.[@kulkarni2015; @schaffer2019]

## References {.unnumbered}
