---
title: "모유 수유 결정과 산후 정신병"
editor: visual
bibliography: References/16-04.bib
---

## 모유 수유의 결정

출산 후 정상적인 식사가 가능해지면 항정신병 약물 복용에 걸림돌이 없어진다. 임신 중에 정신병적 증상의 재발이 없었을 지라도, 출산 후에는 악화 및 재발의 위험성이 높아지는 시기이므로 임신 중에 감량 혹은 중지하고 있던 항정신병 약물을 증량하거나 다시 시작해야 할 때가 많다.그러나 많은 산모들이 약물 복용을 거부하는 이유는 수유와 관련된 두려움 때문이다. 실제로 항정신병 약물을 복용하고 있다면 모유 수유가 바람직하지 않다. 대부분의 항정신병 약물은 모유를 통해 배출되며, 오히려 산모의 체내 농도보다 모유에 더 농축되어 배출된다.

그러나 갓 태어난 영아에게 문제가 되는 것은 장기간 모유 수유를 할 때 뿐이다. 산모가 임신 중에 이미 항정신병 약물을 복용하고 있었다면, 영아는 태아 때부터 약물에 노출되어 있었기 때문에 <s>초유</s>[^16-04-1]를 몇 주 더 먹는다고 해서 크게 사정이 달라지는 것은 아니다. 설령 임신 중에 약물을 먹지 않았다 할 지라도, 일시적으로 약물에 노출되는 것은 영아의 건강에 큰 위해를 가하지 않는다.

[^16-04-1]: **초유(Colostrum):** 출산 후 2\~3일 후부터 나오기 시작하여 약 1주일 정도 나오는 모유. 면역글로불린, 락토페린, 림프구, 대식세포 등이 다량 포함되어 있어 신생아의 초기 면역 기능 확립에 도움을 준다. [@lawrence2022]

출산 후 1주일이 넘게 되면, 계속 수유를 해야할지 결정해야 한다. 모유는 우유에 비해 면역학적으로나 항산화적으로 질이 좋은 이상적인 영양공급원이다.[@newton2004] 더군다나 모유 수유는 산모와 아기의 정서적 안정 뿐 아니라 애착 형성에도 중요하다. 따라서 모유 수유가 금기인 경우를 제외하고는 가능한 모유 수유가 권장되고 있다. 항정신병 약물을 복용한다고 해서 절대적 금기가 되는 것은 아니다. 영아가 약물에 노출되어 생기는 잠재적 위험과 모유 수유를 하지 못해 생기는 불이익을 저울질하여 판단해야 한다. 그러나 결정의 중심은 약물을 복용하고 있는 상태에서 모유 수유를 할 지 말 지 이지, 모유 수유를 위해 약물을 장기간 중단할지로 초점이 옮겨가면 안 된다. 수유를 위해 투약을 계속 미루거나, 투약을 중단하는 것은 산모와 영아에게 더 큰 위험요인이 될 수 있다.[@spigset2015]

만약 모유 수유를 하기로 결정했다면 영아에게 노출되는 약물의 양을 최소화하기 위해 노력해야 한다. 모유로의 배출 양은 수유 시 산모의 혈중 농도에 비례하므로, 가능한 반감기가 짧은 약물을 최소 용량으로 복용토록 한다. 수유 시점을 약물 복용 직전이나 직후로 정하면 분비되는 약물의 양을 최소화할 수 있다. 아이에게 젖을 물리면 처음에는 묽은 전유(前乳, fore milk)가 나오다가 끝무렵으로 가면 지질 비율이 높은 후유(後乳, hind milk)가 나오는데, 항정신병 약물은 지용성인 경우가 많기 때문에 후유에 농도가 높다. 따라서 후유까지 먹지 않도록 신경을 쓰는 것이 좋다.[@Yoshida1997]

### 항정신병 약물의 모유 수유 위험도

산모가 각종 항정신병 약물을 복용하고 있을 때, 모유 수유를 통해 약물에 노출된 영아가 어떤 피해를 입을 수 있는가에 따라 각 약물의 모유 수유 위험도를 결정할 수가 있다.[@hale2022][^16-04-2] 이는 FDA에서 임신 중 약물사용이 태아에 미치는 위험성에 대해 A에서 X까지 등급을 나눈 것에 대응한다. 이 위험도는 가장 안전한 L1으로부터 위험성이 입증된 L5로 나뉘게 되는데, 대부분의 항정신병 약물은 "안전"에 해당하는 L2이거나 "비교적 안전"에 해당하는 L3이다. 따라서 일반적인 선입견과는 달리 모유 수유를 해도 크게 문제가 되는 것은 아니다. 모유를 통해 영아에게 피해가 가는 지 여부는 여러가지 요인에 의해 결정되는데, 그중 중요한 것은 약동학적 변인들이다. 약물의 지용성 정도에 따라 모유에서의 약물 농도가 결정된다. 산모가 복용하는 kg 당 약물 용량을 100이라고 했을 때, 영아가 섭취하게 되는 용량(mg/kg)을 상대적 영아 용량(relative infant dose)라고 하는데, 이는 퀘티아핀이 0.09인데 비해 아미설프라이드는 10.7로 약물마다 차이가 크다. 또한 영아는 아직 간과 신장에서의 대사가 성숙되지 않았기 때문에, 반감기가 긴 약물들은 체내에 축적될 위험이 있다. 항정신병 약물 중에는 리스페리돈, 퀘티아핀이 반감기가 짧으며, 아리피프라졸, 올란자핀은 긴 편이다.

[^16-04-2]: Hale's lactation risk category

실제로 모유를 통해 항정신병 약물에 노출된 영아에서 어떤 이상 반응이 나타나는 지에 대해선 체계적인 연구가 없고, 대부분 증례보고에 머무르고 있다.[@spigset2015] 하지만 모유를 통해 클로자핀에 노출된 영아 중 한명이 무과립구 혈증을 일으킨 것처럼 드물지만 심각한 이상반응이 나타날 때도 있다.[@dev1995adverse] 클로자핀은 L3 등급에 해당하며, 지용성 성질이 강하기 때문에 상대적 영아 용량은 1.33\~1.4 정도이다.[@Mehta2017]

Shao 등[@Shao2015]은 클로자핀을 투여받고 있었던 산모에게서 태어나 모유를 먹고 자란 신생아를 1년간 추적하여, 타 비정형 약물 투여 산모에게서 태어난 신생아들과 비교하였다. Bayley Scale로 조사한 발달 정도는 타 비정형 항정신병 약물군에 비해 유의하게 뒤졌으나, 이러한 차이는 12개월 후 완전히 사라졌다.

이에 비해 퀘티아핀은 상대적 영아 용량이 낮고 반감기도 짧기 때문에 영아에 미치는 영향이 작을 것으로 기대된다. 퀘티아핀을 사용한 6명의 영아 중 2명에서 정신운동성 발달이 다소 저하되었다는 보고가 있으나, 모유 내에서 약물이 거의 검출되지 않았기 때문에 관련 가능성은 낮아 보인다.[@Misri2006] 아리피프라졸에 노출된 영아가 지나친 졸음을 보였다는 보고가 있으므로[@nordeng2014], 지나친 늘어짐, 식이 불량, 수면 양상의 변화가 없는 지 살펴볼 것이 권고된다.

과거의 가이드라인들은 항정신병 약물 사용 중 모유 수유를 권장하지 않았지만, 이러한 권고가 꼭 임상적 증거를 기반으로 내려졌다고 보기는 어렵다. 앞서의 사례들을 모아서 정리해보면, 퀘티아핀, 올란자핀은 모유 수유를 해도 큰 문제가 없어보이고, 할로페리돌, 리스페리돈 등은 그 다음 수준으로 안전해보이며, 이에 반해 클로자핀, 아미설프라이드는 배출 정도가 높고 위험한 부작용이 있을 수 있어 삼가는 것이 좋을 듯 하다.[@klinger2013] Uguz[@uguz2021]은 현재까지 모아진 증거들의 양과 내용을 기반으로 각종 향정신성 의약품을 투여받고 있는 산모의 모유 수유 가능성을 점검하는 채점표를 제안하였다. 이 표에서도 역시 올란자핀, 퀘티아핀, 리스페리돈, 지프라시돈은 상황에 따라 투여할 수도 있다고 되어있으나, 아리피프라졸, 아미설프라이드, 클로자핀은 증거 부족으로 인해 모유 수유가 추천되지 않았다.

결국 모든 사람들을 만족시킬만한 임상적 증거는 모아지지 않았고, 치료 가이드라인도 공허하게 원론을 반복하는데 그치고 있다. 항정신병 약물은 모유로 분비되는 것은 사실이며, 장기간에 걸친 약물 노출이 어떤 결과를 가져올 지 알 수 없지만, 실제로 보고된 이상 사례는 드문 편이다. 결국 모유 수유가 가져올 잠재적 위험과, 모자 상호작용의 이점을 놓고 주관적으로 결정할 수 밖에 없으며, 영아에 대한 소아과적 검진을 꾸준히 한다면 모유 수유를 못할 이유가 없다. 하지만 더욱 중요한 것은 모유 수유를 하기 위해 약물을 중단하는 일은 없어야 한다는 것이다.[@Hasan2015]

### 수유를 하지 않기로 결정한 경우

산모가 영아를 위해 모유 수유를 포기하기로 했다면, 자연스럽게 모유 분비가 중단되도록 유도해야 한다. 영아가 젖을 빨지 않으면 자연적으로 수유가 중단되기도 하지만, 항정신병 약물의 프로락틴 상승 효과때문에 유즙 분비가 중단되지 않을 수 있다. 젖을 짜내지 않으면 통증이나 염증이 생기기 때문에, 산모를 위해선 이 문제 역시 신경을 써 주어야 한다. 이러한 목적으로 가장 많이 쓰이는 약물은 D~2~ 효현제인 bromocriptine이다. 비록 항정신병 약물과 bromocriptine이 서로의 작용을 방해할 수 있으며, bromocriptine 사용 후 정신병적 증상이 악화된 증례도 보고되고 있지만[@Pearson1981], 대다수의 경우에는 큰 문제없이 사용될 수 있다.[@olbrich1994] 일부 저자는 대안으로 cabergoline을 추천하기도 하지만[@baezapertegaz2002], cabergoline 역시 정신병적 증상이나 조증 증상 악화의 위험으로부터 완전히 자유롭지 못하다.[@chang2008]

## 신생아기 항정신병 약물의 금단증상

만약 산모가 임신 중에 항정신병 약물을 지속적으로 사용했을 경우, 출산 후에 신생아 체내의 약물 농도가 급격히 줄어들면서 금단증상을 일으킬 수 있다. 그런데 신생아의 약물 배설 능력이 성인과는 다르기 때문에 예측하기 어렵게 나타날 수 있다.

엄마 뱃속에 있을 때 태아 체내의 약물 배설은 태반을 통해 이루어지기 때문에, 약물이 축적되는 경우는 거의 없다. 그러나 출산으로 태반 연결이 끊어지면 이후의 약물 대사는 전적으로 신생아 자신의 기관에 의존해야 한다. 영아의 약물 제거 능력은 출생 직후 성인의 33%, 생후 7개월에는 성인의 68%, 그 이후로는 성인 수준에 도달한다.[@ring1999; @gow2001] 따라서 출산 직전에 산모를 통해 투여된 약물이 신생아의 체내에서 제대로 배출되지 못할 가능성이 있다. 특히 미숙아에서는 간과 신장의 발달이 더뎌 더욱 배설이 늦어진다. 혈중 빌리루빈치가 높은 미숙아들은 알부민 수치가 떨어지기 때문에 비결합 약물의 비중이 높아질 수 있다. 이러한 생리학적 차이는 축적된 약물이 악영향을 미치는 요인이 될 수도 있지만, 역으로 급격한 농도 감소로 인한 금단 증상을 막아주는 역할을 하기도 한다.

신생아 금단 증후군은 대표적으로 바비튜레이트 및 벤조디아제핀 등의 진정제에서 흔히 나타난다.[@levy1993] 산모가 출산 직전까지 약을 먹고 있는 경우 금단증상의 위험이 높아지나, 출산 전 1주일 이상 약물을 끊었던 경우에는 잘 나타나지 않는다. 전술한대로 약물의 배설이 성인보다 늦기 때문에, 금단 증상의 발현 시기는 출생 직후부터 출산 후 3주까지 다양하다. 약물의 종류에 관계없이 증상은 비슷하여 이자극성, 불면, 진전, 주먹 빨기 등이 보이며, 연하 반사의 소실, 식욕부진, 구토, 설사 등의 소화기 증상도 흔하다. 경우에 따라선 저혈압, 발열 등 자율신경계 증상도 가능하다.

클로자핀을 제외하고는 성인에서 항정신병 약물의 금단 증상이 문제가 되는 적은 없지만[@levy1993], 약물을 중단하고 한동안 수면을 취하지 못하는 것은 성인 환자에서도 흔히 보는 현상이다. 따라서 항정신병 약물에 노출된 신생아에서 금단 증상이 없으리라는 보장은 없다. 하지만 대부분의 경우에는 병용 투여되는 벤조디아제핀 및 항콜린제가 원인인 경우가 많다.

### 장기지속형 주사제에 노출된 신생아

임신 전 장기지속형 주사제를 사용하던 여성이 계획에 없이 임신을 하게 된 경우, 혹은 임신을 계획했더라도 재발의 위험때문에 게속 주사를 맞기로 결정한 경우, 지나치게 긴 주사제의 반감기 때문에 태아는 임신 기간 내내 항정신병 약물에 노출되게 된다. 경구 투여의 경우 첫 삼분기와 출산 전 1주일 부터 출산 시 까지는 투여 용량을 최소화하는 등 탄력적인 조치를 취할 수 있는 반면, 주사제인 경우 그 어떤 조치도 취하기 어렵다. 2007년 리스페달 콘스타를 사용하던 산모가 건강하게 분면하였다는 국내에서의 증례보고 이후[@Kim2007], 산발적으로 장기지속형 주사제 사용 중에 출산한 사례가 보고되기는 하였으나, 그 수는 여전히 적은 편이다.[@Özdemir2015; @Zamora2017; @Fernández-Abascal2021] 보고된 사례들은 대체로 의미있는 부작용없이 건강한 태아를 분만했다는 내용들이다.

## 산후 정신병

### 정신병의 재발

산후 첫 3개월은 조현병 재발의 위험이 극히 높아지는 시기이다. 여성 조현병 환자가 분만했을때 ¼ 가량에서 산후 정신병이 발생한다.[@Sit2006].Taylor 등[@taylor2019]이 의무기록 조회를 통해 분만한 조현병 여성 452 명의 이후 경과를 조사한 결과에서도, 무려 128명(28.3%)이 분만 3개월 내에 입원을 요할 정도로 재발하였다. 이 연구에서 주목할 점은, 임신 말기 항정신병 약물을 투여했든 안 했든 재발률은 거의 비슷했다는 점이다. 즉 분만 후의 높은 재발률을 단순히 약을 끊었기 때문이라고 치부할 수 없었다. 이는 임신 중 약물 복용 여부에 따라 산후 재발률에 큰 차이를 나타내는 (66% 대 23%) 양극성 장애와는 대조적이었다.[@wesseloo2016] 과거 어떤 이유로든 정신과에 입원한 적이 있는 산모가 첫 아이를 출산하였을 때 산후 정신병의 상대적 위험도는 일반 인구의 100배에 달한다고 한다.[@Nager2008] 만약 이전 분만에서 산후 정신병을 겪었던 적이 있다면, 재발 위험은 더욱 높다.[@Garfield2004]

이러한 높은 재발률이 분만 직후 발생하는 내분비적 변화때문인지 육아의 부단과 관련된 심리사회적 스트레스 때문인지는 확실하지 않다. 산후 우울증이 대체로 육아를 둘러싼 가족들 간의 갈등이나 엄마 역할을 둘러싼 양가감정때문에 생기는 경우가 많기 때문에, 조현병 환자 역시 이러한 스트레스에 휩싸일 것이다. 특히 이들은 문제 해결 능력이나 판단력이 떨어지기 때문에, 이들이 겪는 스트레스나 두려움은 일반 산모에 비해 훨씬 더 할 것이다. 이는 임신 결정 시기 혹은 분만 전에 가족과 충분히 논의되어야 하는 문제이며, 사회적으로도 적절한 지원책이 마련되어야 한다.[@cantwell2016]

한편 정상인에서도 산후우울증이나 산후정신병이 심심치 않게 발생하는 것으로 보아, 출산 직후의 급격한 성호르몬의 변화라는 생물학적 요인이 재발 위험을 높일 가능성이 있다. Videbech와 Gouliaev[@Videbech1995]는 출산 1년 이내에 정신증으로 입원하게 된 환자들을 대상으로 산후정신병에 대한 연구를 진행하였는데, 환자들 중에는 초산이 많았으며, 반수 이상에서 양육 스트레스와 관계없이 정신병적 재발이 있었다. 그러나 산후에 일반인에게서 출현하는 정신 증상에는 우울증/조증을 비롯한 정서적 증상이 훨씬 많기 때문에, 이러한 기분의 이상과 조현병의 재발 사이에 어떤 연관이 있는 지는 여전히 의문이다.[@McNeil1988] 산후에 출현하는 정서적 혼란이, 이미 조현병에 걸려있거나 조현병 위험 인자를 갖고 있는 환자에게서 정신병적 증상으로 표현될 가능성도 있다.

따라서 출산 이전에 미리 산후의 재발 위험에 대해 환자 본인 및 가족에게 교육해야 하며, 약물 투여 뿐 아니라 산모와 영아의 안전문제, 입원 가능성 및 대체 양육자, 정신치료적 중재 등 발생할 수 있는 상황에 대해 미리 의논하는 것이 필요하다.[@Wilkinson2008; @Ewertzon2010; @Ewertzon2011]

### 산후에 처음 발병하는 정신병

이전에 조현병 과거력이 없다 할 지라도 산후 정신병은 500 명의 출산 중 한 명 꼴로 발생한다. 산후 몇 개월 동안의 기간은 정신병의 발병이나 정신과적 입원의 위험성이 높은 시기이다.[@Kendell1987] 대부분의 경우 환각, 망상 등에 덧붙여 기분 증상을 보이며, 정서적 불안정성이 결여된 조현병 양상은 상대적으로 드물다. 전형적으로 급변하는 기분, 조증과 우울증의 혼재 양상, 혼돈, 과격한 행동을 보인다. 죄책 망상, 자신이 무가치하다는 망상, 절망감 등에서 자해를 하기도 하며, 드물지만 신생아나 다른 자녀를 해치려는 생각을 품기도 한다. 초기 증상은 그저 불안이나 우울, 감정의 불안정성 등 비특이적일 수 있는데 그러한 전구증상을 놓치면 짧은 기간 내에 급격히 정신병적 상태로 진행되면서, 자살/자해로 이어지기도 한다.[@oates2003; @oates2003a]

과거 출산 시 산후 정신병의 병력이 있거나, 이미 기분 장애의 과거력이 있는 경우, 일차 친척에서 그러한 병력이 있는 경우에는 산후 정신병의 위험성이 유의하게 높아진다.[@Jones2001] 이러한 위험 요소가 있다면, 출산 직후에 증상 변화를 잘 관찰해가면서 필요하다면 항정신병 약물이나 기분조절제, 수면제 등을 예방적으로 사용하여 전구 증상을 조절해야 한다.

산후정신병의 원인은 불확실하나, 양극성 장애와의 강한 관련성을 토대로 유전적 취약성을 의심하기도 한다.[@Jones2001] 에스트로겐 수치의 급격한 저하가 도파민 수용체의 과민성을 유발하고 그 결과 취약한 개인에서 정신병이 발병한다는 가설이 있다.[@Wieck1991] 심한 산후 정서장애 환자에서 에스트로겐 보충이 효과적이었다는 보고가 있긴 하나, 호르몬 치료의 근거는 매우 부족하다.[@balaraman2011; @cantwell2016]

산후 정신병을 인간에게서 연구하기는 윤리적으로 문제가 있기 때문에, 동물 모델을 통해 연구할 수 밖에 없다. 가장 근접한 동물 모델로는 갓 태어난 태아를 죽이는 암퇘지들이 있다.[@Quilter2007] 이 돼지들의 유전자를 조사함으로써 몇몇 후보 유전자를 골라내었는데, 그중 주목받는 유전자 들 중 하나가 X 염색체에 위치한 steroid sufatase (STS) 유전자이다. Steroid sulfatase는 DHEA (dehydroepiandrosterone)를 만들어내는 주요 효소이며, DHEA는 에스트로겐, 프로게스테론의 전구물질이다. Steroid sufatase를 인위적으로 억제한 쥐는 새끼 쥐에 공격적 행동을 보이며, 이는 지프라시돈을 투여하면 경감되었다.[@Humby2016] Steroid sufatase의 활성이 선천적으로 결여되거나 떨어져 있는 유전 질환인 X-linked ichthyosis 환자들은 유의하게 산후 우울증이나 그 밖의 임신/분만과 관련된 정신질환이 잦았다.[@Cavenagh2019] 한편 steroid sulfatase의 활성이 떨어진 환자, 그리고 인위적으로 억제한 쥐 모델에서 발현이 변화되는 여타의 유전자를 찾던 도중, CCN(Cellular Communication Network Factor 3)이 깊은 연관성을 보인다는 것이 밝혀졌다. 이러한 증거들을 종합하여 STS 그리고 CCN은 산후 정서장애 혹은 정신병의 발생과 밀접한 관련이 있을 것으로 예상되고 있다.[@Davies2019; @Thippeswamy2021]

### 출산 후 기간 중에 있는 여성 조현병 환자

조현병 환자가 출산했을 때는 산모와 아기의 건강을 완전히 평가할 수 있는 충분한 기간 동안 길게 입원하는 것이 좋다.[@Spinelli2009] 이 기간 동안 산모는 산후 상태를 안정화시키고 신생아 양육에 대해서도 배우게 된다. 퇴원 후에는 정신보건팀이 가정방문을 통한 접촉을 이어갈 수도 있다. 출산에 따른 호르몬의 변화, 산과적 합병증, 탈수, 수면부족, 부부간 불화, 심리사회적 스트레스의 증가가 그 원인으로 작용할 것이다

조현병 환자도 일반 산모와 마찬가지로 산후에 우울해지고 스트레스 상황에 있을 수 있지만 가장 관심의 대상이 되는 것은 산후정신병 문제이다. 과거 어떤 이유로든 정신과에 입원한 적이 있는 산모가 첫 아이를 출산하였을 때 산후정신병의 상대적 위험도는 일반인구의 100배에 달한다.[@Nager2008] 여성 조현병환자의 경우에는 25%에서 산후정신병이 발생한다.[@Sit2006] 이런 식으로 발병한 환자는 정신병적 증상이 두드러지기도 하지만, 인지 기능이 전반적으로 떨어지며 병식이 없어진다. 혼란스럽고 와해된 행동으로 인해 산모자신과 아기를 위험에 빠뜨릴 가능성이 있다. 자살 또는 타살 사고가 가장 문제가 된다.[@oates2003a]

출산 이전에 미리 산후정신병의 발생가능성에 대해서 그리고 출산 후 즉시 충분한 치료용량으로 다시 약물치료를 시작해야 한다는 것을 교육하는 것이 중요하다. 환자의 동의를 얻은 상태에서 배우자와 가족들이 안전문제, 입원가능성, 항정신병약물의 이용, 정신치료적인 중재 등의 산후 관리에 대해 함께 의논하는 것이 권장된다.[@Wilkinson2008; @Ewertzon2010; @Ewertzon2011]

## References {.unnumbered}
