---
title: "조현병에 동반된 우울 증상의 치료"
editor: visual
bibliography: References/17-02.bib
---

## 우울 증상에 대한 접근

앞 장에서 살펴본 바와 같이 일부 정신과 의사는 조현병 환자가 보이는 우울 증상을 적응장애의 시각에서 바라보기 때문에, 평생 지속될 수도 있는 투병 과정에서 반드시 한번은 거쳐야 되는 통과의례로 본다. 따라서 약물이나 심리 치료를 통해 증상을 경감시키고자 애쓰긴 하지만, 공격적 치료의 대상으로 보지 않는다. 이에 상반된 시각을 갖는 의사들은 우울 증상이 환자 회복이나 삶의 질 향상에 부정적인 영향만을 주기 때문에 주요 우울증 환자와 거의 동일한 치료를 제공하여 관해에 이르도록 해야한다고 믿는다. 이런 식의 구분 외에도, 어떤 의사들은 정신병적 증상이 가라앉으면 자연히 동반된 우울 증상도 해결될 것이라 믿고 있으며, 다른 의사들은 두 증상군이 서로 독립적이라고 생각한다.

지금으로서는 그 어떤 시각도 모든 환자에게 일률적으로 적용될 수 없으며, 역시 환자 개개인의 상황에 따라 시각을 바꿔야만 한다고 보는 게 맞을 것 같다. 따라서 우울 증상이 등장하면 무조건 항우울제를 투여한다는 관례적 의사 결정 보다는 다시 한번 환자 증상을 재검토하여, 어떤 접근이 과연 효과적일 지를 판별해야할 필요가 있다. 이를 위해서는 우울 증상의 정도를 객관적으로 판단해야 하며, 감별 진단에도 정성을 기울여야 한다.

## 우울 증상의 평가

조현병 환자의 우울 증상을 평가할 때는 전통적으로 BPRS나 PANSS의 소항목 중 우울과 관련된 항목들의 총합을 계산하는 방식(BPRS-D, PANSS-D)이 사용되어 왔으며[@El2002], 그렇지 않으면 주요우울장애의 척도인 Hamilton Depression Rating Scale (HAM-D), Montgomery- Åsberg Depression Rating Scale (MADRS), Beck Depression Inventory (BDI) 등이 사용되어 왔다.[@lako2012] 하지만 이들 척도들은 조현병 환자의 우울 증상에 맞추어 개발된 것이 아니기 때문에 독특한 증상을 잡아내지 못하고, 음성 증상이나 추체외로 부작용을 감별하지도 못한다는 점에서 비판을 받아왔다. 이러한 지적에 따라 Addington 등[@Addington1992]은 조현병 환자에 특화된 우울 척도로 Calgary Depression Rating Scale (CDSS)를 제작하였다. 변별타당도나 예측타당도가 우수하다는 점에서 현재로서는 CDSS가 가장 우수하다는데 의견이 일치하고 있으며[@Kim2006; @lako2012; @Schennach2012; @Scholes2013], 대표적인 치료 가이드라인 들은 BDI, MADRS와 함께 CDSS 사용을 추천하고 있다. 그러나 CDSS는 음성 또는 추체외로 증상과 구분되는 우울 증상만을 평가하기 때문에, 환자의 우울감을 포괄적으로 평가한다고 볼 수는 없다. 이 세가지 증상군이 서로 겹치고 따로 떼어내기 어려운 부분이 많기 때문에, 환자의 고통을 제대로 이해하려면 이들 영역을 모두 포괄해서 바라보는 것이 도움이 될 지도 모른다.

## 감별진단

### 낙담 반응

조현병이 가져오는 자아상의 붕괴, 자존감 저하, 자기 비난, 죄책감, 비관이나 미래에 대한 불안 등은 이루 말할 수 없다. 어느 정도까지는 이러한 반응이 정상적임을 고려해야 한다. 오히려 이런 반응이 드러나지 않을 때는, 병식 부족이나, 음성 증상으로 인한 무정서, 판단력 저하에 의한 기이한 해석 등을 의심해야 할 수도 있다. 하지만 심한 낙담 반응은 장기적인 패배감, 자포자기, 무력감, 통제의 상실감, 회피적인 행동 양식 등을 초래할 수 있고 이는 자살의 심각한 위험인자이다. 이러한 심한 낙담 반응은 "demoralization syndrome"이라고 불리워지기도 하였다.[@Drake1985] 최근에는 정신병적 경험 자체가 트라우마가 되어 외상후 스트레스 증후군(PTSD)을 일으킬 수 있다는 견해가 인기를 끌고 있다. 연구에 따라서는 초발 환자의 14\~47%가 PTSD 진단에 부합하는데, 이들 환자는 예외없이 심한 우울 증상을 동반한다.[@Lu2017]

### 기분 장애

과거 삽화가 분명 조현병에 해당했다 하더라도, 이번에는 정신병적 증상의 악화없이 우울 삽화로 재발할 수도 있다. 이런 경우 과거 진단이 잘못되었을 수도 있지만, 조현정동 장애의 가능성부터 애초애 조현병과 기분 장애가 단일 정신병일 가능성까지 다양한 경우의 수를 떠올리게 된다.

일반적인 평가 도구를 갖고 조현병과 주요우울장애에 동반되는 우울 증상을 서로 구분하기는 곤란하다. Upthegrove 등[@upthegrove2018]은 최근 발병한 조현병 환자 83명과 주요우울증 환자 146명의 BDI-Ⅱ 결과를 비교하였는데, "처벌"과 "흥미의 감소" 등 일부 항목에서 차이가 나긴 했지만 다른 증상들은 동일한 요인 구조를 보여, 증상을 이용해 두 군을 나누기는 불가능하다고 하였다. 물론 Serretti 등[@Serretti2004]은 자기 비난, 자살사고, 식욕/체중의 변화가 조현병에 비해 기분 장애에 더 두드러졌다고 하였고, Lange 등[@lange2021] 역시 우울증 환자군은 우울한 기분, 흥미의 감소, 죄책감 등이 더 심하다고 하였다. 그러나 이런 것들은 정도의 차이일 뿐 질적인 차이가 아니기 때문에 증상만을 갖고 감별하기는 매우 어렵다.

전통적으로는 우울증과 조현병에 동반된 망상은 내용이 다르다고 여겨져 왔다. Picardi 등[@Picardi2018]은 죄책망상은 거의 전적으로 우울증 환자에게서 관찰되고, 피해망상은 조현병에서 더 많다고 하였다. 한편 Stanghellini와 Raballo[@Stanghellini2015]는 두 진단은 망상이 형성되는 근본 기전이 서로 다르다며 "단일 정신병" 개념을 비판하였다. 즉 조현병에서의 망상은, 무엇이 사실인지를 알 수 없다는 불확실성과 뭔가 중요한 의미가 환자 자신에게만 숨겨져 있다는 불안과 두려움이 반영되는 반면, 우울증 환자의 망상은 도덕적, 경제적, 신체적 통합 등 일상적이고 실제적인 염려가 표현된다고 하였다. 따라서 형태면에서도 전자의 망상은 숨겨져 있던 의미나 내용이 계시처럼 드러나는 형태인데 반해, 후자의 망상은 기존에 가지고 있던 판단이나 믿음이 더욱 굳어지는 식이라고 하였다. 형태와 내용의 차이를 통해 좀더 정확한 진단에 도달할 수 있다는 주장은 기술정신의학(descriptive psychopathology) 학자들의 신념과 맥을 같이한다.

### 신체질환, 약물 및 남용 물질의 부작용

조현병 환자는 일반인에 비해 다양한 신체질환이 동반될 위험이 높다. 그런데 이중 빈혈, 암, 감염, 내분비계, 자가면역성, 심혈관계, 신경계 질환 등이 우울 증상처럼 나타날 수 있다. 또한 동반 질환을 치료하기 위해 투여된 항암제, 항바이러스제, 스테로이드 제제, 항고혈압제, 진정-수면제 등은 약물을 투여하거나 혹은 감량/중단할 때 우울 증상을 유발할 수 있다.

남용되는 약물 혹은 물질 역시 마찬가지이다. 장기간의 대마 사용은 우울증과 유사한 무기력 상태를 초래하고, 코카인 금단은 전형적으로 우울증과 유사한 증상을 보인다. 카페인이나 니코틴 금단 역시 우울증과 감별이 어려운 불쾌감으로 이어질 수 있다. 조현병 환자가 최근에 이러한 물질 복용의 습관이 변했는지를 항상 검토해보아야 한다.

### 추체외로 증후군

추체외로 증후군으로 근경직이나 무동증이 생기면 몸동작이 늦고 감정반응이 없어지기 때문에 우울증으로 오인될 수 있다. 미세한 무동증은 얼굴이나 성대 등 작은 근육에만 영향을 미쳐 정동의 둔마, 감정 반응성의 감소, 저하된 기분, 흥미의 상실 등과 혼동될 수 있다. 근긴장이나 진전을 겪는 환자는 행동을 시작하고 유지하는 능력이 저하되어 환자 스스로도 자신이 게을러졌다고 느끼게 만든다. 이럴 때는 항정신병 약물을 감량하거나 일시적으로 항콜린성 약물을 투여하여 감별을 시도해볼 수 있다.[@Hausmann2002]

정좌 불능증이 생기면 불안과 자극과민성이 증가한다. 미세한 경우에는 초조, 불안, 정서적 불안정처럼 보이며, 심하게 자극과민, 충동성 등으로 나타나 우울증상과 혼동된다. 정좌 불능증 자체가 자살의 위험 요소이기 때문에 반드시 조기에 치료되어야 한다.[@Seemüller2012] 항정신병 약물 복용 초기나 최근 증량 시 나타나는 급성 정좌 불능증은 감별하기 쉽지만, 약물을 안정적으로 사용하던 환자에서 만성 정좌 불능증이 나타나면 구분하기 매우 어려워진다.[@Berardi2000; @Salem2017]

항정신병 약물로 인한 주관적 불쾌감 역시 아직 일치된 의견이 없고 진단 기준도 없지만, 추체외로 증후군의 하나로 간주되곤 한다. 환자들은 막연하게 "기분이 안 좋고, 항상 기운이 없으며, 피로하고 흥미와 의욕이 없다"고 표현한다.[@Awad2004] 이는 진정/기면 효과와는 구분된다. 환자의 표현만 갖고는 음성/우울 증상과 구분하기 곤란하지만, 비정형 약물의 도입 이후 이런 막연한 불쾌감이 상당히 줄었다는 점에서 음성/우울 증상과는 구분 된다.[@Opjordsmoen2009]

### 음성증상

무쾌감증, 무의욕증, 사회적 위축 등의 음성 증상은 동시에 전형적인 우울 증상이기도 하기에 증상만 갖고는 둘을 감별하기 어렵다.[@van2019] 우울증이 심해지면 슬픈 감정보다는 감정 자체가 소실된다고 하지만, 그래도 정신과 의사들이 음성 증상과 우울 증상을 구분하는 기준은 환자가 느끼는 슬픔에 의사가 얼마나 다가갈 수 있는가이다. 우울은 인간의 근원적인 정서 중 하나이기 때문에 의사는 "나 자신이 우울증에 빠진다면..."이라는 상상을 할 수 있고, 따라서 우울한 환자의 정서에 공감할 수 있다. 그러나 음성 증상은 이러한 공감이 어려우며, 의사 입장에서는 뭔가 불편하고 부적절해 보인다. 이를 문헌에서는 정동의 둔마, 부적절한 정동 등으로 표현해왔다. Kulhara와 Chadda[@Kulhara1987]는 SANS로 평가했을 때 조현병 환자들은 무언어증, 눈맞춤의 저하, 부적절한 정동이 두드러진다고 보고하였다. Krynicki 등[@Krynicki2018]도 음울한 기분, 자살사고, 비관/좌절은 우울증에, 무언어증과 정동의 둔마는 음성 증상에 좀 더 특이적이고, 대신 무쾌감증, 무기력, 무의욕은 두 상태 모두에서 흔하다고 하였다. 이런 점에서 소위 겉으로 드러난 우울은 신뢰할만한 감별점이 되지 못하며, 환자의 내적 경험이 가장 중요하다고 한다.[@mulholland2000] 우울한 환자들은 부정적으로 인지가 변화하며, 신체 증상도 더 흔하다. 모든 환자가 그런 것은 아니지만, 우울 증상이 있는 환자는 자신의 상태를 괴로워하며, 이 때문에 해야할 일을 못한다는 것때문에 죄책감을 느낀다. 이에 반해 음성 증상을 겪는 환자들은 주변 가족들이 답답해할 뿐 스스로는 괴로워하지 않으며, 죄책감도 훨씬 덜 하다.

## 치료 전략

정신과 의사들은 오래 전부터 조현병 질병 경과 중 나타나는 우울 증상에 주목해왔다. 미국과 유럽의 정신과 의사들 중 절반 가량은 치료 약물을 선택할 때 꼭 우울 증상을 고려한다고 응답하였으며, 환자의 43% 정도에게 항우울제를 처방하고 있었다.[@Siris2001]

그러나 항우울제가 기대하는 효과를 나타낸다는 보장도 없고, 연구 결과도 제대로 뒷받침이 되지 않고 있다. 근거 자료가 불충분하다보니 치료지침서에도 그다지 언급되지 않고 있거나, 일관성이 떨어진다.[@Dondé2018] 예를 들어 지침서들은 우울 증상과 우울 장애를 구분하지 않고 있으며, 항우울제를 투여해야 하는 시점은 물론 우울 증상의 관해 기준이나 항우울제를 언제까지 사용해야 되는가에 대해 지침을 내놓지 못하고 있다. 기껏해야 급성기와 만성기를 구분하여 치료지침을 제공하고 있으나, 전구기, 급성 삽화 직후, 유지 치료기 등 세밀한 질병 단계에 대한 언급이 없다.[@Dondé2018]

우울해보인다고 무조건 항우울제를 처방하기 전에 다른 가능성을 먼저 감별하는 것이 우선이지만, 현실적으로 감별이 어렵기 때문에 일단 다른 치료 전략을 먼저 시도해보고, 항우울제 처방은 마지막으로 남겨놓는 것이 바람직하다. 약물 부작용이 조금이라도 의심된다면 용량을 조절하거나 부작용 감소제를 먼저 사용해본다. 낙담 반응이 현저하다고 여겨지면, 스트레스 경감, 긍정적 사고 강화, 자존감 회복 등을 포함하는 지지정신요법을 먼저 시도한다.[@Siris2000; @Gaudiano2015; @sönmez2020] 또한 급성 삽화 중에는 정신병적 증상의 감소와 더불어 우울 증상이 저절로 호전될 수 있으므로, 항정신병 약물 치료를 최적화한다.[@Jäger2008; @miura2020; @reynolds2021] 특히 초발 환자의 경우에는 정신병적 증상에서 회복될 수 있다는 희망을 고취시킬 필요가 있다. 처음 정신병적 증상을 겪으면서 당혹감과 혼란, 두려움과 절망이 가장 심할 때이기 때문이다. 그러나 현실적으로 잔류 증상이 계속 남게될 가능성이 높기 때문에, 완치에 대한 희망적인 비전과 증상이 좀 남아도 정상 생활을 되찾게 될 것이라는 현실적인 비전 사이에서 균형을 찾아야 한다.

### 항정신병 약물

항정신병 약물 치료를 최적화하며, 정신병적 증상이 소실되면 우울 증상이 가라앉는 부분도 있지만, 일부 비정형 항정신병 약물은 그 자체가 항우울 효과가 있다. 아리프피라졸과 퀘티아핀은 주요 우울증의 보조 치료제로 널리 사용되고 있으며, cariprazine, lurasidone, 올란자핀-플루옥세틴 복합제, 퀘티아핀은 양극성 우울증에 미국 식약청 허가를 획득하였다. 따라서 우울 증상을 동반하는 조현병 환자에게 이들 약물을 선택하는 것이 도움이 될 수 있다.[@miura2020; @reynolds2021; @Bajouco2022]

전통적으로 정형 항정신병 약물은 추체외로 증후군을 통해 우울 증상을 악화시키는 것으로 여겨져왔다. 물론 예외가 없는 것은 아니지만, 이는 용량을 매우 낮게 사용했을때 국한되며, 장기적으로는 우울 증상을 악화시킨다고 보는 것이 맞다. 이에 비해 비정형 약물 도입 이후에는 음성/우울 증상을 타겟으로 한 효과에 대해 집중적인 연구가 이루어졌다. Leucht 등[@Leucht2009]은 메타 분석을 통해 리스페리돈을 제외한 다수의 비정형 약물은 정형 약물에 비해 우수한 항우울 효과를 나타낸다고 하였고, 이를 토대로 <s>WFSBP\</s\>[^17-02-1]지침서에서는 우울 증상을 보이는 급성기 삽화의 치료에 리스페리돈을 권하지 않고 있다.[@Hasan2015] Miura 등[@miura2020]이 발표한 대규모의 메타 분석에서는 지프라시돈을 제외한 모든 비정형 약물이 위약에 비해 유의한 항우울 효과를 보였다. 약물 간의 항우울 효과 차이는 두드러지지 않았고, 대신 양성/음성 증상의 호전 정도와 우울 증상의 호전 정도가 강한 양의 상관관계를 보였다. 애초에 우울 증상이 심하지 않던 환자군과 젊은 환자군에서 항우울 효과가 더 크게 나타났다.

[^17-02-1]: World Federation of Societies of Biological Psychiatry (WFSBP)

약리학적으로 지프라시돈은 이미프라민과 비슷한 수준의 노르에피네피린/세로토닌 재흡수 억제 효과를 보이기 때문에 항우울 효과가 우수할 것으로 추정되었으나, 임상 시험에서는 유의미한 결과를 보여주지 못하였다.[@papakostas2012] 이런 점에서 조현병 환자의 우울 증상을 단순히 단가아민 부족으로 설명하기는 어려울 것 같다.

### 기분조절제 사용

항우울제가 정신병적 증상을 악화시키거나, 흥분/고양을 유도할 위험을 걱정하는 의사들은 기분조절제를 사용하려는 경향이 있다. 리튬은 우울, 불안 증상에 효과가 있고, 조현정동 장애나 정동 증상이 현저한 조현병 환자에게 효과적이라는 메타분석 결과[@leucht2004]가 있어서인지, 일부 치료지침서는 리튬 사용을 추천하고 있다.[@lehman2004] 하지만 조현병의 우울 증상을 기분의 이변성으로 해석하는데는 한계가 있고, 항정신병 약물과 함께 투여했을 때 부작용 위험이 높아지므로 신중하게 사용해야 한다. Lamotrigine은 양극성 우울증에 널리 사용되고 있으나, 난치성 조현병 환자에게 lamotrigine을 병용 투여한 몇몇 연구에서 별다른 항우울 효과가 나타나지 않았다.[@Glick2009; @Vayisoglu2013] 하지만 이는 난치성 환자에 국한된 연구 결과로 향후 연구가 좀더 필요한 부분이다.

### 항우울제 사용

삼환계 항우울제를 사용하던 시절에는 정신병적 증상을 악화시킬 가능성과 함께 과다 복용에 의한 자살 시도 우려때문에 많은 의사들은 항우울제 사용을 꺼려하였다.[@Siris1978] 그러나 선택적 세로토닌 재흡수 억제제 (SSRI)를 비롯한 다양한 약물이 도입되면서, 점점 더 항우울제 사용은 빈번해졌다. 서구에서 조현병 환자에게 항우울제를 사용하는 비율은 1990년대에 15%였다가 2000년대 들어 40% 이상으로 늘었다.[@Siris2001]

하지만 우울 증상이든, 음성 증상이든, 물질 남용이든, 아니면 단순한 스트레스 과다이든, 모든 경우에 항우울제를 투여하다보니, 정작 그 효과를 판정하기 매우 어렵다. 또한 연구 상황에서도, 다양한 교란 변수를 통제하기 어렵고 항정신병 약물의 영향을 배제하기 어려워, 분석에 어려움이 있다.[@castle2012]

항정신병 약물과 항우울제를 함께 사용한 82개의 임상 시험을 메타 분석한 결과, 항우울제는 우울 증상뿐 아니라 양성/음성 증상, 삶의 질에 대해 작긴 하지만 분명한 효과가 있다고 보고되었다.[@Helfer2016] 그러나 또 다른 메타 분석에서는 항우울제 추가 후 음성/일반 증상이 유의하게 호전되었지만, 이 영향을 제거하고 나면 항우울 효과는 더 이상 유의미하지 않았다고 하였다.[@Galling2018] 이러한 상반된 연구 결과는 음성 증상과 우울 증상이 서로 밀접하게 연결되어 있어서, 어느 하나에 대한 효과를 따로 떼내어 평가하기 어렵다는 것을 보여준다. 물론 실제 임사 의사들은 음성 증상과 우울 증상을 굳이 구분할 필요성을 못 느끼고 있다. 이런 문제에 봉착한 연구자들은, 조현병 환자의 우울 증상은 주요우울증 환자의 그것과는 별개의 것이라고 주장한다. 예를 들어 주요우울증 환자들은 단가아민 재흡수 억제만으로도 효과를 볼 수 있지만, 조현병 환자들은 다른 치료 기전을 곁들여져야 한다는 것이다. 이런 면에서 α~2~ 아드레날린 수용체 길항작용이나 5-HT~1A~ 부분효현 작용이 주목받고 있다.[@reynolds2021]

항우울제는 그야말로 약방의 감초처럼 널리 사용되고 있지만, 실제 임상에서 얼마만큼의 차이를 가져올 수 있는 지는 의문이다. Fond 등[@Fond2018]이 <s>FACE-SZ 코호트\</s\>[^17-02-2] 자료를 분석한 바에 의하면 우울 증상이 동반된 조현병 환자에게 항우울제를 사용했을 때 우울 증상이 조금 경감되기는 했지만, 절반 가까이의 환자는 여전히 관해에 도달하지 못하였다. Schennach 등[@Schennach2017] 역시 급성기 조현병 환자에게 평균 50일 동안 항우울제를 병용했을 때 우울 증상의 관해 비율은 별로 높아지지 않았다고 하였다. 이러한 연구 결과는 증상을 조금 경감시키는 것과 우울증에서 회복시키는 것은 큰 차이가 있다는 것을 보여준다.

[^17-02-2]: FondaMental Academic Centers of Expertise for Schizophrenia (FACE-SZ) cohort: 프랑스 고등교육혁신부의 주도 하에, 프랑스 전역에 위치한 10개 조현병 전문 치료 센터가 연합하여 구축한 코호트. [FondaMental Foundation](https://www.fondation-fondamental.org/)의 지원으로 이루어졌다.

다행히 항우울제를 사용한다고 해서 정신병적 증상이 악화된다는 증거는 없다.[@Helfer2016; @Galling2018] 다만 플로옥세틴이나 플루복사민은 클로자핀, 퀘티아핀, 지르라시돈 등 일부 항정신병 약물의 혈중 농도를 높일 수 있다. 따라서 cytochrome P450 효소계에 영향을 덜 미치는 시탈로파람이나 서트랄린이 부담이 덜 할 수 있다.[@hausmann2000; @Mao2015] 일단 우울 증상의 치료를 목적으로 항우울제 사용을 결정했다면, 주요우울장애에서의 치료 전략과 동일하게 사용한다. 양성 증상의 악화나 약물상호작용에 주의하면서 충분한 용량까지 서서히 증량하며, 목표 용량에서 8\~12주 기다린 후에도 반응이 없다면 다른 항우울제로 바꾼다.[@Babinkostova2011] 만약 효과가 있다고 판단했다면 6\~12개월 동안 항우울제를 그대로 유지한다.

## References {.unnumbered}
