---
title: "조현병에 동반된 강박증상의 개념"
editor: visual
bibliography: References/17-03.bib
---

## 강박 장애의 개념적 변천

1838년 에스퀴롤은 "사고, 심상(心像), 느낌이나 운동이 반복 또는 지속됨과 동시에 강요받는다는 주관적 느낌을 받는다. 환자는 저항하고자 애쓰며, 이러한 현상이 자신의 인격과 맞지 않고 비정상적이라고 인식한다"라고 기술함으로써, 최초로 강박 장애(Obsessive-Compulsive Disorder, OCD)를 독립적인 정신질환으로 구분한다.[@Kozak1994a]

강박 증상은 조현병의 주요 증상으로 간주되지는 않으나, 오래 전부터 조현병의 모든 질병단계에서 나타난다는 사실이 알려져 왔다.[@poyurovsky2013] 강박 장애와 조현병 사이의 관계에 대한 논란은 강박 장애 자체에 대한 연구만큼이나 오래 되었다.[@Bürgy2007a] 현대의 질병분류체계에서 조현병과 강박 장애는 서로 다른 별개의 질병으로 간주되고 있지만, 임상 양상, 병태생리 등에서 상당히 많은 공통점을 보이며, 무엇보다 한 환자에게 두 질환이 겹쳐 있어서 구분하기 어려울 때가 많다. 흔히들 병식의 유무나, 증상에 저항하려는 노력을 갖고 강박 장애를 구분지으려 하지만, 이는 정도의 차이일뿐 망상과 강박증 사이의 명확한 경계는 존재하지 않는다.

조현병과 강박 장애의 관계에 대한 연구는 주로 두 가지 방향에서 연구되어 왔다. 하나는 정신병 환자들이 보이는 강박 증상에 대한 연구로, **"조현-강박 장애(schizo-obsessive disorder)"**라는 조현병의 한 유형으로 보아야 한다는 주장이 있어왔다.[@hwang1993; @zohar1997] 다른 하나는 강박 장애로 진단된 환자들이 보이는 정신병적 증상에 대한 연구로, **"정신병 양상을 동반한 강박 장애"**[@Insel1986]나 **"강박정신병(obsessional psychosis)"**[@Solyom1985], "병식이 부족한 강박 장애" 등이 그 예이다.

### 근대 프랑스 정신병리학

19세기 초반 프랑스의 정신의학자들은 정신 현상을 기술하기 위해 새로운 용어들을 지치지 않고 만들어내었다. 학자들은 자신만의 독특한 관점을 창의적인 진단명으로 후세에 남기고자 했으며, 이를 통해 그들의 다양한 고민을 엿볼 수 있다.

초기의 학자들은 강박증이 **"지적(知的)"** 능력의 변화라고 보고 사고 장해의 하나로 분류하였다. 여기에는 "망상 없는 광증(manie sans délire)", "지적 단일편집광(monomanie intellectuel)", "명료광증(folie lucide)"와 같은 용어가 해당된다.[@Attademo2015; @Berrios1989; @berrios1996] 한편 에스퀴롤은 환자가 병식을 가지고는 있으나 이를 억누르지 못한다는 점에서 "의지"의 장애로 보았으며 "의욕 단일편집광(volitional monomania)"이라는 이름을 붙였다. 반면 Morel(1866)은 강박 장애를 "감정의 광증(délire emotif)"에 포함시키면서 신경증 혹은 불안증과 연결시킨다. 이와 같은 전통은 강박 장애를 불안장애의 하나로 분류한 DSM-Ⅲ-R로 이어진다. <s> Legrand du Saulle</s>[^17-03-1]은 비록 Morel의 신경증 개념을 받아들였지만, 광증으로 불릴 만큼 유달리 심한 환자들이 있다는 것을 인식하였다. 그는 이렇게 심한 강박 장애를 "병식의 정신이상(insanity of insight)"으로 정의하였다.

[^17-03-1]: **Henri Legrand du Saulle (1830\~1886)**: 프랑스의 정신과 의사로 Bénédict Morel의 제자이다. 인격장애, 공포증과 강박장애에 대한 연구에 공헌하였으며, 사법정신의학(forensic psychiatry)을 개척한 인물로도 유명하다.

이러한 혼란에서 보여지듯이, 강박증은 보는 시각에 따라 사고의 장애나 의지의 장애가 되기도 하고, 감정이나 병식의 장애가 되기도 하였다. 광증으로 불릴만큼 심한 환자가 있는 반면, 불안증에 속하는 가벼운 환자가 있다. 병식이 없어 망상으로 분류되기도 하고, 병식이 너무 강하여 충동에 대한 저항과 투쟁이 오히려 더 고통스러울 때도 있다. <s>Dagonet</s>[^17-03-2] 는 강박 현상을 "그 생각을 버리려 할수록 그것이 더욱 크게 마음에 부과되며, 감정이나 추세를 없애려 할수록 그것이 더욱 강력해"지는 곤란한 현상이라 기술하였다.

[^17-03-2]: **Henri Dagonet (1823\~1902)**: 프랑스의 정신과 의사. 성 안나 병원에서 일하였다. "*Nouveau traité élémentaire et pratique des maladies mentales"*이라는 저서를 출판했는데, 이 책에는 최초로 환자들의 실제 사진이 포함되어 있다.

흥미롭게도 1895년 <s>Séglas</s>[^17-03-3]는 강박 장애와 환각의 연관성에 주목하였다.[@Fuentenebro2000]. 그는 **"환각적 강박 (hallucinatory obsession)"**과 **"강박적 환각 (obsessional hallucinations)"**을 구분하였다. 전자는 강박으로 인한 불안 때문에 환각 경험이 수반되는 것을, 후자는 환각이 너무나 집요하게 나타나 강박적 공포를 가지게 되는 것을 의미한다.[@Attademo2015] 특히 강박적 환각의 경우에는 강박 장애가 독립된 질환인지, 정신병적 증상을 경험하는 하나의 방식을 뜻하는 것인지 의문을 제기한다.

[^17-03-3]: **Jules Séglas (1856\~1939)**: 프랑스의 정신과 의사. Charcot의 조수로 일하였으며, 망상, 환각, 가성환각 등의 정신병리를 체계화하는데 공헌하였다. 특히 정신질환과 언어 구조의 이상에 대한 연구로 유명하다.

강박 장애와 정신증의 연관은 여기서 멈추지 않는다. <s>Janet</s>[^17-03-4]는 강박 증상을 "환자의 사고에 부과되어 자아의 틈새를 파고드는 관념"으로 정의하였다. 이는 스스로의 사고에 대한 통제권을 잃게 된다는 뜻이다. 그는 강박 장애를 "정신쇠약(psychasthenia)" 즉 신경증의 범주에 포함시켰지만, 일부 환자 들이 정신병으로 이행한다는 것을 알고 있었다. 자신의 사고와 감각을 스스로의 의지로 조절할 수 없다는 점에서, 이 개념은 슈나이더의 일급 증상에 영향을 끼쳤다.

[^17-03-4]: **Pierre Marie Félix Janet (1859\~1947)**: 프랑스의 심리학자, 철학자, 정신과 의사. William James, Wilhelm Wundt와 함께 근대 심리학의 창시자로 여겨진다. Charcot 밑에서 배웠으며, 과거의 외상이 현재의 해리 현상에 미치는 영향을 연구했으며, 전의식과 무의식 개념을 고안하였다. 또한 환자-의사 간의 라포 및 전이 현상에 대해서도 논의하였다. 프로이트 역시 Janet에게 진 빚을 인정하였다.

결론적으로 19세기 프랑스 학자들은 인간의 정신 기능이, 사고, 의지, 감정, 충동 등 서로 독립적인 기능으로 나뉘어 질 수 있다는 데 매혹되었고, 강박 증상 역시 이 기능들 중 어느 하나의 이상으로 분류하고 싶어하였다. 그러나 그러면 그럴수록 강박 장애는 어느 하나에 매이지 않는 기묘한 모습을 보였으며, 광증과 신경증 사이에서도 애매한 위치를 차지하고 있었다.[@Berrios1989]

### 근대 독일 정신병리학

19세기 후반에 들어서자 독일 정신과 의사들 역시 강박 장애에 대해 독특한 해석을 내놓기 시작하였다.[@berrios1996; @Bürgy2007a; @Attademo2015] 그러나 사고의 장해인지, 감정의 장해인지, 즉 광증인지 신경증인지를 두고 의견이 엇갈린 것은 마찬가지였다.

<s>von Krafft-Ebbing</s>[^17-03-5](1876)은 우울한 기분이 강박적 심상(obsessive images)을 낳고 환자는 그에 대해 이성적인 반응을 할 수 없게 된다고 하였다. 이에 반해 <s>Griesinger</s>[^17-03-6]는 강박 장애와 망상 장애의 연관성을 중요시하며, 둘 다 사고의 손상에서 생긴다고 주장하였다. <s>Westphal</s>[^17-03-7] 역시 병식이 온전함을 중요시하였지만 신경증으로 보는 것은 반대하였다. 그는 "강박적 심상은 특정 감정 상태만으로는 발생하지 않는다. 이는 환자의 의지에 반하여 의식으로 파고들어 떨쳐낼 수 없으며, 환자는 이를 비정상적이고 이질적인 것으로 인지한다."고 정의하였다. 그는 또한 "강박적 심상은 망상적 관념으로 진행하지 않으며, 정신병과 달리 다른 의식 내용을 침범하지 않는다"고 하였다.[@Bürgy2007a] 이 견해는 강박 증상이 정신병에 대한 방어기제로서, 망상에 의해 의식이 침범되는 것을 막는 기전이라는 관점으로 이어졌다. 이를 뒷받침 하듯 Westphal은 조현병 환자에서 관찰되는 강박 증상을 "유산된 정신병(abortive insanity)"이라고 부르기도 하였다.[@Attademo2015; @Tezenas2019]

[^17-03-5]: **Richard von Krafft-Ebing (1840\~1902)**: 독일의 정신과 의사. 성(性)정신의학의 선구자로 "*Psychopathia Sexualis: eine Klinisch-Forensische Studie* (*Sexual Psychopathy: A Clinical-Forensic Study*)"를 저술하였다. 인간의 다양한 성적 심리와 행위를 나열했음을 물론 이를 정신병리와 연결시켰다. "성도착", "가학/피학 성욕", "동성애/양성애" 등의 개념이 모두 그에게서 비롯되었다.

[^17-03-6]: **Wilhelm Griesinger (1817\~1868)**: 독일의 신경학자이자 정신과 의사. 정신질환이 뇌의 기질적 이상에서 비롯되었다고 믿었으며, 따라서 정신과 환자들을 일반 질환의 환자들과 다를 바 없이 대해야 한다고 주장하였다. 생물정신의학의 개념적 틀을 세운 것으로 여겨진다.

[^17-03-7]: Carl Friedrich Otto Westphal (1833\~1890): 독일의 정신과 의사이자 신경학자. "광장공포증(agoraphobia)"이란 병명을 제안하였다. 신경과적으로도 많은 업적을 쌓아서, 정신과 질환과 매독 등 신경과 질환을 감별하는데 공헌하였다. 이후 Arnold Pick, Karl Wernicke 등 다수의 신경병리학자들을 키워낸다.

이와는 대조적으로 크레펠린은 병식이 희미한 강박 장애 환자에 주목하였다. 그는 강박 사고가 너무 뚜렷하거나, 그에 대한 공포가 심하여 환각이나 망상으로 이어지는 증례를 열거하였다. 대부분의 강박 장애 환자들이 어느 정도는 병식을 갖고 있지만, 증상이 심하고 만성 경과를 밟는 환자, 특히 오염과 접촉에 대한 강박사고를 가진 환자들은 병식이 부족하여, 때로 망상과 구분되지 않는다고 하였다.[@Steinberg2017]

대조적으로 블로일러는 일부 강박 증상이 실제로는 조현병의 양상이라고 주장하여 두 질환의 유사성을 강조하였다. 그는 Janet의 견해와 유사하게, 강박은 가장 흔한 자동증(automatism)으로, 환각이 감각기관에 자동으로 떠올려진 심상인 것처럼, 강박은 사고, 갈망, 욕구의 환각에 해당한다고 보았다. 동시에 일부 강박 장애는 조현병으로 전환되며, 강박 증상이 조현병의 전구기 증상일 가능성을 언급하였다.[@Grover2019]

강박 장애가 광증이냐 신경증이냐, 병식이 없는 상태를 강박 장애로 부를 수 있느냐는 문제는 오랜동안 학자들을 괴롭혀왔고, 여전히 결론이 나지 않은 문제이다. 야스퍼스는 이에 대해 넓은 의미의 강박과 좁은 의미의 강박을 나눔으로서 중재안을 제시한다. 넓은 의미의 강박이란 "자아의 의지에 반하지만 외면하거나 무시할 수 없는 모든 정신적 과정"을 포괄하는데, 여기에는 망상과 환각도 포함된다. 그러나 좁은 의미의 강박은 넓은 의미의 강박을 마주한 자아가 그 내용이 근거 없고 터무니없다고 판단하여, 이에 대항하여 자신을 방어하기 시작할 때 생겨난다. 따라서 좁은 의미의 강박은 의식의 내용에 대한 자아의 태도를 가리킨다.

야스퍼스가 지지한 정신질환의 위계개념에 따르면, 조현병이 강박 장애보다 상위에 있기 때문에 두 질환이 동시에 발생하는 상황을 받아들이기 어렵다. 그러나 야스퍼스는 조현병 환자의 정신병적 경험이 강박적 집착의 초점이 되어, 내용은 망상적인데 형태는 강박적인 복잡한 정신병리 현상이 출현할 수 있다고 하였다. 이는 강박은 내용이 아니라 증상을 대하는 태도라는 그의 이론에 부합하며, Séglas가 언급한 강박적 환각의 개념과도 연결된다.

### 현대의 연구 결과들

19세기 연구자들이 강박 장애가 광증인지 신경증인지를 놓고 논쟁을 벌였던 것에 비해, 20세기 중반 이후의 정신과 의사들은 조현병과 강박 장애의 관계를 병존질환(comorbidity)으로 단순화시켰다. 그에 따라 조현병 환자가 보이는 강박 증상은 조현병에 강박 장애가 겹친 것으로 이해되었으며, 논의의 초점은 동반된 강박 장애가 환자의 자아를 지켜줄 것인지 오히려 붕괴시킬 것인지에 대한 의문으로 옮겨갔다.

고전적인 견해는 정신분석학적으로 해석한 Stengel(1945)의 견해이다. 그는 강박 증상이 보호 인자로 작용하여, 특히 인격의 와해를 막아준다고 주장하였다. 그와 동시대에 활약했던 분석가들은 이 견해를 지지했으며, Rosen[@rosen1957]은 조현병 환자의 3.5%가 강박 증상을 경험하는데, 이들은 상대적으로 양호한 임상 경과와 예후를 보이는 경향이 있다고 하였다.

그러나 좀더 객관적인 연구 방법론으로 무장한 후대의 연구자들은 조현병에 강박 장애가 겹치면 오히려 예후를 악화시킨다고 보았다. Fenton과 McGlashan[@Fenton1986]은 구조화된 면담과 조작적 정의 등 체계적인 방법을 동원하여 조사한 후 조현병 환자의 12.5%에서 두드러진 강박 증상이 관찰된다고 보고하였다. 게다가 강박 증상이 동반된 환자는 입원 기간이 길고 사회적 관계, 전반적인 기능과 취업률이 낮아 질병 결과가 불량하다는 것을 발견하였다. 이는 강박 증상이 인격의 와해를 막는다는 고전적 견해에 정면으로 상충하는 것이었다.

Insel과 Akiskal[@Insel1986]는 병식이 온전해야 강박 장애 진단이 내려질 수 있다는 통상적인 견해를 뒤집고자 하였다. 그들에 따르면 강박 장애 환자의 절반 이상은 강박 사고나 행동에 저항하지 않으며, 강박 행동을 하지 않았을 때 초래되는 해로운 결과에 대해 확신하고 있다고 보고하였다. 따라서 병식을 강박 장애 진단의 기준으로 삼는 것은 불합리하며, 강박 증상을 보이는 조현병 환자가 더 병식이 높다는 과거의 견해도 사실이 아니라고 하였다. 이러한 주장은 강박 증상이 정신병에 대한 방어라는 속설은 물론, 조현병과 강박 장애가 위계적이기 때문에 어느 하나가 우세하면 다른 하나가 감소된다는 개념 역시 배격하는 것이다.

이처럼 강박 장애의 구성요건에서, 강박 증상이 불합리하다고 인식되어야 한다는 조건도, 저항해야한다는 조건도 없어지면서, 강박 증상과 망상의 구분은 더더욱 모호해졌다. 동일한 환자라도 시간에 따라 병식이 생겼다 없어졌다 하기도 하며, 지배관념 혹은 망상의 형태로 변하기도 한다.[@Kozak1994a; @Insel1986] Séglas가 언급한 환각적 강박의 예처럼, 강박 증상이 너무 생생하면 진성 혹은 가성 환각으로 경험될 수 있다는 것이 많은 학자들에 의해 보고되었다.[@pies1984; @Insel1986; @hussain1988; @Fontenelle2008] 이러한 주장들은 강박 장애와 정신증을 구분하는 것이 별 성과없는 노력이라는 현대적 시각을 반영하고 있다.

### DSM-5에서의 강박 장애

DSM-Ⅳ에서만 해도 강박 장애는 불안 장애로 분류되었으며, 진단 기준에는 강박 증상이 스스로의 마음에서 비롯되었음을 인식하고 있다는 조건이 들어있었다. 그러나 DSM-5에서 강박 장애는 불안 장애의 범주에서 떨어져 나와 신체이형장애, 저장장애, 발모장애, 피부벗기기장애 등과 더불어 강박관련장애라는 새로운 범주로 구성되었다. 그 이유로는 이들 질환에서 불안 증상이 흔하긴 하지만 항상 나타나는 것은 아니며[@Phillips2010], 불안보다는 혐오감(disgust)이나 불완전하다는 느낌(feeling of incompleteness)이 더 강하다는 점[@Knowles2018]등이 제시된다. 병식에 대해선 양호, 부족, 결여/망상적 믿음의 세 단계로 나누어, 망상적 단계에 이를 지라도 강박 장애 진단을 내릴 수 있도록 허용하였다.

ICD-11에서도 기본적으로는 DSM과 비슷하여 강박관련장애를 독립시키되, 상기 4개 질환 이외에 건강염려증과 후각관계증후군(olfactory reference syndrome)이 포함되었다. 병식이 없고 망상적으로 보일 지라도, 이러한 잘못된 믿음이 강박과 관련된 증상에만 국한되고, 다른 정신병 양상이 없으면 강박 장애로 진단할 수 있다. 병식 수준은 DSM-5와 같이 양호, 부족, 결여의 세 단계로 나눈다.[@Stein2016]

DSM-5와 ICD-11 모두 강박관련장애의 임상 양상에 지각 이상은 포함하지 않고 있으며, 조현병의 아형으로 조현-강박 장애를 추가하지 않았다. 두 진단 체계 모두 '병식의 결여'를 세부 진단하도록 한 점은 강박과 망상의 연속성에 대한 해결하지 못한 고민을 반영한다고 할 수 있다.

## 조현병 환자가 보이는 강박 증상

### 유병률

이처럼 강박 장애라는 진단 자체가 정신증과 명확히 구분되지 않는 상황에서 조현병과 강박 장애의 공존 유병률을 추정한다는 것은 애초부터 어폐가 있다. 연구 대상의 선정, 진단 도구의 종류, 공변인의 통제 등 역학 연구에서 흔히 맞딱뜨리는 문제에 더하여, 강박 장애의 개념적 혼란때문에 더더욱 추정치가 들쑥날쑥 하다.

무엇보다 "병식 없는 강박 장애"의 진단이 가능하다 보니, 환자를 강박 장애로 진단해야 할 지, 조현병으로 진단해야 할 지, 그것도 아니면 두 질환이 공존하는 것으로 정해야 할 지 기준이 사라졌다. 일례로 강박 장애 환자 중 13.8\~30.7%가 병식이 부족하고 4% 정도는 아예 병식이 없다고 하는데[@Jacob2014], 그럼에도 강박 장애 환자 중 조현병으로 진단이 바뀌는 환자는 1.7% 정도에 불과하다.[@de2009]

먼저 조현병 진단이 붙은 후 강박 증상이 나타나기 시작한 경우는 그나마 진단에 혼란이 덜 하다. 이 경우 조현병 진단이 강박 장애로 바뀌기 보다는, 병존 질환으로 진단하는 것이 보통이다. 일반 인구의 1.9\~2.5%가 강박 장애를 앓고 있는데[@Fontenelle2006], 조현병 환자의 강박 장애 병존율은 12.1%로, 사회공포증, 외상후 스트레스 장애에 이어 세 번째로 높았다.[@Achim2011] 게다가 조현병 환자 중 강박 증상을 한번이라도 보이는 환자의 비율은 62%에 달한다.[@Kayahan2005] 43개 연구 3,987명의 자료를 메타분석한 연구에서도 조현병 환자 중 강박 장애의 유병률은 13.6%, 강박 증상이 나타나는 비율은 30.3%로 보고되었다.[@Swets2014] 최근 스웨덴에서 시행된 종적 추적조사에서는, 조현병 환자가 이후에 강박 장애 진단을 받을 확률이 일반 인구의 7배 였으며, 이는 항정신병 약물 사용과는 큰 관계가 없었다. 이에 비해 양극성 장애 환자가 강박 장애 진단을 받을 위험비는 1.2배에 불과하였다.[@Cederlöf2015]

하지만 기타 정신질환을 앓는 환자들과 비교했을 때에도, 조현병 환자가 유달리 강박 장애 동반 비율이 높다는 뜻은 아니다. 조현병, 조현정동장애, 양극성 장애, 심한 우울증 때문에 입원했던 환자를 추적조사한 바에 따르면, 향후 24개월 동안 강박 증상이 나타날 비율은 질환에 따라 크게 다르지 않았다. 다만 강박 증상이 지속될 비율은 우울증이 가장 높았으며, 양극성 장애가 가장 낮았다.[@Craig2002]

### 정신병리학적, 철학적 고찰

프로이트의 초기 이론에서, 우울증은 초자아의 공격성이 자아 내부를 향한 것(aggression directed toward the self)이라고 이해되었다.[@busch2009] 이에 따르면 초자아가 어느 정도 형성되고 나서야 우울증을 겪을 수 있기 때문에, 영아가 우울증을 앓는다는 것은 상식 밖의 일로 여겨졌다. 그러나 이후 정신분석 이론이 갈등 이론을 벗어나 다양한 모습으로 발전하면서, 영아가 우울증을 앓을 수도 있다는 것이 받아들여지기 시작하였다. 조현병 환자가 과연 강박 증상을 겪을 수 있는 지에 대해서도 비슷한 논쟁이 반복되었다. 그 핵심에는 강박 증상을 경험하기 위해선 일정 수준 이상으로 통합된 자아가 있어야 하는데, 조현병 환자가 그런 확고한 자아를 가질 수 있겠느냐는 의문이 자리잡고 있다.

이 문제를 비껴가기 위해 학자들은 조현병 환자의 강박 증상은 엄밀한 의미에서 진짜 강박으로 볼 수 없다는 주장을 펴기도 한다. Denys[@Denys2011]는 증상으로서의 "강박 사고/강박 행동"보다는 "obsessionality/compulsivity"라는 마음의 경향이 진성 강박을 설명하는 핵심이라고 주장하였다. 강박의 라틴어 어원은 **"obsidere"**로 **"점유, 점령되어 있다"** 또는 **"사로잡혀 있다"**는 의미가 있다. 인간의 모든 정신 활동은 무엇인가를 지향하고 있는데, 정상적인 사람은 그 지향하는 대상이 필요에 따라 수시로 바뀐다. 하지만 강박 장애 환자는 그 대상의 지배적인 성질에 **"사로잡힘"**으로써 그 밖의 세상에 대한 주의를 박탈당하고, 강박 대상에만 집중하게 된다. Obsessionality가 수동적으로 지향성을 박탈당한 것을 가리킨다면, compulsivity는 환자가 능동적으로 강박적 의례에 지향성을 국한시키고, 이 의례를 완벽하게 수행하고 통제하려는 노력을 가리킨다.

Obsessionality/compulsionality 속에서 환자의 지향성은 강박 주제에 흡수되다시피 하여 나머지 세상은 의미를 잃거나 사라질 위기에 처하게 된다. 그러나 아무리 조현병이라도 환자는 현실 세계에 대한 끈을 놓지 않고 있기 때문에, 나머지 세상이 점점 사라지고 있으며, 심지어 자기 자신을 잃어버릴 위기에 처해있다는 것을 부분적으로 인식하고 있다. 그들은 오히려 강박적 주제에 몰두하여 이를 완전히 해결하여야만 정상 세계로 돌아올 수 있다고 믿는다 (불완전하고, 찜찜한 느낌). 만약 강박의 대상이 외부 현실이라면 통제할 가능성이 남아 있겠지만, 대부분 그 대상은 스스로의 마음이기 때문에 이들은 자신의 모든 정신 활동을 통제하려 한다. 그러나 이는 시작하기 전부터 이미 실패가 예정되어 있는 헛된 수고일 뿐이다. 즉 환자들은 마치 모래 수렁에 빠진 것처럼, 현실로 돌아오기 위해 발버둥치다가 점점 강박 대상에 빠져들게 된다.

이론적으로야 그렇지만, 이러한 정신과정이 이루어지려면 자신이 현실로부터 빗겨나 있다는 것, 그리고 빨리 현실로 돌아와야 한다는 초조함을 느낄 수 있어야 하는데, 학자들은 조현병 환자들이 이를 인식할 수 있는 지를 문제삼는다. 이는 자유의지의 문제와도 연관이 있다. 강박증 환자들은 compulsivity 때문에 자신의 자유의지가 침해받고 있다는 것을 인식하고, 자유의지를 되찾기 위해 점점 더 통제하려고 매달린다. 즉 통제력 상실을 겁내는 것은 자유의지가 작동하고 있다는 반증이기도 하다. 이에 반해 조현병 환자는 망상/환각으로 인해 자신이 현실로 부터 벗어나있다는 것, 그리고 자유의지를 상실하고 있다는 것 자체를 인식하지 못한다. 따라서 스스로의 마음을 통제하여 현실로 돌아오고자 발버둥치는 일도 찾아보기 힘들다.

바라보는 시각은 많이 다르지만, 야스퍼스와 그의 계승자들 역시 엄밀한 의미에서 조현병 환자가 강박 증상을 경험하는 것은 불가능하다고 여긴다. 야스퍼스는 의식의 구조를 그 분화 정도에 따라 1) 자아와 대상이 분리되지 않은 단계, 2) 자아가 대상과 분리된 자기 자신(자아)을 인식하는 단계, 그리고 3) 자아가 자신(자아)를 숙고의 대상으로 하는 자기반성 단계로 나누었다. 그는 앞단락의 고찰과 마찬가지로, 강박 증상은 자기반성적 단계에서만 가능한데 비해, 정신병적 상태란 가장 원초적인 자아와 대상이 분리되지 않은 상태라고 지적하였다. Burgy 역시 야스퍼스의 견해를 따라 조현병 환자가 보이는 강박 유사 증상은, 결국 망상과 거리를 둘 정도로 호전된 후에나 가능하다고 보았다.[@Bürgy2005; @Bürgy2007a; @Bürgy2019] 따라서 이러한 견해를 추종하는 학자들은 조현병 환자가 보이는 강박 증상은, 표면적으로만 강박 장애를 닮았을 뿐 내면의 현상학적 측면에서는 분명 강박 장애와 구분된다고 믿었다.

이런 견해들은 가성 강박(pseudo-obsession)이라는 개념을 등장시켰다. 이는 내적인 저항이나, 내용의 불합리성에 대한 인식이 없는, 다시 말하여 병식이 동반되지 않는 강박을 말한다. 가성 강박의 내용은 주로 성적/공격적 충동이나 기이한 신체이형적, 건강염려증적 집착이 많다. 그러나 이런 개념의 진단신뢰성이 매우 낮기 때문에 DSM에는 편입되지 못하였으며, DSM-IV 이후 병식이 부족한 강박 장애 진단이 가능해지면서 점차 잊혀지게 되었다.[@poletti2019]

앞서 블로일러가 강박을 자동증(automatism), 즉 의지와는 상관없이 자생적으로 떠오르는 사고, 갈망, 욕구에 해당한다고 주장했다는 것을 언급하였다. 자생적 사고(autochthonous thought)는 대표적인 조현병 전구기 증상의 하나로 간주되며, 의지와는 독립적으로 여러 가지 관념이 일관성 없이 나타나는 것을 의미한다. 특히 <s>Nakayasu</s>[^17-03-8]는 자생적 사고를 초기 조현병의 일급 증상으로 손꼽기도 하였다.[@nakayasu] Nakayasu는 블로일러와는 달리 자생적 사고와 강박 증상을 분명히 구분하며, 자생적 사고를 강박 증상으로 보는 것에 반대하였다. 강박적 사고는 그 내용이 터무니 없고 불합리하기 때문에 고통을 받는다. 반면 자생적 경험은 그 내용이 이상하기 보다는, 자기 의지와 상관없이 나타난다는 것 때문에 고통을 받는다. 그러나 실제 환자들의 경험을 종합하면 강박 증상 역시 그 자생적 특성때문에 고통을 유발하고, 환자에 따라선 강박 증상의 내용에 대해 불합리함을 느끼지 못하거나, 전혀 저항을 하지 않는 경우도 있다. 따라서 Nakayasu 처럼 자생적 사고와 강박 증상을 깨끗이 구분할 수 있는 지는 의문이다.[@oyebode2015]

[^17-03-8]: Nobuo Nakayasu (1949\~): 일본의 정신과 의사. 동경대학교 정신과학 교실의 교수로 재직 중이다.

이상에서 본 것처럼 정신병리학자들은 조현병 환자들이 진정 강박 증상때문에 고통받을 수 있는 지를 의문시하였고, 조현병 환자의 강박 증상과 강박 장애 환자의 증상을 구분지으려 하였다. 그러나 조현병 환자들이 현실과 동떨어지는 정도는 지극히 개인차가 크기 때문에, 획일적인 구분은 의미가 없을 지도 모르겠다.

### 강박 증상의 임상 양상

일반적인 강박 장애 환자들이 보이는 임상 양상과, 강박 증상을 동반하는 조현병 환자들의 임상 양상 사이에 어떤 차이가 있는 지는 명확하지 않다. 한 환자에서 두 질환이 병존할 때, 그들 사이의 관계는 이론적으로 아래와 같이 생각해볼 수 있다.

1.  강박 증상이 우연하게 공존하는 것일 뿐, 강박 증상과 망상/환각 사이에 아무런 관련이 없는 경우
2.  강박 증상이 망상/환각으로 오인되어 조현병 진단이 내려진 경우
3.  망상/환각에 집착하는 모습이 강박 증상으로 오인되는 경우
4.  강박 증상과 망상/환각이 서로를 유도/자극하는 경우
5.  강박 증상이 지속되면서 이차적으로 피해/죄책 망상이 발생하는 경우
6.  강박 증상이 지속되면서 이를 설명하기 위해 망상이 발생하는 경우
7.  강박 증상이 망상으로 또는 망상이 강박 증상으로 형태가 바뀔 지언정, 내용은 변하지 않는 경우
8.  강박 증상과 정신병적 증상이 같은 질환의 다른 표현형인 경우

환자의 주관적 경험 상으로는, 망상/환각이든 강박적 사고/충동이든, 환자 자신이 만들어낸 것이 아니라 저절로 생겨난 것이며, 저항하려 해도 소용이 없고 의식의 통제에서 벗어나 있는 것이다. 따라서 환자에게 스스로 구분해보라고 하는 것은 의미가 없다. 다만 외부에서 바라보는 의사가 증상의 특징적 내용이나, 병식/저항의 정도 등을 고려하여, 그 둘을 구분하게 되는 것 뿐이다. 조현병에 동반된 강박 증상이라고 해서 정신병리학적 형태에 큰 차이가 있는 것은 아니며, 그 내용 역시 개인이 살아온 배경이나 문화의 영향을 받을 뿐, 조현병 환자라고 해서 특별한 내용이 있는 것은 아니다.

조현병 환자의 강박 증상을 강박적 심상, 관념, 충동, 공포로 나누기도 한다. 강박적 심상은 생생한 심상이 저항할 수 없을 정도로 환자의 마음을 점령하는 것으로, 때로 가성 환각으로 오인되기도 한다. 강박적 관념은 추상적, 철학적 주제에 대한 반추의 형태를 띤다. 강박적 충동은 사물을 건드리거나 그 수를 세거나 정리하려는 충동 또는 이유없이 반사회적 행동을 저지르려는 충동을 뜻한다. 강박적인 공포는 이유 없이 지배당한다고 느끼는 근거 없는 공포이다.[@casey2019]

강박적 공포가 따로 언급되는 이유는, 다수의 강박증이 혐오감과 함께 공포감과 연관되기 때문이다. 환자가 사로잡히는 사고는 일종의 터부(금기)이기 때문에 그 자체로 공포감을 불러 일으키며, 동시에 이를 제대로 끝맺지(해결하지) 못하면 더욱 끔찍한 결과가 초래되리라는 공포를 동반한다. 환자는 공포에 사로잡힌 상태에서 벗어나기 위해 강박 내용과 거리를 두려하지만, 이는 역설적으로 불확실성을 높여 불안을 가중시킨다.[@vongebsattel1958]

또 다른 학자들은 강박 증상을 촉발 인자의 유무에 따라 자생적인 강박(autogenous obsession)과 반응적인 강박(reactive obsession)으로 나누기도 한다.[@Lee2003; @Lee2010] 전자는 뚜렷한 자극이나 단서 없이 불현듯 마음에 나타나며, 성적, 공격적, 비도덕적 생각과 같은 금지된 충동이 올라오며 환자는 이를 억누르거나 여러 방법을 동원해 회피하려고 시도한다. 이에 반해 후자는 현실성이 있는 사고나 나쁜 결과를 미리 예방하려는 시도에 가깝다. 오염, 실수, 사고, 비대칭, 분실 등에 대해 불안해하며 확인을 반복하는데, 이는 현실적으로 생길 수 있기 때문에 자아이질적이라고 느껴지지 않는다. 전자는 조현병 스펙트럼 환자에게서 후자보다 더 흔히 나타나며, 사고 장애와 연관이 깊고, 치료에 항정신병 약물이 필요할 때가 많다.[@Batmaz2016]

### 두 가지 환자군의 구분

반복해서 논한 것처럼, 조현병 환자가 보이는 강박 증상은 망상과 잘 구분되지 않으며, 조현병과 강박 장애가 과연 병존할 수 있는 질환인지도 분명하지 않다. 이런 난제때문에 많은 학자들이 고민해왔으며, "조현-강박 장애(schizo-obsessive disorder)" 혹은 "가성 강박 조현병 (pseudo-obsessive schizophrenia)"이라는 진단명이 등장하기도 했다. 조금 범위가 넓지만 "가성 신경증적 조현병(pseudoneurotic schizophrenia)" 역시 이런 상황에 적용해볼 수 있다.[@hoch1949; @poletti2019]

조현병과 강박 증상의 관계에 대한 문헌이 혼란스러운 이유 중 하나는, 두 가지 서로 다른 환자군을 분명히 구분하지 못했기 때문이다. 첫번째, 급성기를 지난 조현병 환자가 유지 치료 과정 중 정신병적 증상은 많이 줄어들었지만 대신 강박증상을 호소하는 경우가 있다. 둘째, 현재도 환청/망상이 심한 환자가 기이한 강박관념에 사로잡혀 행동적 문제가 심해지는 경우가 있다. 전자의 경우는 일반적인 강박증 환자들과 임상 양상이 유사하여 정신증 대신 강박증이 자리잡은 것으로 해석되는 경우가 많으며, 환자의 자아가 좀더 굳건해진 증거로 받아들여지기도 한다. 이에 비해 후자는 강박 내용이 이치에 맞지 않고 병식도 결여되어, 보통 정신병적 와해가 더 심해진 것으로 진단된다.[@Poyurovsky2004; @Guillem2009]

두가지 경우를 완전히 서로 다른 환자군으로 구분할 수도 있고, 가성 강박(pseudo-obsession)을 논했던 것처럼, 후자의 환자들은 진짜 강박 장애를 겪는 것이 아니라고 단언할 수도 있다. 그러나 또 다른 가능성은 강박증의 생물학적 병리과정에 조현병이 영향을 미칠 수 있다는 점이다. 즉 조현병 경과 중 어떤 시점에 강박 장애가 병발되느냐에 따라 발현 양상이 달라질 수 있다. 정신병적 증상이 조절되고 있는 상태에서 강박 장애가 시작되면, 일반 강박 장애 환자와 다를 바 없는 증상 및 경과를 보일 수 있지만, 사고장애나 인지적 결함이 심한 상태에서 강박 장애의 병리학적 프로세스가 진행되면 강박의 내용이 기괴해지거나, 병식을 획득하기 어려울 수 있다. 증상에 저항하기 위해선 자신의 강박 증상이 비논리적이고 불합리하다는 것은 인식해야 한다. 관해 상태의 조현병 환자라면 어려운 일이 아니겠지만, 심한 조현병 환자에게 이를 기대하기는 어려울 지도 모른다. 물론 이러한 논의는 정신과적 질병의 본질 즉 병태생리적 프로세스가 겉으로 드러나는 증상과는 별개로 존재한다는 가정에 입각해있다. 그러나 이는 논란이 많은 전제이다.

### 감별 진단

소위 현대적인 연구들은 통계적 분석기법에 상당히 의존하고 있지만, 조현병과 강박 장애를 구분하는데는 별반 도움이 되지 못하고 있다. 계량 심리학자(quantitative psychologists)들은 대표적인 강박 장애 척도인 Y-BOCS 결과를 요인분석함으로써, 개개 환자들의 증상 구조를 파악하고자 하였다. 이러한 연구를 통해 Y-BOCS는 대체로 3-5개의 요인으로 나뉘는 것으로 보고되었으며, 최근에는 5-요인 (저장 강박, 오염, 대칭/정리, 종교적/성적 금기, 공격성/확인) 설이 널리 받아들여지고 있다.[@Grover2017]학자들은 이를 근거로 강박 장애 환자와 조현병 환자의 Y-BOCS 요인 구조를 비교해보았으나, 뚜렷한 차이를 발견하지 못하였다.[@Faragian2008; @dehaan2015]

정량적인 차이는 발견되지 않았으나, 이론적으로는 몇 가지 구분점을 제시해 볼 수 있다. 일단 조현병으로 진단되었다가 추후에 강박증상을 보이는 경우에는, 대체로 병존 진단이 내려진다. 반면 정신병적 증상이 심하고, 강박 내용이 기괴하며 병식은 물론 저항도 제대로 하지 않는 경우 가성 강박의 진단이 내려질 수 있다. 가성 강박의 경우, 환자들은 저항을 못하는 것에 멈추지 않고, 그 내용에 매혹되거나 상상을 통해 내용을 부풀리는 등 자아동조적인 반응을 보일 수 있다.

물론 정신병적 증상이 심하다 해서, 모든 환자가 강박 증상을 자아동조적으로 받아들인다는 뜻은 아니다. 사고 장애나 망상의 심각도와는 관계없이, 자아이질적인 강박 증상때문에 고통받을 수 있다. 이런 면에서, 조현병 환자의 강박 증상을 1) 자아이질적 강박, 2) 자아동조적 강박, 3) 강박-망상 연속체로 구분해서 생각할 수 있다.[@cunill2011] 특히 강박-망상 연속체인 경우 강박적 의심이 지배관념을 낳고, 연이어 망상적 확신을 낳는 경과를 밟을 수 있다.[@Guillem2009] Poyurovsky 등[@Poyurovsky2004]는 자아이질적 강박일 때만 조현병과 강박 장애의 동시 이환으로 보고, 후자의 두 경우는 조현병의 경과 중 나타나는 특수 증상으로 보아야 한다고 제안하였다.

그러나 Parker와 Barrett[@Parker1997] 등과 같이, 강박 장애를 감별하고자 애매하기 짝이없는 **자아이질성**을 파헤치는 것은 실제 임상에서 별 도움이 되지 않는다고 주장하는 학자들이 많다. 이들은 질병 경과에 따른 변화를 감안해야 한다고 강조한다. 강박 장애 환자도 만성화되면 자아이질적이었던 강박이 자아동조적으로 변할 수 있으며, 조현병 환자라도 전구기에는 대부분 강박 증상에 대해 자아이질적으로 느끼고 저항한다. 질병 경과에 따라 기대되는 바와, 환자가 나타내는 증상 사이의 격차에 주목할 필요가 있다.[@gangdev2002; @Rodriguez2010; @Oulis2013; @Zink2014]

강박 증상과 망상을 구분하기 위해, 병식이나 자아이질성이 아니라 환자의 주관적, 감정적 경험을 중요시해야 한다는 견해도 있다. 망상은 사실과 다른 믿음에서 멈추지 않는다. 망상은 환자에게 있어, 그 진실성을 수호해야 하는 핵심적 가치이다. 그렇기 때문에 망상의 진실성을 의문시하는 주변 사람들을 회피하거나 공격하며, 망상을 진실로 만들기 위해 다른 기억들조차 왜곡시킨다. 때문에 망상적 믿음에서 비롯된 반복 행동은 정당한 것이며, 환자에게 불안이나 고통을 주지 않는다. 이에 비해 강박 증상은 환자가 수호해야 하는 진실이라기보다는, "설명할 수는 없지만" 떠올려지거나 수행해야만 하는 어떤 것이다. 환자가 강박 행동을 반복하는 것은, 망상을 지키기 위해서가 아니라, 이러한 무언가 마무리되지 않았다는 불편감을 해소하기 위함이다.[@Brakoulias2011; @Oulis2013] 또한 강박 증상에 동반되는 불편감은 자신의 행동이 효과적으로 완수되었는지 스스로를 믿지 못한다는 의문이다. 따라서 망상과는 달리 믿음이나 신념으로 이해될 수 없다.

강박 행동과 상동증을 구분할 수 있느냐는 또 다른 난제이다. 긴장형 조현병의 유병률이 높았던 시절에는 이들이 보이는 반복 행동이 강박 증상으로 이해되기도 하였다. 강박 행동은 투렛 증후군, Sydenham 무도병, 헌팅턴 병 등 원발성 운동장애와 연관성이 있다고 알려져 왔는데[@Krüger2000; @Swets2019], 이처럼 신경학적 증상으로 이해하기 시작하면 상동증과 구분할 근거가 엷어져 버린다. 강박 증상을 동반한 조현병 환자에게서 상동증, 매너리즘, 거부증, 강경증, 운동이상증, 얼굴 찡그림, 반향현상 등 긴장증 증상이 자주 관찰되는데[@Krüger2000], 이런 현상을 <s>Leonhard</s>[^17-03-9]는 manneristic catatonia라고 명명하기도 하였다. 어떤 강박 장애 환자들은 주저함때문에 강박적 느림(obsessional slowness)을 보인다. 이들은 사소한 일에도 너무나 시간이 많이 걸리기 때문에, 긴장증적 부동증과 혼동될 때가 있다.[@Fontenelle2007]

[^17-03-9]: **Karl Leonhard (1904\~1988)**: 독일의 정신과 의사. 동독 치하에서 의사로 근무하면서 내인성 정신병의 분류체계를 집대성하였다. 그는 연구 결과를 "Aufteilung der endogenen Psychosen (Classification of endogenous psychoses)"라는 책으로 펴냈는데, 동독의 공산정권이 반출을 허락하지 않은데다가 주류 정신의학 체계와 어긋난 점이 많았기 때문에 제대로 빛을 보지 못하였다. 사망한 이듬해 International Wernicke-Kleist-Leonhard Society가 창립되면서 그의 업적이 재평가되기 시작하였다.

침습적인 심상은 강박 증상과 흔히 혼동되는 증상 중 하나이다. 예를 들어 머리 속에서 불현듯 노래 곡조가 떠올라, 아무리 떨쳐내려고 해도 떠나지 않는다고 호소하기도 한다. 만약 조현병 환자가 이런 호소를 하게 되면, 블로일러의 해석에 따라 일부 사고 내용이 자아의 통제를 벗어나는 자동증으로 판단하고, 정신병적 증상의 일부로 진단할 수 있다. 그러나 동일한 증상을 일반인이 호소하면 강박 장애 혹은 강박적 경향이라고 진단할 지도 모른다.

사실 간간히 일어나는 침습적 심상은 정상인에게도 높은 비율로 발생하며, 정신병리로 볼만한 근거는 없다. 한 조사에 따르면 일반 인구의 85% 이상이 1주일에 한번 이상 음악적 심상을 경험한다고도 한다.[@liikkanen2011] 그러나 죽음과 파멸, 질병과 손상, 폭력과 재난, 신성모독, 문란하거나 파괴적인 성적 행위 등에 대한 침습적 심상은 강박장애 환자와 조현병 환자 모두에서 높은 빈도로 관찰된다.[@de1986] 한 연구에 따르면 강박 장애 환자 중 70% 이상이 주로 시각적인 침습적 심상을 반복적으로 경험한다고 한다.[@Moritz2014; @Röhlinger2015] 이러한 시각적 혹은 청각적 심상이 불수의적으로 반복되면 환자들은, Séglas가 언급한 강박적 환각에서처럼 환시/환청으로 경험하기도 한다. 과거 학자들은 진성 환각, 가성 환각을 구분하여, 침습적 심상에 의한 환각을 가성 환각으로 분류하기도 했으나, 현대에 와서 이러한 구분은 큰 의미가 없어졌다. 따라서 침습적 심상을 유난히 심하게 겪어 고통스러워하는 환자를 정상으로 보아야 할 지, 강박 장애 혹은 조현병의 초기로 보아야할 지는 어렵지만 중요한 감별 진단 과제이다.

### 조현병의 경과에 강박 증상이 미치는 영향

조현병 환자에게 있어서 강박 증상이 인격의 와해를 막아 준다는 Stengel[@stengel1945]의 고전적 견해와는 달리[^17-03-10], 현대의 연구들은 강박 증상이 동반된 조현병 환자가 증상도 심하고 예후도 좋지 않다는 것을 확인해주고 있다.

[^17-03-10]: 전통적으로 강박장애는 신경증(강박신경증, obsessional neurosis)으로 분류되었으며, 정신증보다는 정서 장애 특히 우울증과 연관되는 것으로 생각되었다. Adolf Meyer의 영향을 받는 미국 정신의학계는 개인이 심리사회적 스트레스에 대응하는 방식을 "reaction"이라 칭하였는데, 여기에는 psychotic reaction이 있는 반면 neurotic reaction도 있다. 따라서 당대 학자들은 obsessional neurosis로 스트레스에 대처하다가 이 마저 깨어지면 psychotic breakdown이 된다고 생각하였다. 즉 obsession이 일종의 "buffer" 역할을 해준다는 것이다.[@stengel1945] 이러한 생각은 현대에도 영향을 끼치고 있다.[@wehbé2019] 예를 들어 클로자핀 사용 후 나타나는 경한 강박증은 조현병에 대한 "보호 인자" 역할을 한다고 주장되기도 한다.[@agostoni2022]

Kim 등[@kim2015]은 조현병 이환 기간과 무관하게 강박 증상이 있으면 PANSS 점수 및 Calgary Depression Scale for Schizophrenia로 측정한 우울 점수가 높다고 하였다. 대규모 메타분석 에서도 강박 증상이 있는 조현병 환자들은, 그렇지 않은 환자에 비해 양성, 음성 및 일반 증상이 모두 심했다.[@Cunill2009] 이는 강박 장애가 조현병을 악화시켰다고 해석할 수도 있지만, 강박 증상이 동반되는 조현병 환자군이 따로 있다고 해석할 수도 있다. Üçok 등[@Üçok2011]의 연구에 따르면 강박 장애가 동반된 조현병 환자군은 발병 연령이 빠르고 공존 정신질환과 입원 횟수가 많으며, 취업률과 기능 수준이 낮았다. 강박 증상의 정도와 정신병적 증상 간에 뚜렷한 상관관계가 보이지 않는 것도 이러한 아형 가설을 지지하는 소견이다. 그러나 여전히 이런 연구들은 두 가지 유형의 환자, 즉 정신병적 증상이 조절되고 있으면서 강박 증상이 나타나는 환자와, 두 증상 모두 심한 환자를 구분하지 않았다는 한계를 지닌다. 예를 들어 Ongür와 Goff[@Ongür2005]가 조사한 바에 따르면, 강박 증상이 심한 환자군은 강박 증상이 없는 환자와 비교했을 때 양성 및 일반 증상이 훨씬 심한 것으로 나타났으나, 강박 증상이 가벼운 환자들은 강박 증상이 없는 환자와 별 차이가 없었다. 또한 초기 조현병 환자를 대상으로 한 연구에서는 강박 장애가 있을 때 정신병 증상이 오히려 적다고 보고되었다.[@Poyurovsky1999] 한편 강박 증상이 있는 환자들은 정신병적 증상의 심각도와는 상관없이 병전 적응이 불량하였으며[@de2013], 삶의 질, 대인관계 만족도 등도 떨어졌다.[@Tiryaki2010; @Üçok2014]

강박 증상이 조현병 환자가 자신의 자아를 지키는 데 도움을 주는 지, 아니면 붕괴를 가속시키는 지를 떠나, 단순히 두 개의 독립된 병리적 프로세스가 겹치는 것만으로도 예후가 불량해진다는 견해도 있다. 예를 들어 강박 장애는 그 자체만으로도 인지 기능을 상당히 저해하는데[@Abramovitch2019], 이런 효과가 조현병과 겹치면 인지 기능 저하가 더 가속화될 우려가 있다. 연구자들은 강박 증상이 있는 조현병 환자와 없는 조현병 환자 사이의 인지 기능 차이에 대해 주의깊게 관찰하였다. 일부 연구에서는 전자의 환자들에서 일부 인지 기능이 더 저하되었다는 결과가 나타났지만, 아직은 결과들이 일관되지 못하여 결론을 내리기는 힘들다.[@Cunill2013; @Schirmbeck2013; @Frías2014] 한편 강박장애가 있는 환자군이 항정신병 약물로 인한 추체외로 부작용이 심하다는 관찰결과는 이들의 뇌 기능이 좀더 취약하다는 것을 시사하였다.[@Ohta2003; @Tibbo2000]

### 조현병의 경과와 강박 장애

조현병의 경과 중 어떤 시기에 강박 증상이 나타나느냐에 따라 그 중요성이나 해석이 달라질 수 있다. Schirmbeck과 Zink[@Schirmbeck2013a]는 강박 증상/장애의 유병률이 위험 정신 상태 12.1%/5.2%, 초발 정신병 17.1%/7.3%, 만성 조현병 25%/12.1%로 조현병이 만성화될수록 빈도가 증가한다고 보고하였다. 이에 대해 학자들은 비정형 항정신병 약물이 강박증을 유발시켰을 것이라 해석하기도 한다. 그러나, 다른 연구 들에서는 고위험 군이나 초발 환자에서도 상당한 빈도로 강박 증상이 발견되어, 만성화 정도와 강박 증상 빈도 사이의 연관 관계를 발견하지 못하였다.[@Niendam2009; @cunill2011]

Zink[@Zink2014]는 조현병 경과 중에 강박 증상이 등장할 수 있는 상황을 다음과 같이 정리하였다.

1)  정신병 발병 이전에 강박장애가 독립적으로 발병하는 경우

2)  정신병 증상 발현의 전조 증상으로 강박 증상이 발생하는 경우

3)  정신병과 강박 증상이 동시에 발생하는 경우

4)  조현병의 만성 경과 중에 강박 증상이 발생하는 경우

5)  항정신병 약물 사용 후 강박 증상이 현저하게 악화되거나 또는 새로 발생하는 경우

최근에 특히 관심을 모으고 있는 것은 조기 정신증 혹은 초고위험군 환자에서 나타나는 비특이적인 강박 증상이다. 이들이 보이는 강박 증상의 특징을 잡아내어, 이를 향후 정신증 발병 위험을 예측하는데 사용하는 것이 연구자들의 바람이다. 실제로 초고위험군 환자가 강박 증상을 보이는 비율은 2.7\~37%[@Zink2014], 11\~60% [@Soyata2018] 정도로 상당히 높게 보고되며, 강박 장애 진단이 내려지는 비율도 1.5\~30%[@Zink2014]로 높은 편이다. 동일한 초고위험군 환자라도 강박 증상을 보이는 환자와 그렇지 않은 환자가 차이가 날 수 있다. 전자는 우울 증상이 심한 편이며[@Niendam2009; @DeVylder2012; @de2013a], PANSS의 음성 증상과 일반 증상 점수가 높고 전반적인 기능 수준이 낮지만, 일부 신경인지검사에서는 오히려 더 나은 결과를 보이기도 한다.[@Hur2012] 연구에 따라 직업/학업 기능이 더 낫다는 보고도 있으나[@Soyata2018], 일반적인 견해는 인지 기능이 잘 유지됨에도 불구하고 사회적, 직업적 적응이 더 불량하다는 것이다.[@Hur2012; @Zink2014]

하지만 조기정신병 전문가들의 바람에도 불고하고, 강박 증상이 있다고 해서 정신증으로 이행하는 비율이 높은 것은 아니다. Niendam 등[@Niendam2009]은 오히려 강박 증상 환자가 이행률이 낮다고 하였으나, 다른 연구자들은 큰 차이가 없다고 보고 있다.[@Fontenelle2011; @Fontenelle2012; @Fusar-Poli2014]

전구기에 강박 증상을 보이다가 다른 질환으로 이행한 환자들 중에는, 조현병보다 기분 장애로 발병하는 경우가 많은 편이다. Hagen 등[@Hagen2013]이 조사한 초발 정신증 환자 중에서 약 10% (26명)가 강박 장애의 진단 기준을 만족시켰는데, 이중 조현병 환자는 5명에 불과하였다. 한편 강박 장애를 동반한 조기 정신증 환자들은 치료를 일찍 받는 경향이 있는데, 발병 연령이 낮기 때문이라기보다는 우울/자살 사고가 심하여 일찍 발견되기 때문인 것 같다.

전구기나 발병 전부터 강박 증상을 보여왔던 환자가 있는 반면, 조현병이 먼저 드러난 후 나중에 강박 증상을 보이는 환자가 있다. 이 비율에 대해선 그다지 자료가 없는데, 한 연구에 따르면 조현병으로 입원 치료를 받은 후 2년 내에 새로 강박 증상이 발생할 비율이 3.5\~4.3% 정도였다.[@Craig2002] 한번 발생한 강박 증상이 어떤 경과를 밟는 지에 대해서도 자료가 미비하다. De haan 등[@de2013]의 5년 추적 자료를 보면, 15.1%의 환자는 첫 입원 때만, 13.4%의 환자는 5년 내내 강박 증상을 보였다. 첫 입원때는 없었던 강박 증상이 3\~5년 후에 새로 나타난 비율은 7.0%였다. 이 자료에 따르면 조현병 환자의 강박 증상은 대체로 나타났다 사라졌다 하며, 오랜 기간 지속되는 경우는 그리 많지 않음을 알 수 있다. 이중 강박 증상이 지속되는 환자들이 특히 문제가 되는데, 이들은 특히 불량한 임상 경과를 밟게 된다.[@Schirmbeck2018] 그에 비해 초반에 강박 증상이 있다가 해소된 환자들은, 그에 발맞추어 정신병적 증상도 호전되고 기능도 향상된다.

이러한 논의 중에서도 두 종류의 환자군이 있다는 것을 짐작할 수 있다. 정신병적 증상 및 강박 증상이 그리 심하지 않으며, 강박 증상이 간헐적으로만 나타나는 환자들은 강박 증상이 겹쳐있을 때는 많이 우울해하지만 회복의 기회가 많고 예후도 크게 나쁘지 않다. 그러나 증상이 심하고, 특히 강박 증상이 지속되는 환자는 정신 증상이 심하고 사회적 기능도 떨어지며, 예후도 부정적이다. 따라서 연구자들은 강박 증상과 예후 사이에 종모양의(bell shaped)의 상관관계를 제안한다.[@Tonna2016] 또 다른 연구자들은 우울증만 잘 조절한다면, 초발 시에는 강박 증상이 보호 기능을 할 수도 있지만, 만성 환자들에게는 악화 요인으로 작용한다고 본다.[@bottas2005]

## References {.unnumbered}
