---
title: "정신질환자와 범죄"
editor: visual
bibliography: References/18-03.bib
---

## 조현병 환자와 범죄

조현병 환자가 아무런 이유없이 범죄를 저지르는 사례가 끊임없이 언론매제체 보도되고 있지만, 이는 상당히 과장되어 있다.[^18-03-1] 특히 연쇄살인이나, 총격살상(mass shooting)과 같은 끔찍한 사건이 벌어지면, 습관적으로 범인이 정신질환을 앓고 있는 것 아니겠냐는 논평이 나오곤 한다.

[^18-03-1]: 정신과 의사들은 물론 많은 관련단체가 언론의 편향 보도의 문제점을 지적하고 해결책을 제안하고 있다. 예를 들어 2021년 부산 지역 정신장애인 당사자 단체인 침묵의소리는 '정신장애 보도 미디어 가이드라인 2.0'을 내놓았으며, 서울시정신건강복지사업지원단은 한국의학바이오기자협회 등과 함께 '[정신질환 보도 가이드라인 1.0](https://blutouch.net/plus/reference/etc/7779)'을 제작, 배포하고 있다. 그러나 법적으로 이를 강제할 수단도 없고, 하다못해 교육을 받아야 한다는 규정도 없다.

실상 사회에서 벌어지는 범죄의 대부분은 아무런 정신질환을 앓고 있지 않은 일반인에 의해 벌어진다. 우리나라의 경우 전체 범죄 중 전체 정신질환 환자에 의한 범죄는 0.4% 정도에 지나지 않는다. 미국에서 조사한 바에 따르면, 한 건의 살인사건을 막기 위해선 35,000명의 조현병 환자를 감금해야 한다고 한다.[@large2011] 이는 조현병 환자를 잠재적 범죄자로 몰아세운다고 해서, 범죄를 줄이는데 하등 도움이 되지 않는다는 것을 의미한다.

물론 조현병 환자가 범죄를 저지르지 않는다는 뜻도 아니고, 문제가 심각하지 않다는 뜻도 아니다. 조현병 환자의 10% 가량은 이런저런 폭력 사건을 일으킨다. 국립법무병원에 입소되어 있는 1,000명 가까운 입소자 중 절반 가량이 조현병을 앓고 있으며, 이중 43.3%가 살인죄이다. 조현병 환자가 폭력을 저지르는 대상 중 상당수는 보호자 혹은 가족이며, 존속살인 사건의 상당수를 조현병이 차지한다. 그야말로 길가던 행인에게 폭력을 행사했다는 건수도 조금씩 증가하고 있다. 조현병 환자에 대해 따로 통계가 나오지는 않았지만, 경찰청 자료에 의하면, 전체 폭력 사건 가해자 중 정신질환자 비율은 2013년 0.61%에서 2017년에는 0.98%로 점진적인 증가추세를 보인다.

이러한 통계수치를 어떻게 해석해야하는지는 각자의 이해관계에 따라 달라진다. 범죄예방에 관심을 둔 일각에서는 폭력사건이 발생하거나 예상되면 경찰이 단독으로 응급입원시킬 수 있게 하자고 주장한다. 또는 정신질환자가 범죄를 저지르면, 출소 후에도 접근제한 및 격리 조치를 하자는 의견도 있다. 이에 반해 인권을 중시하는 측에서는 강제 치료와 관련된 이러한 조치는 인권침해의 우려가 있다고 목소리를 높인다. 의사들 측의 견해는 어떤가? 정신과 의사들은 대부분의 폭력 사건이 치료받지 않은 정신질환자에 의해 저질러지고 있음에 주목하여, 어떻게든 치료 기회를 확대해야 한다고 강조한다. 동시에 폭력 전과가 있는 환자라도 치료만 잘 받으면 범죄 위험은 거의 없어진다고 주장한다. 그러나 조현병 자체가 잘 치료되지 않으며, 모든 폭력이 증상때문인 것도 아니라는 점을 고려한다면, 의사 측의 견해는 지나치게 낙관적으로 들린다.

조현병 환자의 범죄 문제는 쉽사리 결론을 낼 수 있는 문제가 아니다. 환자를 범죄로 몰아가는 요인은, 질병 뿐만 아니라, 환자의 개인적 성향, 가족들과의 불화, 장애인에 대한 복지환경, 사회 전체의 편견과 낙인 등이 모두 종합적으로 작용한다. 모든 조현병 환자들이 잠재적 범죄자라는 편견을 갖지 않고, 우리 사회 구성원으로 받아들일 수 있으려면 의사들은 물론 사회 전체의 인식 전환이 필요하다.

## 가정 내 폭력

### 개요

탈원화와 더불어 가족들은 심각한 정신질환을 앓는 환자와 함께 살면서 돌보아 주어야만 하게 되었다. 물론 돌봐줄 가족이 있는 환자들은 그렇지 못한 환자들보다 치료 참여가 높고 입원을 덜하며 삶의 질이 높다.[@Norman2005] 가정의 화목한 분위기가 조현병 경과에 커다란 영향을 미친다는 점은 부인할 수 없다.

그러나 모든 밝은 면에는 드러나지 않는 어두운 구석이 있다. 조현병 환자의 가족들은 다른 정신질환자의 가족에 비해 삶의 질이 낮고 스트레스에 시달린다.[@Awadalla2005] 가족들의 부담은 보살핌의 수준을 낮추고 이는 다시 환자의 경과를 악화시킨다.[@Caqueo-Urízar2017] 해결되지 않는 증상과 가족구성원으로서의 역할을 다하지 못하는 환자에 대한 가족의 불만은 <s>표출감정</s>[^18-03-2]으로 구체화되며, 높아진 표출감정은 재발의 위험을 증가시킨다.[@butzlaff1998; @King1999]

[^18-03-2]: **표출감정 (expressed emotion)**: 정신질환자를 둘러싼 가족 내부의 환경을 평가하는 지표 중 하나이다. 가족구성원이 얼마나 환자에게 직설적으로 감정표현을 하느냐를 평가하는데, 노골적 비판, 적대감, 과도한 참견이나 과보호 등 대부분 부정적인 감정표현이 포함된다.

이 때문에 특히 사회를 등지고 집안에 칩거하는 환자들은 가족 구성원에게 분노를 표출하고 폭력을 행사하기 쉽다. 조현병 환자가 포함된 302 가구를 대상을 한 일본 연구에서 환자가 가족에게 폭력을 행사한 비율은 평생 60.9%, 지난 1년 동안 27.2%였고[@Kageyama2015], 같은 연구자들의 후속 연구에서는 277명의 보호자 중 87.7%가 심리적 폭력을, 75.8%가 신체적 폭력을 경험하였다.[@Kageyama2018] 호주와 캐나다에서 행해진 연구에서도 약 30\~40%의 가족 구성원이 환자로부터 폭력을 당하였다.[@Vaddadi2002; @chan2008]가 각각 보고되었다. 신체적 폭력이 아닌 언어폭력은 거의 80%의 보호자가 경험하였다.[@Loughland2009] 폭력의 대상은 어머니, 아버지, 손아래 여동생, 손위 형제의 순으로 잦았다.[@Kageyama2015] 가정 내 폭력은 가정 외 폭력과 달리 남녀 비가 비슷하며, 심지어 여성 환자가 더 많았다는 보고도 있다.[@robbins2003; @Fleischman2014]

### 가족의 비판에 대한 환자의 인식

환자가 폭력을 행사하는 이유가 전적으로 가족의 표출감정때문이라고 몰아세우는 것은 바람직하지 않다. 그러나 표출감정이 고양된 가정에서 사는 환자들은 그렇지 않은 환자들보다 보호자의 비판을 더 고통스럽게 느낀다.[@Scazufca2001; @Cutting2006] 보호자가 환자에 대해 부정적이고 비판적인 언급을 하면 할수록, PANSS의 일반 증상 즉 우울, 불안, 타인에 대한 불신, 활동의 저하와 연관되었다.[@Kuipers2006]

환자는 편집적 경향 때문에 자신과 타인에 대한 부정적인 도식을 갖게 된다.[@Smith2006] 환자에게는 가족구성원과의 대인관계가 매우 비중이 높기 때문에, 그들과의 상호작용은 이러한 부정적 도식을 완화시킬 수도 훨씬 강화시킬 수도 있다. 가족들 역시 고통을 겪는 당사자이기 때문에 환자에게 중립적으로 다가갈 수 없고, 한편 환자들은 유일하게 의존할 수 있는 가족들에게 비판을 받게 되면서 불안이 심해지고 심하면 폭력을 행하게 된다.[@Freeman2003] 따라서 가족의 비판적 태도가 환자의 증상과 행동 양상에 영향을 미칠 수 있음을 강조하고, 환자에게는 보호자의 태도를 적절히 다룰 수 있는 기술을 갖추도록 도와야 한다. 그래야 폭력과 재발의 악순환을 막을 수 있다.[@Onwumere2009]

### 가정 내 폭력이 가족구성원에게 미치는 영향

조현병 환자를 돌보는 가족들은 안그래도 환자의 증상, 경제적 곤란, 자책이나 낙인, 사회적 고립 등으로 커다란 부담을 안고 사는데, 게다가 환자가 가정 내 폭력이라도 저지르면 그 고통은 더욱 심해진다.[@Vaddadi1997; @Hanzawa2013; @Kageyama2016] 폭력을 경험한 보호자의 1/5은 자신이 죽을 지도 모른다는 공포를 느끼며[@Loughland2009], 1/3은 환자가 죽기를 바라거나 환자를 죽이고 자신도 자살할 생각을 한 적이 있다.[@Kageyama2018]

폭력을 당한 가족 구성원들은 대응책으로 환자와 따로 살기도 하지만, 경제적 지원, 반복되는 재발과 입원, 신체적 건강의 악화, 사법적 문제때문에 지속해서 관여를 하지 않을 수 없다. 더군다나 한국을 비롯한 동아시아에서는 집안의 체면 때문에 친척이나 지인에게 환자의 정신질환을 밝히려 하지 않는 경향이 있는데[@Chang2006], 이는 환자를 집밖에 내보내지 않으려는 경향을 낳을 수 있다.[@Hanzawa2013] 가족들은 스스로에게 "환자의 가족"이라는 낙인을 찍고, 이러한 수치심과 죄책감을 억압하기 위해 환자를 없는 사람 취급하기도 한다.[@Hanzawa2010] 이러한 적응방식은 오히려 환자의 분노를 자극한다.

한국, 일본, 중국, 대만에서는 법률적으로 환자를 보호하고 치료를 받게 하는 책임이 가족에게 지워진다. 환자가 가족에게 폭력을 행사하여 비자의 입원을 시켜야 하는데, 가족의 동의가 필요하다보니 가족이 또 입원을 강제하는 가해자가 되어버린다. 환자는 애초의 분노에 더해 자신을 입원시켰다는 것에 대해 분노를 더욱 누적하니, 가족과 환자와의 감정의 골은 더욱 깊어진다.

환자가 나이가 들수록, 환자를 돌보는 보호자 역시 노령에 접어든다. 보호자의 체력이 약해지고 환자를 잘 통제하기 어렵게되면서, 환자는 더욱 제멋대로가 되며 폭력에 의지하는 경향을 보인다. 환자는 환자 나름대로 자기 인생의 실패를 부모 탓으로 돌리고, 부모는 부모대로 노년의 안식이 환자때문에 일그러졌다고 비난한다. 특히 경제적 어려움, 다른 거주 시설의 부재, 폭력 대처 방법에 대한 무지 등은 노령의 부모들이 폭력의 희생자가 되기 쉽게 만든다.[@Kageyama2016]

### 대처방안

가족들을 폭력으로부터 보호하려면 1) 환자의 치료 및 2) 가족에 대한 적극적인 질병교육과 가족상담 뿐만 아니라, 3) 지역사회 정신보건체계 및 사회보장 제도의 확충이 요구된다.더불어 치료진은 보호자들이 1) 폭력의 위험신호를 인지하고, 2) 차분한 대화를 통해 긴장을 완화시키며, 3) 위급할 때 도움을 청할 수 있는 대응전략을 숙지하도록 도와야 한다. 위험한 환자를 즉각 현장에서 배제시켜, 적절한 치료 시설로 운송할 수 있는 인프라가 갖춰져야 하며, 가족이 입원시키는 주체가 되는 현행 제도도 다시 재고되어야 한다.

## 스토킹

### 개요.

Meloy[@meloy1998]는 스토킹(stalking)에 대해 '오래 된 행동이지만, 새로운 범죄'라는 모순된 표현을 썼다.[^18-03-3] 스토킹은 피해자가 원치 않는 감시와 추적, 접촉과 소통의 시도, 위협 등을 함으로써 안전에 대한 공포를 유발하는 직/간접적인 행위를 의미한다.[@Mullen1999] 과거에는 스토킹의 부정적 영향을 인정하면서도, 호감이나 관심의 표현이라고 넘어가기 일상이었다. 북미에서조차 스토킹을 범죄로 인정하기 시작한 것은 1990년대 이후이다.

[^18-03-3]: 16세기 문헌에서는 prowler 혹은 poacher라는 단어로 표현되었다. "Stalker"라는 단어는 20세기 초에 들어서부터 사용되기 시작하였는데, 초기에는 영화배우나 가수 등 유명인사에 집착하여, 편지나 선물을 보내고, 어떻게든 자신을 어필하려는 사람들을 뜻하였다. 20세기 후반부터는 주로 헤어진 옛애인 등 이성관계와 결부되어 피해자를 괴롭히는 가해자를 의미하게 되었다.

가해자는 전화, 문자, 편지, 전자우편, 낙서, 선물 등을 동원하거나, 피해자가 나타날만한 장소에서 서성대거나 감시하고, 피해자가 나타나면 접촉을 시도한다. 피해자를 만나지 못하면 가족, 친지를 찾아가기도 하고, 피해자를 대신해서 물건을 주문하거나 예약을 하고, 헛소문을 퍼뜨리기도 한다. 스토킹은 그 자체로 끝나는 것이 아니라, 종국에는 신체적 공격, 성폭행, 납치, 살인으로 이어지는데, 미국에서는 스토킹의 1/4이 심각한 폭력 사건으로 이어졌다.[@meloy1998; @Mullen1999]

스토킹 피해자는 시간에 따라 심해지는 공포를 느끼며, 일상적인 생활에도 제약을 느껴 삶이 붕괴된다. 피해자 입장에서는 스토킹을 중단시킬 해법을 찾기 어려우며, 사법 당국 역시 신체적인 위해가 가해지지 않는 이상 수사권을 행사하려 하지 않는다.[@Weller2013][^18-03-4]

[^18-03-4]: 우리나라에서는 2021년 10월에야 비로소 '스토킹범죄의 처벌 등에 관한 법률'이 시행되었다. 이제 스토킹범죄를 저지른 사람은 3년 이하의 징역 또는 3천만원 이하의 벌금에 처한다. 하지만 이 법은 소위 '반의사불벌죄'에 해당하기 때문에, 수사과정에서 피해자가 처벌을 원치 않는다는 의사표시를 표명할 경우 처벌을 하지 못한다. 이러한 문제점때문에 '반의사불벌죄'라는 독소조항을 없애려는 개정 논의가 진행중이다.

가해자는 흔히 비사회적 또는 자기애적 성격이 두드러지고 피해자에게 권력을 행사하고 통제하려는 소망이 동기가 된다. 스토킹은 집착이자 강박적인 모습을 띠며, 발각이나 처벌 가능성이 높아져도 중단하지 않는다. 상당수는 이전에도 사회 규범을 수차례 위반한 전력이 있다.[@Dressing2011]

### 스토킹과 정신질환

스토킹을 정신질환으로 보아야할지, 정신질환자가 스토킹을 저지를 위험이 높은지에 대해선 충분한 연구가 이루어지지 않았다. Zona 등[@zona1993]은 스토커와 피해자의 유형에 따라 (1) 단순 강박형(simple obsessionals), (2) 애정 강박형(love obsessionals), (3) 색정광(erotomanics)으로 분류하여, 스토킹을 일종의 정신질환으로 보았다. Mullen 등[@Mullen1999]은 동기에 따라 (1) 거절당한 스토커(the rejected), (2) 친밀감 갈구 스토커(the intimacy seekers), (3) 무능력한 스토커(the incompetent), (4) 분개한 스토커(the resentful), (5) 약탈적인 스토커(the predatory)로 나누었다. 거절당한 스토커는 이전에 친밀했던 사람에게 집착하는데 재결합과 복수라는 양가적인 동기를 가지고 있으며 폭력의 위험이 가장 높았다. 모두 분노와 복수의 감정과 연결되어 있다.

<s>RECON 스토커 유형</s>[^18-03-5]은 스토커와 피해자의 관계에 따라 분류한다.[@Mohandie2006] 1) 스토커와 피해자 사이에 이전 교류가 있었던 Ⅰ형은 A. 친밀했던(intimate) 스토커와 B. 면식이 있던(acquaintance) 스토커로 나누며, 2) 이전에 교류가 없었던 Ⅱ형은 A. 유명인사(public figure) 스토커와 B. 낯선 스토커(private stranger)로 나뉜다. 친밀했던 스토커가 가장 난폭했던 반면, 면식이 있던 스토커는 정신병 환자일 가능성이 많다. 유명인사 스토커는 공격 위험은 낮으나 애정망상(erotomania)이 많았다.[@meloy2008]

[^18-03-5]: RECON (relationship and context-based) stalker typology

### 정신병적 스토커

스토커의 대다수는 정신질환자가 아니고 따라서 법률에 의해 처벌받아야 한다.[@Dressing2002] 하지만 개중에는 성격장애, 주요우울장애, 기분부전장애, 적응장애 등 매우 다양한 정신질환이 발견되며, 정신병적 장애도 드물지 않게 발견된다.[@Kamphuis2000; @Mohandie2006] 정신병적 장애를 제외하고는, 질병을 이유로 죄과가 감면되기는 어렵겠지만, 정신병적 장애를 앓고 있다면 처벌보다는 치료가 우선이 될 수 있다.

전체 스토커 중 정신병적 스토커의 비율은 5\~10% 정도로 추정된다.[@meloy1998] Mohandie 등[@Mohandie2006]의 연구에서는 면식이 있던 스토커와 낯선 스토커의 25%, 친밀했던 스토커의 11%가 정신병적 장애를 앓고 있었다. 유명인사를 대상으로 한 스토커의 80% 이상이 정신병적 장애 환자라는 보고도 있다.[@James2009] 후자는 소위 <s>색정광</s>[^18-03-6]이라 불리는 애정망상과 연관되며, 망상 장애 환자는 물론 현실검증력이 저하된 조현병 환자에게서도 발생한다.

[^18-03-6]: **색정광 (erotomania)**: 주로 젊은 여성 환자가, 자신보다 신분이 높고 나이가 많은 남자가 자신을 은밀히 사랑한다고 믿는 망상. 흔히 'de Clerambault syndrome'이라고 하는데, 그 이유는 프랑스의 정신과 의사인 Gaëtan Gatian de Clérambault (1872\~1934)가 1885년에 처음 기술하였기 때문이다. 정신과 의사의 치료를 받는 환자가 담당 의사에 대해 애정망상을 갖는 경우도 이에 해당되는데, 이는 정신병적 전이(psychotic transference)에 속한다고 해야할 것이다.

한편 정신질환이 없던 사람도 스토킹을 지속하다 보면 사고, 감정, 경험 등이 대상에 집중되면서 정신병에 근접하는 증상을 보이기도 한다. 대상에 온갖 주의가 집중되고, 자신의 행동을 정당화하면서 현실검증력이 소실되며, 스토킹 행위가 삶의 전반을 지배하여 직업이나 사회적 관계가 소홀해진다. 시간이 지날수록 스토킹을 위해 자신의 삶 전체를 포기하고, 외부 현실과는 괴리된다.[@Dressing2011]

### 가해자의 치료

가해자들은 치료에 대한 동기가 부족해서 법원의 명령에 의한 비자발적 입원치료가 필요할 수 있다. 그러나 이들이 입원하면, 바른 행실로 조용히 퇴원할 날을 기다리기 때문에 충분한 기간 동안 장기 입원을 유지하기란 쉽지 않다. 스토커의 위험은 자해나 타해에 있다. 이들은 다른 유형의 정신질환자보다 자살 위험이 높으며[@mcewan2010], 피해자를 살해한 후 자살할 가능성도 높은 편이다.[@Schlesinger2006]

스토커에 대한 효과적인 치료 방안은 없다. 스토커가 지니고 있는 색정망상 등의 망상은 특히 치료에 잘 반응하지 않는다. 법적 처벌을 면하기 위해 망상을 행동화하지 않도록 유도하는 것이 고작이며, 실제로 수감, 접근 금지 등 처벌이 시행되기도 하지만, 오히려 스토커들을 자극하여 더욱 위험한 행동을 초래하기도 한다.[@Kamphuis2000]

오히려 기존에 정신병적 장애를 앓고 있던 환자, 즉 조현병이나 양극성 장애를 앓고 있는 환자라면 기존 질환을 치료함으로써 스토킹을 중단시킬 수 있다. 애정망상 말고도 피해/질투 망상 때문에 스토킹을 할 수 있다.[@MacKenzie2011] 이런 경우 항정신병 약물을 통해 호전될 수 있다. 약물 순응도가 낮은 스토커에게는 장기지속형 항정신병약물 주사제를 사용하고 약물에 대한 반응이 좋지 않을 때에는 초기부터 clozapine을 사용한다.[@MacKenzie2011]

기저 질환이 없는 환자들, 특히 거절당한 스토커(the rejected)들은 대부분 반사회성이나 자존심의 상처때문에 스토킹 행위를 한다. 성격장애가 동반된 이들 스토커들에게는 법적 처벌과 함께 정신치료적 접근을 병용하는 것이 도움이 된다.[@Kamphuis2000] 그러나 스토커에게 심리치료를 제공하는 치료자는 자신이 다음 피해자가 될 수 있다는 위험을 감수해야 한다. 따라서 정신병적 장애를 앓고 있는 스토커에 대한 약물치료를 제외하면, 거의 치료가 이루어지지 않고 있다.[@MacKenzie2011]

## 조현병 환자에 대한 폭력

### 개요

조현병 환자의 폭력 위험이 일반인보다 조금 높기는 하지만, 실상 조현병 환자가 폭력의 피해자가 되는 경우가 훨씬 더 많다.[@Schug2013] 그러나 방법론상의 문제때문에 정확한 유병률이나 그 피해정도를 파악하기는 힘들다. 보통 환자의 자가 보고를 통해 폭력 피해를 조사하고 있지만, 피해 망상을 갖고 있는 환자들의 진술을 어디까지 믿어야할 지 의문이다.[@Goodman1999] 대부분의 폭력 사건은 상호적이라 단순히 누가 가해자이고 누가 피해자인지 구분하기 어려울 때가 많다. 또한 그 빈도와 심각성은 지역의 특성과 관련이 깊다.[@de2019] 예를 들어 핀란드는 범죄율이 낮은 만큼 환자들이 얽힌 폭력 피해의 빈도도 낮다.[@Honkonen2004]

### 유병률

2001년\~2013년까지 덴마크 전체 인구의 경찰 기록을 조사한 연구에서 폭력 피해의 경험은, 진단을 막론하고 정신질환을 앓는 남자가 1.76배, 여자가 2.7배 많은 것으로 보고되었다.[@Dean2018] 호주에서 진행된 연구에서는 정신병적 장애 환자들을 면접 조사하였는데, 1년 동안 폭력 피해 경험은 16.4% (남자 15.2%, 여자 18.3%)로 일반인구에 비해 남자는 3.7배, 여자는 6.8배 높았다.[@Morgan2016] 스웨덴에서 역시 정신병적 장애 환자를 대상으로 면접 조사했을 때, 지난 1년 동안 33%가 폭력을 경험했는데, 신체적 폭력 20%, 성폭력 15%, 언어적 위협 21%의 분포를 보였다. 폭력 발생장소의 59%가 집이었던 것으로 보아, 가족이나 지인이 가해자가 된 경우가 많았던 것으로 보인다.[@Bengtsson-Tops2012] 실제로 조현병 및 기타 정신병적 장애 환자, 특히 여성 환자들의 43.8\~83.3%가 평생에 한 번 이상 배우자나 연인으로부터 어떤 유형으로든 신체적, 성적 공격을 받는다.[@Wong2009; @Friedman2011]

조현병 환자들은 발병 전 전구기 동안에도 왕따, 따돌림 등의 피해를 많이 받는다.[@Trotta2013] 환자나 가족은 이러한 트라우마가 발병의 원인이라 생각하지만, 전구기 환자들의 사회적 위축이나 기이한 사고 등이 폭력의 피해자가 될 위험을 키운다. 반면 만성 조현병 환자가 노숙자가 된 경우 73.7\~87.0% 가량이 폭력의 피해를 입는다. 특히 여성 노숙자들은 성적 피해자가 될 위험이 크다.[@Roy2014] 정신병적 장애 환자 전체에 비해서도, 노숙자는 2.5배 이상 폭력의 피해자가 될 위험이 높다.[@Walsh2003; @Chapple2004]

일반인이 폭력의 피해를 입는 비율은 지난 수십년 동안 큰 변화를 보이지 않았으나, 조현병 환자들이 피해를 입을 위험은 1990년대 중반까지 점진적인 증가세를 보였다. 폭력 피해의 빈도는 1975년에 15.3%에서 탈원화가 완료된 1995년에 37%까지 상승하여 이후 별 변동없이 유지되고 있다. 이는 시설내에서 보호받던 조현병 환자들이 지역사회로 쏟아져 나오면서, 방어할 수단없이 폭력에 노출된 것이라 여겨진다.[@Short2013]

### 폭력 피해의 요인

조현병 환자에게 이유없는 폭력을 가하는 것은 중세 이후 유럽 사회의 전통이었다.[^18-03-7] 정신질환자를 배척하는 사회적 분위기에서 1) 동기가 있는 가해자, 2) 적당한 희생자, 3) 보호자의 부재라는 3가지 요소가 갖춰지면 폭력의 피해자가 발생한다.[@cohen1979] 조현병 환자는 사회적 안전망이나 보호자가 제대로 없는 상황에서, 부적절한 행동이나 엉뚱한 고집 등으로 가해자의 화를 북돋고, 동시에 제대로 방어/저항하지 못하기 때문에 폭력의 희생양이 된다.[@finkelhor1996]

[^18-03-7]: 중세의 마녀사냥은 정신질환자에게 사회가 부당한 폭력을 행사한 대표적인 사례이다.

장년기/중년기 환자보다는 청소년/성인기 초기의 환자나 노인 환자들의 폭력 피해 사례가 많은데, 전자는 또래 들 사이의 압력, 후자는 방어 능력의 부재와 관계가 있는 듯 하다. 성별 차이는 별로 없는데, 이는 일반인구에서 남성이 피해자가 될 위험이 높은 것과 대조된다. 그 이유로는 정신질환으로 인해 사회적 역할과 행동 양상이 달라졌을 가능성[@Khalifeh2010]과 여성에 대한 배우자의 폭력이 많기 때문일 가능성이 제시되었다.[@vandeinse2018]

빈곤한 환자, 실직한 환자들이 폭력 피해를 당할 위험이 높은 편이다. 빈곤한 환자들은 범죄률이 높은 주거지에 정착하며, 타인에게 경제적으로 의지하면서 무력한 피해자가 될 가능성이 크다. 한편 직장이 없는 환자는 의미있는 일상생활을 유지하지 못하면서 술에 의지하거나, 거리에서 방황하여 잠재적 가해자에게 노출될 위험이 높아진다.

증상과 폭력 피해의 위험과의 관계는 단순하지 않다. 사고 장해, 판단력 저하 및 빈약한 문제해결 능력은 위험을 인지하거나, 방어책을 강구할 능력을 손상시킨다. 하지만 역으로 증상이 심해지면 외출을 안 하거나, 의심과 피해사고 때문에 극도로 조심하기 때문에 보호 요인으로 작동할 가능성이 있다. 마찬가지로 음성증상은 사회적 회피를 초래하여 폭력 피해의 위험을 줄이지만, 여성의 경우에는 감정의 위축과 둔마된 정동이 성희롱 피해의 위험을 높일 수 있다.[@Chapple2004]

가족과 함께 거주하는 것은 일반적으로는 보호 요인으로 작동하지만[@Dean2007], 워낙 가족이나 지인으로부터 폭력 피해를 당하는 경우가 많아 그 효과는 상쇄되는 듯하다.[@Bengtsson-Tops2012; @Kageyama2015] 하지만 이를 직접적으로 검증한 연구는 없다.

폭력의 피해와 가해는 간접적으로 연결되어 있다. 환자 자신이 과거에 폭력 가해자였던 경우, 차후 피해를 입을 확률이 4\~5배 높다. 역으로 폭력을 당한 경우, 나중에 폭력을 가할 위험도 크게 높아진다.[@short2013a] 어린시절의 외상 경험도 비슷하다. 폭력 피해를 당한 정신병적 환자의 45%가 어린 시절 학대를 받은 것으로 조사되었다.[@Morgan2016]

### 가정 내 폭력

조현병 환자가 가족을 상대로 폭력을 행사할 위험보다, 가족 구성원이 환자에게 폭력을 가할 위험이 더 높다.[@labrum2020] 그럼에도 불구하고 전통적으로 남의 집안 사정에 개입하기를 꺼리는 이유도 있고, 환자를 돌보는 가족의 어려움에 더 공감하기 때문이기도 해서 치료진이 가정 내 폭력에 대해 묻기를 주저하는 경향이 있다.[@Rose2011] 치료진은 자연히 가족들의 말을 더 신뢰하기 때문에, 폭력 사건이 발생한 경우 환자가 그럴만한 짓을 했겠지 하고 믿어버린다.[@Feder2006] 게다가 가족을 가해자로 몰아버리면, 더 이상 환자를 돌볼 사람이 없어진다는 현실적 문제도 개입되어 있다.

하지만 소아/청소년의 경우와 마찬가지로 자기방어능력이 부족한 환자들은, 신고할 방법을 잘 모르거나, 폭력의 정도가 아주 심하지 않으면 신고를 꺼린다.[@short2013a] 따라서 폭력이 심각한지, 반복되었는지 등의 상황을 평가하여 필요하다고 생각되면, 환자를 대신하여 신고를 해주어야 할 경우도 발생한다.

### 폭력 피해의 영향

폭력을 당한 경험이 조현병 자체를 악화시키지는 않지만, 피해 경험이 있는 초발 정신병 환자들은 우울과 물질남용의 비율이 매우 높다. 관해 후에도 물질 사용과 타인에 대한 공격이 많은 경향을 보였다.[@Fisher2017] 이 밖에도 불안과 불쾌감, 사회적 위축 등을 낳으며[@Newman2010], 약물 순응도를 떨어뜨려 장기적 경과를 악화시킨다.[@Hodgins2009] 가정에서의 폭력 피해 경험은 노숙자로 전락하게 만들며, 이는 또 다시 폭력적 환경에 처할 위험을 높인다.[@Lam1998]

### 치료

폭력 피해를 당한 조현병 환자는 불안, 공포, 과각성 등의 증상을 겪을 수 있다. 이는 원래 갖고 있던 증상을 악화시켜, 무엇이 원래 증상이고 무엇이 새로 생긴 증상인지 구분하기 어렵게 한다. 급성적으로는 지지적인 정신치료와 함께 항불안제를 중심으로 한 약물 치료를 하여, 위기를 순조롭게 넘길 수 있도록 한다. 장기적으로는 증상을 줄이고 물질 남용을 방지하여, 환자 스스로 자신을 보호할 수 있는 능력을 키울 수 있어야 한다.[@Latalova2014] 인지행동치료를 통해 폭력 상황을 유발하는 언어나 행동을 교정하고, 생활 습관이나 주변 환경의 변화를 꾀한다.

## 맺음말

조현병 환자들이 가하는 폭력과 당하는 폭력은 서로 밀접하게 연관된다. 결국 피해자가 다시 가해자가 되고, 그 가해자가 다시 피해자가 되는 폭력의 악순환이 일어난다. 이러한 사슬을 끊기 위해서는 궁극적으로 조현병을 완치시켜야 하지만, 아직까지 조현병을 완치시킬 방도가 없기 때문에, 특히 폭력을 부를 수 있는 사고의 왜곡이나 인지적 미숙함, 환경적 위험인자를 조정해야 한다. 한국은 여전히 정신질환에 대한 낙인이 심하고, 환자 가족에 대한 사회적 지원이 부족하다.[@Hanzawa2013] 낙인과 차별이 짙게 배어있는 사회의 문화 그리고 그로 인한 구조적인 폭력은 회복을 저해하고, 폭력의 악순환을 조장한다. 환자의 얘기를 귀 기울여 듣고 공감하며 함께 임상적, 개인적 회복을 촉진해가되 낙인과 차별, 구조적인 폭력의 개선에 힘을 기울여야 할 것이다.

## References {.unnumbered}
