---
title: "조현병에서의 자살"
editor: visual
bibliography: References/19-01.bib
---

## 자살과 자해

모든 생명체 중 인간만이 자살을 행하는 지에 대해서는 논란이 있다.[^19-01-1] 그러나 인간은 삶의 고통을 감내하기보다는 죽기를 선택할 수 있고, 또 스스로 생명을 끊을 실질적인 능력도 있다. 물론 죽고 싶다고 반복적으로 말하는 사람이라도 그중 일부만이 자살 시도를 하며, 자살 시도 역시 대다수 경미한 자해 정도로 끝난다. 17개국 성인을 대상으로 한 조사에서 자살 사고/계획/시도의 평생유병률은 각각 9.2/3.1/2.7%였고[@Nock2008], 국내 조사에서는 각각 15.2/3.3/3.2%로 보고되었다.[@Jeon2010] 이처럼 자살사고를 갖는다고 해서 반드시 시도나 사망으로 이어지지는 않지만, 반복되는 자살사고와 시도는 결국 사망으로 이어질 위험이 높다.[@DeVylder2015]

[^19-01-1]: 일단 동물이 죽음에 대한 개념이 있는지도 확실하지 않다. 개나 돌고래, 혹은 코끼리가 스스로 목숨을 끊었다는 일화가 전해지고는 있지만, 이는 드문 사례일 뿐이며 인간의 감정이 투사되었을 가능성이 높다. 반면 일부 벌이나 개미 등은 집단을 지키기 위해 스스로의 목숨을 던지기도 한다.

<s>자해</s>[^19-01-2]는 1) 성공하지 못한 자살 시도, 2) 죽을 마음이 없는 순수한 자해, 그리고 3) 두 가지가 혼재된 경우를 모두 포괄한다. DSM-5는 향후 연구가 필요한 상태에 "비자살 자해행동(Non-Suicidal Self Injury, NSSI)"과 "자살행동장애(Suicidal Behavior Disorder, SBD)"를 포함시켰다. 자해를 한 사람의 15\~25%가 1년 이내에 같은 문제로 다시 병원을 찾고[@Owens2002; @Carroll2014], 처음에는 자살 의도가 없더라도 1\~3%는 결국 목숨을 잃는다.[@Zahl2004; @Cooper2005]

[^19-01-2]: **자해(self harm, self injury)**: 의도적으로 스스로의 신체에 해를 가하는 행동. Self harm은 보통 자살의도가 없이 치명적이지 않은 상해를 가하는 것을 의미하며, 반면 self injury, self mutilation 등은 자살의도와 상관없이 자기 몸을 상하게 하는 것을 의미한다. 쾌락을 위해서 상해를 가하는 masochism과 구분해야 하며, 발모광(trichotillomania)과 같은 강박행동도 자해라고 하지 않는다. 자해를 관심을 끌기 위한 행동 쯤으로 이해하기도 하지만, 그보다는 감정적 상처를 경감시키기 위한 방어기제로 보아야 한다.

자살/자해라고 하면 우울증을 가장 먼저 떠올리게 된다. 이는 다른 질환보다 우울증 환자가 워낙 많기 때문에 그렇게 비춰지는 것이다. 유럽과 미국 자료를 분석한 연구에서는 자살 사례의 30.2%가 우울증, 17.6%는 물질관련장애와 관련되었지만, 14.1%는 조현병 환자였다.[@Bertolote2004] 조현병 환자의 일반 인구 대비 자살 위험은 13.2배로서, 우울증의 12.3배, 인격장애의 8.1배, 물질사용장애의 4.4배, 불안장애의 4.1배보다 훨씬 높다.[@Too2019] 국내의 국민건강보험공단 자료를 분석한 연구에서도, 자살로 목숨을 잃을 위험을 가장 높이는 질환은 물질사용장애와 조현병이었으며, 우울증은 그 뒤를 따르고 있다.[@Kim2017] 게다가 조현병 환자의 자살 시도는 치명적일 때가 많기 때문에, 사망자의 비율은 상당히 높아진다.[@Chapman2015]

### 조현병 환자의 자살

조현병 환자가 평생에 한번 이상 자살을 시도할 빈도는 26.8%로 일반인구의 2.7%에 비해 10배 가량 높다.[@Lu2019] 물론 후송 서비스나 치료 시설이 열악했던 과거에 비해 사망률은 조금 낮아졌다. 1939년 조현병 환자 500명을 추적한 연구에서 11%가 자살로 사망했다고 보고되었으나[@rennie1939], 최근의 역학 조사에서 자살로 인한 사망률을 5% 내외로 추정된다.[@Hor2010; @Nordentoft2015] 혹자는 조현병 환자들이 인지 저하 혹은 음성 증상 때문에 치밀하게 자살을 준비하지 못한다고 하지만, 오히려 그 때문에 투신, 익사, 목매기와 같은 고전적이지만 치명적인 수단을 사용한다.[@Dutta2010; @nah2017; @Pan2021]

자살을 시도하는 시기는 아무래도 발병 초기일 때가 많다. 핀란드에서 자살 사례를 분석한 결과 71%는 발병 후 3년 이내에 자살하였다.[@Alaräisänen2009] 한편 아직 진단을 제대로 받지도 못한 채, 전구기에 자살로 사망하는 사례는 특히나 안타깝다. 초발 환자를 대상으로 전구기 동안에 느꼈던 자살 사고를 조사해보면, 66%의 환자가 자살 사고를, 49%와 18%는 각각 자해와 자살 시도를 해본적이 있는 것으로 나타났다.[@Taylor2015] 전구기를 포함하여 정신병의 치료받지 않은 기간(duration of untreated psychosis, DUP)은 특히 자살의 위험이 높은 시기이다.[@Barrett2010] 치료를 받지 못한 환자들은 왜 자신들이 고통받는지 결코 이해하지 못한 상태에서 죽음을 선택한다. DUP가 길면 이후에 치료를 받게 되더라도 여전히 자살률이 높게 유지된다.

탈원화가 자살에 미친 영향에 관해서는 논란이 있다. 사회복지 시스템이 잘 갖춰져 있는 북유럽에서는 탈원화와 함께 조현병 환자의 자살률이 감소한 것으로 나타났으나[@Nordentoft2004], 미국에서는 오히려 탈원화 이후 자살로 사망할 위험이 더 높아졌다.[@Hiroeh2001] 이는 준비없는 탈원화는 오히려 환자를 오갈데 없이 만들어 자살을 부추길 수 있다는 자성의 목소리로 이어졌다.[@Yoon2009]

## 자살 위험의 예측

### 위험 요인과 보호 요인

자살은 워낙 많은 요인들이 복합적으로 관여하므로, 아무리 위험 요인과 보호 요인을 따져본다 할 지라도, 한 개인의 실제 행위를 예측하는 것은 여전히 불가능하다.[@Franklin2017] 대신 특정 집단의 자살 위험을 예측하는 것은 좀더 용이하며, 이는 국가 차원에서 의료자원의 효율적 배치와, 예방 프로그램 운용 등 거시적 대책을 마련하는데 도움이 된다.

Roy와 Pompili[@Roy2009]는 조현병 환자의 자살 위험요인을 선행(distal) 요인과 근접(proximal) 요인으로 나누었다. 선행 요인은 유전적, 생물학적, 성격적, 발달적 특성을 포괄하여 스트레스에 대처하는 주된 방어전략을 결정하며, 근접 요인은 자살을 실제로 결심하는데 영향을 끼친다. 정신질환이 선행 요인인지 근접 요인인지에 대해서는 의견이 엇갈리는데, O'Connor 등[@OConnor2018]은 정신질환은 선행 요인으로서, 자살에 대한 소망을 품게 만들지만, 정작 행위를 저지르게 하는 것은 패배감, 굴욕감에 충동성이 더해진 결과라고 하였다. 이에 반해 다른 학자는 인지 저하 혹은 왜곡이 자살의 근접 요인이라고 본다.[@mishara2016] 자살을 실제로 행하려면 죽음에 대한 공포를 뛰어넘어야 하는데, 조현병 환자들은 통증에 대한 민감도가 떨어지거나 행동의 결과를 예측하기 힘들어하여, 앞뒤 안가리고 우선 저지르고 만다. 이러한 논란때문에 조현병 환자자의 자살을 우울감/절망감으로 이해해야 할 지, 판단력 저하/충동성으로 보아야할지 난감해진다.[@Ribeiro2015; @May2016]

정신질환 환자의 28\~73%는 소아기에 학대 받은 경험이 있다.[@Kim2006; @Bendall2008] 꼭 정신질환을 앓고 있지 않더라도 소아기 학대 경험은 자살 사고[@Rosenberg2007]와 행동[@Tousignant2011; @OHare2014]의 위험을 높이기 때문에, 학대를 받았던 조현병 환자라면 유달리 자살 위험이 높을 수 있다.[@Park2015] 자살의 위험을 가중시키는 외상의 유형에는 신체적, 성적 학대 등 심각한 학대 이외에도 정서적 학대를 포함한 모든 유형의 학대나 방치가 포함된다.[@Angelakis2020]

조현병 환자의 자살을 꼭 질병의 직접적인 결과라고 치부할 수는 없다. 환자들 역시 생활을 꾸려가기 위해 안간힘을 써야 한다. 가뜩이나 질병의 고통과 차별/낙인의 굴레 속에서 소득, 구직, 가족 내 역할 수행 등을 제대로 하지 못하는 환자들이라, 일반인보다 더 사회적/경제적 스트레스를 받는다. 이런 스트레스는 특히 40세 이하의 가장에게 더 심하다.[@Howarth2020] 애초에 직업을 가져본적이 없던 환자라면 모를까, 질병으로 인한 사회적 고립, 실직으로 인한 사회적 지위의 상실, 그리고 낮은 사회경제적 계층으로의 전락 등은 모두 자살 위험을 높인다.[@Sher2019] 이러한 요인들은 질병이 진전되거나 아예 나이를 먹어 중년기에 도달하면 훨씬 덜해진다.

반면 가족 등 사랑하는 사람이나 반려동물의 존재, 사회적 연결망이나 지지체계의 존재 그리고 도덕적, 종교적 신념 등 살아야 할 이유 등이 있으면 쉽사리 자살을 선택하기 어렵다. 또한 과거 어려운 난관을 성공적으로 헤쳐나온 경험이 있거나, 타인의 도움을 받는데 거리낌이 없었던 사람이었다면, 상황에 대한 해결책으로 자살을 떠올리지 않는다.[@Ryan2020]

그러나 동일한 요인이라도 개인 심리와 복잡하게 얽히면서 전혀 다른 결과를 낳기도 한다. 흔히 기독교는 자살을 용납하지 않기 때문에 보호 요인이라고 하지만, 원죄 개념과 결부된 죄책감이나, 상실했던 사람을 내세에서 만날 수 있다는 믿음 등은 오히려 자살을 부추긴다.[@Jongkind2019][^19-01-3]

[^19-01-3]: 내세(afterlife)에 대한 믿음은 꼭 기독교에만 국한된 것은 아니다. 고대 이집트로부터 그리이스/로마, 인도의 불교와 힌두교에 이르기까지 내세 혹은 윤회/환생(rebirth)에 대한 믿음은 인간 심리의 중요한 구성요소이다. 죽은 자가 다른 세상에서 삶을 이어가고 있다는 믿음은 살아남은 자들에게 희망을 주지만, 역으로 현실이 너무 각박하다고 느끼면 내세에 이르거나 다시 태어나고 싶다는 소망을 낳는다.

### 자살 시도의 예측 요인

그 무엇보다 자살 위험의 가장 중요한 예측 인자는 과거의 자살 시도 경험이다. 일반 인구에서 과거 한번이라도 자살을 시도했던 사람 중 2.3\~4%는 결국 자살로 사망하고[@Isometsä1998; @Bostwick2016], 자살로 사망한 사람의 2/3는 지난 1년 동안 자살을 시도했던 전력이 있다.[@Owens2002] 자살을 시도했던 환자가 다시 시도하여 사망할 위험은, 첫 시도 후 6개월[@Suokas2001] 또는 1년 이내[@Bostwick2016]에 가장 높지만, 이후에도 여전히 위험은 상승된 채로 지속된다.[@Suokas2001]

이러한 특징은 조현병 환자에게도 그대로 적용된다. 스웨덴에서 조사한 바에 따르면, 자살을 시도한 조현병 환자의 절반 가량이 첫 시도 후 1년 이내에 사망하였다. 조현병 환자의 재시도 위험은 기분장애 환자보다도 커서 위험비(hazard ratio)가 남자 4.1, 여자 3.5였다.[@Tidemalm2008] 또 다른 연구에서는 자살로 목숨을 잃은 남자의 78%, 여자의 89%가 과거 자살을 시도한 전력이 있었다.[@Carlborg2010] 따라서 조현병 환자가 자살을 시도하면, 적어도 향후 2년 정도는 재시도를 막기 위해 보다 집중적인 치료가 필요하다.[@Tidemalm2008]

자살을 행동으로 옮기는 사례의 60\~90%는, 막연한 자살 사고를 갖게 된 지 1년 내에 일어난다. 기분장애의 경우 자살 사고를 지닌다고 해도 실제 자살로 이어질 위험이 그리 높지 않으나, 조현병 환자가 자살 사고를 품게 되면 시도할 위험이 유달리 높아진다.[@DeVylder2015] 아마도 기분장애 환자는 중간중간 관해에 도달하면서 정상 생활로 돌아갈 희망을 품을 수 있지만, 대부분 만성 경과를 밟는 조현병은 그렇지 못하기 때문인 것 같다.[@Chapman2015] 마찬가지로 자해가 반복되면 결국 목숨을 잃을 위험이 크다.[@Olfson2016] 의도적 자해로 응급실을 방문한 환자 25명 중 1명은 5년 이내에 자살로 사망한다는 보고도 있다.[@Carroll2014]

### 자살에 영향을 미치는 요인들

#### 양성 증상

어떤 환청은 끊임없이 환자에게 자살을 강요하거나, 환자가 죽지 않으면 가족들이 피해를 입을 것이라며 협박을 한다.[@Hellerstein1987; @Wong2013] 또한 피해망상에 시달리는 환자가 보이지 않는 가해자에게 쫒겨 자살말고는 벗어날 방법이 없다고 느끼기도 한다.[@Kjelby2015; @Ventriglio2016; @Freeman2019; @Bornheimer2019] 일반 인구에서도, 정신병적 경험을 하고 나면 자살 위험이 높아진다. 메타분석에 따르면 정신병적 증상을 경험한 일반인은 대조군에 비해 자살 사고가 2.39배, 자살 시도가 3.15배, 자살로 인한 사망은 4.39배 높았다.[@Yates2019] 역으로 과대망상 혹은 지지적 환청은 자살빈도와 역의 상관관계를 보인다.[@grunebaum2001]

급성 발병 혹은 삽화와 삽화 간의 구분이 명확한 경우에는, 정신병적 증상에 시달렸던 경험을 잘 기억하지 못하는 환자들이 많다. 이에 비해 점진적 발병이나 삽화 간의 구분이 명확하지 않았던 환자들은, 양성 증상으로 고통받았던 기억이 마치 외상후 스트레스 장애 환자들처럼 깊게 자리잡는다. 이러한 기억은 재발에 대한 공포와 함께, "이런 경험을 계속 할 바에야 차라리 죽는 게 낫다"는 생각을 갖게 한다. 어떤 식으로든 관해에 도달할 수 있도록 치료하는 것은 질병 경과를 개선시키는 것 외에도, 자살률을 낮추는 효과가 있다.

#### 우울 증상

흔히들 진단 불문하고 자살로 이르는 과정의 최종공통경로는 우울증이라고 여긴다. 조현병 환자는 뚜렷한 이유없이 우울 증상을 동반하기도 하지만, 재발과 입원을 반복적으로 경험하고, 복용하는 약물의 용량이 늘어나면서, 회복에 대한 희망을 잃고 우울에 빠진다.[@Kasckow2011; @Coentre2017] 망상이나 환각같은 양성 증상때문에 자살한 사례라고 해도, 그 내용은 원래 마음 속에 품고 있던 우울이나 자기 비하적 사고를 반영할 수 있다.[@Kelleher2012; @Yates2019]

정신과 의사가 조현병 환자를 치료할 때는 환자에게 남아있는 건강한 자아와 치료 동맹을 맺으려 애쓰게 된다. 그러나 소위 정신병 후 우울증(post-psychotic depression)에 시달리는 것은 다름아닌 이러한 건강한 자아이다. 이 때문에 병식이 양호할수록 자살위험이 높아진다는 딜레마에 빠지게 된다.[@drake1984] 특히 고학력이며 병전 기능이 양호했을 때, 이런 식의 자살 위험이 높아진다. 병세가 깊지 않은 질병 초기에 자살률이 높은 것도 같은 맥락에서 이해되고 있다.[@Kuo2005; @Reutfors2009]

#### 음성 증상

의사들은 음성증상이 심한 결핍형 조현병(deficit schizophrenia) 환자들은 자살 위험이 낮을 것이라 믿는다.[@Fenton1997; @Loas2009] 이 환자들은 질병이 만성화되면 증상에 순응하거나, 혹은 증상때문에 몸부림칠 자아의 힘이 약해진다고 보는 것이다. 하지만 꼭 그렇게만 보기도 어렵다. Jahn 등[@Jahn2016]은 대표적 음성증상인 무의욕증과 무쾌감증이, 사회적 고립이나 빈약한 사회적 지지와 맞물려 자살을 유도한다고 보았다. 둔마된 정동과 자살률 사이에 상관관계가 보이기도 한다. 감정을 경험하는 폭이 좁아지고, 주위 사람들과 감정 반응이 어긋나기 시작하면, 사회적 위축, 자존감 저하, 스스로에 대한 부정적인 평가가 심해지면서 자살 위험을 높일 수 있다.[@Grigoriou2020]

#### 인지 증상 및 병식

인지 왜곡이 있다면 자신이 취한 행동의 결과를 제대로 예측하지 못할 수 있다. 또한 현 상황을 헤쳐나갈 대처 전략을 제대로 마련하지 못하기도 한다. 자살을 시도했던 조현병 환자들은 그렇지 않은 환자들에 비해 신경인지 기능이 저하되었다고 보고되었다.[@Yin2020; @Fernández-Sevillano2021] 특히 집행기능이 떨어지면 자살 시도의 위험을 높인다.[@Adan2017] 인지 기능 저하가 자살 행위의 치명률을 낮추기도 혹은 높이기도 할 것이라는 논란이 있지만, 자살에 성공한 사례에 대해서는 연구를 진행할 수가 없어 확인이 불가능하다.

병식과 자살의 관계는 한마디로 정의하기 어렵다. 병식이 낮은 환자들은 증상이 심하고, 재발 횟수가 많으며, 사회적/직업적 기능이 떨어지기 때문에 자살의 위험을 높인다. 반면 병식이 높으면 우울, 절망, 자기 낙인(self-stigma) 등 소위 낙담 증후군(demoralization syndrome)에 빠지기 쉽다.[@Drake1986]

초발 환자군에서는 병식이 높을수록 자살 시도가 많았다.[@Foley2008] 하지만 이러한 연관은 질병 초기에만 국한된다. 병식이 있는 환자가 몇 차례 재발의 고비를 겪어나가면, 오히려 대처 방안을 찾고 치료에 의지하면서 자살 위험이 감소하지만, 그렇지 못한 환자는 원망감과 자괴감에 빠지면서 자살을 선택한다.[@Ayesa-Arriola2014; @Barrett2015] 게다가 병식은 궁극적으로 질병 경과 및 예후에 커다란 영향을 끼치며, 치료가 잘된 환자가 자살률이 낮을 수 밖에 없다. 항정신병 약물을 사용한 환자가 사용하지 않은 환자에 비해 자살률이 낮은 것도 결국 같은 맥락이다.[@tiihonen2006]

한편 병식이 없더라도 치료에 순응하여 잘 따라오는 환자는 자살률이 낮다.[@Warriach2021] 치료에 순응한다는 것은 누군가를 신뢰하여 자신의 어려움을 그에게 맡긴다는 의미이며, 이는 애착관계가 양호한 건전한 성격구조를 갖고 있다는 증거이다. 이러한 성격구조는 치료 결과와는 관계없이 자살의 위험을 줄여준다.

#### 수면 장애

약물 과다 복용으로 자살을 시도한 환자 중 상당수는 오랫동안 불면으로 고통받았던 환자들이다.[@Pigeon2012; @Malik2014; @Bernert2015; @Liu2019] 이들은 무엇보다도 불면의 고통이 가장 컸다고 말하며, 결정적인 순간에 더 이상 깨어나고 싶지 않다며 과다 복용할 결심을 한다.

하지만 정말로 불면의 고통때문에 자살을 선택한 것인지, 자살 위험이 고조된 시기에 불면에 시달리는 것인지 분명하지 않다. 수면제라는 자살 수단이 옆에 있기 때문에 충동적으로 과다 복용했을 가능성도 있다. 따라서 불면이 직접적으로 자살의 위험을 높이는지는 확실하지 않다.[@Liu2020]

#### 물질 남용

조현병이 겹쳐 있든 그렇지 않든, 물질 사용 장애는 자살의 위험을 무려 7\~22배 높이며[@Murphy2020], 자살로 인한 사망위험을 10\~14배 높인다.[@Wilcox2004] 가장 문제가 되는 것은 역시 알코올이며, 대마초, 코카인 등 그 밖의 남용물질은 그다지 자살과는 연관이 없다. 오랜 알코올 남용은 건강을 악화시키는 것은 물론, 가족과의 불화나 해체, 도덕적 비난과 죄책감 등을 부채질하며, 술에 취한 상태에서 판단력을 잃고 충동성을 못이겨 자살을 행한다. 또한 물질 남용 환자들은 애초에 미래에 대한 계획이 없고 충동적/감정적이어서, 심각한 자살 의도가 없이도 자해 행동을 쉽게 저지른다.[@Borges2000]

조현병 환자가 물질 남용을 하는 경우에는 자살 위험이 더욱 높아진다.[@Hawton2005; @Østergaard2017] 조현병 환자 중에 알코올을 비롯한 물질 남용 환자의 비율이 높은데다가, 남용 문제가 겹친 환자는 그렇지 않은 환자에 비해 자살로 인한 사망 위험이 3배 가량 높다. 심지어 현재 중독에서 벗어난 상태라도, 과거 남용 경험이 있으면 자살률이 높아진다.[@Østergaard2017]

흡연 역시 주요 정신장애 환자의 자살 위험을 높이며, 심지어 흡연량과 자살 위험이 양의 상관관계를 보이기도 한다.[@breslau2005] Sankaranarayanan 등[@Sankaranarayanan2015]이 체계적 문헌 고찰을 한 바에 따르면, 흡연은 자살 경향(자살 사고, 시도, 사망을 통털어)을 2배 이상 높였다. 이에 대해 학자들은 흡연이 뇌내 세로토닌 농도를 저하시켜 충동적, 공격적 성향을 강화하거나[@Malone2003], 안와전두피질의 두께를 감소시켜 부정적인 감정을 제대로 처리하지 못하게 한다고 설명한다.[@Kühn2010] 그러나 조현병 환자들은 흔히 증상은 물론 약물 부작용에 대처하기 위해 흡연에 의지하므로, 금연을 유도한다고 해서 자살률이 낮아지리라고 기대하기는 어렵다.[@wu2017]

#### 치료 관련 요인

적극적으로 조현병을 치료해야 질병 경과를 개선시키고, 자살 위험을 낮출 수 있다는 것은 누구도 부인할 수 없다. 그러나 어떤 식으로든 환자와 잘 맞지 않는 치료는 오히려 역효과를 낼 수도 있다. 자의반 타의반으로 어렵게 치료 과정에 들어선 환자는 의사가 자신들의 고통을 없애주길 바라나, 의사는 조현병이라는 더 큰 문제를 해결하기 위해서 환자 자신은 더 큰 고통을 견뎌내야 한다고 강조한다. 이 과정에서 떨어져 나간 환자들은 희망을 잃고 더 자살에 매달릴 수 있다. 예를 들어 전기경련 치료를 받았던 환자들의 향후 자살 사망률을 조사한 바에 따르면, 전기 치료를 중단에 그만 둔 환자들은 오히려 치료를 받지 않은 환자보다도 훨씬 자살률이 높았다.[@rhee2021] 또한 많은 환자들이 퇴원 직후에 목숨을 끊는 현상 역시 비슷하게 설명할 수 있다.[@Chung2017] 영국에서 진행된 연구에 따르면 퇴원 28일 이내의 자살 위험은, 그 이후 48주에 비교해서 남자는 7.1배, 여자는 3.0배 높았다.[@Qin2005] 아마도 재입원에 대한 낙담, 비자발적 입원에 대한 분노, 치료결과에 대한 실망 등이 환자들을 궁지로 몰아넣은 것 같다. 의사의 입장에서 급성 증상이 어느 정도 조절되었다면 치료 성공으로 보겠지만, 환자 입장에서는 여전히 일상 생활을 이어나가기 힘들다면 치료는 실패한 것이다. 이 때 느끼는 좌절은 환자를 자살로 몰고 갈 수 있다.

혹자는 심한 약물 부작용이 환자를 자살로 몰고간다고 주장하지만, 부작용 자체가 직접 자살률을 높인다고 보기는 어렵다.[@mihanovic2010] 다만 좌불안석만은 예외이다.[@Cem2001; @Seemüller2012] 좌불안석으로 인한 고통은 환자를 자살로 몰고가기에 충분하며, 일찌기 1983년에 데포 주사제를 맞고 좌불안석에 시달리던 환자가 자살한 증례가 처음 발표된 이후[@Shear1983], 수많은 유사 사례가 보고되었다.[@Cheng2013; @Kalniunas2021] 좌불안석에 대한 우려는 비정형 약물 도입 후 잦아드는 듯 싶다가, 아리피프라졸때문에 다시 고개를 들었다. 아리피프라졸은 특히 치료 초기에 낮은 용량에서도 진전, 불안감, 신경과민을 일으킬 수 있다.[@Basu2006] 이는 환자에게 커다란 불편감을 가져다주며 심하면 자살 사고에까지 이르게 한다.[@padder2006; @pondé2015] 물론 거시적으로 보았을 때 아리피프라졸 복용이 자살 위험을 높이지는 않는다는 것은 분명하지만, 치료 초기에는 여전히 문제가 될 수 있음을 명심해야 한다.[@Ulcickas2010; @montastruc2019]

이런 우려에도 불구하고 약물 부작용이 자살 위험을 높인다고 우려할 필요는 없는 것 같다. Reutfors 등[@Reutfors2016]에 따르면 오히려 추체외로 증상이 심했던 환자들이 자살률이 더 낮았다. 부작용에 시달렸다는 것은 치료에 순응했다는 뜻이며, 의사와 함께 부작용을 하나하나 해결해나가는 것을 치료에 진전이 있었다고 받아들였을 수도 있다. 지연성 운동장애와 같은 치명적인 부작용이 그다지 자살과 연관이 없는 것도 비슷한 맥락에서 바라볼 수 있다.

### 생물학적 원인

조현병 환자의 자살은 대체로 증상의 직접적인 영향 혹은 고통받는 정상적 자아의 최종 선택 정도로 해석되어왔지만, 환자의 생물학적 특성 자체가 자살을 부추길 수도 있다. 자살 시도 및 사망의 40\~50% 정도는 유전적 영향으로 해석할 수 있다.[@Statham1998; @McGuffin2010] 조현병 환자의 일차 친족 내에는 자살로 사망한 사례가 많았다.[@Trémeau2005] 부모 중 한명이 조현병 환자일때, 자식의 자살 위험이 높다는 보고도 있다.[@Webb2007; @Mittendorfer-Rutz2008; @Stenager2008] 이러한 증거들을 유전적 요인 보다는 양육 환경의 차이로 볼 수도 있으나, 최근 각광받는 후생적 변이(epigenetic variation) 개념으로 본다면, 유전적 소인과 환경적 배경이 어울려 생물학적 변화를 가져온다고 이해할 수 있다.[@Bani-Fatemi2018; @bani-fatemi2020]

구조적 뇌영상학이 인기를 끌던 시기에는 자살과 뇌의 구조적 특징 사이의 관계가 집중적으로 연구되었다. 자살을 시도한 조현병 환자는 대조군에 비해 양측 측두엽, 좌상측 두정엽, 시상, 뇌섬엽, 측두엽 일부 등의 회백질 용적이 감소되어 있고, 특히 자살 방법이 치명적인 경우 죄측 설회(lingual gyrus)와 설상엽(cuneus)의 회백질 용적 감소이 감소되어 있다고 보고되었다.[@Giakoumatos2013] 유사한 연구를 종합하면, 대부분 전전두엽 부위의 피질의 손실과 편도를 비롯한 피질 하 구조물의 용적 증가가 자살과 연결되는 것 같다. 이는 감정 조절의 곤란과, 고위 인지기능 및 충동조절 능력의 상실이 자살 위험을 높인다는 앞서의 논의와 연결된다.[@Girgis2020]

------------------------------------------------------------------------

## References {.unnumbered}
