---
title: "자살위험의 평가와 치료"
editor: visual
bibliography: References/19-02.bib
---

## 자살 위험의 평가

### 개요

의사가 환자의 자살 사고를 미리 감지했다 하더라도, 정작 자살을 막을만한 뾰족한 방도가 마땅치 않다. 상황이 다급하다면 보호입원을 고려할 수 있으나, 자살 사고가 있다는 것만으로 보호입원을 시키기는 어렵다. 하지만 자살을 마음먹은 환자에게, 따뜻한 말한마디를 건네거나 약물을 조절하여, 순간의 마음을 돌릴 수 있었던 경우도 비일비재하다.

환자들 역시 순간순간 마음이 바뀌고 스스로의 마음을 알지 못할진데, 제 3자가 자살의 위험을 예측하여 이를 막아준다는 것은 전제부터 잘못된 과제이다. 게다가 연구의 난점으로 인하여 자살위험도를 그럴듯하게 평가하는 모형은 만들어지지 못하였으며[@Chan2016], 최첨단 기계 학습, 인공 지능을 이용한 예측 모형 역시 별로 나아진 성과를 보이지 못하고 있다.[@Barak-Corren2017; @balbuena2022][^19-02-1]

[^19-02-1]: 인공지능을 이용하여 자살이 예측하고 예방하는 것은 최근 각광받는 전산화 정신건강(digital mental health)의 핵심과제이다. 대상자의 SNS 기록, 스마트폰 통화 내역을 실시간으로 분석하여 자살 위험을 평가하는 기법이 개발되고 있지만, 개인정보와 사생활 침해 문제를 어떻게 해결할 지가 관건이다. [@dhotman2020]

그럼에도 불구하고 자살 위험을 평가하는 과정 자체가 환자의 생명을 무엇보다 소중히 여긴다는 메시지를 전달해주며, 치료동맹을 구축하는 출발점이 될 수 있다. 그렇기에 자살 위험의 평가는 환자의 삶에 대한 진지한 관심과 더불어 이루어져야하며, 그렇지 못한 기계적이고 형식적인 평가는 오히려 환자를 소외시킬 수 있다.[@Fowler2012]

### 평가 척도

막 자살 시도를 하여 응급실에 방문한 환자의 자살 위험도를 평가하기 위해 평가 척도를 들고 나타난 의사의 모습을 상상해보자. 환자는 죽음의 문턱을 간신히 넘은 상태이고, 죽지 않았다는 것을 다행스럽게 생각해야 할 지, 분노해야할 지에 대해서도 마음 속에 혼란이 심하다. 이런 와중에 의사가 평가표에 적힌 문항을 기계적으로 묻기 시작한다면 이를 곱게 받아들일 환자는 거의 없을 것이다. 그러나 다른 시각에서 보면, 평가표에 적혀있는 문항 하나하나가 환자가 지금 사로잡혀 있거나 오래 시달려온 문제를 다루고 있을 가능성이 높다. 따스하고 섬세한 정신건강 전문가가 천천히 항목들을 묻기 시작한다면, 그것만으로도 향후 자살 행동을 반복할 위험이 감소할 수 있다.[@Kapur2013]

#### 평가 척도의 종류

진단을 불문하고 가장 널리 사용되는 평가 척도는 1) Beck Scale for Suicide Ideation (BSI)[@Beck1988]과 2) Columbia--Suicide Severity Rating Scale (C-SSRS)[@Posner2011]이다. 그 밖에 조현병에 특화된 평가 척도로는 Schizophrenia Suicide Risk Scale (SSRS)[@Taiminen2001],과 International Suicide Prevention Trial (InterSePT) Scale for Suicidal Thinking (ISST)[@Lindenmayer2003]이 있다.

BSI는 원래 숙련된 임상가가 반구조화된 면접을 통해 평가하는 Scale for Suicidal Ideation (SSI)의 자가보고 형태이다. 자살 소망과 사고를 평가하는 19항목과 시도 당시 죽기를 원한 정도를 평가하는 두 문항을 합쳐 21문항으로 되어 있다. 이 척도는 자살 위험이 상당히 높은 환자에게만 유용하다는 한계가 있다.[@Andreotti2020]

한편 2012년 미국 FDA가 당시 급증하는 청소년의 자살 문제를 연구하기 위한 전국적 역학조사에 C-SSRS를 사용하기로 결정하면서, C-SSRS가 연구와 임상 모두에서 표준 척도로 자리잡았다.[@Posner2011; @giddens2014] C-SSRS는 18항목의 척도로 (1) 자살사고의 심각성, (2) 자살 사고의 강도, (3) 자살 행동, (4) 자살 시도의 치명성의 네 가지 하위 범주를 측정한다. 1년간 추적한 연구에서 C-SSRS는 민감도 67\~69%, 특이도 65\~76%를 보여 상당히 우수한 척도임이 입증되었다.[@Mundt2013; @Madan2016] 그러나 선별검사로는 유용하지만, 자살 위험을 꼼꼼하고 다면적으로 평가하기에는 역부족이라는 평가를 받는다.[@salvi2019]

## 자살 예방과 정신사회적 치료

### 개요

앞장에 기술한 자살에 영향을 미치는 다양한 영향을 고려할 때, 조현병 치료와는 독립적으로 자살을 막기 위해 다음과 같은 치료 전략을 세울 수 있다.[@Pompili2008; @Roy2009; @Kasckow2011]

1)  위험요인, 특히 중재 가능한 위험요인을 제거한다.

2)  조현병 치료를 충실히 받도록 하여, 양성 증상 및 우울, 초조, 충동성 등 동반된 증상을 최소화한다.

3)  절망감을 덜고 희망을 가지도록 한다.

4)  물질남용 등 공존질환을 치료한다.

5)  주변 환경에서 자살에 사용할 수 있는 수단을 제거한다.

6)  가족 등 주변 사람들이 급박한 자살 위험을 인지하고 말릴 수 있도록 교육한다.

자살이라는 비극적 결말을 막고자 하는 정신과 의사라면, 의사로서의 통상적인 역할과 넘어서야 한다. 자살은 환자가 자신의 고통을 표현하는 수단인데, 의사는 이 고통이 쉽사리 해결되지 않는다는 것을 누구보다도 잘 알며, 그렇기 때문에 환자보다도 먼저 희망과 관심을 잃는 경우가 비일비재하다. 이러한 비관적 상황에서도 희망을 잃지 않도록 환자를 붙잡아 주려면, 의사 자신의 심리적 문제를 해결하는 것이 급선무이다.

자살을 막으려면, 꼭 자살이나 질병과 관련된 문제가 아닐 지라도, 환자의 욕구를 포괄적으로 파악하여 최대한 충족시킬 방도를 마련해야 한다. 동시에 모든 자살을 막을 수 없음을 환자를 둘러싼 가족이나 치료진에게 이해시킴으로써, 이들의 무력감이나 죄책감을 줄이고, 성취 가능한 치료 목표에 치중하도록 격려해야 한다.

### 급성 위기의 중재

당장 심한 자살 사고를 보이는 환자라면 여유있는 상담보다 물리적인 개입을 해야할 지도 모른다. 자살 사고가 정신병적 증상이나 이해범위를 넘어선 우울감 때문인지, 아니면 충분히 공감할 수 있는 절망감 때문인지 구분하는 것이 먼저이다. 전자의 경우라면 자살 사고가 언제건 곧바로 행동화될 수 있음을 명심하여, 안전을 보장할 수 있는 환경을 확보해야 한다.[@Yamaguchi2015]

만약 입원을 시키지 않고 집으로 돌려보낼 경우, 보호, 관찰의 주체와 책임, 감독 수준, 위험한 상황에서의 대처 방법에 대해 명확한 지침을 제공해야 한다. 보통 보호자에게 "절대로 혼자있게 두지 마세요"라고 말하는 정도로 주의 의무를 다했다고 여기기 쉬우나, 보호자들은 어디까지 환자의 행동을 간섭해야 하는 지 주저하기 쉽다. 만약 보호자가 혼란에 빠져 있거나, 책임을 지울 정도로 믿을 만하지 못하다면 입원 치료를 하는 수 밖에 없다. 입원의 목적은 무엇보다 안전한 환경을 보장하는 것이요, 자살의 수단을 없앤 상태에서 환자가 스스로 자살 의지를 포기하도록 기다려주는 것이다.

장기간의 입원이 자살 위험을 낮추는가에 대해서는 논란의 여지가 많지만, 급성 위기를 넘기기 위해서는 입원이 최상의 방법이다. 자살 사고는 수일 내지 수 주일 지속되며, 자살 시도 후 1달 내에 재시도할 위험이 상당히 높다. 따라서 입원 기간이 너무 짧아서는 제대로 위험 시기를 넘겼다고 안심할 수 없다. 정신병적 증상이나 자살 사고와 연관된 고통이 심하면 항불안제 혹은 항정신병 약물을 충분히 투여한다. 전기경련 치료는 약물보다 빠르게 자살 사고와 행동을 감소시킬 수 있으므로, 자살 사고가 줄어들지 않는 경우에는 적극 고려할 필요가 있다.[@Fink2014; @kellner2016]

환자가 충분히 자신의 감정을 토로하고, 자살을 결심할만큼 힘든 상황이었다는 것을 치료자가 공감하여, 어느 정도 감정이 해소되면 구체적인 자살 의지가 줄어들기 시작한다. 환자가 더 이상 자살 의사가 없다고 하면 퇴원을 결정할 수 있지만, 환자가 의도적으로 거짓말을 할 수도 있고, 또 퇴원 후에는 이전과 다를 바 없는 환경에 노출되기 때문에 퇴원 후 얼마 안 되어 재시도하는 경우가 많은 편이다.

국가 혹은 민간단체가 운영하는 자살 상담 센터도 급성 위기를 중재하는데 큰 역할을 한다. 우리나라에서는 보건복지부의 지원 아래 한국생명존중희망재단이 전국 각지에 자살예방센터를 두어 24시간 출동 체제로 운영하고 있다. 전화 상담을 물론 실제로 현장으로 출동하기도 하며, 자살자의 심리부검을 진행하기도 한다. 인프라를 갖추기 위해 부단히 노력한 결과 체계는 갖추어졌으나, 아직은 예산과 인력의 한계로 위기 대응과 현장 출동이 충분히 이루어지지 못하고 있다.[@kim2019] 게다가 자살 모형이 대부분 우울증에 맞춰져 있어, 조현병 환자의 자살 위기 대응에 대해서는 경험이 부족한 편이다.

### 만성 자살 사고의 치료

#### 치료진과 가족에 대한 교육 및 지지

자살 환자를 일상적으로 접해야 하는 치료진은 물론 조현병 환자를 둔 가족들도 임박한 자살 위험을 감지할 수 있도록 교육을 받아야 한다. 자살에 대한 근거없는 속설들은 가족들이 환자의 고통을 무시하고, 자살 위험을 간과하도록 오도하기도 한다. 자살 위험이 높은 환자들은 주위 사람들을 신뢰하지 못하고, 의심이 많으며, 치료에 대해 비판적이거나 무리한 요구를 하며 깎아내리는 경우가 많기 때문에 치료진은 물론 가족들도 무의식적으로 외면하는 경우가 있다. 주변으로부터 거절당한 환자는 더더욱 자신의 고통을 표현하기 위해 극단적인 수단을 선택할 수 있다. 이러한 프로세스를 이해하고 감내하도록 돕는 것도 교육의 한 목적이다.[@Roy2009; @Sher2019]

사정이 이렇다보니, 자살 시도를 하거나 자살에 성공한 환자의 가족들은 환자를 비난하거나 극심한 죄책감에 사로잡히기 쉽다. 자살자와 접한 사람들은 애도, 책임감, 죄책감, 버림받은 느낌, 분노 등을 포함한 어렵고 복잡한 감정을 갖기 쉽고, 그들 자신이 낙인이나 사회적 고립을 경험하기도 한다.[@pompili2007; @talyoung2012] 지인이 1년 이내에 자살한 사람들은 정신질환을 갖고 있지 않더라도, 자살 사고, 계획, 시도의 위험이 각각 1.6 / 2.9 / 3.7배 높다고 보고된 바 있다.[@Crosby2002] 따라서 자살자 가족들의 경험에 대해 주의를 기울이고 자조모임 등을 소개하며, 심각한 경우 약물이나 정신치료를 제공하는 등 사후 예방(postvention)을 시행해야 할 필요가 있다.[@pompili2007]

#### 정신사회적 치료

가장 널리 쓰이는 정신치료로는 1) 인지행동 치료(CBT)와 2) <s>변증법적 행동치료(DBT)[^19-02-2]</s>가 있다. 자해에 대한 정신사회적 치료 연구를 메타분석했을 때 CBT, DBT, <s>정신화 중심 치료(MBT)[^19-02-3]</s>, 집단기반 감정조절 정신치료 등은 자해의 반복을 줄일 수 있었지만, 정신역동적 정신치료, 사례관리, 응급실에서의 단기 카운셀링 등의 효과는 근거가 불충분하였다.[@witt2021] 기법에 따라 치료 성과가 조금씩 다른 것 같지만, 각각의 환자에게 맞는 치료가 다른 법이라, 어떤 치료를 선택하느냐가 더 중요하다.

[^19-02-2]: **변증법적 행동치료(dialectical behaviour therapy)**: 변증법적 행동치료는 환자 스스로 자신을 비적응적 행동으로 이끄는 촉발요인(trigger)을 알고, 촉발요인에 대하여 어떠한 대처기술을 사용하여 생각, 감정, 행동의 연쇄 과정을 끊을 수 있을 지 방안을 마련하도록 한다. 원래 워싱턴대학교의 심리학자인 Marsha Linehan이 경계성 인격장애 환자의 정서조절(emotional regulation)과 인지조절(cognitive regulation) 능력을 배양하기 위하여 개발한 것으로, 전통적 인지치료에 불교적 수용개념을 접목시켰다.

[^19-02-3]: **정신화 중심 치료(mentalisation-based therapy)**: 정신화 개념(mentalization)은 영국의 정신과 의사인 Peter Fonagy가 1990년대부터 강조해온 마음이론 중의 한 개념이다. 자극과 이에 대한 반응 사이에는, 그런 상태에 도달하기 위해 거치는 마음의 흐름이 있으며, 이. 흐름은 과거의 애착관계에서부터 비롯되어 삶의 경험을 통해 형성된다. 이 흐름이 왜곡되고 고착되면, 자극에 대해 부적절한 반응이 반복되는데, 이 흐름을 찾아내어 고쳐나가는 것이 치료의 과제이다.

많은 정신사회적 자살 치료는 Schematic Appraisal Model of Suicide (SAMS)[@Johnson2008]나 Integrated Motivational Volitional Model[@OConnor2018]과 같은 자살심리 모형을 토대로 구성된다. 두 모형은 공통적으로, 감정 조절이 어렵고 사회적 지지를 받지 못하는 환자가, 대인관계의 어려움을 해소하지 못하여 패배감으로 궁지에 몰릴 때 자살을 시도한다고 본다. 하지만 이런 모형은 정신질환의 유무나 종류와는 무관하게 공통된 것이기 때문에, 조현병 환자에게 맞도록 일반 치료의 원칙이 변형될 필요가 있다. 한 가지 예로 Tarrier 등[@tarrier2013; @Tarrier2014]은 SAMS를 기반으로 부정적인 정보 처리 오류에 초점을 두고 Cognitive Behavioural Suicide Prevention in psychosis protocol (CBSPp)을 개발하였다.

연구자들은 각자 나름대로의 철학과 경험을 바탕으로 각양각색의 기법을 고안해내지만, 비판적인 연구자들은 아무리 잘 설계된 프로그램이라고 해도, 양호한 의사-환자 관계를 기반으로 한 통상적인 지지 치료와 뭐가 차이가 나는지 의심스러워한다. 또한 대다수의 프로그램이 자살 사고의 감소를 평가 지표로 삼고 있기 때문에, 실제 사망률을 얼마나 줄일 수 있을 지는 미지수이다.[@Donker2013]

## 약물 및 기타 생물학적 치료

### 항정신병 약물

자살의 원인이 조절되지 않는 양성 증상 때문이라면, 이견없이 좀더 적극적인 치료를 행하는 것이 필요하다.[@Hawton2015; @Witt2021] 죽으라는 환청이나, 조종망상, 죄업망상 등은 매우 심각한 자살의 위험 징후 들이다.[@Wong2013; @Cassidy2018; @freeman2019] 어떤 환자들은 타인을 해치라는 목소리에 저항하기 위해, 혹은 가족들의 생명을 지키기 위해 스스로 목숨을 끊는다. 이런 사례들을 예방하려면 매우 공격적인 치료가 필요하지만, 사실 자살을 시도하는 많은 환자들은 치료를 자의로 중단하거나 약물 순응도가 떨어지는 환자들이다.[@Virkkunen1976; @Tiihonen2006; @Haukka2008] 2002\~2013년 국민건강보험공단 자료를 조사한 연구에서도 30일 이상 약물치료를 중단한 조현병 환자들은, 치료를 유지한 환자에 비해 자살 위험이 4.7배 높았다.[@choi2020] 순응도가 낮다는 것은 두가지로 해석할 수 있다. 첫째는 병식이 없어 자신에게 아무 문제가 없다고 믿는 환자들이다. 물론 이들 중에도 자신을 믿어주지 않는 사회를 원망하며 자살을 행하는 환자들이 있지만, 대다수는 자살에 이를 정도로 절망감에 빠지지 않는다. 둘째는 치료를 받아보았지만 효과도 없고 부작용만 심하여 치료에 대한 기대와 희망을 잃게 된 환자들이다. 처음부터 치료에 순응하지 않았던 환자보다, 어설픈 치료로 효과를 보지 못한 환자들이 더 자살의 위험이 높다. 따라서 환자로 하여금 희망의 끈을 놓지 않도록 하는 것이 무엇보다 중요하다.

클로자핀이 사용되기 전까지는 항정신병 약물은 그저 정신병적 증상에서 비롯된 고통을 줄임으로써 자살 위험을 낮출 것이라는 정도로 생각되었다. 그러나 클로자핀이 증상의 치료와는 별개로 직접 자살률은 낮춘다는 증거가 발견되면서, 항정신병 약물이 자살을 유도하는 생물학적 기전에 직접 영향을 미칠 수도 있으리라는 기대가 높아졌다.

일찌기 1997년에 Walker 등[@Walker1997]은 클로자핀 복용 환자 67,072 명을 분석하여, 중도에 클로자핀을 중단한 군에 비해 유지한 환자군의 자살률이 83% 감소하였다고 보고하였다. 이에 아이디어를 얻어 Meltzer 등[@meltzer2003]은 <s>International Suicide Prevention Trial (InterSePT)</s>[^19-02-4] 연구를 통해, 클로자핀과 올란자핀의 자살 예방 효과를 비교해보았다. 2년간의 추적 조사 결과, 두 군에서 각각 34명과 55명이 자살을 시도하였으며, 이는 통계적으로 유의한 차이임이 드러났다. Tiihonen 등[@Tiihonen2009]이 조현병 환자 66,881명의 사망률과 그 원인을 추적한 조사에서도 클로자핀 사용군의 사망 빈도가 가장 낮았다. 가장 최근에 발표된 메타분석에서는 10여개의 항정신병 약물의 자살 방지 효과를 분석해보았는데, 유일하게 클로자핀 만이 위험비를 0.64\~0.66 정도로 낮추는 것으로 나타났다.[@Taipale2021]

[^19-02-4]: **International Suicide Prevention Trial (InterSePT)**: Herbert Meltzer의 주도하에, 클로자핀이 조현병 및 조현정동장애를 앓고 있는 자살 고위험군 환자에 있어서 자살위험을 낮추는 효과가 있는지 평가한 연구이다. 고위험군이란 지난 3년동안 자살시도를 했거나, 자살위험때문에 입원한 과거력을 의미했으며, 이때 자살이란 분명히 스스로를 해할 의도가 담긴 행동에 국한시켰다. 11개국 67개 센터에서 등록된 980명의 연구참여자를 2년간 추적조사했으며, 비교약물은 클로자핀과 올란자핀이었다.

클로자핀이 왜 자살률을 낮추는 지는 밝혀져 있지 않다. 5-HT 신호전달계에 미치는 영향이 자살 위험은 물론 충동성을 낮추는 효과가 있으리라고 짐작되고 있지만, 아직 일관된 결론이 나오지 못하고 있다. 연구자들은 약물 외적 요인도 상당한 영향을 끼칠 것으로 짐작한다. 주기적인 혈액검사 등을 통해 의료진과 더 긴밀한 관계를 맺는다는 것은 예전부터 잘 알려져 있다. 또한 치료 실패를 거듭했던 환자들이 클로자핀을 통해 새로운 희망을 품게 되었다는 점, 만성 환자가 많기 때문에 이미 자살 위험이 가장 높은 시기를 지나갔다는 점, 의사의 특별한 관심과 보살핌의 대상이 된다는 점도 영향을 미칠 것이다.[[@Tondo2006; @De2010] 이에 비해 클로자핀을 제외한 다른 비정형 약물들은 별다른 자살 방지 효과를 보이지 못하며, 약물 서로 간의 차이도 관찰되지 않는다.[@Roy2009; @Kasckow2011]

낮은 순응도와 자살 위험 사이의 높은 상관관계 때문에, 장기지속형 주사제가 새로운 대안으로 떠올랐다. [[@Forsman2019] Pompili 등[@pompili2007] 역시 장기지속형 주사제가 임상 경과를 안정시켜 정신적 고통을 줄이고 사회적/직업적 기능을 향상시킴으로써, 미래에 대한 희망을 꺼뜨리지 않게 도울 수 있을 것이라고 하였다. 이를 뒷받침하듯 동일한 약물이라도 비정형 장기지속형 주사제가 경구제에 비해 자살 시도를 낮춘다고 보고되었다.[@Díaz-Fernández2020; @Huang2021] 하지만 아직 축적된 자료가 많지 않아 추후 연구가 필요하다.

### 항우울제

만약 우울증 환자가 자살 사고를 보인다면 당연히 항우울제 사용을 먼저 고려할 것이다. 조현병 환자에 있어서도 자살의 최종 공통경로는 우울감일 때가 많으므로, 항우울제를 선택해볼 수 있다. 그런데 문제는 애초에 우울증 환자에서조차, 항우울제가 자살 위험을 낮추는 지 확실하지 않다는 것이다. 일부 항우울제는 오히려 초조, 불안을 가중시켜 자살 위험을 높이기도 한다.[@Hengartner2021]

항우울제가 조현병 환자의 자살 위험을 줄일 수 있는지에 대해서는 연구된 바조차 거의 없다. 아무래도 모든 임상 시험이 윤리적 이유에서 과거에 자살 시도를 했거나 현재 자살 사고를 갖고 있는 환자를 배제하기 때문일 것이다. 1,611명의 조현병 환자를 평균 4.3년간 추적한 조사에서는, 현재 항정신병 약물을 사용하고 있는 군이 자살률이 현저히 낮은 것으로 나타났지만, 항우울제 사용 여부는 유의한 차이를 보이지 않았다.[@Haukka2008] 이 주제에 대한 거의 유일한 임상 시험으로서, 기존의 항정신병 약물에 citalopram을 병용한 군과 그렇지 않은 군을 비교하는 연구가 행해졌는데, 병용 군에서 연구 시작 시점에 품었던 자살사고가 상당히 감소되었다고 하였다.[@Zisook2010] 그러나 자살 사고가 줄었다고 해서 실제 자살 행동이 줄어드는 것은 아니기때문에 섣부른 결론을 내리기는 어렵다.

최근 우울증 환자의 자살 사고를 줄이는데 탁월한 효과를 보인다고 선전되고 있는 케타민 역시 향후 연구가 진행될 필요가 있는 약물이다. Grunebaum 등[@grunebaum2018]은 자살 사고를 품은 주요 우울증 환자에게 케타민 정맥주사를 행하고, 대조군인 미다졸람 주사군과 비교하였다. 그 결과 하루만에 55%의 환자에서 자살 사고가 급감하였다. 우리나라에서도 2020년 말, 비강 스프레이형 케타민 제제인 스프라바토™는 급성 자살 사고가 있는 우울증 환자에게 식약청 허가를 획득하였다.

2018년에는 정신병 후 우울증을 앓고 있던 조현병 환자에게 케타민을 사용하여 정신증상의 악화없이 우울 정서와 자살 사고를 호전시켰다는 증례가 보고되었다.[@bartova2018] 그러나 애초에 NMDA 수용체 차단은 정신병적 증상을 인공적으로 일으키는 주요한 방법이기도 하며, 조현병의 글루타메이트 가설의 토대가 되기도 하였다.[@coyle1996] 정상인을 대상으로 케타민을 투여했을 때도 다양한 정신병적 증상을 일으킬 위험이 매우 높기 때문에, 조현병 환자에게 사용한다는 것은 그만큼의 위험을 각오해야한다는 뜻이 될 것이다.[@beck2020]

### 리튬 및 기분조절제

양극성 장애 환자인 경우 리튬을 장기간 사용하면, 위약이나 다른 기분조절제에 비해 확실히 자살 위험을 낮추는 효과가 있다.[@Cipriani2013; @Del2020; @Nabi2022] 심지어 식수에 섞인 소량의 리튬이 지역사회 주민의 자살률을 낮춘다는 생태학적 연구들도 있다.[@Tondo2018] 자살로 이끄는 요인 중에는 우울감 외에도 감정 기복과 충동성이 중요한 역할을 하기 때문에, 공격성과 충동성에 대한 리튬의 효과가 자살 위험을 낮출 가능성이 충분히 높다.[@Smith2017] Baldessarini 등[@baldessarini2006]이 33,000 명 가량의 양극성 장애 환자 자료를 분석한 바에 따르면, 리튬 사용 환자는 다른 약물로 치료받은 환자에 비해 자살 위험이 1/5에 불과하였다.

이와는 대조적으로 기분조절제로 사용되는 다른 항경련제의 자살 예방 효과는 입증되지 않았다. 오히려 항경련제를 사용하는 환자군은 리튬을 사용한 환자군에 비해 자살 위험이 2.86배 높았다.[@Baldessarini2009] 물론 이러한 연구는 모두 양극성 장애 환자를 대상으로 이루어졌기 때문에, 조현병 환자에게 적용하기는 힘들지만 충동성 때문에 자살 위험이 높아지는 환자라면 리튬을 고려해볼 수 있다.

### 전기경련 치료

성인의 주요 우울장애에 대한 CANMAT 가이드라인은 급성 자살사고에 대한 1차 치료로 전기경련 치료를 추천하고 있다.[@Milev2016] 아무래도 약물치료로는 유의한 효과 발현을 기대하는데 3\~4주 이상의 기간이 필요한데 비해, 전기경련 치료는 보다 신속하게 효과가 나타나기 때문일 것이다.[@Kobeissi2011] 그러나 자살 위험을 줄이는 효과가 우울 증상의 개선과 독립적인지는 확인되지 않았다. 게다가 전기경련 치료의 효과는 오래 지속되지 않기 때문에, 고조된 자살 위기를 넘겼다 해도 언제 또 자살 사고에 사로잡힐 지 모를 노릇이다.

사실상 전기경련 치료는 조현병 환자에게는 잘 사용되지 않는다. 우울증에 대한 효과는 확실한데 비해, 조현병에 대한 효과는 분명하지 않으며, 그나마 치료저항성을 보이거나 약물 치료를 감내하지 못하는 일부 환자에게만 사용되는 실정이다. 따라서 조현병 환자의 자살 위험을 낮추는 효과를 가늠할만한 자료가 턱없이 부족하다. 싱가폴에서 행해진 한 연구에서는 치료저항성 때문에 전기경련 치료를 받은 113명의 조현병 환자에 대하여 자살 사고의 호전 정도를 조사하였다.[@tor2020] 이중 22명이 치료 전부터 자살 사고를 표현하고 있었는데, 세명을 제외하고는 모두 치료 후 자살 사고가 호전되었다. 자살 사고를 매개하는 중요한 요인은 역시 우울감의 호전이었다.

## References {.unnumbered}
