project:
  type: book

book:
  title: "조현병의 약물치료 Vol.2"
  author: "Anselm Jeong"
  lang: ko
  repo-url: https://github.com/AnselmJeong/Psychopharmacology
  repo-actions: [edit]
  sharing: [twitter]
  cover-image: images/cover.jpg
  date: "2022. 5. 5."
  chapters:
    - index.qmd
    - part: "항정신병 약물의 작용기전"
      chapters:
        - 06-01.qmd
        - 06-02.qmd
        - 06-03.qmd
        - 06-04.qmd
        - 06-05.qmd
    - part: "항정신병 약물의 종류"
      chapters:
        - 08-01.qmd
        - 08-02.qmd
        - 08-03.qmd
    - part: "약물 치료의 일반 원칙"
      chapters:
        - 08-04.qmd
        - 08-05.qmd
        - 08-06.qmd
        - 08-07.qmd
        
    - part: "약물 치료의 실제"
      chapters:
        - 10-01.qmd
        - 10-02.qmd
        - 10-03.qmd
    
      
csl: plos.csl



format:
  html:
    theme: 
      light: yeti
      dark: darkly
    mainfont: "Noto Serif KR"
    css: styles.css
    footnotes-hover: false
    anchor-sections: true
    toc: true
    toc-depth: 3
    number-depth: 4
    reference-location: margin
    number-sections: true
    
  pdf:
    documentclass: scrreprt
    #mainfont: "Noto Serif KR"
    fontfamily: "Noto Serif KR"
    colorlinks: true
    cite-method: biblatex
    include-in-header: 
      text:
        \usepackage{kotex}

editor: visual

